### ISSUE TITLE
Connection to gnome-keyring fails on Debian Buster

### ISSUE THREAD

**Issue by Silvanoc** [bit-team/backintime#1000]
I've been having similar issues to those reported in #509, #534 and #587: BIT cannot connect to the GNOME keyring and I'm observing pretty much the same issues being reported in the mentioned tickets.

After some debugging I've been able to diagnose the root-cause:

1. [common/tools.py](https://github.com/bit-team/backintime/blob/f7f28b50b7decd8f7e8666c654c33fda387f2ea0/common/tools.py#L819) is comparing (the keyring backend that could be successfully loaded previously) with the one reported by `python-keyring`
1. In my case `python-keyring` returns the [`chainer` backend](https://github.com/jaraco/keyring/blob/master/keyring/backends/chainer.py) and therefore doesn't match the previous test.

If I add an additional test, it works (for me):
```
elif isinstance(keyring.get_keyring(), keyring.backends.chainer.ChainerBackend):
    found_keyring = False
    for chained_backend in keyring.get_keyring().backends:                                    
        for backend in backends:                                        
            if isinstance(chained_backend, backend):                    
                logger.debug("Found appropriate keyring'{}'".format(str(backend)))              
                found_keyring = True                               
    if found_keyring:                                                        
        return True
```

**Comment by KsmoinO** [comment]
I had the same issue and solved it by creating this file ~/.config/python_keyring/keyringrc.cfg

```
[backend]
default-keyring=keyring.backends.SecretService.Keyring
```

**Comment by buhtzz** [comment]
@Silvanoc There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug, maybe Distro, External (Keyring)

**Comment by Silvanoc** [comment]
I don't have Buster anymore, therefore I cannot easily reproduce it.

**Comment by aryoda** [comment]
I think I understand the problem now when re-visiting this issue and reading this sentence:

> In my case python-keyring returns the [chainer backend](https://github.com/jaraco/keyring/blob/master/keyring/backends/chainer.py) and therefore doesn't match the previous test.

This is related to #1330 which explains the problem in more detail and proposes a solution...
