### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5' when opening BackInTime GUI (Pop!_OS 19,04)

### ISSUE THREAD

**Issue by MostHated** [bit-team/backintime#1004]
Hello all,
    I went to open BackInTime yesterday and when it didn't open I pulled up the logs and noticed the following messages:

```
5/22/19 8:43 AM	pkexec	mosthated: Executing command [USER=root] [TTY=unknown] [CWD=/home/mosthated] [COMMAND=/usr/bin/backintime-qt]
5/22/19 8:43 AM	albert.desktop	Traceback (most recent call last):
5/22/19 8:43 AM	albert.desktop	  File "/usr/share/backintime/qt/app.py", line 35, in <module>
5/22/19 8:43 AM	albert.desktop	    import qttools
5/22/19 8:43 AM	albert.desktop	  File "/usr/share/backintime/qt/qttools.py", line 21, in <module>
5/22/19 8:43 AM	albert.desktop	    from PyQt5.QtGui import (QFont, QColor, QKeySequence)
5/22/19 8:43 AM	albert.desktop	ModuleNotFoundError: No module named 'PyQt5'
```

I tried to search around to see if I could find a fix, but unfortunately came up with nothing so far.

I have tried installing/remmoving/reinstalling the following things (and I believe a few others that were pip related) as per different threads I saw of possible fixes.

pyqt5 pyqt qt qtpy python3-pyqt5 

Running ```backintime --debug``` or ```backintime --version``` comes back with the following, though I have installed python3-dbus.mainloop.pyqt5 (python3-dbus.mainloop.pyqt5 is already the newest version (5.12.1+dfsg-1)) and python3-dbus (python3-dbus is already the newest version (1.2.8-3))

```
~ » backintime --debug                                                                                               mosthated@mosthated-pc
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 51, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

The only thing I can think of that might have caused this was, I wanted a better system file manager so I installed Dolphin, but since I am using Pop!_OS and it is Gnome based, the coloring of Dolphin was light and it would not follow suit with my theme. I searched and saw people said you can use, I believe it was called, qt4-config or qt4-settings, something along those lines. So I installed that but it didn't help, and I saw one that was named similar for qt5, I tried that as well (this was about 2 days ago), but it didn't do anything either. 

I didn't think much of it at the time, until I went to open BackInTime and saw this error. I don't know if installing those things is what caused it, but I have since removed them and taken the steps above, but I still can't open it. 

Does anyone have any recommendations?
Thanks,
-MH

**Comment by hannes101** [comment]
Did you use the package management of the distribution and if so on which Ubuntu version is PopOS based.

**Comment by MostHated** [comment]
Hello,  thanks for the reply.  It's 19.04, and I tried multiple versions from multiple sources of back in time,  including the  newest qt5 from the ppa. Since making this part all errors are saying I am missing dbus when I am not.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The report is quite old.

Can you still reproduce the Issue with the current version of your operating system?

**Comment by MostHated** [comment]
No, it was nearly 2 years ago. I have since found another solution.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Then please close the Issue.
