### ISSUE TITLE
[SOLVED] "Permission denied" error upon changing backup destination

### ISSUE THREAD

**Issue by Enjymon** [bit-team/backintime#1008]
Hello,

After setting up a backup profile to back up on a 1 TB external HD, I wanted to change the backup destination to a new 4 TB HD. So I went to settings and changed the backup folder:
- from /media/alex/Elements (the 1 TB HD)
- to /media/alex/My Passport (the 4 TB HD)

But when clicking on OK to validate the change, I get the following error:
"com.ubuntu.DeviceDriver.PermissionDeniedByPolicy: net.launchpad.backintime.UdevRuleSave"

What is wrong in my setting? Is it the space character in 'My Passport' that causes the issue? If so, I unfortunately cannot edit the path to escape the character in the Settings dialog... Is it something else in my procedure?

Thanks for the help.

**Comment by Enjymon** [comment]
Solution found.
One needs to first copy the backup directory as explained in the FAQ:
[How to move snapshots to a new hard drive](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive)

**Comment by aryoda** [comment]
Related to #1009 

And since solved: Could someone close this issue please?
