### ISSUE TITLE
Correction to the FAQ

### ISSUE THREAD

**Issue by Enjymon** [bit-team/backintime#1009]
I just wanted to mention a possible error in the FAQ.

In the section [How to move snapshots to a new hard drive](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive), the command line indicated in solution 3:
`cd /DESTINATION; tar cf - /SOURCE/* | tar xf -`
might have to be replaced by:
`cd /SOURCE; tar cf - * | tar -C /DESTINATION/ -xf -`

Otherwise one might go from
`/SOURCE/backintime/<computer>/<user>/<#>/*`
to
`/DESTINATION/SOURCE/backintime/<computer>/<user>/<#>/*`
instead of
`/DESTINATION/backintime/<computer>/<user>/<#>/*`

**Comment by buhtz** [comment]
Agree and [fixed](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive).
