### ISSUE TITLE
Can't access folder inside a backup as default user

### ISSUE THREAD

**Issue by sojusnik** [bit-team/backintime#1012]
After I've done a fresh full backup of an external drive (let's call it `Daten`) to another freshly formatted external drive (`Daten Backup`), I don't have permission to open my user's folder within this backup (`/media/sojusnik/Backup Daten/backintime/mir/sojusnik/2/last_snapshot/backup/media/sojusnik`) in Gnome's Files (Nautilus). Only after entering my root password, I'm able to see its content. This is problematic, because I want to see how much space is left on the drive, when I'm using Files as the default user, in my case `sojusnik`.

If I manually change the user and the group of the above mentioned folder (`sudo chown -c $USER:$USER "/media/sojusnik/Backup Daten/backintime/mir/sojusnik/2/last_snapshot/backup/media/sojusnik"`) then they are reverted to `root:root` after a new backup.

I assume that after upgrading to BIT 1.2.0 something has changed, because I've done backups with older versions, with the same settings and drives, and this folder was accessible. Only after formatting `Daten Backup`, to do a complete fresh backup, this folder got other permissions.

I also backup the SSD of my notebook to another external drive (`Backup Notebook`) and there the user's folder (`/media/sojusnik/Backup Notebook/backintime/mir/sojusnik/1/last_snapshot/backup/home/sojusnik`) is also accessible.

The permissions of all relevant folders look like this:

```
/media/sojusnik/Backup Daten/backintime/mir/sojusnik/2/last_snapshot/backup/media$ ls -halv
insgesamt 12K
drwxr-xr-x 3 root root 4,0K Mär 29 12:54 .
drwxr-xr-x 3 root root 4,0K Jun 26 09:26 ..
drwxr-x--- 3 root root 4,0K Jun 26 11:08 sojusnik

/media/sojusnik/Backup Notebook/backintime/mir/sojusnik/1/last_snapshot/backup/home$ ls -halv
insgesamt 12K
drwxr-xr-x  3 root     root     4,0K Mär 29 12:31 .
drwxr-xr-x  5 root     root     4,0K Jun 26 09:26 ..
drwxr-xr-x 19 sojusnik sojusnik 4,0K Jun 26 09:24 sojusnik

/media/sojusnik$ ls -halv
insgesamt 20K
drwxr-x---+ 5 root     root     4,0K Jun 26 11:08  .
drwxr-xr-x  3 root     root     4,0K Mär 29 12:54  ..
drwx------  3 sojusnik sojusnik 4,0K Jun 26 11:53 'Backup Daten'
drwx------  3 sojusnik sojusnik 4,0K Jun 22 21:02 'Backup Notebook'
drwxr-xr-x  4 sojusnik sojusnik 4,0K Jun 26 11:52  Daten
```

Using BIT 1.2.0 (as root) and Ubuntu 18.10.

Every help is appreciated!

**Comment by Enjymon** [comment]
I think you shouldn't use Back In Time as root. In fact it is generally a bad practice to run GUI programs as root. I made that mistake myself in the past as a new Linux user.

I have also read some posts mentioning troubles about dealing with former backups when upgrading to BIT 1.2 (see [here](https://github.com/bit-team/backintime/issues/988)).

Maybe in your case the best is to start anew:
(i) delete the backups made with BIT 1.1.x,
(ii) uninstall completely BIT (chose 'complete suppression' in Synaptic),
(iii) check that you are the owner of all the files and folders in your home directory (run `find ~ -user root`), 
(iv) reinstall BIT 1.2 and (v) run it as non-root to set your backup profiles again.

**Comment by sojusnik** [comment]
Did you note that both of my external drives contain non-root files? So if I'm doing a backup of one freshly formatted external drive `Daten` to another freshly formatted one `Backup Daten`, then BiT creates there a folder which I can't access as a normal user, only as root, as described more detailed before.

Surprisingly, I don't have any problems when backing up my notebook's drive to another external drive (= I can read the user's folder as the default system user), even if the notebook contains root files. In my first case (external to external drive), the user's folder was newly created and in the second case (notebook to external drive) it already existed for several years. So I suspect that something had changed after the BiT 1.2.0 release. But is this a bug or a feature? Maybe the BiT developer could comment on this.

Usually I would agree to not use apps as root, but in my case I also need to back up some files from my root partition (and also automatically restore them afterwards with the same permissions). Is that somehow possible with the non-root version of BiT?

**Comment by sojusnik** [comment]
@Germar Am I misinterpreting something or is this really a bug?

**Comment by sojusnik** [comment]
Enabling "keep ACLs" in the advanced settings did the trick!

One of my folders had a `+` sign (see first post) – an extended permission by an access-control list (ACL).
