### ISSUE TITLE
backup speeds

### ISSUE THREAD

**Issue by BobBorges** [bit-team/backintime#1026]
Is there any way to control the speed of a backup? Currently, I have a blazing fast backup speed of 246kB/s on a USB3 drive...491 hours to back up the current state. I'm afraid my system might overheat. Just kidding, but seriously, can I force it to speed up somehow? 

version 1.1.12

**Comment by buhtzz** [comment]
@BobBorges There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, Support

**Comment by BobBorges** [comment]
Hi, It's relevant in the sense that the problem was never resolved. It's
been so long that I forgot what this Comment was even about. I gave up and
wrote my own shell scripts for backup.

**Comment by emtiu** [comment]
Thanks for reporting back. Since you're no longer using backintime and we can't diagnose this remotely, I'm closing the Issue. Feel free to re-open if you try again and run into the same problem.
