### ISSUE TITLE
How well does backintime work on Mac OS X?

### ISSUE THREAD

**Issue by pengyu** [bit-team/backintime#1029]
I run into problems in using Time Machine on Mac OS X. For some reason, it takes many days to backup (the HD is only < 500GB). Therefore, I'd like to consider backintime. Can backintime replace Time Machine in the sense that it generates backups that be used to restore the whole system just like Time Machine? Thanks.

**Comment by Germar** [comment]
Sorry I never tried to run BiT on Mac OS X nor did I hear from someone else trying.
But I know there are some parts in BiT which will only work on Linux by design. It would be possible to port BiT to OS X, but that would be quite some work. I have neither a Mac nor time for this.
