### ISSUE TITLE
Delete default profile

### ISSUE THREAD

**Issue by barkingbandicoot** [bit-team/backintime#1032]
I set a profile then wished to delete it.
Remove option is greyed out.

The only solution I found was to uninstall the app, delete existing files and reinstall.

**Comment by buhtzz** [comment]
@barkingbandicoot There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Was it the only existing profile ("main profile")? There is now way to delete all profiles. One have to remain.

Tag: Support, Feedback, Feature

I suggest not only to "gray out" the button but add a tooltip to it or a message box behind it and inform the user about the case. I read this question multiple times.

**Comment by buhtz** [comment]
I'm closing this as a duplicate of #1371
