### ISSUE TITLE
Can't restore database file.

### ISSUE THREAD

**Issue by rtevans01** [bit-team/backintime#1033]
On my PC, I use TimeShift to backup my system files and BackInTime for my user files. A few days ago, I ran into a problem with the Joplin notes app. One of my notes encrypted itself for no reason. I tried disabling and renabling encryption with the same password I used before but nothing changed. So I gave BackInTime a go and my note was unencrypted at first but after a few minutes the note was encrypted again. I tried deleting both the .config app data files and the sync target files and then restoring them, but nothing changed. I also closed Syncthing to make sure my notes weren't being synced from another device. I tried restoring from older snapshots and nothing changed.

I then resorted to restoring my entire home directory to the day prior but for whatever reason that messed up my Firefox browser. uBlock and Dark Reader stopped working. In fact, uBlock prevented me from browsing entirely. Websites just kept loading to infinity. Restoring the .mozilla config folder didn't work. Finally, I refreshed Firefox and that fixed it. Unfortunately, Joplin was unchanged after restoring the home directory. 

I noticed all the snapshot .config folders for Joplin had a program file dated to the current day called "window-state-prod.json". I tried deleting it and restoring the .config folder without it but still nothing.

I know this doesn't make sense but I even tried restoring my system with TimeShift as last ditch effort in the hopes it would fix something I overlooked. Nothing changed.

I had a theory maybe the .config and sync location folders were replaced by the current folders somehow because of the prompt message about backing up files before restoring them. However, I noticed the database.sqlite files in the snapshot .config folders were a smaller size compared to the one in my current .config folder, which I thought was promising. On a different note, I also noticed the database is the same size for all the snapshots including the ones made yesterday and today. Could this mean they're all the same database regardless of the date? I tried restoring the database file to a separate location and then pasting it over the current database but no luck.

Tried running BackInTime from a live USB drive to see what would happen but I wasn't able to get to recognize the snapshots in the backup location. 

Is BackInTime malfunctioning or am I doing something wrong here? I hope it's the latter because I really want to recover my notes :( FYI, I used the root version only. 

Any help would be appreciated. I'm using running BackInTime version 1.1.12 on Linux Mint 19.2. Thanks.

**Comment by aryoda** [comment]
> So I gave BackInTime a go and my note was unencrypted at first but after a few minutes the note was encrypted again.

This indicates that the restore with BiT did work but it could probably be a bug in the Joplin Notes App or even worse, a virus on your computer...

Could you solve your restore problem?

**Comment by xCapRx** [comment]
This was a long time ago. I don't remember but IIRC, I changed the ownership permissions in my home folder files to myself and that fixed the problem. I use Joplin Cloud now.

**Comment by aryoda** [comment]
Thanks for your reply and the solution hint!

Is it OK to close the issue (you could do it yourself)?

**Comment by rtevans01** [comment]
Thanks. I'm closing this issue.
