### ISSUE TITLE
Exclude /swapfile by default

### ISSUE THREAD

**Issue by chrisgraham** [bit-team/backintime#1035]
This is a default on my Ubuntu install, and I think definitely should be excluded in some way by default, and referenced in the suggestion list of what to exclude. Otherwise you're backing up a huge always-changing file.

(I realize that swap partitions are better - I have my reasons for not using them on this system)

**Comment by buhtzz** [comment]
@chrisgraham There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution? Thanks for your report.

Tag: Feature, Medium

**Comment by chrisgraham** [comment]
It's trivial to work around once you know it's an issue. This is more for product feedback, and something very quickly resolved.

**Comment by emtiu** [comment]
Thanks, it's a good suggestion. I'm wondering how many distros offer the creation of a swapfile on install, and whether `/swapfile` is universally the default location. From a quick search, it seems to be more of a loose convention found in several howto guides.

Still, it would be a sensible default exclusion, though more for the root user's than regular users' profiles.

**Comment by buhtz** [comment]
It's quite easy to solve.

https://github.com/bit-team/backintime/blob/675c8b4b58208e0a282d2f25371df81c556afd49/common/config.py#L132-L135

We can just add `'/swapfile'` into that list.

Agreed? I would take that.
