### ISSUE TITLE
FileSystem compatibility

### ISSUE THREAD

**Issue by tissy9491** [bit-team/backintime#1036]
Is backintime compatible with btrfs w/o subvolumes enabled?

**Comment by emtiu** [comment]
I'm not sure I understand the question. backintime does _not_ use any btrfs features (like btrfs snapshots).

backintime creates a directory for each snapshot, and unchanged files are hardlinked between snapshots. This will work on btrfs just the same as it does on ext4, but you won't be taking advantage of btrfs features.

Feel free to re-open this Issue if my answer doesn't help :)
