### ISSUE TITLE
Amazon Glacier Support

### ISSUE THREAD

**Issue by davidhealey** [bit-team/backintime#1037]
Is it possible to backup to glacier?

**Comment by peaolo** [comment]
I didn't try, but if you can access the filesystem where Glacier stores your data, I think yes. Exactly I don't know if Glacier grants you filesystem direct access. Here's a link to the official guide, where they explain how to mount (and mount on reboot) the Elastic FileSystem, which I guess any Amazon service relies onto.
https://docs.aws.amazon.com/en_us/efs/latest/ug/mounting-fs.html

Cheers

**Comment by emtiu** [comment]
What @peaolo said: You can back up to pretty much anywhere you can mount, but performance may not be great for exotic remote filesystems. I'm closing this Issue, but feel free to re-open if you have more specific suggestions or would like to discuss further :)
