### ISSUE TITLE
Combine two settings profiles into one

### ISSUE THREAD

**Issue by ndstate** [bit-team/backintime#1043]
Hi,

Is there a way to combine two back in time profiles into one?

Thank you.

**Comment by emtiu** [comment]
Hi, this functionality does not exist, but we can keep this as a feature request :)

**Comment by buhtz** [comment]
Dear @ndstate ,

thanks for your report. About our late reply please read about the [project status](https://github.com/bit-team/backintime/tree/dev#maintenance-status).

Can you describe your use case in more details please?
And how is it useful?

**Comment by buhtz** [comment]
Dear @ndstate ,

can you please describe your wished feature a bit more? For me it is not clear how it should look like and why it is useful for someone. You could describe it as a use case.

**Comment by buhtz** [comment]
I don't see a value in that feature. If @ndstate can't provide a convincing use-case I'll close the issue.
