### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by deisi** [bit-team/backintime#1045]
Hey, would it be possible to provide a flatpak package of backintime? I could provide an initial manifest file as a starting point if desired.

**Comment by buhtz** [comment]
We haven't decided yet in the team how to treat such package formats.

No matter that I'm part of the maintaining team, now I express only **my own personal opinion** about it.

My diplomatic side would say we support every person who want to create and publish a flatpack package of BIT or any other alternative packaging format. We can work together. But I would like to keep that "in official" and farway from the upstream repo. This also includes Issues and Support questions from users using such packages.
It is the same with packages published by Distributions. We (upstream) don't create them and even bug- and support-tickets should go to the distro's own ticket system first.

When you are willing to create such a package, great.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen if you want to add something. Let us know if we can be of assistance to you when creating a Flatpak. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
