### ISSUE TITLE
Restore all files of particular snapshot from command line

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1046]
How to restore recursively from commandline?

**Comment by buhtzz** [comment]
@lamyergeier There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

What do you mean with "recursively restore"?

Please have a look at `man backintime-cli` or `man backintime`. You can run backintime on commandline.

Tag: Feedback, Support

**Comment by emtiu** [comment]
The manpage explains how to use `backintime restore` for this purpose. To restore recursively, just give a directory as the path.

Closing this Issue.
