### ISSUE TITLE
Udev schedule not working with automount

### ISSUE THREAD

**Issue by RazielleS** [bit-team/backintime#1048]
When using an fstab entry like
```
UUID=70063286-6105-4853-80a8-72c27845dc40       /mnt/backup     ext4            rw,relatime,noauto,x-systemd.automount,x-systemd.idle-timeout=5m,user   0 0
```
it is not possible to use the udev schedule because I get a `Couldn't find UUID for "/mnt/backup/backintime/Soulreaver/raziel/1"`

The main reason seems to be, that `mountArgs(path)` in `tools.py` does only return the arguments of the first line in `/etc/mtab`.
When in fact using automount is creating two lines inside `mtab`:
```
systemd-1 /mnt/backup autofs rw,relatime,fd=39,pgrp=1,timeout=300,minproto=5,maxproto=5,direct,pipe_ino=30401780 0 0
/dev/sdf1 /mnt/backup ext4 rw,nosuid,nodev,noexec,relatime 0 0
```

So a solution for this may be to first access the path to trigger automount, and then use the second line of mtab, if one exists.

I'm not really experienced with python, so I can't test this right now...but I will gladly help with debugging and testing.

**Comment by buhtzz** [comment]
@RazielleS There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Bug, Low

Seems like a bug to me. I remember the relevant part of the code. But never used automount and have to investigate this further.

@RazielleS I have never used automount like you did. Can you help me please and give me a short step by step howto how to set this up? I need to reproduce that problem.

**Comment by buhtz** [comment]
Dear Silvia,
your bug report is quit old, also my request of additional information.

Can you give us some more information to reproduce the problem?

Otherwise we need to close this Issue.

**Comment by RazielleS** [comment]
Hello @buhtz 

In this case I'll close the issue. I do not use this setup anymore and currently have no way to reproduce the issue.

Thank you for checking.

**Comment by buhtz** [comment]
Grützi Silvia,
looking at your website you seem to be a pro.
What kind of backup solution are you using now?

**Comment by RazielleS** [comment]
I am currently using Duplicati which automatically creates encrypted off-site backups each night.
But I am still looking for a good local backup solution. So I might give backintime another another try at some point.
