### ISSUE TITLE
Question: Can I preserve the n most recent snapshots?

### ISSUE THREAD

**Issue by tjabzer** [bit-team/backintime#1049]
It seems the programmed snapshot remove paradigm focuses strictly on time in some way. Is there a way to configure backintime to preserve the n most recent snapshots and delete any that are older in sequence than n?

**Comment by buhtzz** [comment]
@emtiu I remember this discussion from another issue but couldn't find it. Did we closed it?

Tag: Feature, Discussion

**Comment by emtiu** [comment]
Closing in favor of #1303.
