### ISSUE TITLE
Add Back in Time to the standard Ubuntu/Deb repos?

### ISSUE THREAD

**Issue by EternityForest** [bit-team/backintime#1050]
There's a lot of new linux users scared off by the command line.  Normally, we just tell them to use Kubuntu or such, and they don't need to use the CLI at all.

But as far as I can tell, there are no good dedicated backup utilities available in the standard repos, and not really much else at all besides BiT that's all that great.

It seems like getting into the standard repos would be a pretty reasonable goal, especially when it's already an established and trusted project.

**Comment by 68420948** [comment]
Backintime is available in Debian Bullseye/Testing. The GUI is packaged as [backintime-qt](https://packages.debian.org/search?keywords=backintime-qt).

**Comment by buhtzz** [comment]
Today BIT is available in the Ubuntu universe as a Community supported package.
I don't understand why Ubuntu refuse to use Debian backintime package in Ubuntu Core.

Please take this to the discussion lists and package maintainers of your Distro. Please link your discussions here so we can keep track on that.

Tag: Distro, Infrastructure

Close.
