### ISSUE TITLE
Scheduled backup to external drive should ask to connect drive

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#1054]
Hi,

can users already be asked to connect the drive before doing a scheduled backup to an external drive or should this be done via a user-callback using case `7) #Mount drives` with a custom wait dialogue?

**Comment by buhtzz** [comment]
No feedback from "ghost" account.

Tag: Feature, Low, Discussion

Would be a (nice) feature but not much users using it. I vote for close.

**Comment by emtiu** [comment]
If the drive isn't available, a desktop notification should appear (with an invitation to connect the drive within 30 seconds).
