### ISSUE TITLE
Very slow operation - Manjaro Linux (XFCE)

### ISSUE THREAD

**Issue by leebut** [bit-team/backintime#1055]
Hello,

Back in Time has been running very slowly, sometimes slower than 100kB/s.
I am running version 1.2.1 on Manjaro Linux.

SYSTEM:
Ryzen 5 2600 CPU
16GB Ram
ASUS Prime B450-k M'board

**Comment by timbo-lino** [comment]
Same here (manjaro KDE)
On Fedora I needed to go back to 1.1.24 to get it working

**Comment by agmartin2** [comment]
This may be the same as #988 (Version 1.2.0 works very slow). Seems caused by a change in the way BiT deals with permissions, groups and ownerships.

**Comment by timbo-lino** [comment]
Right now automatic backups seem to work normally. 

They are in a good size and are finished in a good time. Not that fast as 1.1.24 but I can live with it.

**Comment by emtiu** [comment]
Closing as duplicate of #988.
