### ISSUE TITLE
(enhancement) Include pattern to include files with a given extension

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#106]
I think it would be very interesting to be able to create a pattern to select all the files with a given extension, starting from folder and recursively down all its folder. For instance, I want to back up all of my *.conf files inside /etc to keep track of configuration changes.

---

Imported from Launchpad using lp2gh.
- date created: 2011-01-11T20:59:34Z
- owner: txelu70
- the launchpad url was https://bugs.launchpad.net/bugs/701662

**Comment by Germar** [comment]
(by danleweb)
Actually this is more like add an include pattern.

**Comment by Germar** [comment]
(by fabrizio-marana)
Actually, I want to backup my videos directory, but not the avi files. (basically: subtitles, posters, anything except the huge movie files), so I've set to include /home/user, exclude /home/user/Videos/*.avi.

The rsync command line in sysmon shows an exclude for /home/user/Videos/*.avi, but still backs them up... (changed it now to exlude /home/user/Videos/ which excludes everything and is fine as a temporary solution as I'll copy the other files in the init-callback)

**Comment by Germar** [comment]
(by germar)
As Dan pointed out in #1 this bug is about include pattern. Which is still not possible in BIT.

But you are looking for an exclude pattern. Adding '/home/user/Videos/**/*.avi' to exclude will do the trick.

With next major version 1.1.0 BIT can also exclude files by size.

**Comment by buhtz** [comment]
Isn't all this possible with current BIT? Close?

**Comment by Germar** [comment]
Nope, include pattern is not possible and won't ever be possible because of the way BiT uses in-/excludes
