### ISSUE TITLE
Restore a folder

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1060]
I am new to linux. 
And I am looking for a good backup program. As I consider to use your program, some questions occurred and I allow me to ask them. Would appreciate some answers:

I have a folder "MyFiles". In this folder there are two files: "File1" and "File2"

When I make a backup at 
2020-01-01 from the folder "MyFiles", then in this Backup are the files "File1" and "File2"

On the 2020-01-02 I delete "File1" in my Linux system, because I do not longer need it.
On the 2020-01-03 I make again a Bckup from the folder "MyFiles".
On the 2020-01-04 I delete by mistake the folder "MyFiles" in my Linux system.
On the 2020-01-05 I restore the backup from 2020-01-03 (my second backup). What will now be in the folder "MyFiles" after the backup? "File1" and "File2" or only "File2" ?

Thank you.

**Comment by daveTheOldCoder** [comment]
The answer is "only File2".
