### ISSUE TITLE
backing up virtual machines

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1061]
Is it true that BackInTime is especially well suited for backing up virtual machines, because when my Image from the virtual machine has changed a little bit, then the next snapshot does not save the entire image file again. Right?

**Comment by buhtzz** [comment]
@Golddouble Thanks for asking. There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Your assumption is not correct. BIT only see one file and doesn't take care that it is an image with a filesystem inside. If the image changes the whole image files is used for a new backup.

Close.

**Comment by Golddouble** [comment]
As this question is answered now, I am satisfied. Thank you. 

(So Vorta is the better choice for making a backup of the image of a virtual machine. But BIT looks nevertheless interesting, when I want to backup some single files from root. For this neither LuckyBackup nor Vorta seems to be the right choice.)

**Comment by aryoda** [comment]
@Golddouble  I think we can close this issue since your question was answered. OK?

**Comment by Golddouble** [comment]
OK.
