### ISSUE TITLE
backup while system is running?

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1062]
**Backup of personal data:**
Sometimes I just work with a file. For example, a file is open in Office. Now it could be, that the backup has just started automatically and wants to make a backup of this file, used by the system. Does that work or is that not possible.

**I don't know if backintime can be used to back up the system. But I assume that it can:**
Here is the same question as above:
Can we back up system files while the system is running and needs its system files?

**Comment by daveTheOldCoder** [comment]
As far as I know, Linux doesn't lock files that are in use to prevent them from being read. So files that are in use can be backed up. The only problem is that the snapshot might wind up containing a mixture of incompatible files, which would make restoring problematic.

**Comment by emtiu** [comment]
What @daveTheOldCoder said :)

**Comment by Golddouble** [comment]
Thank you both.
