### ISSUE TITLE
restore /etc folder

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1063]
Scenario:
At 2020-01-01 I make a backup of my /etc folder.
At 2020-01-01 my harddisk beaks.

So, to get back my system, I install Linux new and restore the etc folder with backintime. 

Would this work? Can I restore the /etc folder this way? Or are some files protected, so that they can not be replaced through backintime ?

Can the /etc folder be restored in a running system? Or do I have to do this with a live system?

Do I have now my system back (of course without the programs). Would my system now work again? Or would it be broken? For example because of any rights?

Thank you.

**Comment by DecoDogs** [comment]
I would be **very** cautious about a bulk restore of /etc.  Especially if the version of Linux is not EXACTLY the same as what was already there ... INCLUDING system updates.

Also, you would be, in a direct restore, overwriting files of your running system which could lead to some interesting results.  I would restore the /etc _backup_ 'somewhere else', then pick and choose what to replace in the _live_ /etc.  Run 'ls -lct' on the restored /etc and look at the top entries.

As it happens, unless you're doing something really unusual, there are probably only a few files which might be usually customized (for example, but not comprehensive, hosts, group, passwd/shadow, possibly some rc files, maybe logrotate stuff), so you might want to consider making a stash of those somewhere else on your system after you customize them.  `And.... keep notes.`

Likewise, /etc files are generally owned by root(.root) and, while many are readable by anyone, many are also protected (shadow, gshadow, sudoers, ...) and not readable by everyone.  Of course, you can run BIT as root.... with a lot of caution... and restore on an as-needed basis from that.  Still better, I think, to restore elsewhere, then copy.

As an aside, you might want to consider 'timeshift'.  It is designed for system (not user) backups.  Just something else to have in your quiver.

-Ed

**Comment by emtiu** [comment]
Thanks for your great answer, @DecoDogs! Closing this, but note the related discussion in #480.
