### ISSUE TITLE
Default exclude: .git folders

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1067]
Goal: Exclude git submodules (folders that contain `.git` file). 

Refer: [rsync - Backintime: Skip git submodules - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/588503/backintime-skip-git-submodules)

**How can I specify this?**

**Comment by romedius** [comment]
You should be able to use a pattern in Settings>Exclude to exclude those files.
`.git/*`
should do the job
(I am using BiT 1.1.24 (Debian))

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Simply use the third tab on the snapshots settings "Exclude".

**Comment by aryoda** [comment]
@lamyergeier Could you find a solution? Which one?

**Comment by emtiu** [comment]
There are several feature requests for new/different default excludes, but I think this shouldn't be one of them. As a default, git commit histories should not be excluded. Not every git repo is online and can readily be reproduced. Individual excludes are the way to go here.
