### ISSUE TITLE
Not backing up with "Repeatedly(anacron)" set

### ISSUE THREAD

**Issue by sderrick** [bit-team/backintime#1068]
Mint 19.3
BIT 1.1.12

BIT is not backing up. If I manually initiate a backup with the "take snapshot" button it runs fine.  Prior to updating to Mint 19.3,  I was on 17.x, BIT ran fine.

I looked in /.local/share/backintime/anacron and found a file that was 5 years old. contents were  20150411

I am using a tempfs system for /var/log /var/tmp and /var/spool to prolong the life of my SSD drive.  I'm not sure if that may effect BIT.  I have a script that creates folders for various programs that expect their temp folder to persist.

Here are the only entries that mention "backintime"  after starting my machine.  I Don't see any errors.

> syslog.1:Mar 12 08:42:05 scott-Qosmio-X70-A dbus-daemon[2014]: [session uid=1000 pid=2014] Activating service name='org.kde.kwalletd5' requested by ':1.37' (uid=1000 pid=2479 comm="python3 /usr/share/backintime/common/backintime.py" label="unconfined")
syslog.1:Mar 12 08:42:05 scott-Qosmio-X70-A dbus-daemon[2014]: [session uid=1000 pid=2014] Activating service name='org.kde.kwalletd' requested by ':1.37' (uid=1000 pid=2479 comm="python3 /usr/share/backintime/common/backintime.py" label="unconfined")
syslog.1:Mar 12 08:42:05 scott-Qosmio-X70-A dbus-daemon[941]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.123' (uid=1000 pid=2479 comm="python3 /usr/share/backintime/common/backintime.py" label="unconfined") (using servicehelper)
syslog.1:Mar 12 08:42:06 scott-Qosmio-X70-A dbus-daemon[941]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'

**Comment by emtiu** [comment]
Hi, if this issue is still relevant to you, please take a look at https://github.com/bit-team/backintime/issues/1228#issuecomment-1247327529 and see if it tells you anything useful about your problem. Thanks :)
