### ISSUE TITLE
Cannot delete new files without deleting excluded files as well

### ISSUE THREAD

**Issue by human314** [bit-team/backintime#1070]
I want to use BIT to move my data files from one PC to another. So basically, I backup /home/user except all the hidden folders. 
Now on restore I want to delete all files on the new PC and replace them with the backup, except the hidden folders. 
However on BIT restore I can not find an option for this. As far as I understand, I can delete all files on the new PC, if I check "Remove newer files in original folder". However - as it says in the tooltip - this also deletes the folders that were excluded on backup. 
Is there a way to use backintime for what I want to do?

**Comment by emtiu** [comment]
I don't think there is a way to do that natively with backintime. You might _try_ to remove all folders from the exclusion list in the settings before restoring. This should also prevent those previously excluded folders from being deleted upon restore. But I'm not sure if that might have other consequences, so be careful :)

**Comment by emtiu** [comment]
(Oh, and feel free to re-open this Issue, if you want to discuss or debug this further.)
