### ISSUE TITLE
Cron-triggered backups hang since updates on 3/22

### ISSUE THREAD

**Issue by bitmagewb** [bit-team/backintime#1071]
BackInTime backups have been working fine on my Fedora 31 system, but stopped after I applied updates on 3/22.  A strace of cron shows it hanging after a call to dbus:

[pid 39425] connect(5, {sa_family=AF_UNIX, sun_path="/run/user/1000/bus"}, 21) = 0
[pid 39425] geteuid()                   = 24848
[pid 39425] sendto(5, "\0AUTH EXTERNAL 3234383438\r\n", 27, 0, NULL, 0) = 27
[pid 39425] recvfrom(5, "OK 6970ab6a3be97f2a36aef28376d96"..., 1024, 0, NULL, NULL) = 37
[pid 39425] sendto(5, "BEGIN\r\n", 7, 0, NULL, 0) = 7
[pid 39425] sendto(5, "l\1\0\1\0\0\0\0\1\0\0\0m\0\0\0\1\1o\0\25\0\0\0/org/fre"..., 128, 0, NULL, 0) = 128
[pid 39425] recvfrom(5, "l\2\1\1\n\0\0\0\377\377\377\377?\0\0\0\5\1u\0\1\0\0\0\7\1s\0\24\0\0\0"..., 4096, 0, NULL, NULL) = 260
[pid 39425] sendto(5, "l\1\0\1K\0\0\0\2\0\0\0\177\0\0\0\1\1o\0\25\0\0\0/org/fre"..., 219, 0, NULL, 0) = 219
[pid 39425] recvfrom(5, "l\2\1\1\0\0\0\0\377\377\377\377>\0\0\0\5\1u\0\2\0\0\0\7\1s\0\24\0\0\0"..., 4096, 0, NULL, NULL) = 80
[pid 39425] sendto(5, "l\1\0\0014\0\0\0\3\0\0\0\210\0\0\0\1\1o\0\30\0\0\0/org/fre"..., 204, 0, NULL, 0) = 204
[pid 39425] recvfrom(5,  <unfinished ...>

The processed spawned is:
39425 ?        SN     0:00 python3 -Es /usr/share/backintime/common/backintime.py backup-job

A strace of it shows it stuck on recvfrom(5,.  It never progresess past that point.  When I first discovered the issue I had 30 or so of them hanging around from failed scheduled runs.  A reboot did not change the behavior.  Running a snapshot manually from the GUI works correctly, so it only seems to affect cron-triggered backups.  My crontab line:
#Back In Time system entry, this will be edited by the gui:
0 10,11,12,13,14,15,16,17,18 * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2>&1

Unfortunately there were a lot of updates applied on 3/22, the python ones were:
python3-libdnf-0.43.1-5.fc31.x86_64
python3-dnf-plugins-extras-common-4.0.8-4.fc31.noarch
python3-dnf-plugin-system-upgrade-4.0.8-4.fc31.noarch
python3-hawkey-0.43.1-5.fc31.x86_64
python3-setuptools-41.6.0-1.fc31.noarch
python3-pyyaml-5.3-4.fc31.x86_64
python3-jeepney-0.4.3-1.fc31.noarch
python2-setuptools-41.6.0-1.fc31.noarch
python-setuptools-wheel-41.6.0-1.fc31.noarch

(I can supply a list of all rpms updated if that would be helpful.)

**Comment by emtiu** [comment]
Hi @bitmagewb, is this problem still relevant to you? Did you ever find out more about what was going on?

**Comment by bitmagewb** [comment]
Unfortunately I no longer have that system to be able to test.
