### ISSUE TITLE
Persistent tray icon indicate backup and auth failures (was: [request/query]: Log failed auth attempts for remote profiles)

### ISSUE THREAD

**Issue by kortschak** [bit-team/backintime#1072]
This came up a couple of days ago. Some time ago, I changed my ssh keys on my machine and while I updated all the public keys I remembered, I missed the one for my backup host. I noticed a couple of days ago that there had not been a remote backup made for a few days and it took me a while to correlate the date that it stopped with the date that I changed my keys. This doesn't show up in a log anywhere because the logs held by backintime seem only to deal with logging the back up process and not the connection process.

Is there a logging of failed auth attempts? If not, ISTM that this would be a useful feature to add. I'd also suggest that a warning notification in the case of a failed auth attempt would also be useful (this would have triggered me much earlier to fix the problem I described above).

I'll note that manually triggering a snapshot in the case of an auth failure gives no indication of that failure except that no work is done. The command-line invocation is more informative (and how I managed to get enough friction between my neurons to figure out the problem).

```
~ $ apt-cache policy backintime-common 
bbackintime-common:
  Installed: 1.2.1~bionic
  Candidate: 1.2.1~bionic
  Version table:
 *** 1.2.1~bionic 500
        500 http://ppa.launchpad.net/bit-team/stable/ubuntu bionic/main amd64 Packages
```

**Comment by buhtzz** [comment]
@kortschak Thanks for the report. I assume this is still relevant and reproducible.

Tag: Bug/Feature, High, Qt, Scheduling

Don't we have a Meta Issue somewhere about the fact that BIT doesn't inform about failed snapshots in every case?

**Comment by kortschak** [comment]
Yes, it's still relevant.

**Comment by buhtz** [comment]
Hello Dan,
the problem you describe touches several issues.

Logging is done in the systems syslog. There is a [FAQ entry](https://github.com/bit-team/backintime/blob/dev/FAQ.md#how-to-read-log-entries) about that topic.

- #1645 : About make systray icon permanent to visually indicate problems.
- #827 : About errors in user-callback scripts not notified
- #1018 : A proposal about a new command to get the current status of all snapshot profiles in JSON format on command line.

Please let me know if you want to add new information. To my understanding your problem and possible solutions are covered by the issues I listed. So we can close your issue. Opinions?

Best,
Christian

**Comment by kortschak** [comment]
I don't think this is related to #1645 or #827. I think it _is_ tangentially related to #1018, but the main issue here is ensuring that the failure is surfaced clearly to the user. I know I can look in the syslog, but why would I bother if I did not notice that something went wrong, as was the case in the initial report. What I'm asking for is a mechanism to ensure that failures are presented to users so that they _can then_ follow up with either syslog investigation or using something like what is described in #1018.

**Comment by buhtz** [comment]
Thanks for the feedback Dan.

> the main issue here is ensuring that the failure is surfaced clearly to the user

I agree and also see this as the main issue. But the question which method could be used to bring errors to the users.

#1645 and #827 about the systray icon. If you would have a persistent (always existing) tray icon it could indicate errors with changing its appearance to a "warning red" sign or something else. Then you would see somethings not right.

#1018 is about a mechanism to ask BIT about the current status of all snapshot profiles and potential errors in a machine readable way. You could use this mechanism to integrate it into own scripts (e.g. in cron jobs) checking for such errors and then react (e.g. sending a mail, notify in systray, flash a red light in the dining room, give lot of beeps, or something else).

**Comment by kortschak** [comment]
Yes, you are correct, if a system tray item had a marker of failure, that would work.

**Comment by buhtz** [comment]
~To my team mates: Might be useful to open a fresh meta issue about a "persistent tray icon"?~ Found it: #1370

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
Christian
