### ISSUE TITLE
Identical files copied even if checksum is checked

### ISSUE THREAD

**Issue by Xwang1976** [bit-team/backintime#1073]
I'm using BiT 1.2.1 on my archlinux system for backing up my android phone files.
Today I've discovered that BiT created new files copies because the timestamp of all files in the phone has changed due to the summer time change happened since the last backup (99% of files are unchanged being images or music files which only have a different timestamp).
So I deleted the last snapshot and I modified the configuration checking the "use checksum" to force BiT to ignore timestamp and use only checksums.
Then I executed a new snapshot and BiT still created copies of all files despite they are identical (same size and md5sum but different timestamp).

**Comment by Xwang1976** [comment]
I've done it again and I've the same issue, but I've discovered that the config is correct (the profile I was using is not the first one).
So the problem is that all files are copied even thought their checksum is the same!!!

**Comment by m2c2lure67** [comment]
I've been using BiT for quite a while now, and just noticed all of my snapshots are nearly 400GB!  It's my understanding that only the oldest should be near that size...?

**Comment by daveTheOldCoder** [comment]
> Filelight reports each of my BiT snapshots is taking nearly 400GB

This FAQ entry shows a reliable way to measure the snapshots' disk usage:
https://github.com/bit-team/backintime/wiki/FAQ#how-can-i-check-if-my-snapshots-are-incremental-using-hard-links

**Comment by emtiu** [comment]
Hi @Xwang1976, is this problem still relevant to you? Did you ever find out more about what was happening?

It sounds like your problem might be related to #988, but I'm not sure.

**Comment by m2c2lure67** [comment]
It appears that the snapshot(s) with this issue eventually fell off, and
the freespace was recouped.  Thanks for following up.
