### ISSUE TITLE
Security issue with backup file permissions

### ISSUE THREAD

**Issue by udopt** [bit-team/backintime#1078]
I make daily, automated backups of some root files within /etc and of course of my home folder. The backup is run as root.

For each backup, there is a new backup directory, where the name consists of date, time and an integer. This directory contains some files such as "config", but more importantly the folder "backup" which actually contains the backup files.

With BIT version 1.1.24 from Ubuntu 19.10, the files inside this last "backup" folder could not be deleted by me, only by root (even the backup files from my home folder). I considered this a nice security measure to avoid unwanted deletions of the backup files either by me (as an accident) or by malicious programs running with user rights.

BIT version 1.2.1 from Ubuntu 20.04 however stores the backup files with exactly the same permissions they had in the folder before. This means that the files can now be deleted with user rights (no root required as before).

Is this the new default behavior or did I miss some option I should have set when transitioning from BIT 1.1.24 to 1.2.1?

**Edit** This is the new default behavior: https://github.com/bit-team/backintime/issues/988. The question remains if the old behavior can still be enforced.

**Comment by Cyber1000** [comment]
I only found this workaround some time ago, which still works for me with version 1.2.1: https://github.com/bit-team/backintime/issues/988#issuecomment-504665090
You may try it with this.

The code itself doesn't indicate a direct way to override this.

**Comment by udopt** [comment]
Terrific, that solved the problem for me!
