### ISSUE TITLE
Please allow incremental backups to the same folder from different backup profiles

### ISSUE THREAD

**Issue by mYnDstrEAm** [bit-team/backintime#1079]
I'd like to do backups of folders from multiple backup profiles. Folders/files selected in profile A largely overlap with the folders/files selected in profile B. Currently BackInTime creates a new folder with the number of the backup profile like this: _backup-destination/backintime/computer-name/user-name/profile-number_. However, I'd like to incrementally backup to basically the same ("profile-name") folder instead of creating an entirely new, full backup for the new profile.
For example Profile B might be for backups that are scheduled to run more often and excludes a few more files and misses some folders when compared to profile A.
Could you please build this into BIT? It would be very useful.
Here another user also asked about it: _[backintime: make several profiles incremental to one?](https://unix.stackexchange.com/questions/561218/backintime-make-several-profiles-incremental-to-one)_

It looks like you can simply create a new profile with similar settings and change the full snapshot path under General->Advanced to the same folder as the other profile. **However**, the "last_snapshot" folder doesn't include folders which were excluded in newer backups. I suspect that there also might be additional problems with this solution so it really does need new functionality dedicated to enable proper support of backups from multiple profiles.

**Comment by ti-nok** [comment]
You could implement what you want like this:
- create an initial backup with your profile 2
- go to backup-destination/backintime/computer-name/user-name/2
- replace all your backed up files with hard links to backup-destination/backintime/computer-name/user-name/1

**Comment by emtiu** [comment]
Mixing the backups of separate profiles in this way is not supported, and I'm sorry to say that I can only imagine it would be a nightmare to support.

To get the space savings you want with a configuration like that, you're probably best served with an in-band deduplicating file system like zfs.
