### ISSUE TITLE
option to only keep one snapshot at a time

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#108]
This came up while I was trying to find a way to use BIT to back up data to dropbox. The dropbox client syncs all hardlinks as separate files, so 2 snapshots take twice the online disk space of one snapshot. To save space an option to only keep one single snapshot at a time would be helpful.

See also discussion at https://answers.launchpad.net/backintime/+question/146468

Sebastian

---

Imported from Launchpad using lp2gh.
- date created: 2011-03-09T17:42:19Z
- owner: sebhofer-gmail
- the launchpad url was https://bugs.launchpad.net/bugs/732144

**Comment by buhtz** [comment]
Nice idea, but how should this be implemented? Doing a incremental backup and after this deleteing the first one?

While the snapshot is running this would take nearly twice online disc space until the snapshot is fnished and BIT remove the first one.

**Comment by sebhofer** [comment]
Puhh... I filed this issue 6 and a half years ago... And I have stopped using BIT a long time ago...

**Comment by buhtz** [comment]
What are you using now for your backups?

@Germar we can close this I think.

**Comment by sebhofer** [comment]
SpiderOak for my private backup needs
