### ISSUE TITLE
can't start backintime-qt with sudo

### ISSUE THREAD

**Issue by 1edenec** [bit-team/backintime#1084]
Hello everybody. 
The application stacked while backing up was running. After PC reboot 
sudo backintime-qt doesn't start. it says:
backintime already running!
but no any copy of backintime launched.

**Comment by aryoda** [comment]
`ps -ax | grep -i backintime` would list all running background tasks (I hope).

Have you solved the problem? How?

**Comment by emtiu** [comment]
Also, `sudo` is not the best way to run backintime as root. You should:
1. Find "Back In Time (root)" in the applications menu of your Desktop Environment (if it exists), or
2. run `/usr/bin/backintime-qt_polkit` (if it exists), or
3. call `pkexec backintime-qt` from a terminal.

**Comment by emtiu** [comment]
Timeout after >4 weeks.
