### ISSUE TITLE
Use variables in config to 'preeseed' configuration

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#109]
To preseed backintime configurations Backintime should provide a possiblility to use variables in the config file.

Example:
The backupdestination for a user is in /backup/USER/.
So it should be possible to use 'snapshots.path=/backup/$(USER)' or something.

With this one could 'preseed' the backup configuration for every user in /etc/skel

---

Imported from Launchpad using lp2gh.
- date created: 2011-05-24T12:05:49Z
- owner: it-oas
- the launchpad url was https://bugs.launchpad.net/bugs/787510

**Comment by buhtz** [comment]
Does this effects the practice? Does it improve the users experience and easy his life?
In the practice I see no positive effect of such a feature.

Config code is an essential part of BIT. Modifing this code takes the danger of heavy bugs and would cause the need to do a lot of testing to prevent such bugs.

I would recommend not to implement this if there isn't a heavy reason.

**Comment by emtiu** [comment]
I agree that this probably isn't a feature worth the trouble. Most users probably only ever set up 1-3 backup profiles on one machine and live with them for years.
