### ISSUE TITLE
Very slow to start backup

### ISSUE THREAD

**Issue by wattsra** [bit-team/backintime#1091]
I perform daily backups of my root folder to an externally mounted drive. I have excluded all of the system and device folders which I believe either loopback or will create issues. However I still have some major issues with speed. 

The speed will stay in double digit kb/s for about 45 mins, before eventually speeding up to 30Mb/s. It seems to be very slow trawling through the /snap directory. Should I be excluding this /snap directory? I would like to keep my snaps also backed up should I want to restore my whole system in the future.

I can attach my logs if it helps.

**Comment by mYnDstrEAm** [comment]
How did you log which things were slow to trawl through?

Also see #1102

**Comment by buhtzz** [comment]
@wattsra There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment]
Closing since the reporter isn't responding. Note that #1102 is a feature request for timing information.
