### ISSUE TITLE
Backintime Dead: Alternative?

### ISSUE THREAD

**Issue by bit-user** [bit-team/backintime#1092]
Hey all,

since backintime seems to be dead, is there a fork or similar project that can work with the backups created by backintime? I want to transition as soon as possible, before an issue makes the backups unusable and no developer will fix it :)

Thanks!

**Comment by colinl** [comment]
One of the good things about BiT is that the backups are plain files and links.  The backups will never become completely unusable as you can go in with file explorer and find all versions of all the files in the same folder heirarchy that they came from.  I plan to decide what backup strategy to move to and then just archive the current backup, secure in the knowledge that if I lose (or have already lost but haven't noticed) anything then I will be able to go in and find it.

**Comment by bit-user** [comment]
Once you came to a decision, would you mind posting it here @colinl ? I would love to hear an opinion :)

**Comment by colinl** [comment]
I haven't started looking at alternatives yet.  All suggestions gratefully received.  One of the key things may be to use something that, if open source, has a number of active contributors so that if one moves on to other things the project is not abandoned.

**Comment by bit-user** [comment]
Yeah good point. And if something is built upon rsync it would be a huge benefit :)

**Comment by morgangrubb** [comment]
https://github.com/bup/bup is the one I'm hanging out for. It needs to be updated to python3 but the devs are active.

**Comment by bit-user** [comment]
Very nice, thanks @morgangrubb ! I will check it out :)

**Comment by colinl** [comment]
Yes, bup does not nice, however it is fairly new and does warn that it is not fully mature.  I like to have two independent backup strategies running so I may try it as one of them, and use a more mature one for the other.

**Comment by kpeeters** [comment]
If you're only looking for a command-line thing restic is very good https://restic.net/ . Still, I'd hope that we can keep backintime alive, perhaps even use its UI to wrap restic at some point.

**Comment by anishmittal2020** [comment]
I know many people are frustrated (as I was) due to the version 1.2.1 which is quite slow. 

# I have suggestion on debian based OS:

And installing old version by building those is not that easy. But I would suggest install 1.1.24 command line package (not qt package). And use the tool from CLI without GUI. It works fine for me.

**Comment by bit-user** [comment]
I am really surprised, that such a popular tool like backintime doesn't find a dev to take over :(

**Comment by ispmarin** [comment]
Also looking for an alternative. Backintime is such a great tool.

**Comment by sebastian9er** [comment]
@kpeeters Thanks a lot! I switched to restic, since I don't need a GUI anyway and that is maintained with a solid user base (I know this didn't prevent backintime from dying, but I will test my luck) :)

**Comment by timbo-lino** [comment]
What do you think about rsnapshot ( https://github.com/rsnapshot/rsnapshot ) as an alternative?

**Comment by Ckarles** [comment]
> If you're only looking for a command-line thing restic is very good https://restic.net/ . Still, I'd hope that we can keep backintime alive, perhaps even use its UI to wrap restic at some point.

Thx! I didn't know this project but I was thinking of doing this exact same design for a bit of time now, I'm glad somebody has already done it!!!

I need to look under the hood to see what they actually put in place, but so far this solution is the one I would've done myself of not found out, so big thanks to you here.

> What do you think about rsnapshot ( https://github.com/rsnapshot/rsnapshot ) as an alternative?

I've used it for a long period of time to backup hundreds of production servers on zfs pools. For this particular use I would recommend it, it has some drawbacks but is very solid, and simple (which is oh so important), we never had any issues concerning backups coming caused by rsnapshot itself.

For a desktop use though, never used it, it's just wasn't design for that goal in mind I guess, it's pretty restrictive in that regard, and very "static".

**Comment by mYnDstrEAm** [comment]
I'd recommend borg as good alternative - here is a Qt GUI for it:
https://github.com/Nebucatnetzer/borg-qt
It has similar features to BiT as well as deduplication.

I hope more devs will get behind BiT. Deduplication could also be added to BiT. How can we get more devs to develop it?

**Comment by jonath92** [comment]
I like [rdiff-backup](https://github.com/rdiff-backup/rdiff-backup) but it is only for  CLI without GUI. I am not a backup expert and haven't tried any other mentioned software here. I just wanted to mention it as an alternative for the sake of completeness.

**Comment by gcolds** [comment]
> I'd recommend borg as good alternative - here are two Qt GUIs for it:
> https://github.com/borgbase/vorta
> https://github.com/Nebucatnetzer/borg-qt
> They have similar features to BiT as well as deduplication.
> 
> I hope more devs will get behind BiT. Deduplication could also be added to BiT. How can we get more devs to develop it?

Holy cow!  Thanks for this information mYnDstrEAm!  BorgBackup with the Vorta GUI is fantastic.  Not only does it do deduplication without hardlinks, it compresses the backups, and is consistently faster than backintime with incremental backups in my setup (desktop to UnRAID home server).  It's even consistently faster than Apple Time Machine in my experience (at both initial backups and incremental backups).  It took me a while to understand how to configure it the way I had BIT configured and the actual process of mounting a backup for browsing and/or restoring is a bit sluggish at first but other than that, it's a freaking dream.  I intend to archive my oldest backintime snapshots to a few Bluray M-Discs and them I'm going to remove backintime from my system.  It was great for the 3 years that I used it but Vorta+BorgBackup seems to be a better solution (at least for my setup).  

**Thanks again mYnDstrEAm!**

**Comment by mauromol** [comment]
It's really sad that nobody has time to take over BiT development... :-(

I think BiT is great and its "backup format" is so simple and so effective...

Thanks for the alternatives mentioned here. Some of them are interesting, but I think that BiT would still be a valuable solution nowadays. I really hope that the situation can change.

**Comment by emtiu** [comment]
The latest discussion on the state of the project took place in #1232.
