### ISSUE TITLE
The add file/folder dialogs should show hidden files/folder by default

### ISSUE THREAD

**Issue by Sharon507** [bit-team/backintime#1097]
As pointed out in #1051, hidden items can be shown by pressing ctrl-H but many users won't know that. I was almost ready to uninstall and look for a different backup utility to use.

**Comment by daveTheOldCoder** [comment]
"Show hidden files" is in the View menu.

**Comment by Sharon507** [comment]
Sorry - I realise I didn't make this clear before, but I was referring to the file dialog that you get when you are initially setting up your backup profile (or are modifying it via Settings) and you choose Add File or Add Folder from the Include or Exclude tab. Until I found #1051 I thought it must not be possible to back up hidden files or folders at all with this software.

**Comment by daveTheOldCoder** [comment]
I see your point. Apparently the View menu's "Show hidden files" toggle (or Ctrl-H) is a global setting that affects all the file/folder lists, but that may not be obvious to all users.

**Comment by Sharon507** [comment]
Yes - I hadn't realised that initially. I think the first time I launched the software it took my straight into setting up my backup configuration so I hadn't seen the menus in the main window at that point.

**Comment by Sharon507** [comment]
I should add that I'm very impressed by the BackInTime software. I've only just started using it but it seems excellent.

**Comment by daveTheOldCoder** [comment]
It's working well for me too. I've only found one problem, which I described in the "Weekly snapshots not being retained" issue.

**Comment by Sharon507** [comment]
Thanks. It's good to be aware of that. I'll keep an eye out for it.
