### ISSUE TITLE
Stop in taking snapshot while claiming it is still working

### ISSUE THREAD

**Issue by lcnature** [bit-team/backintime#1099]
Hello,
I am using 1.2.1, on Ubuntu 18.04 to back up my computer to an external hard drive
I found that often backintime stops taking snapshot after working intensively for an hour or so. The main window shows it is still working but the last file it took snapshot stays unchanged for hours, and on system monitor I can see that it also uses 0% CPU.
When I checked the log file, usually the last tens logs are fine, but before the last tens of files being backed up, there are often errors starting with "[E] Error: rsync: recv_generator:   ....... failed: Input/output error (5) " on a file in the ".local/share/backintime/mnt/" folder which points to the externel hard disk. I thought it may be because the external hard drive is failing. But I ran a disc check and did not find a bad segment.
So I wonder if you think this is indeed a hard drive problem, or something else.

Thanks!

**Comment by emtiu** [comment]
Hi @lcnature, these errors normally indicate a failing drive, as you have suspected. Not all checks are able to find such problems before a drive really does fail.

Did you ever figure out what was going on?

**Comment by lcnature** [comment]
No actually. I think I eventually forgot to do backup after that problem...

**Comment by emtiu** [comment]
All right, thanks for writing back :)
