### ISSUE TITLE
View progress of snapshot in terminal ?

### ISSUE THREAD

**Issue by JPnux** [bit-team/backintime#1108]
Hello,

Is it possible to view progress of the snapshot when executing "backintime backup" in a terminal ?

Actually, I don't have the progress.

I just see this :
-------------------------

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Profil principal
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
-------------------------

Thank you

**Comment by daveTheOldCoder** [comment]
This might provide more details:
`backintime --debug backup`

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Issue can be closed.

**Comment by emtiu** [comment]
Closing as duplicate of #1131.
