### ISSUE TITLE
wrong italian traduction

### ISSUE THREAD

**Issue by stethewwolf** [bit-team/backintime#1110]
info to reproduce:
SO: Manjaro
Back In Time : 1.2.1 

pakcages : 
backintime-1.2.1-1-any.pkg.tar.xz
backintime-cli-1.2.1-1-any.pkg.tar.xz

bug
![image](https://user-images.githubusercontent.com/5927405/91016829-ae26a700-e5ed-11ea-83ac-cded81c04327.png)

the right traduction should be : 
( funziona solo con collegamenti assoluti )

**Comment by stethewwolf** [comment]
I try fix the Issues here https://github.com/stethewwolf/backintime/tree/fixes/ita_translation 
asap I will test them and if them are good create a pull request 

Regards.

**Comment by colinl** [comment]
Unfortunately I think you may be wasting your time making a PR.  If you look at open PRs you will see they are not being actioned.  It appears the project is no longer maintained.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The project is still maintained. But most of the year inactive - right. But @Germar still take care as much as he can.

@stethewwolf Please open an PR.

**Comment by stethewwolf** [comment]
Sorry I'have just seen the message inside the REAME.md contained in the "po" folder.

I basically did what I shouldn't 0: ) ,  but I haven't a launchpad account so I will open the PR but please take it only as reference to fix the translation on lauchpad
