### ISSUE TITLE
[E] Error: rsync: mkstemp failed: File name too long (36)

### ISSUE THREAD

**Issue by foretastesynergy** [bit-team/backintime#1112]
App uses such many folders that it's not enough for filename
Next string is just folder name of backup. 
"backintime" - 2 times. username - 2 times. original full path in backup? *facepalm*
Are you crazy? 
/home/poltora/.local/share/backintime/mnt/5_11446/backintime/i7-com/poltora/5/new_snapshot/backup

This is error:
[E] Error: rsync: mkstemp "/home/poltora/.local/share/backintime/mnt/5_11446/backintime/i7-com/poltora/5/new_snapshot/backup/mnt/poltora/.priv/1.5/Финансы/.Квадрант денежного потока Роберта Кийосаки – критика, можно ли верить, что не так со схемой.html.dLoXDP" failed: File name too long (36)

**Comment by colinl** [comment]
I don't see anything like that.  Are you sure you have not included .local in the folders to be backed up.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Why filesystem is on the backup destination and how is it mounted?

**Comment by buhtzz** [comment]
@colinl There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, External

Close.

**Comment by emtiu** [comment]
Closing as duplicate of #1304, which would greatly help with this problem.
