### ISSUE TITLE
PermissionError: [Errno 13] Permission denied /tmp/backintime.lock

### ISSUE THREAD

**Issue by matsonfamily** [bit-team/backintime#1116]
if backintime lock is created, backintime cannot perform it's auto backups as the root user.  I can open the gui and tell it to backup and it has no error and no log, and nothing in /var/log that i notice.  The lockfile is created with my user's permissions, but I'm not sure why or when.  If I manually delete it, it then works, and opening as either me or the root user doesn't create the lockfile, but every once in a while it's created and then only my user (auto or manual) can do backups.  I usually don't notice, because 90% of my backups are auto, but then I'll find that either root or my user's backups are failing.  The running service helper doesn't seem to create the lockfile, either.  I'm not sure how to troubleshoot it.  Thanks.

```
~$ sudo backintime-qt
[sudo] password for xxx: 

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 739, in backup
    ret = takeSnapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 94, in takeSnapshot
    ret = snapshots.Snapshots(cfg).backup(force)
  File "/usr/share/backintime/common/snapshots.py", line 633, in backup
    self.flockExclusive()
  File "/usr/share/backintime/common/snapshots.py", line 1752, in flockExclusive
    self.flock = open(self.GLOBAL_FLOCK, 'w')
PermissionError: [Errno 13] Permission denied: '/tmp/backintime.lock'
```

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Maybe same Issue #1122

**Comment by matsonfamily** [comment]
I think this is now resolved.  I've had a few times where I've had to delete the regular user lockfile, then it started working, and i've let it go for about a month, with daily auto backups.  seems good now!
