### ISSUE TITLE
Is there a way to define extra SSH options?

### ISSUE THREAD

**Issue by kdupke** [bit-team/backintime#1117]
I searched for a way to define extra ssh options but was not lucky with it.

I assume the only solution is to use an ssh replacement aka shell script with the extra options in a specific path just for backintime.

However, when trying to do so backintime seems to ignore the ssh prefix setting I assumed to be designed to have a different path for ssh?

**Comment by colinl** [comment]
What are you trying to set?

**Comment by kdupke** [comment]
Sorry, missed there was a comment.

I am looking to use openSSH with HPN-SSH patches, to disable encryption on a direct connection.

I was able to solve this to put an openssh-wrapper into the path before the system openssh. In the script I now check the target system and if this is the direct connection I use the needed options for disabling encryption.

**Comment by buhtzz** [comment]
Close as solved.
