### ISSUE TITLE
Request to add me as member to the repo so I can update the documentation

### ISSUE THREAD

**Issue by caco3** [bit-team/backintime#1119]
Hi @Germar, @dinoboy197, @LanceGundersen 
I am using BiT since over 10 years, mainly in connection with my Synology Diskstation.

I also helped on the wiki page in https://github.com/bit-team/backintime/wiki/Hardware-Specific-Setups/_history 
That page and several others are now quite outdated and really hard to maintain. 
I would suggest to move it to https://backintime.readthedocs.io and update it. I am willing to help with that, but I would need to be a member of the repos for that.

**Comment by caco3** [comment]
@Codeberg-AsGithubAlternative-buhtz 
You seem be at least partially active, eg in https://github.com/bit-team/backintime/issues/1114#issuecomment-740234401

Do you have access to the Github config?
There are **several** people who are willing to actively help on the project, but if you guys do not let us help, that **really** sad!

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Sorry, I have no access to the config or any other admin rights on @Germar 's repo.

**Comment by caco3** [comment]
@Codeberg-AsGithubAlternative-buhtz Thanks for the info. It is IMHO really a shame that @Germar simply drops his project and is not even willing to hand it over to a new team. :angry:

**Comment by LanceGundersen** [comment]
I have no idea why I was mentioned here 🤔

**Comment by caco3** [comment]
> I have no idea why I was mentioned here thinking

@LanceGundersen I mentioned you because you are listed as a member of Bit, see https://github.com/orgs/bit-team/people

Do you have admin access to the BiT repos?

**Comment by rnc** [comment]
I would have to say that although @Codeberg-AsGithubAlternative-buhtz does reply to issues (but without resolving them?), without appropriate admin level permissions then #1088 and #1114 may be correct

**Comment by colinl** [comment]
We have to be careful before criticising @Germar.  His facebook page has not been updated for a long time, perhaps some awful fate has befallen him.
The best solution here is for someone else here who has an interest to fork the repository and take over the maintenance.  I believe the license allows that.  In fact did not someone recently here say that they have forked it and applied some outstanding PRs?

**Comment by caco3** [comment]
> We have to be careful before criticising @Germar. His facebook page has not been updated for a long time, perhaps some awful fate has befallen him.
> The best solution here is for someone else here who has an interest to fork the repository and take over the maintenance. I believe the license allows that. In fact did not someone recently here say that they have forked it and applied some outstanding PRs?

IMHO it is not fair to a team to just head off and let it stay for itself in the rain.
There are many people who would be willing to step in and help.

And beside of this, if you search for @Germar in the internet you will find his portrait on a company website. So we gladly can interpret that he is doing well.

**Comment by xandark** [comment]
I came here looking for support and vibrancy and I too am sad that it appears to be abandoned, especially when there are others who want to step up. 

Yes, I would be happy if this project found itself forked into a larger community so as to save it. The intention of the fork could be that it would be merged back if the original maintainer ever decided to come back to the project.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I agree with @colinl . I just didn't want to describe it so direct. I hope @Germar is fine in these days.

@caco3 This is not about fairness. And there is no "team". feedparser was and is a one-man-show. I am a bit into it because I use it vey intensive. But myself I also not able to take over the project. Maintaining a project is not so easy as you might think.

But "fair" is that you can fork everytime and improve it. It depends on your maintain abbility and your team which one of the repos will persist.

feedparser is not a tiny tool/app. It is a library which a lot of other software depends on. So there is a lot of responsibility maintaining it.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I just want to inform that there is a newer Issue (#1232) discussing the status of the project and forming a new maintaining team. [Since yesterday](https://github.com/bit-team/backintime/issues/1232#issuecomment-1146882621) there is also mailing list about development and maintaining BIT.
