### ISSUE TITLE
How to restore the system root-folder and hidden home files/folders

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1120]
I know, that we can also create bckups of root-folders, when we start backintime as root.

1. Question:
When we now make a backup of the root-folder without home and without the hidden folders in home:
How can we then restore this root?
Do we have to start a life system and restore from there?
Or does backintime support root restoring by itself, like timeshift does?
I can restore "root" in timeshift. timeshift automatically shut down the system replaces the root folders and files and starts the system new. Done.
Does backintime also support this?

2. Question:
When we make a backup of the hidden folders and hidden files from the home folder:
How can we then restore this hidden files?
I know, that we can not restore some hidden files and folders in home folder, when the system is running. So do we have to start a life system and restore from there with backintime?
Or does backintime support hidden home-files and -folder restoring by itself, like timeshift does?
I can restore "root" in timeshift. timeshift automatically shut down the system replaces the root folders and files and starts the system new. Done.
Does backintime also support this?

Thank you.

**Comment by buhtzz** [comment]
@Golddouble There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Documentation

**Comment by Golddouble** [comment]
I once considered using backintime for the backup of my home. This was, why I was asking this question. I have never tried it out. I then decided to use Vorta for my home backup instead. I use Timeshift for my root and the hidden home files. But yes, I am still interested in an answer. But I am sure, that for both questions the answer would be: I live system is needed.

**Comment by emtiu** [comment]
Hi, thanks for writing back. I'm answering your questions and closing the Issue.

1: You're right, there's no offline whole-system restore. That's outside of backintime's "job description".
2: Restoring hidden folders is no problem. They can sometimes be trouble on Windows, but on Linux, they're just regular folders with special names (starting with `.`).

**Comment by Golddouble** [comment]
Thank you.

For 2)
My concern was, that when I restore my hidden folders in a running system,then things could get a little messed up. Maybe some hidden folders are used in the running system and when I just replace such a hidden folder whyle the system is running, my concern was, that this would destroy the system. So this is no problem?

**Comment by emtiu** [comment]
I see, thanks for clarifying. Yes, this can mean trouble, depending on what's running. You shouldn't replace `$HOME/.mozilla/` while Firefox is running, for example. The same thing goes for `$HOME/.kde/` and other settings folders. If I wanted to do that, I would close the respective programs. In the case of the desktop environment, maybe restore from the command line without being logged into the graphical environment (see the manpage about `backintime --restore`), or do it from the root user.
