### ISSUE TITLE
I can't add folders to backup

### ISSUE THREAD

**Issue by Toadfield** [bit-team/backintime#1130]
If I click on the add folder button and then click on the folder I want,then it just gets opened,but not added.
System info:
![image](https://user-images.githubusercontent.com/68649672/106009968-40f5d100-60b9-11eb-9afa-6e5ee8e93b6a.png)
![image](https://user-images.githubusercontent.com/68649672/106010015-4c48fc80-60b9-11eb-887b-c44338f01317.png)

**Comment by colinl** [comment]
I presume that when you click the Add Folder button it brings up a file browser.  If so then you should be able to click the folder you want to add, and then click Choose.  It should not open the folder unless you double click.

**Comment by Toadfield** [comment]
Oh,I choose "file" instead of "folder".
