### ISSUE TITLE
[Ubuntu, Mint] PPA distro version support

### ISSUE THREAD

**Issue by buteman** [bit-team/backintime#1136]
I tried to set up backintime on my Mint 20.1  but got this error

sudo add-apt-repository ppa:bit-team/stable
Cannot add PPA: ''This PPA does not support focal''.
Any idea how I can fix this please

**Comment by ciosbel** [comment]
Same here on a fresh Ubuntu 20.04.
```
E: The repository 'http://ppa.launchpad.net/bit-team/stable/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by yohore** [comment]
In Linux Mint 20.1, after:


> sudo add-apt-repository ppa:bit-team/stable


I get:

> No se puede añadir el PPA: «'Este PPA no admite focal'».

Please, help.
Thank you.

**Comment by awandepan** [comment]
Because the supported ubuntu version is only until Eoan,
Focal not yet supported

why not just install it from repo?
`sudo apt install backintime-qt`

**Comment by yohore** [comment]
> Because the supported ubuntu version is only until Eoan,
> Focal not yet supported
> 
> why not just install it from repo?
> `sudo apt install backintime-qt`

Now it works.
Thank you so much.
