### ISSUE TITLE
Backintime hangs at the end

### ISSUE THREAD

**Issue by fmarzocca** [bit-team/backintime#1140]
I am running Linux MInt 20 and backintime 1.2.1.
Every time I launch a snapshot, it freezes at 93% and doesn't finish. I have to close the application and the running processes.

**Comment by TheTimeWalker** [comment]
Have you checked the logs? Maybe tried running backintime with `--debug`?

**Comment by fmarzocca** [comment]
I have searched for specific logs or lines in syslog, with no luck.


- Sent from my mobile phone. Sorry for typos -

Il Mer 17 Mar 2021, 18:37 Tony Stipanic ***@***.***> ha
scritto:

**Comment by fmarzocca** [comment]
```
sudo backintime --debug
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []
```

**Comment by fmarzocca** [comment]
I have found a lot of these errors, but I don't understand the meaning:

`notify-send Back In Time () : Profilo principale Error: rsync: rename "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/home/fabio/.local_orig/share/nautilus/scripts/.Open Terminal here..YE6RrJ" -> "home/fabio/.local_orig/share/nautilus/scripts/Open Terminal here..": Invalid argument (22)
notify-send Back In Time () : Profilo principale Error: rsync: mkstemp "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/home/fabio/.sane/xsane/.CANON:CanonPIXMAMG3600Series.drc.aAqbBG" failed: Invalid argument (22)
notify-send Back In Time () : Profilo principale Error: rsync: mkstemp "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/home/fabio/.sane/xsane/.Canon:LiDE100.drc.ktAHYI" failed: Invalid argument (22)
notify-send Back In Time () : Profilo principale Error: rsync: mkstemp "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/home/fabio/.sane/xsane/.Canon:LiDE100_2threshold.drc.Tq1qxI" failed: Invalid argument (22)
notify-send Back In Time () : Profilo principale Error: rsync: mkstemp "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/home/fabio/Audio/.2020-07-01-13:40:41.ogg.ZSW0XJ" failed: Invalid argument (22)
notify-send Back In Time () : Profilo principale Error: rsync: recv_generator: mkdir "/media/fabio/Transcend/Plato Backup/backintime/Plato/root/1/new_snapshot/backup/var/lib/bluetooth/00:1A:7D:DA:71:15" failed: Invalid argument (22)
`

**Comment by AlexSchr** [comment]
Could it be that some filenames cannot be created on the target because of invalid characters?
Like colons (":")? In what kind of file system does the target lie?

**Comment by fmarzocca** [comment]
NTFS


- Sent from my mobile phone. Sorry for typos -

Il Ven 19 Mar 2021, 18:38 AlexSchr ***@***.***> ha scritto:

**Comment by AlexSchr** [comment]
Colon (":") is not allowed in file names on NTFS.
Source: https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations
Back in time uses rsync, so the following question covers the issue:
https://serverfault.com/questions/231138/rsync-to-windows-with-in-filenames
