### ISSUE TITLE
backup to local USB disk gives "rsync error 2 (Protocol incompatibility)"

### ISSUE THREAD

**Issue by sneumann** [bit-team/backintime#1144]
Hi, 
I am running backintime on a laptop onto a local USB disk mounted as 
`type xfs (rw,nosuid,nodev,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota,uhelper=udisks2)`

I get a Warning from rsync `returns 2` which is `Protocol incompatibility`,
and some digging shows this happens if you are running rsync across some connection
between two computers with different rsync versions. Not the case here, 
this is all local. I checked (just one) file that changed recently, and it is present 
in the backup directory. 

=> Anymore insights into this rsync error ? How to prevent the warning, how to check integrity of the backup ?

Yours,
Steffen

```
INFO: Call rsync to take the snapshot
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
WARNING: Command "rsync --recursive --times --devices --specials --hard-links --human-readable --links --acls --xattrs --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20210301-082432-781/backup --chmod=Du+wx --exclude=/media/sneumann/LinuxBackup/msbi-corei --exclude=/root/.local/share/backintime --exclude=.local/share/backintime/mnt --exclude=.gvfs --exclude=.cache* --exclude=[Cc]ache* --exclude=.thumbnails* --exclude=[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=/home/sneumann/Ubuntu One --exclude=.dropbox* --exclude=/proc/* --exclude=/sys/* --exclude=/dev/* --exclude=/run/* --exclude=/media --exclude=/root/.local/share/backintime/takesnapshot_.log --exclude=/root/.local/share/backintime --include=/ --include=/** --exclude=* / /media/sneumann/LinuxBackup/msbi-corei/backintime/msbi-corei/root/1/new_snapshot/backup" returns 2
```

**Comment by emtiu** [comment]
Hi Steffen, did you ever find further clues (in logs, for example) or a solution to this problem?

**Comment by buhtz** [comment]
Dear @sneumann ,
are you somehow able to reproduce the problem with the latest version of BIT and rsync?

**Comment by sneumann** [comment]
Hi, I can't recall having observed the issue recently. Yours, Steffen
