### ISSUE TITLE
[Wayland] SSH input fields in Settings dialog do not accept input

### ISSUE THREAD

**Issue by thelazy6** [bit-team/backintime#1145]
In settings dialog, subgroup common, mode SSH, the host and path input fields do not accept input. Only occurs on wayland, not x11.
ADDENDUM: The whole settings dialog crashes (also on x11) in SSH mode at clicking OK.

**Comment by buhtz** [comment]
Dear @thelazy6 ,

Wayland evolved a lot since your last post. Can please try to reproduce the problem with an up to date GNU/Linux distribution and the latest BIT version. If you can reproduce please post the output of `backintime --diagnostics`.

Thanks

**Comment by thelazy6** [comment]
The bug does not exist any more on both GNOME 43 (Fedora) and KDE 5.27 (KDE neon).
