### ISSUE TITLE
[Feature Request] Cronjob when device turned off

### ISSUE THREAD

**Issue by newhinton** [bit-team/backintime#1148]
When a device is turned off, or sleeping, no snapshot is being made. It would be great if a snapshot was missed during off-time, it would be started as soon as possible.

**Comment by newhinton** [comment]
I wrote a small script that can be run every x minutes that archieves this:

https://gist.github.com/newhinton/e67a2f95e281e82f57a4784b6986ed27
When using it, please check the comments and adjust accordingly

**Comment by daveTheOldCoder** [comment]
I have backintime scheduled to run every hour. As long as I'm using my computer for more than an hour at a time, that gives me adequate snapshots.

**Comment by Hoimar** [comment]
If you select "Recurring (anacron)" (or whatever the translation is) and select "Every: 1 hour" in the schedule, won't that do exactly the same?

In the docs you can read that this runs a cronjob every 15mins which will check if a new snapshot has to be triggered (or every 60mins if you select "weekly").

**Comment by ayoungethan** [comment]
> If you select "Recurring (anacron)" (or whatever the translation is) and select "Every: 1 hour" in the schedule, won't that do exactly the same?

That's what I thought, but I opened https://github.com/bit-team/backintime/issues/1228 because it doesn't seem to be successfully checking whether it should actually run, it just runs and completes a backup every 15 minutes for some reason.

**Comment by emtiu** [comment]
Hi, I'm closing this issue because the requested feature exists. There are indeed bug reports on it, like #1068 and #1228. We're looking at possible problems there :)
