### ISSUE TITLE
No tray icon on KDE openSUSE Tumbleweed

### ISSUE THREAD

**Issue by sackwort** [bit-team/backintime#1152]
Operating System: openSUSE Tumbleweed 20210406
KDE Plasma Version: 5.21.3
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2
Kernel Version: 5.11.11-1-default
OS Type: 64-bit
Graphics Platform: X11
Processors: 4 × Intel® Core™ i3 CPU 550 @ 3.20GHz
Memory: 11.7 GiB of RAM
Graphics Processor: AMD REDWOOD

Please could someone advise how to get a tray icon to display on the above system?

Before trying-out Tumbleweed I used Kubuntu 20.10 and the tray icon worked as expected.

**Comment by emtiu** [comment]
Hi, thanks for your report. This is a very tricky issue to debug, I've tried to summarize current knowledge in #1306.

It would help if you could:
1. Check if this problem still affects you, and **if yes**:
2. Please give your backintime version, and maybe:
3. Log output, if you find something that looks relevant (like in https://github.com/bit-team/backintime/issues/1098#issuecomment-857316902)

Thanks a lot! :)

**Comment by aryoda** [comment]
Could you please help me to identify the reason for the missing system tray icon by following these instructions:

https://github.com/bit-team/backintime/issues/1306#issuecomment-1321230648

THX a lot!

**Comment by buhtz** [comment]
I vote to close because of missing feedback.

**Comment by ptilopteri** [comment]
I am on openSUSE Tumbleweed and I have a tray icon.

**Comment by aryoda** [comment]
FYI: I am still working on my general fix of all system tray icon issues (#1306) to fix all known edge cases (this issue may be such an edge case)

**Comment by aryoda** [comment]
@ptilopteri 

> I am on openSUSE Tumbleweed and I have a tray icon.

Do you use X11 or wayland? If you use wayland, BiT (root) will not show a systray icon IMHO...
