### ISSUE TITLE
f,g,h, i and j versions for ubuntu have disapeared from PPA stable

### ISSUE THREAD

**Issue by vaurat** [bit-team/backintime#1154]
hello, got a 404 from my groovy 20.10.
http://ppa.launchpad.net/bit-team/stable/ubuntu/dists/ does not contain it. anymore ?

**Comment by buhtzz** [comment]
@vaurat There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

What are f, g, h, i and j?

Tag: Feedback, Distro-Specific

**Comment by emtiu** [comment]
Closing as duplicate of #1136.
