### ISSUE TITLE
GUI icons KDE Plasma compatibility fix suggestion

### ISSUE THREAD

**Issue by Sadi58** [bit-team/backintime#1159]
At the present Back In Time looks out of place under KDE Plasma 5.
To fix this, the following 2 changes are required in `./qt/icon.py` (installed as `/usr/share/backintime/qt/icon.py`).
1. Insert **`'breeze'`** between `'gnome'` and `'oxygen'` in line 19.
2. Replace `'show-hidden'` with **`'view-hidden'`**  in line 62.
This last change (because Breeze icon theme has such an icon already) will then require changing all icon names under `./qt/icons` from `show-hidden.svg` to **`view-hidden.svg`** (which are installed in hicolor icon theme action icons).

**Comment by farion** [comment]
And Icons should work for HiDPI.

**Comment by aryoda** [comment]
I am not sure if the `view-hidden.svg` icon is always available in the desktops but should be installed by BiT (see #507)...

**Comment by aryoda** [comment]
@Sadi58  Very thoughtful proposal!

Could be fixed together with #1306

**Comment by aryoda** [comment]
> And Icons should work for HiDPI.

Did you observe problems with BiT on High DPI displays?

The High DPI settings of our underlying GUI framework `Qt5` are described here

https://doc.qt.io/qt-5/highdpi.html

and in BiT at least the `AA_EnableHighDpiScaling` is activated by default:

https://github.com/bit-team/backintime/blob/3132f4dd4fc627aef46e152696f5b98fb3db0298/qt/qttools.py#L163-L165

**Comment by aryoda** [comment]
I have fixed all known issues (hopefully) with my PR #1480, re-testing and feed-back welcome!

https://github.com/bit-team/backintime/blob/535b1c7bfe04811dec06d1d2599135f373618222/qt/icon.py#L24

https://github.com/bit-team/backintime/blob/535b1c7bfe04811dec06d1d2599135f373618222/qt/icon.py#L95-L97

**Comment by aryoda** [comment]
I am closing this now as fixed and will be contained in the next release.

Please open a new issue in case of any problems.
