### ISSUE TITLE
What happens if you select 'Local Encrypt' after having used "Local' for a year.

### ISSUE THREAD

**Issue by coquizen** [bit-team/backintime#1165]
Since there doesn't seem to be an option to run it via a 'dry-run' and worried that data might be lost, can someone describe backintime's read/write policy when switching over to 'Local Encrypt'? Obviously the preferred approach would be to encrypt retroactively (understanding there there may still be vestiges of un-encrypted data, of which I am not too concerned about for the time being).

**Comment by emtiu** [comment]
Hi, thanks for the question! Unfortunately, backintime is not designed to "convert" your existing backup by encrypting it and preserving the old snapshots and structure.

So if you switched over, a new, encrypted backup would be written, and it won't be incremental on the first run. If you want to have that, it's best to create another profile and start from scratch with that.
