### ISSUE TITLE
 Migrate all settings from a non-main profile to the main profile?

### ISSUE THREAD

**Issue by MostHated** [bit-team/backintime#1171]
Hello,
    I was wondering if there is a way I can simply take all the settings from a non-main profile and apply them to the main profile? The main one was initially a remote location but that is no longer in use, so I want to take one of the other profiles and just move it to the main, then remove that one so I can get rid of the error messages of it being unable to contact the old address. It seems like the profile was/is saved to the actual backup, but is there another location in which it would be safe to do this so backups going forward will use this new config?

Thanks,
-MH

**Comment by Germar** [comment]
You can manually edit the config in `.config/backintime/config`. Just remove all lines starting with `profile1` and change all lines starting with `profile2` to `profile1`.  Finally change `profiles=1`
Make sure to create a copy before starting to edit!

**Comment by MostHated** [comment]
It took me a sec to figure out what was going on, as I did as you recommended but nothing changed. Then I realized that I was running it using the root launcher, so I had two configs, the one bring used was in /root/.config/ but once I changed that one, it fixed everything up. Thanks for the assistance, I do appreciate it. :+1:
