### ISSUE TITLE
Version is still 1.2.0 - forgotten to change to 1.3.0

### ISSUE THREAD

**Issue by schinfo** [bit-team/backintime#1172]
You've forgotten to bump the version !!!

For example look at backintime/VERSION

**Comment by yochananmarqos** [comment]
The changelog was updated, but other files were not. The About dialog (`common/config.py`) still shows 1.2.0. Other files may need to be changed as well:

```
./qt/docbook/en/index.docbook
./qt/man/C/backintime-qt.1
./common/config.py
./common/man/C/backintime.1
./common/man/C/backintime-askpass.1
./common/man/C/backintime-config.1
./VERSION
```

**Comment by Germar** [comment]
Sorry, forgot to push the branch. It's online now
