### ISSUE TITLE
Tests no longer work with Python 3.10

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#1175]
Hi all,

thanks a lot for the update of the package, I already incorporated the changes into fedora. But for f35 the build fails, because python 3.10.
It seems to be caused by using "import collections" and then "collections.MutableSet"
<stdin>:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
[build.log](https://github.com/bit-team/backintime/files/6765291/build.log)

Please see https://github.com/bit-team/backintime/pull/1174

**Comment by Germar** [comment]
Thanks for the PR. But that didn't work on Ubuntu. Please try current master

**Comment by yochananmarqos** [comment]
@Germar The tests still fail with that commit:

```
======================================================================
FAIL: test_powerStatusAvailable (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/backintime/src/backintime/common/test/test_tools.py", line 328, in test_powerStatusAvailable
    self.assertTrue(tools.powerStatusAvailable())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 68 tests in 0.136s

FAILED (failures=1, skipped=9)
make: *** [Makefile:593: unittest-v] Error 1
make: Leaving directory '/build/backintime/src/backintime/common'
```
