### ISSUE TITLE
[Question] can I recover my last backup with a live distro if my system doesn't start anymore?

### ISSUE THREAD

**Issue by SlushThorsten** [bit-team/backintime#1178]
I want to switch from timeshift to back in time,so I want to know if I can recover my last backup with a live distro if my system stops working.
If it works,then how exactly can I do that,would I also have to install back in time in the live distro environment?

**Comment by emtiu** [comment]
Hi, thanks for the question. Backintime doesn't support this kind of operation. It can restore files to their original copies/locations, but it doesn't take care of boot partitions and such. There is a feature request for this capability: #480
