### ISSUE TITLE
Exlude folder by pattern?

### ISSUE THREAD

**Issue by marksarnold** [bit-team/backintime#1179]
Hello,
is it possible to exclude folders using a pattern?
I am trying to exclude all Google Chrome cache folders. The pattern would be something like "*/.config/google-chrome/*/Service Worker/CacheStorage"
There could be multiple such folders in one .config folder, one for each profile. The key part is the wildcard folder in front of the "Service Worker" folder, which denotes the profile name.
The GUI only allows me to browse and select a folder, but not to enter a folder name/pattern.

Thanks,
Mark

**Comment by Germar** [comment]
Take a look at `man rsync` at the section 'Include/Exclude Pattern Rules'. All rsync pattern work with BiT when you use `Add` in `Exclude` config

**Comment by marksarnold** [comment]
Oh, sorry; I didn't realize the "Add" button would let me manually type a pattern. That's what I was missing...
Thank you!
