### ISSUE TITLE
rsync may choke on recursive sylinks, inflating takesnapshot_log to huge size

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#118]
My /.local/share/backintime/takesnapshot_log file has grown to 22.5 GB. Regardless of what happens on my side this should not be possible and should, in my oppinion, be considered a bug. 

And no, I won't be uploading that particular file as a whole ;-)

---

Imported from Launchpad using lp2gh.
- date created: 2013-04-04T17:01:49Z
- owner: hernil
- the launchpad url was https://bugs.launchpad.net/bugs/1164619

**Comment by Germar** [comment]
(by germar)
Wow. That's huge. Was this an initial backup of some 100 million files?
I'll consider to use bz2 to store the log.

Regards,
Germar

**Comment by Germar** [comment]
(by hernil)
It's a backup of my home folder containing about 33 000 files. And no, not the initial backup, even though it has been a while. I'm not quite sure what that file actually does so it's hard for me to guess what might be the reason. 

Nils

**Comment by Germar** [comment]
(by germar)
If you did not delete the file yet, could you please run 
'grep -e "^\[E\]"  ~/.local/share/backintime/takesnapshot_log | bzip2 > error.bz2'

and send me the error.bz2 to germar DOT reitze HOSTED ON gmail DOT com

Regards,
Germar

**Comment by Germar** [comment]
(by hernil)
I'm sorry, I kept it in just this case, but it appears to have been removed somehow by something else.

**Comment by Germar** [comment]
(by hernil)
Happened again. I don't know why. I sent you the grep :-)

**Comment by Germar** [comment]
(by hernil)
I discovered the source of the problem. It was a teamviewer-folder with some sort of infinite symlink recursion that didn't play well with rsync. Don't know if there is any way to check for these sorts of things before doing the actual backup?

**Comment by Germar** [comment]
(by germar)
A quick search on google showed me that the supposed workaround for this is to use rsync with --copy-links (in BIT: Expert Options > Copy links). But I would rather remove or exclude the symlink.
To check for this we would have to scan the entire source folder. I don't think this is worth to do. The better solution would be if rsync could check for this. You can file a bug on rsyncs wishlist if you want.

**Comment by buhtz** [comment]
I asked the opener at Launchpad about feedback

> Dear Nils,
> your Issue is still open and active at the "new" repository.
> 
> https://github.com/bit-team/backintime/issues/118
> 
> Can you give us some feedback about the current state of it.
> Did you use Back In Time? Maybe you find a solution for your symlink problem with the TeamViewer folder?
> 
> If you filled a bug report at rsync (which I strongly recommend!) please link it here.

As I see it a solution won't get implemented in BIT.
But I keep the Issue open until adding this special problem to the documentation/FAQ. So it is a docu feature request.

**Comment by hernil** [comment]
Hey, 
It's been 10 years since the bug report. I appreciate you following up but if nobody else has chimed in since then it's safe to say it doesn't affect many people out there. Please close the bug :-) 

Cheers,

**Comment by buhtz** [comment]
Do you still use BIT?

**Comment by hernil** [comment]
No, unfortunately. There was (is) a lot to like but I ended up moving to btrfs before zfs and using their built in replication functionalities as the efficiency is unmatched (full hourly snapshot replicated from workstation to backup server in ~20 seconds). 

I would love the BiT UI to browse said snapshots though - that would be great! 

Wish you all the best with the project!

**Comment by buhtz** [comment]
Feel free to re-open the Issue if it comes up again.
