### ISSUE TITLE
Deleted Folder in Source dont Sync in Destination V1.3.1

### ISSUE THREAD

**Issue by MGD95** [bit-team/backintime#1187]
Deleted Folder in Source dont Sync in Destination , Only After a Change in Source Folder, if Nothing Change dest folder still include the delete folder

**Comment by buhtzz** [comment]
@MGD95 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing, because the reporter isn't responding, and the description of the problem is incomplete.
