### ISSUE TITLE
Uncaught exceptions in backintime-qt-root

### ISSUE THREAD

**Issue by urilabob** [bit-team/backintime#1191]
It looks like there is a missing set of imported exception handlers in backintime. Sorry, I don't know python at all, so have no idea where to start in trying to debug this. Please see trace below (it also incorporates another bug relating to I/O, but I have reported that separately as it seems they are two separate issues). Specifically, here, there doesn't seem to be a handler for  EOF errors.

System: Linux version 5.14.14-200.fc34.x86_64
Backintime version: backintime 1.3.1

Relevant portions of journal 
Oct 30 09:21:59 bobslin python3[7393]: detected unhandled Python exception in '/usr/share/backintime/qt/app.py'
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: Traceback (most recent call last):
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 69, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: old = termios.tcgetattr(fd) # a copy to save
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: termios.error: (25, 'Inappropriate ioctl for device')
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: During handling of the above exception, another exception occurred:
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: Traceback (most recent call last):
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/qt/app.py", line 1607, in
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: mainWindow = MainWindow(cfg, appInstance, qapp)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/qt/app.py", line 485, in init
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: hash_id = mnt.mount()
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/common/mount.py", line 134, in mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: return backend.mount(check = check)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/common/mount.py", line 420, in mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: self._mount()
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/common/encfstools.py", line 63, in _mount
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: self.password = self.config.password(self.parent, self.profile_id, self.mode)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/common/config.py", line 696, in password
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: return self.pw.password(parent, profile_id, mode, pw_id, only_from_keyring)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/share/backintime/common/password.py", line 200, in password
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: password = getpass.getpass(prompt)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 91, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: passwd = fallback_getpass(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 126, in fallback_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: return _raw_input(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 148, in _raw_input
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: raise EOFError
Oct 30 09:21:59 bobslin backintime-Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: password = getpass.getpass(prompt)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 91, in unix_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: passwd = fallback_getpass(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 126, in fallback_getpass
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: return _raw_input(prompt, stream)
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: File "/usr/lib64/python3.9/getpass.py", line 148, in _raw_input
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: raise EOFError
Oct 30 09:21:59 bobslin backintime-qt-root.desktop[7393]: EOFError
Oct 30 09:22:00 bobslin abrt-server[7409]: Deleting problem directory Python3-2021-10-30-09:21:59-7393 (dup of Python3-2021-10-30-09:09:02-5751)uncaught
Oct 30 09:22:00 bobslin abrt-notification[7416]: [🡕] Process 5751 (app.py) of user 0 encountered an uncaught termios.error exception
Oct 30 09:22:00 bobslin gnome-shell[7419]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Oct 30 09:22:00 bobslin gnome-shell[7419]: > Warning: Unsupported maximum keycode 708, clipping.
Oct 30 09:22:00 bobslin gnome-shell[7419]: > X11 cannot support keycodes above 255.
Oct 30 09:22:00 bobslin gnome-shell[7419]: Errors from xkbcomp are not fatal to the X server
qt-root.desktop[7393]: EOFError
Oct 30 09:22:00 bobslin abrt-server[7409]: Deleting problem directory Python3-2021-10-30-09:21:59-7393 (dup of Python3-2021-10-30-09:09:02-5751)
Oct 30 09:22:00 bobslin abrt-notification[7416]: [🡕] Prouncaughtcess 5751 (app.py) of user 0 encountered an uncaught termios.error exception
Oct 30 09:22:00 bobslin gnome-shell[7419]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Oct 30 09:22:00 bobslin gnome-shell[7419]: > Warning: Unsupported maximum keycode 708, clipping.
Oct 30 09:22:00 bobslin gnome-shell[7419]: > X11 cannot support keycodes above 255.
Oct 30 09:22:00 bobslin gnome-shell[7419]: Errors from xkbcomp are not fatal to the X server

**Comment by urilabob** [comment]
PS sorry about the typo in the heading...

**Comment by buhtz** [comment]
Can you reproduce this with the latest stable release (1.3.3) or the latest development version?

Seems relevant to X and/or Wayland because of `xkbcomp` in the output. Don't know much about it. Maybe aryoda can say if this is relevant.

**Comment by buhtz** [comment]
Feel free to re-open if new information comes up.
