### ISSUE TITLE
[Feature Request] Multiple destinations per profile

### ISSUE THREAD

**Issue by 8070alejandro** [bit-team/backintime#1192]
# Feature

Possibility to add more than one directory as target for backups.

# Use case

In a system with multiple drives, it would be interesting to backup to more than one for redundancy.

# Alternatives and issues

Right now you can create multiple profiles, all of them identical except for the target directory, and make them execute at the same time or sequentially.  
The downside is that, as the source is read multiple times, probably with a noticeable time span in between, there can be inconsistencies between backup instances. There's also more reading than needed, which will take make the backup process slower.

Another possibility is mirroring/RAID (my knowledge on this is limited, so I can be plainly wrong), but it's harder to set for the user than just adding multiple directories as target where we already have to add one.

**Comment by buhtzz** [comment]
@8070alejandro Thanks for your report and your idea.

BIT does use rsync in the background which is not intended to act like this.

IF you need redundancy than you can configure a RAID1.

Close as out-of-scope.

**Comment by emtiu** [comment]
Agreed.
