### ISSUE TITLE
[Feature Request] Installed packages list backup

### ISSUE THREAD

**Issue by 8070alejandro** [bit-team/backintime#1193]
# Feature

Option to include a list of installed packages for each backup.

# Use case

Although not strictly a "file backups" feature, it would be nice that, for each backup run, a file containing all the packages installed on the system could be created. This way it could be easier to restore a system without performing a true "system restore" that could potentially already be problematic, just we wouldn't know yet.

# Alternatives and issues

Using the `user-callback` option on the profile config menu, a command can be set to do it, but it's complicated and at least in my case, I don't know how to reference the directory in which the metadata for each backup is stored (the one containing `backup/`, `config`, `fileinfo.bz2`, `info` and `takesnapshot.log.bz2`).

**Comment by Germar** [comment]
Please take a look at https://github.com/bit-team/user-callback/blob/master/user-callback.apt-backup

**Comment by 8070alejandro** [comment]
Thanks, but that code stores the files in a `/home` subdirectory. I would like it to be stored in the backup directory, the one that is created for each backup.
Is there a way to reference in that script the backup directory that is being created?

**Comment by 8070alejandro** [comment]
Thank you a lot. I will try it when I have time.

**Comment by Germar** [comment]
> Thanks, but that code stores the files in a `/home` subdirectory. I would like it to be stored in the backup directory, the one that is created for each backup.

The user-callback runs before BiT starts to create the new snapshot. So if you include the folder `~/.apt-backup` all necessary files will be in the snapshot. Plus BiT will take care of linking unchanged files.

**Comment by 8070alejandro** [comment]
> The user-callback runs before BiT starts to create the new snapshot. So if you include the folder `~/.apt-backup` all necessary files will be in the snapshot. Plus BiT will take care of linking unchanged files.

Silly of me not to think on this. Good idea.
