### ISSUE TITLE
Preventing backintime from running in the background

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1200]
I have commented all backintime cron jobs, but backintime still starts in the background automatically. How can I stop this behavior?

**Comment by wolftune** [comment]
Is this related to the issue I opened more recently? https://github.com/bit-team/backintime/issues/1209

**Comment by buhtzz** [comment]
@lamyergeier There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug

**Comment by aryoda** [comment]
@lamyergeier Could you please describe the circumstances of the automatic start?

- Which BiT version?
- How and where have you disabled BiT? In the crontab? For your user only or also for root?
  Please check your crontabs with `crontab -l` and `sudo crontab -u root -l` (`-l` = small letter L)...
- Does the problem persist after restarting your computer?

**Comment by buhtz** [comment]
I assume that @lamyergeier mixed user- and root-crontab here.
There is also no feedback from the reporter for over 4 months.

I vote for close.
