### ISSUE TITLE
failed: Invalid argument (22) - Backup Error

### ISSUE THREAD

**Issue by ryankingart** [bit-team/backintime#1205]
I'm trying to backup my computer files on an external hard drive, but after the backup finishes, it says that the backup has errors. When I click on the View Last Log button, to see the errors, it shows me a large list of files that were not backed up.

**Error looks like this:**  [E] Error: rsync: mkstemp  **(Then lists location of file, then the file name)**  failed: Invalid argument (22)

When I look for the file that had the error, its not there in the backup on the external hard drive. So Back in Time is not backing up the files that give the errors. It does backup all of the other files, but not the ones with the errors.

If anyone can hep me figure out the problem, I would really appreciate it.

Thanks!
Ryan King

**OS:** Linux Mint 20.2 Cinnamon
**Back In Time Version:** 1.3.1

**Comment by s-slash** [comment]
I got the same error. I noticed that all the errors relate to file location including the symbol ":".

I didn't find solution for the moment.

**OS:** Manjaro
**Back In Time Version:** 1.3.1

**Comment by ryankingart** [comment]
I figured out the problem. When I formatted my backup hard drive, I didn't set the type to Ext4. In my disk manager, I can see that my computer's hard drive is using Ext4. So I formatted my backup hard drive, set the type to Ext4, and now everything is working correctly.  @s-slash I hope this helps you out.
