### ISSUE TITLE
Unchanged files are backed up

### ISSUE THREAD

**Issue by aakodadi** [bit-team/backintime#1207]
I am using backintime 1.3.1 to back up my home directory, and I noticed that files are getting copied to the snapshot even when they are the same as the last snapshot. Even when I don't change anything to my home directory, the snapshot still takes 250 MB a day. I am aware about #994, but my files have read permission.

I also tried setting `snapshots.use_checksum` to `true` with no success.

#### Example

I have a file in my home directory called `pow.py`.

```
$ ls -l /home/user/pow.py 
-rw-r--r-- 1 user user 566 Oct  4 21:34 pow.py
```

You can see that the file didn't change since Oct  4 21:34. Yet, the two last screenshots Dec 24th and Dec 25th contain the same file.

```
$ ls -l  /mnt/hdd/backintime/my-pc/user/1/20211224-050002-865/backup/home/user/pow.py
-rw-r--r-- 7 user user 566 Oct  4 21:34 /mnt/hdd/backintime/my-pc/user/1/20211224-050002-865/backup/home/user/pow.py
```

```
$ ls -l /mnt/hdd/backintime/my-pc/user/1/20211225-050001-468/backup/home/user/pow.py
-rw-r--r-- 7 user user 566 Oct  4 21:34 /mnt/hdd/backintime/my-pc/user/1/20211225-050001-468/backup/home/user/pow.py
```

Is this supposed to happen? What am I missing?

**Comment by gsker** [comment]
On Sun, 26 Dec 2021, Abdelhakim AKODADI wrote:
[snip]
> $ ls -l /home/user/pow.py 
> -rw-r--r-- 1 user user 566 Oct  4 21:34 pow.py
> 
> You can see that the file didn't change since Oct 4 21:34. Yet, the two last screenshots Dec 24th and Dec
> 25th contain the same file.
> 
> $ ls -l  /mnt/hdd/backintime/my-pc/user/1/20211224-050002-865/backup/home/user/pow.py
> -rw-r--r-- 7 user user 566 Oct  4 21:34 /mnt/hdd/backintime/my-pc/user/1/20211224-050002-865/backup/home/
> user/pow.py
> 
> $ ls -l /mnt/hdd/backintime/my-pc/user/1/20211225-050001-468/backup/home/user/pow.py
> -rw-r--r-- 7 user user 566 Oct  4 21:34 /mnt/hdd/backintime/my-pc/user/1/20211225-050001-468/backup/home/
> user/pow.py
> 
> Is this supposed to happen? What am I missing?
>

You are missing the "7".  If you did another backup today and looked at that 
file, it should have turned into an "8".  That is the number of hard links to 
the file.  The backed up file you are seeing is just another pointer to a 
file that is already backed up -- it doesn't take up another 566 bytes of space.
It's doing it as efficiently as it can.
* Run    /bin/ls -li  to see the inode entry to prove to yourself it is really two pointers to the same file.
* Run    man inode    to read about inodes
* See the last entry in https://rsnapshot.org/faq.html

**Comment by aakodadi** [comment]
Oh, I see. I get it now. Thanks
