### ISSUE TITLE
Flaky test due to process creation

### ISSUE THREAD

**Issue by 2e0byo** [bit-team/backintime#1213]
On my system at least `test_tools` fails on `test_processCmdline`.  

Adding a breakpoint just before the assertion causes the problem to go away, as does adding a `sleep(0.1)` to `createProcess` before returning the pid.  Moving the call to `tools.processCmdline` before the breakpoint shows it returns an empty string unless a short delay is introduced.

I'm not sure if this problem is widespread enough to be important, but I'll add a trivial PR anyway.

**Comment by Germar** [comment]
Thanks @2e0byo
