### ISSUE TITLE
Can't Mount Encfs for SSH Encrypted Backup?

### ISSUE THREAD

**Issue by SarahSzabo** [bit-team/backintime#1220]
I'm trying to back up to my server downstairs, but can't seem to do so due to an error message.

![image](https://user-images.githubusercontent.com/37841645/151413687-56727fb8-b71c-40dc-8493-203cbb3b56f0.png)

root has login SSH keys and can log in without the need for password (although I did type it in the field). I verified with konsole that server is up and can be logged into remotely.

encfs version is:

```
sarah@MidnightStarSign:~$ encfs --version
encfs version 1.9.5
```

There are additional errors for the program though, including some strange ones given that it has root permissions such as:
![image](https://user-images.githubusercontent.com/37841645/151414537-5582d2f1-7d07-46b7-8abc-b7e152ac25ea.png)

Uninstalling BackInTime and removing its config folder in ~/.config didn't seem to solve the issue.
Rebooting does not help, and the issue is persistant at every restart.

**Comment by buhtzz** [comment]
@SarahSzabo There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback

**Comment by buhtz** [comment]
@SarahSzabo Can you give us feedback about your current situation. Did you tried a newer version of BIT? Can you reproduce the problem.

Otherwise we need to close the Issue.

**Comment by buhtz** [comment]
Closing because of no response from issue opener. Please feel free to re-open.
