### ISSUE TITLE
option to automount drive

### ISSUE THREAD

**Issue by Gibbz** [bit-team/backintime#1229]
I have a backup drive in my machine. However its a spinning hdd that spins down. Can you please add an option to automount the drive so that the scheduled backups can be done?

Thanks!

**Comment by gsker** [comment]
This would be done in a `~/.config/backintime/callback script.`
Check out the man page. I have done this in several ways over the years. Currently I'm just setting up /mnt/backup in /etc/fstab as automount, but it's probably safer to NOT have it automount, but rather mount it from the user-callback script.  
Mine was like this before I started doing the automount.

```#! /bin/zsh
setopt allexport
unset DISPLAY

PROFILE=$1
ACTION=$3
CFG=$HOME/.config/backintime/config

discoverpath() {
  BPATH="$(/bin/grep -oP "profile${PROFILE}.snapshots.path=\K.*" $CFG)"
  MNTPOINT="${BPATH%/*}"
  echo Backup Path is $BPATH Mount Point is $MNTPOINT
}

backupmount() {
   echo "mounting ...."
   discoverpath  
   [ -d $BPATH ] || { echo "Mounting $MNTPOINT" ; mount $MNTPOINT && exit 0 ; }
   [ ! -d "$BPATH" ] && { echo "ERROR55: $BPATH mount failed." ; exit 55 ; }
}

backupumount() {
   echo "Umounting ...."
   discoverpath  
   [ -z "$MNTPOINT" ] || { sync ; sync ; umount "$MNTPOINT" ; }
}

case "$ACTION" in
  7) ; backupmount  ;;
  8) ; backupumount ;;
esac

```

**Comment by gsker** [comment]
@emtiu  we can close this ---

**Comment by aryoda** [comment]
Possibly related to #761: Mount unmounted Backup Destination, run, then automatically unmount
