### ISSUE TITLE
Error: rsync: opendir "/home/user/.dbus" failed: Permission denied (13) when backing up after upgrading to GNU/Linux Trisquel 10.0

### ISSUE THREAD

**Issue by deprecated-github-account** [bit-team/backintime#1231]
I can no longer backup since I upgraded my system from GNU/Linux Trisquel 9.0 to GNU/Linux Trisquel 10.0

My terminal prints the following error when I run `backintime backup`:

```
Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Call rsync to take the snapshot
notify-send Back In Time () : Main profile Error: rsync: opendir "/home/user/.dbus" failed: Permission denied (13)
WARNING: Command "rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20220303-170249-815/backup --chmod=Du+wx --exclude=/media/user/backup --exclude=/home/s04tw/.local/share/backintime --exclude=.local/share/backintime/mnt --include=/home/ --exclude=.gvfs --exclude=.cache/* --exclude=.thumbnails* --exclude=[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=.dropbox* --exclude=/proc/* --exclude=/sys/* --exclude=/dev/* --exclude=/run/* --exclude=/etc/mtab --exclude=/var/cache/apt/archives/*.deb --exclude=lost+found/* --exclude=/tmp/* --exclude=/var/tmp/* --exclude=/var/backups/* --exclude=.Private --include=/home/** --exclude=* / /media/user/backup/backintime/x220/user/1/new_snapshot/backup" returns 23
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
```
I ran a search for similar errors in Issues and found https://github.com/bit-team/backintime/issues/559 but I can't see `decrypt paths` in the last snapshot log - only this error:

`[E] Error: rsync: opendir "/home/user/.dbus" failed: Permission denied (13) `

What can I try to do to fix this?

(MATE Desktop Environment 1.24.0)

**Comment by deprecated-github-account** [comment]
> What do you see in your backup destination directory, --link-dest=../../20220303-170249-815/backup ?
> a.k.a /media/user/backup/backintime/x220/user/1/20220303-170249-815/backup

I see:

```
user@x220:/media/user/backup/backintime/x220/user/1/20220303-170249-815$ sudo du -h -a --max-depth=1 . 
4,0K	./takesnapshot.log.bz2
15G	        ./backup
4,0K	./info
0	       ./failed
996K	./fileinfo.bz2
8,0K	./config
15G	.
```

Thank you for asking me to check the last backup destination directory, I did not think ./backup would be 15G. In other words, I did not think that most of the backup went through, and that the error only apply to the .dbus directory.

As you suggested in your last sentence, I looked up the permissions of the .dbus directory. It was owned by root. I ran `user@x220:~$ sudo chown -R user:user .dbus` (user is the username).

Then I tried `backintime backup`. It printed this:

```
Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
```

Looks like everything is in order.

Thank you.

I will close this issue later if @gsker think there is nothing to add.




----

> And by snashot log do you mean takesnapshot.log ??

No. I understood from https://github.com/bit-team/backintime/issues/559#issuecomment-201906035 that the "snapshot log" @Germar mentioned was "View Snapshot Log" from Back In Time's Graphic User Interface application.

**Comment by gsker** [comment]
I'm not sure where that UI log data comes from.  I'll check later.  I'm glad it worked out!
