### ISSUE TITLE
[Arch] Build test fails & installation is aborted

### ISSUE THREAD

**Issue by Kleysley** [bit-team/backintime#1233]
I've been trying to install backintime on my Arch installation (kernel 5.16.13).
No matter if I build it from source or whether I try to install the gui or the cli version, the build always fails the same way.
Here is the console output:

```
Ran 19 tests in 0.029s
OK
python -m unittest  -b test/test_argparser.py
.....................
----------------------------------------------------------------------
Ran 21 tests in 1.990s

OK
python -m unittest  -b test/test_backintime.py
FF
Stderr:
/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/test/test_backintime.py:33: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))

======================================================================
FAIL: test_local_snapshot_is_successful (test.test_backintime.TestBackInTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/test/test_backintime.py", line 68, in test_local_snapshot_is_successful
    self.assertEqual(proc.returncode, 0, msg)
AssertionError: 1 != 0 : Returncode: 1
stderr: Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/backintime.py", line 1165, in <module>
    startApp()
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/backintime.py", line 517, in startApp
    args.func(args)
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/backintime.py", line 1150, in checkConfig
    cfg = getConfig(args)
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/config.py", line 280, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/tools.py", line 1719, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3.10/site-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.10/site-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

stdout: 
Back In Time
Version: 1.3.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Update to config version 6


======================================================================
FAIL: test_quiet_mode (test.test_backintime.TestBackInTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/test/test_backintime.py", line 33, in test_quiet_mode
    self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))
AssertionError: '' != 'Traceback (most recent call last):\n  Fil[2338 chars]de 1'
Diff is 2416 characters long. Set self.maxDiff to None to see it.

Stderr:
/home/kleysley/.cache/yay/backintime/src/backintime-1.3.1/common/test/test_backintime.py:33: DeprecationWarning: Please use assertEqual instead.
  self.assertEquals("", subprocess.getoutput("python3 backintime.py --quiet"))

----------------------------------------------------------------------
Ran 2 tests in 0.335s

FAILED (failures=2)
make: *** [Makefile:566: unittest] Error 1
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: backintime (backintime-cli)
 `
```

**Comment by aryoda** [comment]
On which type of file system are you building and executing the unit test?

**Comment by aryoda** [comment]
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner:
> Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

Looks like the BiT serviceHelper service is not running (or accessible) so that no communication can be established via the DBus inter process communication bus...

The 2nd exception seems to confirm this:
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited:
> Launch helper exited with unknown return code 1

I see no way to reproduce and diagnose this exactly but it is probably related to
- some build dependencies are missing (dbus from PyQt5 or python)
- missing rights to attach a service to dbus
- Python 3.10 (which is used here) and BiT version 1.3.1 is from the same day as the merge of this issue: #1175 (Tests no longer work with Python 3.10).
dev.CONNECTION, SetupUdev.OBJECT)

**Could you already solved this issue or narrow it down?**

**Comment by Kleysley** [comment]
Some info:
I'm on on the newest version of Arch linux (filesystem is EXT4). I have Python 3.10.6 installed on my system, that's the version that's currently distributed with Arch. I tried both the AUR package of backintime and the manual build. Both fail to do so, even with the newest version (1.3.2-2).

The installation still fails with the same error. I don't know what to do about missing rights to attach a service to dbus and also don't know how to check for missing build dependencies.

**Comment by aryoda** [comment]
OK, thx for your clarification.

Normally this problem should be passed on to the AUR package maintainer too, probably here:
https://aur.archlinux.org/packages/backintime-cli

The package maintainer should be able to fix missing dependencies or report here "upstream" if there should really be a general problem (eg. with Python 3.10.x or undocumented dependencies)...

Meanwhile I have pulled the current source code on Ubuntu 20.04 with Python 3.8.10 and built it with the usual `make`.

Starting the unit tests in `common/` with `make unittest` then throws a dbus (!) error:

```
ModuleNotFoundError: No module named 'dbus'
...
python3 -m unittest  -b test/test_applicationinstance.py
E
======================================================================
ERROR: test_applicationinstance (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_applicationinstance
...
```

I have installed the missing dbus module via `sudo apt install python-dbus` then - it did not change it.

I have tried to install `dbus` via `pip` with `pip install dbus` and get this error:

> ERROR: Could not find a version that satisfies the requirement dbus (from versions: none)
> ERROR: No matching distribution found for dbus

**Big question to our developers here: Is this reproducible? Is the `dbus` package deprecated or broken?**

**Comment by aryoda** [comment]
It seems `pip3 install dbus-python` solved the problem for me on Ubuntu (NOT Arch), unit tests do run OK now...

Can someone please cross-check and confirm this?

**Comment by emtiu** [comment]
Thank you for your report, @Kleysley. Please see the latest comments in #921, of which this Issue is a likely duplicate.

**Comment by aryoda** [comment]
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

I think our generated `Makefile` has a chicken-egg type of problem for first-time installations when I look into the `PKGBUILD` (which seems to follow our documented `configure/make/make install` way):

`make test` already requires an already installed `serviceHelper` - see https://github.com/bit-team/backintime/issues/921#issuecomment-1275364552 - but is only installed in a later script step **after** succeeding all unit tests (`make install` of `qt` folder)...

So if BiT was installed once successfully with `make install` from `common` **and** `qt` the unit tests should succeed!
