### ISSUE TITLE
v1.3.2: make test fails

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#1234]
Seeing a failure running `make test`, first failure is on `test_processCmdline (test.test_tools.TestTools)`:
```
python -m unittest  -b test/test_tools.py
.....s.....s.s..s......s......F.........s..s.s...ss.s.s.............
======================================================================
FAIL: test_processCmdline (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/backintime/src/backintime-1.3.2/common/test/test_tools.py", line 262, in test_processCmdline
    self.assertRegex(tools.processCmdline(pid),
AssertionError: Regex didn't match: '.*/sh.*/common/test/dummy_test_process\\.sh' not found in ''

----------------------------------------------------------------------
Ran 68 tests in 0.063s

FAILED (failures=1, skipped=12)
make: *** [Makefile:577: unittest] Error 1
```

**Comment by Germar** [comment]
I just set up a new arch VM but I can not confirm the failure.
That unittest starts a dummy process `common/test/dummy_test_process.sh` and test reading `/proc/{PID}/cmdline` from the process. Please run `make test-v` and post the output of the failing test. Please also check if `common/test/dummy_test_process.sh` is executable, start it manually and post the content of `/proc/{PID}/cmdline` for that process.

**Comment by graysky2** [comment]
@Germar - Yes!  https://github.com/bit-team/backintime/pull/1214 fixed the issue.
