### ISSUE TITLE
how to consolidate backup drives

### ISSUE THREAD

**Issue by jpaulbiss** [bit-team/backintime#1235]

**Comment by jpaulbiss** [comment]
I have been using backintime for quite a while, since about 2012. These backup have been fragmented across a number of hard drives, 2-3  years on each disk.
Is there any way I can combine all these disks in to one large backup and also maintain a backup of that drive.
I tried to copy the 600GB backups on a 1TB disk to a 3TB disk using
 rsync -av /media/jpb/Downloads /media/jpb/Downloads-01
The first error was 
ending incremental file list
rsync: mkdir "/media/jpb/Downloads-01" failed: Permission denied (13)
rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]

I did a chmod 777, chown jpb, chgrp users
rsync started to copy.
After hours I got an error that the 3TB drive was full.

**Comment by gsker** [comment]
It won't be easy, but I think if you look at the command that backintime uses when it does its backups then you might be able to  can deduce what you need to do to consolidate.  Test first though. 
I pulled this from my backintime.log file:
`Mar 12 20:06:00 veeta backintime (root/2): WARNING: Command "rsync --recursive --times --devices --specials --hard-links --human-readable --links --acls --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20220309-200001-559/backup --chmod=Du+wx  ........
`
The ....  were just a bunch of includes and excludes with the source and destination at the end.

The steps you will need to do will be to take each of your backup directories in order and for each of them run a new rsync command like this one, but the argument `--link-dest` will point to the prior backup.  That tells the --hard-links command what to hard-link to.  You will likely want to not do --delete, and you might need to do --relative (-R).
I have not done this, but that's what I would try.  I'm going to test it now.

**Comment by jpaulbiss** [comment]
Before your last reply I tried the following and it seem to work:
rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i /media/jpb/Downloads/  /media/jpb/Downloads-01/
I used backintime and I was able to do a backup and navigate the folder tree.

However this was just transferring the contents of one drive to another and not the contents of multiple drives to one.
I’ll give your script a try if I can remember hoe to write one, Haven’t done this in 20 years,. :)

**Comment by gsker** [comment]
It sounds like you've got the hang of it -- could you close this issue?

**Comment by jpaulbiss** [comment]
Consider it closed. Thanks so very much.

**Comment by gsker** [comment]
Hmmm. Not so much a feature for the app, but for inclusion in the docs, eh?.
