### ISSUE TITLE
advice please

### ISSUE THREAD

**Issue by jpaulbiss** [bit-team/backintime#1239]
I would like to have two disks for my backups in case one dies. What would be the best way to configure backintime to do this?
Thanks

**Comment by emtiu** [comment]
I would just create two profiles, with different target locations. You'll have to make sure that settings and exceptions are the same for both profiles, but it's the most robust way. Fancier solutions include RAID mirroring of the two drives or something.

Keep in mind that a drive connected to the system can still be deleted accidentally or by malicious software, or in an electrical incident. Maybe consider making one disk removable. You'll have to connect it manually for backups, but it will be much safer from incidents.

**Comment by jpaulbiss** [comment]
Thanks.
Would it possible to make a copy of the first profile and just change the name and destination?
I can redirect where to save the snapshot from the profile panel; but that is temporary.

**Comment by emtiu** [comment]
I don't think there's a built-in function for that, but you could look at the config files and check out how the profiles are saved.

In any case, it would surely be a separate profile with its own settings, not an adapting "clone" that mirrors settings from the other one.

**Comment by jpaulbiss** [comment]
Thanks. If I manually start a snapshot, which I do with a couple of disk since they are not what you would call high traffic,. I can change the destination drive from the settings panel.  I have tested this a half dozen time and it does not seem to cause any issues.
