### ISSUE TITLE
Can't backup root over ssh (Permission Denied (13))

### ISSUE THREAD

**Issue by g1sbi** [bit-team/backintime#1241]
I'm trying to set up a root backup over SSH, but I'm getting permission errors over protected folders. How can I fix this?

**Comment by nodiscc** [comment]
You should provide logs of the error, as well as the output of `ls -l` or `ls -ld` on the problematic files/directories. And provide relevant parts of your `~/.config/backintime/config` file

**Comment by emtiu** [comment]
Closing because we haven't heard from the reporter in months, and can't reproduce the problem.
