### ISSUE TITLE
Automatically Select Profile Based on Connected Drive

### ISSUE THREAD

**Issue by fooltopia** [bit-team/backintime#1249]
I have two profiles which back up parts of my data to different external hard drives which I only connect when I want to make a backup. At the moment, I have to manually select the profile that matches the connected external hard drive, which is a bit tedious. 

Back In Time during startup already checks if the backup drive is available and displays a warning if it's not. What I would like it to do is to check for each profiles if the backup drive is available and select the first profile which matches a connected drive. 

If this option is already available, please let me know where I can find it. Otherwise, I would love if you could add it. Thank you for your consideration. 

And thanks for this amazing software. It makes managing backups super easy.

**Comment by emtiu** [comment]
I don't think there's a specific feature for this. The way I do it is to maintain two separate profiles with identical settings (includes, schedule etc.), but different mountpoints. Whichever drive is connected gets the backup (or both!).

Alternatively, you might be able to script something around a symlinked mountpoint, but I haven't tried that.

**Comment by fooltopia** [comment]
Sounds like you're using automated backups. In my case, I'm doing the backups manually. 
But you're right, I can probably script something. I've been using the GUI and it never occurred to me to look at the command line options. 
Thanks for the tip.
