### ISSUE TITLE
Log Output stopped

### ISSUE THREAD

**Issue by btberlin** [bit-team/backintime#1251]
Back in time 1.3.2.  Ubuntu 20.04.3.  Backing up to a USB disk formatted ext4.  There is no log output.  Previously, backing up to a USB drive formatted NTFS the log output worked fine.  How to start logging?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Please start backintime in a terminal with option `--debug` and show the terminal output here.

**Comment by emtiu** [comment]
Closing because we haven't heard from the reporter in two months, and can't reproduce the problem.
