### ISSUE TITLE
laptop backup

### ISSUE THREAD

**Issue by cscyberprof** [bit-team/backintime#1255]
Running BiT on a latop (which may be sleeping/hibernating or unable to contact the scp server at the precise moment that cron issues the BiT command means that long periods can pass w/o backups taking place even though everything is technically in working order.

This is, of course the way cron works but I wonder if I am missing some more elegant solution than periodically calling my thrown-together script below which wakes up to make sure that  there is a backup ~ every 6 hours or at the next reasonable opportunity but not more often to avoid backup-clutter.

Is there a way to make BiT itself do this?

update: There is reference in the faq to a "Repeatedly" schedule that would provide this function but I can not find this in the interface. 
I have updated the code to use _backup instead of backup-job as is used in cron since, if the laptop is on and has connectivity to the scp server, it should certainly backup.
`

```
#!/bin/bash
while true; do

#get the time of the last backup (using the filename -- hope they keep that syntax he he

# So now I am making this smarter by making it check for changes in the Dcouments folder as a trigger also.
LASTBACK=$(backintime --profile 'Main profile' last-snapshot | awk ' /SnapshotID/ { split($2,a,/\-/);b=substr(a[2],1,4); printf("%sR%s",a[1],b)}')
if [ -z "$LASTBACK" ] ; then # we got nothing -- quit
        echo failed to get last backup time. $(basename "$0")  Quitting | systemd-cat -p "err"
        exit
fi
#How much time has pass since the last backup (in seconds)
((elapsed=$(date +"%s")-$(date +"%s" -d "${LASTBACK}") ))
#Has it been longer than 6 hours (in seconds) OR have their been Changes in ~/Documents 
if [[ elapsed -gt 21600 ]]   || 
         [[  $(find /home/eric/Documents/ -mount -newermt "$(date -d $LASTBACK)") ]] ; then 
        echo $(basename "$0") initiating backup | systemd-cat
        notify-send -i  /usr/share/icons/gnome/22x22/actions/back.png  "Back In Time Snapshot starting $(date  +'%H:%M')"
#       /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null
        /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup >/dev/null
        notify-send -i  /usr/share/icons/gnome/22x22/actions/back.png  "Back In Time Snapshot finished $(date  +'%H:%M')"
        echo $(basename "$0") completed backup | systemd-cat
else
        notify-send -i  /usr/share/icons/gnome/22x22/actions/back.png  "Only $(date -d@$elapsed -u +%H:%M) since last backup. Skipping" 
fi

sleep 15m ; done

`
```

**Comment by emtiu** [comment]
Thanks for your suggestion and code!

Another solution that people have suggested is support for fcron, which can apparently do the same. This is discussed in #610.

**Comment by emtiu** [comment]
Sorry for the confusion – the feature you are looking for really does exist. It's called "Repeatedly (anacron)" in the Schedule settings:

![Screenshot_20220914_235207](https://user-images.githubusercontent.com/2159933/190269832-ce211ca6-508b-4e7d-b6ce-748f91dacee2.png)

Take a look at https://github.com/bit-team/backintime/issues/1228#issuecomment-1247327529 for a description of how it works.
