### ISSUE TITLE
minimum free space needed : overestimated ?

### ISSUE THREAD

**Issue by Saroumane** [bit-team/backintime#1257]
backintime version used : 1.2.1 (from Ubuntu 21.10), then 1.3.2 from ppa

Hello, I think I have a strange "minimum free space on disk" problem.
I use backintime everyday on my main internal HDD backup without problem.
Once in a month, I try to backup on an 2 TB HDD I keep offsite. (with a dedicated "Remote" profil in backintime. The HDD is USB3 plugged for the operation)
On this "remote" HDD I have 46 GB of free space left. The last backup was on the 2nd of May.
Today I can't make a new incremental backup. It fails like this :

```
june 05 16:35:02 host backintime-qt-root.desktop[24077]: Back In Time
june 05 16:35:02 host backintime-qt-root.desktop[24077]: Version: 1.2.1
june 05 16:35:02 host backintime-qt-root.desktop[24077]: Back In Time comes with ABSOLUTELY NO WARRANTY.
june 05 16:35:02 host backintime-qt-root.desktop[24077]: This is free software, and you are welcome to redistribute it
june 05 16:35:02 host backintime-qt-root.desktop[24077]: under certain conditions; type `backintime --license' for details.
june 05 16:35:02 host backintime-qt-root.desktop[24077]: INFO: Lock
june 05 16:35:02 host backintime-qt-root.desktop[24077]: INFO: Take a new snapshot. Profile: 2 Remote
june 05 16:35:02 host backintime-qt-root.desktop[24077]: INFO: Call rsync to take the snapshot
june 05 16:35:02 host backintime-qt-root.desktop[24077]: notify-send Back In Time (user) : Remote Error: rsync: [sender] write error: Broken pipe (32)
june 05 16:35:02 host backintime-qt-root.desktop[24077]: notify-send Back In Time (user) : Remote Failed to take snapshot 2022-06-05 15:29:20 !!! 
```

I suspect there is not enough space left on disk to deal with the new backup : I monitor the free space (using `df`), and it quickly falls to 0% . Meanwhile backintime continue to backup for a long time, before failing.
I don't understand what happens : since last month I think have 3 or 4 GB of new data (maximum)

Last month I already had the problem for the 1st time, and I had to start a complete (and slow) backup from scratch, after I emptied the HDD.

Do you have any advice about how to deal with this ? (Apart from "buying a bigger disk" ? :)

Is it "dangerous" to try a "dry run" like described here ?
https://github.com/bit-team/backintime/issues/248

**Comment by Saroumane** [comment]
Meanwhile I did a quick check against folders keeping my daily backup on my HDD backup : 

```
du -hc --max-depth=0 20220430-070001-668 20220604-070001-628
1,7T	20220430-070001-668
157G	20220604-070001-628
```

So I guess I was completely wrong, I have more or less ~150 GB of new data since last month.
I still does not understand from where it comes from :)

**Comment by gsker** [comment]
I experienced this recently.  For me the time taken at the end turned out to be the cleanup process where all the files get deleted.

And the reason it ran out  space was because the link that points to last_snapshot was pointing to a location that did not have all the files so it was not really doing an incremental -- it was copying all of it.
