### ISSUE TITLE
How to force full snapshot?

### ISSUE THREAD

**Issue by lobneroO** [bit-team/backintime#1265]
I am new to BackInTime (and actually have not used it yet). 
So far as I understand, BackInTime creates incremental snapshots. This would require me to keep all snapshots forever, until I do a new full backup.
I have not seen how to do that though? So far as I could see, every backup would be incremental and there is no setting to tell it otherwise.
I have looked through the docs and the FAQ, but couldn't find anything on that.

**Comment by emtiu** [comment]
There's probably a misunderstanding about how backintime works.

It uses the `rsync` program to create backups, and `rsync` is instructed to create hardlinked copies of identical files. Additional hardlinks to unchanged files do not use additional diskspace.

So, backintime's backups are **_incremental_** in the sense that only changed files are copied when creating snapshots. But also, each snapshot is a **_full backup_** in the sense that it contains every file from the source.

Over time, files that are always unchaged will be referred to by many hardlinks in the backup filesystem (as in: a file that is identical in 100 snapshots will only exist on disk once, but have 100 hardlinks pointing to it). On the other hand, files that often change will exist in many copies, all different, and each taking up space for itself.

Whenever you delete a snapshot, backintime removes hardlinks from unchanged files, and only fully deletes a file if it was unique in that snapshot. Therefore, even if you delete the oldest snapshot, the next one remains a "full backup", as it always was.

Feel free to ask again if you have more questions :)
