### ISSUE TITLE
Error message while restoring: "rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]"

### ISSUE THREAD

**Issue by deprecated-github-account** [bit-team/backintime#1273]
When I restore from the last snapshot on a new system (Trisquel Nabia 10.0.1), the progress bar (at the bottom of "Back in Time" GUI) stalls at: `88% | sent: 69.10G | Speed: 21.52MB/s | Working:`

However,  based on the size of the restored folder /home, the restoration job seems to be completed. The size of /home restored and the size of /home of the last snapshot are almost the same 75,5 GB (74,6 GB on disk) for the restored folder /home and 75,5 GB (74,8 GB on disk) for /home of the last snapshot. The total number of items are identical "83.163 items, totalling", according to right click > Properties > Contents.

The other window named "Restore" displaying the log shows with a "fail" at the beginning, and an error at the end:

```
rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive -R -v --backup --suffix=.backup.20220822 /media/<user>/backup-<user>/backintime/<computername>/<user>/1/20220820-162441-120/backup/./home/<user> /
building file list ... done
rsync: chgrp "/home" failed: Operation not permitted (1)
home/
[113000+ lines with paths of restores files]
sent 69.13G bytes  received 2.09M bytes  22.43M bytes/sec
total size is 77.65G  speedup is 1.12
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
 
 
Restore permissions:

Restore permissions: Done
```

Does someone know why the log displays: `rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]` and why the progress bar stops at 88%?

---
This issue https://github.com/bit-team/backintime/issues/1075 from 2020 mentions the same problem.

**Comment by aryoda** [comment]
Questions:
1. How did you start the restore process "on a new system" (which menu item from the BiT GUI or manually via pure `rsync`)?
2. What is the the file system of the restore source and target?
3. Which version of `rsnyc` is installed on your system?

Ignoring the frozen progress bar: The error itself in `main.c` is a `rsync` error (BiT has no C code itself), so there are possibly two  roadworks:

1. BiT: Catch `rsync` error to reflect errors in the progress bar
2. Examine `rsync` error (has nothing to do with `rsync` IMHO

**Comment by aryoda** [comment]
If your target for restoring the backup is **not** a Linux file system (but NTFS, FAT32, or another Windows file system) restoring the group, owner and permissions is not possible since the target file system does not support the same permission system...

**Comment by deprecated-github-account** [comment]
Thank you for your questions. Please find the answers below:

1. I used BiT's GUI, so in the menu of BiT's GUI I clicked on Restore 
2. The file system of the restored source is ext3 and the target is xfs. I looked up what a file system on Wikipedia to make sure I provide you with the correct answer. I will copy the output of `$ mount ` in case I missed something:
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=3983148k,nr_inodes=995787,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=802756k,mode=755)
/dev/sda3 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15815)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
/dev/sda4 on /home type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=802752k,mode=700,uid=1000,gid=1000)
/dev/sdb1 on /media/<user>/backup-<user> type ext3 (rw,nosuid,nodev,relatime,uhelper=udisks2)
/dev/sdc1 on /media/<user>/3AC5-25F8 type vfat (rw,nosuid,nodev,relatime,uid=1000,gid=1000,fmask=0022,dmask=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,showexec,utf8,flush,errors=remount-ro,uhelper=udisks2)
```

The source is:
`/dev/sdb1 on /media/<user>/backup-<user> type ext3 (rw,nosuid,nodev,relatime,uhelper=udisks2),`
And since I am trying to restore to /home, I guess the target is:
`/dev/sda4 on /home type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)`
3. `$ rsync -v` outputs "rsync version 3.1.3 protocol version 31"

Thank you for discerning between the two possible errors. I am interested in fixing the `rsync` error for now, shall I take this discussion/issue elsewhere e.g. on `rsync`'s repository or mailing list? Or can we carry on investigating the `rsync` error on BiT's repository?  If we can carry on here, I will search online for this rsync error[1] and report here.

[1] `rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]`

**Comment by aryoda** [comment]
THX for your details!

The ext3 and xfs mount options look OK for rsync with permissions.

Did you start `rsync` as root (may possibly be needed since changing the owner or setting permissions of a file may require this)...

BTW: rsnyc'ing from ext3 to xfs with permissions was reported as having problems here (I am not sure if it applies in your case):

WayneD/rsync#301

IMHO continuing the `rsync` discussion here should be OK to keep this issue visible for others with similar problems.
If you find out more please post it here. I have no further idea but if you'd manage to create minimal reproducible example (eg. with two anonymized small files) like in the mentioned issue above it would allow us to examine it further...

**Comment by deprecated-github-account** [comment]
> Did you start rsync as root (may possibly be needed since changing the owner or setting permissions of a file may require this)...

No.

Your question reminded me that there are two ways to start BiT'S GUI, "Back in Time" and "Back in time (root)". I had started "Back in Time" (**not** root).

I just tried to restore a small folder with a few files that was in /home/<user>/Desktop **with "Back in Time (root)"**. This is the log found in the window named "Restore (as superuser)":

```
rsync --recursive --times --devices --specials --hard-links --human-readable --links --perms --executability --group --owner --info=progress2 --no-inc-recursive -R -v --backup --suffix=.backup.20220823 /media/<user>/backup-<user>/backintime/<computer>/<user>/1/20220820-162441-120/backup/./home/<user>/Desktop/photo_<photodescription>/
building file list ... done
home/
home/<user>/Desktop/photo_<photodescription>
home/<user>/Desktop/photo_<photodescription>/F1000002.JPG
home/<user>/Desktop/photo_<photodescription>/F1000002.png
home/<user>/Desktop/photo_<photodescription>/F1000002.xcf
home/<user>/Desktop/photo_<photodescription>/F1000003.png
home/<user>/Desktop/photo_<photodescription>/F1000003.xcf
home/<user>/Desktop/photo_<photodescription>/F1000004.JPG
sent 63.84M bytes  received 136 bytes  18.24M bytes/sec
total size is 63.83M  speedup is 1.00
 
 
Restore permissions:
chown /home 0 : 0

Restore permissions: Done
```

There is no more `rsync` error. It seems that my mistake was to omit to restore from root (i.e. from "Back in Time (root)" instead of "Back in Time").

The second error @aryoda mentioned in https://github.com/bit-team/backintime/issues/1273#issuecomment-1223302602 with BiT's progress bar seems to persist though. The progress bar of the same restore process I shared the log of above displays:
`
65% | Sent 41.86M | Speed: 25.85MB/s | Working:`

The folder (and the files) are restored though. The restore source folder and the restore target folder are the same size (and have the same number of items.)

**Comment by aryoda** [comment]
> There is no more rsync error. 

Good to hear that (I hope it also works when restoring the full backup).

> BiT's progress bar seems to ... [be not updated]

OK, leave the issue open, **a developer must check the progress bar update event handler of the restore GUI.**

Furthermore **I suggest to add a "use-case-driven" documentation** "I want to... how can I do this", here mainly:

1. Restore a backup with permissions: Use "Back In Time (root")...

**Comment by deprecated-github-account** [comment]
Noted. Thank you for your help, @aryoda. I will report here if/when I restore a full backup to confirm that there is no `rsync` error. I have no plans to do so now though.

Good point on the documentation. I looked on https://backintime.readthedocs.io/en/latest/ but could not find documentation on "how to restore". Maybe I missed something.

Shall a new Issue be open with regards to the progress bar issue so that we can close this issue (about `rsync`'s error)? Another Issue could also be opened with regards to the suggestion about the documentation. That said, I don't see any of the two as blocking so I am happy leave it for now and close this issue.

**Comment by aryoda** [comment]
@deprecated-github-account I have created two new issues as "spin-out". I propose that you close this issue now...

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
@emtiu We have consent to close this Issue.

**Comment by deprecated-github-account** [comment]
I am closing this issue. 

See https://github.com/bit-team/backintime/issues/1275 to follow up with the bug of the progress bar of BiT's GUI (c.f. https://github.com/bit-team/backintime/issues/1273#issuecomment-1223302602) and  #1276 to carry on the discussion on documentation.
