### ISSUE TITLE
Documentation: Master issue for improvments (please reference all doc-related issues here)

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1276]
Please try to link all documentation-related issues in this "master issue" to help doc writers to get an overview.

# User docs

- Add a use-case driven ("how can I...") documentation to BiT (#1273)
  - different restore scenarios (#1168)
  - restore keeping the file permissions (https://github.com/bit-team/backintime/issues/1273#issuecomment-1224915199)
  - how to move existing snapshots to a new folder/drive (#1009) -> is currently contained in the FAQ
  - expert options for copingy links (#182)
- add requirements for using remote server shells (#1082)
- what happens if I remove snapshots (#875)
- Restrictions in using different file systems as backup source and restore target folder (ext3, ext4, xfs, NTFS, fat32...):
  - hard links (#924)
- FAQ
  - FAQ not mentioned in Spinx doc (#1237)
  - when to use "BiT (root)" (and why)
- Installation dependencies
  - Missing dependencies for dbus and qt5 (#871)
- Update Web-Site (#504)

# Dev docs
- How to contribute as pull request
  - git commands (create local branch, create pull request...)
  - which py file to start in the dev IDE (for GUI `qt/backintime-qt` and backend `common/backintime`): 
  - required acceptance criteria (Travis CI succeeds, changes contain unit tests...)
  - how to edit man page files
  - how to run the unit tests (see make targets in folder 'common' after calling `./configure`)
  - how to implement and run unit test
  - how to create and apply a patch file for other developers as alternative to pushed "public" branches

**Comment by emtiu** [comment]
Issue #182 also belongs here – and, we now have the https://github.com/bit-team/backintime/labels/Documentation label :)

**Comment by aryoda** [comment]
I have added #182 to the above list.

This master issue could be dropped if every linked issue was tagged correctly.
Are there enough active contributors who have the right to tag issues in this repo?

**Comment by emtiu** [comment]
> This master issue could be dropped if every linked issue was tagged correctly.

I will prioritize that, then, because I enjoy closing Issues ;)

> Are there enough active contributors who have the right to tag issues in this repo?

Unfortunately, it's just me for the moment, but we're working to remedy that situation.

If you have't already, you're welcome to join the mailing list where we coordinate our work: https://mail.python.org/mailman3/lists/bit-dev.python.org/

**Comment by emtiu** [comment]
> This master issue could be dropped if every linked issue was tagged correctly.

Done! When you find a new issue that needs the https://github.com/bit-team/backintime/labels/Documentation Label, feel free to @-mention me in a comment (until we get the permissions sorted out better).
