### ISSUE TITLE
FR: Disable the notifications for removable drives

### ISSUE THREAD

**Issue by isle9** [bit-team/backintime#1277]
The app keeps sending me notifications that my snapshots folder can not be found and that I should connect my removable drive if it's on there even though I've disabled automatic backups.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
How do you make sure that you disabled automatic backups?

Can you please start BIT via `--debug` option in the terminal and send us the debug output?

Please send the content of `/etc/crontab`.

Also please give us information about operating system version, BIT version.

**Comment by isle9** [comment]
I think I've figured it out.
