### ISSUE TITLE
Improve issue mangement: Add templates

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1278]
**Current status:**

Issues are currently reported via free text entry without any guidance about the requires or minimal content.

**Consequences:**

Issues do often not contain enough information to narrow down the problem (eg. OS, desktop environment, BiT version, rsync version...).
or even to reproduce it.

**Proposed improvement:**

Add github issue templates for
* bugs
* feature requests
* documentation

The templates shall specify the minimal required information and link to more detailed documentation how to obtain them (if required).

**Implementation hints:**

Use the Github feature "issue templates" to set up the Github standard templates and modify them as required:

Within the repo "bit-team/backintime": _Settings > General > Issues > Set up templates_

**Comment by emtiu** [comment]
Thanks for the idea! It looks like I don't have access to those settings at the moment (permissions here are work in progress).

I would agree with @buhtzz that we should keep the template short and sweet. Three points maybe?
1. What's your OS and backintime version?
2. If you know it: What's your desktop environment (GNOME, KDE etc.)
3. Please find your version of rsync (`rsync --version`)?

**Comment by aryoda** [comment]
> It looks like I don't have access to those settings at the moment (permissions here are work in progress).

I used my own repo to check this (I also have no rights for this repo)

>     1. What's your OS and backintime version?
>     2. If you know it: What's your desktop environment (GNOME, KDE etc.)
>     3. Please find your version of rsync (`rsync --version`)?

For best reproducibility of problems I would also like to know
- the Python version
- in case of restore problems: the source and target file system type

A nice feature of the BiT GUI and command line tool would be a "diagnostics" output with all this, eg.

```
$> backintime --diagnostics
Ubuntu 20.04.01
BiT 1.3.2
Python 3.10
rsync x.y
PyQt x.y
...
```

**Comment by emtiu** [comment]
> For best reproducibility of problems I would also like to know
> 
>     * the Python version
>     * in case of restore problems: the source and target file system type

I understand, but it's bordering on "too much to ask" IMHO. As a newbie reporter, I would be discouraged my any more than three required fields before I get to talk about my problem.

> A nice feature of the BiT GUI and command line tool would be a "diagnostics" output with all this, eg.
> 
> ```
> $> backintime --diagnostics
> Ubuntu 20.04.01
> ```

That's a **very** good idea!

**Comment by buhtzz** [comment]
> A nice feature of the BiT GUI and command line tool would be a "diagnostics" output with all this, eg.

On my todo list... ;)

**Comment by buhtz** [comment]
Can we close this?

The `--diagnostics` is implemented.
We do have improved our README and introduced a CONTRIBUTING.md.
And in the near feature we might make `dev` branch the default one which also solve some of the known problems.

**Comment by aryoda** [comment]
I think we can live without issue templates so far
