### ISSUE TITLE
ApplicationInstance lock should check process name to find invalid lock files

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#128]
As far as I can tell, the daily backups are still taking place just fine, but the GUI refuses to show itself, and this started within the last three weeks or so (since that was approximately the last time that I checked into the state of my backups). 

Going to a shell to run BIT we get the normal boilerplate as well as the message that the application is already running and providing a PID. Strangely, upon checking with ps, there's no such PID, and there's no 'backtintime' anywhere in the list.

Ubuntu 12.04

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-07-14T03:39:19Z
 * owner: 32variations
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1341414

**Comment by Germar** [comment]
(by germar)
Please take a look if there is a file '~/.local/share/backintime/app.lock.pid' and delete it.

**Comment by Germar** [comment]
(by 32variations)
Thanks for your quick response.

There's no such file. Also, a few hours ago, the problem magically went
away.

Before I sent my bug report, I did an extensive search and found that,
indeed, other individuals had also had this same issue - and the same
resolution: it went away.

About all I "did" that might possibly have made any difference was to
briefly drop into a KDE desktop and see if I could root around there and
find out anything about my regular 12.04/Gnome login. After finding nothing
informative, I logged back into my normal desktop, tried the usual root
launcher one last time and all was well again.

The only other thing that was going on that might have something to do with
it was the fact that it had missed doing the backup the day before all of
this apparently started  because I forgot to plug in the backup drive.


Hope that helps. I will let you right away if it occurs again. I tend to be
really anal about my computer, so I'll watch more carefully and see if I
can uncover some useful information.


Thanks!

**Comment by Germar** [comment]
(by germar)
What has happen is this:
- 'app.lock.pid' wasn't removed for what ever reason last time you closed BIT GUI (may be BIT crashed)
- the PID inside that lock file was now used by an other process (may be from your Gnome desktop)
- BIT read the lock file and send a 'kill -0 <PID>' to check if the process is alive and got a positive response. So it said the lock is valid and exit
- when you logged out of Gnome and log into KDE this process was killed and no other process took the same PID again
- next time you started BIT 'kill -0 <PID>' showed no running process and so deleted the (now invalid) lock and started just normal.

Problem is that we don't check which process is using that PID. We just check if there is a process alive with this PID.

**Comment by Germar** [comment]
(by 32variations)
What was surprising was that the issue survived many reboots and cold boots. It was only a guess on my part that trying one of my other desktops might have anything to do with it, or perhaps even lead to a favorable outcome.

Thanks again.

**Comment by Francewhoa** [comment]
> Please take a look if there is a file '~/.local/share/backintime/app.lock.pid' and delete it.

Thanks Germar :) We were facing the same challenge. This fixed it.  

Same for us, the challenge was persistent after many reboots and cold boots. Trying one of the other desktops did not work in our case.

**Steps to reproduce this challenge:**

1. Start a BIT. Using a first profile, start a first backup.
1. While the first backup is running, using a second profile, start a second backup.
1. The two profiles are overlapping and using lots of system resources and lots of storage volume operations. The operating system is slow and  unusable. We try using BackInTime graphical user interface to stop the two backups in progress. But found no way to do that.
1. Using Terminal/Console kill all processes related to BIT. Such as:
```
 backintime-gnome
 /usr/share/back
 rsync
 ```
1. Using Gnome, try to open BackInTime. It won't open. The kill above might have cause this challenge.
1. Using Terminal, run the following command to open BackInTime
`backintime`
The following error message is return
> WARNING: import keyring failed
6. Deleted `app.lock.pid` file fixed this issue
1. Using Gnome, try to open BackInTime agin. It does open :)
A new `backintime` file was automatically created. Which contain a new and different PID.

Using 
* Debian 8 Jessie 64 bit
* BackInTime 1.0.36
* Gnome 3.14.1

Related issue: #652

**Comment by Germar** [comment]
Version 1.0.36 is quite old. More recent version handle those locks more reliable.
