### ISSUE TITLE
failed: Operation not permitted (1)

### ISSUE THREAD

**Issue by khaeusler** [bit-team/backintime#1283]
Hello

I have the problem that when the HDD is plugged in, an error always occurs during the automatic backup.

```
========== Take snapshot (profile 2): Wed Sep  7 12:39:58 2022 ==========

  [E] Error: rsync: recv_generator: mkdir "/media/USER/UUID/backup/backintime/HOSTNAME/root/2/new_snapshot/backup/etc/chatscripts" failed: Operation not permitted (1) 
[E] Error: rsync: recv_generator: mkdir "/media/USER/UUID/backup/backintime/HOSTNAME/root/2/new_snapshot/backup/etc/ppp/peers" failed: Operation not permitted (1)
```

```
$ LANG=C ls -lA /etc/{chatscripts,/ppp/peers}
/etc//ppp/peers:
total 4
-rw-r----- 1 root dip 1093 Jul 24  2017 provider

/etc/chatscripts:
total 12
-rw-r--r-- 1 root root 950 Jan 27  2016 gprs
-rw-r--r-- 1 root root 653 Jan 27  2016 pap
-rw-r----- 1 root dip  656 Jul 24  2017 provider
```

When I repeat the operation manually, the error does not occur.
What could be the cause?

Chears
Kay

Edit:
OS: Kubuntu 18.04.6

Back In Time: 1.3.2
python: 2.7.17
python3: 3.6.9
rsync: 3.1.2 (protocol version 31)

**Comment by emtiu** [comment]
This looks like a problem with directory permissions. Could you use `ls -ld` to check the ownership and permissions of the _directories_ (not their contents) `/etc/`, `/etc/chatscripts` and `/etc/ppp/peers`, both in your original filesystem and on the backup filesystem? Also, which filesystems are involved here (source and destination)?

**Comment by khaeusler** [comment]
```
$ ls -ld /etc/{chatscripts,ppp/peers} /media/USER/UUID/backup/backintime/HOSTNAME/root/2/*/backup/etc/{chatscripts,ppp/peers}
drwxr-s--- 2 root dip 4096 Aug  5  2020 /etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /etc/ppp/peers
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20171121-135223-736/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20171121-135223-736/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20180423-120940-249/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20180423-120940-249/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Nov  8  2018 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20190729-122949-161/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20190729-122949-161/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20200924-140752-769/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20200924-140752-769/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210522-012636-280/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210522-012636-280/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210719-201213-561/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210719-201213-561/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210801-205634-383/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210801-205634-383/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210908-123850-937/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20210908-123850-937/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20211013-205344-831/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20211013-205344-831/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20211130-162112-637/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20211130-162112-637/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220128-180538-550/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220128-180538-550/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220216-151219-335/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220216-151219-335/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220328-130258-723/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220328-130258-723/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220426-193823-820/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220426-193823-820/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220530-164610-528/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220530-164610-528/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220610-071152-148/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220610-071152-148/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220722-215910-804/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220722-215910-804/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220821-222601-425/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220821-222601-425/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220907-135804-889/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/20220907-135804-889/backup/etc/ppp/peers
drwxr-s--- 2 root dip 4096 Aug  5  2020 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/last_snapshot/backup/etc/chatscripts
drwxr-s--- 2 root dip 4096 Jul 24  2017 /media/USER/UUID/backup/backintime/HOSTNAME/root/2/last_snapshot/backup/etc/ppp/peers
```

**Comment by emtiu** [comment]
Both `/etc/chatscripts` and `/etc/ppp/peers` have the setgid bit set (`drwxr-s---`), but your destination filesystem is mounted with the `nosuid` option. Maybe that's the reason why backintime (or more precisely: rsync) can't re-create those directories in your backup?

You could try re-mounting the destination filesystem without `nosuid` and running another backup.

**Comment by khaeusler** [comment]
in the file /etc/fstab, the nosuid flag is not set.
```
/dev/mapper/luks-UUID   none    ext4    users   0       0
```

How or where can I specify that suid is allowed?

Why can the s-bit be set on the 2nd (backup)?

**Comment by aryoda** [comment]
Please check and report the actually applied mount options for your drive with `mount`, eg.

`mount | grep -i luks-UUID`

**Comment by emtiu** [comment]
> in the file /etc/fstab, the nosuid flag is not set.
> 
> ```
> /dev/mapper/luks-UUID   none    ext4    users   0       0
> ```
> 
> How or where can I specify that suid is allowed?

Looks like at some point, your distro decides to make the mount `nosuid`, in spite of what `/etc/fstab` says. I haven't seen that before, and I don't know how it happens.

> Why can the s-bit be set on the 2nd (backup)?

That's a good question. You could try to manually create some setgid/suid folders and files on the backup filesystem, or transfer the affected files and folders specifially with `rsync`, to see if you can make the error appear by hand.

If you can't, then _maybe_ something else is going on, and the mount options aren't the problem after all.

**Comment by aryoda** [comment]
> Looks like at some point, your distro decides to make the mount `nosuid`, in spite of what `/etc/fstab` says. I haven't seen that before, and I don't know how it happens.

I had this problem a few months ago and found out that Ubuntu is defensive and you have edit some file to explicitly allow this
(I can't remember which one and searching for it did not bring it back so far :-(

**Comment by aryoda** [comment]
Found it and it was even "more secure":

https://stackoverflow.com/questions/25001206/suid-doesnt-work-in-bash

SUID is only working for binary files, not script files like bash (would be a huge security risk by just changing the content of the script file to execute everything with root rights).

I am not sure, but your file names causing the error sound like script names.

How could you even set SUID on them ;-) ?

**Comment by khaeusler** [comment]
Not the files have the s-bit, only the directories have the s-bit.

The files come from the package ppp.
http://security.ubuntu.com/ubuntu/pool/main/p/ppp/ppp_2.4.7-2+2ubuntu1.3_amd64.deb

Already there the s-bit is set for the directories.
I simply uninstalled the package, it is not needed anyway.

Thanks

**Comment by khaeusler** [comment]
Why isn't the info logged in the fileinfo.bz2 file, as well as the ownership?
The file/directory rights could then be restored correctly during the restore.

**Comment by emtiu** [comment]
> Why isn't the info logged in the fileinfo.bz2 file, as well as the ownership? The file/directory rights could then be restored correctly during the restore.

This is exactly how backintime normally works.

If this didn't work for you, you may have run into a problem related to #988, which we still need to tackle. (The maintainer team for backintime has just newly re-formed after a the project was nearly unmaintained for a while.)

I'm closing the Issue since you seem to have worked around the problem. Thanks for your debugging efforts!
