### ISSUE TITLE
Fresh install which picks up old settings does not set cronjob correctly

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#129]
If you have a nicely working instance of backintime successfully performing daily backups, and then you reinstall your operating-system (but preserve your home folder), followed by reinstalling backintime, then backintime nicely remembers its old settings.

You can take a snapshot and it works as it did before.  It all looks perfect - in fact it (incorrectly) reports that it is still scheduled to do daily backups.   But strangely the daily backups do not happen, because the cronjob file was reset after the reinstall but the backintime settings were not reset - so the two do not match.

I'm not sure what the solution to this problem is, other-than having backintime occasionally inspect the crontab file, e.g. whenever the backintime application is started.  But I think this is a bug because back-in-time's settings panel is incorrectly stating that a daily backup schedule is set, and this gives a false sense of security.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2014-07-17T21:00:06Z
 * owner: michael-fairbank
 * the launchpad url was https://bugs.launchpad.net/bugs/1343599

**Comment by Germar** [comment]
(by germar)
crontab doesn't run in userspace. It run as root and the user can only add new schedules with 'crontab' command. The schedules are stored somewhere in /var. That's why the schedules where gone after you reinstalled your system.

BIT always set up crontab schedules as soon as you press OK in Settings dialog. No matter if they had change or not.

We could add a warning on GUI start if crontab doesn't match BIT config and ask to run Settings.

**Comment by Germar** [comment]
(by michael-fairbank)
I think the best solution might be to add a crontab call during the 'apt-get install backintime' process if that is possible. That way it would only be called once, and it would be called immediately as soon as it is needed (without being dependent on any actions chosen by the user), and without giving the user any potentially confusing dialog windows to respond to?

**Comment by Germar** [comment]
(by germar)
Nope, that won't work because apt-get is started as root and crontab need to run by the user who is using it.

Also this wouldn't help if the crontab entry is wiped for some other reason.

**Comment by Germar** [comment]
(by michael-fairbank)
Ok why not do the crontab call whenever the application starts up?

Also, does one part, or all, of backintime run as one of the "startup"
applications whenever the user logs on?  If one of these backintime
startup-processes makes the crontab call then that will mean the cron job
is set up without any user intervention.

**Comment by tmetro** [comment]
I ran across this issue after a fresh OS install, but anticipated it and went looking for it, so I wasn't without backups for long.

> ...having backintime...inspect the crontab file...whenever the...application is started...

Yes. BIT clearly knows how to find its own entry in the crontab, so at minimum it should warn the user if it finds it is absent or different from the one it would generate based on the current settings.


> ...best solution might be to add a crontab call during the 'apt-get install...

Yes, having crontab setup as part of the post-inst automation would be ideal as well. While the check on GUI start should be a bare minimum, a post-inst operation would fix things up even if the user doesn't run the GUI right away.

The main problem with that approach is that it does require that the user has restored their home directory **before** BIT is reinstalled. (In my case that was true for my personal home dir, but I didn't happen to restore root's home dir until after BIT had been installed.)


> ...that won't work because apt-get is started as root and crontab need to run by the user who is using it.

I'm not following why that is a limitation. Root can modify the crontab for **any** user. It would take some effort to find all the home directories that contain BIT settings, but it is doable.
