### ISSUE TITLE
Refactor unittest: `test_sshCopyId()` runs only for Germar

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1298]
This is about [`TestSshKey.test_sshCopyId()`](https://github.com/bit-team/backintime/blob/f1ec35fd039c3d25bad8495eb27c8b27dc71e581/common/test/test_sshtools.py#L244) in `common/test/test_sshtools.py`

https://github.com/bit-team/backintime/blob/f1ec35fd039c3d25bad8495eb27c8b27dc71e581/common/test/test_sshtools.py#L244

That is a nice skipping reason. 😄 This is the only skipped test left before all test go green.

If someone like to investigate that further and maybe find a good solution to solve this....

**Comment by buhtz** [comment]
### Feature I found
I investigated that unittest and the feature/behavior behind it. Back In Time offers the feature to generated a new key pair and upload its public part to the remote server.

I was not aware that this is possible. I also assume that most users are also not aware and that is rarely used. Possible bugs are unknown because of less users.

The feature can be activated behind the plus button:
![image](https://github.com/bit-team/backintime/assets/11861496/0622ef2d-fb62-4558-8c64-cc2c59a78f1b)

### Discussion if we need that feature
I think we need discussion here.

I don't see a need for a feature like this. People how know how to setup SSH server/client and a key pair don't need BIT frontend for that. They do it on the shell or on a SSH-related GUI (e.g. putty on Windows). Or they still have setup their passwordless SSH login in the past. No one would die if this feature isn't in BIT anymore.

The plus-button could be replaced with a link to an tutorial how to setup passwordless-SSH-login.

Looking it the other way the GUI should be improved to make this feature more prominent to the users.

### Bug ?
There is also maybe a "bug". The plus button is disabled when creating a new SSH snapshot profile. It is disabled because there is always the key file pre selected. This happens on my system all the time. I assume that the existing `id_rsa` file is selected automatically if it exists on a system.

https://github.com/bit-team/backintime/blob/848655ae6917e0c2a9f4565941d30fa9b0fedda3/qt/settingsdialog.py#L254-L259

So I assume this feature is only active for people who don't have a key-pair "installed" yet.

### My vote and conclusion
In the end I see a lot of work for a feature that no one needs, that is not in the scope of BIT and where much better tools exist. I vote for removing the whole feature.

**Comment by Germar** [comment]
I can't double check at the moment, but I'm pretty sure, that 'Create SSH-key-pair' is called automatically after finishing Settingsdialog if the user has no ssh-key yet. And I don't belive that most people know how to do this on a shell.

The unittest is disabled always but on my machine because there is a hard-coded dummy-passwort in it. On my Test-VM I replace (`sed ...`) that dummy-passwort with my real password on the Test-VM

**Comment by buhtz** [comment]
Ah, I see. Users don't have to know that feature. BIT does know itself when the user need it and present it to him. :smile: Great!

Now I better understand the purpose and "behavior" (in a unittest meaning) of that feature.

IMHO it is possible to refactor the test to run on every machine. But before doing that there IMHO is some refactoring work to do with the `Config` class and some other parts involved.

I see no hurry. I would put this on hold.

**Comment by buhtz** [comment]
Note to myself: Good opportunity to demonstrate `class SshAgentCmd(_ShellCommand)` and how to mock it.
