### ISSUE TITLE
Migration to PyQt6 until the end of 2023 because of PyQt5 support end

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1301]
Currently we are using `PyQt5`.
The original Qt5 (by Qt Company) [ends its support in the second quarter of 2023](https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders#contactopen).
But different from original Qt the [support for PyQt5 ends until the end of 2023](https://www.riverbankcomputing.com/pipermail/pyqt/2022-September/044903.html) what buys us a little more time.

Our luck is that the qt code is quit isolated from the rest.
And [this blog post about migrating PyQt 5 to 6](https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/) stated that it seems quit easy to migrate.

We also have to take into account the backwards compatibility to PyQt5. But this also seems to be quite easy. But maybe it doesn't matter anymore in the end of 2023.

Sidenote: What I knew but didn't realized in the first place. Qt is created by _Qt Company_. But `PyQt` is created by _Riverbank Computing_.

**EDIT**: For new contributors this is a good opportunity to help in that project without touching the code. Use the [branch qt6migration at buhtz/backintime](https://github.com/buhtz/backintime/tree/qt6migration) and play around with the GUI to find bugs introduced by this migration.

**Comment by buhtzz** [comment]
My assumptions based on wrong knowledge.

The companies behind Qt and PyQt5 are different. The Qt support timelines may not stick to the ones for PyQt5. But I investigate this further if there is a near deadline and will reopen possibly.

**Comment by buhtzz** [comment]
OK, we have an [official statement from the PyQt maintainer](https://www.riverbankcomputing.com/pipermail/pyqt/2022-September/044903.html) himself that the support for PyQt5 ends until the end of 2023.

So it is not so urgent; just a bit. ;)

**Comment by buhtz** [comment]
IMHO the final deadline is when Debian drops the Qt5 support.

**EDIT**: Helpful resource about migration https://www.pythonguis.com/faq/pyqt5-vs-pyqt6/

**Comment by buhtz** [comment]
I did some "research" and was able to start BIT with its main window using Qt6.

There is some work in the details but nothing complex. Just renaming some classes, import paths and methods.

But I had some compatibility and dependency issues. Before migrating to Qt6 and doing a release with PyQt6 support we should investigate further the PyQt6 support of the usually used GNU/Linux distributions. For example Debian 11 (the current stable) does support Qt6 but not PyQt6 out of the box. Using backport repositories, PPA or PyPi would be a burden for our users and is IMHO not a choice for our stable users.

I don't like the idea but we should also consider supporting PyQt5 and 6 as an alternative.

There is no rush. The PyQt5 support ends in the end of this year. So I would recommend to relax and investigate the situation about PyQt6 support in the Linux distros in the early 2024.

We could make a last PyQt5 based release in end 2023 or beginning 2024 and then migrate the develop branch to PyQt6.

I documented the technical details, pitfalls and a patch file in my private Zettelkasten.

**Comment by buhtz** [comment]
Currently working on it in https://github.com/buhtz/backintime/tree/qt6migration .

But won't merge this before the next release.

**Comment by emtiu** [comment]
I've created a Vagrantfile for testing your private branch: [Vagrantfile.txt](https://github.com/bit-team/backintime/files/13634486/Vagrantfile.txt)

If vagrant is configured correctly, running `vagrant up` takes about 2 minutes to set up a VirtualBox machine with Debian 12 and @buhtz' Qt6 branch cloned, built and a link to `backintime-qt` installed to the desktop.

**Comment by buhtz** [comment]
Of course it is always better having mutliple testing persons. But to my own testing I could say I am done with it clicking everywhere around. :D Still identified some minor problems and also fixed them in the branch I mentioned.
