### ISSUE TITLE
It is not taking time snapshots

### ISSUE THREAD

**Issue by limopc** [bit-team/backintime#1302]
Some time ago, it was working fine!
Now timely snapshots does not occur. (I have checked the checkbox to take snapshots even if there is no change), rebooted, restarted.. I did everything. Still no timely snapshots (currently every 5 minutes). Only manual snapshots.

I am taking the snapshots to an external USB HDD, and the /home folder is on a local SSD BTRFS, EndeavourOS Linux

I will appreciate any help.
Thank you.

**Comment by buhtzz** [comment]
Dear @limopc ,
thank you for your report. Usually we don't offer direct email support. Please let's keep the discussion her in that Issue thread. Because of spam bots I would recommend to remove your mail address from the initial posting.

Please give us some more informations
 - Open a terminal and start backintime in debug mode via `backintime-qt --debug` and post the output on the terminal here.
 - Exact operating system name and version.
 - On Terminal: The output of `rsync --version`
 - On Terminal: The output of `mount`

**Comment by limopc** [comment]
Thsnk you very much for your prompt response. And sorry for my delay.
I mean in settings I can configure to automatically take a snapshot every 5 minutes, every 30 minutes... 
It is not taking snapshots after the specified time passes.
This is the outputs
`backintime-qt --debug
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /home/limo/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/limo/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile, 2=BlackUSB
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
ERROR: [common/config.py:1357 Config.canBackup] /run/media/limo/LD/backintime/lenovo/limo/2 does not exist
DEBUG: [common/tools.py:1237 readCrontab] Read 4 lines from users crontab
DEBUG: [common/config.py:1466 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1500 Config.cronLine] Profile: Main profile | Automatic backup: Every 5 minutes
DEBUG: [common/config.py:1500 Config.cronLine] Profile: BlackUSB | Automatic backup: Every 5 minutes
DEBUG: [common/config.py:1450 setupCron] Crontab didn't change. Skip writing.
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/configfile.py:529 Config.setCurrentProfile] change current profile: 1=Main profile

`
Exact operating system name and version.
`System:
  Kernel: 5.15.68-1-lts arch: x86_64 bits: 64 compiler: gcc v: 12.2.0
    Desktop: KDE Plasma v: 5.25.5 Distro: EndeavourOS base: Arch Linux
Machine:
  Type: Laptop System: LENOVO product: 20157 v: Lenovo G580
`
rsync --version
`rsync --version
rsync  version v3.2.6  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs,
    xattrs, optional secluded-args, iconv, prealloc, stop-at, no crtimes
Optimizations:
    SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 none
Compress list:
    zstd lz4 zlibx zlib none

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.
`
`mount
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=3981268k,nr_inodes=995317,mode=755,inode64)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755,inode64)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
/dev/sda2 on / type btrfs (rw,noatime,compress=zstd:3,ssd,space_cache=v2,subvolid=256,subvol=/@)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11993)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /tmp type tmpfs (rw,noatime,inode64)
/dev/sda2 on /home type btrfs (rw,noatime,compress=zstd:3,ssd,space_cache=v2,subvolid=257,subvol=/@home)
/dev/sda2 on /var/cache type btrfs (rw,noatime,compress=zstd:3,ssd,space_cache=v2,subvolid=258,subvol=/@cache)
/dev/sda2 on /var/log type btrfs (rw,noatime,compress=zstd:3,ssd,space_cache=v2,subvolid=259,subvol=/@log)
/dev/sda1 on /efi type vfat (rw,noatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=798408k,nr_inodes=199602,mode=700,uid=1000,gid=1001,inode64)
pcloud on /tmp/.mount_pcloudn1j26h type fuse.pcloud (ro,nosuid,nodev,relatime,user_id=1000,group_id=1001)
pCloud.fs on /home/limo/pCloudDrive type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1001)
/dev/sdb1 on /run/media/limo/BackupUSB type fuseblk (rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096,uhelper=udisks2)
`

I really appreciate your help.

P.S.
I am on KDE Plasma, SSD, BTRFS, Sanpper, and I am trying to backup to an external USB HDD NTFS.
I hope this helps.

Thank you again.

**Comment by buhtzz** [comment]
There is a known bug (#1247) in Back In Time working with rsync 3.2.4 or younger. You use 3.2.6.
Can you post the output of `echo $RSYNC_OLD_ARGS` please.

As a workaround please add `--old-args` in "Expert Options / Additional options to rsync". Maybe this helps.

**Comment by buhtzz** [comment]
Btw: You can use that button to format text as code.
![image](https://user-images.githubusercontent.com/11861496/191274724-7c9ab038-13ea-4e9b-987a-83e1307aa18f.png)

Or you encapsulate multiple lines with three backticks in the beginning and end of that text.

![image](https://user-images.githubusercontent.com/11861496/191275215-2f8e1a10-d173-422b-aeb2-ae92660959dc.png)

**Comment by limopc** [comment]
OK. I did your recommendation, took a manual snapshot.
It is configured to take snapshot every 5 minutes whether there is a change or not.
Now more than 10 minutes, and it did not take a snapshot automatically.
![Screenshot_20220920_160231](https://user-images.githubusercontent.com/32569443/191278726-baf5bea7-7402-4c5c-b2f1-43775a156ca0.png)
![Screenshot_20220920_160327](https://user-images.githubusercontent.com/32569443/191278938-f5fd7a82-84ef-49ed-bf3e-0fc5284427b5.png)

(apologies for text not formated. I pressed the button and it gave me `     `  and I pasted between the 2 `.
I will try your formatting with ```)

**Comment by buhtzz** [comment]
Possibly a misunderstanding. Did you pressed that button?
![image](https://user-images.githubusercontent.com/11861496/191281892-fc59feb0-56c7-48e5-8d68-de10d79bbcf2.png)

And how does your debug output look like 1) when you push that button and 2) when you wait 5 minutes to the next automatic snapshot?

**Comment by limopc** [comment]
Yes. This button is how I created the manual snapshot.
This is the debug output I just ran now. (more than 5 minutes)
```
[limo@lenovo ~]$ backintime-qt --debug
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /home/limo/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/limo/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile, 2=BlackUSB
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/tools.py:829 keyringSupported] No appropriate keyring found. 'keyring.backends.chainer' can't be used with BackInTime
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:1237 readCrontab] Read 4 lines from users crontab
DEBUG: [common/config.py:1466 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1500 Config.cronLine] Profile: Main profile | Automatic backup: Every 5 minutes
DEBUG: [common/config.py:1500 Config.cronLine] Profile: BlackUSB | Automatic backup: Every 5 minutes
DEBUG: [common/tools.py:1274 writeCrontab] Wrote 4 lines to users crontab

```
I should push the button and send debug output immediately?

**Comment by limopc** [comment]
Pressed the button, then at terminal I got:
```
 backintime-qt --debug
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /home/limo/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /home/limo/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile, 2=BlackUSB
The application is already running! (pid: 19580)
```
(snapshot is still saying "working")

**Comment by buhtzz** [comment]
Mhm... Can you try it again and after that post the output of `journalctl -b | grep backintime` please.

**Comment by limopc** [comment]
OK. Just Rebooted then (in order - USB not mounted yet)
-  `journalctl -b | grep backintime`
```
[limo@lenovo ~]$ journalctl -b | grep backintime
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1072]: which: no su in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1078]: which: no backintime in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1079]: which: no nice in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1080]: which: no ionice in ((null))
Sep 21 10:03:43 lenovo systemd[485]: app-backintime@autostart.service: Consumed 1.211s CPU time.
[limo@lenovo ~]$ 
```
- Mounted the USB
```
[limo@lenovo ~]$ journalctl -b | grep backintime
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1072]: which: no su in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1078]: which: no backintime in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1079]: which: no nice in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1080]: which: no ionice in ((null))
Sep 21 10:03:43 lenovo systemd[485]: app-backintime@autostart.service: Consumed 1.211s CPU time.
[limo@lenovo ~]$ 
```
- Launched BackInTime
```
[limo@lenovo ~]$ journalctl -b | grep backintime
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1072]: which: no su in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1078]: which: no backintime in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1079]: which: no nice in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1080]: which: no ionice in ((null))
Sep 21 10:03:43 lenovo systemd[485]: app-backintime@autostart.service: Consumed 1.211s CPU time.
[limo@lenovo ~]$ 
```
- Pressed to create a snapshot and `journalctl -b | grep backintime`
```
[limo@lenovo ~]$ journalctl -b | grep backintime
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1072]: which: no su in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1078]: which: no backintime in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1079]: which: no nice in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1080]: which: no ionice in ((null))
Sep 21 10:03:43 lenovo systemd[485]: app-backintime@autostart.service: Consumed 1.211s CPU time.
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Lock
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Take a new snapshot. Profile: 1 Main profile
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Call rsync to take the snapshot
[limo@lenovo ~]$ 
```
(saying "working")
![working](https://user-images.githubusercontent.com/32569443/191451398-1fe614b1-47f0-4bb6-9952-5f10cb200e67.png)
Strange thing! Still working though there are previous snapshots and no much files added or changed since last snapshot/backup!
ptime: 12m 
Done right now! 
![done snapshot](https://user-images.githubusercontent.com/32569443/191452542-b5955aca-41bf-4fac-aafd-b706747270e1.png)
- then again  `journalctl -b | grep backintime
```
[limo@lenovo ~]$ journalctl -b | grep backintime
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1072]: which: no su in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1078]: which: no backintime in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1079]: which: no nice in ((null))
Sep 21 10:03:43 lenovo net.launchpad.backintime.serviceHelper[1080]: which: no ionice in ((null))
Sep 21 10:03:43 lenovo systemd[485]: app-backintime@autostart.service: Consumed 1.211s CPU time.
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Lock
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Take a new snapshot. Profile: 1 Main profile
Sep 21 10:09:50 lenovo python[2837]: backintime (limo/1): INFO: Call rsync to take the snapshot
Sep 21 10:16:33 lenovo python[2837]: backintime (limo/1): INFO: Save config file
Sep 21 10:16:33 lenovo python[2837]: backintime (limo/1): INFO: Save permissions
Sep 21 10:16:38 lenovo python[2837]: backintime (limo/1): INFO: Create info file
Sep 21 10:16:40 lenovo python[2837]: backintime (limo/1): INFO: Unlock
Sep 21 10:16:40 lenovo plasmashell[2837]: under certain conditions; type `backintime --license' for details.
[limo@lenovo ~]$ 
```

I really appreciate your help.

**Comment by buhtzz** [comment]
And what is about your backup jobs every 5 minutes. Do they run?
I'm not sure what is going on but maybe `--old-args` did solved the problem.

So your problem is solved now?

Can anyone of my team mates tell me what this error is about?
```
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'

```

**Comment by limopc** [comment]
`And what is about your backup jobs every 5 minutes. Do they run?` Unfortunately not yet.
`--old-args did solved the problem` I have it already, still not backing up automatically.
![oldargs](https://user-images.githubusercontent.com/32569443/191457151-d727742d-ac98-4526-ba32-73fb23e3b161.png)

Just thinking, can this be because of my system configuration. Somehow BackInTime can't handle it properly for some reason?!
- System on a SSD, BTRFS, (Sanapper, BTRFS Assisitant... etc)
- Target Drive where I save backups external USB HDD, NTFS format.
The question you asked `Can anyone of my team mates tell me what this error is about?` seems have point here.
I would like to add that in my configuration:
- I am on KDE Plasma
- I disabled Baloo as it does not play well with BTRFS
- I installed `kio_recoll` as I am using Recoll instead of Baloo, you may have a look at [my thread at EndeavourOS forum ](https://forum.endeavouros.com/t/make-dolphin-use-recoll-kio-recoll-installed/29901/66) for further details if it may help.

**Comment by limopc** [comment]
`Thanks for your patience and cooperation in debugging, by the way :)`
You are welcome. It is me who should thank you for your kind support and for the wonderful BackInTime.
By the way, I am a strong believer in open source, cooperation, Linux.... on Linux since 2000 by the way (but I do not count myself anything but just a user.
I will be glad to help anyway.
Thank you

```
[limo@lenovo ~]$ crontab -l
#Back In Time system entry, this will be edited by the gui:
*/5 * * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null
#Back In Time system entry, this will be edited by the gui:
*/5 * * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job >/dev/null

[limo@lenovo ~]$ 

```

**Comment by emtiu** [comment]
Hmm, tricky. The crontab looks all right, and I don't see the problems in the logs.

NTFS has been known to cause some trouble (though not the same thing you're seeing). And we should test without the USB drive involved, anyway. Also, the cronjob might be throwing errors that you're not seeing. (I'm not sure how errors from commands in the crontab are reported on modern systems. In the past, the system would send a local mail message, but it probably gets logged somewhere else these days.)

So, let's try this: Make a new test profile with some small backup data, backup up to another place (not the NTFS USB drive). Set it to 5 minutes' schedule, and see if it works.

Also, try to run `/usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job` from a terminal, it's the same command that's called from the crontab.

**Comment by limopc** [comment]
Thank @emtiu 
I modified another profile to take snapshots/backups to local directory on my BTRFS SSD and took a snapshot.
Closed BackInTime, and left it for over 5 minutes after the snapshot (even created a new empty text file to see if there will be any difference)
Still, no snapshots.
I am suspicious I am missing something to install (my previous post)
Sorry for late reply.

**Comment by emtiu** [comment]
> UPDATE: Running `/usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job` from terminal gave me error can't find snapshots (USB not plugged in, and snapshot to local SSD is on another profile.)

I see. You can either connect your USB drive and try again, or modify the command to run the other profile, as you can see in your crontab: `/usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job` (notice the `--profile-id 2`).

**Comment by limopc** [comment]
Thanks a lot. I really appreciate your patience.

I connected the external USB and ran the command and got the following:
```
[limo@lenovo ~]$ /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job

Back In Time
Version: 1.3.2

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
[limo@lenovo ~]$ INFO: Take a new snapshot. Profile: 2 BlackUSB
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock

```
Launched the app -> second profile USBBlack (which was changed to local SSD) and noticed a snapshot was taken.
Waiting to see if it will take another snapshot after a 5 minutes.
OK. 5 min. and no new snapshot!

Are you sure I am not missing something to install? Please double check previous posts and error messages.
Thank you.

**Comment by emtiu** [comment]
I'm out of ideas for the moment. Snapshots work when triggered manually, and the crontab has the right entries. The snapshots just don't happen when they should be called from the crontab.

It probably comes down to this:
```
Sep 21 10:03:42 lenovo dbus-daemon[380]: [system] Activating service name='net.launchpad.backintime.serviceHelper' requested by ':1.46' (uid=1000 pid=736 comm="python -Es /usr/share/backintime/common/backintime") (using servicehelper)
Sep 21 10:03:43 lenovo ksmserver[548]: kf.kio.gui: Could not find an executable named: "/usr/share/backintime/qt/app.py"
Sep 21 10:03:43 lenovo dbus-daemon[380]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
```
… but I don't know enough about what it means at the moment.

**Comment by limopc** [comment]
OK. Thank you very much for attempting to help.
I understand from the messages above there is as the the aybe if I can somehow get this "app.py" and copy it to the folder it might work.
Where do yopu think I can get this python file (app.py)?

**Comment by emtiu** [comment]
That's certainly not the root of the problem. `app.py` is already included with backintime, and the GUI and manual snapshots wouldn't work if it wasn't present.

The problem probably lies somewhere with the "serviceHelper", or the crontab, or somewhere in between. Maybe some sort of encapsulation failure because of some security settings, but I don't know enough for a good guess.

**Comment by limopc** [comment]
`but I don't know enough for a good guess.`

OK. No problem.
Any way, it is OK for me for now to take manual snapshots.
Thank you very much

**Comment by limopc** [comment]
Thank you very much!
I posted a thread at the EndeavourOS forum as I thought it might be related to my system.
The problem was that cron was not enabled by default.
So they guided me to enable it and everything working perfectly now!
Thank you very much for your support and for your wonderful BackInTime.
Thanks.

**Comment by emtiu** [comment]
Ah, I'm glad that we found a solution :) I'll remember that, and we might make it an FAQ entry. Have fun with backintime :)
