### ISSUE TITLE
Check old TODO entries

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1311]
I found a [`TODO`](https://github.com/bit-team/backintime/blob/master/TODO) file in the repo which last commit was 6 years ago. That was the content:

```
TODO:
* use rsync return code to check that the snapshot was really taken (no out of space, copy error ...)
* uid/gid translate table with 'Full rsync mode'
* grep DBUS_SESSION_BUS_ADDRESS from session-managers environ (https://github.com/bit-team/backintime/issues/723)
```

We need to check this points if they are still relevant.

Tag: Meta, Discussion

**Comment by aryoda** [comment]
Let me confess that I have just sent a PR with new TODO comments during my "code review" to document undocumented code parts ;-)

Normally I would treat code with TODO comments as a reason to reject a PR...

**Comment by emtiu** [comment]
You're forgiven this one time ;)

**Comment by buhtzz** [comment]
> Let me confess that I have just sent a PR with new TODO comments

🤣 I don't have problems with that. This PR here is not about **in-code** TODO comments but just about a single TODO file in the repo itself.

**Comment by buhtz** [comment]
> * uid/gid translate table with 'Full rsync mode'

Dear @Germar ,

do you have an idea what this point is about?

**Comment by Germar** [comment]
Filesystems always store the uid and gid for a file. Not the user/groupname. uid/gid are enumerate by the time of creating each user/group. So if you have an old machine with user foo=uid1000 and user bar=uid1001 and you build a new machine but this time you create user bar first, you'll end up with user foo=uid1001 and user bar=uid1000. If you now restore your files (with BiT root) foo can't access his files but all the files from bar...

**Comment by buhtz** [comment]
Thanks for explaining.

So this TODO entry could be treated as a feature request. Am I right so far?

**Comment by buhtz** [comment]
> * use rsync return code to check that the snapshot was really taken (no out of space, copy error ...)

Covered by issue #489

> * uid/gid translate table with 'Full rsync mode'

Covered by issue #1434.

> * grep DBUS_SESSION_BUS_ADDRESS from session-managers environ (https://github.com/bit-team/backintime/issues/723)

Covered by issue #770 (see [comment](https://github.com/bit-team/backintime/issues/770#issuecomment-333984054))
