### ISSUE TITLE
Cannot delete snapshots when using --old-args with backintime

### ISSUE THREAD

**Issue by petaramesh** [bit-team/backintime#1320]
Hello,

I use backintime-qt 1.3.2 with rsync v3.2.6.

At first it wouldn't work until I found in another post the suggestion to add “--old-args” in the advanced rsync options, that fixed it.

However, I now can create snapshots, but I cannot delete snapshots, and running backintime in debug mode when I try to delete snapshots, shows me errors similar to what I saw before using the “--old-args”.

So it appears to me that the “--old-args” additional options is not passed when deleting snapshots.

I assume this is a bug that would need fixing ?

Kind regards.

**Comment by buhtzz** [comment]
Dear @petaramesh ,
thank you very much for this report.

I also assume that you are right and this is related to #1247 which is about the _new default argument protection_ of rsync. I'm still working on that problem and will also take your side problem into account.

I just have a solution but it will take some time to implement this without blowing everything away. The new maintaining team is just forming and we are getting just warm with the code of BIT. But in context of #1247 your problem has the highest priority.

Tag: Bug, High, Extern/Rsync

**Comment by petaramesh** [comment]
Hi,
I'm not sure where is the best place to set these rsync options (given that I wouldn't want them to affect my usual rsync commands).

I tried to put “Exec=RSYNC_OLD_ARGS=1 RSYNC_PROTECT_ARGS=0 backintime-qt” in /usr/share/applications/backintime-qt.desktop, but it doesn't seem to help. Or should I rather use some “export” command ?

**Comment by buhtzz** [comment]
> I wouldn't want them to affect my usual rsync commands).

Very important point. I should have mentioned that myself. Sorry.

> I tried to put “Exec=RSYNC_OLD_ARGS=1 RSYNC_PROTECT_ARGS=0 backintime-qt” in /usr/share/applications/backintime-qt.desktop, but it doesn't seem to help. Or should I rather use some “export” command ?

I'm not well with desktop-files. But on a usual shell you would do it via `export RSYNC_OLD_ARGS=1`.

Another place where you could do this is the "entry point" (a start script).
https://github.com/bit-team/backintime/blob/master/qt/backintime-qt

You my find it at `/usr/bin/backintime-qt` on your system.

**Comment by buhtzz** [comment]
If it is possible for you and your environment, can you please check out the PR #1351 and test if your problem is fixed?

**Comment by emtiu** [comment]
Closing this Issue, because #1351 was merged and should have eliminated the problem. Please re-open if it causes trouble again!
