### ISSUE TITLE
Delete file or directory items in all snapshots at once

### ISSUE THREAD

**Issue by buhtzz** [bit-team/backintime#1332]
Feature Request

I want to be able to delete one file or one folder in all snapshots at once.
Currently it isn't even possible to delete an item in one snapshot.

Maybe this is a bit out of scope of BIT?

In the end I also could create a FAQ entry how to do this on filesystem level.

**Comment by emtiu** [comment]
But … that's a regular feature o_O

Just right-click a file and select "Snapshots", then "Select all" and "Delete".

Unless I misunderstand something.

**Comment by buhtzz** [comment]
Auweia! Embarrassing. ;)
You are right.
