### ISSUE TITLE
making backintime common throws error for missing language file

### ISSUE THREAD

**Issue by dkebler** [bit-team/backintime#1342]
I am trying to build common from the repo in a bare bones ubuntu container.

the po subdirectory and the file in question are there.  So what am I missing.  I really only want to make common with english so I don't need to include all these other language translations.  How do I get by this error and/or configure for english only.

As I mentioned this is a bare bones install so no locale is set in the container.

```
root@try-local-ucommandit-backup:[backintime/common] (master) $ ./configure --python3
All OK. Now run:
    make
    sudo make install
root@try-local-ucommandit-backup:[backintime/common] (master) $ make
msgfmt -o po/zh_TW.mo po/zh_TW.po
make: msgfmt: No such file or directory
make: *** [Makefile:97: po/zh_TW.mo] Error 127
```

```
root@try-local-ucommandit-backup:[common/po] (master) $ ls -la
total 1944
drwxrwxr-x+ 1 root root  4096 Oct 24 20:27 ./
drwxrwxr-x+ 1 root root  4096 Oct 24 20:29 ../
-rw-rw-r--+ 1 root root   238 Oct 24 20:18 README.md
-rw-rw-r--+ 1 root root 41971 Oct 24 20:18 ar.po
-rw-rw-r--+ 1 root root 41070 Oct 24 20:18 bg.po
-rw-rw-r--+ 1 root root 35769 Oct 24 20:18 bs.po
-rw-rw-r--+ 1 root root 39569 Oct 24 20:18 ca.po
-rw-rw-r--+ 1 root root 53936 Oct 24 20:18 cs.po
-rw-rw-r--+ 1 root root 38741 Oct 24 20:18 da.po
-rw-rw-r--+ 1 root root 51580 Oct 24 20:18 de.po
-rw-rw-r--+ 1 root root 37184 Oct 24 20:18 el.po
-rw-rw-r--+ 1 root root 36707 Oct 24 20:18 en_CA.po
-rw-rw-r--+ 1 root root 40867 Oct 24 20:18 en_GB.po
-rw-rw-r--+ 1 root root 35565 Oct 24 20:18 eo.po
-rw-rw-r--+ 1 root root 40507 Oct 24 20:18 es.po
-rw-rw-r--+ 1 root root 36891 Oct 24 20:18 et.po
-rw-rw-r--+ 1 root root 49685 Oct 24 20:18 eu.po
-rw-rw-r--+ 1 root root 38267 Oct 24 20:18 fi.po
-rw-rw-r--+ 1 root root 36778 Oct 24 20:18 fo.po
-rw-rw-r--+ 1 root root 51296 Oct 24 20:18 fr.po
-rwxrwxr-x+ 1 root root    79 Oct 24 20:18 genmessages.sh*
-rw-rw-r--+ 1 root root 48302 Oct 24 20:18 gl.po
-rw-rw-r--+ 1 root root 38688 Oct 24 20:18 he.po
-rw-rw-r--+ 1 root root 37531 Oct 24 20:18 hr.po
-rw-rw-r--+ 1 root root 42788 Oct 24 20:18 hu.po
-rw-rw-r--+ 1 root root 39922 Oct 24 20:18 id.po
-rw-rw-r--+ 1 root root 41464 Oct 24 20:18 is.po
-rw-rw-r--+ 1 root root 46498 Oct 24 20:18 it.po
-rw-rw-r--+ 1 root root 39029 Oct 24 20:18 ja.po
-rw-rw-r--+ 1 root root 34952 Oct 24 20:18 jv.po
-rw-rw-r--+ 1 root root 38344 Oct 24 20:18 ko.po
-rw-rw-r--+ 1 root root 36685 Oct 24 20:18 lt.po
-rw-rw-r--+ 1 root root 34880 Oct 24 20:18 messages.pot
-rw-rw-r--+ 1 root root 37360 Oct 24 20:18 nb.po
-rw-rw-r--+ 1 root root 51124 Oct 24 20:18 nl.po
-rw-rw-r--+ 1 root root 36532 Oct 24 20:18 nn.po
-rw-rw-r--+ 1 root root 40127 Oct 24 20:18 pl.po
-rw-rw-r--+ 1 root root 38222 Oct 24 20:18 pt.po
-rw-rw-r--+ 1 root root 45800 Oct 24 20:18 pt_BR.po
-rw-rw-r--+ 1 root root 36021 Oct 24 20:18 ro.po
-rw-rw-r--+ 1 root root 46690 Oct 24 20:18 ru.po
-rw-rw-r--+ 1 root root 38053 Oct 24 20:18 sk.po
-rw-rw-r--+ 1 root root 35872 Oct 24 20:18 sl.po
-rw-rw-r--+ 1 root root 38060 Oct 24 20:18 sr.po
-rw-rw-r--+ 1 root root 49574 Oct 24 20:18 sv.po
-rw-rw-r--+ 1 root root 35395 Oct 24 20:18 th.po
-rw-rw-r--+ 1 root root 38121 Oct 24 20:18 tr.po
-rw-rw-r--+ 1 root root 40486 Oct 24 20:18 uk.po
-rwxrwxr-x+ 1 root root   622 Oct 24 20:18 updatelaunchpad.sh*
-rw-rw-r--+ 1 root root 38839 Oct 24 20:18 zh_CN.po
-rw-rw-r--+ 1 root root 36639 Oct 24 20:18 zh_TW.po
root@try-local-ucommandit-backup:[common/po] (maste
```

**Comment by aryoda** [comment]
> make: msgfmt: No such file or directory

The error is complaining about the missing`msgfmt` command, not a missing language file.

To solve this please install it via `apt-get install gettext`.

If `gettext` is not installed probably further required dev packages are not installed
and you can find the required installation package for a missing command file via

`dpkg-query –S ‘filename’`

**Comment by aryoda** [comment]
>  I really only want to make common with english so I don't need to include all these other language translations.

If you don't need the translations I guess you can just delete the unwanted translation but keep one dummy file required by `./configure`:

```
cd common/po
rm *
touch dummy.po
cd ..
./configure
make
make test
sudo make install
```

**Comment by buhtzz** [comment]
Doesn't the configure script (or make?) does check for existence of some packages and tools in the beginning? Can we add a check about "msgfmt", too?

**Comment by aryoda** [comment]
> Doesn't the configure script (or make?) does check for existence of some packages and tools in the beginning? Can we add a check about "msgfmt", too?

Excellent idea! We document the dependencies for humans in our README but we don't enforce them in `./configure`.

Eg. a simple `which msgfmt` check would be enough here.

Advantage: Package maintainers will always recognize missing dependencies without reading README :-)

This is worth a new FR issue!

**Comment by emtiu** [comment]
@dkebler Can you confirm that installing gettext solves the problem?

**Comment by aryoda** [comment]
> Took me some time to find out in which package "msgfmt" belongs

`dpkg-query -S msgfmt`

**Comment by dkebler** [comment]
@buhtzz, Sorry was away for the week.  Yes adding that package removes the error.  Yes probably should be included in the list in the readme and/or checked for in the script.  Probably in standard distributions it's included but the base Ubuntu docker image is very minimal.

**Comment by aryoda** [comment]
I have just updated our Github README and clarified the build and run-time dependencies incl. the findings from this issue: 475b3fa1e45513152630c42823523684107fb33e

@dkebler Thanks for reporting and re-testing! If it is OK for you I would close the issue.

BTW: I will open a new issue with a feature request to check the dependencies in the `Makefile`.
