### ISSUE TITLE
Decide about manpage "backintime-config" and the generating script "create-manpage-backintime-config.py"

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1354]
# Current situation
 - BIT offers the [manpage `backintime-config`](https://manpages.ubuntu.com/manpages/bionic/man1/backintime-config.1.html) describing all(?) variables used in the config file.
 - There is the script [`common/create-manpage-backintime-config.py`](https://github.com/bit-team/backintime/blob/master/common/create-manpage-backintime-config.py) that intends to generate the manpage out of the real existing config file.
 - The script is nearly undocumented and full of bugs.
# Open questions
Because of the bugs I assume that that script wasn't used in the last years. Looking into the commit history of that file it seems to me that only some minor changes (copyright and version strings) where made.
# To discuss
I tend to remove that script and the `backintime-config`manpage. Users don't need to edit the config file by hand. The infos from that manpage are technical documentation and should go somewhere else. Or if the config.py code has good in-code docstrings there is no more need for an extern technical documentation about the config file. So my primary argument is that we (or the user) don't need a config manpage.

Fixing the script would take much resources. I suspect that writing it new from scratch would be faster. But even this does take resources that are invested better in other tasks.

**Comment by aryoda** [comment]
Good point. I just realized my manpage fix

https://github.com/bit-team/backintime/commit/3c1e08e110246e2159f6666ad309664098cbb6eb

will most probably be overwritten if the py script is really used as man page generator.

> if the config.py code has good in-code docstrings there is no more need for an extern technical documentation about the config file.
> So my primary argument is that we (or the user) don't need a config manpage.

When I was fixing the man page due to an issue the OP was really using the doc to write his BiT config file "by hand".
This is a rare but existing use case and the documentation is IMHO still required.

As end user I'd prefer to **not** read the documentation as docstrings in a python file (which is BTW not installed and therefore
not accessible for end users!).

**Comment by emtiu** [comment]
> When I was fixing the man page due to an issue the OP was really using the doc to write his BiT config file "by hand".
> This is a rare but existing use case and the documentation is IMHO still required.

I agree, this is a legitimate use-case. It seems to be very rare that backintime is used headless, but I like that it's possible, and we should continue supporting it.

> Good point. I just realized my manpage fix [3c1e08e](https://github.com/bit-team/backintime/commit/3c1e08e110246e2159f6666ad309664098cbb6eb) will most probably be overwritten if the py script is really used as man page generator.

A little OT here, but relevant to this point: We seem to be in the same situation for translation changes (modifications of .po files). We'll need to figure this out before making a release.

**Comment by aryoda** [comment]
> OK, I see. ;) But we agree that this is a rare use-case? For that I would say a manpage is "a bit to much" for it.
> Would it be a compromise to move that config-manpage in an md-file in our technical docu folder or into the FAQ?

man pages are the fundament of Linux and I personally do use them quite often so I plead for keeping (and in the future: revising) the man page of BiT CLI.

For the GUI we don't need a man page IMHO.

> Currently translations need be done on the launchpad repo.

And for changed wordings we need the (human) translators. How can we trigger them?

**Comment by Germar** [comment]
> OK, I see. ;) But we agree that this is a rare use-case? For that I would say a manpage is "a bit to much" for it.

I'd disagree that a manpage is to much. There are quite some users which contacted me over the years who use BiT headless. I did the same from the very first day untill two years ago. The configfile format is a bit ugly, but as long as you know all the keys and possible values you can create your own config without a GUI/TUI. And IMHO for someone working headless a manpage is still the first place to search. The docstrings and the resulting [Dev-Doc](https://backintime-dev.readthedocs.org/) contain completely different information.

I wrote the `create-manpage-backintime-config.py` script, to get a first start of that manpage. Didn't want to create it manually because that would have taken a lot more time and it will always be a source for failures.

I vote for keeping the manpage `backintime-config`. But I'm fine with purging `create-manpage-backintime-config.py` and make changes to the manpage manually from now on.


> Germar wrote about it in one of his mails. Currently translations need be done on the launchpad repo. There is a script somewhere that collect the launchpad language files and copy them into the repo. Then you have to just commit the modifications. Looking for better/modern (maybe GitHub integrated but **without** GitHub locked-in effect) translation platform is IMHO also a good task for the 1.3.4 release.

I'll update the current translations from Launchpad. I always wanted to move translations away from Launchpad but I have no experience at all with other platforms.

**Comment by emtiu** [comment]
> I'll update the current translations from Launchpad. I always wanted to move translations away from Launchpad but I have no experience at all with other platforms.

Thanks! Note that we have commited changes to the .po files here—contrary to your recommendation regarding the Launchpad process. From what I see on Github (and remember committing), the total extent of the changes should be these two commits:
- 3330663f3aba3ebde6173501bb01bf05a44a11f2
- bb7108be2ba8832dcab08264a0461a289c0793f5

**Comment by Germar** [comment]
I already double-checked that. There have been changes to italian, french and brasilian-portuguese translations. Those changes made for italian and french where already on Launchpad. For brasilian I copied the changes manually.

**Comment by buhtz** [comment]
> I wrote the `create-manpage-backintime-config.py` script

Dear @Germar ,
can you please give us a short description of that script; what it does and what it's intention is.
I can take care of that script when I better understand what it does.

What I got so far
 - It read the [`config.py`](https://github.com/bit-team/backintime/blob/master/common/config.py) file line by line
 - It tries to find variables with `DEFAULT` in its names.
 - ...

😄 I don't really get it. What is it looking for in `config.py`?
I'm scared that the script isn't flexibel enough to modifications in `config.py`.

A side question: The variable `key` ([here](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/create-manpage-backintime-config.py#L191)) seems to be undefined here.

**Comment by gsker** [comment]
Perhaps this would the a good time to change the location for the root 
cconfiguration to something in /etc.


-- 
Gerry Skerbitz
***@***.***

**Comment by buhtz** [comment]
Dear Gerry,
thanks for your feedback.

> Perhaps this would the a good time to change the location for the root cconfiguration to something in /etc.

This Issue here is not about location of a configuration file but just about if and how to document it. But please open a new Issue about the location if you see a real problem here.

**Comment by Germar** [comment]
@buhtz the script reads every line and try to analysis them:
- the search for [DEFAULT](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/create-manpage-backintime-config.py#L166) will find ([these lines](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/config.py#L124)) and put them into a dict for later replacing the variable with the value.
- if that didn't match it will [look for lines starting with](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/create-manpage-backintime-config.py#L168) `#?` which is basically my own description for the manpage-entry. Multiple lines will get merged and stored in `commentline` until the processing of the current config option is done. That will reset `commentline`
- if a line starts with `#` it will be skipped
- next the script [searches for lines which return the config value](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/create-manpage-backintime-config.py#L180) (like [snapshots.ssh.port](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/config.py#L509)).  There it will extract the key/name (`snapshots.ssh.port`), the default value (`22`), the instance (`Int`) and if it is a profile or general value.
- if the line contain a `List` value like [snapshots.include](https://github.com/bit-team/backintime/blob/f801b14a98f9a442008a5f514eec98e1b2d7e29a/common/config.py#L791), it will process all values for the list like `snapshots.include.<I>.value` and `snapshots.include.<I>.type`.  Also it will add the size like `snapshots.include.size`

In `process_line` it will replace some information with those I wrote manually in the `#?` description, seperated by `;` there is the comment,  value, force_default and force_var. If there is no forced value it will chose the value based on the instance with `select_values`

The undefined `key` is a bug. But it will never happen as it will just reuse the `key` from the last iteration which is already in use so `process_line`will skip this.

Which bugs did you found with the script? It runs fine on my 20.04 installation with Python 3.8.10

**Comment by buhtz** [comment]
Dear Germar,
thank you very much for your explanation. No I definitely know what is going on. 😄 

> Which bugs did you found with the script? It runs fine on my 20.04 installation with Python 3.8.10

Can't reproduce. It was a quick shot. I assume it was the missing shebang.

So I perceive that we keep the autogenerated manpage. So we can close this.

I will later add a small PR just with some comments in the create script.
