### ISSUE TITLE
Tests failing on Arch Linux

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#1356]
Continuing conversation from AUR page @aryoda

Here is the [PKGBUILD](https://gist.github.com/graysky2/0cc61205bb1452184f5eab82d0426be9) I used.

First, building in a clean build root (see [this](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot#Classic_way) article for usage) fails on the check step.  
[backintime-1.3.2-3-x86_64-check-from-build-root.log](https://github.com/bit-team/backintime/files/9945520/backintime-1.3.2-3-x86_64-check.log)

Secondly, when I build outside of the build root (just running `makepkg -sL` as my user also fails on the check step but due to a different error:
[backintime-1.3.2-3-x86_64-check-from-user-build.log](https://github.com/bit-team/backintime/files/9945522/backintime-1.3.2-3-x86_64-check.log)

**Comment by aryoda** [comment]
Found it:

> File "/build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300/common/test/test_diagnostics.py", line 114, in test_distro_package_folder

https://github.com/bit-team/backintime/blob/6fc658dd54f139b20f858e5089d0baa860bb8300/common/diagnostics.py#L339-L343

We have a hard coded path part `backintime` in our diagnostics code which fails to match any path part because `makepkg` + `PKGBUILD` use `backintime-6fc658dd54f139b20f858e5089d0baa860bb8300` (= appending the commit number).

What's strange is: A missing path part should throw an exception of type "ValueError" but it does not in your log but only on my Arch so there is perhaps another problem in the shadow (I will spent some more time on this)

Thanks for your support (and sorry that you had to invest so much time into that - I didn't know much about how PKGBUILD works so far - lesson learned :-)

I will fix the issue soon...

**Comment by aryoda** [comment]
> What's strange is: A missing path part should throw an exception of type "ValueError" but it does not in your log
> but only on my Arch so there is perhaps another problem in the shadow (I will spent some more time on this)

Got it too:

> /build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300/common/test/test_diagnostics.py

Your build path contains `backintime` a few more parents up so there is a match but the wrong one:

> AssertionError: Posix[20 chars]ntime') != Posix[20 chars]ntime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300')

I misinterpreted `Posix..ntime` as DateTime data type but it is just saying that it omitted 20 chars of the Posix path!

**Comment by graysky2** [comment]
Sounds good.  I am glad upstream for this wonderful project is active.  Let me know you'd like me to test.

About PKGBUILDs and the Arch build system in general: so simple and easy.  I say that having used Debian and Fedora packaging before.  The PKGBUILD by comparison is pretty damn easy to read and to create.  Simple bash.

**Comment by buhtzz** [comment]
I'm confused and you have to help me a bit. This is about `common/test/test_diagnostics.py::Diagnostics_FakeFS::test_distro_package_folder`, correct?

I wrote that test. But I'm not into Arch.

`/build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300/common/test/test_diagnostics.py`

Do I understand that correct, that our upstream-repo is cloned into `/build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300`? So this is the full path of the repo on your "local" build system? In other words `/build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300` is the `distro_package_folder()` the method is looking for.

Mhm.. I understand why it is that folder in Arch. I have to think about it.

I try out and assume that I can simple do this on a fresh Arch system.

```
git clone https://github.com/bit-team/backintime.git /build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300
cd /build/backintime/src/backintime-6fc658dd54f139b20f858e5089d0baa860bb8300
cd common
pytest test/test_diagnostics.py::Diagnostics_FakeFS::test_distro_package_folder -v -s
```

This should reproduce the problem?

**Comment by aryoda** [comment]
@buhtzz Yes, this should reproduce it on **any** distro.

I am just wondering why reliable indicator the path gives us to recognize the "installation root folder".
Currently we know for sure that `diagnostics.py` is in `common` (due to our source code and `make install` layout)
and just need to climb up the path two parents to get the project/inst root folder.

So I suggest to fix ` _determine_distro_package_folder()` with:

```
    # level of highest folder named "backintime"
    # bit_idx = path.parts.index('backintime')

    # cut the path to that folder
    # path = Path(*(path.parts[:bit_idx+1]))
    path = path.parent.parent  # ascend to "backintime" folder (the file name in the path is considered as one parent too!)
```

This should always work (I am just testing this).

**Comment by buhtzz** [comment]
> I am just wondering what reliable indicator the path gives us to recognize the "installation root folder".

I'm wondering, too. I took my time and thought back what was my intention to introducing this function. Your "fix" is OK, but doesn't solve the fact that this function is not needed anymore.

I wanted to know if someone use BIT from a git repo, or where it is installed in the OS, or maybe if it runs in an virtual environment. All that informations are caught elsewhere. Knowing the path of the "distribution package folder" (aka project folder, or git repo root) doesn't really help.

So I vote for remove
 - the test
 - the function
 - and of course, the `backintime'->`distribution-package` [field](https://github.com/bit-team/backintime/blob/6fc658dd54f139b20f858e5089d0baa860bb8300/common/diagnostics.py#L47) from the diagnostics. output.

I see not need or "reliable indicator" for something important to that field. What do you think.

**Comment by aryoda** [comment]
> this function is not needed anymore

the node "backintime > started-from" does give exactly the same information
and the function also seems to be a duplicate to this function (which already uses "parent parent") :

https://github.com/bit-team/backintime/blob/914238b64a9f55a1c06e92fd99f53b6b79df0259/common/tools.py#L91-L104

**So I will remove the function and the diagnostics JSON node from the code to fix this issue.**

BTW: Using a non-standard path name to build is an excellent test, I have found more hard coded assumptions (just fixing them too)

**Comment by aryoda** [comment]
@graysky2 I have fixed the issue, could you please re-test?
The issue was closed automatically due to referencing it in my PR, if there should still be a problem, I will re-open it.
THX a lot :-)

**Comment by graysky2** [comment]
- Building from latest commit in a clean build root was successful.
- Building with just `makepkg` as a user was also successful.
