### ISSUE TITLE
Error Saving Configuration

### ISSUE THREAD

**Issue by ont4300** [bit-team/backintime#1365]
Fresh install of 1.3.2 on OpenSUSE Tumbleweed.

Running backintime-qt_polkit when trying to create a ssh backup I get the attached error.  Note that backintime had been working before I did the system rebuild.

I have attached my settings and the error message.

Thanks... Tom.

![backman-settings](https://user-images.githubusercontent.com/24478202/202556358-9cc7181c-a066-42f2-ae29-b444e2a6e61c.png)

![backman-dir-error](https://user-images.githubusercontent.com/24478202/202555133-84cfda0a-290a-4a16-8ed4-88fe9cde34d6.png)

**Comment by buhtz** [comment]
Thanks for your report.
Can you show the output of `rsync --version` (or maybe `-V` or `-VV`).
I assume you have rsync 3.2.4 or higher. If so this is related to #1247 which is still fixed in upstream version.

**Comment by ont4300** [comment]
On the local machine (Tumbleweed).

rsync  version 3.2.7  protocol version 31
Copyright (C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.
Web site: https://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, symlinks, symtimes, hardlinks, hardlink-specials,
    hardlink-symlinks, IPv6, atimes, batchfiles, inplace, append, ACLs,
    xattrs, optional secluded-args, iconv, prealloc, stop-at, no crtimes,
SLP
Optimizations:
    SIMD-roll, no asm-roll, openssl-crypto, no asm-MD5
Checksum list:
    xxh128 xxh3 xxh64 (xxhash) md5 md4 sha1 none
Compress list:
    zstd lz4 zlibx zlib none
Daemon auth list:
    sha512 sha256 sha1 md5 md4

On the remote machine (Leap 15.3)

rsync  version 3.1.3  protocol version 31
Copyright (C) 1996-2018 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 64-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc, SLP

**Comment by ont4300** [comment]
I tried the solution in #1247 and it worked. I am creating a backup now.

I seem to remember doing this dance several months ago, but completely
forgot about the solution.

Thanks for the suggestion... Tom.

**Comment by buhtz** [comment]
Thanks for your feedback.

I opened a bug report at OpenSuse to inform the distro maintainers
https://bugzilla.opensuse.org/show_bug.cgi?id=1205551
