### ISSUE TITLE
Ubuntu 20.04 and 22.04 SSH encrypted issue

### ISSUE THREAD

**Issue by bascetta74** [bit-team/backintime#1379]
Starting with Ubuntu 20.04 and now with 22.04 I have an issue using SSH encrypted.
Though there is no password for the private key and the encryption password is in back-in-time configuration (and cache password for cron is selected), every time I run the program two windows to ask me for the private key and the encryption password appear. The same happens when the program is started by cron.

**Comment by buhtz** [comment]
I'm not the pro in that topic but I assume you will find your problem here in the [README section about known problems (https://github.com/bit-team/backintime#known-problems-and-workarounds).

Please report back if you solved your problem or have further questions.

**Comment by bascetta74** [comment]
It was not easy as I'm not an expert of keyring but at the end I did it!

I followed issue #1321 (Using KDE Wallet works at 2nd attempt only #1321) until the last comment in order to modify the code in backintime/common/tools.py and now works.

Thanks,
Luca


Luca Bascetta, PhD.
Associate Professor
Chair of the Agricultural Engineering Study Programme

Politecnico di Milano
***@***.***
bascetta.deib.polimi.it<http://bascetta.deib.polimi.it>

[cid:c39a46ca-5c3b-423c-9492-304e179aa35f]


________________________________
Da: buhtz ***@***.***>
Inviato: martedì 29 novembre 2022 15:41
A: bit-team/backintime ***@***.***>
Cc: Luca Bascetta ***@***.***>; Author ***@***.***>
Oggetto: Re: [bit-team/backintime] Ubuntu 20.04 and 22.04 SSH encrypted issue (Issue #1379)


I'm not the pro in that topic but I assume you will find your problem here in the [README section about known problems (https://github.com/bit-team/backintime#known-problems-and-workarounds).

Please report back if you solved your problem or have further questions.
