### ISSUE TITLE
Wrong icon of "View last log" in backintime-qt

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#1386]
I am using backintime-qt on Xfce, so under a GTK+ environment.  I am always a bit confused, because the "View last log" entry in the menu bar is associated with a "Create new file" icon.
![image](https://user-images.githubusercontent.com/11256578/206372568-207b0002-fe82-4378-b2b7-a0a5f9bacd06.png)
It doesn't really change with the icon theme, it's just that when using some icon themes the icons are not shown, but only text.
I am not sure, which icon might be better suited, but I always find the current one confusing.
![image](https://user-images.githubusercontent.com/11256578/206372887-8d49c9f3-d15e-422d-b1a3-bf0583955afb.png)
If there's a rationale behind this, then I am fine with it.

**Comment by buhtz** [comment]
I agree to (minimally) wait until our next release before doing bigger things on the GUI.

> https://github.com/bit-team/backintime/blob/55580a1be62560fc059943b9d7575c83cbe6baa0/qt/icon.py#L45
> 
> That is correct and is caused by three possible reasons:

I wouldn't say that is "correct". The loaded icon here is `document-new` which is incorrect because there is no new file created.

This issue here is IMHO not about a missing icon but a wrong one.

I still vote for removing that two log icons. I assume that this toolbar buttons are not used very often. And the functionality itself remains in the "view" menu.

**Comment by aryoda** [comment]
We could **use the standard freedesktop.org icon "document-open-recent"** for the "view last log" toolbar button.

It looks like this in the toolbar (using xcb with the qt5ct platform theme and the `fusion` style):

![Screenshot from 2023-01-23 02-01-20](https://user-images.githubusercontent.com/11374410/213950626-45b2ff7e-8540-44ba-88fe-4231c2dcd65d.png)

I am not really happy with this icon but it is the standard and IMHO we should not invent other semantics for existing icons.

The current icon with the "plus" symbol is:

![Screenshot from 2023-01-23 02-06-42](https://user-images.githubusercontent.com/11374410/213950833-5f018673-fa89-4f1c-94f6-4f8b1b9673af.png)

**Comment by hannes101** [comment]
I think the "document-open-recent" makes sense in that context. However, I would rather not change the other log icon to "document-open", which in my opinion doesn't fit nicely to that particular use.

**Comment by aryoda** [comment]
I have fixed all known systray and app icon issues (hopefully) with my PR #1480 (on dev branch)
and this issue is contained too:

https://github.com/bit-team/backintime/blob/535b1c7bfe04811dec06d1d2599135f373618222/qt/icon.py#L74

Re-testing and feed-back welcome (but not critical for this issue).
