### ISSUE TITLE
[Arch with Chaotic-AUR] unittest in TestTools::test_filesystem & test_device do fail on Chaotic-AUR build system because of overlayfs

### ISSUE THREAD

**Issue by Technetium1** [bit-team/backintime#1389]
The same failure happens for [backintime](https://aur.archlinux.org/packages/backintime) & [backintime-git](https://aur.archlinux.org/packages/backintime-git). Might just a need a check for [`overlayfs`](https://wiki.archlinux.org/title/Overlay_filesystem).

Build logs:
[backintime-git.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/backintime-git.log)
[backintime.log](https://builds.garudalinux.org/repos/chaotic-aur/logs/backintime.log)

```py
python -m unittest  -b test/test_tools.py
.....s..F.Fs.s..s......s................s..s.s...ss.s.s.............
======================================================================
FAIL: test_device (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/main-builder/pkgwork/src/backintime-1.3.2/common/test/test_tools.py", line 447, in test_device
self.assertRegex(tools.device('/nonExistingFolder/foo/bar'),
AssertionError: Regex didn't match: '(:?/dev/.*|tmpfs)' not found in 'overlay'

======================================================================
FAIL: test_filesystem (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/main-builder/pkgwork/src/backintime-1.3.2/common/test/test_tools.py", line 453, in test_filesystem
self.assertRegex(tools.filesystem('/nonExistingFolder/foo/bar').lower(),
AssertionError: Regex didn't match: '(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs)' not found in 'overlay'
```
This was found thanks to a request to add both packages to Chaotic-AUR in https://github.com/chaotic-aur/packages/issues/1733

**Comment by buhtz** [comment]
Hello @Technetium1 ,
thahk you very much for your report.

> ```python
> python -m unittest  -b test/test_tools.py
> .....s..F.Fs.s..s......s................s..s.s...ss.s.s.............
> ```

Beside your Issue the `s` (skipped tests) indicates that there are some more "problems" with your environment. I assume you should setup password-less SSH access to get make the skipped tests run also. But I suspect this doesn't affect the overlay-problem.

How can we reproduce the problem? I assume this isn't a "regular" ARCH installation? What need to be done to get the "overlay thing" activated while our tests run? How did you run that tests (pytest, make, ARCH package installer, ...)? Please keep in mind that we are not ARCH users and we don't share your implicit knowledge about ARCH.

**Comment by buhtz** [comment]
After discussion with "willemw" (the `backintime-git` AUR maintainer) I need to make a step back.

> I assume you should setup password-less SSH access to get make the skipped tests run also.

Of course, it would be great if everyone would test everything. ;) But for "inofficial" package repos like AUR, Chaotic, etc I see no high need to run all BIT tests.

In the future we will reorganize our test cases and divide them into Unit- and Integration-tests. Then distro maintainers can decide themself what parts to test. I would say that moste of the SSH related test cases do belong into the Integration-test category.

**Comment by buhtz** [comment]
@Technetium1 I'm not able to install/activate an overlayfs and run BIT tests with it.
You have to help me with showing the output of `pytest -v -s`.

Another way could be that you modify the tests on your site and tell us if it works. I assume this two modifications would fix the issue.

Modify the regex string in [line 436](https://github.com/bit-team/backintime/blob/55580a1be62560fc059943b9d7575c83cbe6baa0/common/test/test_tools.py#L439)

    r'(:?/dev/.*|tmpfs|instances/containers/travis.*)')

into

    r'(:?/dev/.*|tmpfs|overlay|instances/containers/travis.*)')

And modify that regex string in [line 446](https://github.com/bit-team/backintime/blob/55580a1be62560fc059943b9d7575c83cbe6baa0/common/test/test_tools.py#L446)

    r'(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs|shiftfs)')

into

    r'(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs|shiftfs|overlay)')

**Comment by Technetium1** [comment]
Can I get the same effect of `pytest -v -s` by appending `-v` from: https://github.com/bit-team/backintime/blob/f9b13d022791cb0b467290054eb830069fe310e0/common/configure#L300
to:
`HOME=tmp make -C $_pkgname/common test` in [`check()`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=backintime-git#n31)

I will also try to modify those 2 test and include the results once I do.

**Comment by Technetium1** [comment]
`sed -i 's/tmpfs'\|'/tmpfs'\|'overlay'\|'/g' common/test/test_tools.py`
Results in:
```diff
-                         r'(:?/dev/.*|tmpfs|instances/containers/travis.*)')
+                         r'(:?/dev/.*|tmpfs|overlay|instances/containers/travis.*)')
-            r'(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs|shiftfs)')
+            r'(:?ext[2-4]|xfs|zfs|jfs|raiserfs|btrfs|tmpfs|overlay|shiftfs)')
```
So I append to `check()`:
`sed -i 's/tmpfs'\|'/tmpfs'\|'overlay'\|'/g' $_pkgname/common/test/test_tools.py`

It builds successfully!!!
