### ISSUE TITLE
KDE4 GUI displays mis-encoded characters in log viewer

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#139]
Using the KDE4 GUI (on a regular Ubuntu Unity desktop), the log prints (at least some) Scandinavian characters wrongly. I'll attach a screenshot for demonstration. Meanwhile, the log viewer of the Gnome GUI displays the same characters without problems (I'll attach a screenshot of that as well).

jani@saegusa:~$ apt-cache policy backintime-kde4
backintime-kde4:
  Asennettu: 1.0.36~precise
  Ehdokas:   1.0.36~precise
  Versiotaulukko:
 **\* 1.0.36~precise 0
        500 http://ppa.launchpad.net/bit-team/stable/ubuntu/ precise/main amd64 Packages
        100 /var/lib/dpkg/status

jani@saegusa:~$ locale
LANG=fi_FI.UTF-8
LANGUAGE=fi:en
LC_CTYPE=fi_FI.UTF-8
LC_NUMERIC="fi_FI.UTF-8"
LC_TIME="fi_FI.UTF-8"
LC_COLLATE=fi_FI.UTF-8
LC_MONETARY="fi_FI.UTF-8"
LC_MESSAGES=fi_FI.UTF-8
LC_PAPER="fi_FI.UTF-8"
LC_NAME="fi_FI.UTF-8"
LC_ADDRESS="fi_FI.UTF-8"
LC_TELEPHONE="fi_FI.UTF-8"
LC_MEASUREMENT="fi_FI.UTF-8"
LC_IDENTIFICATION="fi_FI.UTF-8"
LC_ALL=

---

Imported from Launchpad using lp2gh.
- date created: 2015-06-06T05:34:34Z
- owner: uusijani
- the launchpad url was https://bugs.launchpad.net/bugs/1462579

**Comment by Germar** [comment]
(by uusijani)

**Comment by Germar** [comment]
(by uusijani)

**Comment by emtiu** [comment]
Closing, since the separate KDE/GNOME GUIs were abandoned with the 1.1.x release (in favor of a single Qt4 GUI).

In the latest Qt5 GUI (starting with 1.2.x) , I see no problem with non-ASCII (German) characters in the log viewer.
