### ISSUE TITLE
Slow backups

### ISSUE THREAD

**Issue by coffseducation** [bit-team/backintime#1393]
BiT has been excruciatingly slow to backup.
Thu Dec 29 11:17:19 2022 - now 12.46 and only 6% backed up.
78.04 gb in an hour and a half.
Transfer from file manager is faster!

How can I speed it up?

Operating System: Kubuntu 22.10
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.6
Kernel Version: 5.19.0-26-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7820HQ CPU @ 2.90GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: Dell Inc.
Product Name: Precision 5520

Back In Time version:  1.3.2

**Comment by coffseducation** [comment]
SOLVED:
with-
Add --old-args in [Expert Options / Additional options to rsync](https://backintime.readthedocs.io/en/latest/settings.html#expert-options).

**Comment by aryoda** [comment]
@buhtz  Do you know a public documentation for this performance issue due to the changed `rsync` options that we could mention in our README.md?

**Comment by buhtz** [comment]
> @buhtz Do you know a public documentation for this performance issue due to the changed `rsync` options that we could mention in our README.md?

I have no idea (clue?) how `--old-args` and the [rsync-incompatibility-bug](https://github.com/bit-team/backintime#incompatibility-with-rsync-324-or-newer) could be involved here. I see no effect on the performance. It works or it works not. 😄 

I suppose that @coffseducation solved the problem another way without knowing how. It is my strong opinion that `--old-args` wasn't involved.

**Comment by coffseducation** [comment]
> I have no idea (clue?) how `--old-args` and the [rsync-incompatibility-bug](https://github.com/bit-team/backintime#incompatibility-with-rsync-324-or-newer) could be involved here. I see no effect on the performance. It works or it works not. smile

I do not know. All I know is that as soon as I entered `--old-args` I went from 600kb - 2mib to 10-21mib!

**Comment by aryoda** [comment]
OK, let's keep this issue closed and watch if other users report similar issues...

**Comment by Germar** [comment]
> I do not know. All I know is that as soon as I entered `--old-args` I went from 600kb - 2mib to 10-21mib!

rsync normally compares things like name, date and size to check if a file has changed. If rsync found a difference in e.g. date it will create a rolling checksum of both local and remote file and will only transfer changed sectors of the file.
It seems like without --old-args rsync treated all files as 'changed' and creates the rolling checksum for every file. Depending on the hash-power of BOTH (local and remote) CPU this can extremely slow down the snapshot process.
