### ISSUE TITLE
Permissions error on SSH remote

### ISSUE THREAD

**Issue by kc9jud** [bit-team/backintime#1406]
Automatic backups now fail because the remote user doesn't have write access to the _parent_ of the snapshots folder. For instance, if the remote directory is `/mnt/disk` and snapshots are stored in `/mnt/disk/backintime/client`, the permissions check fails if the remote user does not have write access to `/mnt/disk`, even if the user has write permissions in `/mnt/disk/backintime/client`.

This seems like a security issue, since this means that having multiple users back up to the same remote server will require every user to have write access to all other users' directories.

**Comment by kc9jud** [comment]
This appears to have been introduced with 1.3.3? My backups were working through January 13th.

**Comment by buhtz** [comment]
Dear kc9jud,
thank you for your report.

I'm not aware of changes in BIT that could affect write permissions. But maybe.

Can you give us some more background info. Please show us the output of `backintime --diagnostics` and tell us the installation source (distro repo, PPA, ...) of your Back In Time.

Please run BIT via `--debug` flag in a terminal, reproduce the error and post it here please.

Did you update other parts of your system as well?

**Comment by aryoda** [comment]
I am aware of a possibly related similar issue with `ssh` here: #1394

**Comment by buhtz** [comment]
Dear Patrick,
can you please give us some feedback and provide the debug output we asked for.
Otherwise the Issue need to be closed.

Thanks in advance,
Christian

**Comment by kc9jud** [comment]
Let me see if I can reproduce this...

**Comment by buhtz** [comment]
Closing this ticket for now. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
