### ISSUE TITLE
udev setup error: "Couldn't find UUID..." (LUKS-encrypted USB raw block device)

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1408]
When I try to set BiT to `When drive get connected (udev)`, an error appears: 

`Couldn't find UUID for "/path/to/montpoint/backintime/<machine>/root/1"`

The backup device is a `btrfs` FS on a LUKS full disk encrypted USB SSD. It `luksOpen`-s OK and shows up in `findmnt` or `blkid`.

Setting to other schedules works as expected. 

Could the missing UUID error result from the encryption of a full disk instead of a partition? How to work around this? 

Thanks for help or bug fix!

For the record:
backintime and backintime-qt both v1.3.3.1, installed from Manjaro Community repo
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.12-1-MANJARO (64-bit)

**Comment by aryoda** [comment]
> When I try to set BiT to When drive get connected (udev), an error appears...

I am not quite sure if I understand the scenario right that causes the error.

Is the LUKS partition/block device mounted and "open" when you try to choose  `when drive get connected (udev)` in Bit?

> It luksOpen-s OK and shows up in findmnt or blkid.

What do you mean with this sentence? That you can open the LUKS block device in general (so it is not "corrupted") or that is open BEFORE you try to configure BiT (see my first question above)?

**Comment by noyannus** [comment]
I should have been more clear, sorry.

1. Start situation: BiT is set up for scheduled backups, 'Repeatedly (anacron)' or 'Every hour'.
2. I change this in the popup menu to 'When drive get connected (udev)'. 
3. Click 'OK' and the quoted error dialog appears. 

BiT works perfectly with this drive when set to hourly or anacron. I can set and 'OK' these, and the snapshots are made as expected.

I can not rule out that the problem appears only on my system. Something BiT expects on the system that I may have broken?  Is there a way to test the udev part?

Edit: That's where I'm stymied:
![Screenshot_20230224-233257 -001](https://user-images.githubusercontent.com/6339921/221308460-b8a70fcc-5bea-4ff4-a67b-dc4f60ca3d62.png)

**Comment by aryoda** [comment]
**Edit: Please ignore this comment for now and follow my instructions in the 2nd comment below...**

I still don't understand how the LUKS partition is "unlocked" after connecting the USB drive. Could you please describe this process here a little bit?

Could you also please start `udevadm monitor` in a console, connect the USB drive and

1. show the relevant `udevadm monitor` console output for your USB device 
3. show the relevant output of `blkid` (= only the partition on the USB drive) - may be empty
4. the mount information for the USB drive partition (output of `mount`)?
5. The output of `udevadm info --name=/dev/<your usb drive>f`

Our documentation gives a little bit more background how this works in general:

https://backintime.readthedocs.io/en/latest/settings.html

> When drive get connected (udev): this schedule will start a new snapshot as soon as the USB/eSATA/Firewire drive get connected.
> You can configure a delay (hours, days or weeks like in schedule Repeatedly) so it won’t start on every new connection.
> This will add a new udev rule in `/etc/udev/rules.d/99-backintime-<USER>.rules` using the partitions UUID.
> **If using KDE you need to enable auto-mount for the device in System-Settings.**

**Comment by aryoda** [comment]
Internal note: The relevant code for this error msg is this:

https://github.com/bit-team/backintime/blob/e22c7f253fa048fab9119f4cbea34c0fa8d1aba6/common/config.py#L1610-L1618

**Comment by aryoda** [comment]
@noyannus 

> The backup device is a btrfs FS on a LUKS full disk encrypted USB SSD

I have tested it with both scenarios - a LUKS-encrypted partition on a USB memory stick and as LUKS-encrypted raw block device (created via `sudo cryptsetup -v -y luksFormat /dev/sdX`) with a file system within the container: Both scenarios do work with the current DEV version and I do not remember any changes in the last months affecting this code.

I have got the suspicion that the mount point may contain a _space_ or another special character (maybe _escaped_) so that the corresponding UUID cannot be extracted from the `/etc/mtab`.

I need more info from your side: Please mount your drive (incl. opening the LUKS container) and

1. show me the line for the USB device from the output of `findmnt`.
2. show me the line containing the mount info from `cat /etc/mtab`

You can replace sensitive names like your user name or the UUID with `<user name> `and `<UUID> `(please make sure the UUID is really the same before replacing it ;-)

In my example the required output looked like this (which was working in my case):

```
 ─/media/<username>/blue_usb             /dev/mapper/luks-95d3260c-019e-492b-89c1-8ed7b2e4a0d8
...
/dev/mapper/luks-95d3260c-019e-492b-89c1-8ed7b2e4a0d8 /media/<username>/blue_usb btrfs rw,nosuid,nodev,relatime,space_cache,subvolid=5,subvol=/ 0 0
```

**Comment by noyannus** [comment]
Thank you for the time you investigated in the search for a solution!

**Please put all further investigation on hold.**

I see *signs of hardware failure* and will close this issue. May reopen if I can with certainty rule out a hardware problem.
