### ISSUE TITLE
Allow a comment field when creating a snapshot

### ISSUE THREAD

**Issue by dbyy** [bit-team/backintime#1418]
Hello,

It would be nice to have the opportunity to enter a comment when crating a snapshot (e.g. why snapshot has been created during some testing of new installed software) so that a better distinction between snapshots is possible .
e.g. I'm testing some tweaking on phpBB/mySQL and want to have the code&database reversed easily, just in case.
The comment on a snapshot would help me to identify for which stage the snapshot has been created.
I could create an external document with those information but an embedded comment would be easier.
In this scenario I'm creating a snapshot on demand, not on a given schedule.
Perhaps there is already such a feature and I just couldn't find it.
TIA

**Comment by Germar** [comment]
There is indeed already such functionality. You can rename a snapshot which will show the new name in the snapshot list and also prohibit `Smartremove` to remove that snapshot

**Comment by aryoda** [comment]
> You can rename a snapshot which will show the new name in the snapshot list

I think we could add a context menu with a "rename snapshot" entry to make this functionality easier to discover.

It is currently only available in the menu via *Snapshot > Snapshot name* and the keyboard shortcut "F2".

I suggest to
- add a verb to the menu entry (e.g. "Rename snapshot")
- add a context menu for the selected snapshot to rename it
- change the *profile > Auto-remove* checkbox "Don't remove named snapshots" into
  "Don't remove **re**named snapshots" (to consistently use the same "rename" word)..
- trigger our translators ;-)

**Comment by dbyy** [comment]
I not necessarily thought to rename a snap-shop, rather to add a comment field when creating a snapshot.
I'm fine with the originally given name of the snapshot.
For me these are two distinct actions:
a) renaming a snapshot
b) add a comment field when creating a snapshot (perhaps with edit capabilities).
Your thoughts?

**Comment by emtiu** [comment]
Have you tried the existing naming functionality? It does exactly what you want: the automatic name is kept, and your custom name is displayed separately (like a comment). And, it can be edited and removed.

**Comment by buhtz** [comment]
![image](https://user-images.githubusercontent.com/11861496/225947648-2d6233af-e91f-45f4-85cf-7ec4463a0844.png)

**Comment by aryoda** [comment]
I do fully understand the wish for a multi-line comment field (renaming is only a short one-liner).

I'd prefer to fix all major bugs first before implementing this FR since it requires some time to implement (where to store the comment, where to show it, there are at least two dialogs to show and possibly edit it, backwards-compatibility with existing snapshots...).

**Comment by dbyy** [comment]
I understand your point.
Please consider it as a feature request for the future.

Is there not a 'repository' of snapshots, possibly stored in a database like sqlite?

Thanks

**Comment by aryoda** [comment]
THX for your patience :-)

> Is there not a 'repository' of snapshots, possibly stored in a database like sqlite?

The snapshot meta data is stored as files (in one folder per snapshot). A renamed snapshot contains an additional meta file named `name`:

![Screenshot from 2023-03-18 18-51-29](https://user-images.githubusercontent.com/11374410/226124602-520b3ecc-07b3-4250-bb9b-7362f1bcc9d0.png)

**Edit:** I think we could either add another meta file (e.g. `comment`/`notes`) or use the existing `name` file (starting with the comments in line 2 - but comments without renaming would then be less intuitive)...

**Comment by dbyy** [comment]
I took another look at the 'naming' feature and I have to say actually it's helping me to 'name' a snapshot with a specific scenario.
I just didn't know that the F2 key will allow me to add text to the given snapshot name. 
I wouldn't call it a 'rename' function but it's fulfilling the purpose.
Thanks for the tip.
