### ISSUE TITLE
System tray icon does not show when running backintime as root

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#142]
I run backintime as root so that I can backup my entire system. However, when running as root, there is no system tray icon. When running from a command line, the standard error is as follows.

    "sni-qt/3864" WARN  18:00:33.785 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
    No systemtrayicon available
    WARNING: Inhibit Suspend failed.

(I'm also unsure if the inhibit suspend also fails only for root.)

Lack of a system tray icon is annoying, because if the backup job is scheduled, I cannot easily tell when it has completed, so I can eject the backup media.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-06-24T23:49:44Z
 * owner: sparhawkthesecond
 * the launchpad url was https://bugs.launchpad.net/bugs/1468555

**Comment by Germar** [comment]
(by germar)
KDE Plasma 5 seems to prohibit other users (and so does root) from adding SystemTrayIcons to your NotificationArea. I've no idea how to work around this yet.

Inhibit suspend fails for root because this is a dbus sessionbus call and root has no access to users sessionbus.

**Comment by Germar** [comment]
(by sparhawkthesecond)
You may already know this, but just in case…

I installed stalonetray [1] so I could use mail-notifier [2], which doesn't work with the "new" KDE Plasma 5 tray. However, backintime (running as root) automatically popped its icon into this tray when it next ran!


[1] http://stalonetray.sourceforge.net/
[2] http://www.nongnu.org/mailnotify/

**Comment by protist** [comment]
There were some recent fixes in Plasma 5. Now, all of these "old-style" icons are back in the tray, including mail-notifier and backintime (running as root). Hence, this issue can be closed.

**Comment by Germar** [comment]
Great! Thanks for the feedback!
