### ISSUE TITLE
Back in Time (root) won't start due to Qt plug-in xcb (invalid MIT-MAGIC-COOKIE-1)

### ISSUE THREAD

**Issue by dwlamb** [bit-team/backintime#1424]
Having suffered a HD crash, I reinstalled Kubuntu 22.04 and installed Back In Time from the repository. After using Back In Time 3-5 times to recover files from my /home directory back-up, Back In Time will not start any more under root. It will start without root privileges. But I need root access since the backup was made with root privileges.

Steps taken to troubleshoot:

1. completely remove Back In Time using:
  `sudo apt-get remove --purge backintime-*`
  `sudo apt-get autoremove --purge backintime-*`
2. using `find` to locate any file or directory references to 'backintime' starting from '/' I used the results to delete all results from my system
3. The system presumably clean, I reinstalled Back In Time again. Still, after launching Back In Time as root from Krunner or the system menu the programme does not open.
4. Going through the `sys.log` file I found entries similar to:

```
Apr 11 18:00:34 xxx systemd[1391]: Started Back In Time (root) - Backup.
Apr 11 18:00:40 xxx krunner[208557]: Invalid MIT-MAGIC-COOKIE-1 keyqt.qpa.xcb: could not connect to display :0
Apr 11 18:00:40 xxx krunner[208557]: qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
Apr 11 18:00:40 xxx krunner[208557]: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
Apr 11 18:00:40 xxx krunner[208557]: Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
Apr 11 18:00:41 xxx krunner[208541]: Aborted (core dumped)

```

I don't work with Qt. Googling for answers to this problem yielded results more from a developer's p.o.v. or for applications far and away from Back In Time.

**Comment by aryoda** [comment]
Oh dear, an HDD crash! I hope your loss is limited to setup time (and not data)!

I will try to diagnose and find a fix for this tomorrow (local time ;-)

Meanwhile could you please open a console and provide the output of
- `backintime --diagnostics`
- `backintime-qt --debug`
- `backintime-qt_polkit --debug` (**Edit: If have modified this cmd because it was wrong**)

> After using Back In Time 3-5 times to recover files from my /home directory back-up, Back In Time will not start any more under root.

Do I understand it right:

- BiT did run as root on your newly installed system for multiple times and then stopped working?
- How did you start BiT (root)? Via the icon or from the console?

**Comment by dwlamb** [comment]
@aryoda: Thanks for replying

>Oh dear, an HDD crash! I hope your loss is limited to setup time (and not data)!

No major data loss.  Just loss of about 4 hours work between the last back-up and loss of electricity - on a perfectly clear & sunny day - which triggered the drive to fail.

> Do I understand it right:
>-  BiT did run as root on your newly installed system for multiple times and then stopped working?

Correct.

>- How did you start BiT (root)? Via the icon or from the console?

I launched from Krunner; a feature of KDE Plasma. Press Alt+F2 and a dialog box opens at the top of the screen where one can begin typing a command, either as one would for console syntax or just the name and the system utilises the \*.desktop file as in the icon. During the troubleshooting phase I also tried icon and console methods.<br/>All methods yielded similar output in the `sys.log` as quoted in the first message, except when BiT was running properly.

Output of the commands you asked to test.  All run from console as `sudo`:

- sudo backintime --diagnostics (possible error in syntax you requested?)
```
usage: backintime [-h] [--config PATH] [--share-path PATH] [--debug]
                  [--profile NAME | --profile-id ID] [--quiet] [--version]
                  [--license]
                  {backup,backup-job,benchmark-cipher,check-config,decode,last-snapshot,last-snapshot-path,pw-cache,remove,remove-and-do-not-ask-again,restore,shutdown,smart-remove,snapshots-list,snapshots-list-path,snapshots-path,unmount}
                  ...
backintime: error: Unknown Argument(s): --diagnostics
```
- sudo backintime-qt --debug
```
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
Invalid MIT-MAGIC-COOKIE-1 keyqt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

- sudo backintime-qt_polkit --debug
```
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
Invalid MIT-MAGIC-COOKIE-1 keyqt.qpa.xcb: could not connect to display :0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

**Comment by aryoda** [comment]
> sudo backintime --diagnostics (possible error in syntax you requested?)

OK, you have the packaged "old stable" version installed on your system which does not yet have this feature.

> sudo backintime-qt_polkit --debug

For BiT (root) please try this command **without sudo** since `sudo` does behave different to `pkexec` (which is used indirectly via the `.desktop` file:

`backintime-qt_polkit --debug`

Also:

- How did you restore the files (without having a BiT configuration since you had to re-install the OS so the BiT configs/profiles are lost; the profiles are stored in the file `/root/.config/backintime/config` in your case)?
- Did you also restore the files of root's home folder (`/root/`)?
- What is the output of `sudo xhost`?
- Does `xauth list` show an existing MIT-MAGIC-COOKIE?

PS: Perhaps the MIT-MAGIC-COOKIE-1 cookie file was overwritten with an old version which would then no longer match between the Xorg server and the "client" (it is stored in a file specified after the `-auth` argument of the running xorg, use `ps ax | grep -i xorg` to show this).

**Comment by dwlamb** [comment]
Hello again aryoda,

> backintime-qt_polkit --debug

This worked. BiT prompted from my root password and I went through the steps of recovering the configuration from the sub-directory on the back-up drive. 

Output from console:
```console
DEBUG: [common/backintime.py:583 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.2.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:670 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:671 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/config.py:377 Config.setSnapshotsPath] Check snapshot folder: /media/ExtLinux/backups
DEBUG: [common/config.py:291 Config.checkConfig] Check profile Main profile
DEBUG: [common/tools.py:1244 readCrontab] Read 1 lines from users crontab
DEBUG: [common/config.py:1477 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1511 Config.cronLine] Profile: Main profile | Automatic backup: Every Day
DEBUG: [common/tools.py:1281 writeCrontab] Wrote 3 lines to users crontab
DEBUG: [common/configfile.py:529 Config.setCurrentProfile] change current profile: 1=Main profile
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:1244 readCrontab] Read 3 lines from users crontab
DEBUG: [common/config.py:1477 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1511 Config.cronLine] Profile: Main profile | Automatic backup: Every Day
DEBUG: [common/config.py:1461 setupCron] Crontab didn't change. Skip writing.
DEBUG: [common/tools.py:812 keyringSupported] No keyring due to import error.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:81 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
```

Exiting BiT and restaring it again as root from Krunner or Menu icon and BiT works.


> Also:
> 
> How did you restore the files (without having a BiT configuration since you 
> had to re-install the OS so the BiT configs/profiles are lost; the profiles 
> are stored in the file `/root/.config/backintime/config` in your case)?

As accomplished today, BiT presented a dialog box with the question:<br />`Back In Time is not configured. Would you like to restore a previous configuration?`.<br/>I clicked OK and followed the prompts, recovering the  configuration from a previous back-up set saved to the back-up drive.

>     * Did you also restore the files of root's home folder (`/root/`)?

No. I was not clear in my original post. The hard drive that crashed was Kubuntu 20.04. I decided to upgrade now and use my settings from the `/home` on the old system to this system as a baseline. 


> What is the output of `sudo xhost`?
 
Output:
```console
access control enabled, only authorized clients can connect
SI:localuser:daniel
```

> Does `xauth list` show an existing MIT-MAGIC-COOKIE?

Yes.

Redacted output:

```console
<hostname>/unix:0  MIT-MAGIC-COOKIE-1  <32 character hash>
```

> PS: Perhaps the MIT-MAGIC-COOKIE-1 cookie file was overwritten with an old 
> version which would then no longer match between the Xorg server and the 
> "client" (it is stored in a file specified after the -auth argument of the 
> running xorg, use ps ax | grep -i xorg to show this).

I believe that identifies what happened. Reading subsequent articles regarding `.Xauthority`, that file would have been rewritten by what is on the back-up set. I've never enountered an xauth/`.Xauthority` issue before as I have moved my `home` from one computer to another or reformatted a root drive to install a new distro.

`ps ax | grep -i xorg` output:

```console
   1555 tty1     Ssl+   0:43 /usr/lib/xorg/Xorg -nolisten tcp -auth /var/run/sddm/{355f9b5a-0d59-4976-bf4b-7b56559ac93b} -background none -noreset -displayfd 17 -seat seat0 vt1
  10142 pts/3    S+     0:00 grep --color=auto -i xorg

```

Live and learn, hoping you find someone along the way to share knowledge.

**Comment by aryoda** [comment]
THX, all the output looks good so far!

>>    backintime-qt_polkit --debug

> This worked. 
> ...
> Exiting BiT and restarting it again as root from Krunner or Menu icon and BiT works.

So does BiT (root) work again on your computer or am I misinterpreting this?

If it works now (to document the solution here for others before closing it):

- Did you do any other steps than starting `backintime-qt_polkit --debug` once?
- What does `echo $XAUTHORITY` show? Background: If set it points to another location for the `.Xauthority` file...
- What is the output of `$XDG_SESSION_TYPE`?

If it still does not work:

- Does your home folder contain an `.Xauthority` file at all?
- Did your backup folder contain the `.Xauthority`
- What does `echo $XAUTHORITY` show? 
- What does `sudo echo $XAUTHORITY` show? 
- What is the output of `$XDG_SESSION_TYPE`?

BTW: Running GUI-based apps like BiT (root) with `sudo` **is not recommended** since newer display managers cause authorization issues to improve the security (separation of processes). This is why BiT (root) uses above startup script which uses `pkexec` instead.

**Edit:** Internal dev note: All details about the MIT-MAGIC-COOKIE-1 are explained in `man 7 xsecurity`

**Comment by buhtz** [comment]
I don't understand all details here but this Issue reminds me on some of my own. I got that `xcb` error while testing the migration of BIT from PyQt5 to PyQt6.

I got the important help about that xcb-error-message in that Qt Forum thread:
https://forum.qt.io/topic/145196/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/6?_=1684784759656

It depends on where the plugin is installed. Maybe look for the location of a file `libqxcb.so`. Then call `ldd /path/to/libqxcb.so` and look in the output. There might be a `not found` line like this

    libxcb-cursor.so.0 => not found

Depending on the "not found" file you might know which package is missing. In my case I just need to install `libxcb-cursor` via `apt` on Debian system.

**Comment by aryoda** [comment]
> > PS: Perhaps the MIT-MAGIC-COOKIE-1 cookie file was overwritten with an old
> > version which would then no longer match between the Xorg server and the
> > "client" (it is stored in a file specified after the -auth argument of the
> > running xorg, use ps ax | grep -i xorg to show this).
> 
> I believe that identifies what happened. Reading subsequent articles regarding `.Xauthority`, that file would have been rewritten by what is on the back-up set. I've never enountered an xauth/`.Xauthority` issue before as I have moved my `home` from one computer to another or reformatted a root drive to install a new distro.

I think we could close this issue since it works again and we have a plausible hypohesis what caused the problem.

@dwlamb Please raise your hand if we should keep this issue open for a reason otherwise I will close it after a cooling-off period of a few weeks. THX a lot for your great collaboration!
