### ISSUE TITLE
"View Last Log" Errors - failed: Read-only file system

### ISSUE THREAD

**Issue by ryankingart** [bit-team/backintime#1426]
**After taking a snapshot, I like to check the "View Last Log" to make sure there wasn't any errors. Recently, some errors have started appearing, after I take the snapshots.**

**There are probably a few hundred lines of errors, but here is an example of one:**

 _[E] Error: rsync: [generator] recv_generator: mkdir "/media/ryanking/WD Elements/backintime/ryanking/root/3/new_snapshot/backup/home/ryanking/.mozilla/firefox/qf2nbac4.default-release-1/storage/default/https+++polyhaven.com" failed: Read-only file system (30)_

**The errors mostly seem to have to do with Firefox data, and they all have the: failed: Read-only file system, at the end of the error. Not sure why this just started happening, and I'm also not sure what data exactly its not backing up. Some sort of website history or storage I guess.**

**Although some of the errors have to do with other programs, like this one:**

_[E] Error: rsync: [receiver] mkstemp "/media/ryanking/WD Elements/backintime/ryanking/root/3/new_snapshot/backup/home/ryanking/.config/skypeforlinux/skylib/.slimcore-ecs-cache.data.5MttIz" failed: Read-only file system (30)_

**After the snapshot is finished, when I click on the take snapshot button again, it sometimes reads:**

_Found leftover snapshot which can be continued._
_Done, no backup needed_

**I Installed Back In Time with these commands:**

```
sudo add-apt-repository ppa:bit-team/stable
sudo apt-get update
sudo apt-get install backintime-qt
```

**My OS:**  Linux Mint 21.1 Cinnamon
**Cinnamon Version:**   5.6.8

**Terminal output after the command: `backintime --diagnostics`.**

{
    "backintime": {
        "name": "Back In Time",
        "version": "1.3.3-3",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": false,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": false
    },
    "host-setup": {
        "platform": "Linux-5.15.0-67-generic-x86_64-with-glibc2.35",
        "system": "Linux #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023",
        "os-release": {
            "NAME": "Linux Mint",
            "ID": "linuxmint",
            "PRETTY_NAME": "Linux Mint 21.1",
            "VERSION": "21.1 (Vera)",
            "ID_LIKE": "ubuntu debian",
            "VERSION_ID": "21.1",
            "HOME_URL": "https://www.linuxmint.com/",
            "SUPPORT_URL": "https://forums.linuxmint.com/",
            "BUG_REPORT_URL": "http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/",
            "PRIVACY_POLICY_URL": "https://www.linuxmint.com/",
            "VERSION_CODENAME": "vera",
            "UBUNTU_CODENAME": "jammy"
        },
        "display-system": "x11",
        "locale": "en_US, UTF-8",
        "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.10.6 main Mar 10 2023 10:55:28 CPython GCC 11.3.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.10",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python310.zip",
            "/usr/lib/python3.10",
            "/usr/lib/python3.10/lib-dynload",
            "/usr/local/lib/python3.10/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.10/dist-packages"
        ],
        "qt": "PyQt 5.15.6 / Qt 5.15.3"
    },
    "external-programs": {
        "rsync": {
            "program": "rsync",
            "version": "3.2.7",
            "protocol": "31.0",
            "copyright": "(C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.",
            "url": "https://rsync.samba.org/",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ],
            "license": "GPLv3",
            "caveat": "rsync comes with ABSOLUTELY NO WARRANTY"
        },
        "ssh": "OpenSSH_8.9p1 Ubuntu-3ubuntu0.1, OpenSSL 3.0.2 15 Mar 2022",
        "sshfs": "3.7.1",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
    }
}

**Comment by emtiu** [comment]
Thanks for you report and debug data! Until someone finds the time to look into this more closely, I'd advise that you run some checks on the target filesystem or drive (WD Elements, from what I can see).

Intermittent "read-only filesystem" errors can be an indication of filesystem corruption or hardware failure, and that's obviously something you would want to rule out.

**Comment by ryankingart** [comment]
Thanks for your help @emtiu 
I checked the hard drive via the disks manager, and got this error:

![Error](https://user-images.githubusercontent.com/52793051/233164345-65277a04-572b-43ad-b737-335961d751b7.jpg)

Could this also be a sign of the hard drive failing? Also, I have three redundant external hard drives that I use to backup my files, and I have them setup as three different profiles on back in time. When I backed up the other two hard drives, the back in time errors did not occur. So it may just be that I need to replace that hard drive.

If you think this is the problem, I can close this issue on GitHub.

**Comment by emtiu** [comment]
From what you're reporting, I'd say there is a high chance that the drive is failing. It's good that your backups are redundant :)

Also, if the same BackInTime configuration for the same files/folders works on other drives, then the drive is probably the root cause of the errors you are seeing.

**Comment by ryankingart** [comment]
Thanks for your help!

**Comment by aryoda** [comment]
>I checked the hard drive via the disks manager, and got this error:
>
> ![Error](https://user-images.githubusercontent.com/52793051/233164345-65277a04-572b-43ad-b737-335961d751b7.jpg)

According to `man e2fsck` the exit code 12 (which is binary encoded via 8 + 4) means

- 4    - File system errors left uncorrected
- 8    - Operational error

which gives not much background about the reason(s).

May I propose that you boot a live Linux system (e.g. via a USB memory stick) to repair your file system so that the file system is not in use while checking it...

**Comment by ryankingart** [comment]
@aryoda Are you suggesting that I do that for my main computer's hard drive, or the external hard drive that I was using for the backup?

**Comment by aryoda** [comment]
Good point, I didn't realize the target drive is an external drive so there is no need to boot and fschk using a live linux
