### ISSUE TITLE
ReadTheDocs: Create a .readthedocs.yaml configuration file

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1443]
ReadTheDocs [informed](https://blog.readthedocs.com/migrate-configuration-v2/) us that they need a `.readthedocs.yaml` file in each repository. The deadline is at 25th September 2023.

This is also related to our separate [user-documentation repository](https://github.com/bit-team/doc).

It might be easy to achieve and I still have done this for my repos on Codeberg.org (but they are using pydoctor instead of sphinx).

**Comment by buhtz** [comment]
This is the original BIT dev-docu. There is layout problem in the sidebar and also in the footer (not shown here). The text do overflow into the content area.
![image](https://github.com/bit-team/backintime/assets/11861496/8065c376-28c0-4cba-acef-fecbaebd57e5)

I don't know the reason. I just switch to the Sphinx-ReadTheDocs theme which looks a bit like the old Python 2 docu.
[Here is a testing-version of the new BIT docu with "Sphinx-RTD" theme](https://bit-testing-readthedocs.readthedocs.io/).
![image](https://github.com/bit-team/backintime/assets/11861496/fc4124a8-5caf-4855-8557-bef0701c08cb)

I will prepare a PR with the [yaml-file](https://github.com/buhtz/backintime/blob/testing_readthedocs/.readthedocs.yaml) soon.

**Comment by aryoda** [comment]
> I just switch to the Sphinx-ReadTheDocs theme which looks a bit like the old Python 2 docu.
> https://bit-testing-readthedocs.readthedocs.io/

Good decision, your testing version does work with my Firefox and looks very nice IMHO!
