### ISSUE TITLE
"Done, no backup needed" if host/user/profile fields empty

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#145]
BiT will not take incremental backups if the host, user, and/or profile fields in the profile settings are empty.

I have two profiles: An hourly backup for frequently used files and dirctories -- this one works flawslessly without problems.

The other profile is a 'complete backup' that I run every once in a while. To keep the backup path short, I had deleted the host/user/profile information in the profile settings. BiT would create the initial backup, but would report "Done, no backup needed." whenever I tried to create subsequent backups. Formatting the backup drive and starting all over did not help.

As soon as I filled in those fields, BiT started to work fine again.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-07-23T19:16:00Z
 * owner: bovender
 * assignee: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1477733

**Comment by gmk57** [comment]
I still have this issue with BiT 1.1.12-2 on Linux Mint 19.1.

**Comment by Germar** [comment]
Those fields are essential for BiT. Subsequent versions doesn't allow them to be empty anymore. Just fill them and all works fine

**Comment by gmk57** [comment]
Are they really that essential? If BiT is used for local backup, there is often a single machine, single user and even single profile. And, all else being equal, it is better to "keep the backup path short", as you noted in your first message.
