### ISSUE TITLE
mount.py: F821 Undefined name "grp" / Check fuse-group membership

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1450]
While reviewing my own PR #1448 with linters (ruff & pycodestyle) I found a possible bug.
Ruff says `common/mount.py:608:36: F821 Undefined name "grp"` .
https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/mount.py#L591
It should IMHO throw a `NameError`. Further investigation needed.

 - When was it introduced (commit history)?
 - What happens there?
 - Why isn't there a known issue about that problem?
 - Do we need that code if it is never reached?

**Comment by buhtz** [comment]
Now it becomes very interesting. :smile: In most cases that code is never reached because `self.CHECK_FUSE_GROUP` is `False`.

But when does it become `True`!? This happens on specific circumstances at build/install/packaging stage in `configure` script.

https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/configure#L143-L150

Some lines above we can see that `$FUSE_GROUP` is set by a command line argument while calling `./configure`. When called with `--fuse-group` then `configure` do **edit the python files** replacing the default value for `self.CHECK_FUSE_GROUP`. 

This behavior was introduce 2013 via 26474f8e0ed3dc6df597e41e6e5b72842e375d88 .

The behavior is justified with "Some distributions require user to be in group 'fuse' to use sshfs and encfs".

Do we know which GNU/Linux distributions are meant here?

My answer to this would be that we are upstream and shouldn't care (much) about distro specific things. It is up to the package maintainer of each distribution to take care of things like this. We can only provide correct error messages for the cases causing that error.

What is your opinion about that? @Germar do you have any knowledge or history about that "user should be in fuse-group" problem?

### EDIT
The code was introduced 2013 and to my knowledge and research never executed. I couldn't find no issue at Microsoft GitHub or Launchpad about that. It seems to me that the fuse-group situation isn't important anymore or was never. So we could just remove all that fuse-thing.
I also wonder if someone installs `sshfs` and you need to be in `fuse` group to use it, shouldn't the distro package maintainer of `sshfs` take care of that and add the user to that group with some package-install-magic? Why do need BIT take care of that?

**Comment by Germar** [comment]
There is just an `import grp` missing in `mount.py`. Looks like I forgot to move that from `schools.py` and `encfstool.py`.

I'd keep that function. There was a problem with silently failing if user is not in group fuse. I can't remember which distro, but it was definitely in use.

**Comment by buhtz** [comment]
> There is just an `import grp` missing in `mount.py`. Looks like I forgot to move that from `schools.py` and `encfstool.py`.

Ah, I thought it is a typo. I'll fix that.

> I'd keep that function. There was a problem with silently failing if user is not in group fuse. I can't remember which distro, but it was definitely in use.

IMHO it doesn't matter if that problem still exists or not. It is not our upstream problem. Things like this are in the responsibility scope of the distributions.

Beside of that it seems to me that the problem is not relevant anymore today. I found some old sshfs-related posts and wikis talking about adding users to fuse-group. Some of them are "confused" because this doesn't solve there problem. The advice to add user to fuse-group is gone today. Ubuntu doesn't write about that anymore. Maybe it happens while installing sshfs or sshfs doesn't need it anymore. On my Debian "fuse" doesn't even exist.

My compromise would be not to remove that code but to deactivate it (e.g. via comments). We could also add some `--diagnostics` information about existance of `fuse` and `fuse_membership` if the problem really ocure again.

**Comment by buhtz** [comment]
Note to myself about https://github.com/bit-team/backintime/blob/72ced78a5ee3c7803e0cba16e11698af4d883535/common/sshtools.py#L203-L205

Check for `proc.returncode != 0` or better do positive check `if proc.returncode == 0: return`.

**Comment by buhtz** [comment]
Please let me summarize my research

1. Today's Wikis don't mention that the user need to be part of group `fuse` anymore. E.g. [Arch-Wiki](https://wiki.archlinux.org/title/SSHFS), [Ubuntu-Wiki](https://wiki.ubuntuusers.de/FUSE/sshfs/)
2. Sources mentioning the user group `fuse` are out dated. E.g. [ciyberciti.biz - year 2017](https://www.cyberciti.biz/faq/how-to-mount-remote-directory-filesystems-with-sshfs-on-linux/)
3. [Questions about this on the `sshfs` upstream mailing list](https://sourceforge.net/p/fuse/mailman/fuse-sshfs/thread/5bd24491819c1bd96ba8190b5d54324a%40posteo.de/#msg37864051) also support my assumptions.
4. The [kernels docu about FUSE](https://www.kernel.org/doc/html/latest/filesystems/fuse.html) also don't indicate any need for such a user group.
5. I also don't see how errors related to `sshfs` could occur "silently". The return code of its call is checked.
6. To my knowledge, since this code (including its missing `import grp`) was introduced in 2013, no one reported a bug or issue about that _undefinied name "grp"_. Therefore, the probability is high that this code was never reached by any user.

Because of that I would vote to remove the whole fuse-group related code instead of refactoring it.
