### ISSUE TITLE
dummytools.py: F821 Undefined name "parent"

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1451]
While reviewing my own PR #1448 with linters (ruff & pycodestyle) I found a possible bug. Further investigation needed.
https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/dummytools.py#L51
Ruff says `common/dummytools.py:51:61: F821 Undefined name "parent"`.

 - When was it introduced (commit history)?
 - What happens there?
 - Why isn't there a known issue about that problem?
 - Do we need that code if it is never reached?

**Comment by buhtz** [comment]
> https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/dummytools.py#L51

I assume that [`mount.MountControl.parent`](https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/mount.py#L66) is meant instead of `parent`.

The `class Dummy` isn't used anywhere. It seems just to be an example about how to derive from `mount.MountControl`. My first suggestion would be to move this into the (user or development) documentation somewhere.

**Comment by Germar** [comment]
Have a look in sshtools.py:

https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/sshtools.py#L78-L80

`Dummy` is a template for future classes.

**Comment by buhtz** [comment]
Dear Germar,
thanks for the quick reply.

> Have a look in sshtools.py:

Not sure if I interpret that correct. So you mean I'm right with my assumption that `parent` should be replaced with `self.parent`?

> `Dummy` is a template for future classes.

I don't get that point. That code is never used.
If it is a "template" in the meaning that other developers should use that code as a start to create there own `mount.MountControl` based classes then I would say this should go into documentation (e.g. docstrings) and not into productive code.

**Comment by Germar** [comment]
> Not sure if I interpret that correct. So you mean I'm right with my assumption that `parent` should be replaced with `self.parent`?

No, `parent` is a `QWidget` or `None` set in `class Mount` in `mount.py`

> If it is a "template" in the meaning that other developers should use that code as a start to create there own `mount.MountControl` based classes then I would say this should go into documentation (e.g. docstrings) and not into productive code.

I don't care. I think it's easier to just copy `dummy.py` when someone starts a new `mount.MountControl` based classes. But you can move it into dev-doc if you like.

**Comment by buhtz** [comment]
> > Not sure if I interpret that correct. So you mean I'm right with my assumption that `parent` should be replaced with `self.parent`?
> 
> No, `parent` is a `QWidget` or `None` set in `class Mount` in `mount.py`

Sorry, I'm confused and don't get it.
Then how to solve the problem "Undefined name 'parent'"?

**Comment by Germar** [comment]
`parent` is  defined in `mount.MountControl`. `Dummy` inherit from `Mount.MountControl`, so it contains all args and functions, that `mount.MountControl` defined.

To solve the `undefined name` problem you need to tell the tool to resolve the inheritance of the class

**Comment by buhtz** [comment]
I assume there is a misunderstanding. But maybe I can't see the forest for the trees. 😅 

> To solve the `undefined name` problem you need to tell the tool to resolve the inheritance of the class

The tool is able to resolve inheritance.

My point (and the problem of Python and the linter) is that the name/object `parent` is unknown in `Dummy.__init__()`. It is not a variable in the methods names space. It is not an argument.

I do understand that conceptually it is inherited from `class Mount` which can be seen here:
https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/mount.py#L66

Because of that that line
https://github.com/bit-team/backintime/blob/8fbec2d5e2d3c40af7cad5f5c6945ac1adf15f9e/common/dummytools.py#L51

IMHO should be modified into

    self.setattrKwargs('password', self.config.password(self.parent, self.profile_id), store = False, **kwargs) 
                                                        ^^^^^

Am I wrong here somehow? I don't want to break anything.

**Comment by aryoda** [comment]
> IMHO should be modified into
> 
> ```
> self.setattrKwargs('password', self.config.password(self.parent, self.profile_id), store = False, **kwargs) 
>                                                     ^^^^^
> ```
> 
> Am I wrong here somehow? I don't want to break anything.

@buhtz If think `self` is required here to access the attribute of the (parent) object.
Without `self` it would refer to local or global variable (which do not exist).

Since I wasn't sure myself I have used this example code to check this:

```
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname
    self.parent = "a variable in the parent class"

  def printname(self):
    print(self.firstname, self.lastname)


class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

    print(f"parent (self): {self.parent}")  # works
    # print(f"parent: {parent}")            # NameError: name 'parent' is not defined. Did you mean: 'print'?

  def welcome(self):
    print("Welcome", self.firstname, self.lastname, "to the class of", self.graduationyear)



x = Student("Mike", "Olsen", 2019)
x.welcome()
```

**Comment by aryoda** [comment]
@buhtz You have copied the template code of `class Dummy` from `dummypytools.py` into a doc string in `mount.py` via the commit https://github.com/bit-team/backintime/commit/1003d360d758bce78c6cd528ea41df3734fec95b but the code for `class Dummy` is still contained in `dummytools.py` (even though you wrote "move" in your commit message):

https://github.com/bit-team/backintime/blob/71c9657324c0e08dd3288dbff830dd90c1cc15d2/common/dummytools.py#L21

Was this intentional?

BTW:  If "parent is a QWidget" in some cases (which I have not checked) we should refactor this with our GUI redesign since the backend logic (in `common`) should never see any GUI object from (e.g. use the observer pattern instead to ask a listener)

**Comment by buhtz** [comment]
> @buhtz You have copied the template code of `class Dummy` from `dummypytools.py` into a doc string in `mount.py` via the commit [1003d36](https://github.com/bit-team/backintime/commit/1003d360d758bce78c6cd528ea41df3734fec95b) but the code for `class Dummy` is still contained in `dummytools.py` (even though you wrote "move" in your commit message):

Autsch. I'll fix that mistake.
Reopen because common/dummytools.py still exists but should be deleted.
