### ISSUE TITLE
Why use setThemeName() and why is it never reached?

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1468]
I found a piece of code and don't understand what it does or why it is there. Maybe someone can light me up with it. I have some PR's on my todo list relating to this.

https://github.com/bit-team/backintime/blob/e44e9d64b972be2dab3aa0f94af34d44e80eabf9/qt/icon.py#L19-L26

It was introduced 9 years ago (and slightly modified since then) via c95b616.

The `setThemeName()` is never reached on my tests. What is the purpose and intended behavior here?
Can't exactly see how #1364 and #1306 is related to it.

**Comment by buhtz** [comment]
After a cup of coffee...

Please correct me if my assumptions not correct here. Qt do use the currents system theme by default. But sometimes an icon is not available in that theme. In this case this code do check other (well known) themes (3 in this piece of code) if the icon is available there. If it is the case then this alternative theme is set for BIT no matter what the current systems theme is. Right?

Some thoughts about that
 - First of all I'm interested why icons not available in a theme? We don't use such exotic icons in BIT. Maybe something is wrong with the icon handling and not with the theme.
 - Why is `document-save` used in this piece of code. I would bet this is an "extrem standard icon" available in every icon theme ever used. It will never be unavailable in any theme.
 - Using an alternative theme is IMHO not a good behavior. It seems more appropriate to fall back to Qt's in build icons available via `QStyle` in that case. There are not much and they are not pretty. But they are there.

**Comment by aryoda** [comment]
> Why use setThemeName() and why is it never reached?

This LOC **is** executed but only if none of the white-listed themes is installed (so the last white-listed theme "oxygen" is activated then even though it is not installed - this is a bug and I have fixed it in my upcoming PR)

**Comment by buhtz** [comment]
Did you know about [Qt's in-build icons](https://www.pythonguis.com/faq/built-in-qicons-pyqt/)?

> this is a bug and I have fixed it in my upcoming PR)

Ah, good to know. Then I will wait with refactoring `qt/icon.py` to prevent locale namespace imports happening here:

```
$ git grep "import icon" **/*.py
qt/app.py:77:        import icon
qt/app.py:1502:        import icon
qt/logviewdialog.py:54:        import icon
qt/messagebox.py:31:    import icon
qt/qtsystrayicon.py:61:        import icon
qt/restoredialog.py:44:        import icon
qt/settingsdialog.py:84:        import icon
qt/settingsdialog.py:2097:        import icon
qt/settingsdialog.py:2430:        import icon
qt/snapshotsdialog.py:51:        import icon
qt/snapshotsdialog.py:95:        import icon
```

**Comment by aryoda** [comment]
> Did you know about [Qt's in-build icons](https://www.pythonguis.com/faq/built-in-qicons-pyqt/)?

Yes, and I will reuse one of these icons as fallback if possible.

> Then I will wait with refactoring qt/icon.py 

THX :-)  I will speed up hopefully

**Comment by buhtz** [comment]
My idea is to refactor it to something like [this](https://www.riverbankcomputing.com/pipermail/pyqt/2023-July/045389.html).

```
from PyQt5.QtGui import QIcon

ICONS = {'PAUSE': 'media-playback-pause'}

def __getattr__(name):
    return globals().setdefault(name, QIcon.fromTheme(ICONS[name]))
```

Or why not just wipe out `icon.py` and just use `QIcon.fromTheme()` directly where it is needed. I don't see much value in icon.py. Some more coffee is needed...
