### ISSUE TITLE
Provide documentation how to use BiT on Synology NAS via a docker container

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1471]
The  operating system of Synology NAS devices ("DSM") support installing and running docker images quite easily.

There is at least one docker container available that packages BiT into an image meant to be run on a Synology NAS:

https://hub.docker.com/r/intelliops/backintime
(based on a BiT fork: https://github.com/belsander/backintime)

Document (e.g. in the [FAQ](https://github.com/bit-team/backintime/blob/dev/FAQ.md#hardware-specific-setup))
- the possible use cases
- how to install the docker container
- impact on security and stability

Optional:
- Also consider other NAS systems like QNAP, Western Digital etc.

PS: THX to @buhtz for bringing up this topic!

**Comment by buhtz** [comment]
Is someone able to provide these information? The use case seems to be rare.

Otherwise I vote to close the issue.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
