### ISSUE TITLE
Discussion: re-arrange the menubar and its entries

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1482]
I would like to discuss if and how we could rearrange the mainwindows menubar and its entries. Additionally I see the need to separate the multiple meanings of "snapshot" and find consensus about alternative terms.

# Current situation

![image](https://github.com/bit-team/backintime/assets/11861496/7c26a66e-39f0-4e07-80f3-fbd9f114da26)

# My intention and goals
My intention in the back is to place a "Setup language" menu entry somewhere where the users can select the UI language. I couldn't find a good place. Add a new menu entry on the first level seems a bit to much. We also don't have an application specific settings dialog where this usually would be placed.

I don't want to make it perfect. This means I don't want to to modify and fix everything that could be discusses. For example the help menu itself needs to be discussed; but not here. I want to keep it as simple as possible.

# What is a "Snapshot"?
One other thing I want to take into account is the terminology about "Snapshot". In my opinion this term does have multiple meanings in the way it is currently used in BIT's UI (and also in the code base). We need to separate the meaning between:

1. A "snapshot" as the result of an rsync run. It is in the backup destination a folder named with a specific timestamp.
2. The "profile" (or alternative term; e.g. "backup job", "backup task") which is represented by all `profile*` lines in the config file, in the settings dialog and the whole mainwindow itself.

I think the meaning of "snapshot" is clear. But we should find a term for what I would call a "profile" and using it consequently. I choose "profile" because this term is used in "Main profile", in the settings dialog and sometimes in the terminal output.

# My rough proposal about the menubar
- New menu "Back In Time" as first and application specific menu.
- New menu "Profile" was added.
- I removed the "View"
  - Entries "Up" and "Show hidden" are removed without replacements. They do exists in the fileview toolbar.
  - Other entries are moved to snapshot or profile menu.

```
- Back In Time
    - Setup language
    - Shutdown
    - Exit
- Profile
    - Settings
    - Take a snapshot
    - Take a snapshot with checksum
    - View last log
    - Refresh snapshot list
    - Snapshots
- Snapshot
    - Remove
    - View log
- Restore
    - Restore
    - Restore to ...
    - Restore {current_folder}
    - Restore {current_folder} to ...
- Help
    - Help
    - Config
    - Website
    - Changelog
    - FAQ
    - Ask a question
    - Report a bug
    - About
```

The "Snapshot" and "Restore" menus are only enabled if a snapshot is selected in the timeline.

I could be said that "Restore" is related to a specific "Snapshot" and should belong to this menu. I agree with this logic. But "Restore" is one of the main features. It might not be consistent but it is more "shiny" to have this as a separate menu.
On the other hand the "Snapshot" only has two entries. It wouldn't hurt to move the entries from "Restore" into it. What do you think?

"Refresh snapshot list" could be renamed into "Refresh snapshot timeline" or "Refresh timeline".

"Profile" -> "Snapshots" opens the `SnapshotsDialog`. As I discussed in #1485 that dialog can be removed in the future. But until then we need to place its entry point somewhere in the menus and find a label for it. The current label is IMHO to broad but I can't find a better solution.

As I said there is much more room for improvement. But would keep it simple only would modify it that way that I'm able to have a good place for the language menu. Everything else should be done in a separate Issue/PR and is not urgent.

**Comment by buhtz** [comment]
I updated the proposal in some details.

**Comment by aryoda** [comment]
Great initiative, UX has much room for improvement :-)

Here are my comments:

```
- Back In Time
    x Setup language                      # introduce a "Preferences" menu entry instead to centralize more settings
    + Preferences...                      # with "Setup language" and "Show hidden files in snapshots" (default when BiT is started)
    - Shutdown
    - Exit
- Profile
    x Settings                            # very confusing, this is to edit profiles! Move to "Profile" menu
    + Manage profiles...                  # formerly known as "Settings" (which is confusing)
    - Refresh snapshot list
    - Take a snapshot
    ? Take a snapshot with checksum       # confusing for the user, what is the difference to "Take snapshot"?
                                          # IMHO the additional value (use case) is that the snapshot is compared to the original files at the end of the snapshot
                                          # to ensure the integrity. So we could name it somehow similar to (but shorter ;-)
                                          Take snapshot with file integrity check
                                          # I cannot find this entry anymore in HEAD@dev, have we lost something?
                                          # AFAIR @buhtz: You had refactored the toolbar buttons into one button that open sub buttons, right?
    - View last log
    ? Snapshots                           # Unclear term and use case: IMHO the primary use case is to compare snapshots (great feature!)
- Snapshot
    + Compare snapshots                   # formerly known as "Snapshot"
    + Rename snapshot
    - Remove snapshot
    - View snapshot log
- Restore
    - Restore
    - Restore to ...                      # remove space for "..." in all menu entries
    - Restore {current_folder}
    - Restore {current_folder} to ...
- Help
    - Help
    x Config                              # Unclear term (new term introduced). 
    + Profiles config file                # formerly known as "Config"
    - Website
    - Changelog
    - FAQ
    - Ask a question
    - Report a bug
    + Diagnostics                         # New "feature" in the GUI: Show the diagnostics output in a windows
    - About
```

> "Profile" -> "Snapshots" opens the SnapshotsDialog.
> As I discussed in https://github.com/bit-team/backintime/issues/1485 that dialog can be removed in the future.
> But until then we need to place its entry point somewhere in the menus and find a label for it.
> The current label is IMHO to broad but I can't find a better solution.

I would name this "Compare snapshots" and I love the use case behind this dialog
so I would like to keep this feature (with a better UI) - even though I have never checked if it works correctly (shows the correct diff).

**Comment by aryoda** [comment]
> I removed "View" and the entry "Up"

I do not even fully understand what this "up" does. The menu item is linked to this action code:

https://github.com/bit-team/backintime/blob/3269e34a38ba456a8eb2c9558551f00009f5b8cd/qt/app.py#L1250-L1260

**Edit:** Ah, I think it "cd"'s into the parent folder in the snapshot file manager view...

**Comment by aryoda** [comment]
What I find confusing a from a user perspective that the UI of a backup software does not have a "backup" menu but only a "restore"...

How about either 
1. renaming "Profile" into "Backup" or
2. even melting the "Profile" and "Snapshot" main menus into **Backup** with these entries:
    - Manage profiles
    - Refresh snapshot list
    - Take a snapshot
    - Take a snapshot with integrity check
    - Rename snapshot
    - Compare snapshots
    - Remove snapshot
    - View snapshot log
    - View last log

**Comment by buhtz** [comment]
Thank you so much for your thoughts about this. I like your ideas. No "Backup" menu! WTF!? Never noticed. :sob: I :heart: the idea to have one! :smile: 

> introduce a "Preferences" menu entry instead to centralize more settings with "Setup language" and "Show hidden files in snapshots" (default when BiT is started)

Mhm... One new dialog just to have two settings? I'm not motivated but OK. :smile: Let's move this to another issue? Another "argument" would be that I still have a select language dialog implemented (see below). But it is also fine for me if we drop it and create an application specific preferences dialog.

About the ellipsis `...` (or `…`): What is the idea about this ellipsis behind "Preferences" and "Manage profiles"? 

About "Restore to ..." you wrote "# remove space for "..." in all menu entries".
Different from "Preferences" and "Manage profiles" I would argument it is an unfinished sentence. According to my modest Wikipedia knowledge there need to be space before the ellipsis because the ellipsis is treated as a word by its one. Words need to be separated by blanks.

The "Take a snapshot with checksum" is currently hidden in a submenu ([app.py:97](https://github.com/bit-team/backintime/blob/3269e34a38ba456a8eb2c9558551f00009f5b8cd/qt/app.py#L97)). My menubar refactoring PR #1478 is not the cause because is is still open and waiting for review. :smiley: 
![grafik](https://github.com/bit-team/backintime/assets/11861496/20e8758a-6b05-4757-86f2-af02383909d3)

About "Diagnostics" in the "Help" menu: I'm not convinced that we need this or that this might help someone. It is IMHO a lot of info most users do not understand and also don't have to understand.

# Current state of proposal
Let me summarize. This is the current proposal.

```
- Back In Time
    - Preferences...
    - Shutdown
    - Exit
- Backup
    - Manage profiles...
    - Refresh snapshot list
    - Take a snapshot
    - Take a snapshot with integrity check
    - Rename snapshot
    - Compare snapshots
    - Remove snapshot
    - View snapshot log
    - View last log   
- Restore                                 
    - Restore                             
    - Restore to ...                      
    - Restore {current_folder}            
    - Restore {current_folder} to ...
- Help                                    
    - Help                                
    + Profiles config file                
    - Website                             
    - Changelog                           
    - FAQ                                 
    - Ask a question                      
    - Report a bug                        
    + Diagnostics                         
    - About                               

```

# Little preview  about my Language Selection dialog
The intention here was to make it "visible" and totally clear to the users how much language does BIT support. You could say I want to throw it into their faces. :smile: That is why I wouldn't use a tiny boring dropdown menu. :rofl: 

Let me explain what you see in this screencast. I do start BIT and open the language dialog four times. Each time I modify the current locale first starting with Russian, following with Italian, German and `C` (no local?). The fourth with `C` contain only two options; that is a bug. Ignore it. Expect of that you can see that each language name is displayed in three different flavors: Its native name with its native letters, its names spelled using the current system language (in this example: ru, it, de) and in a tooltip its name in English including its ISO language code.
It shouldn't be a problem to use this flavors also in a dropdown menu.

![Peek 2023-07-25 20-34](https://github.com/bit-team/backintime/assets/11861496/f0a21ef1-ce96-4749-8d46-21f8d6e7f2bb)

There are more interesting technical details I will come with when maybe PR'ing. I won't blow up the current Issue.

**Comment by aryoda** [comment]
> Mhm... One new dialog just to have two settings? I'm not motivated but OK. smile Let's move this to another issue? 
> Another "argument" would be that I still have a select language dialog implemented (see below).
> But it is also fine for me if we drop it and create an application specific preferences dialog.

All fine to me, let's start small. I was just anticipating future settings and trying to avoid a menu change.
 
> About the ellipsis `...` (or `…`): What is the idea about this ellipsis behind "Preferences" and "Manage profiles"?

I use it to indicate that a non-trival window will be opened (beyond a simple message box or yes/no/cancel dialog).
Without it the menu item does directly execute an action.

> ...
> According to my modest Wikipedia knowledge there need to be space before the ellipsis because the ellipsis is treated as a word by its one. Words need to be separated by blanks.

I think you are right, syntactically a space between the last word and the omission marks ("...") may be required in English but in most menus I see it without space (compare e.g. Firefox). We could ask a native speaker, I am not sure here...

> The "Take a snapshot with checksum" is currently hidden in a submenu ([app.py:97](https://github.com/bit-team/backintime/blob/3269e34a38ba456a8eb2c9558551f00009f5b8cd/qt/app.py#L97)).

Ah, yes, there it is!

> My menubar refactoring PR #1478 is not the cause because is is still open and waiting for review.

THX for the gentle reminder ;-)))
My call of duty now until EOD tomorrow!

**Comment by aryoda** [comment]
> The "Take a snapshot with checksum" is currently hidden in a submenu ([app.py:97](https://github.com/bit-team/backintime/blob/3269e34a38ba456a8eb2c9558551f00009f5b8cd/qt/app.py#L97)).


"checksum" is an alternative method to discover file changes (according to the BiT help),
we should find a better name for the menu item than `Take a snapshot with integrity check`...
(and a clear tooltip) for that, e.g.:

    Take a snapshot (use checksum for file change detection)

and the normal "Take a snapshot" could become

    Take a snapshot (use mod-time & size for file change detection)

Proposals for shorter menu entries welcome :-)

```
> backintime backup -h
usage: backintime backup [-h] [--checksum]
options:
  -h, --help  show this help message and exit
  --checksum  force to use checksum for checking if files have been changed.
```

The `rsync` help (where the argument becomes effective) says:

> --checksum, -c           skip based on checksum, not mod-time & size

**Comment by buhtz** [comment]
Yes, I see the problem with the checksum. I don't even understand why there are two modes of change detection. But that is another topic.

- Take a snapshot (use mod-time & size for file change detection)
- Take a snapshot (use checksum for file change detection)

I assume in most cases users don't want to think about such details. They just want to "Take a snapshot" without thinking to much about it. 😄 I don't have a good idea. I would add the details in a tooltip and keep the menu entries short no matter if they describe everything or not.

Let's keep "Take a snapshot" as the default mode. And the other one "Take a snapshot (checksum mode)".
This might not be better for understanding but better for the eyes.

- Take a snapshot -> Tooltip: Use modification time & size for file change detection.
- Take a snapshot (checksum mode) -> Tooltip: Use checksum for file change detection.

**Comment by aryoda** [comment]
> Let's keep "Take a snapshot" as the default mode. And the other one "Take a snapshot (checksum mode)". This might not be better for understanding but better for the eyes.
> 
>     * Take a snapshot -> Tooltip: Use modification time & size for file change detection.
>     * Take a snapshot (checksum mode) -> Tooltip: Use checksum for file change detection.

Perfect solution, let's keep the menu entries short.
