### ISSUE TITLE
Plural forms in Slovenian and other languages

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1488]
@b100w11 [reported](https://github.com/bit-team/backintime/issues/1465#issuecomment-1655102835) at #1465.

There are some issues with the slovenian translation (and i guess also with others).
Slovenian has different plural forms based on the last number of the plural (this is probably an oversimplification and the linguists will have something to complain, but it explains the issue).
So if we take an example with "knjiga" (book) we have this forms.

> 1 knjiga
> 2 knjigi
> 3-4 knjige
> 5 knjig
> 

The same pattern repeats with "101 knjiga", "102 knjigi", ... ,  "1001 knjiga", "1002 knjigi" and so on.

The gettext solution is this
`"Plural-Forms: nplurals=4; plural=(n%100==1 ? 1 : n%100==2 ? 2 : n%100==3 || n%100==4 ? 3 : 0)\n"`

So it should work for every instance where there is a singular and plural form.
Something similar should also solve the "day(s)" problem in English and other languages.
I don't know where to incorporate this.

**Comment by buhtz** [comment]
Thanks for reporting this. I'm not well experienced with that plural forms feature. But this is a good oportunity to dive into it. :smile: Please correct me if I'm wrong here.

As I can see the "Plural-Forms" line you propose as a "solution" still exists in our latest version.

https://github.com/bit-team/backintime/blob/56ea86f99b44539b42d2788a8c33c19ce6dff29d/common/po/sl.po#L13-L14

I assume we just don't use them for specific strings. We should use `gettext.ngettext()` instead of `_()` for that strings for example here:
https://github.com/bit-team/backintime/blob/56ea86f99b44539b42d2788a8c33c19ce6dff29d/common/config.py#L117-L119

Am I right so far?

I read through the GNU gettext docu about that plural form:
 - https://www.gnu.org/software/gettext/manual/gettext.html#Plural-forms
 - https://www.gnu.org/software/gettext/manual/gettext.html#Translating-plural-forms

I couldn't find a (for me) sufficient description about the syntax in the "Plural-Forms" line in the po-files header.

**Comment by b100w11** [comment]
Yes it seems that gettext.ngettext() should do the trick.

**Comment by buhtz** [comment]
I was looking through the [BIT screenshots on Weblate](https://translate.codeberg.org/screenshots/backintime/common/) to find cases where the use of `ngettext()` is appropriate.

I do see only the Schedule drop-down menu.
![grafik](https://github.com/bit-team/backintime/assets/11861496/ebd6f960-d31b-432d-8ecc-dd35b89c623a)

Are you aware of other places or source strings? Keep in mind that there are cases where there is no other way to say "Day(s)", e.g. in a spin-box where the user can modify the value.
![grafik](https://github.com/bit-team/backintime/assets/11861496/4fe0c259-afb1-40ab-a653-2019b7dab6bd)

**Comment by buhtz** [comment]
Hello Vanja,
the "Schedule drop-down menu" now support the Plural Forms. I couldn't find another location in the UI where we could use Plural Forms. Please let me know if you find one.

You won't see the effect in Slovenian, yet. I will synchronize the translations from Weblate and the modified source strings here in the repository in the next days. After this is done you should see multiple plural forms in the weblate frontend; e.g. [here](https://translate.codeberg.org/translate/backintime/common/sl/?q=Every+%7Bn%7D+minutes&sort_by=-priority%2Cposition&checksum=).
