### ISSUE TITLE
Suboptimal find+chmod before snapshot deletion

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#151]
The full discussion starts here: https://bugs.launchpad.net/backintime/+bug/1487781/comments/7

In summary, running find+chmod to make the snapshot writable before deletion is probably suboptimal in most circumstances, at least in full rsync mode.
In fact, most of the snapshot files are likely to be already writable to the user, hence running a find on the full directory structure of the snapshot to delete is probably overkill, especially with huge snapshots.

It may be smarter to run rm -rf first, and then find+chmod only if the first rm -rf does not complete its job, then repeat rm -rf on the remainder. An option may allow the user to restore the old behaviour if he/she knows his/her files are mostly read-only.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-09T21:45:17Z
 * owner: mauromol
 * the launchpad url was https://bugs.launchpad.net/bugs/1494024

**Comment by bgurmendi** [comment]
+1

**Comment by Germar** [comment]
Oh. That's interesting! Thanks for sharing :+1:
