### ISSUE TITLE
Backup locks-up system

### ISSUE THREAD

**Issue by sackwort** [bit-team/backintime#1517]
Since moving to MX Linux three months ago, whenever Back In Time is performing a backup the system locks-up. Say a backup takes four minutes, every 20 seconds or so I can't click anything or operate the desktop, or if I'd already clicked something it doesn't take effect for ten seconds or so.

I've been using Back In Time for years on various Linus distros without this issue.

Could this be a Debian issue? If so, I'd be grateful of any tips/advice.

**Comment by emtiu** [comment]
Can you tell us what drive/filesystem/server the backups are written to/from? Your problem description sounds a bit like I/O delay, maybe from a slow external hard-drive, or a busy network connection.

**Comment by sackwort** [comment]
Thanks for your quick reply. Sorry, I should've mentioned this.  I'm using an external USB-3 HDD to backup to, which is formatted EXT4 as is my PC. The external drive is not a fast one, but I've never had this issue on any other Linux desktop.

I also should have mentioned that I don't get this issue when doing a restore.

**Comment by buhtz** [comment]
Can you please give us some more version information.

Which version of backintime (BIT) do you use currently?
How and from which source did you install it? I wasn't able to find "backintime" on MX Linux website.

Which version of BIT on which GNU Linux distribution did you use before when you got no issues?

**Comment by sackwort** [comment]
I've attached the output of "backintime --diagnostics", which is something else I forgot to post. Sorry.

I installed it on MX via the Terminal ("sudo apt install backintime-qt").

As for using it on other distros, I've always used the latest available from their repositories. I can't really remember what versions, to be honest. On occasion, I've also used the PPA.
[backintime-diagnostics.txt](https://github.com/bit-team/backintime/files/12498118/backintime-diagnostics.txt)

```
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.3.3",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.1.0-11-amd64-x86_64-with-glibc2.36",
        "system": "Linux #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08)",
        "os-release": {
            "NAME": "Debian GNU/Linux",
            "ID": "debian",
            "PRETTY_NAME": "Debian GNU/Linux 12 (bookworm)",
            "VERSION_ID": "12",
            "VERSION": "12 (bookworm)",
            "VERSION_CODENAME": "bookworm",
            "HOME_URL": "https://www.debian.org/",
            "SUPPORT_URL": "https://www.debian.org/support",
            "BUG_REPORT_URL": "https://bugs.debian.org/"
        },
        "display-system": "x11",
        "locale": "en_GB, UTF-8",
        "PATH": "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.11.2 main Mar 13 2023 12:18:29 CPython GCC 12.2.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.11",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python311.zip",
            "/usr/lib/python3.11",
            "/usr/lib/python3.11/lib-dynload",
            "/usr/local/lib/python3.11/dist-packages",
            "/usr/lib/python3/dist-packages"
        ],
        "qt": "PyQt 5.15.9 / Qt 5.15.8"
    },
    "external-programs": {
        "rsync": {
            "program": "rsync",
            "version": "3.2.7",
            "protocol": "31.0",
            "copyright": "(C) 1996-2022 by Andrew Tridgell, Wayne Davison, and others.",
            "url": "https://rsync.samba.org/",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": true,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ],
            "license": "GPLv3",
            "caveat": "rsync comes with ABSOLUTELY NO WARRANTY"
        },
        "ssh": "OpenSSH_9.2p1 Debian-2, OpenSSL 3.0.9 30 May 2023",
        "sshfs": "3.7.3",
        "encfs": "(no encfs)",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.15(1)-release (x86_64-pc-linux-gnu)"
    }
}

```

**Comment by buhtz** [comment]
I'm confused. You told you "moved to MX Linux". You do use "MX Linux"? But it seems that "MX Linux" identifies itself as "Debian 12"?

To clear up things please post the output of this commands.
- `apt-cache policy backintime-common`
- `apt-cache policy backintime-qt`

EDIT: Checking out "MX Linux" on DistroSea I can confirm that it identifies itself as "Debian" in `/etc/os-release` file.

**Comment by sackwort** [comment]
Here are the outputs:

backintime-common:
  Installed: 1.3.3-4
  Candidate: 1.3.3-4
  Version table:
 *** 1.3.3-4 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://deb.debian.org/debian bookworm/main i386 Packages
        100 /var/lib/dpkg/status

backintime-qt:
  Installed: 1.3.3-4
  Candidate: 1.3.3-4
  Version table:
 *** 1.3.3-4 500
        500 http://deb.debian.org/debian bookworm/main amd64 Packages
        500 http://deb.debian.org/debian bookworm/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by aryoda** [comment]
> Say a backup takes four minutes, every 20 seconds or so I can't click anything or operate the desktop

BiT is just running `rsync` as a background process so I would guess there is either a hardware issue (even though a restore does not show this problem) or hardware configuration issue in MX Linux (e.g. kernel configuration).

To check this could you please

- open the BiT GUI (`backintime-qt`)
- open a terminal/console
- execute the command `sudo dmesg -wT | tee log1.txt` in the terminal to observe and log all system messages
- attach your external USB drive
- start the backup process via the BiT GUI

You can now watch the system log output in the terminal...

Once the backup has finished: Press Ctrl + C in the terminal to stop the logging.

Then open the created `log1.txt` file and 
- search for terms like ERROR, WARN, FAIL, TIMEOUT and check the log for suspicious content
- search for the term `usb`
- search for all content related to the USB device (e.g. by using the assigned device name like `sdf`)

I could check the `log1.txt` for you if you want to post it here but before uploading please make sure that it does not contain any sensitive data!

PS: Also a fsck + repair (if required) of the external drive would be helpful (you can use the `disks` App for that: Select the external drive and click on `check filesystem` in the cog(wheel) menu...

**Comment by sackwort** [comment]
@aryoda Thanks for that. I've done all you suggested but don't see any issues. However, something I just noticed, whilst running these tests, is that the problem might be with Vivaldi browser. I spend all day working in the browser, so I noticed my issue there. So I think it gave me the impression that the issue was system-wide. But I just gave Firefox a go, and the issue did not appear, which made me look closer at the rest of the desktop outside of Vivaldi and that also seems to be working OK.

I'm sorry, but I may have wasted everyone's time here. I think I focused on the wrong culprit.

**Comment by aryoda** [comment]
Thanks for your feed-back! Good to know that you have found the most-likely culprit.

If you are absolutely sure you (or we) can close this issue now otherwise we could wait some days or weeks...

**Comment by sackwort** [comment]
Thank you for everyone's help. It does seem to be a Vivaldi issue, so I think it can be closed. Thanks again.

**Comment by sackwort** [comment]
Thank you for everyone's help. It does seem to be a Vivaldi issue, so I think it can be closed. Thanks again.
