### ISSUE TITLE
Clean up some old branches

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1519]
This is about infrastructure of the current repo.

I looked through the existing branches and vote to remove some of them.

 - [buhtz_config-singleton](https://github.com/bit-team/backintime/tree/buhtz_config-singleton): my own stuff, small, I save it elsewhere until I pick this topic up again
 - all `series*` branches. We don't use them. There purpose seems to be providing hotfixes etc for older versions. We discussed this elsewhere. We don't and can not support old versions on upstream. Distro maintainers should backport hotfixes if there is a need. And this version series are outdated.
 - [incorp-bit-search](https://github.com/bit-team/backintime/tree/incorp-bit-search): I checked the content. Seems to be a feature about improved search functionality. Not finished. Not much code. Nothing we can use currently or later.
 - [traack_gui_test](https://github.com/bit-team/backintime/tree/traack_gui_test): Nice example of how to use Qt to test GUI. It is nothing to merge but a nice HowTo example. I will save that piece of code elsewhere if we pick up the Gui-testing topic.
 - [traack_fix_snapshot_test](https://github.com/bit-team/backintime/tree/traack_fix_snapshot_test): Many commits but just a hand full of lines modified. Nothing that can be reused today or in the future.
 - [traack_fixup_devnull](https://github.com/bit-team/backintime/tree/traack_fixup_devnull): No modifications. This branch is just behind HEAD and 7 years old. There is nothing new/modified in it.

**Comment by buhtz** [comment]
@Germar To be sure I would like to know your experienced opinion about that issue.

**Comment by Germar** [comment]
> * all `series*` branches. We don't use them. There purpose seems to be providing hotfixes etc for older versions. 

that's correct

> We discussed this elsewhere. We don't and can not support old versions on upstream. Distro maintainers should backport hotfixes if there is a need.

they should, but they won't! So if you want to get a critical bug fixed you have to backport it and release a minor update for an old series. But there is no need to keep branches for this. You can just checkout a Tag and create a new branch if necessary.


> * [incorp-bit-search](https://github.com/bit-team/backintime/tree/incorp-bit-search): I checked the content. Seems to be a feature about improved search functionality.

Someone tried to add a search function into BiT. Could have been a powerful feature, but it was way to complex to implement. And as BiT stores all backups as plain files, every Linux tool (`find` etc.) can do the job.


> * [traack_fix_snapshot_test](https://github.com/bit-team/backintime/tree/traack_fix_snapshot_test): Many commits but just a hand full of lines modified. Nothing that can be reused today or in the future.

This was `try and error` for fixing Travis. Can get deleted

> * [traack_fixup_devnull](https://github.com/bit-team/backintime/tree/traack_fixup_devnull): No modifications. This branch is just behind HEAD and 7 years old. There is nothing new/modified in it.

I reused/merged the branche back in the days

**Comment by buhtz** [comment]
Dear Germar,
thanks for your reply.

Removed following branches
- `traack_gui_test` - Content is stored in @buhtz owns _Zettelkasten_
- `buhtz_config-singleton` - Content is stored in @buhtz owns _Zettelkasten_
- `incorp-bit-search`
- `traack_fix_snapshot_test`
- `traack_fixup_devnull`
- `series*` branches: `series1.0`, `series1.1`, `series1.2`
