### ISSUE TITLE
Unfinished Feature: Full system backup

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1526]
# Introduction
This issue should conserve the idea and the code about a feature that is not finished yet.
# Full system backup
I'm not the founder of that feature but it seems to me it is about to backup the whole filesystem (means `/`).
# The code
The code existed in the code base but was deactivated and not accessible to users.

This code add the buttons in the GUI and also hide them.
https://github.com/bit-team/backintime/blob/b578fc595dbe55288b709691eb26250bd3e2d212/qt/settingsdialog.py#L108-L116

This is the button handler.
https://github.com/bit-team/backintime/blob/b578fc595dbe55288b709691eb26250bd3e2d212/qt/settingsdialog.py#L1096-L1132

# More background
First parts of the feature where [introduced in 2016 with version 1.1.10](https://github.com/bit-team/backintime/blob/b578fc595dbe55288b709691eb26250bd3e2d212/CHANGES#L226). It was [hidden in the same year with version 1.3.0](https://github.com/bit-team/backintime/commit/dfbd4bb17c1b312a8a21c258096ddf14100e11be). The feature was also [discussed on the mailing list in 2023](https://mail.python.org/archives/list/bit-dev@python.org/message/KHZIVYZAPWEMIOZMIUQEQG3ZHR2M5QYC/).

**Comment by emtiu** [comment]
For past discussions on this subject, see #480 and #667.

**Comment by buhtz** [comment]
Resolved by PR #1527 .
