### ISSUE TITLE
Config: Add "written_with" field to record the BIT version used

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1531]
I would like to add a field `config.written_with` (or `config.bit_version`, or something else) to hold the Back In Time version that config file was written with the last time. This is more transparent then `config.version`.

I would like to get rid (on a long run) of the field `config.version` because it has not much value, blowing up the code and is not very transparent.

**Comment by aryoda** [comment]
> I would like to add a field `config.written_with` (or `config.bit_version`, or something else) to hold the Back In Time version that config file was written with the last time.

Is this an "info only" field or is it planned to use it in some (condition) logic in the code?

If we consequently stick to additive config changes and use good defaults for missing entries that did not exist in older config versions (as you did in the previous config change introducing the language code) we really don't need the `config.version` anymore (as well as no migration code from old config versions) - but only if all users have already migrated their old config versions (which is not guaranteed).

Do we have know which incompatible config changes were done in the past the **require a mandatory** config migration to the most-recent version? I guess looking into the migration code could answer this...

**Comment by buhtz** [comment]
About older config versions see #1497.

Usage plans? Good question.

My first (but thrown away) intention was to reset the manual-starts-countdown to bring up again the ApproachTranslatorsDialog on very new release. But then we would lie because the dialog says you will never see this dialog again. 😆 

No, currently I don't have a good use case for such a field. But maybe it will come up. But the developers theory always say you shouldn't write code preparing for "maybe use-cases". Mhm... Maybe we shouldn't do it.
