### ISSUE TITLE
More robust unit tests: Strict checking of output as expected causes many false positives

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1539]
## Background

Several unit tests do check the captures console output  ("actual") against the expected output.

## Impact

This is not very robust (causes many false positives due to unexpected warnings mainly caused by different external setup constellations).

## Current implementation

Currently well known "false positive" warnings are filtered out from the actual console output:

https://github.com/bit-team/backintime/blob/dev/common/test/test_backintime.py#L143-L150

## Proposals

Either

- filter out all warnings in a generic way
- or switch from console output checking to another method (eg. comparing the created snapshot instead)

## References

See also the side discussion in this PR which added another tolerated warning:

https://github.com/bit-team/backintime/pull/1537#issuecomment-1725050367

**Comment by aryoda** [comment]
@buhtz As a first step I think we should really filter out all warnings (as you have proposed).

**Comment by buhtz** [comment]
> @buhtz As a first step I think we should really filter out all warnings (as you have proposed).

OK, that is a compromise I can live with. After 1.4.1 or before?

**Comment by aryoda** [comment]
> > @buhtz As a first step I think we should really filter out all warnings (as you have proposed).
> 
> OK, that is a compromise I can live with. After 1.4.1 or before?

We could do it for v1.4.1 if another warning needed to be added to the exclusion list, otherwise directly after the v1.4.1 release.

And for refactoring and improving the unit tests I have no idea how a realistic schedule could look alike.

**Comment by buhtz** [comment]
> We could do it for v1.4.1

OK, I could take hand on that in the next two weeks.

> And for refactoring and improving the unit tests I have no idea how a realistic schedule could look alike.

This is IMHO an ongoing task. We will discover problems like this all along the road.
