### ISSUE TITLE
Finalize translation for upcoming release "1.4.1"

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1540]
Sync translations with Weblate before release 1.4.1.

**Comment by buhtz** [comment]
@aryoda Just give me a "go" and I'll do it. Will just take some minutes.

**Comment by aryoda** [comment]
I am planning to prepare release 1.4.1 this saturday night or sunday so you could update it Friday or Saturday

**Comment by buhtz** [comment]
Fixed via [5e6bfee](https://github.com/bit-team/backintime/commit/5e6bfeef144238245d8aca4039547ea5c60323c8).
