### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by neon12345** [bit-team/backintime#1542]
I like your cleanup algorithm and want to use it in a bash script. You can find my implementation of the algorithm [here](https://gist.github.com/neon12345/89968c0a71f064657b33ddd5047b3722).

I am not a lawyer and don't know whether a script using this has to be licensed as GPL now. So I thought the easiest way would be to ask for permission to license this as Apache-2 or MIT.

What do you think?

**Comment by aryoda** [comment]
@neon12345 Thanks for asking :-)

That is a great piece of work your bash script!

I think algorithms (without code) do not fall under FOSS license agreements (which cover software and its source code and documentation) so you are free to ~use~ (re-)implement and use it (even without mentioning or referring to "Back In Time").

Algorithms normally can't be licensed (in most countries) but specific implementations (= the code) are under the protection of the license.

BTW: If you really **had** to decide on a compatible license (which you don't have here IMHO) this would be more complicated, eg. there are strong [opinions](https://www.mend.io/blog/license-compatibility/) that Apache 2.0 is not compatible to our GPL v2.0.

@buhtz @emtiu Other opinions?

Disclaimer: I am not a layer.

Looking into the [GPL v2 license](https://github.com/bit-team/backintime/blob/dev/LICENSE) it mentions no algorithms but software and source code as "program":

> 0. This License applies to any program or other work which contains
> a notice placed by the copyright holder saying it may be distributed
> under the terms of this General Public License.  The "Program", below,
> refers to any such program or work, and a "work based on the Program"
> means either the Program or any derivative work under copyright law:
> that is to say, a work containing the Program or a portion of it,
> either verbatim or with modifications and/or translated into another
> language.

**Comment by buhtz** [comment]
Sorry, I don't understand what "clean up" algorithm is referring to. You mean how Back In Time does remove old snapshots? Our Smart Remove feature? :smiley: 

I also see no problem here. I'm fine with it.
But thanks  a lot for asking.

**Comment by neon12345** [comment]
> Sorry, I don't understand what "clean up" algorithm is referring to. You mean how Back In Time does remove old snapshots? Our Smart Remove feature? 😃
> 
> I also see no problem here. I'm fine with it. But thanks a lot for asking.

Yes it is the "Smart Remove" algorithm with keep X per day, week, month and one per year.

Thanks!

**Comment by emtiu** [comment]
Also not a lawyer, but my understanding is: You didn't copy any code, but re-implemented it in your own way in another language.

If that's true, the I agree with @aryoda: You're fine, and don't need to worry about licensing :) Have fun and keep up the great work!

**Comment by neon12345** [comment]
> Also not a lawyer, but my understanding is: You didn't copy any code, but re-implement it in your own way in another language.
> 
> If that's true, the I agree with @aryoda: You're fine, and don't need to worry about licensing :) Have fun and keep up the great work!

One could always argue that it is just a translation from one language into another, but at some point there is no way to re-implement an algorithm in another language then. 

Therefore I thought it is better to ask for permission, just in case, than to argue.

Thanks!

**Comment by aryoda** [comment]
> One could always argue that it is just a translation from one language into another,

GPL (v2) is a little bit unsharp and intrusive here IMHO but **formally** unless you take our code and translate line-by-line into another programming language (perhaps even automatically) it is your creative work to learn and re-implement an algorithm.

So I see no need to apply the GPL v2 license for your bash script.

BTW: It is one of the major FOSS traits to allow you to study ("S" ;-) the code (eg. to understand an algorithm).
