### ISSUE TITLE
Remove debian-folder

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1548]
The `debian` folder is used by Germar to create deb-files distributed via a PPA.

I propose to migrate that folder somewhere else. I would suggest to migrate it to Launchpad itself because Launchpad also host the related PPA.

That folder is specific to a bunch of GNU Linux distribution and therefor irrelevant for another bunch of distros (e.g. Arch based). This is no problem but natural. But it is not related to an upstream repository which should always be independent from a specific GNU Linux distribution or alternative distribution ways (Flatpak, Snap, ...). Things like this should maintained elsewhere.

Official Debian itself don't use this `debian` folder. Debian to have its [own repository](https://salsa.debian.org/jmw/pkg-backintime) maintaining such a folder.

I'll contact Germar via mail.

**Comment by Germar** [comment]
`debian` is used by `makedeb-src.sh` by me to create files for the PPA. But it is also used by `makedeb.sh`. I'm pretty sure, a lot users uses this to build their own `.deb` packages from source. I vote to keep `debian`. You can remove it from release tarball in `make-tarball.sh` so it won't disturb other distro maintainers any more

**Comment by buhtz** [comment]
Notice for my own: https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build-own-deb-file

**Comment by buhtz** [comment]
Dear Germar,

> `debian` is used by `makedeb-src.sh` by me to create files for the PPA.

I am aware of that. That is why I suggested to move the PPA related files to Launchpad or an alternative repo. IMHO an upstream repo should be kept clean and independent from distro-specific technology. PPA is specific to Debian-based distros.

> But it is also used by `makedeb.sh`. I'm pretty sure, a lot users uses this to build their own `.deb` packages from source.

I see no evidence for that. If users need the latest version of BIT they have alternative ways and can use the upstream repo (currently via `make` and with Python based build-system #1575 in the future) or the PPA. I see not much need to build their own deb file.
But even if they want to do it they just can do it without having a "debian" folder in this upstream repo. They can create that folder on their own or using the script in your separate repo I mentioned before.

Separate the "debian" folder into another repo would improve the infrastructure of the BIT project and make it easier to organize it.

**Comment by aryoda** [comment]
> Separate the "debian" folder into another repo would improve the infrastructure of the BIT project and make it easier to organize it.

I think separating the Debian packaging script from the BiT source code would be great (if communicated clearly)
since we don't loose functionality.

Still this requires that the "build Debian package" repo must know where the BiT source repo is located (cloned into).

Maintaining this repo dependency is tricky in `Git` (`Git` sub modules etc. are far from being "simple").

Perhaps a "configure" argument to specify the path to the BiT repo would be a solution...

**Comment by buhtz** [comment]
There have been no new arguments on this matter since it was last discussed here. Since this blocks the upcoming release, the active maintainer team has made a decision to move the debian folder into a new repo (e.g. `bit-team/backintime-deb`). The script in there will be updated to temorary pull in the current backintime repo before building the deb file.

**Comment by buhtz** [comment]
PR #1733 is merged and therefor the folder removed.

It is preserved in this attached archive to be re-used by PPA maintainers. It also contain an extra script to temporary clone the latest upstream release.
[backintime_debian-folder_deprecated.zip](https://github.com/user-attachments/files/16107035/backintime_debian-folder_deprecated.zip)
