### ISSUE TITLE
Unclear what enfcs.Decode does (Question to Germar)

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1559]
Dear @Germar ,
please have a look at this piece of code realated to `encfstools.Decode` class.

https://github.com/bit-team/backintime/blob/6df8c901ceecd659eaadb993103da3c6e89b4041/common/encfstools.py#L507-L510

I added some debug prints but was not able to trigger that part of the code.
- What does it do?
- Is it relevant?

The reason for my question is if I can modify the source string `_('Take snapshot')` without interfering something.

Is this somehow related to this piece of code?
https://github.com/bit-team/backintime/blob/6df8c901ceecd659eaadb993103da3c6e89b4041/common/snapshots.py#L907-L908

**Comment by Germar** [comment]
This is relevant to decode encrypted path in `takesnapshot.log`. Problem is that BiT writes translated phrase `Take snapshot` into the log for lines like:

https://github.com/bit-team/backintime/blob/6df8c901ceecd659eaadb993103da3c6e89b4041/common/encfstools.py#L526-L531

Everytime the translation changes for this phrase, this will break decoding old logs which has been created before last translation-update.

With this code I tried to fix this at least for the german translation-change. But that's a losing game anyways...

**Comment by buhtz** [comment]
[I] Take snapshot (rsync: rsync: send_files failed to open "...
        ^^^^^^^^^^^^^

Do we talk about this string?

Do I understand that correct? Someone create encfs snapshots with English language. After some snapshots the users decided to switch the UI (or OS) language to something else and do some more snapshots with the same profile.
Then it is not possible to "decode" the old snapshot logs written in English?

It seems to me that we shouldn't touch the source string `_('Take snapshot`)`. Correct? 😄

**Comment by Germar** [comment]
> Do we talk about this string?

Correct!



> Do I understand that correct? Someone create encfs snapshots with English language. After some snapshots the users decided to switch the UI (or OS) language to something else and do some more snapshots with the same profile.
> Then it is not possible to "decode" the old snapshot logs written in English?

Yes, that's correct. But not just because someone changed his locale, this will also happen if the translation of that string changes

> It seems to me that we shouldn't touch the source string `_('Take snapshot`)`. Correct? 😄

I would recommend to not change it. Also changing translation should be handled with care.

It would be better to not translate that string at all and create a regex with every possible translation for backwards compatibility

**Comment by buhtz** [comment]
> It would be better to not translate that string at all and create a regex with every possible translation for backwards compatibility

Can't we just modify the regex that way that it says "any string" at this part of the string?
Is there a risk for a false positive?

Just checking for a "pattern" (my pseudo code) like this seems to be enough

    [I] * (rsync: *

**Comment by Germar** [comment]
> Can't we just modify the regex that way that it says "any string" at this part of the string?

🤔 you're right. Sometimes I'm too complicated 🙄
The log is written by this

https://github.com/bit-team/backintime/blob/6df8c901ceecd659eaadb993103da3c6e89b4041/common/snapshots.py#L907-L908

Just make sure to use non-greedy regex

**Comment by buhtz** [comment]
Because of #1549 I wouldn't work further and wouldn't modify the regex. The code es related to EncFS.

Before modifying the regex I would need a unit test to make sure I don't accidentally modify behavior.
But this is to much work for code that will soon get replaced or removed.
