### ISSUE TITLE
rsync error when BiT ZFS volume

### ISSUE THREAD

**Issue by Anard** [bit-team/backintime#1571]
Hi.
I recently upgraded a drive from 1 HFS to 2 mirrored ZFS. BackinTime did backups from this disk without any problem. But since it's a ZFS volume, it backs-up some data from this drive before exiting with error : 

`[E] Error: rsync: [sender] write error: Broken pipe (32)`

Seems it can't rsync more than some minutes before exiting. The drive receiving BiT backups is an ext4 volume.

```$ neofetch
         -/oyddmdhs+:.                anard@imack 
     -odNMMMMMMMMNNmhy+-`             ----------- 
   -yNMMMMMMMMMMMNNNmmdhy+-           OS: Gentoo Linux x86_64 
 `omMMMMMMMMMMMMNmdmmmmddhhy/`        Host: H97M-D3H 
 omMMMMMMMMMMMNhhyyyohmdddhhhdo`      Kernel: 6.1.57-gentoo-intel 
.ydMMMMMMMMMMdhs++so/smdddhhhhdm+`    Uptime: 1 day 
 oyhdmNMMMMMMMNdyooydmddddhhhhyhNd.   Packages: 1 (dpkg), 4 (rpm), 1564 (emerge 
  :oyhhdNNMMMMMMMNNNmmdddhhhhhyymMh   Shell: bash 5.1.16 
    .:+sydNMMMMMNNNmmmdddhhhhhhmMmy   Resolution: 1920x1080 
       /mMMMMMMNNNmmmdddhhhhhmMNhs:   DE: Xfce 4.18 
    `oNMMMMMMMNNNmmmddddhhdmMNhs+`    WM: Xfwm4 
  `sNMMMMMMMMNNNmmmdddddmNMmhs/.      WM Theme: Arc-Dark 
 /NMMMMMMMMNNNNmmmdddmNMNdso:`        Theme: AD-Tangerine [GTK2] 
+MMMMMMMNNNNNmmmmdmNMNdso/-           Icons: flat-glass [GTK2], bloom [GTK3] 
yMMNNNNNNNmmmmmNNMmhs+/-`             Terminal: xfce4-terminal 
/hMMNNNNNNNNMNdhs++/-`                Terminal Font: Fantasque Sans Mono 10 
`/ohdmmddhys+++/:.`                   CPU: Intel i5-4460 (4) @ 3.400GHz 
  `-//////:--.                        GPU: Intel HD Graphics 
                                      Memory: 10220MiB / 15442MiB
```

Here is full log when taking a snapshot from command line :
```$ backintime backup

Back In Time
Version: 1.3.3

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 1 Profil principal
INFO: Call rsync to take the snapshot
notify-send Back In Time (anard) : Profil principal Error: rsync: [sender] write error: Broken pipe (32)
WARNING: Command "rsync --recursive --times --devices --specials --hard-links --human-readable -s --links --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20231115-040002-201/backup --chmod=Du+wx --exclude=/media/Saver --exclude=/home/anard/.local/share/backintime --exclude=.local/share/backintime/mnt --include=/home/anard/ --include=/home/ --include=/media/Medias/ --include=/media/ --exclude=.gvfs --exclude=.cache/* --exclude=.thumbnails* --exclude=.local/share/[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=.dropbox* --exclude=lost+found/* --exclude=.Private --exclude=/media/Medias/.* --exclude=/media/Medias/temp* --exclude=/media/Medias/Public --include=/home/anard/** --include=/media/Medias/** --exclude=* / /media/Saver/backintime/imack/anard/1/new_snapshot/backup" returns 11
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
```

**Comment by buhtz** [comment]
Dear Anard,
thanks for your report and the terminal log.

Please add the output of `backintime --diagnostics` to your report.
And please try to reproduce the problem with `backintime-qt --debug` and post this (very long) terminal output.

On a [quick & dirty search](https://bobcares.com/blog/rsync-sender-write-error-broken-pipe-32) I learned that error 32 might be caused by a full disc/volume or by a problem with the network connection. Can you check that please?
 
Thanks in advance
Christian

**Comment by aryoda** [comment]
Could you please

1. add `-vvv` to the `rsync` options (expert settings in the GUI) to make `rsync` quite verbose what it is doing. and show us relevant warnings, errors and the last view lines of output before `rsync` "dies`?
2. show us the mount options of ZFS

You could run the `rsync` command (contained in your above output snippet in the console too after creating the required `/media/Saver/backintime/imack/anard/1/new_snapshot` folder).

**Comment by Anard** [comment]
OK. As said @buhtz, it seems it was a full disk error. As my filesystem changed, it needed a large new snapshot and failed. I cleaned up older snapshots manually, then BiT could take a new snapshot without errors.
Thx for help.

**Comment by aryoda** [comment]
Thanks for reporting the reason and how to fix it!

I think we will watch further common reasons & solutions for `rsync` exit codes (now that BiT does consider them) and should provide a FAQ for this in the future.
