### ISSUE TITLE
LogViewDialog: Remove hidden feature "Exclude" because it is redundant

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1578]
Accidentally I discovered a feature in the `class LogViewDialog` that is kind of hidden. Screencasts say more then words:

![Peek 2023-12-07 16-03](https://github.com/bit-team/backintime/assets/11861496/530e2428-9727-42f3-8b5b-bc954d3769a5)

I vote to remove the "Exclude" and the "Copy" feature from this dialog because:
 - The "Copy" works out of the box in each Qt editable text element. No need to overwrite it with an own Copy implementation.
 - The "Exclude" is kind of hidden or unusual to access. I assume that there is nearly no one excluding files like this.
 - Excluding files that are currently in the snapshot can be easily done in the main window.

It will reduce code complexity.

https://github.com/bit-team/backintime/blob/59097f7a3c0ddd978e5a7a47b21909bed637a010/qt/logviewdialog.py#L167-L187

**EDIT**: Asked on [reddit](https://www.reddit.com/r/opensource/comments/18cyab2/opportunity_for_beginners_some_code_cleaning_in/?utm_source=share&utm_medium=web2x&context=3) for fresh contributors because this seems to be GOOD FIRST ISSUE.

**Comment by emtiu** [comment]
I agree with your assessment, good catch!

**Comment by aryoda** [comment]
I love "easter eggs", why remove it (does it hurt?)?

**Edit:** We could also add short label at the bottom of the dialog mentioning the context menu...

BTW: Could we use this context menu to add a context-sensitive help for the 11-char `rsync` itemize-changes option (see my FR #1579)?

**Comment by buhtz** [comment]
![image](https://github.com/bit-team/backintime/assets/11861496/d93cdcd3-4111-4de9-b473-30c9a788309c)

This is an example how I imagine a log view. With a widget like this it is more easy to use tool tips and all the other fancy and usability-improving this of a GUI. But we do not have resources to implement it and our priorities are different from heavy GUI improvements like this.

> I love "easter eggs", why remove it (does it hurt?)?
😄 Unused translatable strings (that is how I discovered this), untested code, decreased coverage, etc pp. You know me. I like it clean and clear.

> Edit: We could also add short label at the bottom of the dialog mentioning the context menu...
From an UI design perspective it feels like a workaround.

The whole feature is creepy. It has a high risk of introducing problems by the users because the user need to highlight the right text. If the text is not correct (and we do not check it) the behavior is unpredictable.

> BTW: Could we use this context menu to add a context-sensitive help for the 11-char rsync itemize-changes option (see my FR https://github.com/bit-team/backintime/issues/1579)?
Not sure but I assume it is not possible the easy way to get correct location of the mouse cursor and its corresponding text under it. It is just a multi-line text-field. It is much easier when having a nice widget like I show in the example picture.

**Comment by aryoda** [comment]
> This is an example how I imagine a log view. With a widget like this it is more easy to use tool tips and all the other fancy and usability-improving this of a GUI.

Yes, a structured grid view would be nice and also challenging since the log output is semi-structured needs robust parsing, see eg. this typical output (filter = all):

```
========== Take snapshot (profile 1): Wed Dec  6 11:48:10 2023 ==========

[I] ...
[I] Taking snapshot
[I] rsync --recursive --times --devices --specials --hard-links --human-readable -s --copy-links --acls --perms --executability --group --owner --info=progress2 --no-inc-recursive --delete --delete-excluded -v -i --out-format=BACKINTIME: %i %n%L --link-dest=../../20231206-114635-194/backup --chmod=Du+wx --exclude=/home/JaneDoe/temp/testBAK_profil1 --exclude=/home/JaneDoe/.local/share/backintime --exclude=.local/share/backintime/mnt --include=/home/JaneDoe/Documents/ --include=/home/JaneDoe/ --include=/home/ --include=/home/JaneDoe/temp/deleted_folder/ --include=/home/JaneDoe/temp/ --include=/home/JaneDoe/.mozilla/ --exclude=.gvfs --exclude=.cache/* --exclude=.thumbnails* --exclude=.local/share/[Tt]rash* --exclude=*.backup* --exclude=*~ --exclude=.dropbox* --exclude=/proc/* --exclude=/sys/* --exclude=/dev/* --exclude=/run/* --exclude=/etc/mtab --exclude=/var/cache/apt/archives/*.deb --exclude=lost+found/* --exclude=/tmp/* --exclude=/var/tmp/* --exclude=/var/backups/* --exclude=.Private --exclude=lock --include=/home/JaneDoe/Documents/** --include=/home/JaneDoe/temp/deleted_folder/** --include=/home/JaneDoe/.mozilla/** --exclude=* / /home/JaneDoe/temp/testBAK_profil1/backintime/PC1/JaneDoe/1/new_snapshot/backup

[I] Take snapshot (rsync: building file list ... done)
[I] Take snapshot (rsync: BACKINTIME: .d..tp..... ./)
[I] Take snapshot (rsync: sent 1,68M bytes  received 19 bytes  479,80K bytes/sec)
[I] Take snapshot (rsync: total size is 1,22G  speedup is 723,91)
[I] 'rsync' ended with exit code 0: Success
[I] Saving config file…
[I] Saving permissions…
```

> The whole feature is creepy. It has a high risk of introducing problems by the users because the user need to highlight the right text. If the text is not correct (and we do not check it) the behavior is unpredictable.

I fully agree with that so let's remove this functionality

**Comment by Sakh1l** [comment]
Can this #1578 be assigned to me?

**Comment by buhtz** [comment]
May I introduce @Sakh1l to the others here. He contacted me via reddit after my good-first-issue-announcment there.

> Can this #1578 be assigned to me?

Done.
Have a look at https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md and let me know if I can help you somehow. Also feel free to contact me via email.
