### ISSUE TITLE
Best practices to exclude cache folders to speed up backup

### ISSUE THREAD

**Issue by sojusnik** [bit-team/backintime#1594]
Hey folks!

Going through the log, I've noticed that a lot of small files within cache folders significantly slow down the backup process and in addition to that it actually makes no sense to back them up anyway.

So I wonder what's the best way to exclude such folders elegantly by using excluding patterns?

Adding them manually would be too cumbersome, since only some apps have only one dedicated cache folder, some have several, but in Firefox each site has its own cache folder. See several examples:

```
~/.config/BraveSoftware/Brave-Browser/ShaderCache
~/.config/BraveSoftware/Brave-Browser/GrShaderCache
~/.config/BraveSoftware/Brave-Browser/GraphiteDawnCache
~/.config/BraveSoftware/Brave-Browser/component_crx_cache
~/.config/BraveSoftware/Brave-Browser/extensions_crx_cache
~/.config/BraveSoftware/Brave-Browser/Guest Profile/GPUCache
~/.config/BraveSoftware/Brave-Browser/Default/GPUCache
~/.config/BraveSoftware/Brave-Browser/Default/DawnCache
~/.config/BraveSoftware/Brave-Browser/Default/optimization_guide_hint_cache_store
~/.config/BraveSoftware/Brave-Browser/Default/Shared Dictionary/cache
~/.config/BraveSoftware/Brave-Browser/Default/Service Worker/CacheStorage
~/.config/BraveSoftware/Brave-Browser/Default/Service Worker/ScriptCache

~/.mozilla/firefox/oyoajxci.default/storage/default/https+++www.reddit.com/cache

~/.var/app/com.discordapp.Discord/cache
~/.var/app/com.discordapp.Discord/config/discord/Cache
~/.var/app/com.discordapp.Discord/config/discord/Code Cache/
~/.var/app/com.discordapp.Discord/config/discord/DawnCache/
~/.var/app/com.discordapp.Discord/config/discord/GPUCache/

~/.var/app/org.signal.Signal/cache
~/.var/app/org.signal.Signal/config/Signal/DawnCache/index
~/.var/app/org.signal.Signal/config/Signal/GPUCache/index

~/.var/app/org.telegram.desktop/cache
~/.var/app/org.telegram.desktop/data/TelegramDesktop/tdata/user_data/media_cache
```

The solution could be added to the FAQ section, since every BiT user would profit from it.

**Comment by emtiu** [comment]
Hi, thank you for bringing this up! I noticed the same when using BackInTime myself.

I'm afraid there is no easy way that works for all users. Excluding all folders named `cache` or `Cache` is a start, but you already discovered: It's different for most applications.

So maybr the FAQ could just include a hint to check the logs and find folders to exclude, like you did.

**Comment by buhtz** [comment]
Have you seen this "Add" button and the "Exclude patttern" dialog?
![grafik](https://github.com/bit-team/backintime/assets/11861496/39dce0db-3ce7-4a11-a256-eccdd0b1ca54)

Do you have an idea or suggestion how we could improve the situation for our users?

**Comment by sojusnik** [comment]
@buhtz 

Sure, my question was more about proper exclude patterns for cache folders in general.

At the moment I decided to play it save and use the following
```
.var/app/**/[Cc]ache/*
.var/app/**/media_cache/*
.mozilla/firefox/**/cache/*
.config/BraveSoftware/Brave-Browser/Default/Service Worker/CacheStorage/*
```
for the above mentioned folders.

**Comment by aryoda** [comment]
> So maybe the FAQ could just include a hint to check the logs and find folders to exclude, like you did.

Definitely!

And we could also add two buttons to link to the FAQ for
-  "Best practices": How to check the logs to find "exclude candidates"
- `Exclude pattern syntax`: Here with "pattern" I mean the regular language syntax
- Optional "Application exclude patterns" with hints to candidate folders to exclude for common apps (possibly maintained by our community in the future)

**Comment by sojusnik** [comment]
> > So maybe the FAQ could just include a hint to check the logs and find folders to exclude, like you did.
> 
> Definitely!
> 
> And we could also add two buttons to link to the FAQ for
> 
>     * "Best practices": How to check the logs to find "exclude candidates"
> 
>     * `Exclude pattern syntax`: Here with "pattern" I mean the regular language syntax
> 
>     * Optional "Application exclude patterns" with hints to candidate folders to exclude for common apps (possibly maintained by our community in the future)

Those are excellent points!

One thing that we might have to decide is whether to recommend using `*` after `/` or not, f.i.

`.var/app/**/[Cc]ache/*`

will back up the folder itself, but not its content, while

`.var/app/**/[Cc]ache/`

won't even back up the folder.

So I wonder which approach should we recommend in the FAQ?

For rsync pattern matching rules see [here](https://download.samba.org/pub/rsync/rsync.html#PATTERN_MATCHING_RULES) or [here](https://linux.die.net/man/1/rsync).

**Comment by aryoda** [comment]
Related to #1555 (mentions how to exclude Mozilla and Discord lock files)

**Comment by buhtz** [comment]
### What need to be done?
Add an entry into the FAQ.md how to solve the problem.

**Comment by bjce** [comment]
Hello, I came across this question which I also encounters often: personally what I would like to be able to do is either to just simply copy paste a list of predefined excluded pattern or to be able to edit this feature via a command in the command line (The command line solution woudl be my prefered one by far).

Here is an example of the list patterns that so far I entered by hand for all the backup profiles I use

    /home/user01/.arduino15
    /home/user01/.cache
    /home/user01/.cargo
    /home/user01/.config
    /home/user01/.mozilla
    /home/user01/.thunderbird

**Comment by buhtz** [comment]
Hello bjce,
thanks for reaching out.

I do understand your usecase that way, that you want to bulk edit the exclude list?

We will switch to TOML format for the config file someday. Then it should be easier to modify that list because than it is just a list. See #1984 

I'll also keep this in mind when enhancing the Profile settings dialog. A bulk edit option there would also be nice.

Regards,
Christian

**Comment by bjce** [comment]
Thank you. TOML is indeed a great idea (as well as bulk edit option in the GUI)

**Comment by buhtz** [comment]
> TOML is indeed a great idea

If you are interested and have resources to contribute (without coding) you could help on that point. I am not sure how to represent all existing config variables in the TOML file, because there are several options. The primary goal is to make that file easy to understand and edit by human beings using a text editor (e.g. on a headless server using BIT without GUI).

So you might want to create an example TOML file containing four profiles, one for each flavor (local/SSH encrypted or not).

**Comment by bjce** [comment]
Great I'll be happy to do that. 2 questions there if I may: 
1. Why the choice of TOML (and not YAML): is it because it is more resilient to failure to YAML?
2. The TOML file would be a translation (maybe incomplete at the beginning at least) of the very nice config file if each backup profile (found at the root of each snapshot), alright?
What do you think?

**Comment by bjce** [comment]
Here is an example of toml config: 

```
title = "myBITconfig"

# for local backups
[profile1]
name = "my_profile_name"

[profile1.source_path]
path = "/home/user"

[profile1.source_path]
path = "/media/user/my_HD_drive"

[profile1.schedule]
custom_time = [8,12,18,23]

[profile1.snapshot.exclude]
value01=".gvfs"
value02=".cache/*"
value03=".thumbnails*"
value04=".gvfs"
value06=".cache"
value07=".cargo"
value08=".config"
value09=".mozilla"
value10=".thunderbird"

[profile1.snapshots.smart_remove]
keep_all = 2
keep_one_per_day = 7
keep_one_per_month = 21
keep_one_per_week = 3

# for remote backups
[profile2]
name = "my_profile_name2"

[profile2.source_path]
path = "/home/user"

[profile2.source_path]
path = "/media/user/my_HD_drive"

[profile2.schedule]
custom_time = [8,12,18,23]

[profile2.snapshot.exclude]
value01=".gvfs"
value02=".cache/*"
value03=".thumbnails*"
value04=".gvfs"
value06=".cache"
value07=".cargo"
value08=".config"
value09=".mozilla"
value10=".thunderbird"

[profile2.snapshots.smart_remove]
keep_all = 2
keep_one_per_day = 7
keep_one_per_month = 21
keep_one_per_week = 3

[profile2.snapshots.ssh]
host = 192.168.1.1
path = "/media/myremote_HD"
port = 22
private_key_file = "/home/user/.ssh/id_ed25519"
user = "user"

```

**Comment by buhtz** [comment]
Moved your comments to https://github.com/bit-team/backintime/issues/1984#issuecomment-3188031230
