### ISSUE TITLE
Fore-/Background color of 2nd level list header should take dark-mode into account

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1601]
BIT in light/white mode looks like this:
![grafik](https://github.com/bit-team/backintime/assets/11861496/b8f2242d-593e-4110-901f-a07fb7482671)
Screenshot was taken in Debian 12 with XFCE and Adwaita theme.

Take look to the three 2nd level headers and their color in dark mode.

![grafik](https://github.com/bit-team/backintime/assets/11861496/f886aa09-1fda-4210-8660-95560f4f123e)
Screenshot was taken in Debian 12 with XFCE and Adwaita Dark theme.

The color do not change because it is hard coded.

Todo:
 1. Doing research if Qt offers a way to create such a 2nd level header without explicit specifying its color. Does Qt offer a default color (depending on the used theme) for GUI elements like this?
 2. If the previous is not possible we should define a dark-theme color for that element and find a way to ask Qt if currently a dark- or light-mode is active.
 3. An alternative to 2 would be totally redesign this GUI elements to eliminate the need of such a 2nd level header. I don't have an idea about it yet and would recommend not to do it in the current state of our project.

These parts of the code are relevant here:

https://github.com/bit-team/backintime/blob/9618d03520b902635e8b647a0ec6efa45bd8929e/qt/app.py#L1035-L1039

https://github.com/bit-team/backintime/blob/9618d03520b902635e8b647a0ec6efa45bd8929e/qt/qttools.py#L551-L560

**Comment by buhtz** [comment]
I am not able anymore to open BIT in dark mode. The desktop and all its applications are in dark mode but BIT does ignore it and comes up bright.

I also did `sudo make uninstall && make clean && ./configure && make && sudo make install` for common and qt folder.

I am confused. Might the dark BIT (from the screenshot above) be an some weeks old installation? Did something changed in the last weeks that could be related to the used theme?

**Comment by buhtz** [comment]
```
DEBUG: [plugins/systrayiconplugin.py:76 init] System tray is available to show the BiT system tray icon
DEBUG: [common/pluginmanager.py:263 PluginManager.load] Add plugin systrayiconplugin.py
DEBUG: [qt/qttools.py:229 createQApplication] QT QPA platform plugin: xcb
DEBUG: [qt/qttools.py:230 createQApplication] QT_QPA_PLATFORMTHEME=<not set>
DEBUG: [qt/qttools.py:235 createQApplication] QT_STYLE_OVERRIDE=<not set>
DEBUG: [qt/qttools.py:238 createQApplication] QT active style: fusion
DEBUG: [qt/qttools.py:239 createQApplication] QT fallback style: 
DEBUG: [qt/qttools.py:240 createQApplication] QT supported styles: ['Windows', 'Fusion']
DEBUG: [qt/qttools.py:241 createQApplication] themeSearchPaths: ['/usr/local/share/icons', '/usr/share/icons', ':/icons']
DEBUG: [qt/qttools.py:242 createQApplication] fallbackSearchPaths: []
```
and

```
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.2-dev",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-6.1.0-13-arm64-aarch64-with-glibc2.36",
        "system": "Linux #1 SMP Debian 6.1.55-1 (2023-09-29)",
        "OS": {
            "/etc/os-release": "Debian GNU/Linux 12 (bookworm)",
            "/etc/debian_version": "12.4\n"
        },
        "display-system": "x11",
        "locale": "de_DE, UTF-8",
        "PATH": "/home/UsernameReplaced/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.local/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.11.2 main Mar 13 2023 12:18:29 CPython GCC 12.2.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.11",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/share/backintime/qt",
            "/usr/lib/python311.zip",
            "/usr/lib/python3.11",
            "/usr/lib/python3.11/lib-dynload",
            "/usr/local/lib/python3.11/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.11/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 5.15.9 / Qt 5.15.8",
            "Theme": "Tango",
            "Theme Search Paths": [
                "/usr/local/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.2.7",
            "protocol": "31.0",
            "capabilities": {
                "file_bits": 64,
                "inum_bits": 64,
                "timestamp_bits": 64,
                "long_int_bits": 64,
                "socketpairs": true,
                "symlinks": true,
                "symtimes": true,
                "hardlinks": true,
                "hardlink_specials": true,
                "hardlink_symlinks": true,
                "IPv6": true,
                "atimes": true,
                "batchfiles": true,
                "inplace": true,
                "append": true,
                "ACLs": true,
                "xattrs": true,
                "secluded_args": "optional",
                "iconv": true,
                "prealloc": true,
                "stop_at": true,
                "crtimes": false
            },
            "optimizations": {
                "SIMD_roll": false,
                "asm_roll": false,
                "openssl_crypto": true,
                "asm_MD5": false
            },
            "checksum_list": [
                "xxh128",
                "xxh3",
                "xxh64",
                "md5",
                "md4",
                "sha1",
                "none"
            ],
            "compress_list": [
                "zstd",
                "lz4",
                "zlibx",
                "zlib",
                "none"
            ],
            "daemon_auth_list": [
                "sha512",
                "sha256",
                "sha1",
                "md5",
                "md4"
            ]
        },
        "ssh": "OpenSSH_9.2p1 Debian-2+deb12u1, OpenSSL 3.0.11 19 Sep 2023",
        "sshfs": "3.7.3",
        "encfs": "(no encfs)",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.15(1)-release (aarch64-unknown-linux-gnu)"
    }
}

```

**Comment by buhtz** [comment]
The screenshot was taken on a virtual machine using Debian 12.
My described problem about opening BIT "ignoring" the dark theme is related to a second Debian 12 machine (RaspberryPi) also using XFCE.

What could be different?

**Comment by emtiu** [comment]
I see the same in my current Debian 12 testing for the dev branch (qt5). It's running 9618d03520b902635e8b647a0ec6efa45bd8929e from last week.

![Screenshot_20240113_145711](https://github.com/bit-team/backintime/assets/2159933/eff8fadb-c595-48ac-84f9-9a9e0eff7813)

**Comment by buhtz** [comment]
I checked again the VM I used. It seems to be a difference between Qt5 and Qt6. Having a dark mode desktop but using `dev` branch (which uses Qt5) the GUI is bright. Using `qt6migration` branch the GUI is dark.

**Comment by buhtz** [comment]
I found a way to use "color roles". Which one do you prefer the most? Here I use two different color roles ("PlaceholderText" and "WindowText") for the text color.

## Dark mode
![grafik](https://github.com/bit-team/backintime/assets/11861496/e08f8de8-a882-45a4-9f18-a5b09701e79e)

![grafik](https://github.com/bit-team/backintime/assets/11861496/84165b12-53db-4299-8665-172ba6f0c004)

## Light mode
![grafik](https://github.com/bit-team/backintime/assets/11861496/c3a3fe63-3762-4c44-a1c8-0d3c5c55183b)

![grafik](https://github.com/bit-team/backintime/assets/11861496/7fcb5977-4334-4291-8418-b24d8e94560f)

**Comment by emtiu** [comment]
I like the "PlaceholderText" variant a bit more, because the color is less "strong", which gives a better visual sense of sorting/overview/categorization, I think.
