### ISSUE TITLE
Exception when trying to run user callback

### ISSUE THREAD

**Issue by katian** [bit-team/backintime#1603]
Hello,

do you know how t resolve this issue ?

```
janv. 08 05:21:28 better-mantis backintime-qt.desktop[333472]: ERROR: Exception when trying to run user callback: Permission denied
janv. 08 05:21:28 better-mantis python3[333472]: backintime (katian/1): ERROR: Exception when trying to run user callback: Permission denied
```

```
$ ll /home/
total 8,0K
drwxr-xr-x  3 katian katian 4,0K juin  30  2023 appimage/
drwx------ 55 katian katian 4,0K janv.  6 17:15 katian/

```

```
$ ll .config/backintime/user-callback/user-callback.echo 
-rwxr-xr-x 1 katian katian 232 janv.  8 04:42 .config/backintime/user-callback/user-callback.echo*
```

I suppose it has to do with `drwx------` ?

:thinking:

**Comment by aryoda** [comment]
Could you please check how your file system for the home folder is mounted (`mount`).
If the mount entry for the partition of your home folder contains `noexec` you cannot execute anything
and have to change this in the mount options of `/etc/fstab`.

**Comment by aryoda** [comment]
And: Your home folder should by mounted with `drwxrwxr-x` normally but is `drwx------`.
If this was not on purpose change it back (may require to boot into a console as root)...

Did you start BiT as user or root?

And which version?

**Comment by aryoda** [comment]
@katian Ah, your `user-callback` script has the wrong name:

It is: `user-callback.echo`
It should be: `user-callback` (without any file ending)

Please rename it (or check if it already exists with the correct name and which permissions are set)...

**Comment by katian** [comment]
> Could you please check how your file system for the home folder is mounted (`mount`). If the mount entry for the partition of your home folder contains `noexec` you cannot execute anything and have to change this in the mount options of `/etc/fstab`.

here it is : `/dev/sdb on /home type ext4 (rw,relatime)`

**Comment by katian** [comment]
> And: Your home folder should by mounted with `drwxrwxr-x` normally but is `drwx------`. If this was not on purpose change it back (may require to boot into a console as root)...
> 
> Did you start BiT as user or root?
> 
> And which version?

as user
version 1.3.3

`is drwx------`
I'm running as a user, that's not enough?

**Comment by aryoda** [comment]
> /dev/sdb on /home type ext4 (rw,relatime)
>
> as user version 1.3.3
> 
> `is drwx------` I'm running as a user, that's not enough?

it should (esp. since the mount looks OK), so changing this to try it out should be the last ressort...

Could you please start the GUI with the `backintime-qt --debug` option (via terminal)
and show me the debug output line with this message (anonymize your user name):

`DEBUG: [plugins/usercallbackplugin.py:81 UserCallbackPlugin.callback] Call user-callback: /home/<user>/.config/backintime/user-callback 1 Main profile 5`

Then check if the user callback file exists with the correct name and user rights. It must be:

```
~  > ll .config/backintime/user-callback
-rwxr-xr-x 1 user user 4355 Aug 17 22:25 .config/backintime/user-callback*
```

**Comment by katian** [comment]
ok  @aryoda i was wrong, sorry, user-callback is a file not a directory it works fine now with 755 rights

**Comment by emtiu** [comment]
That's good to hear :) I'm closing the Issue, feel free to re-open this or open another one if you encounter more problems.
