### ISSUE TITLE
Manual testing of PyQt6 code

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1607]
The migration (#1301) from PyQt5 to PyQt6 is ongoing and happens in a forked repo in a separate branch: [`buhtz/backintime:qt6migration`](https://github.com/buhtz/backintime/tree/qt6migration).

Because of that migration there is a high risk of introduced bugs because of name typos causing `AttributeError`. The code is not covered by unit tests. Therefore a manual testing is needed.

Install the PyQt6 version of Back In Time (using [`buhtz/backintime:qt6migration`](https://github.com/buhtz/backintime/tree/qt6migration) or a fork from it) and try to open and use all GUI components (dialogs, buttons, OK/Yes/No/Cancel, ...) available. Report the discovered errors or fix them and open a RP.

**Comment by emtiu** [comment]
If you are familiar with vagrant (a Virtual Box frontend), feel free to use this Vagrantfile to set up a Debian 12 testing machine with @buhtz' qt6 branch with minimal interaction: [Vagrantfile.txt](https://github.com/bit-team/backintime/files/13950660/Vagrantfile.txt) (remove the `.txt` file name ending for use)

**Comment by aryoda** [comment]
I am planing to evaluate [`pytest-qt`](https://pypi.org/project/pytest-qt/) plugin for `pytest` for GUI "unit" test automation using the test cases of my the manual tests of the forked version. Perhaps it is usable (I will report).
I will start next week...

**Comment by buhtz** [comment]
This is not a veto, just my personal opinion. :smile: 
In short: I wouldn't recommend to write pytest-style tests to establish a high quality test suite.

I was also pointed to `pytest-qt` plugin. I haven't tested it yet but to my knowledge it is nothing more then a wrapper for the _QTest_ module of Qt. It does hide some code but also won't hurt if we avoid it.

I love the nice and colorful frontend of pytest and some features (re-run tests starting with the last failing). So I do use the `pytest` command. But I don't like the paradigms behind it. I always prefer `unittest` like tests and would recommend to avoid `pytest` style tests.

It is IMHO not impossible to write good quality and valuable tests with pytest but it is quit hard. PyTest animates its users to write low quality tests. They are hard to read because so much things are hidden behind "fixtures" (which is nothing more then a Python decorator) and other fancy features.
IMHO unit tests should be explicit (Python zen rule number 2 `Explicit is better than implicit.`). And there is nothing wrong with having more lines for a unit tests compared to the code that should be covered by such a tests.

Another point is that pytest-style unit tests are hard to understand and write for beginners. The hurdle is IMHO higher compared to vanilla `unittest` style tests.

Not a big deal but it would increase the number of (developing) dependencies by 2: pytest and pytest-style.

I am aware that `unittest` is less object orientated and pythonic. But I don't put much value in it because it is not productive code. Pytest is more modern and pythonic. But there are reasons why pytest still is not part of the Python in-build modules no matter that it is long living and broadly used. For me it is kind of a quality certificate if code becomes part of the official Python modules. If this does happen then I am willing to take a closer look.

As a real world example of problems with hidden test code just see our own [`generic.py`](https://github.com/bit-team/backintime/blob/dev/common/test/generic.py). A lot of classes inheriting each other and 100 of lines of code hidden. Tests like this hard to understand and to maintain. OK, it is not a perfect example because these are not unit tests but system and integration tests. :smiley: 

What I find funny (and kind of dangerous for beginners) is that the pytest folks always make advertising with the fact that you need less lines of code (compared to vanilla `unittest` module). That shouldn't be the goal. With a good IDE and good 10-finger-system it doesn't matter if you have to write 10 or 100 lines of codes. Number of lines do not correlate with quality. As I stated it is a disadvantage of pytest that you have to write less lines of code. 

Just my humble opinion. Of course I will deal with pytest-style tests if we have someone contributing a big bunch of tests. But I will be very hard while reviewing such code to keep a good maintenance-costs-and-value-ratio.

EDIT: In the past there was a branch with one Qt4-based unit tests. The branch is deleted but I saved that code in my private Zettelkasten.
