### ISSUE TITLE
Is it safe to restore a backup with an older version of the app than the backup was made with?

### ISSUE THREAD

**Issue by sojusnik** [bit-team/backintime#1608]
I've migrated from Ubuntu 23.04 to 23.10 recently and restored my backup after a fresh installation. My backup was done with **v1.4.1** (see official [PPA](https://launchpad.net/~bit-team/+archive/ubuntu/stable?field.series_filter=lunar)), but since the official PPA for 23.10 wasn't updated, I had to use the version from Ubuntu's repository, which is **v1.3.3**.

At first glance, the restoration was successful, but to be on the safe side, I want a second opinion if it is safe at all to restore a backup with an older version of the app, than the backup was made with?

I see that there's another [PPA](https://git.sdxlive.com/PPA/about), but couldn't find which version of BiT it is providing. Since this PPA also has tons of other apps, I've decided not to use it for probable compatibility issues.

**Comment by emtiu** [comment]
I don't see any reason why there would a problem with a restore between those two versions :)

**Comment by buhtz** [comment]
To my knowledge and insights I also do see no problem. It should work.

About the PPAs: They are not "official". This are external managed sources not maintained by us.
See #1609 where I fixed a link to PPA install instructions. https://git.sdxlive.com/PPA/about/#installing-the-ppa
I am not a regular PPA user so I can not be of assistance. If you still have problems with one of the PPAs or its documentation I strongly recommend to contact their maintainers to improve it.
