### ISSUE TITLE
Translation: Singular "Plural form" unused and meaningless to translators

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1610]
https://github.com/bit-team/backintime/blob/136f466a88606dfb6eaa112f29a8531511531c68/qt/settingsdialog.py#L363-L365

Results in

![grafik](https://github.com/bit-team/backintime/assets/11861496/93c4a522-4ac1-4b56-b110-af51f4c083bc)

The Singular Form doesn't make much sense from the perspective of translators.

Could be modified into.
```
config.Config._1_HOUR: ngettext( 
     'Every hour', 'Every {n} hours', 1).format(n=1),
config.Config._2_HOURS: ngettext(
     'Every {n} hour', 'Every {n} hours', 2).format(n=2),
```
Short tests seems to work.

**Comment by aryoda** [comment]
> The Singular Form doesn't make much sense from the perspective of translators.

So you propose to drop the `1` in case of singular (if I understand the `ngettext()` signature right (`gettext.ngettext(singular, plural, n)`)?

**Comment by buhtz** [comment]
Yes.
