### ISSUE TITLE
Process gets stuck at "Smart remove 6/7"

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1617]
Process gets stuck at "Smart remove 6/7".
    Sorry, I'm 74-years-old and not tech savvy.
    I am running Ubuntu 22.04 LTS.
    My Back-In-Time gets stuck at "Smart remove 6/7" - this happens even after rebooting.
    Can anyone suggest what I should do to rectify the situation.
    I should be most grateful if you could give very specific instructions as "beyond following instructions, am not tech savvy.
    Many thanks, Douglas

_Originally posted by @Douglas1949 in https://github.com/bit-team/backintime/issues/1264#issuecomment-1909640075_

**Comment by aryoda** [comment]
**Reply by @douglas1949:**

Many thanks for your reply - greatly appreciated.
Here are the answers to your questions:
1) BiT version 1.2.1
2) I am root - and using as such - BUT, still get funny message every now
and then - see one of the two screenshots attached
3) Settings: Mode: local   /    Schedule disabled   /   Target files are on
pc HDD and backed up to ExtHDD   /   See screenshots
Many thanks for your time and help - I do appreciate it.
Douglas/Duncan
[…](https://github.com/bit-team/backintime/issues/1264#)

**Comment by aryoda** [comment]
> still get funny message every now and then - see one of the two screenshots attached

I guess the screen shots in your email answer were filtered out by Github.

Could you please upload them via web browser - they seem to be very helpful for a diagnoses...

Meanwhile I am checking our source code to get ideas about what could go wrong in this part of BiT
(`Smart remove 6/7` means that seven snapshots shall be removed and BiT is just removing snapshot number 6)

_Internal note_: The code for this message in v1.2.1 is here: https://github.com/bit-team/backintime/blob/27fa0c5d4db7da3757f3f5e6afa4cc0a7214b010/common/snapshots.py#L1377-L1379

> Many thanks for your time and help - I do appreciate it.

always happy to help :smile:

**Comment by aryoda** [comment]
**Reply by @Douglas1949:**

I have uploaded the two screenshots to my evernote account and given the
following email address access to the file - you should have received the
invitation by now:
***@***.***

Once again - many thanks
Douglas/Duncan

**Comment by aryoda** [comment]
Reply by @Douglas1949:

Here are the screenshots we were talking about - attached; I hope you can see them?
![Screenshot from 2024-01-25 12-28-48_BiT_Auto-remove-tab](https://github.com/bit-team/backintime/assets/9962507/0a176741-acff-4cb6-9697-44f82e86df4f)
![Screenshot from 2024-01-25 12-30-07_BiT_write-access-issue](https://github.com/bit-team/backintime/assets/9962507/68fd3149-4089-4a66-b50e-f5ace9158752)

**Comment by aryoda** [comment]
@Douglas1949

It looks like the external HDD has problems (maybe disconnected without "unmounting" or worst case - an emerging hardware defect - let's check this as described below).

Could you please attach it and
1. Open a terminal and show me the output of `df -Th`
1. In the terminal: Show me the output of `mount` to find out if the ext. disk is mount with write access
1. do SMART data & self test and describe me the result:
    - Open the `Disks` app
    - select your external disk in the list on the left side
    - select the data partition of your backup target in the `Volumes` list at the right side
    - click on the three dots `...`
    - select `SMART Data & Self-Tests`
    - click `Start Self-test`
       Just do the normal/quick self test (**no write test**) if you should have different options.

**Comment by Douglas1949** [comment]
Many thanks - managed to fix the issue. As you suggested, it was indeed a fault with the external HDD. Fixed it by running the following:
    1. Check for Disk Errors with fsck:
        ◦ Open a terminal.
        ◦ Unmount the external HDD if it's currently mounted. You can do this with the umount command. For example:
          bashCopy code
          sudo umount /dev/sdX1
          Replace /dev/sdX1 with the actual device identifier of your external HDD partition.
        ◦ Run the fsck command to check and repair the filesystem:
          bashCopy code
          sudo fsck /dev/sdX1
          Replace /dev/sdX1 with the actual device identifier of your external HDD partition.

**Comment by buhtz** [comment]
Great to here about that happy end.

I am not deep enough into that part of BIT. But might it be somehow possible to make BIT more verbose and responsive in such a situation? Maybe an error message after a time out or a better debug message, or some other magic?

**Comment by emtiu** [comment]
Thank you for reporting back, Douglas, and glad to hear the problem has been resolved.

@buhtz: I think that file system errors will always be erratic and hard to handle gracefully. Our best guess is probably to advise users to check this possible error-source early. @aryoda has done this perfectly here :)

**Comment by aryoda** [comment]
Perhaps I should add a FAQ entry here:

https://github.com/bit-team/backintime/blob/dev/FAQ.md#common-problems-and-solutions

I am not sure what would be the best headline ("question") to find problems like this but at least we could easily reference the steps to diagnose and solve these kind of problems then in future issues...
