### ISSUE TITLE
BiT does not start after update: "No modul named 'dbus'"

### ISSUE THREAD

**Issue by diwaffm** [bit-team/backintime#1619]
I'm running BiT on an openSuse 15 box, backing up a folder to a remote computer.

This was running fine since I updated to V1.4.1-2.1 today.
If I try to start BiT on the GUI, nothing (visual) happens. If I start 
/usr/bin/backintime --debug, I get
```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 57, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

/usr/bin/backintime-qt --debug, I get
```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 36, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 57, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```

During installation of V1.4.1-2.1 all needed QT Updates were also perfomed.

**Comment by aryoda** [comment]
I think for some reason a python `dbus` package was not installed correctly (or uninstalled) or a different python version is used (OpenSuse seems to support that).

Could you please show me the output of `which python3`?

On my Thumbleweed VM I am having Python 3.11 in `/usr/bin/python3` and the required dbus packages are most probably:

- python311-dbus-python
- libQt5DBus5

Could you please check the correct installation of the above packages?

PS: Please note also that we have an open master incident on Tumbleweed with `cron` jobs as root (not related to your problem of course):

https://github.com/bit-team/backintime/issues/1592

**Comment by diwaffm** [comment]
python311-dbus-python was not installed at all (but 310...)
libQt5DBus5 is installed in version 5.15.7+kde167-2.1

after installing python311-dbus-python, 
/usr/bin/backintime --debug
results in

```
DEBUG: [common/backintime.py:589 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.4.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Hauptprofil
DEBUG: [common/tools.py:174 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/backintime.py:677 getConfig] config file: /home/diwa/.config/backintime/config
DEBUG: [common/backintime.py:678 getConfig] share path: /home/diwa/.local/share/backintime
DEBUG: [common/backintime.py:679 getConfig] profiles: 1=Hauptprofil
WARNING: [common/tools.py:2726 __logKeyringWarning] import keyring failed

```
and
/usr/bin/backintime-qt --debug
results in
```
Back In Time
Version: 1.4.1

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/configfile.py:591 Config.setCurrentProfile] Change current profile: 1=Hauptprofil
DEBUG: [common/tools.py:174 initiate_translation] No language code. Use systems current locale.
DEBUG: [common/backintime.py:677 getConfig] config file: /home/diwa/.config/backintime/config
DEBUG: [common/backintime.py:678 getConfig] share path: /home/diwa/.local/share/backintime
DEBUG: [common/backintime.py:679 getConfig] profiles: 1=Hauptprofil
DEBUG: [common/pluginmanager.py:245 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:262 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/tools.py:719 is_Qt5_working] Qt5 probing result: exit code -11
DEBUG: [common/tools.py:722 is_Qt5_working] Qt5 probing stdout: 
DEBUG: [common/tools.py:723 is_Qt5_working] Qt5 probing errout: QSettings::value: Empty key passed
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen
failed to load driver: zink

DEBUG: [plugins/systrayiconplugin.py:82 init] No system tray available to show the BiT system tray icon
MESA: error: ZINK: vkCreateInstance failed (VK_ERROR_INCOMPATIBLE_DRIVER)
glx: failed to create drisw screen
failed to load driver: zink

```

Thanks
Dirk

**Comment by aryoda** [comment]
> This was running fine since I updated to V1.4.1-2.1 today.
> [...]
> after installing python311-dbus-python,

It looks like you installed BiT via a distro package and the required dependencies should be installed automatically to make BiT work.

Installing a newer python3 version may require to also manually install or update the required python packages.

Since we (the BiT developer team) do not maintain distro packages I can't tell you for sure the names of the required packages but you can find list of Debian package names in our [build & install from source](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build--install) documentation.

In my TumbleWeed VM these package versions are installed and BiT does work. Perhaps you can find and install the missing ones:

![image](https://github.com/bit-team/backintime/assets/11374410/ad3df235-68ce-4250-a2a8-2bcd32ae2e14)

![image](https://github.com/bit-team/backintime/assets/11374410/d65ad414-03a4-4db8-aab2-bc5335cd25ba)

**Comment by buhtz** [comment]
Maybe it would help to open a ticket at opensuse because it is a packaging issue. We can not help here a lot.

**Comment by diwaffm** [comment]
Ok, thank you anyway.
Now I know, where I have to look at.

**Comment by buhtz** [comment]
Please link the ticket from OpenSuse here and let us know if there is a solution.
Maybe we can somehow improve our communication with the distro maintainers.

**Comment by aryoda** [comment]
> Please link the ticket from OpenSuse here and let us know if there is a solution.

And please link our issue here in the ticket of OpenSuse...

> Maybe we can somehow improve our communication with the distro maintainers.

@buhtz Communication is already excellent, the distro maintainer is [Tejas Guruswamy](https://github.com/tguruswamy) and has opened #1574 as well as has sent us PR #1602  :smile:

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
