### ISSUE TITLE
"Highly recommended" exclusion patterns in "Manage profiles" GUI dialog should show only missing patterns

### ISSUE THREAD

**Issue by aryoda** [bit-team/backintime#1620]
## Current status

`rsync` and therefor BiT do allow to specify "exclude file patterns" for files that shall not be `rsync`ed:

Currently the GUI always shows all recommended (= default) exclusion file patterns:

![image](https://github.com/bit-team/backintime/assets/11374410/902da6fe-7cae-41b9-abab-533665b91d2d)

## Feature request

It would be more helpful to show only those default exclusions patterns as "highly recommended" that are not already contained in the actual exclusion list.

## Relevant code

https://github.com/bit-team/backintime/blob/d583cf8a4b7de4271f897f07a94d0fbe07f9caff/qt/settingsdialog.py#L556-L561

https://github.com/bit-team/backintime/blob/d583cf8a4b7de4271f897f07a94d0fbe07f9caff/common/config.py#L98-L119

## Related to

- #1583
- #1618
- #1594
- #1382
- #1215
- #972

**Comment by Prakul95** [comment]
https://github.com/bit-team/backintime/pull/1629 pull request for dev branch.
