### ISSUE TITLE
Build: Investigate CI problems on "ppc64le" machine

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1647]
I am not sure what the problem is. I need to investigate it.

See https://app.travis-ci.com/github/bit-team/backintime/jobs/617987486

The CI should fail (because of a known pylint error) but it does not.

It seems that the pylint test is never executed. It also seems that there might be a problem with the "python3" interpreter.

Happens only on that machine. The same commit show the expected fail on AMD64.

**Comment by buhtz** [comment]
Stupid me. The behavior is intended.
Qt-related tests are not run on "ppc64le" machines.
https://github.com/bit-team/backintime/blob/6eb26bebdfb0a199194dcd5e21e124965aeeb7d5/.travis.yml#L81

Reason is there is a known problem installing PyQt5 in virtual environments on that machines. For that architecture there is no PyQt5 build available on PyPi.

**Comment by aryoda** [comment]
Is `PyQt6` supported then on `ppc64le` dockers?

**Comment by buhtz** [comment]
> Is `PyQt6` supported then on `ppc64le` dockers?

Not sure if TravisCI use docker or something else. The problem is based on a complex combination of several Issues.

1. Ubuntu is used on TravisCI.
2. Ubuntu does offer PyQt in its official Ubuntu repositories, installable via `apt install`.
3. TravisCI run every Python version in a virtual environment.
4. Python in a virtual environment (by default) do not have access to the Ubuntu Python packages. That means `python3-pyqt6` can be installed but is not visible to the Python interpreter used by TravisCI in the virtuel environment.
5. For such cases Python usually offers the `--system-site-packages` option to make global Python packages installed by the OS available to the virtuel environment.
6. But TravisCI restrict that `--system-site-packages` switch to the systems "default Python interpreter" (see [Travis docs](https://docs.travis-ci.com/user/languages/python#travis-ci-uses-isolated-virtualenvs)).
7. Yes, the used Ubuntu version do offer Python 3.8. But especially on the ppc64le architecture TravisCI somehow decided to use an extern (sideloaded) Python interpreter.
8. Because the Ubuntu ppc64le machine do not use Ubuntus own (global) Python interpreter the use of `--system-site-packages` is not possible.
9. The alternative usually is to install packages from PyPi via `pip`.
10. But PyPi doesn't offer a `PyQt*` build for ppc64le architecture.

It might be possible to hack around on TravisCI, deactivating the virtual environment etc pp. But I don't want to start with that. This one machine is not so important. The chance to miss errors especially for this architecture and Python version is extremely low. I also doubt that there are much users out there using BIT on ppc64le. This are people using Ubuntu (or GNU Linux) on an Apple device, right?

**EDIT**: Without TravisCI we could install Ubuntu on a ppc64le machine and run the tests then. This should be possible. I once have created a qemu machine with ppc64le architecture. It took me hours to boot and install some things. It is extreme slow but also my own PC is not the fastest.
