### ISSUE TITLE
Unit test: User callback

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1648]
This issue need to be solved before working on PR #1269 .

To my knowledge user-callback behavior is not covered by any of the current tests. Of course the code is executed in some tests (and covered in a technical way) but not tested.

IMHO the **behavior to test** would be if the callback reasons/steps are called on the right position on the timeline after/before some other specific steps of the taking a snapshot process.

*Problem*: My assumption is that this is nearly impossible in the current state of the productive code. The code is not isolated enough. And especially in testing user-callback behavior to many elements of code are involved. I see no way doing this with "unit tests" or "integration tests" in the near time.

*Solution*: A "dirty" approach could be to do a full snapshot run in an "system test" and then parsing the log output for the expected messages (or their patterns) and if they appear in the correct order. We still have tests doing full backups. They do use some helper code from `test/generic.py`.

**Comment by aryoda** [comment]
I think I (or someone else) could solve most of the testing requirements via an instrumented user-callback script that produces the required output (while checking if the call corresponds to current snapshot or mount state).

A good basis for that is my "logging-only" [user-callback script](https://github.com/bit-team/user-callback/blob/master/user-callback.diagnostics)...

**Comment by buhtz** [comment]
Thanks for that script. I am working on it....

**Comment by buhtz** [comment]
I never really used user-callback. So I played around. To me this is seems to be a valid and expected combination and order of user-callback "reasons" for a local snapshot profile. Do you agree? Is this the order of Reason I should test for?

```
INFO: user-callback returned 'Profile: "Main profile" (1)  Reason: 7'
INFO: user-callback returned 'Profile: "Main profile" (1)  Reason: 1'
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: user-callback returned 'Profile: "Main profile" (1)  Reason: 3
sys.argv[4:]=['20240224-222022-131', '/tmp/bit.oz71hdju/snapshotdestination/backintime/test-host/test-user/1/20240224-222022-131']'
INFO: user-callback returned 'Profile: "Main profile" (1)  Reason: 2'
INFO: user-callback returned 'Profile: "Main profile" (1)  Reason: 8'
```

- 7 - "Mount drives"
- 1 - "Backup process begins"
- 3 - "A new snapshot was taken" incl. id and path of the snapshot
- 2 - "Backup process ends"
- 8 - "Unmount the drives"

**Comment by buhtz** [comment]
Microsoft GitHub closed the accidentally closed the issue. Feel free to reopen if you think there should be more user callback related tests.
