### ISSUE TITLE
Build error AUR package backintime-git "install: cannot change permissions of ‘/usr/share/metainfo’: No such file or directory"

### ISSUE THREAD

**Issue by willemw12** [bit-team/backintime#1654]
https://github.com/bit-team/backintime/pull/1642 causes a build error of the Arch AUR backintime-git package:

     "install: cannot change permissions of ‘/usr/share/metainfo’: No such file or directory"

The AUR package build file can be found here: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=backintime-git. Temporarily comment out the check() function if some tests fail,

The problem and the solution are already mentioned here https://github.com/bit-team/backintime/pull/1642#issuecomment-1961257140:

    in qt/configure, change:

    printf "\tinstall -d /usr/share/metainfo\n" >> ${MAKEFILE}

    to:

    addInstallDir "/share/metainfo"

**Comment by willemw12** [comment]
That build error happens when building in a [clean chroot environment.](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot)

When building and installing normally, the error is:
    
    (38/38) checking for file conflicts                                                                                                    [##############################################################################] 100%
    error: failed to commit transaction (conflicting files)
    backintime-git: /usr/share/metainfo exists in filesystem
    Errors occurred, no packages were upgraded.

**Comment by buhtz** [comment]
Now I understood what `addInstallDir` is for. 🤣 
I'll prepare a PR.
