### ISSUE TITLE
Compare snapshots: Don't use "false" as fallback diff command

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1662]
https://github.com/bit-team/backintime/blob/ed282ad53a3bbbfbab079ee71ea8b13fb17703c1/qt/snapshotsdialog.py#L34-L42

Based on [report on bit-dev mailing list](https://mail.python.org/archives/list/bit-dev@python.org/message/NR4VSKGWOHB6NF4DINZZGI42I5SBNVXR/).

### Problem
An extern application is used to compare snapshots. If `meld` and `kompare` as such tools are not installed BIT is falling back to `false`. Be aware that `false` is not `False` and that `false` is a valid command in a *nix shell (see `$ manpage false`). This makes no sense from users perspective. The "Compare" button just does nothing in this case. No reaction. No response to the user.

BIT doesn't check for `false` but just checks for availability of the configured diff command.
https://github.com/bit-team/backintime/blob/ed282ad53a3bbbfbab079ee71ea8b13fb17703c1/qt/snapshotsdialog.py#L336-L340

![image](https://github.com/bit-team/backintime/assets/11861496/ebdb5199-d5ea-4f28-a86d-4d72f8d3fb36)

### Solution
The diff command should be empty (or None) if meld or kompare are not available. And the Compare button should check for emptiness.
Also the error message could be improved. A simple "Command not found" is not user friendly and to technical.

**Comment by stcksmsh** [comment]
```
if tools.checkCommand('meld'):
    DIFF_CMD = 'meld'
    DIFF_PARAMS = '%1 %2'
elif tools.checkCommand('kompare'):
    DIFF_CMD = 'kompare'
    DIFF_PARAMS = '%1 %2'
else:
    DIFF_CMD = ''
    DIFF_PARAMS = '%1 %2'
```
```
        if not diffCmd:
            messagebox.critical(
                self, ('No diff command found. Please install meld or kompare.'))
            return
```
This is my idea of the fix, but I have a question (which probably does not make too much sense):
Based on the mailing list report we can see users want to be able to use non gui compare tools, an example of `diff` is given in the email. Right now if someone were to set the command to `diff` and the parameters to `-r %1 %2` which should be a valid diff command, it will simply do nothing. Maybe just show a `messagebox.info` with the output (if there is anything to show, as kompare and meld do not seem to 'give' anything to stdout)?

**Comment by buhtz** [comment]
Hello Kosta,
thanks for jumping in here.

Your approach seems correct to me. I would suggest a slightly refactoring like this:

```
if tools.checkCommand('meld'):
    DIFF_CMD = 'meld'
elif tools.checkCommand('kompare'):
    DIFF_CMD = 'kompare'
else:
    DIFF_CMD = None

if DIFF_CMD is None:
    DIFF_PARAMS = None
else:
    DIFF_PARAMS = '%1 %2'

```

And the dialog:

        if diffCmd is None:
            messagebox.critical(
                self, ('No tool found to compare snapshots. It is suggested to install "meld", "kompare", or a similar tool.'))
            return

> Based on the mailing list report we can see users want to be able to use non gui compare tools
> [..]
> if someone were to set the command to `diff` and the parameters to `-r %1 %2` which should be a valid diff command, it will simply do nothing.

I would treat this as an edge case. The users are responsible for this them self. When they want a terminal based diff output they have to use the correct commands (some bash/sh, termemu magic). Just ignore this case.

> Maybe just show a `messagebox.info` with the output (if there is anything to show, as kompare and meld do not seem to 'give' anything to stdout)?

We **could** check the output on stdout when using subprocess.run(). But this is to much code and complexity for an edge case (1 user in 100.000 maybe). My intention is to simplify the the old BIT code where ever it is possible to improve its maintainablity. 😄
