### ISSUE TITLE
Subsequently change folder names in snapshots from back-in-time 

### ISSUE THREAD

**Issue by ftomasch** [bit-team/backintime#1668]
Hello!
Is it possible to edit folder names in a directory structure automatically created by Back-in-Time?

I use three internal hard drives for my digital photos. A hard drive has two partitions: one for the system and one for my work files.
I installed Kubuntu 23.10 as the operating system.
After my initial installation, the three hard drives were mounted in the “mnt” folder.
Now I set up Kubuntu a second time and made sure that the hard drives were mounted in the designated “/media/[user]/” folder.
Now my problem:
Since the backup media path has changed, I cannot add more backups to the old snapshots.

Is there a way to adapt the backups to the new paths or do the backups have to be created from scratch?

I tried changing the three names to “Back-in-time”, “Discover” and “Using the Console”. - unfortunately in vain. The backup media is “read-only”

I installed Back-in-Time (root) with Discover, version 1.3.3-4, Distributor: Ubuntu
Here are the backintime --diagnostics:
```
{
“backintime”: {
“name”: “Back in time”,
“Version”: “1.3.3”,
“latest-config-version”: 6,
"local-config-file": "/home/UsernameReplaced/.config/backintime/config",
“local-config-file-found”: true,
"global-config-file": "/etc/backintime/config",
“global-config-file-found”: false,
"started-from": "/usr/share/backintime/common",
“running-as-root”: false,
"user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
“keyring-supported”: true
},
“host setup”: {
"Platform": "Linux-6.5.0-25-generic-x86_64-with-glibc2.38",
"system": "Linux #25-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb 7 14:58:39 UTC 2024",
“os-release”: {
“NAME”: “Ubuntu”,
"ID": "ubuntu",
“PRETTY_NAME”: “Ubuntu 23.10”,
“VERSION_ID”: “23.10”,
“VERSION”: “23.10 (Mantic Minotaur)”,
“VERSION_CODENAME”: “mantic”,
“ID_LIKE”: “debian”,
"HOME_URL": "https://www.ubuntu.com/",
"SUPPORT_URL": "https://help.ubuntu.com/",
"BUG_REPORT_URL": "https://bugs.launchpad.net/ubuntu/",
"PRIVACY_POLICY_URL": "https://www.ubuntu.com/legal/terms-and-policies/privacy-policy",
“UBUNTU_CODENAME”: “mantic”,
“LOGO”: “ubuntu-logo”
},
“display system”: “x11”,
“locale”: “de_DE, UTF-8”,
"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/ Container",
“RSYNC_OLD_ARGS”: “(not set)”,
“RSYNC_PROTECT_ARGS”: “(not set)”
},
“python setup”: {
"python": "3.11.6 main Oct 8, 2023 05:06:43 CPython GCC 13.2.0",
"python-executable": "/usr/bin/python3",
“python-executable-symlink”: true,
"python-executable-resolved": "/usr/bin/python3.11",
“sys.path”: [
“/usr/share/backintime/qt/plugins”,
“/usr/share/backintime/common/plugins”,
"/usr/share/backintime/plugins",
“/usr/share/backintime/common”,
"/usr/lib/python311.zip",
“/usr/lib/python3.11”,
“/usr/lib/python3.11/lib-dynload”,
“/usr/local/lib/python3.11/dist-packages”,
“/usr/lib/python3/dist-packages”
],
“qt”: “PyQt 5.15.9 / Qt 5.15.10”
},
“external programs”: {
“rsync”: {
“program”: “rsync”,
"Version": "3.2.7",
“Protocol”: “31.0”,
“copyright”: “(C) 1996-2022 by Andrew Tridgell, Wayne Davison and others.”,
“url”: “https://rsync.samba.org/”,
"Skills": {
“file_bits”: 64,
"inum_bits": 64,
“timestamp_bits”: 64,
“long_int_bits”: 64,
“Socket pairs”: true,
“symlinks”: true,
“symtimes”: true,
“Hard links”: true,
“hardlink_specials”: true,
“hardlink_symlinks”: true,
“IPv6”: true,
“atimes”: true,
“batch files”: true,
“inplace”: true,
"append": true,
“ACLs”: true,
“xattrs”: true,
"secluded_args": "optional",
“iconv”: true,
“prealloc”: true,
“stop_at”: true,
“crtimes”: false
},
“Optimizations”: {
“SIMD_roll”: true,
“asm_roll”: false,
“openssl_crypto”: true,
“asm_MD5”: false
},
“checksum_list”: [
“xxh128”,
“xxh3”,
“xxh64”,
“md5”,
“md4”,
“sha1”,
"none"
],
“compress_list”: [
“zstd”,
“lz4”,
“zlibx”,
“zlib”,
"none"
],
“daemon_auth_list”: [
"sha512",
"sha256",
“sha1”,
“md5”,
“md4”
],
“license”: “GPLv3”,
“caveat”: “rsync includes ABSOLUTELY NO WARRANTY”
},
"ssh": "OpenSSH_9.3p1 Ubuntu-1ubuntu3.2, OpenSSL 3.0.10 August 1, 2023",
"sshfs": "3.7.3",
“encfs”: “(no encfs)”,
"Shell": "/bin/bash",
“Shell version”: “GNU Bash, Version 5.2.15(1)-Release (x86_64-pc-linux-gnu)”
}
}
```

**Comment by buhtz** [comment]
Dear ftomasch,
thank your for your report and question.

I do not understand all details you gave here but I assume you want to move your backup folder? We do have a [FAQ](https://github.com/bit-team/backintime/blob/dev/FAQ.md) and there have a look at the entry about [How to move snapshots to a new hard-drive?](https://github.com/bit-team/backintime/blob/dev/FAQ.md#how-to-move-snapshots-to-a-new-hard-drive).

But please **be careful**. You do this on your own risk.

Please report back how it worked. And maybe you want to improve the related FAQ entry to make it easier to understand for other users.

**Comment by ftomasch** [comment]
Dear butz!
thank you for the quick response!

Unfortunately the FAQ is not my problem.
I changed the path of the original folders. From "mnt" in the
"media/landsby".
Everything else stayed the same!
I would also like to make this change to the source path for the old
snapshots.

Here is a sketch:


Best regards

**Comment by buhtz** [comment]
I can not see your "sketch".

And sorry, again I don't understand you. "change to the source path of rthe old snapshots" makes no sense to me. What is a source path for you? What is a "snapshot" for your?

**Comment by ftomasch** [comment]
Sorry!
Unfortunately I only have the German language version.
By “snapshot” we mean the backup files.

So that you receive the attached file, I converted it to JPG and
enclosed it in this email.
It's called "Backintime.jpg"

I am also attaching a second image file called “Snapshot.jpg”. In it I
marked the “Snapshot” menus.
I hope you receive the files now.

To be on the safe side, here is a link to Google Drive:
https://drive.google.com/file/d/1wI3EGJTrkzah22GRIPEUIgkoeRdsolGJ/view?usp=drive_link
 From there you can download an archive with the two files

Best regards

Backintime:

Schnappschuss:

Am 14.03.24 um 14:59 schrieb buhtz:

**Comment by buhtz** [comment]
> Sorry! Unfortunately I only have the German language version.

Na prima, dann lass uns doch ausnahmsweise ins Deutsch wechseln. Vielleicht verstehe ich dann besser, worum es hier geht. Die anderen Maintainer im Team verstehen auch ganz gut Deutsch. 🤣 

Ich würde vorschlagen du nutzt nicht das E-Mail Interface von GitHub, sondern begibst dich direkt auf GitHub.com . Hier kannst du problemlos Bilder per Copy & Paste einfügen.

Deinen Google Drive Link kann ich auch nicht öffnen, weil ich keinen Account dort habe.

**Comment by ftomasch** [comment]
Hallo!
Vorgeschichte:
Im Laufe der Zeit habe ich viele digitale Bilder erstellt. Die Sammlung wurde immer größer. 
So hat es sich ergeben, dass ich die Bilder auf drei Festplatten aufgeteilt habe. Eine Festplatte hat zwei Partitionen um das System von meinen Dateien zu trennen. 
Ab und zu war es notwendig die Datenstruktur der Sammlung den Erfordernissen anzupassen. Ich habe also Ordner verschoben bzw. umbenannt.  
Ein komplettes neues Backup dauert recht lang. Daher bin ich auf die Idee gekommen, die Änderungen auf den Festplatten und dem Backupmedium parallel durchzuführen.

Aktuell:
Seit Kurzem bin ich auf Kubuntu umgestiegen. Die Vorteile sind einfach gigantisch!
"Back-in time" hat den großen Vorteil, dass alte Versionen mit gespeichert werden. Bei mir sind das hauptsächlich XMP-Dateien.

Zuerst hatte ich die Festplatten das Verzeichnis "mnt" mit Kubuntu verbunden. Dieser Weg ist speziell für Wechellaufwerke vorgesehen. In der Praxis musste ich ständig die Festplatten neu mounten. 
Die ersten Sicherungen habe ich über diesen Weg erstellt.

Inzwischen hänge ich die Platten über einen anderen Weg ein, über "media/Landsby". So sind sie dauerhaft mit dem Betriebssystem verbunden.

Das Problem:
Bei einem neuen Backup erkennt "Backintime" den ursprünglichen Pfad (mnt) mit allen Dateien perfekt. 
Aber: Da ich den Einhängepunkt verhändert habe, **erkennt "Backintime" den neuen Pfad der Ursprungsdateien (media/landsby) nicht.** 
Da unter "mnt" weder Ordner noch Dateien zu finden sind, kann Backintime keine Daten sichern.
Es sei denn ich richte ein völlig neues Backup ein

Daher wollte ich, nach alter Gewohnheit, die Pfadangaben auf dem Sicherungsmedium ändern,
Dann die Pfadangaben in Backintime/Hauptmenu/Verknüpfungen
                                           sowie Backintime/Konfiguration/Include
 Leider ohne Erfolg                                          

Ist es möglich die alte Sicherung mit den Daten des neuen Pfades zusammenzubringen?


![Backintime - alter und neuer Pfad](https://github.com/bit-team/backintime/assets/34056100/44f6d4a9-f2c5-448e-9052-520ef9c2b54f)

**Comment by buhtz** [comment]
Ah, dein Screenshot hilft. Der Screenshot zeigt 6 (nicht 3) Sicherungsordner.
Für Back In Time (BIT) sind `/mnt/Projects` und `/media/landsby/Projects` zwei unterschiedliche und eigenständige Sicherungsordner.

Auf Seiten von BIT kannst du da nichts ändern. Der von mir verlinkten FAQ Eintrag ist vermutlich nicht hilfreich, weil er nur das Verschieben des Snapshot-Ordners (also des Backup-Ziels) beschreibt. Dir geht es aber darum, dass sich die Backup-Quelle (also die Sicherungsordner) geändert haben. Richtig?

Da sehe ich keine Möglichkeit, dass mit adäquaten Mitteln umzusetzen. Das wäre zu hacky, erfordert viel Wissen über die interne Arbeitsweise von BIT und rsyncs hardlink Funktion und hat auch dann keine guten Aussichten auf Erfolg.

Du könntest tricksen und ein bind-mount anlegen. Das heißt, wenn die echten Dateien jetzt in `/media/landsby/Projects` liegen, musst du diesen Ordner nach `/mnt/Current` mounten. Dann muss in BIT, der Sicherungsordner aber wieder nach `/mnt` zeigen. Jedoch hast du das ja schon geändert, weshalb ich nicht denke, dass man das zurückdrehen kann.

Ich sehe keine wirkliche Lösung. Du wirst das Backup mit den neuen Sicherungsordnern, wohl frisch anlegen müssen, so dass alles initial komplett kopiert wird und auch entsprechend Speicher verbraucht.

Evtl. haben meine Team-Kollegen noch eine Idee?

**Comment by ftomasch** [comment]
OK, alles klar!
Das ist gut zu wissen für die Zukunft
Ich denke, das ich möglicherweise Backups zu wenig Zeit gewidmet habe. 
In der analogen Welt ist ein Backup um einiges komplexer, da gibt es sogar den Beruf "Achivar*in"

Noch eine allerletzte Frage:
Wie verständlich war eigendlich mein zusammengestöpseltes Englisch? Ich meine nicht den Inhalt, sondern die Grammatik und Wortwahl.
Es ist eine recht außergewöhnliche Konstallation, mit einem Deutschsprachigen in Englisch zu kommunizieren ....

Vielen vielen Dank für den absolut professionellen Support!!!!

**Comment by buhtz** [comment]
> Noch eine allerletzte Frage: Wie verständlich war eigendlich mein zusammengestöpseltes Englisch? Ich meine nicht den Inhalt, sondern die Grammatik und Wortwahl.

Mein Englisch ist auch nicht das Gelbe vom Ei. Ich habe deinen Inhalt wirklich nicht verstanden, weil dein Wording nicht passte. Du hast einige Begriffe im Kontext von BIT nicht passend genutzt bzw. nicht klar genug formuliert. Das ist aber mehr ein Problem der Fachsprache im Kontext von BIT und nicht von Englisch. Die Grammatik an sich ergab schon Sinn.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen if the problem still exists. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
Christian on behalf of the _Back In Time_ team
