### ISSUE TITLE
Toolbar changes don't survive a GUI restart

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#167]
Right click on the GUI toolbar. Select Orientation>Left.
Close the GUI with the Exit button.
Restart the GUI, and the toolbar is on the top again.

Locking the toolbar has no effect on this behaviour.

Version 1.0
Using KDE 4.3.2 (KDE 4.3.2)

---

Imported from Launchpad using lp2gh.
- date created: 2010-09-21T10:57:38Z
- owner: dave-morriss
- the launchpad url was https://bugs.launchpad.net/bugs/644273

**Comment by Germar** [comment]
(by danleweb)
You are right, this behaviour was never developed.

**Comment by emtiu** [comment]
As of backintime 1.3.2, the option to rotate the toolbar no longer exists. It _did_ in the past, as verified for backintime 1.0.36 on KDE4 (in an old VM). The change probably came about when migrating to Qt5, also causing #1105.

Closing this as overcome by events.
