### ISSUE TITLE
Cannot restore config from clean install of latest git version of backintime-qt

### ISSUE THREAD

**Issue by hshl2** [bit-team/backintime#1680]
<details>
<summary>output of the console command backintime --diagnostics</summary>

> {
>     "backintime": {
>         "name": "Back In Time",
>         "version": "1.4.4-dev.d33f35e1",
>         "running-as-root": false,
>         "latest-config-version": 6,
>         "local-config-file": "/root/.config/backintime/config",
>         "local-config-file-found": false,
>         "global-config-file": "/etc/backintime/config",
>         "global-config-file-found": false,
>         "started-from": "/usr/share/backintime/common",
>         "user-callback": "/root/.config/backintime/user-callback",
>         "keyring-supported": false
>     },
>     "host-setup": {
>         "OS": {
>             "/etc/os-release": "Arch Linux",
>             "/etc/arch-release": "",
>             "/etc/lsb-release": "DISTRIB_ID=\"Arch\"\nDISTRIB_RELEASE=\"rolling\"\nDISTRIB_DESCRIPTION=\"Arch Linux\"\n"
>         },
>         "platform": "Linux-6.8.4-zen1-1-zen-x86_64-with-glibc2.39",
>         "system": "Linux #1 ZEN SMP PREEMPT_DYNAMIC Fri, 05 Apr 2024 00:14:08 +0000",
>         "display-system": "($XDG_SESSION_TYPE not set)",
>         "locale": "en_US, UTF-8",
>         "PATH": "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl",
>         "RSYNC_OLD_ARGS": "(not set)",
>         "RSYNC_PROTECT_ARGS": "(not set)"
>     },
>     "python-setup": {
>         "python": "3.11.8 main Feb 12 2024 14:50:05 CPython GCC 13.2.1 20230801",
>         "python-executable": "/usr/bin/python3",
>         "python-executable-symlink": true,
>         "python-executable-resolved": "/usr/bin/python3.11",
>         "sys.path": [
>             "/usr/share/backintime/qt/plugins",
>             "/usr/share/backintime/common/plugins",
>             "/usr/share/backintime/plugins",
>             "/usr/share/backintime/common",
>             "/usr/lib/python311.zip",
>             "/usr/lib/python3.11",
>             "/usr/lib/python3.11/lib-dynload",
>             "/usr/lib/python3.11/site-packages"
>         ],
>         "qt": {
>             "Version": "PyQt 6.6.1 / Qt 6.6.3"
>         }
>     },
>     "external-programs": {
>         "rsync": {
>             "version": "3.2.7",
>             "protocol": "31.0",
>             "capabilities": {
>                 "file_bits": 64,
>                 "inum_bits": 64,
>                 "timestamp_bits": 64,
>                 "long_int_bits": 64,
>                 "socketpairs": true,
>                 "symlinks": true,
>                 "symtimes": true,
>                 "hardlinks": true,
>                 "hardlink_specials": true,
>                 "hardlink_symlinks": true,
>                 "IPv6": true,
>                 "atimes": true,
>                 "batchfiles": true,
>                 "inplace": true,
>                 "append": true,
>                 "ACLs": true,
>                 "xattrs": true,
>                 "secluded_args": "optional",
>                 "iconv": true,
>                 "prealloc": true,
>                 "stop_at": true,
>                 "crtimes": false
>             },
>             "optimizations": {
>                 "SIMD_roll": true,
>                 "asm_roll": false,
>                 "openssl_crypto": true,
>                 "asm_MD5": false
>             },
>             "checksum_list": [
>                 "xxh128",
>                 "xxh3",
>                 "xxh64",
>                 "md5",
>                 "md4",
>                 "sha1",
>                 "none"
>             ],
>             "compress_list": [
>                 "zstd",
>                 "lz4",
>                 "zlibx",
>                 "zlib",
>                 "none"
>             ],
>             "daemon_auth_list": [
>                 "sha512",
>                 "sha256",
>                 "sha1",
>                 "md5",
>                 "md4"
>             ]
>         },
>         "ssh": "OpenSSH_9.7p1, OpenSSL 3.2.1 30 Jan 2024",
>         "sshfs": "(no sshfs)",
>         "encfs": "(no encfs)",
>         "shell": "/usr/bin/bash",
>         "shell-version": "GNU bash, version 5.2.26(1)-release (x86_64-pc-linux-gnu)"
>     }
> }

</details>

This is a Wayland install as well.
Version: [backintime-git](https://aur.archlinux.org/packages/backintime-git) from the AUR built in clean chroot

I've been having an issue where the scheduled tasks don't run via cron anymore, so in the process, I've tried multiple things. One of which has been to move from the standard AUR package to the git, including a clean and fresh start of the git package, removing all configs. When starting from absolute scratch with backintime-git, as root (executed with `sudo -E backintime-qt --debug`), the prompt notifying me that Back In Time is not configured and asks if I'd like to restore a previous config shows up. Selecting yes will crash. Selecting no will open the application. Trying to restore the config at any point will result in the same crash.

```
ERROR: [qt/icon.py:39 <module>] No supported theme installed (missing icons). Please consult the project web site for instructions how to fix this.
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 2008, in <module>
    mainWindow = MainWindow(cfg, appInstance, qapp)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/app.py", line 354, in __init__
    settingsdialog.RestoreConfigDialog(self).exec()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/backintime/qt/settingsdialog.py", line 2273, in __init__
    self.colorRed.setColor(QPalette.WindowText, QColor(205, 0, 0))
                           ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QPalette' has no attribute 'WindowText'. Did you mean: 'windowText'?
```

**Comment by buhtz** [comment]
Hello gwstorm,
thanks for reporting this.

The problem was introduced within our migration from version 5 to 6 of PyQt (#1632). It is easy to fix. But the underlying problem is that our linter did not found this (no-member) problem by itself. Might be because that PyQt6 is a c-extension and not a regular Python package. Opened a follow-up question: https://github.com/pylint-dev/pylint/issues/9541 Maybe I can improve our linting.

Best,
Christian

**Comment by buhtz** [comment]
For a first workaround you can edit your settingsdialog.py file yourself. Change `QPalette.WindowText` into `QPalette.ColorRole.WindowText`.

I will wait for a fix until I got an answer from the pylint devs.

**Comment by hshl2** [comment]
That worked.
