### ISSUE TITLE
Replace an "isIPv6Address()" with python package "ipaddress"

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1686]
Replace this method `isIPv6Address()` with Python in-build [ipaddress](https://docs.python.org/3/library/ipaddress.html) package introduce with Python 3.3.

https://github.com/bit-team/backintime/blob/d33f35e10b4c3027b3b12881152c157eb1b2cc8c/common/tools.py#L1849

This is the only place this function is used. Remove the code and its unit tests.

**Comment by jarbhav** [comment]
@buhtz I would like to work on this, if it's still available.

**Comment by buhtz** [comment]
Hello Vaibhav,
OK, you are in. Thanks for you offer.

Best,
Christian

**Comment by jarbhav** [comment]
Hi Christian,
I have opened PR #1689 addressing this, please let me know if any changes are needed.

Thanks,
Vaibhav
