### ISSUE TITLE
Cursor size does not scale with KDE Display settings

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1690]
The cursor in BiT refuses to scale in a KDE setup with all screens set to scale to 200% (here on external primary screen):

![image](https://github.com/bit-team/backintime/assets/6339921/7afdb5ca-579f-4e84-9118-ec9596876840)

![image](https://github.com/bit-team/backintime/assets/6339921/3126d0a4-b376-4607-9015-66c22b7e1285)

Operating System: openSUSE Tumbleweed 20240412
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.0.0
Qt Version: 6.7.0
Kernel Version: 6.8.5-1-default (64-bit)
Graphics Platform: X11

**Comment by buhtz** [comment]
Dear noyannus,
Thanks for this report.

Can you please post the output of `backintime --diagnostics`.

I do not understand your screenshots. Can you please extend your description and explanation. Why do I see here?

> The cursor in BiT refuses to scale

Does this mean that when moving the cursor outside of the BIT window it gets the expected size?

Best,
Christian

**Comment by noyannus** [comment]
The screenshots show 
- a part of the BiT toolbar with the unscaled cursor over it,
- and the same toolbar with the desktop behind it, the cursor tip being over the desktop area.
Both images are at the same resolution.

>> The cursor in BiT refuses to scale

>Does this mean that when moving the cursor outside of the BIT window it gets the expected size?

Yes. It shrinks and changes shape when it moves into the BiT window, and grows and changes again when it leaves the window. The cursor that appears when outside BiT was set in the KDE settings. The cursor inside seems to be the default one (I guess, it's very small on 4K).

The diagnostics throw an error (as root or as user doesn't matter):
```
localhost# backintime --diagnostics
Traceback (most recent call last):
File "/usr/share/backintime/common/backintime.py", line 1190, in <module>
startApp()
File "/usr/share/backintime/common/backintime.py", line 507, in startApp
args = argParse(None)
^^^^^^^^^^^^^^
File "/usr/share/backintime/common/backintime.py", line 568, in argParse
args, unknownArgs = mainParser.parse_known_args(args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 1902, in parse_known_args
namespace, args = self._parse_known_args(args, namespace)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 2114, in _parse_known_args
start_index = consume_optional(start_index)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.11/argparse.py", line 2054, in consume_optional
take_action(action, args, option_string)
File "/usr/lib64/python3.11/argparse.py", line 1978, in take_action
action(self, namespace, argument_values, option_string)
File "/usr/share/backintime/common/backintime.py", line 742, in __call__
diagnostics = collect_diagnostics()
^^^^^^^^^^^^^^^^^^^^^
File "/usr/share/backintime/common/diagnostics.py", line 74, in collect_diagnostics
'OS': _get_os_release()
^^^^^^^^^^^^^^^^^
File "/usr/share/backintime/common/diagnostics.py", line 398, in _get_os_release
return osrelease['os-release']
~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'os-release'
localhost#
```

**Comment by buhtz** [comment]
Thanks for reporting back. I do now understand your problem. Sounds funny but wired. Never experienced a behavior like this. Might you be able to record that? There is a nice tool named [peek](https://github.com/phw/peek) which I do my own screen recordings with and save them as GIFs. Just for fun not for diagnosis.

I have no idea what it could be. But I am not an expert when it comes to desktop environments, X and all this graphic stuff. Maybe my colleauge "aryoda" have an idea. But it will take some weeks until he will reply. Another approach could be to ask in the KDE or Suse forums and mailing lists. Maybe they will have an idea. Or in the Qt forum itself.

The `KeyError: 'os-release'` is a known problem fixed (#1581) in 1.4.3 and later. No big deal. Just ignore it.

Please don't hesitate to ask back if you don't hear from us.

**Comment by noyannus** [comment]
Here's the fun:

![Peek 2024-04-15 17-42](https://github.com/bit-team/backintime/assets/6339921/95046a01-91a9-4431-89e9-26ca92b72907)

**Comment by buhtz** [comment]
Do you have any other Qt using application you can test?
Mhm... Your version of BIT should use Qt5. The latest development version of BIT is using the next Qt version 6. It might be fixed then.

**Comment by noyannus** [comment]
> Do you have any other Qt using application you can test?

How do I identify them?

>  It might be fixed then.

No problem. Was just a funny observation. Feel free to close.

**Comment by buhtz** [comment]
> > Do you have any other Qt using application you can test?
> How do I identify them?

Don't know exactly how to do this on Suse. But you should "ask" your package manager. There is a package named "pyqt5" or "python-pyqt5" or "python3-pyqt5". This package should have information which other packages do depend on it. This other packages might be some relevant GUI applications.

> > It might be fixed then.
> No problem. Was just a funny observation. Feel free to close.

I will keep this open until we know more.

I also started a discussion at openSuse: https://forums.opensuse.org/t/mouse-cursor-changes-size-between-window-and-desktop/174223

**Comment by noyannus** [comment]
With a fake attempt to uninstall `python311-qt5..` I found only BiT and Treeline that would break. 

With treeline, the cursor behaves as expected.

But I see the funny behaviour with the YaST package manager. ~8-O


EDIT:
TreeLine version 3.1.6
Library versions:
   Python:  3.11.8
   Qt:  5.15.13
   PyQt:  5.15.10
   OS:  Linux-6.8.5-1-default-x86_64-with-glibc2.39

Not sure which is responsible for the YaST interface:
yast2-packager - YaST2 - Package Library    5.0.5-1.1
patterns-kde-kde_yast - YaST KDE User Interfaces    20240311-2.1
patterns-yast-x11_yast - YaST User Interfaces    20220411-1.6
patterns-yast-yast2_basis - YaST Base Utilities    20220411-1.6

**Comment by buhtz** [comment]
I assume this problem is not related to BIT and we can not handle it on our site. But I am not sure.

I will keep the issue open for a while but vote to close it after that cool done phase even if there is no known solution.

**Comment by noyannus** [comment]
The package manager points to an upstream issue. And maybe Qt6 will resolve it anyway.

**Comment by noyannus** [comment]
More fun, this time with Font Manager.

![Peek 2024-04-16 11-49](https://github.com/bit-team/backintime/assets/6339921/0c1b2901-aaad-48fe-bd47-05945394d6d7)


![Peek 2024-04-16 11-51](https://github.com/bit-team/backintime/assets/6339921/12a1c66a-c215-4e2c-a6e4-4833e198deff)

**Comment by buhtz** [comment]
Seems not to be Qt-related because Gtk is also involved.

**Comment by tannenfreund87** [comment]
I think you can close this. This is some weird behavior, that involves different toolkits, X11, Wayland and XWayland. KDE switched to Wayland as the default session with plasma 6, and openSUSE Tumbleweed removed the X11 session for some user configurations in the update from plasma 5 to 6.

I saw this behavior with other Qt5-based apps in a plasma 6 Wayland session, too. After some update, it disappeared, only to remain for some flatpak apps. It's a mess, but definitely out of scope for backintime.

**Comment by noyannus** [comment]
"Upstream issue" seems to be the consensus.

Closing.
