### ISSUE TITLE
Backup failed with error "rsync ended with code 255"

### ISSUE THREAD

**Issue by artem78** [bit-team/backintime#1691]
Hello.

I try to make backup to remote server using SSH. When I press "Take a snapshot" button It fails with message:

![Снимок экрана в 2024-04-16 11-27-04](https://github.com/bit-team/backintime/assets/8585304/7cc29dde-eb29-4cb4-bd2c-34c5b361bdc8)

I use BackInTime v1.4.1-1 from bit-team/stable PPA on Linux Mint 20.3 64-bit.

My config file - [backintime-config.txt](https://github.com/bit-team/backintime/files/14994138/backintime-config.txt).

`backintime --diagnostics` command output:
```
qt5ct: using qt5ct plugin
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.4.1-1",
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "running-as-root": false,
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "platform": "Linux-5.4.0-174-generic-x86_64-with-glibc2.29",
        "system": "Linux #193-Ubuntu SMP Thu Mar 7 14:29:28 UTC 2024",
        "OS": {
            "/etc/os-release": "Linux Mint 20.3",
            "/etc/lsb-release": "DISTRIB_ID=LinuxMint\nDISTRIB_RELEASE=20.3\nDISTRIB_CODENAME=una\nDISTRIB_DESCRIPTION=\"Linux Mint 20.3 Una\"\n",
            "/etc/debian_version": "bullseye/sid\n"
        },
        "display-system": "x11",
        "locale": "ru_RU, UTF-8",
        "PATH": "/home/UsernameReplaced/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.8.10 default May 26 2023 14:05:08 CPython GCC 9.4.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.8",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python38.zip",
            "/usr/lib/python3.8",
            "/usr/lib/python3.8/lib-dynload",
            "/usr/local/lib/python3.8/dist-packages",
            "/usr/lib/python3/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 5.14.1 / Qt 5.12.8",
            "Theme": "Mint-Y",
            "Theme Search Paths": [
                "/home/UsernameReplaced/.icons",
                "/home/UsernameReplaced/.local/share/icons",
                "/var/lib/flatpak/exports/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": "3.1.3",
        "ssh": "OpenSSH_8.2p1 Ubuntu-4ubuntu0.11, OpenSSL 1.1.1f  31 Mar 2020",
        "sshfs": "2.10.0",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)"
    }
}
``'

**Comment by buhtz** [comment]
Hello Artem,
Thanks for this report and the detailed information.

Can you login to your server via SSH without problems and without a password?

    $ ssh artem@server

**Comment by artem78** [comment]
@buhtz 

Yes, it works.

**Comment by buhtz** [comment]
Can you please run BIT in a terminal window with `backintime-qt --debug`, reproducing the problem and then post the output? Please first check your debug output because there might be sensible information in it.

**Comment by artem78** [comment]
I did as you said. Program asked SSH password in terminal and after input started backup.

[backintime log.txt](https://github.com/bit-team/backintime/files/15030393/backintime.log.txt)

I have no ideas why program doesn't use key and ask for password.

![Снимок экрана в 2024-04-18 23-57-36](https://github.com/bit-team/backintime/assets/8585304/b6ab2f2e-2059-44d3-9386-363a017a9fcd)

**Comment by buhtz** [comment]
do you have a passphrase on your key?

**Comment by artem78** [comment]
No, but my OS first time asks password for unlock key.

![Снимок экрана в 2024-04-19 12-21-09](https://github.com/bit-team/backintime/assets/8585304/dda8dc79-7398-49bd-9089-b60fa236c48e)

**Comment by buhtz** [comment]
Mhm... I am a bit out of expertise here. But I think we have a trail.

**Comment by artem78** [comment]
I don't know what exactly I did, but after some manipulations the error disappeared. Thanks for your time and help.

**Comment by buhtz** [comment]
Thank you for reporting back. I assume it was something related to the SSH setup.

Please let us know if you find out what it was or what it might have been. Then we can improve our documentation and maybe also the errors message reported by BIT itself.

Best,
Christian

**Comment by aryoda** [comment]
Note sure about the reason for this issue but I think exit code 255 is not (directly) from `rsync` but from `ssh` (see `man ssh`):

> EXIT STATUS
>      ssh exits with the exit status of the remote command or with 255 if an
>      error occurred.

`rsync` itself mentions this too (but only in the source code) although it does not translate this into a more specific error message:

https://github.com/RsyncProject/rsync/blob/4592aa770d51d5e83845b032feea1de441f03ee7/errcode.h#L50-L60

So perhaps we should mention `ssh` too for non-`rsync` exit codes because our current message

https://github.com/bit-team/backintime/blob/6d12f7d09c1ee82f8d8380220b3dfed3e61d2aa4/common/snapshots.py#L1424-L1426

is misleading in this case.
