### ISSUE TITLE
additional files to be excluded

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#170]
This is more of a suggestion list then a bug report, I also invite other people to freely add to this bug (I could not find a duplicate) for the same purpose.

Here is a list of files that should be excluded by default, as they cause problems:
1) */dosdevices/?:
they are soft links created by wine, normally in  .wine/dosedvices/?: but possibly in other places (e.g. picasaweb installation), they often include broken links that cause problems. They are recreated by win automatically in any case
2) ~/.DCOP*
include several special files that are created by kde and cannot be back-upped properly
3) .pulse/*remote
links created by pulseaudio (I think) to temporary storage, often broken and in any case they are recreated automatically

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-11-28T03:03:37Z
 * owner: justforspam
 * the launchpad url was https://bugs.launchpad.net/bugs/682270

**Comment by buhtz** [comment]
I would suggest closing this issue. The 3 cases described are quite special.
The user can add that files/folders by her/himself when she/he really need it.
