### ISSUE TITLE
Remove "class DriveInfo" (dead code)

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1701]
Always surfing through the codebase ... 🏄 

The `class DriveInfo` was introduced in 2009 by Dan.
https://github.com/bit-team/backintime/blob/5aa0746bf36bb49d95969e558ca4fdde38dfaa86/common/driveinfo.py#L25

Looking into the commit history it wasn't substantially modified.
But it was also never used (checked via `git grep`).

Code and idea behind should be investigated. There is not much documentation about it.

**Comment by buhtz** [comment]
The class try to find out the features (permissions, hardlinks, ...) of the given file system.
And it seems to store the result as a config file.

I say it can be removed without replacement.

**Comment by SanjaySiddharth** [comment]
Hello @buhtz , Can I help the team out and perform this code modification ?

Let me know if you need any more information

**Comment by buhtz** [comment]
Dear SanjaySiddharth ,
thanks for this kind offer.
When scrolling up you might see that the issue was referenced in #1706 which itself is a Pull Request. So the Issue was taken by some one else and has a solution (#1706).

Let me know if you find something else.

Best,
Christian

**Comment by SanjaySiddharth** [comment]
Hey @buhtz ,

Thanks for taking the time to let me know this.

Regards,
Sanjay
