### ISSUE TITLE
Feature request: Profile Splitting Wizard

### ISSUE THREAD

**Issue by TiagoTiago** [bit-team/backintime#1722]
I initially just set up a single backup profile to backup everything to guarantee I had everything taken care of from the start, and over time gradually build up the include and exclude lists as needed. But I've noticed backups can take a long time to start as it starts collecting information and then goes thru the huge lists of everything almost one by one ( I know there's some level of parallelism in the background, but still not enough), and it doesn't starts new backups of anything until the whole single monster profile finishes.

I would like the ability to be able to copy settings between profiles, and move includes/excludes between profiles with "smart" options, letting me exclude things from the big profile that are taken care of by the new profile and stuff like that (an important keyword there being "options", there can be situation where the user may want the same file backuped by multiple profiles, maybe more often locally and more sporadically remotely, or for various other reasons; so  "exclude item moved to new profile if it would otherwise be included directly or indirectly in the existing profile" won't always be the preferred mode of action).

Ideally, this wizard should be available both when creating new profiles, but also for fine-tuning things later for when you realize you missed something at the start.

**Comment by buhtz** [comment]
Hello TiagoTiago,

Thank you for taking the time to describe this feature and providing the
details. I appreciate your feedback and ideas.

Is your request just about the profile settings only or also about the snapshots (backup data)? For the later it is technically nearly impossible.

When it is "just" about the settings it is IMHO to complex and not worth the effort. What you describe involves profiles depending on other profiles settings. Technically this is not impossible but to complex and need to be maintained i the future by someone. I also assume not much users will use such a complex setup.

You could simply use a text editor to modify the config file yourself. But be careful.

I would suggest you take a step back and think about your backup strategy from scratch again. The scenario you describe indicates that there is a problem with your strategy.

Best regards,
Christian

**Comment by TiagoTiago** [comment]
> The scenario you describe indicates that there is a problem with your strategy.

Yeah, there is a problem, I was hoping for a way to tidying it up that would involve less manual work.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian
