### ISSUE TITLE
"Website" toolbar button is redundant

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#173]
Similar to bug #686695 : the website button should go away. Its functionality is already present in the About button.

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-07T19:14:07Z
- owner: kiddo
- the launchpad url was https://bugs.launchpad.net/bugs/686711

**Comment by emtiu** [comment]
I think the button, hidden away in the Help menu along with other useful URLs, doesn't hurt. Then again, as long as it doesn't point to any actual website, but just to this repo, it really isn't very useful.

**Comment by buhtz** [comment]
Fixed via PR #1478.
![image](https://github.com/bit-team/backintime/assets/11861496/b4392f73-4d2a-43a9-8f35-826fb57fec8e)
