### ISSUE TITLE
Drop Python3.8 support this year

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1731]
Regarding to [python.org](https://www.python.org/downloads/) the Python version 3.8 will lose its "security" support phase in October this year.

Because of that we should drop the support for Python 3.8 after the upcoming release.

**Comment by daveTheOldCoder** [comment]
Aside from the security issue, will the latest version of BiT still work with Python 3.8?

I'm asking because my python3 version is 3.8.10.

I suppose I could upgrade python3, but I would need to find a PPA or use a manual install.

If I only need to change the value of PYTHON_VERSION_REQUIRED in the script(s), I may do that for now.

**Comment by buhtz** [comment]
Technically you are right. We don't plan to use Python features that are exclusive to Python 3.9 or higher.
Be aware that the last release 1.5.1 still supports Python 3.8. That BIT version will be part of the next Ubuntu.

The reason to drop 3.8 is the release schedule of Python.org itself .Python 3.8 is not actively supported anymore. It only gets security updates, but only until the end of this year. It is nearly dead. We are just orientate on that. If there are GNU/Linux distros out there supporting such old Python versions they have to really **support** it. In consequence this means they need to backport some other software (e.g. Bit).

As maintainer I am always interested in user stories. So what operating system are you on that you are stick to Python 3.8?

**Comment by daveTheOldCoder** [comment]
I'm using Pop!_OS 20.04, which is based on Ubuntu 20.04, which is supported until Apr 2025.

I should upgrade to Pop!_OS 22.04, or Pop!_OS 24.04 which should be available soon, but I've been having trouble setting up a dual-boot so that I can keep the old version bootable (for a while) as well as the new one.

Both of those have Python 3.9 or higher.

I also found this PPA, which has newer versions of Python 3 : https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

**Comment by buhtz** [comment]
> I'm using Pop!_OS 20.04, which is based on Ubuntu 20.04, which is supported until Apr 2025.

In case of Ubuntu you must read the fine print. What does mean "supported"? If there are security issues in Python3.8 the Python Foundation itself won't fix them because they do not support Python3.8 anymore. Does Canonical Ubuntu fix them? I am not sure about it and won't count on it. The terms "support" and "LTS" in context of Canonical Ubuntu are just a hot bubble, a marketing lie. If you need something stable, secure and reliable, try Debian GNU/Linux.

And it is also fact that Back In Time is not part of Ubuntu. BIT is contained in the "universe" repository of Ubuntu which is not Ubuntu. BIT for example is just copied from Debian GNU/Linux repository into that "universe" repository. "Universe" is a community driven repository that is not contained in the "support" and "LTS" of Canonical. Canonical use this repository only for marketing. The community does the work and Canonical put their Ubuntu lable on it, earning money without taking the responsibility for the "universe" repo.

> I also found this PPA, which has newer versions of Python 3 : https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

I wouldn't recommend to mix Python versions on a system.

**Comment by daveTheOldCoder** [comment]
I've been using Pop!_OS for about five years, and Ubuntu for about 14 years, and am generally happy with them. I use distros that are provided by the manufacturer of my computers, which are specifically designed to be Linux-compatible, so everything works. Before I did that, there were always a few things that I could never get working.

The PPA should have all the dependencies, so I wouldn't really be mixing Python versions.

**Comment by daveTheOldCoder** [comment]
Out of curiosity, did my mention of Pop!_OS result in the issue you posted to their github tracker? :wink:

I was in the process of upgrading to Pop!_OS 22.04, but am now considering installing Ubuntu 24.04 instead.

The reasons are (a) System76 has limited S/W support (System76's business is building and selling Linux computers, not developing and supporting software. I suspect they only have one or two people supporting Pop!_OS on a part-time basis.) and (b) Ubuntu 24.04 was released in April, while Pop!_OS 24.04 is only in Alpha. Also, "Ubuntu" is easier to type than "Pop!_OS". :smiley_cat:

**Comment by buhtz** [comment]
Hi Dave,
yes I was trying to get info from PopOS but found out their website is not very verbose/transparent about the project details. Not very maintainer friendly.

**Comment by daveTheOldCoder** [comment]
>Aside from the security issue, will the latest version of BiT still work with Python 3.8?

I'm just noting that this is no longer an issue for me. I'm now using Ubuntu 24.04, which has Python 3.12.3.
