### ISSUE TITLE
feat+docu(EncFS): Research about how to handle encrypted drives and how BIT can help with that

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1736]
Related meta issue #1734 

# Introduction
Welcome to the project, if you pick up this Issue because of the "GOOD FIRST USE" label. You will be mentored through the process if you want. First the Issue is explained. At the end you will find some guidance for first contributors. Please do not hesitate to ask questions. Your solution don't need to be perfect.

Participation or contribution is not recommended unless you are familiar with Back In Time and are an active user. This project is not intended for learning basic Python skills or enhancing your GitHub profile.

# Problem
This issue is not about a bug but about researching about some topics. They are:
- Which use cases do we have in the context of using encrypted file systems on partitions (e.g. via LUKS) or file containers (e.g. VeraCrypt) as backup destination?
- Can BIT handle (e.g. mount) them today or does BIT need new features?
- Can BIT somehow be improved to make it easier or more transparent handling encrypted drives?
- Which topics (use cases, problems, use-callback scripts, ...) should be considered in a good documentation about it?
- Is a good documentation enough or does BIT need new features?

# Solution
Dive in to the topic. Doing tests. Write down your experience and report to us.

# Your next steps
1. If this is your first contribution in this project please introduce your self and tell us about your skills, wishes and plans. Also let us know how you found the issue and the project.
2. We can develop the next steps in the further discussion. Don't hesitate to ask.

**Comment by AhmedCSAhmed** [comment]
Hey @buhtz, I would like to be assigned this issue. I found it through good-first-issues, and this will be my first ever contribution to this repo. I would love to be mentored through the process, if possible.

**Comment by buhtz** [comment]
Hello Ahmed,

thank you for your efforts. Please read the issue carefully and work on the described steps.

Best,
Christian

**Comment by AhmedCSAhmed** [comment]
Will do

**Comment by buhtz** [comment]
To my understand we can close this.

We got several comments (e.g. [this](https://github.com/bit-team/backintime/issues/1734#issuecomment-2151875246)) about using BIT with an encrypted file system. It might be a use case for some person but it is not a replacement for EncFS.

So the question this issue is about is IMHO answered.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
