### ISSUE TITLE
Continuation of issue 1721

### ISSUE THREAD

**Issue by philm001** [bit-team/backintime#1744]
Hello everyone, I apologize for going silent for so long. I haven't had a chance to respond and since the issue is closed, I would like to re-open this issue since I am still having this issue of implementing the auto back up. 

Here is a link to the original issue: https://github.com/bit-team/backintime/issues/1721

Per the feedback, I have checked the following locations and noted their outputs below:

# /etc/crontab

`
 /etc/crontab: system-wide crontab
 Unlike any other crontab you don't have to run the crontab
 command to install the new version when you edit this file
 and files in /etc/cron.d. These files also have username fields,
 that none of the other crontabs do.

SHELL=/bin/sh
 You can also override PATH, but by default, newer versions inherit it from the environment
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

 Example of job definition:
 .---------------- minute (0 - 59)
 |  .------------- hour (0 - 23)
 |  |  .---------- day of month (1 - 31)
 |  |  |  .------- month (1 - 12) OR jan,feb,mar,apr ...
 |  |  |  |  .---- day of week (0 - 6) (Sunday=0 or 7) OR sun,mon,tue,wed,thu,fri,sat
 |  |  |  |  |
 *  *  *  *  * user-name command to be executed
17 *    * * *   root    cd / && run-parts --report /etc/cron.hourly
25 6    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
47 6    * * 7   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.weekly )
52 6    1 * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )
#
`

### /var/spool/cron/crontabs/

Empty

### /etc/cron.d/

Empty

### Output from crontab -l

`
Back In Time system entry, this will be edited by the gui:
Please don't delete these two lines, or all custom backintime entries will be deleted next time you call the gui options!

`

**Comment by buhtz** [comment]
Issue #1721 is not closed. Please go back there.
