### ISSUE TITLE
"local encrypted" not working because of missing snapshotpath (release critical)

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1808]
While preparing next release and testing on Debian unstable. A local encrypted profile.

This message appears every time when closing the manage profiles dialog.
![image](https://github.com/user-attachments/assets/3085f698-a15c-422b-9aad-586d64915599)

Clicking yes and entering the password:
![image](https://github.com/user-attachments/assets/d60f74e5-593a-45a6-b632-fc007faea52a)

I don't know about EncFS and need to investigate this.

**Comment by emtiu** [comment]
Hmm, I haven't tried this in a VM, but at first glance, there are some strings in seriously wrong places:

> _Can't mount_ 'encfs --extpass=backintime-askpass […]

Looks like there's a command string (`encfs --extpass=[…]`) where there should be a path/mountpoint.

**Comment by buhtz** [comment]
The encfs version in Debian stable and testing are the same.
There is also the problem that the backup destination field in the "General" tab of "Manage profiles..." is empty.

I am assuming we will miss the next Ubuntu release.

**Comment by buhtz** [comment]
I do have a trail ...

It does not depend on the Debian version. I can reproduce this on Debian stable (12), too. It is something about the snapshotpath edit field in the Manage profiles dialog and the `self.mode` variable. That field is empty under specific (maybe rare) circumstances. In consequence a call to "encfs" (when closing the manage profiles dialog) does not have all relevant arguments. Still investigating.

It happens with BIT dev but not with v1.4.3 (latest release).

To reproduce:
- Main profile should be a simple local.
- Create second profile "local encrypted".
- Restart bit.
- In the main window (not the settings dialog) switch to the second profile.
- Open the settings dialog.
- You see the "save snapshots here" field is empty.

This does not happen when:
- Start BIT.
- Open settings dialog.
- Switch to second profile.
- The field has a value.

I was not able to reproduce this on my productive machine. This might be because I do have multiple profiles (nearly 10) on that machine.

**Comment by buhtz** [comment]
Found the reason. Was introduced with PR #1771. Now will checkout a solution.

**Comment by emtiu** [comment]
Good job tracking this down 🤝
