### ISSUE TITLE
backintime build fails with a missing SSH public key "/builddir/.ssh/id_rsa"

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#1813]
I am trying to build it for fedora, but the build fails with a test, which I don't really understand why. I think perhaps, that the command `sshKeyGen` is not executed before the rest of the commands in sshtools.py.
Thanks for any hint, perhaps I am also missing a build dependency, but I didn't see anything missing in the log.

[build.log](https://github.com/user-attachments/files/16398661/build.log)

**Comment by buhtz** [comment]
The "unit" tests are very fragile. For example Debian do not run them at all in their build pipeline. The maintainer only run them on their local machine.
Your build.log looks like something rpm related? I have no experience with that.

You need a running ssh server with a password-less login to localhost for some of the tests.
It seems that your script/environment/bit looks in "/builddir/.ssh/id_rsa" for the ssh key. Usually it is in ~/.ssh/id_rsa.
What is "builddir"?

See the [FAQ entry about SSH related tests](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#SSH). Usually unit tests do not fail but are skipped if SSH is not working.

This variable is used while testing to determine if the SSH setup is as expected:
https://github.com/bit-team/backintime/blob/79bc654d10daa12ce51171c81ea9f5a2c19c6fb4/common/test/generic.py#L70-L79

https://github.com/bit-team/backintime/blob/79bc654d10daa12ce51171c81ea9f5a2c19c6fb4/common/test/generic.py#L48-L48

For a first test you should try to [run the test](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#testing) from the upstream git repo without the rpm stuff.

**Comment by hannes101** [comment]
Yes, it's within a local mock environment. Then I think I disable them for now for the build. What would be the easiest way to do this?

**Comment by hannes101** [comment]
Nevermind, I just removed the ssh test file in tests and now it's skipped for the time being.

**Comment by buhtz** [comment]
If you want, we can think about how to solve this.
I am not sure about it. But our test environment does locate the ssh-key file in `~/.ssh/` and is calling `pathlib.Path.home()`. In your case it seems that the mock-thing causing to overwrite the return value of `home()` making it `/builddir`.

I don't think it is a clean solution to overwrite $HOME because of things like this. Would be interesting how other applications doing this in context of RPM package building.
