### ISSUE TITLE
Provide BIT 1.5.x in PPA: jammy, noble (feature request)

### ISSUE THREAD

**Issue by speedy-10** [bit-team/backintime#1822]
Hi guys, thanks for your new work on BIT!
If you'll find time to update the https://launchpad.net/~bit-team/+archive/ubuntu/stable, when BIT is stable enough, that would be nice. 
Regards

**Comment by buhtz** [comment]
Hello M.,
thank you for reporting.

Please notice that this Back In Time upstream project do not direct support PPA or any other external package format. Please see [this FAQ entry](https://github.com/bit-team/backintime/blob/dev/FAQ.md#support-for-specific-package-formats-deb-rpm-flatpack-appimage-snaps-ppa-) and our [install instructions](https://github.com/bit-team/backintime?tab=readme-ov-file#installation) about it.

I understand that the available information are a bit misleading. Germar Reitze is the maintainer of the PPA and in the past he was also an active maintainer of this upstream project. It is not clear how active he is today. You should contact him via his Launchpad account or [open a ticket there](https://bugs.launchpad.net/~bit-team).

Best regards,
Christian

**Comment by speedy-10** [comment]
Thanks, I wrote him an e-mail over launchpad.

**Comment by buhtz** [comment]
The in October upcoming Ubuntu Version should have bit 1.5.1

**Comment by speedy-10** [comment]
Hi, so far I didn't get an answer from Germar.
I'm using LinuxMint and no STS-ubuntu's, so I'd have to wait until 2026 for the next LTS-version.
Perphaps one of the other contributors could provide a separate, new PPA, if Germar has no more time for updating his PPA?

Regards

**Comment by buhtz** [comment]
IMHO PPAs or other 3rd party sources like snap/flat/fancyshit are not of much use. They are all unstable and unsecure by definition. It is just an extra step simulating stability and false security. If you need the freshest version why not just install from upstream (our repo)? But do it on your own risk even if it is the latest official release tarball. If your distro provide PyQt6 in its official repository then the latest BIT version should run on your system.

Or contact the package maintainer of your distro and ask for a backport. Or provide the backport yourself.

**Comment by speedy-10** [comment]
PPA is very easy for normal users, I don't like tarball. Is it much work to provide a deb-File, too, for the contributors?

**Comment by buhtz** [comment]
Yes, it might be some work. It is up to everyone to provide a PPA himself. So why not trying it? See [this merged PR](https://github.com/bit-team/backintime/pull/1733) where we removed the debian packaging related stuff from the upstream repo. You can use it. It is the same stuff Germar use to create the PPA.

It might also be possible to join Germar at his PPA project. He might be willing to hand it over to someone. So the URLs won't change.

As you can read in the FAQ entry I was linking to, we do support every extern contributor providing an alternative release channgel, even if it is something like snap. We can communicate and we are also open to modify something at upstream if it ease the process for such projects.
