### ISSUE TITLE
Is there any plan for official PPA?

### ISSUE THREAD

**Issue by trancephorm** [bit-team/backintime#1845]
Using https://launchpad.net/~bit-team/+archive/ubuntu/stable PPA is not working, there is no Release file, whatever that means. I would rather not compile, any chance it can be installed easily on Ubuntu 24.04?

**Comment by buhtz** [comment]
Hello trancephorm,
thank for reaching out. The PPA you are pointing to is an extern source not managed by our upstream project. Please read the following:
- [FAQ: Support for specific package formats (deb, rpm, Flatpack, AppImage, Snaps, PPA, …)](https://github.com/bit-team/backintime/blob/dev/FAQ.md#support-for-specific-package-formats-deb-rpm-flatpack-appimage-snaps-ppa-)
- [CONTRIBUTING.md: Build & Install](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build--install)

Anyway, it seems that Ubuntu 24.04 still has BIT 1.4 in its repo. You won't miss much compared to the latest upstream release 1.5.2.

Best,
Christian

**Comment by trancephorm** [comment]
Thank you! What is the package name if Ubuntu 24.04 has it in its repo? I can't find it.

**Comment by buhtz** [comment]
You can do `apt-cache search backintime` or look at [Ubuntu's package website](https://packages.ubuntu.com/noble/backintime-qt).
