### ISSUE TITLE
Snapshot logs missing

### ISSUE THREAD

**Issue by Key-Snapper** [bit-team/backintime#1866]
I'm moving from Linux Mint 21.1 to a fresh installation of Linux Mint 22.
As I have had owner problems with Windows files in the past, I use the root version.
The profiles are imported from the old snapshots and checked for changed paths.

After 4 days I noticed that some profiles were working and some were not.
The error messages are

> Failed to get take_snapshot log from None:
[Errno 2] File or directory not found: '/root/.local/share/backintime/takesnapshot_.log'.

I copied the log files from the old system, but it didn't help.

**Comment by buhtz** [comment]
Hello Key Snapper,

Thank you for taking the time to report the bug and providing the
details. I appreciate your feedback, will investigate the issue,
and work on a solution to the best of my ability.

Please post the output of `backintime --diagnostics` or name the version of Back In Time if that command is not available.

Please provide steps to reproduce this error message.

Please run BIT with `--debug` option and post the debug output around that error message.

Best regards,
Christian

Might be related to `common/snashotlog.py::SnapshotLog.get()`:
https://github.com/bit-team/backintime/blob/91bb54c583857fb1a9ac4c2bc9de5c212e9db5a9/common/snapshotlog.py#L179-L211

**Comment by buhtz** [comment]
Hello Key-snapper,
I need some feedback from your and answers to my questions. Otherwise I am not able to go further in analyzing this problem and need to close the issue.

Regards, Christian

**Comment by Key-Snapper** [comment]
I apologize for not getting back to you sooner. The problem has resolved itself over time.
The backups started again automatically and could also be started manually.
