### ISSUE TITLE
Does Back In Time keep the files that I deleted in the backup?

### ISSUE THREAD

**Issue by irodionzaytsev** [bit-team/backintime#1876]
Suppose I have a file A.txt in directory B/ and I am backing up the directory to my drive. When I do the backup, I will have B/A.txt on my drive. Now if I locally delete the file A.txt, and run the backup, what will happen to the file A.txt in the new snapshot? Will it be there or will it be deleted? Is there an option to control this? As I understand, by default rsync does NOT delete the file and it appears in the new snapshot, but there is an option --delete, so that A.txt WILL be deleted.

**Comment by buhtz** [comment]
> what will happen to the file A.txt in the new snapshot? Will it be there or will it be deleted?
Neither of it. It won't be transferred by rsync because it does not exist anymore in your backup source.

If you delete one file between two snapshot runs, the file won't exist in the second snapshot.

**Comment by daveTheOldCoder** [comment]
backintime adds the rsync --delete option.

See lines 500 and 1338 here:
https://github.com/bit-team/backintime/blob/v1.5.2/common/snapshots.py

I don't see a way of overriding that behavior from the user interface. (Personally, I like the existing behavior.)

**Comment by buhtz** [comment]
Any further questions or information to add? Or can we close the Issue?

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
