### ISSUE TITLE
Cannot edit the schedule of backintime 1.2 (with crontab or in GUI when HD not connected)

### ISSUE THREAD

**Issue by bjce** [bit-team/backintime#1884]
First of all, thank you very much for developping and maintaining backintime that is a greate piece of software!

I can successfully make backup with backintime but when I want to edit the `.config/backintime/config` file, and open then the GUI, the changes are overwritten. Moreover if I want to edit the schedule of the task with `crontab -e` as recommended in the doc, the schedule gets also overwritten by the change if I open the gui.
It might also be worth noting that when I want to edit a backup setting of on an external hard drive that is not connected to the computer, I get the following message: 
```
/path/to/externalHD/path is not a folder!
```
Here are the outputs of command that might be usefull:

```
$ backintime --diagnostics
usage: backintime [-h] [--config PATH] [--share-path PATH] [--debug]
                  [--profile NAME | --profile-id ID] [--quiet]
                  [--version] [--license]
                  {backup,backup-job,benchmark-cipher,check-config,decode,last-snapshot,last-snapshot-path,pw-cache,remove,remove-and-do-not-ask-again,restore,shutdown,smart-remove,snapshots-list,snapshots-list-path,snapshots-path,unmount}
                  ...
backintime: error: Unknown Argument(s): --diagnostics
```
It appears this argument is not known...

I got backintime from with the following command (in Ubuntu 22.04)
```
sudo apt-get install -y backintime-qt
```

**Comment by buhtz** [comment]
Hello bjce,

Thank you for taking the time to report and ask . I appreciate your feedback, will investigate the issue.

Your version of BIT is round about 5 years old. Please be aware that the "LTS" in Ubuntu does not count for packages in the "universe" repository. If you need a stable GNU/Linux distro I recommend to switch to Debian GNU/Linux.

That you can not modify the schedule or other settings when the external drive is not connected is an intended behavior. But of course it is not elegant. That behavior depends on the current "design". We try to fix this in the long run.

Why do you want to edit "config" file when you have a GUI? What makes me wonder that your config file is "overwritten". Can you give me a more detailed example please. Which setting did you modified in "config" file? Was this modified setting reflected in the GUI? What do you mean by overwritten?

When you do "crontab -e" you will see some comments in that file. There it is cleary stated that you are not intended to edit the existing cron jobs. You can add your own extra cron jobs but you can not modify the existing ones that are related to your snapshot profiles.

Please see the projects background information to get an idea about our workflow andn priorities:

- [Maintenance status](https://github.com/bit-team/backintime#maintenance-status)
- [The team](https://github.com/bit-team/backintime#the-team)
- [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline)

Best regards,

**Comment by bjce** [comment]
Dear @buhtz

Many thanks for taking the time of answering my question so promptly and in a very detailed way

- Regarding switching to Debian: I consider myself quite as a Linux beginner and switching to Debian from Ubuntu makes me a bit afraid for the moment. Shall I try to install another newer version of BIT through another source?

- Regarding the modifiable schedule while HD disconnected as intented behavior. I understand and will patiently wait for the future update

- the part of the config file I tried to modify was in fact not the schedule but the exclude path of rsync (e.g. "profile1.snapshots.exclude.17.value=/var/backups/*". I tried to write additional custom exclude (by writing "profile1.snapshots.exclude.18.value=/path/to/fileOrFolderToIgnore" when the GUI was not running but it got erased after gui was restarted)o

- crontab: indeed there is the message that this will be overwritten, but I still tried to edit it the documentation was stating that "crontab -e" could be tried (https://backintime.readthedocs.io/en/latest/settings/) but I most probably misunderstood the doc. I will then edit the schedule only through the GUI (or is there another file that one can edit for this instead of going through the GUI?).

I will also carefully have a look at the links you provided about the bigger picture of the BIT project

Many thanks again

Best regards

**Comment by buhtz** [comment]
> * Regarding switching to Debian: ...switching to Debian from Ubuntu makes me a bit afraid

Keep in mind that Ubuntu is "based" on Debian. The majority of packages in Ubuntu are just copied from the Debian repositories. I am aware that Debian still has a nerdy and unfriendly image. This comes from the past. But today Debian as a software and its community are quit friendly. No need to be afraid. Just stick to the "stable" Debian, don't use unstable/sid/testing.

> Shall I try to install another newer version of BIT through another source?

No need for this. This wouldn't fix your problems.

> the part of the config file I tried to modify was in fact not the schedule but the exclude path of rsync

Interesting. Then their might be a typo or a syntactical problem. The config file format is not easy to tackle. I also do work on that. So it might be that BIT was not able to read your new exclude entries and just ignored them.

> * crontab: indeed there is the message that this will be overwritten, but I still tried to edit it the documentation was stating

Yes, the docu is not clear enough about it. There is a lot potential in the documentation for improvement. Also on my list...

The crontab entries related to your snapshot profiles are removed and re-created (from the profile settings, the config file) everytime you open Back In Time. When you want to modify the schedule settings you have to edit the config file or use the Settings window in the GUI.

> I will then edit the schedule only through the GUI (or is there another file that one can edit for this instead of going through the GUI?

GUI is the recommended way. Otherwise you could edit the schedule settings in the "config" file. But these are quit complex.

**Comment by bjce** [comment]
Thank you very much for all your detailed answered @buhtz !

**Comment by bjce** [comment]
Maybe just a last question @buhtz : is there a way to exclude a .dotfile or a .dotdirectory via the GUI? I coud not find it in the GUI file browser

**Comment by buhtz** [comment]
Is your problem fixed?

**Comment by bjce** [comment]
yes many thanks!
