### ISSUE TITLE
Integrate with file managers (e.g. plugins for right-click functionality)

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#189]
Hi,

After seeing BIT's interface in its webpage, I found it so similar to the file manager that I thought, why not just integrate both?

I made a mockup showing the general idea. Some things might be missing, but I think those can be discussed.

Could you consider the idea?

---

Imported from Launchpad using lp2gh.
- date created: 2009-05-08T05:04:40Z
- owner: frandavid100-gmail
- the launchpad url was https://bugs.launchpad.net/bugs/373546

**Comment by Germar** [comment]
(by frandavid100-gmail)

**Comment by Germar** [comment]
(by danleweb)
I file manager it more that just exploring files, it should allow you to create/rename/modify files. Event more it should be able to explore samba, sshfs, ftp ... I don't think I can do better that Nautilus or Dolphin.

**Comment by Germar** [comment]
(by frandavid100-gmail)
Hi Dan,

Well, I didn't mean Back in Time should BE a file manager but rather be INTEGRATED (sort of as a plugin, if you will) in Nautilus, for example. Maybe, when installed, it could add a Backup sidebar and a Backup menu to Nautilus.

That way the user wouldn't need a separate program to backup their data, they could do it easily straight from the file manager. Since backing files up is a form of file management, it would make sense.

I think I know how to integrate all of BIT's features into nautilus without overcomplicating the interface at all. In case you and nautilus developers are interested, that is.

**Comment by Germar** [comment]
(by danleweb)
I'll be happy to see Nautilus with BIT integrated. But I can speak only for me. I don't know Nautilus developers or how to contact them.

**Comment by Germar** [comment]
(by frandavid100-gmail)
I'm not sure this would be the proper way to do it, but maybe setting this request as "also-affects" Nautilus could help?

**Comment by Germar** [comment]
(by a9016009)
http://mail.gnome.org/mailman/listinfo/nautilus-list

**Comment by Germar** [comment]
(by frandavid100-gmail)
Yes, contacting the mailing list would also be a good option. Would you be willing to collaborate with the Nautilus devs to achieve this?

**Comment by Germar** [comment]
(by adrian-lamy)
Common answer for bugs #373572 and #373546

A Sun developer has made an integration in nautlus with timeline for his backup program for ZFS filesystem. Why not reuse the code?
http://blogs.sun.com/erwann/entry/zfs_on_the_desktop_zfs

**Comment by caco3** [comment]
Link is broken, but this one seems to point to the same: https://blogs.oracle.com/erwann/entry/zfs_on_the_desktop_zfs

**Comment by buhtz** [comment]
Last relevant comment is from 2009 (on launchpad). Could you plesae report about the status and if this is still needed.

My opinion might be quite hard:
One of the big problems of Linux on desktops is the isolation and incompatibility of the different desktop environments. Why we should support Nautilus? Why not the others? Binding ressources for one specific software and its users group is to much for BIT. Pracitlcy: no ressources for this. Idologicly: We shouldn't support separation of the desktop environments. If they sit together and write kind of a open-standard-API for each filemanager that we could use here I would recommand this feauter. 

Currently I would recommand to close. @Germar ?

**Comment by emtiu** [comment]
Let's keep this as a low-priority feature request, and make it file-manager-independent. It would be nice to have right-click options like "See past versions in backintime" or "Exclude from backintime backup" in file managers like Dolphin or Nautilus. But that's a far-in-the-future wish :)

**Comment by buhtz** [comment]
I assume that features like this do need addons or something like this in the file managers not in Back In Time.
Of course Back In Time need to provide an API for such addons.

But until there is no one who develop such addons we won't provide such an API.

Closing this as not relevant for BIT currently. Feel free to reopen if some want to work on the file managers site.
