### ISSUE TITLE
Timeline for browsing snapshots

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#190]
First, please excuse me for reporting this as bug - I can't find a way to mark this as an enhancement

Currently, the snapshot pane on the left displays the snapshot names linearly. This should be OK if the number of snapshots are less. Supposing if backintime is configured to take (automated) weekly snapshots and if the snapshots get accumulated for a span of over 5 years, it would be very difficult to locate or jump to a particular 'range of snapshots' (for e.g. snapshot created between 2009 & 2010.

It would be easier if you could provide a timeline-like control similar to that in fspot. 

Screenshot1: http://xs.to/xs.php?h=xs139&d=09195&f=timeline123.png
Screenshot2: http://f-spot.org/Image:Main-window.png

---

Imported from Launchpad using lp2gh.
- date created: 2009-05-08T07:24:54Z
- owner: kpkeerthi
- the launchpad url was https://bugs.launchpad.net/bugs/373572

**Comment by Germar** [comment]
(by kpkeerthi)

**Comment by Germar** [comment]
(by danleweb)
This should be better in answers section. I think a quick jump to a special group will do. Also lists in GTK/Gnome provide quick search.

**Comment by Germar** [comment]
(by kpkeerthi)
I agree. But in terms of usability a timeline like control would be better than a list. It would also fit better for this application and would enable browse/scroll back in time to view the snapshots in a snap.

**Comment by Germar** [comment]
(by danleweb)
Event if I don't think I'll implement it soon, it is a very good idea.

**Comment by Germar** [comment]
(by adrian-lamy)
Common answer for bugd #373572 and #373546

A Sun developer has made an integration in nautlus with timeline for his backup program for ZFS filesystem. Why not reuse the code?
http://blogs.sun.com/erwann/entry/zfs_on_the_desktop_zfs

**Comment by emtiu** [comment]
I think you're right, there's not much of an advantage over the snapshot list panel the GUI currently has. I'm adding the https://github.com/bit-team/backintime/labels/Discussion Label, but unless someone has a very good argument or screenshot for a timeline interface, I'm in favor of closing.
