### ISSUE TITLE
Feature Request: Higher limit for available space on backup medium. 

### ISSUE THREAD

**Issue by khenty** [bit-team/backintime#1903]
Follow-up of #1880 

On my installation of backintime-qt, the largest value I can enter for the limit on available backup space is 1000 GB. I propose increasing this limit as a workaround for backintime's maxing out my 12 GB backup drive (100%). It's also possible that there's a bug here. Given that I'm doing daily backups, the backup drive is maxed out about once a week. I correct the problem by manually removing snapshots ("rm -rf SNAPSHOT_PATH [SNAPSHOT_PATH ...]). 
 
[diagnostics.txt](https://github.com/user-attachments/files/17356703/diagnostics.txt)

**Comment by buhtz** [comment]
Hello khenty,
thank your for your request.

What do you mean by "maxed out"?

Currently the "limit" can be set to 1.000 GB (~1 TeraByte). The meaning is not a limit, but BIT will start to remove snapshots if there is less than 1.000 GB free on your volume. Do you really want more than 1.000 GB kept free?

How can this help you? How big is one of your snapshots?

As a beginning I would suggest, that you modify your BIT installation by yourself. It is just one line.
https://github.com/bit-team/backintime/blob/3e80feee3ef81d5ab48b7d03828726c5ed0f08f1/qt/settingsdialog.py#L765

There the value `1000` is the limit of the that spinbox. Just put two more `0` to it and let's see if this really helps you.

Regards, Christian

**Comment by buhtz** [comment]
Hello khenty,
could you please take a look at my last comment and report back. Otherwise I need to close the Issue.

Thanks in advance,
Christian

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
