### ISSUE TITLE
[enhancement] Improved notifications when backup job is running

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#191]
Currently, when backintime is running the backup job, I could see a system tray icon that pops up a dialog displaying current file being backed up. 
1. The pop remains static and not does not indicate any change in progress even if the job is done with the file and has moved on to next file. Can this be made dynamic to reflect the current file being worked upon?
2. The popup dialog has Cancel and OK buttons? This might confuse the users as they might think that clicking on 'Cancel' will abort the backup process. I feel OK button alone would suffice.
3. A notification balloon (OSD) in the System tray would be nice:
   > It could be made to appear when the scheduled backup starts and finishes with some sort of acknowledgement message at the start and at the end.
   > On mouse over the system tray icon, you could progressively display some sort of status information, like current file being processing, % complete, estimated time or time elapsed and things like that.

---

Imported from Launchpad using lp2gh.
- date created: 2009-05-08T07:47:24Z
- owner: kpkeerthi
- assignee: danleweb
- the launchpad url was https://bugs.launchpad.net/bugs/373578

**Comment by Germar** [comment]
(by danleweb)
I have not popup dialog. Only a notification balloon that appear on error it the right option is set.
The tooltip also change but once displayed it remains unchanged until the next time it will be showed.
The same to the balloon. I didn't found a way to update it while it is displayed.

**Comment by Germar** [comment]
(by kpkeerthi)
The dialog pops up when you click on the system tray icon that appears when backup job is running.

**Comment by Germar** [comment]
(by kpkeerthi)
Attaching a screenshot of the dialog. 
1. Everytime the system tray icon is clicked a new dialog open
2. The current file name never changes in the dialog, unless the tray icon is clicked again and a new dialog opened.
3. The Cancel button is misleading and it appears that it would cancel the backup process. But it is not.

**Comment by Germar** [comment]
(by danleweb)
Strange. Maybe this is something related to Ubuntu 9.04. I used pnotify which just show a bubble on Ubuntu 8.04/8.10.

**Comment by Germar** [comment]
(by theoriginal-skullburner)
I also still have this problem on Ubuntu 9.04 with version 0.9.26.

**Comment by Germar** [comment]
(by bratdaking)
Ok, I just read your other bug, so I guess it could need some improvements
:-)


2009/10/10 SkullBurner <email address hidden>

> I also still have this problem on Ubuntu 9.04 with version 0.9.26.
>
> --
> [enhancement] Improved notifications when backup job is running
> https://bugs.launchpad.net/bugs/373578
> You received this bug notification because you are a member of Back In
> Time Team, which is the registrant for Back In Time.
>

**Comment by Germar** [comment]
(by theoriginal-skullburner)
I filled another bug as a enhancement wish. First I wanted to post it here but this here is more a real bug description with a enhancement proposal which is similar to that what I wanted to propose about progress dialog. So I decided to make new bug out of my enhancement proposal because I wanted to avoid a confusion.  : - )

**Comment by Germar** [comment]
(by emrys)
There is a blueprint related to point 3.

https://blueprints.launchpad.net/backintime/+spec/show-progress-bar

I also find confusing the Cancel option of point 2.

**Comment by buhtzz** [comment]
The image from the initial post at Launchpad.
![image](https://user-images.githubusercontent.com/11861496/190094575-71257548-ead7-4995-a42c-6ed61820836f.png)

Is this related too #1236 ?

**Comment by emtiu** [comment]
Since the bug was reported, the systray notification has gained pause/stop buttons and shows the same information as the GUI's status bar. This can be closed.
