### ISSUE TITLE
Shortcuts list not congruent with Settings > Included folders

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1924]
My entries in the Shortcuts pane have auto-changed. ~:-O

I used to have the most frequently restored from folders there (placed there by listing them explicitly in Settings > Include).

![Screenshot_20241109_225015](https://github.com/user-attachments/assets/ffd6c59f-1325-473b-9356-8cd824710fb2)

After a fresh system install (migration from Tumbleweed to Slowroll) and one backup with checksums (always as root), this list has changed, but the list at  Settings > Include is still the same. 

edit: The crossgrade entailed a change of user ID numbers; I had to `chown -R` the user folder to the new user (although it had the same user name).

![Screenshot_20241109_224916](https://github.com/user-attachments/assets/dd341343-09d1-4724-aa1b-1f7d03b0b49f)

Not really a break of function (just a few clicks more to reach my folders), but puzzling nonetheless. And it does not look nice. :-)

Backintime 1.5.2
Installed on openSUSE Slowroll via Discover or Zypper

```
localhost% sudo backintime --diagnostics
{
"backintime": {
"name": "Back In Time",
"version": "1.5.2",
"running-as-root": false,
"latest-config-version": 6,
"local-config-file": "/root/.config/backintime/config",
"local-config-file-found": true,
"global-config-file": "/etc/backintime/config",
"global-config-file-found": false,
"started-from": "/usr/share/backintime/common",
"user-callback": "/root/.config/backintime/user-callback",
"keyring-supported": false
},
"host-setup": {
"OS": "openSUSE Tumbleweed-Slowroll",
"platform": "Linux-6.11.6-2-default-x86_64-with-glibc2.40",
"system": "Linux #1 SMP PREEMPT_DYNAMIC Mon Nov  4 08:15:48 UTC 2024 (8545f24)",
"display-system": "($XDG_SESSION_TYPE not set)",
"locale": "en_DK, UTF-8",
"PATH": "/usr/sbin:/usr/bin:/sbin:/bin",
"RSYNC_OLD_ARGS": "(not set)",
"RSYNC_PROTECT_ARGS": "(not set)"
},
"python-setup": {
"python": "3.11.10 main Sep 09 2024 17:03:08 CPython GCC",
"python-executable": "/usr/bin/python3",
"python-executable-symlink": true,
"python-executable-resolved": "/usr/bin/python3.11",
"sys.path": [
"/usr/share/backintime/qt/plugins",
"/usr/share/backintime/common/plugins",
"/usr/share/backintime/plugins",
"/usr/share/backintime/common",
"/usr/lib64/python311.zip",
"/usr/lib64/python3.11",
"/usr/lib64/python3.11/lib-dynload",
"/usr/lib64/python3.11/site-packages",
"/usr/lib64/python3.11/site-packages/PIL",
"/usr/lib64/python3.11/_import_failed",
"/usr/lib/python3.11/site-packages"
],
"qt": {
"Version": "PyQt 6.8.0.dev2410061818 / Qt 6.8.0"
}
},
"external-programs": {
"rsync": {
"version": "3.3.0",
"protocol": "31.0",
"capabilities": "file_bits: 64; inum_bits: 64; timestamp_bits: 64; long_int_bits: 64; socketpairs: True; symlinks: True; symtimes: True; hardlinks: True; hardlink_specials: True; hardlink_symlinks: True; IPv6: True; atimes: True; batchfiles: True; inplace: True; append: True; ACLs: True; xattrs: True; secluded_args: optional; iconv: True; prealloc: True; stop_at: True; crtimes: False",
"optimizations": "SIMD_roll: True; asm_roll: False; openssl_crypto: True; asm_MD5: False",
"checksum_list": "xxh128, xxh3, xxh64, md5, md4, sha1, none",
"compress_list": "zstd, lz4, zlibx, zlib, none",
"daemon_auth_list": "sha512, sha256, sha1, md5, md4"
},
"ssh": "OpenSSH_9.9p1, OpenSSL 3.1.7 3 Sep 2024",
"sshfs": "3.7.4a",
"encfs": "1.9.5",
"shell": "/bin/bash",
"shell-version": "GNU bash, version 5.2.37(1)-release (x86_64-suse-linux)"
}
}
localhost%
```

**Comment by buhtz** [comment]
Hello noyannus,

thank you for taking the time to report this.

My apologize but I don't understand the problem.

> I used to have the most frequently restored from folders there (placed there by listing them explicitly in Settings > Include).

My misunderstand starts with this sentence.

The next point is that your first screenshot shows user-related folders and the second root related.

Regards,
Christian

**Comment by noyannus** [comment]
More context is definitely warranted; my bad, especially the screenshots were cropped too aggressively. The first showed Backup folders that are listed for "Now" in the backup list, the second were Backup folders for an actual backup.

More details. I run BiT as root and had set the Included folders to the user folders that I access more frequently like so:

![Screenshot_20241110_143854](https://github.com/user-attachments/assets/7bae9f98-bdfa-435f-86aa-0458bfd9cc15)

This used to result in matching paths listed under "Backup folders". It looked like this (this screenshot is for "Now", I guess "Now" reads the source filesystem, so it was not affected?).

![Screenshot_20241110_144044](https://github.com/user-attachments/assets/f75fb84f-9c4d-4174-933d-a57129208942)

Recently I changed OS edition with a clean install, and accidentally created a user with a different ID. The owner of the files from the old user (before OS change) was not shown any more, e.g. in Dolphin. So I changed the owner of all the user files in the BiT backups with `chown -R <user>:<group>  .../backintime/<machine>/root/1/<date>/backup/home/<user>` (with `find ... -path ... -exec ...`, actually). Now the owner (IDs) of the backups match the current user (ID).

What puzzles me is that the user folder bookmarks are gone, and the bookmarks list the content of the root home instead. But the Included folders in the BiT Settings have remained unchanged, they are as in the first screenshot.

![3Screenshot_20241110_144350](https://github.com/user-attachments/assets/eb5c6e49-d855-4d62-8f6b-6f7f044e19b7)


P.S.: This setup of BiT is not meant to be a full system backup. I use it to have all my changes of an old system in their place, ready to copy (and modify if necessary) them over to a fresh system -- things like keyfiles, network settings, chrony, crontab,.... BiT is very useful here.

**Comment by buhtz** [comment]
Sounds complex. You reinstalled the system and then manipulated the backup folders. IMHO the backup folder should work without modifying it.
Because I don't know exactly every step you did I am unable to identify the cause of the problem.

I was in a similar situation in the past.
You should start again from scratch and keep your old backup folder as a "backup".

**Comment by noyannus** [comment]
> You should start again from scratch and keep your old backup folder as a "backup".

That is probably the sanest strategy. 

Thank you for your readiness and taking the time to think through the problem.
