### ISSUE TITLE
1.5.3 release tarball contains -rc1 suffix

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#1926]
Upon extracting the tagged tarball, the parent dir is named backintime-1.5.3-rc1

**Comment by buhtz** [comment]
Hi graysky2,

thank you for testing and reporting.

Can you show me? I don't see it in any of the 3 archives attached to the release.

**EDIT**: Maybe this is about line 21 and 25 in your [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=backintime) file?

**Comment by graysky2** [comment]
Ah, my apologizes, I test built 1.5.3-rc1 a few weeks ago but forced the tarball's name to omit the -rc1.  When I update the PKGBUILD for 1.5.3 final release, the old tarball was not overwritten so it contained that -rc1 suffix.  Fixed now.
