### ISSUE TITLE
Missing debug-info on paths when backup path structure does not exist

### ISSUE THREAD

**Issue by igor-karpekin** [bit-team/backintime#1941]
Hello,
I had to configure everything from terminal - no UI. It took me a few hours to construct the necessary path for backups because of very confusing docs and lack of my understanding of the app. Can you please add the erroneous backup target path into debug output? Currently that is how it looks:

_notify-send -t 30000 Back In Time (admin) : daily Can't find snapshots folder. If it is on a removable drive please plug it. Waiting 30 seconds.
Failed to execute child process “dbus-launch” (No such file or directory)
DEBUG: [common/snapshots.py:747 backup] Cannot start snapshot yet: target directory not accessible. Waiting 1s._

Please add the full path in the error message that caused the error, that is a simple change, but can help a lot, e.g:

_notify-send -t 30000 Back In Time (admin) : daily Can't find snapshots folder '/backup/backintime/myserver/root/1'. If it is on a removable drive please plug it. Waiting 30 seconds._

Thanks,
Igor.

**Comment by buhtz** [comment]
Hello Igor,

Thank you for taking the time to report the issue and providing the details. I appreciate your feedback, will investigate the issue. 
Your suggestion is IMHO a good solution.

Which version of BIT are you using?

About the docu and config file? Yes, that is far a away from optimal. We have several issues and todo-task open and pending about that topic. One is that I do plan to convert the current config file format into a TOML file which is IMHO easier to read for human beings.

If you have any more details or ideas to share, feel free to reach out.

Not sure when we'll find the time to work on it. Please see the projects background information to get an idea about our workflow and priorities:

- [Maintenance status](https://github.com/bit-team/backintime#maintenance-status)
- [The team](https://github.com/bit-team/backintime#the-team)
- [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline)

Best regards,
Christian

**Comment by s4moore** [comment]
Hello, I am searching for my first issue and came across this.

If I understand the problem correctly, couldn't this be achieved by simply changing common/snapshots.py 828 > 829 from:
```
message = (
    _("Can't find snapshots directory.\n"
```
to:
```
message = (
    _(f"Can't find snapshots directory '{self.snapshotsFullPath(profile_id)}'.\n"
```

**Comment by buhtz** [comment]
Hello Samuel,
yes, you are right. Would you like to jump in and provide a PR?

I would suggest a minor modification to your solution because our translators might not understand that string (see our [doc about translatable strings](https://github.com/bit-team/backintime/blob/dev/doc/maintain/2_localization.md#instructions-for-the-translation-process)):

    message = (
    _(f"Can't find snapshots directory '{path}'.\n")
    .format(path=self.snapshotsFullPath(profile_id)

We can work further on this if you open a PR.

Thanks in advance,
Christian

**Comment by s4moore** [comment]
Thank you, I have submitted a PR (#1975)

**Comment by vinothk-master** [comment]
Hi @buhtz 
Is this issue fixed or can I work on this please?
Thanks
Vinoth Kannan

**Comment by buhtz** [comment]
Hello vinothk-master,
thank you for your message and offer to work on this. As mentioned in the [previous comment](https://github.com/bit-team/backintime/issues/1941#issuecomment-2558096005) there is a PR (PullRequest) with number #1975 open for this issue. So there is someone who is working on this.

But there are several other opportunities to help with. You can [improve the translation](https://translate.codeberg.org/engage/backintime/) for example. You can offer your [feedback about the re-design of the auto-remove dialog](https://github.com/bit-team/backintime/issues/1976). Or just have a look into all the other issues. You also might want to look into our user manual and give us your idea how it should look like.

Don't hesitate to ask back.

Regards,
Christian
