### ISSUE TITLE
Keyboard shortcut to close window

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1949]
Gnome uses `Ctrl +W` to close Window (Firefox and vscode use it to close tab), may be use this close **snapshot log window**, and other windows.

May be use `Ctrl+q` to close backintime window.

**Comment by buhtz** [comment]
Hello Lamyergeier,
thank your for your question.

I don't understand the problem. Please describe it in more details.

As on most Windows and GNU/Linux systems you can use ALT+F4 to close an application.
You can also use ALT+F4 or ESC to close sub-windows but not the application.

Things like this are usually configured in the window manager or desktop environment.

Regards,
Christian
