### ISSUE TITLE
File Toolbar: let user type the path, or copy/paste it there

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1951]
![image](https://github.com/user-attachments/assets/a8b6041e-d5c1-423a-8d73-3afe85bd949b)

In the **File Toolbar** as above, let user type the path, or copy/paste it there.

**Comment by buhtz** [comment]
Hello Lamyergeier,
thank you for the report. We appreciate it.

My apologize but I don't understand your report. Please give me more details.
What is the problem?
What is the current behavior of BIT?
What is the behavior or feature of BIT you expect?
Describe your use case or workflow in more details please.
Which problem do you want to solve with a new feature?

Regards,
Christian

**Comment by lamyergeier** [comment]
What is the problem? Unable to type or paste in file browser
What is the behavior or feature of BIT you expect? Let user type it with keyboard

**Comment by buhtz** [comment]
Again it is very hard to understand you. I can just guess.

You want to have the path-field in the main window editable?

![image](https://github.com/user-attachments/assets/8cf5ff74-c52f-4944-8404-cb0b26def375)

**Comment by lamyergeier** [comment]
Yes, I would like to have the path field editable so that its quicker than choosing a long path with several mouse clicks.

**Comment by buhtz** [comment]
Hello lamyergeier,
the idea is not bad.
But it needs new code and refactoring old code. User input need to be validated etc pp This is much effort for less benefit.
I don't see resources to implement and maintain this.

If you don't have nothing else to add I'll close the issue soon.

Thanks in advance,
Christian
