### ISSUE TITLE
Deprecate cron and use systemd timer or at least give the option of a timer

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#1978]
Have you considered eventually deprecating cron in favor of a systemd user timer or at least allowing the option to use one?  Rationale is that every major distro has switched to systemd and thus has this ability without an added dependency.

Below are example service and timer units.  The GUI would have to adjust the timer settings but just to be illustrative, I used once daily.

1. Place both in `~/.config/systemd/user/`
2. Run `systemctl --user daemon-reload`
3. Run `systemctl --user enable backintime-backup-job.timer`
4. Run `systemctl --user start backintime-backup-job.timer`

You can query the status with `systemctl --user list-timers`
Example:
```
% systemctl --user list-timers                       
NEXT                         LEFT LAST PASSED UNIT                        ACTIVATES                    
Thu 2024-12-26 05:53:40 EST 36min -         - psd-resync.timer            psd-resync.service

1 timer listed.
Pass --all to see loaded but inactive timers, too.
```

```
% cat ~/.config/systemd/user/backintime-backup-job.service
[Unit]
Description=Run backintime snapshot generation

[Service]
Type=oneshot
ExecStart=/usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job
```

And

```
% cat ~/.config/systemd/user/backintime-backup-job.timer  
[Unit]
Description=Start a backintime snapshot once daily

[Timer]
OnCalendar=daily
AccuracySec=1m
Persistent=true

[Install]
WantedBy=timers.target
```

**Comment by buhtz** [comment]
Hello Graysky

> Have you considered eventually deprecating cron in favor of a systemd user timer or at least allowing the option to use one?

Yes. Answer is no. See #669.

> Rationale is that every major distro has switched to systemd and thus has this ability without an added dependency.

I don't see that way. "Mayjor" is Debian and Arch. There are several non-systemd distros.
Dependency is not the point. BIT will depend on cron or systemd. Nothing change.

Again, what is the advantage of using systemd-timer? I don't see one. Just because it is there?
Cron is supported (or simulated) by all GNU/Linux systems. Systemd is not.

Every user is free to use his own schedule system with BIT.

Regards,
Christian

**Comment by graysky2** [comment]
The only advantage I see is one less dependency but I understand your rationale.  Perhaps you can consider providing these with a disclaimer of unsupported or user contributed with a little documentation pointing users to them as an option.

**Comment by buhtz** [comment]
If you want you can provide your example about how to use BIT with systemd for our FAQ.md file. I might integrate that later into the user manual.

**Comment by graysky2** [comment]
I will send a PR
