### ISSUE TITLE
Can't backup to same area with different user

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#2]
Back In Time 0.9.99.37 Ubuntu 10.04

If you backup to an area as one user, and then try to backup to the same area as another user it fails.

Login as User1
Set Where to save snapshots: /var/tmp
Take backup
Login as User2
Set Where to save snapshots also to: /var/tmp
Take backup
Backup fails with permission denied/unable to write to backup area since /var/tmp/backintime and /var/tmp/backintime/machinename are owned by User1

If its supposed to be this way then no problem as its easy to workaround, and its not clear any of the alternatives are any better.  Its not actually a problem I have, just something I noticed.  As you've considered all of this when creating profiles I was wondering what your thoughts were?

Current backup path:
   SNAPSHOTLOCATION/ - unknown writable (presumably at least user writable if not world writable)
      backintime/ - user writable
         MACHINE/ - user writable
             USER/ - user writable
                 PROFILE# - user writable

Issue:
Once one user uses the location, they have sole write permissions to the area (they can use different machines in the area, but other users can't use the area even on the same machine)

Option 1:
Issue can be avoided if users specify a different Where to save Snapshot directory/subdirectory (e.g. /var/tmp/myuserbackups)
But this means you are specifying user directory twice (not a bit deal, but then why have USER subdirectory)
    SNAPSHOTLOCATION-PER-USER/backintime/MACHINE/USER/PROFILE#

Option 2:
Change permissions on top levels to allow write access:
     SNAPSHOTLOCATION/ - unknown writable
          backintime/ - world writable (to allow other users to backup other machines)
               MACHINE/ - world writable (to allow other users to backup on this machine)
                    USER/ - user writable
                          PROFILE# - user writable
But this means another user can rename the MACHINE directory (or even backintime directory) to another name to 'hide' it from the other users, even if they can't delete the directory (since its contents can't be deleted)

Option 3:
Change the order of the backup path to per user only:
    SNAPSHOTLOCATION/ - unknown writable
        backintime - world writable
            USER - user writable
                MACHINE - user writable
                      PROFILE# - user writable
But you still have the issue with backintime being world writable
Although you could make the argument that SNAPSHOTLOCATION has that issue as well so it doesn't matter

Option 4:
Change to user at top level:
    SNAPSHOTLOCATION/
         USER   - user writable
               MACHINE - user writable
                     PROFILE# - user writable
or to make it more specific to backintime:
    SNAPSHOTLOCATION/
         backintime-USER   - user writable
               MACHINE - user writable
                     PROFILE# - user writable

or the same as now, or something else...

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2010-06-01T17:20:46Z
 * owner: dave2010
 * the launchpad url was https://bugs.launchpad.net/bugs/588393

**Comment by Germar** [comment]
(by danleweb)
This is not the way it should work. "backintime/host" should be available to everybody. "backintime/host/user" should be seen only by user. This is a huge bug.

**Comment by dinoboy197** [comment]
test comment 2

**Comment by dinoboy197** [comment]
Ack, sorry for incorrectly placed comment.
