### ISSUE TITLE
Button to return profile settings to defaults

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#204]
It would be good if it was possible to restore default values with one push on a button (and a question afterwards), especially for the excluded folders and patterns

---

Imported from Launchpad using lp2gh.
- date created: 2009-11-10T20:52:43Z
- owner: bratdaking
- the launchpad url was https://bugs.launchpad.net/bugs/480272

**Comment by buhtz** [comment]
It seems that no one else asked for a feature like this. Because of that I would like to close the Issue. "Nice to have" is not good enough to invest resources into it.

**Comment by emtiu** [comment]
I agree. The same effect can be achieved by creating a new profile.
