### ISSUE TITLE
Web interface for bit

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#209]
I would like to see an optional web interface to BIT that allowed browsing of the snapshots, and the copy function (but not restore).  I would want this to be secured in some way.  Here is a scenario where this would be useful (and how I would use it):

Network share running on Server A
--> Share is used by Active Directory users on Windows computers

BIT running on Ubuntu on Server B
--> BIT server is bound to Active Directory
--> BIT web interface is secured and requires either local or domain credentials to log in.  (not just any user should be able to log in though, only specified users / groups.
------> Once logged in, an end user can look at the contents of a snapshot and retrieve items from it.  Restores would have to be done from the server or by "administrative" login to the web interface.

I know this is asking a lot, but I wanted to put it out there.  Thanks for an already nice product!

---

Imported from Launchpad using lp2gh.
- date created: 2009-12-02T23:09:18Z
- owner: bratdaking
- the launchpad url was https://bugs.launchpad.net/bugs/491645

**Comment by Germar** [comment]
(by sammcj)
A web interface to BIT would be amazing!

**Comment by buhtz** [comment]
It is quite old. No fresh wishes. ;)

Usefull in some cases maybe. But complex and binding ressources we don't have. This is a far away (means impossible) feature. And it opens several security issues. We should need an expert here.

I would recommend to close.

**Comment by emtiu** [comment]
I agree that this is out of scope, but we may keep the Issue as a reminder.

**Comment by buhtz** [comment]
After working with BITs code base for some months I don't see how to implement this.
I even don't see a use case.

A textual user interface would be much better and would solve the use case running BIT on a headless server.

I vote for close.

**Comment by Germar** [comment]
It is possible to implement. But it's quite a lot work!

**Comment by aryoda** [comment]
https://www.djangoproject.com/ ;-)

But first we need to better separate the GUI from the view models and controllers and add unit tests for that,
so far far future (or a new contributor suddenly appears ;-)

**Comment by buhtz** [comment]
Django is box of pandora. In context of BIT is like using a lear jet to go out and buy buns. 😄 

What is a use case for such a web-dingsbums?

Just login via SSH and start the TUI. We need a TUI much more then a web-interface. A TUI is easier to isolate, test and maintain.

**Comment by emtiu** [comment]
> Just login via SSH and start the TUI. We need a TUI much more then a web-interface. A TUI is easier to isolate, test and maintain.

Many people have centered their workflow around web interfaces (which are better for graphs, for example). It's just a matter of personal preference.

But we should focus on what BackInTime can do, and in that respect I agree with @aryoda that it's a far-future idea at best.

**Comment by buhtz** [comment]
❤️ OK guys. But I assume there are technically better (easier) webservice options then Django.

**Comment by buhtz** [comment]
Now after working round about 2 years at BIT taking our resources and problems into account I vote to close this issue. I don't see when and how this ever will be implemented by us. And technically I also don't think it is a good idea to implement it using this repo. Such a web interface could be a good separate project just using the `backintime` CLI.
I would say we support every external project trying to implement a web interface for BIT but we won't do and maintain it in our own repo.

Personally I would prioritize a TUI interface for BIT instead of a web front end. With a TUI you can SSH into your server and do your thing.

I vote to close because of this.

**Comment by emtiu** [comment]
I agree with this assessment.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
