### ISSUE TITLE
Optional disable of versioning for files above a certain size

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#210]
Hi and thanks for this great piece of software.

What I miss in BackInTime is the possibility to disable the versioning system for files with a size higher than a set limit.
Let's say, every files > 500MB are only stored in the last snapshot, and are deleted from the former ones.
Because there are some big files I want to backup, but my hard-drive is too small to afford storing multiple versions of those big files.
## Best regards and thanks again.

Renaud

---

Imported from Launchpad using lp2gh.
- date created: 2009-12-03T20:57:57Z
- owner: bratdaking
- the launchpad url was https://bugs.launchpad.net/bugs/492090

**Comment by buhtz** [comment]
IMHO implementing something like this would open the box of pandora. This is against the nature of rsync and its hard link feature. You have to implement exceptional algorithms and workarounds to realize this.

I vote for close.

**Comment by Germar** [comment]
Exactly
