### ISSUE TITLE
[enhancement] search

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#211]
it would be useful to be able to search one or more selected snapshots for particular files or patterns.

---

Imported from Launchpad using lp2gh.
- date created: 2009-12-05T04:17:53Z
- owner: knubee
- the launchpad url was https://bugs.launchpad.net/bugs/492730

**Comment by Germar** [comment]
(by danleweb)
You can use BIT to find all snapshots that contains a file. To search for patterns there are better tools (gnome, catfish). BIT snapshots can be explored with your preferred file explorer.

**Comment by guzziopa** [comment]
On cmdline i use updatedb & mlocate

**Comment by emtiu** [comment]
Closing as duplicate of #842.
