### ISSUE TITLE
Wish: Progress report when deleting a snapshot

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#237]
Using Back In Time 1.0.8. My initial snapshot is 58GB. Deltas are between 16 and 19GB. My external SATA drive had insufficient disk space to store a new backup, so I went to delete some of my previous snapshots (a couple of the deltas).

When I delete a snapshot, nothing _appears_ to happen. Back In TIme simply becomes unresponsive for a few minutes. Eventually, the snapshot disappears from the "Snapshots" list and Back In Time is responsive again. Some kind of dialog that announces that Back In Time is busy doing the task would be nice. Apparently-freezing is kind of scary to the end user. :)

---

Imported from Launchpad using lp2gh.
- date created: 2012-04-30T15:42:58Z
- owner: nbs
- the launchpad url was https://bugs.launchpad.net/bugs/992026

**Comment by Germar** [comment]
(by catalin-hritcu)
Not sure if this is the same problem but when I tried deleting a (failed but almost complete) snapshot backintime froze for a really long time eating up all of my RAM (16GB!) and bringing my whole machine to a near halt. I needed to start a terminal (where I was getting 1s delay typing characters) to manually kill the 4 backintime processes. Afterwards it seems that the snapshot wasn't really removed at all. I'll have to do it manually.

**Comment by Germar** [comment]
(by catalin-hritcu)
Forgot to mention, but I'm using backintime 1.0.34 on Linux Arch. My laptop has an SSD and I do backups on an external HDD.

**Comment by Germar** [comment]
(by catalin-hritcu)
Removing the snapshot manually worked just fine:
[root@detained 1]# time rm -dfr 20140614-151820-891
rm -dfr 20140614-151820-891  0.36s user 12.76s system 2% cpu 7:32.88 total
[root@detained 1]#

**Comment by Germar** [comment]
(by germar)
This bug report is a wish to have a progress during deleting.

If BIT really consumes all your RAM this is a serious bug that should have it's own report.

BIT uses this commands to remove snapshots:
find "/path/to/backintime/host/user/profile_id/snapshot_id" -type d -exec chmod u+wx "{}" +
rm -rf "/path/to/backintime/host/user/profile_id/snapshot_id"

Can you please test again (especially the find command) if that eat up your RAM? If it does please open a new bug for this.

**Comment by Germar** [comment]
(by germar)
The find command is wrapped. The command starts with find and ends with +

**Comment by Germar** [comment]
(by catalin-hritcu)
Thanks for the quick answer, Germar. I've made the name of this issue of this issue more explicit, and created a new one for my problem: https://bugs.launchpad.net/backintime/+bug/1332969
More details about running the find command there (short summary: it didn't eat up all memory).

**Comment by buhtz** [comment]
Just a notice: The Launchpad-Bug 1332969 about RAM-usage is closed.

**Comment by emtiu** [comment]
Closing in favor of #1264.
