### ISSUE TITLE
[Enhancement] Size column doesn't give size

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#251]
Currently the size column doesn't actually give DIRECTORY sizes, it gives a count of items.  While the count is nice to have, I'd really like to see directory sizes, so as to be able to determine what size backup device I'll need (and be able to adjust my choices to fit on the device I have available).  Just like CD burning programs do for example.  

So in that the count is nice I'd like to see an additional column for number of items, and the size column to actually reflect the size.  In addition, 

In addition, I'd like to see an option (3 way toggle? all/included/excluded) to include or exclude those items actually included or excluded for backup.

This would probably eliminate the need for a "dry run", as requested by someone else.

Thanks for a great program!

---

Imported from Launchpad using lp2gh.
- date created: 2014-06-05T03:08:47Z
- owner: publicface
- the launchpad url was https://bugs.launchpad.net/bugs/1326616

**Comment by emtiu** [comment]
Closing as out of scope, external tools (such as ncdu or k4dirstat) are much better suited for inspecting your existing data than backintime's "Now" view. The suggestion to highlight included/excluded files in the file viewer is kept in #734.
