### ISSUE TITLE
Duplicate/migrate exclude list into another profile

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#255]
I'm trying to copy an extensive EXCLUDE list (approx. 50 lines) to paste in a different profile.

First       Ctrl+A    appears to work correctly, selecting all entries in the EXCLUDE window.  

Then      Ctrl+C    

then in another profile     Ctrl+V    does not appear to do anything.

and      Ctrl+V    in a text editor (gedit) pastes one item .... apparently at random

Linux Mint 17.1 / Cinnamon
BackInTime V1.1.2

---

Imported from Launchpad using lp2gh.
- date created: 2015-03-15T03:26:49Z
- owner: johnb0647
- the launchpad url was https://bugs.launchpad.net/bugs/1432286

**Comment by Germar** [comment]
(by germar)
Copy/paste is not supported (yet). I'll add this to wishlist.

For now you can close BIT, open ~/.config/backintime/config in your favourite editor and copy/paste all profile1.snapshots.exclude.* values. Finally do a find/replace for profile1 into profile2 for this lines

**Comment by Germar** [comment]
(by johnb0647)
Thank you, sir.  This will do just fine.

John Buczek
Balay Thimuai, Liptong
Valencia 6215
Philippines


On Monday, 16 March, 2015 09:50 PM, Germar wrote:
> Copy/paste is not supported (yet). I'll add this to wishlist.
>
> For now you can close BIT, open ~/.config/backintime/config in your
> favourite editor and copy/paste all profile1.snapshots.exclude.* values.
> Finally do a find/replace for profile1 into profile2 for this lines
>
> ** Changed in: backintime
>     Importance: Undecided => Wishlist
>
> ** Changed in: backintime
>         Status: New => Confirmed
>


-- 
PLEASE UPDATE YOUR ADDRESS BOOK.
MY OLD eMAIL ADDRESS [*<email address hidden> * ] IS BEING CANCELLED!

My permanent addr: *<email address hidden>*

**Comment by buhtz** [comment]
Regarding our priorities and resources I vote to close because it is a rare case and it seems no one else asked for it.
Just edit the config file in a text editor of your choice.

Maybe someone want to jump in? I would prefer a solution different from copy and paste. I would offer a button like "Import list from another profile".

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen
if the problem still exists. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
Christian
