### ISSUE TITLE
when "create hard-links" begin, mount.ntfs consumes all the CPU

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#337]
When doing a snapshot everything seems to be going fine while using rsync. Although when backintime begins the creation of hard-links mount.ntfs takes all the CPU and doesn't seem to accomplish anything. I'm using an external usb drive that worked before with backintime.

More details:
the folder new_snapshot is created.
the read/write functions are fully operational for my external drive

kind regards

---

Imported from Launchpad using lp2gh.
- date created: 2010-10-19T07:20:43Z
- owner: goncalobernardo
- the launchpad url was https://bugs.launchpad.net/bugs/663123

**Comment by Germar** [comment]
(by danleweb)
Maybe there is something related to ntfs. I don't recommend it. I recommend a linux fs (ex: ext3/4).
Hard-links are created with "cp" command.

**Comment by Germar** [comment]
(by eljo)
This bug also affects me since 08/01/2011 (last backup)
"Create hard-links" do not terminate ; "cp -aRI <source> <destination>" is wait-answer-interruptible.
Same configuration : external usb drive formatted in ntfs
ubuntu 10.10 ; back in time 0.9.6 and 1.0.6

Thanks for your work
Joël

**Comment by Germar** [comment]
(by danleweb)
Can you please run it from command line ("backintime --backup") and check the output. Hopefully there will be something useful.
BIT use rsync to take the snapshot. If rsync blocks ... I'm not sure how to investigate it.

Regards,
Dan

**Comment by Germar** [comment]
(by eljo)
I confirm my problem was related to ntfs.
chkdsd /f and two boots later, there is no more problem.
I am going to consider using ext3...

Thanks for your time,
Joël

**Comment by Germar** [comment]
(by marja-e)
I think I have been having the same problem, but the system monitor reports that backintime is doing nothing... and then some hours into "create hard-links" everything crashes, the system monitor crashes, the desktop crashes, etc. I was unable to chkdsk and the disk utility claims the disk was clean.

**Comment by emtiu** [comment]
Closing as outdated, though related to #635.
