### ISSUE TITLE
Copy failed due to permissions

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#343]
Permissions for files are too restrictive, when stored in backup directory (external ext4 formatted drive).
Copy Dialog and Drag & Drop in Back in Time failes because of missing read Permissions.
I don`t know, if I`ve messed up file restirctions myself, or if this was done by Back in Time.
Thanks for your work!

Greetings

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-13T20:29:59Z
- owner: taltos
- the launchpad url was https://bugs.launchpad.net/bugs/689850

**Comment by Germar** [comment]
(by danleweb)
Dyid you backup them as another user ? (root for example) and you try to restore / copy as regular user ?

Regards,
Dan

**Comment by Germar** [comment]
(by taltos)
No, I only use Back in Time as root.
Restore works perfectly, but copy e.g to the Desktop for just checking one backed up file, fails.

**Comment by Germar** [comment]
(by danleweb)
Actually the "Copy" is not a good idea since it just copy the file as is stored on snapshot partition (read-only and maybe sans real user/group).
The restore copy the file and set the real rights/user/group from a special file.
There must a "restore to" that replace copy.

Regards,
Dan

**Comment by emtiu** [comment]
Closing as outdated.
