### ISSUE TITLE
backintime-kde4 fails to start in SLED 11 SP1

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#351]
On a new install of SLED 11 SP1 running KDE4, I downloaded and compiled the 1.0.6 version of backintime from the the tar.gz source.
I first tried to start backintime from the icon, but that did not work, or provide any information.
I then tried to start backintime-kde4 from a shell:

backintime-kde4
Traceback (most recent call last):
  File "/usr/share/backintime/kde4/app.py", line 43, in <module>
    from PyKDE4.kdecore import *
ImportError: No module named PyKDE4.kdecore

---

Imported from Launchpad using lp2gh.
- date created: 2011-02-09T18:15:45Z
- owner: grimes-mark
- the launchpad url was https://bugs.launchpad.net/bugs/715945

**Comment by Germar** [comment]
(by danleweb)
If you install it manually you have to install some packages manually: python, cron, rsync, x11-utils, python-glade2, python-gnome2, python-notify, meld, gksu.
I don't know the names for this packages in your distributions.

Regards,
Dan

**Comment by emtiu** [comment]
Closing as outdated.
