### ISSUE TITLE
Menu item should be in System>administration

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#355]
The Back in Time and the Back in Time (root) are located in the  applications menu by default, but they are administrative tools and therefore I think should be moved to the System > Administration menu by default, it would make more sense.

---

Imported from Launchpad using lp2gh.
- date created: 2011-03-12T09:10:24Z
- owner: josefsson-martin
- the launchpad url was https://bugs.launchpad.net/bugs/733733

**Comment by emtiu** [comment]
This should be the case in most Desktop Environments by now, as the `.desktop` file contains `Categories=System`:
https://github.com/bit-team/backintime/blob/9310acc30362907c7d14f3c8c31a0e4a366d44f5/qt/backintime-qt.desktop#L10
