### ISSUE TITLE
Back in Time (root) - doesn't complete snaphot

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#356]
When launching from the shortcut on the menu labelled "Back in Time (root)" on Debian I can run a backup operation to take a snapshot. It goes through the motions and seems to be writing to the target folder. However at the end of the operation it says "Failed to take snapshot" and the target folder is now empty.

When I launch from the command using the command "sudo backintime-gnome" it runs successfully.

---

Imported from Launchpad using lp2gh.
- date created: 2011-03-29T12:03:33Z
- owner: simon-sleaford
- the launchpad url was https://bugs.launchpad.net/bugs/744907

**Comment by emtiu** [comment]
Closing as outdated.
