### ISSUE TITLE
rsync can't create directory

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#362]
Ubuntu 11.04
Fresh install with back-in-time 1.0.6
## WARNING: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/mnt/Backup" --exclude="/home/mbecker/.local/share/backintime" --include="/home/mbecker/" --include="/home/" --include="/data/Workspaces/" --include="/data/" --exclude=".gvfs" --exclude=".cache_" --exclude="[Cc]ache_" --exclude=".thumbnails_" --exclude="[Tt]rash_" --exclude="_.backup_" --exclude="_~" --exclude="/home/mbecker/Ubuntu One" --exclude=".dropbox_" --exclude="/home/mbecker/Musik" --exclude="/home/mbecker/Bilder/SmartStor" --exclude="/home/mbecker/Videos" --include="/home/mbecker/**" --include="/data/Workspaces/**" --exclude="*" / "/mnt/Backup/backintime/producer01/mbecker/1/new_snapshot/backup/" 2>&1" returns 5888

I've seen another bug (#362223) that describes the situation. There it's said, that it is fixed in 0.9.22. I didn't know if I should reopen that ticket or make a new one.

---

Imported from Launchpad using lp2gh.
- date created: 2011-05-02T03:22:34Z
- owner: m-becker
- the launchpad url was https://bugs.launchpad.net/bugs/775306

**Comment by Germar** [comment]
(by m-becker)
I executed the rsync command. mkdir only fails for back-in-time as root. As my user I can execute the command and everything is transfered.

**Comment by emtiu** [comment]
Closing as outdated.
