### ISSUE TITLE
Folder selection dialog slow in KDE 4

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#375]
When I want to create a new profile and select folder to save the snapshots, the folder viewer in KDE is extremely slow (we're talking minutes of waiting time here, on local disks without a large amount of content). Unsure if this is an upstream bug, e.g. this: https://bugs.kde.org/show_bug.cgi?id=190343 

I am using KDE 4.6.5.

Anyway, if there would be a way around it, like if it perhaps could be possible to just write the folder path without opening the folder selection window, that would be very nice!

---

Imported from Launchpad using lp2gh.
- date created: 2011-07-19T08:17:50Z
- owner: ylevinsen
- the launchpad url was https://bugs.launchpad.net/bugs/812745

**Comment by emtiu** [comment]
Closing as outdated
