### ISSUE TITLE
backintime-gnome-1.0.6-2.fc14: __libc_message: Process /usr/bin/python was killed by signal 6 (SIGABRT)

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#389]
This bug was not found by me. It was reported by a Fedora user and is being passed upstream as advised by Dan.
Source (Fedora) bug: https://bugzilla.redhat.com/show_bug.cgi?id=706590
There is a backtrace attached to the Fedora bug.

"
architecture: x86_64
Attached file: backtrace, 77756 bytes
cmdline: python /usr/share/backintime/gnome/app.py
component: backintime
Attached file: coredump, 44429312 bytes
crash_function: __libc_message
executable: /usr/bin/python
kernel: 2.6.35.13-91.fc14.x86_64
package: backintime-gnome-1.0.6-2.fc14
rating: 4
reason: Process /usr/bin/python was killed by signal 6 (SIGABRT)
release: Fedora release 14 (Laughlin)
time: 1305973052
uid: 500
"

---

Imported from Launchpad using lp2gh.
- date created: 2011-10-09T20:20:34Z
- owner: tim-timj
- the launchpad url was https://bugs.launchpad.net/bugs/871464

**Comment by emtiu** [comment]
Closing as outdated.
