### ISSUE TITLE
directory not readable by user stops backup

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#411]
If you try to back up a directory that has no user read permission and the directory is owned by another user than the one running the backup (d-wxrwxrwx) the backup stops at that folder.

The backup destination is an NFS mounted partition with the following options:

/mnt/array/array_volume/Array 10.10.100.0/255.255.255.0(rw,anonuid=99,anongid=99,secure,root_squash,wdelay,sync)

On the local machine I am running back-in-time as the root user (all files in the backup become owned by user 99, group 99). This causes the folder to be unreadable in the backup location due to the "owner" not having permission to the directory. The source directory is readable because it isn't owned by the root user (that BIT is running as.)

---

Imported from Launchpad using lp2gh.
- date created: 2012-08-22T23:32:41Z
- owner: crwulff
- the launchpad url was https://bugs.launchpad.net/bugs/1040334

**Comment by Germar** [comment]
(by crwulff)
Back In Time v1.0.7

**Comment by buhtz** [comment]
Closing because of less information and outdated BIT version. But I contacted the original poster at Launchpad and ask him for feedback and encouraged him to re-open the Issue if needed.
