### ISSUE TITLE
backintime chokes on broken symlinks and sockets

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#416]
If backintime encounters a broken symlink or a socket, it produces an error and aborts the backup.
This happpens even if deselecting symlinks is selected, in the case of symlinks.
Selecting do not abort on errors does not help.
After encountering the error, a message says that the disk is full, which is not the case.
The source partition was only about 10% as large as the destination, and there was no apparent corruption on the target disk.  The files already copied were readable at destination.

A local USB drive was used.
/ was being backed up, with some directories like /tmp and /run excluded.
Symlinks were dereferenced (under advanced options), which worked well for those not corrupted.
Directories which were mount points for other partitions were copied empty, which was expected and desired behavior.
(If these directories were excluded, then restore could not have ensured that they were present for the system to function normally)

Backintime-gnome version 1.0.8 revision 1 on Mageia 2
Manual mode was used.
The backup seemed to progress normally (at least a few hundred files, if not thousands)
before encountering the errors.
After encountering the broken symlink error, I removed the symlink, and on subsequent tries the socket error was encountered.
Retrying produced the same error.

---

Imported from Launchpad using lp2gh.
- date created: 2012-11-20T08:24:10Z
- owner: andr55
- the launchpad url was https://bugs.launchpad.net/bugs/1081013

**Comment by emtiu** [comment]
Closing as outdated.
