### ISSUE TITLE
BIT freezes entire system GUI

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#448]
I have BIT setup to backup to rmeote ssh folder with encryption. I do not know if it is specific to those settings, but when I run backintime-gnome on a freshly booted system, the entire system GUI becomes completely frozen. I can switch to another TTY, but I can't do anything on the original tty1 with xorg.

However, if I run backintime-gnome from the terminal emulatur first, then it asks me (in the terminal only) for rsa password, and once given, GUI works fine even if I shut it down, and restart without terminal command. But only until next reboot.

bacintime 1.0.40
Arch linux
Openbox

---

Imported from Launchpad using lp2gh.
- date created: 2014-12-09T13:25:53Z
- owner: qwrules
- the launchpad url was https://bugs.launchpad.net/bugs/1400703

**Comment by Germar** [comment]
(by germar)
Sounds like there is a problem with gnome-keyring. Please disable the use of keyring with following command and try again:

sed -e "s/.password.save=true/.password.save=false/g" \
        -e "s/.password.use_cache=true/.password.use_cache=false/g" \
        -i ~/.config/backintime/config

If this fixed the problem you should try to reinstall python2-keyring and python2-secretstorage

**Comment by Germar** [comment]
(by qwrules)
I did that, and this time I got a GUI box asking for SSH password, which I gave. Then another GUI box appeared asking for Encryption password. I typed it in, hit OK, and the entire system GUI froze.

I had to switch to another tty to reboot the system from command line.

**Comment by Germar** [comment]
(by germar)
Hmm. Please run 'backintime-gnome 2>&1 >~/backintime.log' and post backintime.log

Also please rename ~/.config/backintime/config and create a new profile with local snapshots so we can see if this is related to ssh/encfs or if it is a general problem.

**Comment by Germar** [comment]
(by germar)
Oh, I forgot to mention that you should run 'backintime-gnome 2>&1 >~/backintime.log' after reboot so we could see the output during freeze

**Comment by Germar** [comment]
(by qwrules)
The problem does not happen for local snapshots, whether they are encrypted or not.

Running backintime-gnome 2>&1 >~/backintime.log is pointless because then the system will not freeze cause it will ask me inside terminal for
"Enter passphrase for key '/home/juha/.ssh/id_dsa': "

The whole point is that it crashes when it is NOT run from terminal. If I run the same command from runbox (like Synapse), then the system crashes as usual but the backintime.log remains empty.

**Comment by Germar** [comment]
(by germar)
Okay, sorry. I didn't recognize that. 

Please change the last line in /usr/bin/backintime-gnome to:

ssh-agent python ${APP_PATH}/app.py "$@" 2>&1 >~/backintime.log

**Comment by Germar** [comment]
(by germar)
And sorry for the late answer. I'm quite busy these days.

**Comment by Germar** [comment]
(by qwrules)
The ~/backintime.log file is being created, but remains empty.

**Comment by Germar** [comment]
(by qwrules)
Also, GUI does not freeze if the remote SSH host is offline and BIT can't connect to it.

**Comment by Germar** [comment]
(by germar)
Without any log this is just shooting into blue. Lets try to deactivate some steps on the mountprocess and see if it makes BIT to stop freezing.

Please add a line 'return True' after 'def pre_mount_check(self, first_run = False):' in /usr/share/backintime/common/sshtools.py
It it's still freezing add 'return' after 'def _mount(self):' and try again

If one of these helped please add some (not very professional) debug symbols into the function that failed. Something like
with open('/home/USER/bit.log', 'w') as f:
     f.write('check_ping_host run successfully, trying next')

**Comment by emtiu** [comment]
Closing as outdated.
