### ISSUE TITLE
Log view window hangs when showing all the ouput

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#456]
I've just created a full snapshot, then clicked the “View snapshot log” button in KDE GUI. Then I selected “All” in the drop-down list, and the application got frozen for several minutes, eating the whole core of my CPU and a lot of memory. 

% ls /.../.../20150301-073230-553/ -lh 
total 11M
dr-xr-xr-x 4 1000 1000 4.0K Mar  1 06:19 backup
-r--r--r-- 1 1000 1000 3.3K Mar  1 08:35 config
-r--r--r-- 1 1000 1000    0 Mar  1 08:35 failed
-r--r--r-- 1 1000 1000 5.5M Mar  1 08:38 fileinfo.bz2
-r--r--r-- 1 1000 1000  143 Mar  1 08:38 info
-r--r--r-- 1 1000 1000 5.4M Mar  1 08:38 takesnapshot.log.bz2

Snapshot log is just 6 MB compressed and can be perfectly viewed without any lags using bzless.

Back In Time version: 1.0.36
Distribution: Fedora Linux 20

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-03-01T06:44:28Z
 * owner: firegurafiku
 * the launchpad url was https://bugs.launchpad.net/bugs/1426823

**Comment by Germar** [comment]
(by germar)
"just 6 MB" is HUGE!!! This could be easily couple hundred MB's uncompressed. bzless only reads the visible part of the file. That's why it is very fast. If you uncompress the file and show it e.g. with gedit it will lag the same.

**Comment by ronisbr** [comment]
I also seeing this behavior with big log files.
For example, if I try to open the log of two snapshots in which the .bz2 file has 853.4 KiB and 599.7 KiB (41.2 MiB and 27.3 MiB uncompressed), then the GUI just freezes. For smaller logs, like 9.1 KiB compressed, everything works fine.

**Comment by Germar** [comment]
I'm about to rewrite log for next version (already made some massive restructuring). I'll then try to make it work with huge log-files, too.
