### ISSUE TITLE
backintime fails when remote shell is fish

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#470]
Setting up a profile (backing up via ssh) fails when remote shell is fish.

backintime complains that cannot create remote folder. starting the backintime-qt4 from terminal I see the following error:

Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: d=0;test -e /data/marcoc/ || d=1;test $d -eq 1 && mkdir /data/marcoc/; err=$?;test $d -eq 1 && exit $err;test -d /data/marcoc/ || exit 11;test -w /data/marcoc/ || exit 12;test -x /data/marcoc/ || exit 13;exit 20

Thanks,
marco

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-10T07:46:57Z
 * owner: marcocamma
 * the launchpad url was https://bugs.launchpad.net/bugs/1494162

**Comment by Germar** [comment]
(by marcocamma)
One possible solution could be to add to the Popen.subprocess(....) call the argument: 
   executable='/bin/bash'

of course this could create problems if the path is different ...
so a possible solution could be to add in the advanced tab the path to the shell (by default /bin/bash).
hope it helps,
marco

**Comment by Germar** [comment]
(by germar)
No, subprocess.Popen(..., executeable='/bin/bash') doesn't help because it's the remote shell which is causing this troubles, not the local. I'm sorry to say, but you need to specify /bin/bash for the remote users shell in /etc/passwd. I'd use a separate user for BIT on remote so you can keep using fish for your daily work...

**Comment by buhtz** [comment]
Follow up #1905
