### ISSUE TITLE
Add Ability to interrupt snapshot

### ISSUE THREAD

**Issue by simonsmiley** [bit-team/backintime#474]
I started my intitial backup and realized it contained tons of files that I don't need a backup of.  
I could not find any way of stopping a snapshot other than killing the processes...

**Comment by Germar** [comment]
This is already reported in #195 but I'll keep this open because pause is more difficult to implement.

**Comment by norgoe** [comment]
I have not tried this myself, but I thought backintime is using rsync.
Pausing should be a matter of sendng a TSTP or STOP signal to rsync.
A CONT signal should resume the paused rsync.
And if this fails a second rsync call with --partial should continue the operation where it left when paused / aborted.

**Comment by Germar** [comment]
Jepp, thats right (except --partial, that would be needed in first run to prevent partial transferred files from being transferred again). But there are some steps that need to be done before I can implement this. For example BIT starts all processes with `os.system()` and has no control over it after launch. I need to change this to subprocess.Popen().

**Comment by Coshibu** [comment]
I second this. Would be great to have the option to just cancel a backup.

**Comment by caco3** [comment]
This is a feature I also miss.
Also, if you delete a backup, the GUI freezes for a while without showing any progress/status information.

**Comment by Germar** [comment]
GUI freeze is fixed in `1.1.10`

**Comment by simgunz** [comment]
Are there any progress on this feature? It happens so often that I need to stop a backup.

**Comment by Germar** [comment]
Jepp. I changed almost all external processes to `subprocess.Popen()`. So the basis for this feature is done.

**Comment by simgunz** [comment]
Good to hear that! Thanks for your work.

**Comment by caco3** [comment]
+1
@Germar: Thank you very much for your work!

**Comment by cpbl** [comment]
Are these also available in the qt4 app?
