### ISSUE TITLE
Too many hard links permanently break backup

### ISSUE THREAD

**Issue by michihenning** [bit-team/backintime#475]
I have a stress test for my code that, temporarily, creates 2000 hard links to a file in a single directory. Normally, the test cleans up when it finishes and removes the links again but, occasionally, the test directory with all the links gets left behind, for example, if a test crashes or is interrupted.

The problem is that this *permanently* and *silently* breaks my scheduled backups. The backups run from cron once an hour, but there is absolutely no indication that something is amiss. I only notice when I look at the backup history and see that nothing was backed up for a week or so.

When I run backintime manually, so I can see the console output, there are messages about too many hard links. Now, I understand that backintime can't do the impossible and create more links to a file than the file system allows. But the problem is that this appears to be a hard error that prevents *everything* from being backed up. Note that deleting the directory that contains all the links does *not* fix the problem. It appears that the error is caused by previously backed-up versions of that directory, even though, in the current version of the file system, the directory no longer exists.

I think it would be great to handle this error and, if there is a complaint about too many hard links, log the error but continue to back up everything else.

**Comment by Germar** [comment]
I'll have a look. Thanks

**Comment by Germar** [comment]
I wasn't able to reproduce this here. With `Full rsync mode` disabled `cp -aRl` will refuse to create more than 65000 hard links and return a nonzero exit code and with `Full rsync mode` enabled rsync will report it can't create more than 65000 hard links. But in both cases I got a new snapshot.

Can you please run `backintime backup --debug` in Terminal and post the output? Please use current stable version 1.1.8 from our repository ppa:bit-team/stable

**Comment by michihenning** [comment]
OK, I'll try and reproduce this on Monday and see if I can provide more detail. I'll also try with your ppa. My apologies for the initial lack of detail, I expected it to be easily reproducible.

**Comment by michihenning** [comment]
Sorry for the late reply, it's taken me a while to reproduce. All this is with version 1.0.36 for the moment.

So, I started out with a clean slate (empty backup disk). I then ran a few of the tests that create lots of links and killed them off so they'd leave their hard links behind. All up, there are six directories, each of which contains 1000 hard links to the same single file.

I then started taking snapshots from the GUI interface. They work fine. Taking more and more snapshots, I eventually hit this. (There are tons of lines like this):

equest-cancellation/build/tests/stress-test.gcjKuD/Pictures/590Photo-with-exif.jpg’ to ‘/media/Backup/backintime/djembefola/root/1/20151104-103026-573/backup/home/michi/src/thumbnailer/request-cancellation/build/tests/stress-test.gcjKuD/Pictures/590Photo-with-exif.jpg’: Too many links
cp: cannot create hard link ‘/media/Backup/backintime/djembefola/root/1/new_snapshot/backup/home/michi/src/thumbnailer/request-cancellation/build/tests/stress-test.gcjKuD/Pictures/478Photo-with-exif.jpg’ to ‘/media/Backup/backintime/djembefola/root/1/20151104-103026-573/backup/home/michi/src/thumbnailer/request-cancellation/build/tests/stress-test.gcjKuD/Pictures/478Photo-with-exif.jpg’: Too many links

So, it appears that the problem shows up once there are enough snapshots to push the link count over the limit.

But I no longer see the problem with nothing backing up. Despite the error message, the snapshot is taken successfully now :(

I'll keep an eye on the regular snapshots and check periodically whether the problem comes back.

**Comment by Germar** [comment]
There is nothing I can do about that error message and the limitation. I'll close this for now. If the problem comes back, please drop me a line

**Comment by michihenning** [comment]
So far, everything has been working fine again. My apologies for the noise. I'll shout if this comes back.

**Comment by Germar** [comment]
No worries :+1:
