### ISSUE TITLE
Status "speed" shows strange values

### ISSUE THREAD

**Issue by kmkom** [bit-team/backintime#476]
Backintime 1.1.8
Linux Mint 17.2 Cinnamon
The Drive is an external HD (ext4), connected via USB3.

The "speed-value" increases more and more during the backup!
![speed](https://cloud.githubusercontent.com/assets/15555865/10868558/bb2c2ed2-8091-11e5-8924-ee89f60b332d.png)

**Comment by Germar** [comment]
This is a bug in `rsync 3.1.0`. It is fixed in `3.1.1`. But even with that rsync version the progress bar is a bit wired. But there is nothing I can do from BIT side. Hopefully rsync will improve progress in next versions.

**Comment by kmkom** [comment]
Hello Germar,
thanks for the information and keep up the good work!

**Comment by kmkom** [comment]
Some time ago I installed Rsync version 3.1.1 from here: https://rsync.samba.org/
Now the speed value looks plausible.

**Comment by buhtz** [comment]
Recommend to close.
