### ISSUE TITLE
I cant seem to be able to create an encrypted local backup.

### ISSUE THREAD

**Issue by JeroenMathon** [bit-team/backintime#477]
I keep getting this error.
```
Can't mount 'encfs --extpass=backintime-askpass --standard /media/jeroen/KINGSTON/Backup /tmp/backintime/root/mnt/1074DCA6/mountpoint':

16:58:08 (FileUtils.cpp:368) fatal: config file specified by environment does not exist: /media/jeroen/KINGSTON/Backup/.encfs6.xml
```

**Comment by Germar** [comment]
Which encfs version do you use?

    encfs --version

**Comment by JeroenMathon** [comment]
This is my encfs verison
```
encfs version 1.8.1
```

**Comment by Germar** [comment]
encfs 1.8.1 changed behaviour on how it handles `ENCFS6_CONFIG` environ variable. I'll have a look how I can fix this in BIT.

For now please create encfs config manually:

    mkdir /tmp/mnt
    encfs --standard /media/jeroen/KINGSTON/Backup /tmp/mnt
    #provide a new password twice
    fusermount -u /tmp/mnt
    rmdir /tmp/mnt
