### ISSUE TITLE
Check for target filesystem capabilities (esp. hardlinks)

### ISSUE THREAD

**Issue by TLINDEN** [bit-team/backintime#478]
So I tried to setup BIT with a CIFS mounted drive (usb disk dos32 formatted, attached on a fritzbox). It works but always copies everything since hardlinks are not working (cp -aRl returns 256) on it. That's not BIT's fault of course but it would be better if it would check if the target directory supports hardlinks and  warn the user if it doesn't.

best,
Tom

PS: there's even a howto suggesting such a setup: https://wiki.ubuntuusers.de/Datensicherung_auf_NAS

**Comment by Germar** [comment]
I added some checks in 1.1.8 for FAT, CIFS and SSHFS mountpoints. A check for hard link support will follow :+1: 

That's not my suggestion :stuck_out_tongue_winking_eye: I'd rather use SSH mode. It's a lot faster! But I've no idea if it works with FritzBox.

**Comment by buhtz** [comment]
PR #1860 added a warning about NTFS volumes.

I think we can close this issue after 9 year. Thank you for contribution and participating to the discussions.
