### ISSUE TITLE
Add additional includes and immediately run new snapshot will remove new includes again

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#48]
If I set up a BackinTime back and use it a few times, am I able to add additional backup directories to the same setup.

Say, as root,  I set up to backup /home/xxx/World  & /home/xxx/France. At a later date, can I add /home/xxx/Scotland to the backup.
I seem to remember doing this is the past but it does not seem to work now. What happens is that BIT accepts the change and makes the backups but does not include the added directory. The orriginal backup directories continue to be backed up OK, only the new one is not added.  Is this the behaviour that I should expect?

I am running V1.0.34 on LinuxMint13 which is like Ubuntu Precise

I forgot to say how much I value BIT. It is one of the most useful pieces of software I have. It has saved me hours of time raking through backups to find a file I need. I have tested it as much as I can and I have never found as error, other that the possible one mentioned above. It is flexible and easy to move backups from one computer to another and one disk to another, once I had grasped how to do this from the terse but accurate documentation.

---

Imported from Launchpad using lp2gh.
- date created: 2014-12-15T23:37:42Z
- owner: germar
- assignee: germar
- the launchpad url was https://bugs.launchpad.net/bugs/1402867

**Comment by buhtz** [comment]
Is this still relevant? Hope not. ;)

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Because of age and my own experience I assume that is not longer relevant.
Could be closed.
