### ISSUE TITLE
Problems with ssh config

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#481]
Hey,
I'm trying to set up Backintime to use ssh mode, since I learned from other discussions that the 'local' Mode on an NFS mount is much less performant.

Im using Backintime as root.

so my config is the following:
<pre>
[my-client] ~ # pwd
/root
</pre>
<pre>
[my-client] ~ # tree -pufi .ssh/
.ssh
[-rw------- root    ]  .ssh/[id]_rsa
[-rw-r--r-- root    ]  .ssh/[id]_rsa.pub
[-rw-r--r-- root    ]  .ssh/known_hosts
</pre>
The remote is a QNAP NAS, which I configured according to this thread:
https://answers.launchpad.net/backintime/+question/238350

When I try to activate the ssh mode, I get the following error:
>Password-less authentication for backup@[my-local-ip] failed. Look at 'man backintime' for further instructions.

Nevertheless, using the terminal directly I am able to log-in password-less.

Any help would be highly appreciated!

**Comment by Germar** [comment]
You're using a non default file name for your ssh key. BIT can't find that automatically. Please add `/home/[user]/.ssh/[id]_rsa.pub` in `Settings > General > Private Key`

**Comment by kerner1000** [comment]
Thanks Germar, but I did that already.

**Comment by Germar** [comment]
Oh, you need to add the private key `/home/[user]/.ssh/[id]_rsa` and not the `.pub`. Sorry, my mistake.

This is the command which is used by BackInTime to check passwordless login. Please try it in Terminal
```
ssh -o PreferredAuthentications=publickey -p 22 -o ServerAliveInterval=240 -o IdentityFile=/home/[user]/.ssh/[id]_rsa backup@[my-local-ip] echo "Hello"
```

Oh, and during writing this I realized that you wrote `[my-local-ip]`. This is the IP of your QNAP, right??

**Comment by kerner1000** [comment]
Yes, <code>[my-local-ip]</code> means my NAS IP. 

I tried your test command on terminal, and I found the problem:
<code>@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
</code>

I removed the RSA key from <code>known_hosts</code> and then it worked! Many thanks so far!

Unfortunately, now I get the following error:

<code>
Can't mount sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[id]_rsa -o idmap=user backup@[my-local-ip]:/share/Backup /root/.local/share/backintime/mnt/DDB63517/mountpoint
</code>

**Comment by Germar** [comment]
Did you replace the QNAP sshd with OpenSSHd? Might be that the buildin sshd doesn't support sftp. Take a look at this [HOWTO](http://forum.qnap.com/viewtopic.php?f=11&t=70425)

**Comment by kerner1000** [comment]
Yes, I already did that.

**Comment by Germar** [comment]
There need to be a line like 
```
Subsystem sftp /usr/lib/openssh/sftp-server
```
in your `/etc/ssh/sshd_config` on the QNAP. And `/usr/lib/openssh/sftp-server` must be an executable.

Please run
```
mkdir ~/mnt
sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[id]_rsa -o idmap=user backup@[my-local-ip]:/share/Backup ~/mnt
```

**Comment by kerner1000** [comment]
<code>
grep server /opt/etc/openssh/sshd_config

\# This is the sshd server system-wide configuration file.  See

\# Lifetime and size of ephemeral version 1 server key

Subsystem	sftp	/opt/libexec/sftp-server

\#	ForceCommand cvs server
</code>

<code>
sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[id]_rsa -o idmap=user backup@[my-local-ip]:/share/Backup ~/mnt
backup@[my-local-ip]:/share/Backup: Not a directory
</code>

**Comment by Germar** [comment]
Hmm. `Not a directory` is strange because BIT should check this before trying to mount. Please make sure `/share/Backup` exist, is a directory and is read write and executable by user `backup` on the QNAP (maybe this is because uppercase `Backup`? Try again with `/share/backup`)

**Comment by kerner1000** [comment]
With lowercase it says 'Cannot create'. Maybe some file permissions more down in the directory tree? What need the permissions to be for lets say the whole path
<code>/share/Backup/backintime/..</code>

**Comment by Germar** [comment]
This should fix the permissions. Please run this on your QNAP via SSH
```
sudo chown backup /share/Backup
sudo chmod 755 /share/Backup
```

**Comment by kerner1000** [comment]
Didnt help..

**Comment by kerner1000** [comment]
<code>/share/Backup/</code>, not the tailing slash.
Thanks a lot!
Now its running!

**Comment by Germar** [comment]
Hmm seems the QNAP is a bit picky!? Never had problems without trailing slash before

I'm glad I could help

**Comment by kerner1000** [comment]
It was worth the pain, the performance is really much better! Its much much faster (matter of minutes compared to hours) and even better, it uses much less bandwidth! 
Thanks for your work Germar!
