### ISSUE TITLE
-y | --fuzzy rsync option

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#482]
Hey,
I'm frequently renaming/ reorganizing my files. Would it make sense to pass
<pre>-y | --fuzzy rsync option</pre> as an additional option to rsync? Or is it set per default already?
Best

**Comment by Germar** [comment]
`--fuzzy` only make sense if you rename files. If you rename a folder or move files in to other folders it wouldn't help. 

It's not set in BIT but starting with BIT 1.1.0 you can `Paste additional options to rsync` in `Expert options`

**Comment by kerner1000** [comment]
Thanks Germar for the explanations. I think I will give it a try; as I understand it, it does not come with any drawbacks.

**Comment by Germar** [comment]
It would take a bit longer, that's all.
