### ISSUE TITLE
Run a script just before a backup

### ISSUE THREAD

**Issue by Suor** [bit-team/backintime#484]
For example:
```bash
dpkg --get-selections > ~/Package.list
sudo cp -R /etc/apt/sources.list* ~/
sudo apt-key exportall > ~/Repo.keys
```

Maybe even adding this to settings as code not filename, for it to be saved in configuration.

**Comment by buhtz** [comment]
This is a FeauterRequest? Can please tell us about a little bit more details about it.
I can not see what are your needs.

Do you know the user-callback-mechanism in backintime? Please check the manpage of it for details. You can do your own stuff in this situations
 * Backup process begins
 * Backup process ends
 * New snapshot
 * Error
 * On (graphical) App start.
 * On (graphical) App close.
 * Mount all necessary drives. (_THIS is the time point you need._)
 * Unmount all drives

**Comment by Suor** [comment]
This look like what I need, thanks. I meant GUI for this though.

**Comment by Suor** [comment]
> I can not see what are your needs.
Currently I just want to save installed packages list. Previously I used correspinding feature in rsyncbackup to dump db to sql.

**Comment by buhtz** [comment]
A GUI for this is on my wishlist, too. ;)
Please feel free to contact me directly about the user-callback. I have some expirience with it.

**Comment by Germar** [comment]
Please take a look at [our shiny new FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection)
