### ISSUE TITLE
Last Log is truncated when plugging device upon notification

### ISSUE THREAD

**Issue by Suor** [bit-team/backintime#485]
If BackInTime wants to start a backup when target device is not connected it shows a notification: "Please plug the drive within 30 seconds". If you manage to do that, backup proceeds as normal. However if you later start an app and click "View Last Log" icon you get a truncated version of a log:

```
========== Take snapshot (profile 1): Sat Nov  7 22:45:01 2015 ==========

[E] Can't find snapshots folder.
If it is on a removable drive please plug it.
Waiting 30 seconds.
```
If you manually select last snapshot and click "View Snapshot Log" icon then you'll see full log though.

**Comment by Germar** [comment]
Did you switch `Filter` to e.g. `Information`? Default Filter is `Error` in `View Last Log` which will only show the above error message...

**Comment by Suor** [comment]
You are right, it's `Error` default filter in `View Last Log`, but `Changes` in `View Snapshot Log`.

This is confusing though.

**Comment by Germar** [comment]
You're right. I was also confused by this when I started using BIT. I'm just wondering what would be the best default. If I change default to `Changes` someone will never find `Error`. Maybe set default to `All`!?

**Comment by Suor** [comment]
Informations rarely needed during normal use. And they make reading changes hard. 

My solution replace dropdown with 3 checkboxes: "Errors", "Changes" and "Informations". Select first 2 by default.

**Comment by Suor** [comment]
Also, while we are here, 2 different dialogs for snapshot log and last snaphot log seem superfluos, the only difference is the presense of snapshots dropdown and title. So remove "Last Log View" dialog and just open "Snapshot Log View" with last snapshot selected.

You might also want to make this dialog wide by default, filepaths don't really fit now.

**Comment by Germar** [comment]
I'd rather add a new item `Errors + Changes` than using Checkboxes.

`Last Log View` shows the log from `~/.local/share/backintime/takesnapshot_X.log`. This is always the most recent log (e.g. when no new snapshot was created because nothing has changed)

`Snapshot Log View` is the log from selected snapshot `/path/to/backintime/host/user/profileid/snapshotid/takesnapshot.log.bz2`

**Comment by Suor** [comment]
Checkboxes are superior from UX perspective fot these reasons:

1. They are all immediately visible, no need to click to see options.
2. They are more then just text, I probably woudl have noticed checkbox graphic placed differently in different dialogs and the original issue would not appear.
3. They are more declarative. It's obvious that these are all options and they are mutually exclusive.
4. They are faster to click through, this is the consequence of immediate visibility. No pause to review the UI change when dropdown appears.

**Comment by Suor** [comment]
Also what about making log dialogs wider by default?

**Comment by Germar** [comment]
But checkboxes take a lot more space. I prefer the combobox.

New default size is 800x500 in respect of small screens. But logviewdialog will now store your size and remember next time.

**Comment by Suor** [comment]
> But checkboxes take a lot more space. I prefer the combobox.

Not really a lot. You can remove `Filter` label, you already have `Errors + Changes` item, which has sum of the lengths. `Snapshots` label could (and probably should) be renamed to `Snapshot`. Plus 800px is not really some popular screen resolution so window could be widen a bit if it still doesn't fit.

> But logviewdialog will now store your size and remember next time.

Nice touch.
