### ISSUE TITLE
UI blocked/greyed out while removing snapshot

### ISSUE THREAD

**Issue by Suor** [bit-team/backintime#487]
If it takes long enough to remove snapshot UI becomes grey and unresponsive. Ideally you would remove snapshot from UI instantly and then delete files in a background thread.

BTW I am not stopping here ) You might want to add `ux` label.

**Comment by Germar** [comment]
What does `ux` stand for?

**Comment by Suor** [comment]
User eXperience. When UI works but could be made better, more convenient.

**Comment by Germar** [comment]
Thanks for explanations. And keep creating issues :)
