### ISSUE TITLE
Can I backup multiple PCs to same directory on a server

### ISSUE THREAD

**Issue by colinl** [bit-team/backintime#495]
A Question.  I notice that the directory hierarchy in the backup destination starts with the PC host name.  Does that mean that I can backup from multiple PCs to the same directory on a central server without BIT becoming confused?

**Comment by Germar** [comment]
Yes, that's the reason for that hierarchy ;-)
You can simultaneous take snapshots with different hosts, users and even profiles (on one host with the same user). But for sure this will slow down the whole process.

**Comment by colinl** [comment]
Great, thanks.  I guessed that was the case but could not find anything confirming that was possible.
