### ISSUE TITLE
Wishlist: mark directories for only keep latest version

### ISSUE THREAD

**Issue by Tyrsen** [bit-team/backintime#498]
This is a problem which currently I have to manually go through and solve after every single single backup I take, so I am writing here in the hopes that it can be addressed.

I would like to have another tab added to the 'settings' window, where you can configure (much like the exclude tab) directories/files which will only keep the last version.

So, if I add e.g. "/home/username/.local/share/Steam/steamapps/common/*" to this list, it will remove any previous backups and only keep the latest snapshot.

This is very important for especially games, which can be patched frequently and a small change to a large data file causes a duplicate of the file. I want a backup kept so that I can restore if needed, but I don't want to keep 10 versions of the same thing, adding hundreds of GB to my backup drive unnecessarily.

This is very different from the exclude function, because you still have a backup of that directory - the difference is you only have the latest version in your last snapshot, and not all of them going back to infinity.

The way I currently do this is to simply go through a couple dozen relevant directories after each backup, rightclick each one > snapshots, and manually removing them from older snapshots. A way to automate this so that you don't have to go through and manually do this would be superb.

**Comment by Germar** [comment]
related to #210 but no duplicate

**Comment by buhtz** [comment]
Thanks again for this report and idea. But it is IMHO out of the scope of BIT and also technically not worse the effort.
For the use case you describe you simply should use a second snapshot profile.

Vote to close.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
