### ISSUE TITLE
WARNING: Inhibit Suspend failed on Ubuntu 14.04 server

### ISSUE THREAD

**Issue by sbancal** [bit-team/backintime#500]
Hi,

Backing up an Ubuntu 14.04 serveur with Back In Time 1.1.8 (from ppa:bit-team/stable) gives always the following warning on STDERR : 

> WARNING: Inhibit Suspend failed.

After some little code browsing, it seems that the step to inhibit suspend / hibernate is mandatory.
What about the case of a cronjob run by root on a server?

Thanks,
Samuel

**Comment by Germar** [comment]
root has no Dbus sessionbus. So this won't work. I suppressed the warning if running as roo.

**Comment by sbancal** [comment]
Thanks!
