### ISSUE TITLE
UI enhancements and questions

### ISSUE THREAD

**Issue by fwilly** [bit-team/backintime#501]
1. **log view at any time**  
    If a run isn't successfully the log view action "*View / view snapshot log*" is deactivated. If I start the process and get "*No snapshot necessary*" I cannot find out why.  
    Better would be an integration in status line as combobox. Any time it can be expand to view the current log. If it is expanded it should be update automatically. If it is collapsed it will be display the current status message.  
Yes it is a little bit tricky to implement in a separate thread to do not slow done the gui, but it is possible.
2. **SSH only with private key possible?**  
    Or how can I remove a defined private key to switch to user/password authentication instead user/private key authentication?
3. **Keyring save**  
    I use kubuntu. Will be sometime possible to save passwords in kwallet?

**Comment by Germar** [comment]
1. `View snapshot log` shows the log of the current selected snapshot in timeline. If you selected `Now` in timeline (which is not a snapshot but a live view of your harddrive) it is deactivated.
`View last log` will always show the log of the last run no matter if this run ended in a new snapshot or in `no snapshot necessary`

2. That's not (yet) possible.

3. That should work for normal users. But not for root as root has no keyring. If not you're missing some dependencies. Make sure you have `python3-keyring` and `python3-keyring-kwallet` or `python3-secretstorage` installed.
