### ISSUE TITLE
Launch backintime, Nothing Happens Debian Jessie - Xfce

### ISSUE THREAD

**Issue by Palatini** [bit-team/backintime#502]
Hi,

I installed back in time, and used backintime-gnome because of https://answers.launchpad.net/backintime/+question/250198

When I click on it nothing happens, during the installation, Meld was installed too, and it's working when I click on it.

I've looked for log, but i could'nt find anything in /var/log/syslog and nothing seems to be added in /var/log when I click on backintime or backintime (root).

Any idea?

Thanks

**Comment by Germar** [comment]
Please open a Terminal, run `backintime-gnome` and post the output in here.

**Comment by Palatini** [comment]
hi,
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Traceback (most recent call last):
  File "/usr/share/backintime/gnome/app.py", line 41, in <module>
    import backintime
  File "/usr/share/backintime/common/backintime.py", line 26, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 30, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 27, in <module>
    import dbus
ImportError: No module named dbus

**Comment by Germar** [comment]
There is one dependency missing. Please run 
```
su
apt-get install python-dbus
```

**Comment by Palatini** [comment]
great thanks a lot, it's working now :) 
I thought that dependecies are automaticly installed when i used apt-get install  apt-get install backintime-common backintime-gnome

**Comment by Germar** [comment]
Yeah, they SHOULD. But the Debian package is not in a good shape. I already filled a bug-report for that missing dependency and the maintainer fixed that. But the new version (1.1.6) with that fix got hold back by an other bug report...
