### ISSUE TITLE
Statusbar icon -> Start BackInTime not working

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#503]
Hi, Im running Linux Mint 17.2, Cinnamon 64-bit. When BackInTime is running in the background, there is a Statusbar icon that indicates progress. It has a context menu and a button to start BackInTime, which is not working.
Im using bit as root.

**Comment by Germar** [comment]
Fixed this already in [commit d9df9c5](https://github.com/bit-team/backintime/commit/d9df9c56c9e12f60e9de244f15d4c91cbdb16c92)
