### ISSUE TITLE
Website is out of date

### ISSUE THREAD

**Issue by simonsmiley** [bit-team/backintime#504]
The current backintime website is quite out of date. I couldn't find any link to github for example.

I guess github's pages could be easily used for this. I guess I could do that, if you don't want

**Comment by Germar** [comment]
The website http://backintime.le-web.org/ is owned by Dan. He left the project couple month ago.

After moving to GitHub from Launchpad I was planning to use GitHub's Wiki for this but nothing done so far. So, help is always very welcome! :+1: 

Just let me know if you need any permissions for editing.

**Comment by LanceGundersen** [comment]
I am willing to help out, let me know where!

**Comment by Germar** [comment]
I never made a docu before so I'm very open for suggestions.

I first thought we could just use GitHubs wiki for the doc. But now I added a dev-doc in http://backintime.rtfd.org/ with `sphinx` and I really like how that works. So maybe It would be better to create a new `bit-team/doc` repository with basic `sphinx` config and then write the whole doc in there using restructuredText.

What do you think?

@buhtz would you like to join the discussion?

**Comment by Germar** [comment]
Oh, and thanks a lot for offering help on this! I really appreciate this!

**Comment by buhtz** [comment]
Sorry, for late reply. The dev-doc is nice. Tried sphinx once but was to much and complexe for my simple needs/brain. ;)

When you can handle that, great! Than you can help me once when I try to use it again. :D

**Comment by Germar** [comment]
Great. So I'll prepare a basic structure in the next days and let you guys know :smiley:

Sure I can help you on sphinx. Just use either [Google style](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html) or [Numpy style](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_numpy.html#example-numpy) docstrings and drop me a line if you're ready.

**Comment by caco3** [comment]
http://backintime.le-web.org/ is the first hit google brings, so it is very important to have it up to date.
The latest news there is from 2011. Not really representing the ongoing development...
If Dan is not able/willing to update the page/add a note, then you should try to build a site which is ranked even better as his.

**Comment by Germar** [comment]
SEOs are very welcome ;-)

I'm sure Dan will add a link as soon we have a new Doc

**Comment by dinoboy197** [comment]
:+1: on building a new home for BIT on the web! (whether it be github, rtfd.org, le-web.org, or otherwise)

I'll be happy to link to it from my own blog once we get something in shape which is user-friendly and advertises well why people should use BIT :)

**Comment by Germar** [comment]
Good news! I finally set up a [new documentation for Back In Time](https://github.com/bit-team/doc)  :raised_hands:

It is hosted on 'Read the Docs' http://backintime.rtfd.org/

So, if you don't mind I would like to invite you joining the @bit-team/doc team and help on making a great documentation again. Thanks a lot in advance!

**Comment by dinoboy197** [comment]
:rocket: :clap: :trophy: !

**Comment by colintedford** [comment]
Instead of just linking from the old site, why not have it redirect to the current one? And maybe save a copy of the old site for historical interest / just in case.

**Comment by Germar** [comment]
Dan told me, he will shut down that site in March

**Comment by AdmiralAsshat** [comment]
Just a heads-up, that site http://backintime.le-web.org/ is completely gone now. 

If the domain is for sale, someone may wish to grab it. Otherwise, perhaps change the existing source and documentation to point somewhere else?

**Comment by Germar** [comment]
The domain le-weg.org is still owned by Dan and I don't think he is gonna sell it.

**Comment by AdmiralAsshat** [comment]
That's disappointing to hear. Why squat the domain for a project you no longer wish to work on?

**Comment by Germar** [comment]
Because it's his private domain which he was/is using for other purpose, too.

We don't need that domain anymore. Everything that belongs to BiT is on Github and RTFD

**Comment by colintedford** [comment]
http://backintime.le-web.org/ is a subdomain of le-web.org, which is almost like a separate domain. All he'd need to do is make http://backintime.le-web.org/ permanently redirect and then ignore it -- it won't affect le-web/org. I'd suggest having it redirect to a proper domain name, which you can then redirect wherever you want in the future (backintime.org is taken but backintimeapp.org is available).

**Comment by buhtz** [comment]
Plesae! Don't use "app". :D
It suggest bad software, focusing stupid users, unsecure, ...

**Comment by colintedford** [comment]
Use whatever name you want. Backintimetool.org is available too, as are others I'm sure.

**Comment by buhtz** [comment]
GitHub offers an own project related "Website". see the settings page of the project.

btw: I thikn GitLab offers something like that, too. I moved two of my projects to GitLab.

**Comment by colintedford** [comment]
The idea of the domain name is to never have to change the (proposed) redirect at le-web.org, so we don't break search results and the links of everyone who's ever linked to the project. The domain can point to anywhere -- the GitHub thing, the GitLab thing -- and point to anywhere else in the future without asking le-web's owner to do anything.

**Comment by buhtz** [comment]
I agree to colintedford. But I think there is a communication problem with the domain owner, isn't it?

**Comment by Germar** [comment]
Nope, I'm in contact with Dan.

**Comment by buhtz** [comment]
The initial issue (website out of date) is solved.
All other side topics are refelected in other issues.
