### ISSUE TITLE
Error when starting BIT: mountpoint /home..../mountpoint not empty 

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#505]
Since several years now, I run BIT backups to a remote server using ssh.

Suddenly, when I try to start BIT I get the above error message.

Does it relate to any previous broken transmission? How can I safely repair this? 
I am particularly conscious about preserving all my backup data intact.  

(I tried to google and also search the git repo but did not find anything related to this error. Further, I tried to search the old questions/answers at Launchpad, but there doesn't seem to be anything there? Hopefully they were all moved here to github.)

Thank you for any help with this problem!

**Comment by Germar** [comment]
Please make sure no BackInTime instance is running anymore with
```
killall backintime
```
and unmount the mountpoint just in case
```
fusermount -u /home/USER/.local/share/backintime/mnt/.../mountpoint
#use the original path from the error message
```
Or, to be fully save, just restart.

Next you can delete the whole `mnt` folder.
```
rm -rf ~/.local/share/backintime/mnt
```

This is probably just a leftover from previous broken snapshot.

**Comment by ersv** [comment]
HI Germar,

Thank you for the help.

Now, I can get into BIT and I see all the snapshots. However, when I press the button for taking a snapshot (disk with a green arrow pointing downwards) nothing happens. The status bar bottom left says "Ready" (but in my language translated to English here) even though I just pressed said button.
 
Really strange, I never seen BIT like this.

Any ideas?

**Comment by Germar** [comment]
Looks like there are more leftovers in `~/.local/share/backintime/`. Please make sure again, there is no running instance left like above and rename that folder. BackInTime will create a new one
```
mv ~/.local/share/backintime ~/.local/share/backintime.sic
```
Also please use the current version (1.1.8 at time of writing). It uses a better way of handling those leftovers. You can install current version [from our PPA](https://github.com/bit-team/backintime#ubuntu-ppa) if you're on Ubuntu.

**Comment by ersv** [comment]
Hi Germar, 

Thank you, now it is working! Feels great and no data loss.

Actually, I am already using the 1.1.8. version. If what happened isn't the expected behaviour with this version I will be more than happy to help you try to diagnose the cause of the problem if you would give me some instructions.

Thanks again for a great piece of software.

**Comment by Germar** [comment]
Could you please send me a tar archive of the old `~/.local/share/backintime` folder for diagnostics?
```
tar cvJf backintime.tar.xz ~/.local/share/backintime.sic
```
You can send it to germar DOT reitze HOSTED ON gmail DOT com instead of posting here as you might not want to expose the logs in there to the public.

**Comment by Germar** [comment]
Fixed and added a test for it!

**Comment by ersv** [comment]
Great to see that you improved BIT a little bit more ;^)

For the record, what was the problem?

**Comment by Germar** [comment]
Technical spoken it was an unhandled exception.

The `worker.lock` file was empty for what ever reason. During checking if an other process is currently running we parse the `worker.lock` and extract the `PID` from it. The `PID` should be transformed from a `string` instance into an `integer` instance. But the as the `string` was empty, `int(string)` raised a `ValueError` exception.
