### ISSUE TITLE
Usability: use appropriate icon for "Show hidden files"

### ISSUE THREAD

**Issue by anothernode** [bit-team/backintime#507]
The GUI (tested with Back In Time 1.1.8 on Arch Linux) uses an icon showing a plus symbol in the toolbar to enable/disable display of hidden files.

This is counterintuitive. Users expect the plus symbol to stand for creation of some object, like a new folder, not to change the viewing mode of a data window.

I would suggest something along the lines of a (stylized) eye instead.

**Comment by Germar** [comment]
An stylized eye is a good idea! I never created an icon before. Hope you like it...

![show-hidden](https://cloud.githubusercontent.com/assets/2731999/11944808/09baaa4a-a849-11e5-806d-c3f06e8ce15f.png)

**Comment by anothernode** [comment]
Look perfect, Germar :+1:
