### ISSUE TITLE
BiT - AUR build is completly broken!

### ISSUE THREAD

**Issue by Spirit328** [bit-team/backintime#508]
Hi there!

I saw BiT working at a friend of mine and was quite excited. 
So I decided to have it on my Odroid XU4 (with a RAID 1 of two 1 TB HDD) as my "backup-server".
Here is what I did.

1. Flashed a brandnew Archlinux on a fresh uSD card.
2. reboot
3. [build the RAID 1 and mount it to /var/raid]
4. sudo pacman -S wget
5. copy & pasted the URL to get backintime
````
[alarm@alarm temp]$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/backintime.tar.gz
--2015-12-22 10:22:54--  https://aur.archlinux.org/cgit/aur.git/snapshot/backintime.tar.gz
Resolving aur.archlinux.org (aur.archlinux.org)... 5.9.250.164, 2a01:4f8:160:3033::2
Connecting to aur.archlinux.org (aur.archlinux.org)|5.9.250.164|:443... connected.
HTTP request sent, awaiting response...
200 OK
Length: unspecified [application/x-gzip]
Saving to: 'backintime.tar.gz'
backintime.tar.gz       [ <=>                  ]   1.78K  --.-KB/s   in 0s
2015-12-22 10:22:55 (56.5 MB/s) - 'backintime.tar.gz' saved [1819]

[alarm@alarm temp]$ tar -xvf backintime.tar.gz
backintime/
backintime/.SRCINFO
backintime/Fix_bug_473-AttributeError.patch
backintime/PKGBUILD
[alarm@alarm temp]$ cd backintime
[alarm@alarm backintime]$ ll
total 20
drwxr-xr-x 2 alarm alarm 4096 Dec 16 19:51 .
drwxr-xr-x 3 alarm alarm 4096 Dec 22 10:23 ..
-rw-r--r-- 1 alarm alarm 1506 Dec 16 19:51 .SRCINFO
-rw-r--r-- 1 alarm alarm  865 Dec 16 19:51 Fix_bug_473-AttributeError.patch
-rw-r--r-- 1 alarm alarm 1916 Dec 16 19:51 PKGBUILD
````
Well, it does not run as expected. ;-)

Could you please have a look and provide the intended files?
THANK YOU very, very much in advance.

Thorsten

**Comment by Germar** [comment]
Hi Thorsten,

looks good so far. What exactly doesn't work? You just [need to proceed](https://github.com/bit-team/backintime#archlinux) with
```
gpg --keyserver pgp.mit.edu --recv-keys 615F366D944B4826
makepkg -src
sudo pacman -U backintime-<VERSION>.pkg.tar.xz
```

Regards,
Germar

**Comment by Spirit328** [comment]
Hi Germar,

thank you for your reply. I am sorry, for being not precise enough.
I followed the instructions as descirbed on [GitHub](https://github.com/bit-team/backintime).

````
[alarm@alarm ~]$ sudo gpg --keyserver pgp.mit.edu --recv-keys 615F366D944B4826
gpg: key 944B4826: "Germar Reitze <germar.reitze@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
````
So far, so good. The gpg key was still available. No surprises here.

Now proceeding with downloading the tar.gz file.
````
[alarm@alarm ~]$ wget https://aur.archlinux.org/cgit/aur.git/snapshot/backintime.tar.gz
ll--2015-12-28 16:15:29--  https://aur.archlinux.org/cgit/aur.git/snapshot/backintime.tar.gz
Resolving aur.archlinux.org (aur.archlinux.org)... 5.9.250.164, 2a01:4f8:160:3033::2
Connecting to aur.archlinux.org (aur.archlinux.org)|5.9.250.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'backintime.tar.gz'

backintime.tar.gz       [ <=>                  ]   1.78K  --.-KB/s   in 0s

2015-12-28 16:15:30 (58.3 MB/s) - 'backintime.tar.gz' saved [1819]
````
Next will be untaring ....
````
[alarm@alarm ~]$ tar xvzf backintime.tar.gz
backintime/
backintime/.SRCINFO
backintime/Fix_bug_473-AttributeError.patch
backintime/PKGBUILD
````
Now we'll change into the directory backintime, created by the tar command. (as described in the instructions)

````
[alarm@alarm ~]$ cd backintime
[alarm@alarm backintime]$
````
Inside the directory we'll do the `makepkg -src`, as described.
````
[alarm@alarm backintime]$ makepkg -src
==> ERROR: Cannot find the strip binary required for object file stripping.
````


I also tried the following: I downloaded the "regular" backintime-1.1.8.tar.gz from [here](https://launchpad.net/backintime/+download), untared it and copied the files of the former downloaded file into the directory `backintime-1.1.8`. 
The "regular" backintime-1.1.8.tar.gz is about 600 KB big. The backintime.tar.gz for ARM is about 1 KB in size. 
That is why I thought there must be something missing in the tar-file. Or do I have to download something else from somewhere?

````
[alarm@alarm backintime]$ cd ../backintime-1.1.8
[alarm@alarm backintime-1.1.8]$ ls -la
total 124
drwxr-xr-x 5 alarm alarm  4096 Dec 28 16:27 .
drwx------ 4 alarm alarm  4096 Dec 28 16:26 ..
-rw-r--r-- 1 alarm alarm   144 Sep 28 20:20 AUTHORS
-rw-r--r-- 1 alarm alarm 34871 Sep 28 20:20 CHANGES
-rw-r--r-- 1 alarm alarm   865 Dec 28 16:27 Fix_bug_473-AttributeError.patch
-rw-r--r-- 1 alarm alarm 17987 Sep 28 20:20 LICENSE
-rw-r--r-- 1 alarm alarm  1916 Dec 28 16:27 PKGBUILD
-rw-r--r-- 1 alarm alarm  2968 Sep 28 20:20 README
-rw-r--r-- 1 alarm alarm   158 Sep 28 20:20 TODO
-rw-r--r-- 1 alarm alarm   517 Sep 28 20:20 TRANSLATIONS
-rw-r--r-- 1 alarm alarm     6 Sep 28 20:20 VERSION
drwxr-xr-x 6 alarm alarm  4096 Sep 28 20:20 common
drwxr-xr-x 3 alarm alarm  4096 Sep 28 20:20 debian
-rwxr-xr-x 1 alarm alarm   289 Sep 28 20:20 make-tarball.sh
-rwxr-xr-x 1 alarm alarm   552 Sep 28 20:20 makedeb-src.sh
-rwxr-xr-x 1 alarm alarm   248 Sep 28 20:20 makedeb.sh
drwxr-xr-x 5 alarm alarm  4096 Sep 28 20:20 qt4
-rwxr-xr-x 1 alarm alarm   225 Sep 28 20:20 updatecopyright.sh
-rwxr-xr-x 1 alarm alarm  1493 Sep 28 20:20 updateversion.sh
[alarm@alarm backintime-1.1.8]$ makepkg -src
==> ERROR: Cannot find the strip binary required for object file stripping.
````
This doesn't help either. 
Now I am counting on you to give me directions or any hint. I do not know any further. \*sigh\*

**Comment by Germar** [comment]
Please install `base-devel`
```
pacman -S base-devel
```

**Comment by Spirit328** [comment]
Hi Germar!
THANKS A LOT!!! This helped me to get around.
After installing some other packages like `libpng-1.6.19-1-armv7h.pkg.tar.xz` and `python` and `python-setuptools-1_19.1.1-1-any.pkg.tar.xz` and some other stuff that could not be downloaded automatically from `mirror.archlinuxarm.org`, I made it.

Ready for configuring the first jobs.

Again: 
THANKS A LOT!!!

P.S.: Maybe it would be very helpful for others, to mention a quick check, if `base-devel` is installed on their machines? Something like ` pacman -Qs base-devel` ?

**Comment by Germar** [comment]
I'm not the maintainer of the AUR package. This would have to be done by graysky on [AUR](https://aur.archlinux.org/pkgbase/backintime/). But as far as I understand the [Arch wiki](https://wiki.archlinux.org/index.php/Makepkg#Usage), `base-devel` is not considered as a dependency in `PKGBUILD`. Feel free to report this on AUR.
