### ISSUE TITLE
"Save Password to Keyring" greyed out.

### ISSUE THREAD

**Issue by joaoherberto** [bit-team/backintime#509]
Runing Fedora F23 X86_64, BIT 1.0.36 

The "Save Password to Keyring" is greyed out, and I have python3-keyring and  python3-secretstorage installed.

Any ideas?

**Comment by Germar** [comment]
Do you use `Back In Time (root)`? Root has no keyring so it can't be used with it. What DE (KDE|Gnome) do you use?

**Comment by joaoherberto** [comment]
Yes, knew about the root issue... Just using the regular user account on Gnome3

**Comment by Germar** [comment]
Please install `python3-gnomekeyring` and try again.

Maybe related to #473?

**Comment by joaoherberto** [comment]
Humm... python3-gnomekeyring is not available when searching dnf and I do have RPMFusion installed. How ever Package python3-keyring-5.0-2.fc23.noarch is already installed.

Aside from having to enter the password for the encryption every time I restart the laptop, it works flawlessly. Been using BIT for years, have it running on three other laptops, but those are running Fedora 22.

**Comment by Germar** [comment]
I found [gnome-python2-gnomekeyring](https://www.rpmfind.net/linux/RPM/fedora/23/aarch64/g/gnome-python2-gnomekeyring-2.32.0-22.fc23.aarch64.html) for Fedora 23. But nothing for Python3. Sorry, I have never used Fedora and can't help on this.

**Comment by Germar** [comment]
BTW did you try [BackInTime 1.1.x for Fedora](https://copr.fedoraproject.org/coprs/mhoeher/backintime/)?

**Comment by joaoherberto** [comment]
ok, went through the procedure to remove the old version and followed the instructions to add the repo, this is what I get:

[joao@JOAOXPS14 ~]$ sudo dnf --allowerasing install backintime-qt4
Last metadata expiration check performed 0:05:40 ago on Tue Dec 22 19:57:50 2015.
Error: nothing provides pm-utils needed by backintime-1.1.6-1.fc23.noarch
[joao@JOAOXPS14 ~]$ 

I ran dnf update first  and restarted the machine just to make sure... still got the same error..

**Comment by Germar** [comment]
I'm really sorry to say I can't help on this. I've no clue about Fedora. But also this is a problem with the Fedora package, not with BackInTime it self. So you should try on [their bug-tracker](https://gitlab.com/rpdev/fedora-backintime/issues).

**Comment by joaoherberto** [comment]
"Sorry, I have never used Fedora and can't help on this." No worries, I just recently moved over to Fedora from Debian/Ubuntu derivatives and I can honestly say that it is one if not the best distros I have ever used. Been using GNU/Linux for over ten years, it took a lot to move me over but once I tried, it just works.
I decided to just go back to the previous version, I can put up with entering the password...
Thank you for your time and effort, much appreciated... Merry Christmas.

**Comment by Germar** [comment]
Thanks. Happy Holidays to you, too.

**Comment by Germar** [comment]
Oh, BTW I just added more debug messages on keyring support. So with next version `1.1.10` it should at least show, why this doesn't work :wink:

**Comment by joaoherberto** [comment]
OK, found problem on why "Save Password" is grayed out in Gnome3, Fedora 23, & ArchLinux/Manjaro   Package "SecretStorage" is needed   https://pypi.python.org/pypi/SecretStorage, apparently it replaces "python3-gnomekeyring". I switch to Manjaro and running BIT  v1.1.12 it all works flawlessly with encryption.
