### ISSUE TITLE
Help>About fails to open a window

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#515]
Running [v1.1.10](https://aur.archlinux.org/packages/backintime) on Arch Linux.  When I invoke Help>About I get the following with no window displayed.  Missing a dep or legit bug?

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 955, in on_about
    dlg = About(self)
  File "/usr/share/backintime/qt4/app.py", line 1348, in __init__
    rev_no = tools.get_bzr_revno()
AttributeError: module 'tools' has no attribute 'get_bzr_revno'
Created new window in existing browser session.
```

The same can be said for Help>Help and Help>Config File Help although these result in a different error:
```
sh: x-terminal-emulator: command not found
```

**Comment by Germar** [comment]
I forgot to change `About` dialog, sorry. `get_bzr_revno()` is gone and replaced by `get_git_ref_hash()`.

`Help>Help` and `Help>Config File Help` should now show the man-page as long as we don't have any other up-to-date documentation. I used `x-terminal-emulator man backintime` for this. On Ubuntu and derivates this is a symlink to `gnome-terminal` or `konsole`. Is there something similar on Arch?

I'll make a new release with both fixed.

**Comment by graysky2** [comment]
> On Ubuntu and derivates this is a symlink to gnome-terminal or konsole. Is there something similar on Arch?

Not sure actually... there are many options for xterms and I'm not sure exactly how one would invoke a generic one :pensive:

**Comment by Germar** [comment]
What about adding a dependency in Arch for [xman](https://www.archlinux.org/packages/?name=xorg-xman)? Looks like a lightweight tool (not much dependencies by its own). I could check if either `x-terminal-emulator` or `xman` is available and open the manpage with one of them.

Only `wayland` could make troubles. Not sure if `xman` would install seamless on a pure `wayland` system...

**Comment by graysky2** [comment]
The patch to fix the about dialog works.
I installed xorg-xman but as-is there is no change.  Perhaps that is to be
expected.

On Sunday, January 10, 2016, Germar Reitze <notifications@github.com> wrote:

> What about adding a dependency in Arch for xman
> <https://www.archlinux.org/packages/?name=xorg-xman>? Looks like a
> lightweight tool (not much dependencies by its own). I could check if
> either x-terminal-emulator or xman is available and open the manpage with
> one of them.
>
> Only wayland could make troubles. Not sure if xman would install seamless
> on a pure wayland system...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bit-team/backintime/issues/515#issuecomment-170403969>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ronisbr** [comment]
Well, neither openSUSE has `x-terminal-emulator`. The _equivalent_ is `xdg-terminal` that opens a default terminal, but it will not work since it can accept only one parameter. Thus, the following command fails:
```
$ xdg-terminal man backintime
xdg-terminal: unexpected argument 'backintime'
Try 'xdg-terminal --help' for more information.
```
My temporary solution to the problem was to replace `x-terminal-emulator` in `qt4/app.py` with `xterm`. It is not good, but it works.
```
sed -i -e "s|x-terminal-emulator|xterm|g" qt4/app.py
```
Maybe `backintime` should check if `x-terminal-emulator` exists and, if not, call `xterm` instead that seems a sane default.

**Comment by Germar** [comment]
Found a better solution in reading manpage from pipe and show it in a native Qt dialog. No other dependency necessary anymore. Will release `1.1.12` soon

**Comment by ronisbr** [comment]
Thanks!

**Comment by graysky2** [comment]
Good show!
