### ISSUE TITLE
Cannot open About dialog in backintime 1.1.10

### ISSUE THREAD

**Issue by ronisbr** [bit-team/backintime#517]
Hi!

When I try to open the About... dialog in backintime 1.1.10, I get the following error:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 955, in on_about
    dlg = About(self)
  File "/usr/share/backintime/qt4/app.py", line 1348, in __init__
    rev_no = tools.get_bzr_revno()
AttributeError: 'module' object has no attribute 'get_bzr_revno'
```

It turns out that if I remove the following lines, then everything works fine:
```
rev_no = tools.get_bzr_revno()
if rev_no:
       version += ' Bazaar Revision %s' %rev_no
```

Until this issue is solved, I will create a patch with the aforementioned change to avoid this bug in openSUSE package.

**Comment by ronisbr** [comment]
Duplicated

**Comment by Germar** [comment]
As said in dup #515 I'll release a new version shortly which will fix this.
