### ISSUE TITLE
Is purely qt5 possible?

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#518]
Is it feasible to build and run BIT using the qt5 libs rather than the qt4 libs or is qt4 a hard-dependency?

EDIT: I see some mention of qt4tools in the code so I assume that it is but thought I would ask.

**Comment by Germar** [comment]
`qt4tools` is a BIT-own module. That wouldn't be a problem. But it would be quite some work to port BIT to `PyQt5`. For example BIT still uses a lot old style Signal and Slots `QObject.connect()` which is not supported by `PyQt5` anymore.

It will be possible, for sure. And I'll do it some day. But at the moment that's not on my top priority list. Is there any special reason for Qt5?

**Comment by graysky2** [comment]
None of consequence.  Just trying to remove the qt4 family of deps if possible since I also have qt5 on here for some other stufff.  No need for you do to any heroic work particularly if it is a non-trivial.  Feel free to close or keep it open as a TODO as you please.

**Comment by rapgro** [comment]
:+1: Please keep this issue as TODO but implement asap.

**Comment by Goddard** [comment]
I know some distros are purging Qt4 applications.  KaOS for example doesn't use 32bit libs and is about to drop Qt4 support, but they are ahead of the pack in this regard.

**Comment by Germar** [comment]
@Goddard KaOS neither has BackInTime in repositories...

**Comment by Goddard** [comment]
I was gonna talk to the main maintainers about building it that is why I came here, but I noticed it is Qt4 so not sure they would be into it.  They said Qt4 has already reached EOL.

No worries though.  I was just bringing it to your attention.

**Comment by graysky2** [comment]
Nice, is a point release in the works?

**Comment by Germar** [comment]
There are so many changes under the hood right now that I decide to make a new major release 1.2.0
It's still some work to do so it will take some more months

Qt5 in current master still segfaults on exit...

**Comment by graysky2** [comment]
OK... nothing is easy, is it :stuck_out_tongue:

Keep up the great work!
