### ISSUE TITLE
Backintime cannot check power status in openSUSE

### ISSUE THREAD

**Issue by ronisbr** [bit-team/backintime#519]
Hi!

I saw that backintime uses the command `on_ac_power` to check whether the computer is plugged on AC or using battery. However, it turns out that this command is not available anymore in openSUSE. AFAIK, this was a part of `pm-utils` package that was dropped. For more information, see:
http://lists.opensuse.org/opensuse-factory/2015-06/msg00443.html

Can you please tell me what do you consider as the right workaround for this problem?

Thanks,
Ronan

**Comment by Germar** [comment]
I've no idea but I'll have a look. `on_ac_power` is just a shell script. So if there is nothing appropriate I'd need rewrite that in BIT. But I guess there is a `dbus` method that could tell the same...

For now you can just skip `pm-utils` dependency. BIT will work without.

**Comment by Germar** [comment]
`org.freedesktop.UPower` provides that information. So we can ditch `pm-utils` dependency
