### ISSUE TITLE
make -test fails on Arch

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#522]
It seems that common/configure wants py.test-3 but Arch does not provide that executable.

```
which: no py.test-3 in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

We have a package that provides:  `/usr/bin/py.test` and `/usr/bin/py.test-3.5`

1) Can you modify common/configure to look for `py.test-3.5 or py.test-3 or py.test` in the PATH?

2) The `make test` still fails when I run it in the clean-chroot per the Arch build standards (but it does work outside in my live environment)  Any ideas?  Perhaps I am missing a dependency in the chroot that I have in the live environment?  I do not know python so the error message is lost on me.

```
% make test
py.test-3.5 
test/test.sh
============================= test session starts ==============================
platform linux -- Python 3.5.1, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
rootdir: /build/backintime/src/backintime-1.1.12/common, inifile: 
Clean testing directory
Create testing directory
Create testing data
collected 92 items

test/test_applicationinstance.py ..........
test/test_argparser.py ..............
================================================================================
 TEST --> A snapshot have been created 
 SUCCESS --> A snaphshot should have been created 
================================================================================

.......
test/test_configfile.py ................................................
test/test_snapshots.py ..
test/test_tools.py ...F.......

=================================== FAILURES ===================================
________________________ TestTools.test_process_exists _________________________

self = <test.test_tools.TestTools testMethod=test_process_exists>

    def test_process_exists(self):
        ''' Test the function process_exists '''
>       self.assertTrue(tools.process_exists("init") or tools.process_exists("systemd"))
E       AssertionError: False is not true

test/test_tools.py:68: AssertionError
===================== 1 failed, 91 passed in 3.37 seconds ======================
Makefile:561: recipe for target 'unittest' failed
make: *** [unittest] Error 1
make: *** Waiting for unfinished jobs....

================================================================================
 TEST --> No snapshot have been created 
 SUCCESS --> A useless snaphshot have been created 
================================================================================


================================================================================
 TEST --> A snaphshot should have been created 
 SUCCESS --> A snapshot have been created 
================================================================================


================================================================================
Summary integration tests :
--> Successes : 3 - Fails : 0
================================================================================

All tests passed successfully, cleaning testing directory

```

**Comment by graysky2** [comment]
... I see some warnings upon running the ./configure script:
```
which: no py.test-3 in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
which: no coverage in (/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
```

On Arch, it seems that [community]/python-coverage provides `coverage` but there is not a package that provided `py.test-3`.  We do have [community]/python-pytest but it provides `py.test-3.5`

**Comment by Germar** [comment]
1. `unittest` should run without any extra dependencies. `coverage` is just used to protocol the usage of each line during tests and reports them to [coveralls.io](https://coveralls.io/github/bit-team/backintime?branch=master). It has no value outside of [travis-ci.org](https://travis-ci.org/bit-team/backintime) (maybe I should really restrict this to travis...)
`py.test-3` just shows a fancy output which I prefer. But if non of both (`coverage` nor `py.test-3`) is available those tests will be run by `python` (or `python3` depending on `configure` args).

2. The test in `test-tools.py` is failing because non of `init` nor `systemd` process where running. I thought at least one of these are default on every Linux :confused:. Do you know a process which is constantly running on each and every Arch and even in chroot?

**Comment by Germar** [comment]
Oh, I just saw that for some reason it defaults to `coverage` instead of `python`. But I'm to tired to troubleshoot this today. Will fix it tomorrow.

**Comment by graysky2** [comment]
No problem.  It's just the test function that fails; the package works fine.  I am happy to test a commit when you are up to it.

**Comment by Germar** [comment]
Would you please give the [current `configure`](https://github.com/bit-team/backintime/blob/6bcd58d27fa5cd33e65e267b49625d6edd48f153/common/configure) a try?

`coverage` and `py.test-3.5` problems both should be fixed now.

To fix the 2nd problem would you please post a `ps aux` from inside the chroot?

**Comment by graysky2** [comment]
The new configure works great without either the 'python-coverage' or 'python-pytest' dependency.
Here is ps aux before the chroot runs `make test`
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.0  14012  2752 ?        SNs+ 18:05   0:00 /bin/bash /chrootbuild
root         7  0.0  0.0  70368  4624 ?        SN+  18:05   0:00 sudo -u builduser makepkg -s --noconfirm -L --holdver
buildus+     8  0.0  0.0  13468  4236 ?        SN+  18:05   0:00 /usr/bin/bash /usr/bin/makepkg -s --noconfirm -L --holdver
buildus+   568  0.0  0.0   4208   828 ?        SN+  18:05   0:00 tee /logdest/backintime-1.1.12-1-x86_64-check.log
```

**Comment by Germar** [comment]
Thanks for the `ps`. Pretty short proc list :flushed:

I'll have to use either the current process or spawn an extra process to test against.

**Comment by Germar** [comment]
2nd is fixed, too. Would you please clone `master` and run unittests on Arch and inside the chroot? I have no Arch at hand atm.

**Comment by graysky2** [comment]
You bet.  One sec.

**Comment by graysky2** [comment]
Errors out:
```
python -m unittest  -b test/test_applicationinstance.py
test/test.sh
....Clean testing directory
Create testing directory
.Create testing data
.....
----------------------------------------------------------------------
Ran 10 tests in 0.018s

OK
python -m unittest  -b test/test_argparser.py
..
================================================================================
 TEST --> A snapshot have been created 
 SUCCESS --> A snaphshot should have been created 
================================================================================

........
================================================================================
 TEST --> No snapshot have been created 
 SUCCESS --> A useless snaphshot have been created 
================================================================================


================================================================================
 TEST --> A snaphshot should have been created 
Assertion failed:  "Test if backintime make a new snapshot on content dir change" for test : "A snaphshot should have been created"
File "test/test.sh", line 118
 FAIL --> 118 
================================================================================


================================================================================
Summary integration tests :
--> Successes : 2 - Fails : 1
================================================================================

Makefile:577: recipe for target 'integrationtest' failed
make: *** [integrationtest] Error 1
make: *** Waiting for unfinished jobs....
...........
----------------------------------------------------------------------
Ran 21 tests in 3.313s

OK
python -m unittest  -b test/test_configfile.py
...................................................
----------------------------------------------------------------------
Ran 51 tests in 0.004s

OK
python -m unittest  -b test/test_snapshots.py
.................s............................................
----------------------------------------------------------------------
Ran 62 tests in 0.047s

OK (skipped=1)
python -m unittest  -b test/test_tools.py
.device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
device node not found
F...........
======================================================================
FAIL: test_get_filesystem_mount_info (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/backintime/src/backintime-master/common/test/test_tools.py", line 133, in test_get_filesystem_mount_info
    self.assertGreater(len(mounts.items()), 0)
AssertionError: 0 not greater than 0

----------------------------------------------------------------------
Ran 13 tests in 0.037s

FAILED (failures=1)
Makefile:563: recipe for target 'unittest' failed
make: *** [unittest] Error 1
```

**Comment by Germar** [comment]
Okay, thanks. I'll rewrite `integrationtest` (`common/test/test.sh`) with pure python `unittest` soon. It's not reliable.
But `test_get_filesystem_mount_info` need to work. @dinoboy197 do you have an idea on this?

**Comment by dinoboy197** [comment]
An assumption that `test_get_filesystem_mount_info` makes is that the system it is running on has at least one mount represented in `/etc/mtab` that has a UUID assigned. It's not an explicitly mentioned assumption in the test - I had though when I wrote this test that any system executing it would have at least one UUID label, but this may have been an invalid assumption. @graysky2 - on the system that is running the failed test, does any of it's mounts have [UUID labels](https://wiki.archlinux.org/index.php/fstab#UUIDs)?

**Comment by graysky2** [comment]
Yes, incorrect assumption in my case.  I exclusively use labels in my /etc/fstab to define mounts.

**Comment by graysky2** [comment]
@dinoboy197 - I modified my /etc/fstab defining a UUID partition therein.  I reboot the machine and /boot was successfully mounted as such but the build in the schroot still fails.

```
UUID=248ad77c-b020-4bf4-47d2-bbf5ef0075c1 /boot ext4 defaults,relatime,discard 0 1
```

**Comment by dinoboy197** [comment]
OK, thanks for letting me know! Would you `cat` your `/etc/mtab` for us, so that I can see what it looks like on your system? That should give us enough information to modify the runtime code and test to be more robust to a system with only fs labels.

**Comment by graysky2** [comment]
You bet.  No real privacy concern posting to github/public but I emailed it to Germar asking him to share with you as well anyway.

**Comment by Germar** [comment]
It doesn't matter how the drives are mounted in `/etc/fstab`. Important is that we can access the `UUID` of at least one mount.

For this `tools.get_uuid()` iterate over all symlinks in `/dev/disk/by-uuid` and check if the realpath is the device in question. If it doesn't find the `UUID` in this way it tries to call `udevadm info --name=/dev/sdXX` and extract the `UUID` from the output.

So the question is, why does both ways fail in chroot jail? I think, host systems `/dev` is not loop mounted to the jail. That's why the first solution fails. For the second solution I need to have a look into `udevadm` to tell where it is getting it's informations (maybe `/proc`?)

**Comment by graysky2** [comment]
I haven't messed around with either of them but am glad to provide you with output from in or outside of the chroot to help debug.

**Comment by Germar** [comment]
Is there any documentation about the AUR build chroot? Looks like I need to set up a new Arch VM...

**Comment by graysky2** [comment]
Yes, I am building with a bash wrapper script I wrote called [clean-chroot-manager](https://aur.archlinux.org/packages/clean-chroot-manager/) which is a glorified wrapper of the key utils for building in chroots contain in the official package called devtools.

Arch has an excellent wiki; your VM should be up in no time.  Once it's running, install the base-devel group `pacman -S base-devel` and then you may build from the AUR using `makepkg`... just download the AUR source, extract, and run `makepkg -s` to build.  To build in the clean-chroot which is where all these problems are currently, try ccm linked above.  It's as simple as `sudo ccm s` and you're off the races.  You may edit the backintime PKGBUILD from the AUR to include any commands you wish to see echoed to the terminal for troubleshooting.

Example:
```
pkgname=('backintime' 'backintime-cli')
_pkgname="backintime"
pkgver=1.1.12
pkgrel=1
arch=('any')
url="https://github.com/bit-team/backintime"
license=('GPL')
makedepends=('rsync' 'cron' 'openssh' 'python-keyring' 'python-dbus' 'polkit' 'procps-ng')
source=(backintime-master.zip)
sha256sums=('06e736b16cb0262a511e36328db045009f6c07c05be1e6913db5b91ca42b689f')

build() {
  cd "backintime-master/common"
  ./configure --python --no-fuse-group
  make

  cd "$srcdir/backintime-master/qt4"
  ./configure --python
  make

  echo "here is mtab from within the chroot"
  cat /etc/mtab
  exit 0
}
```

**Comment by Germar** [comment]
Okay, Arch VM is up and running and I played around for a while. I think the key problem is that all devices in chroot jail are `tmpfs` which have no `UUID`.

Only solution that I see atm is to skip the test in the chroot jail by adding a `unittest.skipIf()` decorator for `test_get_filesystem_mount_info`. We could check if neither `/dev/disk/by-uuid` is available nor `udevadm info -e | grep uuid` has at least one match.

**Comment by dinoboy197** [comment]
> Only solution that I see atm is to skip the test in the chroot jail by adding a unittest.skipIf() decorator for test_get_filesystem_mount_info. We could check if neither /dev/disk/by-uuid is available nor udevadm info -e | grep uuid has at least one match.

Yeah, I was going to suggest something similar. Perhaps we should log a warning indicating that the user should test in a system with at least one UUID filesystem before creating any tags / releases from the current branch?

**Comment by Germar** [comment]
The `skipIf` decorator will show a message why it was skipped. I added `No UUIDs available on this system.` in the above commit. I assume a good package maintainer like @graysky2 would notice and run an other test, wouldn't you? :wink:

**Comment by graysky2** [comment]
Make no assumptions with me :p

Let me know which commit to test beyond what you have done in your VM.
What do you think of pacman by the way?  For me it beat the shit out of apt
and aptitude when I was running Debian and Ubuntu.  So simple and powerful.

On Sunday, January 17, 2016, Germar Reitze <notifications@github.com> wrote:

> The skipIf decorator will show a message why it was skipped. I added No
> UUIDs available on this system. in the above commit. I assume a good
> package maintainer like @graysky2 <https://github.com/graysky2> would
> notice and run an other test, wouldn't you? [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bit-team/backintime/issues/522#issuecomment-172410572>
> .
>


-- 
Sent from Gmail Mobile

**Comment by Germar** [comment]
[This is final commit](https://github.com/bit-team/backintime/tree/b80a6fa943a134029b60ec056a1d06f5382caecb) for this issue. I changed  `makedepends=('python' 'python-dbus' 'procps-ng' 'systemd')` in `PKGBUILD` in order to run those tests in `ccm`.
* `python-dbus` is a hard dependency to run backintime-cli
* `procps-ng` because some tests spawn `top`
* `systemd` because of `/usr/bin/udevadm`

Is there a way to have dependencies only for the `check` function?

`pacman` is great. I already remember how to search for a package that provide a special file which I have to google every time for `apt-get` even after so many years...
Also the `PKGBUILD` format is great. `debian/control` and `debian/rules` is so complicated compared to this...

**Comment by graysky2** [comment]
>Also the PKGBUILD format is great. debian/control and debian/rules is so complicated compared to this...

Exactly! It is so simple and I think you will find that the entire Arch Philosophy is aligned with the simplicity principal.  Again, one of the reasons I love it.

I will test this now and post back.

**Comment by graysky2** [comment]
I created a git PKGBUILD (both cli and qt4 rolled into 1 but that's fine for this purpose) that unless you tell it otherwise will build the latest commit from this repo.  It fails for me inside and outside the chroot.  Can you verify?

https://gist.github.com/graysky2/b6e3e31710dc9716bbe0

Error during test:
```

python -m unittest  -b test/test_applicationinstance.py
test/test.sh
Clean testing directory
Create testing directory
Create testing data
..........
----------------------------------------------------------------------
Ran 10 tests in 0.016s

OK
python -m unittest  -b test/test_argparser.py

================================================================================
 TEST --> A snapshot have been created 
 SUCCESS --> A snaphshot should have been created 
================================================================================

..........
================================================================================
 TEST --> No snapshot have been created 
 SUCCESS --> A useless snaphshot have been created 
================================================================================


================================================================================
 TEST --> A snaphshot should have been created 
Assertion failed:  "Test if backintime make a new snapshot on content dir change" for test : "A snaphshot should have been created"
File "test/test.sh", line 118
 FAIL --> 118 
================================================================================


================================================================================
Summary integration tests :
--> Successes : 2 - Fails : 1
================================================================================

Makefile:577: recipe for target 'integrationtest' failed
make: *** [integrationtest] Error 1
make: *** Waiting for unfinished jobs....
...........
----------------------------------------------------------------------
Ran 21 tests in 3.411s

OK
python -m unittest  -b test/test_configfile.py
...................................................
----------------------------------------------------------------------
Ran 51 tests in 0.004s

OK
python -m unittest  -b test/test_snapshots.py
.................s............................................
----------------------------------------------------------------------
Ran 62 tests in 0.048s

OK (skipped=1)
python -m unittest  -b test/test_tools.py
.s...........
----------------------------------------------------------------------
Ran 13 tests in 0.010s

OK (skipped=1)
```

**Comment by Germar** [comment]
Oh, sorry. I forgot to tell that I only used `make unittest`. Like I said above `make integrationtest` (which is both included in `test` target) is not reliable.

I just removed `integrationtest` from `test` target now and now your `PKGBUILD` is running fine here. Inside chroot jail there are two skipped test (`test_get_filesystem_mount_info` and `test_change_group`) outside all test run smooth.

I'll add a small dummy script which can be used to test a running proc so we can skip `top` dependency.

Instead of `pkgfile` I just used `pacman -Ql | grep "/usr/bin/top"` which worked great.

**Comment by graysky2** [comment]
OK.  I will wait for your new version bump and then adjust the unofficial PKGBUILD.

Yes, your usage of pacman is correct but it only works if you happen to have the package that provides "/usr/bin/top" on the system whereas pkgfile works with all packages in all repos you have enabled in `/etc/pacman.conf`

Note that you actually need to implicitly install pkgfile to get it and need to generate the initial database per the post-install message.  The -b only returns binaries.  Anyway, lemme know when you push the next release and thanks!

 ```
% pkgfile -b top
core/procps-ng

```

**Comment by dinoboy197** [comment]
This is my first experience with Arch (being a Debian / Ubuntu / CentOS user) so this is very enlightening. Thanks!

**Comment by graysky2** [comment]
That's how it started it for me as well... I needed a more updated package that wasn't in the Ubuntu repos... the freshness index of Arch is off the charts so... here I am years later still running Arch.

**Comment by Germar** [comment]
`procps-ng` dependency is gone now. I had to replace some `ps` calls, too. I think this issue is solved now. Thanks to both of you!

**Comment by graysky2** [comment]
Great, I am able to build 97a8c9b without errors within a clean chroot!

**Comment by dinoboy197** [comment]
:+1:

**Comment by Germar** [comment]
> Is there a way to have dependencies only for the check function?

@graysky2 I just randomly found `checkdepends=(...)` can be used in `PKGBUILD`.

So next BIT releases `PKGBUILD` should have `checkdepends=('python-dbus' 'systemd')`

**Comment by graysky2** [comment]
@Germar - I can check that out... it seems that the test function no longer works with the latest commit outside of a chroot.  I have covered a lot of miles since Jan 20 so shouldn't it build from git?

```
==> Starting check()...
/usr/bin/py.test-3 
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 642, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 835, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pytest 2.8.7 (/usr/lib/python3.5/site-packages), Requirement.parse('pytest==2.8.5'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/py.test-3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2912, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2898, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2925, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 644, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 657, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 830, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest==2.8.5' distribution was not found and is required by the application
Makefile:566: recipe for target 'unittest' failed
make: *** [unittest] Error 1
```

I have extra/python-logilab-common installed which I believe provides pytest.

**Comment by Germar** [comment]
@graysky2 Not sure where `py.test-3` comes from. I just double-checked with `py.test-3.5` from `community/python-pytest` which works fine (after fixing an other problem)

We have a new dependency `bindfs` which is in AUR. I'm not sure how to add this in `PKGBUILD`. But after installing manually the test run fine outside chroot. With `ccm` there is an other problem in our test that I need to troubleshoot.

**Comment by Germar** [comment]
@graysky2 Okay, I found the problem. chroot is running with `LANG=C` which will fail tests because of missing unicode support. This should work in chroot, too:
```
check() {
        cd "$_pkgname-${pkgver}/common"
        LANG=en_US.UTF-8 make unittest-v
}
```
Locale `en_US.UTF-8` is generated on my system with `ccm` automatically. Not sure if this is default. So might be better to add generating that locale, too?
