### ISSUE TITLE
AssertionError: path is not str type on 'Save permissions'

### ISSUE THREAD

**Issue by akki42** [bit-team/backintime#523]
Hi Germar,

on current git master, my ssh encrypted backup fails on "save permissions" with the following debug output:

```
IINFO: [common/snapshots.py:999 Snapshots._take_snapshot] Save permissions
DEBUG: [common/sshtools.py:258 SSH.unlock_ssh_agent] Private key /home/akki/.ssh/### is already unlocked in ssh agent
DEBUG: [common/encfstools.py:647 Decode.start_process] start 'encfsctl decode' process
DEBUG: [common/encfstools.py:651 Decode.start_process] Call command: encfsctl decode --extpass=backintime-askpass /home/akki/.local/share/backintime/mnt/6B0CA066/mountpoint
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 987, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 465, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 668, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 77, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 704, in take_snapshot
    ret_val, ret_error = self._take_snapshot( sid, now, include_folders )
  File "/usr/share/backintime/common/snapshots.py", line 1039, in _take_snapshot
    new_snapshot.fileInfo = fileInfoDict
  File "/usr/share/backintime/common/snapshots.py", line 2151, in fileInfo
    assert isinstance(path, str), 'path is not str type: {}'.format(path)
AssertionError: path is not str type: b'/home/akki/Dokumente/Archiv/Korrespondenz'
DEBUG: [common/encfstools.py:761 Decode.close] stop 'encfsctl decode' process
DEBUG: [common/encfstools.py:519 Encode.close] stop 'encfsctl encode' process

```

The path or file name in the last but two line varies with each attempt.
 
This error occurs since commit https://github.com/bit-team/backintime/commit/fa4508ea305978c16193579682653d1900f81000 ; earlier versions work fine...
 
Please let me know if you need any further information...

**Comment by Germar** [comment]
Thanks for the report. I heavily reorganized `snapshots.py`. This is still work in progress and not fully tested. Is there any special need you're running the dev clone instead of current stable `1.1.12`? Maybe I can back-port that for you...

**Comment by akki42** [comment]
Thanks, but no worries... I can use `v1.1.12` for the time being...

**Comment by dinoboy197** [comment]
Yep, just ran into this too :) Also using the latest in master.

**Comment by dinoboy197** [comment]
I've authored two PRs which fix both [the snapshot issue](https://github.com/bit-team/backintime/pull/528), and the next issue you would encounter which would be [correct uid / gid / perms restoration](https://github.com/bit-team/backintime/pull/529).
