### ISSUE TITLE
Can't remove folder

### ISSUE THREAD

**Issue by nielsk** [bit-team/backintime#524]
I am using an encrypted local backup and suddenly I am getting this error:

    Can't remove folder: home/$user/.local/share/backintime/mnt/1_8131/backintime/$computername/$user/1/new_snapshot

My folder /home/$user/.local/share/backintime/mnt/ looks like this:

    1_4917 -> /home/$user/.local/share/backintime/mnt/96E095B7/mountpoint
    96E095B7

I tried symlinking per hand but with each try taking a snapshot the symlink-name changes where backintime tries to remove the new_snapshot-folder

**Comment by Germar** [comment]
Please run `fsck /dev/sdXX` (or `fsck.ext4`) on the backup device. Most times I heard about not removable folders in snapshots it was a inconsistent filesystem.

**Comment by nielsk** [comment]
In checked now the backup-disk and the drive where the folder gets mounted and symlinked. Both are error-free and the error still occurrs

**Comment by Germar** [comment]
Please run
```
rm -rf $(backintime --keep-mount --quiet --snapshots-path | grep "SnapshotsPath" | awk '{print $2}')/new_snapshot
```

If this doesn't help try again with `sudo rm -rf ...`

**Comment by nielsk** [comment]
Thanks. It seems that the encfs-file container has a problem and there is no fsck for fuse-fs as far as what my google-fu told me.
So I moved now new_snapshot to new_snapshot.old (because I couldn't delete it because of a non-empty folder that is empty) and now it works.

**Comment by Germar** [comment]
You can also use `encfsctl encode /path/to/.encfs6.xml backintime/HOST/USER/1/new_snapshot` to get the encrypted path of the `new_snapshot` folder and try to remove that directly.

`encfs` should by default write into `syslog`. Is there any hint why it failed to remove?

**Comment by nielsk** [comment]
nothing I can find right now. But since there was an empty folder which I couldn't remove because "it wasn't empty", I'd say that the filesystem in the encfs-container has a problem

**Comment by Germar** [comment]
`encfs` has nothing like a container or a filesystem. It works on file-level. Every plaintext file or folder has it's corresponding encrypted file or folder on the destination drive. So if there is a filesystem problem on the destination drive you'll have the same in the paintext mount.

**Comment by joaoherberto** [comment]
I had the same issue shortly after a system restore. Removing the "new_snapshot" directory per Germar worked but there was some kind of permissions issue, I could not delete it for some reason.
Now, I have two backup drives, one in my laptop and one external. The internal one has never had any issue. I think the external one may have been in the middle of a back when I disconnected it.
At any rate, what I did is navigate to the actual backup drive folder, for instance mine is /run/media/joao/Backup "Back up is my mounted drive folder", my user name is "joao". Fixed all permissions in that drive by using the "chown" command. First go to where your drive folder is mounted and type: 

> sudo chown -R $USER:$USER Backup
($USER should automatically fill in your user name and group, if not you can do it yourself, for my example is would be sudo chown -R joao:joao Backup) Note: this may take a while depending on the size of your HDD!
Next open BackInTime and select the profile you want to use, this should mount the backup directory in ~/.local/share/backintime/mnt/ there should be a symbolic link to the mounted drive, in my case it was 2_9199/backintime/<host-name>/<user-name>/<profile-num>/  then delete the "new_snapshot".

Worked for me :-)
