### ISSUE TITLE
Repeatedly Backup with Anacron does not work

### ISSUE THREAD

**Issue by jounathaen** [bit-team/backintime#525]
I set a profile with the repeatedly(anacron) option, but it does not get execuded every day (in fact, only when I click "Take Snapshot"). 
I've looked in /etc/anacrontab and there is no entry.
I didn't get asked for root password when creating the Profile (which is afaik necessary to write to anacrontab).
Same situation when I run Back in Time (Root).
(Version  1.1.12)

**Comment by jounathaen** [comment]
Ok, I've found an Instruction on ubuntuusers, and set a script manualy to /etc/cron.daily/ but I've expected that the software does that by itself or gives me a warning...
(nevertheless, I like the software ;-) )

**Comment by Germar** [comment]
The `repeatedly (anacron)` schedule in fact doesn't use anacron. It just simulate the same (and more) features anacron would provide. It creates a schedule in crontab (take a look at `crontab -l`) which will start `backintime backup-job` every 15min. BackInTime by it self will then decide on a timestamp in `~/.local/share/backintime/anacron/` if a new snapshot is necessary or not.

To test the settings just delete the timestamp inside that directory and a new snapshot should run on next quarter hour.

That script from ubuntuusers is not necessary anymore. It's outdated from times when BackInTime didn't support this by its own.
