### ISSUE TITLE
Snapshots are not creating hard links (backup drive completely filled)

### ISSUE THREAD

**Issue by stvn66** [bit-team/backintime#526]
I recently setup Back In Time to backup my home folder to a NFS mounted storage device.  I mounted the NFS drive at /home/synology/ and I setup to perform a daily backing up everything in /home/schowell/ (I am not recursively backing up the backups).  I have just over 2 TB of files in /home/schowell/ and the NFS NAS drive is over 14 TB.  After creating 7 snapshots, the backup storage is now completely full.  

I am confused about why this is happening.  Using the Back In Time interface to navigate the files in a given snopshot, I can select a file using left click, choose "Snapshots", then toggle "List only different snapshots" and the only revision is "Now".  It seems Back In Time recognizes the file has not changed but the 14 TB are full and I am not sure what to do about it.  Thanks for any help.

**Comment by Germar** [comment]
Your NFS mount might not support hard-links. Please take a look on our FAQ [How to ckeck hard-links](https://github.com/bit-team/backintime/wiki/FAQ#how-can-i-check-if-my-snapshots-are-incremental-using-hard-links)

I'd suggest to not use NFS at all. It's very slow to sync onto a mounted share. You should rather use BackInTimes 'SSH' mode. Take a look at FAQ [How to use Synology](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-synology-dsm-5-with-bit-over-ssh)

**Comment by stvn66** [comment]
Performing the check did verify it was not creating hard-links.

I setup `SSH` backing up instead which seemed to be working.  Thanks for the recommendation!  I updated the How to use Synology as I did.  Hope that helps others.

**Comment by Germar** [comment]
Great! Thanks for the edit. I just added a note on how to save and exit in vi
