### ISSUE TITLE
Lack of documentation on setting up encrypted backups.

### ISSUE THREAD

**Issue by sudhirkhanger** [bit-team/backintime#527]
Hi,

As a user I am having a very hard time figuring out how to setup encrypted backups with BiT. I can find not documentation whatsoever. Can you provide some basic information on how to setup encrypted backups with BiT?

Thanks.

**Comment by Germar** [comment]
You only need to add your user to group `fuse`
```
sudo adduser USER fuse
```
Where `USER` is your own username. Than log out and log in again so the group change take place. Now you can start BackInTime and configure your profile with mode `Local encrypted`

**Comment by sudhirkhanger** [comment]
It turns out I don't need to be in `fuse` to group to create encrypted backup. I just needed to choose `Local encrypted` from the modes.

Will file permissions remain intact on restore if I backup to a filesystem like ntfs formatted external hard drive which doesn't support Linux file permissions? I currently use Deja-dup which created encrypted zip files so that has not been a problem.

**Comment by Germar** [comment]
Oh, sure. `fuse` group depends on your distribution.

As long as you don't choose 'Full rsync mode' in options all permissions will get stored into a special file after a new snapshot was taken. So it doesn't matter if your filesystem doesn't support permissions.

**Comment by sudhirkhanger** [comment]
Thank you. I will begin moving my back up system Back In Time.
