### ISSUE TITLE
Restoring files / directories from snapshot at root fails

### ISSUE THREAD

**Issue by dinoboy197** [bit-team/backintime#530]
Just marking this to follow up - I can work on this.

Note that this is ONLY for snapshots which start at the root, which would be necessary for a full system backup.

Restoring either a single file or a single directory fails. Looks like there are some target file in the snapshot path issues going into the rsync command.

**Comment by Germar** [comment]
:+1:

**Comment by Germar** [comment]
@dinoboy197 could you please have a look if commit bb1d3017cf9e19dce7ee3e0d86ef3b09d09e8b03 fixed this, too?

**Comment by dinoboy197** [comment]
Hey Germar - thanks for checking in! Looks like rsync of files from a root snapshot works, but permission restore is somehow problematic for root-owned files.

I'll take a closer look tomorrow, but in case you want to check it out before me, here is a sample output from restoring a single file from a root snapshot. I created the snapshot just moments ago using HEAD of master branch:
```
rsync -rtDHh --links -pEgo --info=progress2 --no-i-r --rsh="ssh -p 22  -o IdentityFile=/root/.ssh/id_rsa" -R -v 'traack@backup:"/mnt/tank/backup/lune-backintime/backintime/lune/root/1/20160317-202250-685/backup/./core"' "/root/GNUstep/"
receiving file list ... done
core
sent 43 bytes  received 39.96M bytes  2.16M bytes/sec
total size is 39.95M  speedup is 1.00
 
 
Restore permissions:
UID for '-' is not available on this system. Using UID 500 from snapshot.
GID for '-' is not available on this system. Using GID 5000 from snapshot.
chown /root/GNUstep/core 0 : 0

Restore permissions: Done
```

**Comment by Germar** [comment]
Works here without problems. Are you sure you have a user with UID 500 and a group with GID 5000 on your machine?

**Comment by dinoboy197** [comment]
Yep, here is the strange thing - the file that I was trying to restore was a file called "core" at the root mount, which is in fact owner / group root:
```
traack@lune:/$ pwd
/
traack@lune:/$ ls -al core
-rw------- 1 root root 39952384 Apr 19  2015 core
```

I've backed up this file with BIT running as root, and am also trying to restore this file when running as root. I confused as to what UID 500 and GID 5000 have to do with this file at all.

Any bright ideas? It may be a symptom of a different bug or user error entirely; of that I am not sure.

**Comment by dinoboy197** [comment]
OK, looks like I was just caught off-guard by the comment
```
UID for '-' is not available on this system. Using UID 500 from snapshot.
GID for '-' is not available on this system. Using GID 5000 from snapshot.
```
in the logs during permission restore. Looks like the correct permissions actually were applied. False alarm!

**Comment by Germar** [comment]
Would still be interested in where this comes from...

Oh, I just see that my last post in here didn't show up (maybe I forgot to press `Comment`!?). Anyways, would you please post the `info` file and the line regarding `/core` from `fileinfo.bz2`?

**Comment by dinoboy197** [comment]
Yes! Here is the info you're looking for:

[Here is the info file from the latest backup, again using HEAD of master](https://github.com/bit-team/backintime/files/187267/info.txt)

Here is the relevant line from the fileinfo.bz2 file:
```
33152 root root /core
```

I have no user with uid 500 on my system, nor a group with gid 5000. All very puzzling. Enjoy!

**Comment by Germar** [comment]
Thanks. I'll have a look. I also had the same on my server (running BIT 1.1.12) yesterday...
