### ISSUE TITLE
.desktop Icon reference deprecated for GTK+ 3

### ISSUE THREAD

**Issue by puenka** [bit-team/backintime#535]
Hey, I just quickly wanted to inform about an issue (I haven't checked whether it's been corrected with a newer version) on my Fedora machine (backintime release 1.0.36):

The correct icon simply doesn't appear in the applications menu (Gnome 3).
It seems that the .desktop entry (well, entries, both for user and root) is being created with an icon reference to "gtk-save", which however has been deprecated, likewise all the GTK-STOCK-ITEMS for Gnome since 3.10.

The new placeholder seems to be "document-save", but I do not know anything about your aims regarding backwards compatibility to GTK+ 2 e.g.

**Comment by Germar** [comment]
Thanks. BackInTime >= `1.1.0` already uses `document-save`.
