### ISSUE TITLE
[E] Error: rsync: failed to set times on [..]: Invalid argument (22)

### ISSUE THREAD

**Issue by caco3** [bit-team/backintime#536]
Since a while every backup shows the same errors in the log.
It's always the same few files:
```[E] Error: rsync: failed to set times on ".../.rm4scc_size_setting.png": Invalid argument (22)```

I altered the access rights to those files, but no success.
I renamed the folder containing them, no success.
I even renamed them, but still same error.
Only when I delete the files, the errors go away. 
But when I add the files again (even with another name), the errors show up again.

How can I fix this?

I am accessing the backup drive through NFS:
```192.168.1.xx:/volume1/BackinTime on /media/ds_BackinTime type nfs4 (rw,nosuid,nodev,noexec,relatime,vers=4.0,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.xx,local_lock=none,addr=192.168.1.xx,user)```

**Comment by Germar** [comment]
A [quick search](http://stackoverflow.com/a/668049/1139841) suggested adding `--omit-dir-times` to your mount command. But I'd rather skip NFS completely and switch over to SSH mode in BIT. It's a lot faster... Take a look at `man backintime` section SSH

**Comment by caco3** [comment]
Thank you for your help!
And thank you for document it that well in the man page!
The NFS link you mention seems not to fit my issue (different error message).
Also I could not yet figure out how the omit parameter should be used in the fstab configuration. I even found pages where they state that it is not possible with NFS.

I think it would be more appropriate to use rsync.
I succeeded to extend my SSH access to use the key, but then I run into the issue 3072, which is already discussed on http://superuser.com/questions/996928/backup-of-a-linux-desktop-on-a-synology-nas-ds-5-2-using-backintime. Further more, it was you who gave a detailed answer there. :) I will have a look on it. If possible, I want to avoid having to compile rsync or use optware. Not because I can't (have done it many times), but more because Synology resets those configurations again almost on every update.

**Comment by Germar** [comment]
Please follow the [HowTo on our wiki](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-synology-dsm-5-with-bit-over-ssh). There where some more infos added couple days ago.

I don't own a Synology device, so I can't provide experience (just did the same for my WD MyBook which is working quite well). But I know from couple feedbacks that this works well on Synology, too.

Using an rsync daemon for destination would be great for sure. But this is at the moment not possible as BIT need to run more than just rsync on remote host.

**Comment by caco3** [comment]
I configured by Diskstation as suggested in the wiki
I am able to remote mount the folder with
```sshfs -p 5071 -o ServerAliveInterval=240 -o IdentityFile=/home/root/.ssh/id_rsa -o idmap=user backup@192.168.1.99:/volume1/backups/BackinTime /tmp/bb```
Even as a normal user and without a password it works.
How ever when I try it in BackinTime, I always get a "Permission denied, please try again."

Note that on my Diskstation the SFTP Port is set to 5071. But also with 22 it doesn't work.

**Comment by Germar** [comment]
So you have `ssh` and `sftp` on different ports? This is not covered by BIT (I even didn't know that his is possible). BackInTime need to run commands on the remote host through `ssh` and mount the remote folder with `sshfs` both from the same remote port

**Comment by caco3** [comment]
I am not sure if SFTP was on 5071 as default or if I changed it myself sometimes.

Anyway, I got it working now with non-standard ports, but had to learn quite a bit.
There are in total 3 places where you have to set the correct port (if not using the standard 22):
1. Control Panel > Terminal: ```Port = <PORT_NUMBER>```
2. Control Panel > FTP > SFTP: ```Port = <PORT_NUMBER>```
3. Backup & Replication > Backup Services > Network Backup Destination: ```SSH encryption port = <PORT_NUMBER>```

Only if all 3 of them are set to the same port, BackinTime is able to establish the connection.
As a test, one can run the command 
```rsync -rtDHh --checksum --links --no-p --no-g --no-o --info=progress2 --no-i-r --rsh="ssh -p <PORT_NUMBER>  -o IdentityFile=/home/<USER>/.ssh/id_rsa"  --dry-run --chmod=Du+wx /tmp/<EXISTING_FOLDER> "<USER_ON_DISKSTATION>@<SERVER_IP>:/volume1/Backups/BackinTime"``` in a terminal (on the client PC).

I will update the wiki to make this more clear.

Thank you for your support and great work with BackinTime!

**Comment by Germar** [comment]
Thanks for the edit. But reading `All keys were skipped because they already exist on the remote system.` makes me wonder why you manually installed them again!? Did you test login but still have been asked for your password?

**Comment by caco3** [comment]
I am not exactly sure where the issue was. I tried to copy it several timers, also to several different user homes on the Diskstation. In all cases, I got this message and still had to use the password.
Then I copied the mentioned file manually and then it worked.
I playes around a lot with my Diskstation, so maybe I had the keys already somewhere.

**Comment by Germar** [comment]
Okay. May be a bug in `ssh-copy-id`. I'll change your command in a way already existing keys won't get overwritten by the manual copy.
