### ISSUE TITLE
read-only mount breaks tools.update_cached_fs()

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#540]
OSError on `tools.update_cached_fs()` in GUI in combination with new read-only mounts. Need to search for a different solution on how to update fuse mounts for GUI.

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 630, in update_take_snapshot
    tools.update_cached_fs(self.config.get_snapshots_full_path())
  File "/usr/share/backintime/common/tools.py", line 993, in update_cached_fs
    with tempfile.NamedTemporaryFile('w', dir = dir) as f:
  File "/usr/lib/python3.4/tempfile.py", line 623, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python3.4/tempfile.py", line 346, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
OSError: [Errno 30] Read-only file system: '/home/germar/.local/share/backintime/mnt/...'
```

**Comment by dinoboy197** [comment]
Ah, nice find. I think this addition got committed right around the time that I pushed the r/o ssh work to master, and I had tested exhaustively way before I rebased the ```update_cached_fs()``` commit into my feature branch. Oops!

Would you like me to patch this up by allowing the mount to be r/w while the ```update_cached_fs()``` method is executing in ```tools.py```?

**Comment by Germar** [comment]
That's right. I added that `tools.update_cached_fs()` round about at the same time. There is an other one, but that one is only called after deleting multiple snapshots at once. So you couldn't find this.

No, remounting is not an option. Problem here is that the mounted view on the remote files is not in sync immediately after files had been changed directly on the destination (NOT through the fuse-mount). Writing a dummy file was just a trick to force a new sync. I'll try to find an other trick. Maybe `stat` or `open` a non-existing file will do the same...

**Comment by Germar** [comment]
Okay, I think there is a better solution. I need to rewrite Timeline again (already did that couple weeks ago). This time I'll use a `QFileSystemModel` instead of `snapshots.iterSnapshots()` to fill the Timeline. `QFileSystemModel` uses `inotify` so the changes will update automatically after fuse updated its cache.

**Comment by Germar** [comment]
`QFileSystemModel` doesn't notice the remote changes. Even Nautilus doesn't recognize it. So pure `inotify` won't work either.

But I found an even better solution with `-o cache_dir_timeout=2` for sshfs.
