### ISSUE TITLE
Remove individual files from snapshots in GUI fail because of read-only

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#544]
Removing files in `Snapshots` dialog will fail with traceback

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/snapshotsdialog.py", line 402, in run
    self.snapshots.delete_path(item.snapshotID(), self.parent.path)
  File "/usr/share/backintime/common/snapshots.py", line 1911, in delete_path
    os.chmod(dirname, dir_st.st_mode | stat.S_IWUSR)
OSError: [Errno 30] Read-only file system: '/path'
```

I'm planning to rewrite `Snapshots.remove_snapshot()` to use `rsync <EMPTY_DIR> DST` instead of `find -exec chmod...; rm -rf ...`. Should be a lot faster as mentioned in #151. I'll rewrite `Snapshots.delete_path()` to use the same process, too.

**Comment by dinoboy197** [comment]
Sounds good. I'll watch out for some changes on this issue and will create a regression test for it!

**Comment by Germar** [comment]
after rolling back `read-only mount` this is fixed
