### ISSUE TITLE
Can't find anacron

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#546]
When I set schedule to **"Daily (anacron)**" I immediately see the following error message:

> Can't find anacron.
> Are you sure anacron is installed ?
> If not you should disable daily anacron backups.

anacron 2.23-3 is installed on my debian 8.3 stable.

What should I do?

**Comment by Germar** [comment]
What does `which anacron` print on command line? I just had a look into Debians anacron package. The binary is in `/usr/sbin/anacron`. Maybe `/usr/sbin` is not in your `PATH` environment!?

**Comment by dx486** [comment]
`which anacron` does not print anything. 

True, it is in `/usr/sbin` not in my `PATH` environment. I guess I should add this directory to `PATH` to fix this error.

**Comment by Germar** [comment]
Jepp, right. Sorry I forgot to mention that...

**Comment by dx486** [comment]
Sorry for such a basic question. You may close this issue now.
Just a suggestion: Maybe you can change the error message as: _"Are you sure anacron is installed and in PATH?"_

**Comment by Germar** [comment]
No worries. Current version doesn't need anacron anymore. BIT will do anacron's part now by it's own. So that message is gone, too.
