### ISSUE TITLE
Februrary 29 invalid date

### ISSUE THREAD

**Issue by fossildoc** [bit-team/backintime#551]
Backintime fails to work on the leap day, February 29. It complains that the date is invalid.

**Comment by Germar** [comment]
Could you please run BIT from Terminal and post the output? It's already March 1. here...

**Comment by fossildoc** [comment]
INFO: Lock
INFO: [GnomePlugin.Systray.run]
 INFO: on process begins
INFO: [GnomePlugin.Systray.run] begin loop
INFO: Profile_id: 5
INFO: Compare with old snapshot: 20160229-082656-300
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -i --dry-run --out-format="BACKINTIME: %i %n%L" --chmod=Du+wx  --exclude="/mnt/backup" --exclude="/home/richard/.local/share/backintime" --include="/home/richard/Documents/languages/german/" --include="/home/richard/Documents/languages/" --include="/home/richard/Documents/" --include="/home/richard/" --include="/home/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/richard/Ubuntu One" --exclude=".dropbox*" --exclude="/home/richard/Documents/languages/german/germanbackup.zip" --exclude=".~lock*" --include="/home/richard/Documents/languages/german/**" --exclude="*" / "/mnt/backup/backintime/g7/root/5/20160229-082656-300/backup/"" returns 0
INFO: Create hard-links
INFO: Command "find "/mnt/backup/backintime/g7/root/5/20160229-082656-300/backup/" -type d -exec chmod u+wx {} \;" returns 0
INFO: Command "cp -aRl "/mnt/backup/backintime/g7/root/5/20160229-082656-300/backup/"* "/mnt/backup/backintime/g7/root/5/new_snapshot/backup/"" returns 0
INFO: Command "find "/mnt/backup/backintime/g7/root/5/20160229-082656-300/backup/" -type d -exec chmod a-w {} \;" returns 0
INFO: Command "chmod -R a+w "/mnt/backup/backintime/g7/root/5/new_snapshot"" returns 0
INFO: Call rsync to take the snapshot
INFO: Command "rsync -rtDH --links --no-p --no-g --no-o  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/mnt/backup" --exclude="/home/richard/.local/share/backintime" --include="/home/richard/Documents/languages/german/" --include="/home/richard/Documents/languages/" --include="/home/richard/Documents/" --include="/home/richard/" --include="/home/" --exclude=".gvfs" --exclude=".cache*" --exclude="[Cc]ache*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude="/home/richard/Ubuntu One" --exclude=".dropbox*" --exclude="/home/richard/Documents/languages/german/germanbackup.zip" --exclude=".~lock*" --include="/home/richard/Documents/languages/german/**" --exclude="*" / "/mnt/backup/backintime/g7/root/5/new_snapshot/backup/" 2>&1" returns 0
INFO: Save config file
INFO: Command "cp /home/richard/.config/backintime/config /mnt/backup/backintime/g7/root/5/new_snapshot/backup/.." returns 0
INFO: Save permissions
INFO: Create info file
INFO: Command "chmod -R a-w "/mnt/backup/backintime/g7/root/5/20160229-212941-932/backup"" returns 0
INFO: Command "chmod -R a-w "/mnt/backup/backintime/g7/root/5/20160229-082656-300/backup/"" returns 0
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 208, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 120, in start_app
    take_snapshot( cfg, True )
  File "/usr/share/backintime/common/backintime.py", line 47, in take_snapshot
    snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 822, in take_snapshot
    self._free_space( now )
  File "/usr/share/backintime/common/snapshots.py", line 1348, in _free_space
    old_backup_id = self.get_snapshot_id( self.config.get_remove_old_snapshots_date() )
  File "/usr/share/backintime/common/config.py", line 516, in get_remove_old_snapshots_date
    return date.replace( year = date.year - value )
ValueError: day is out of range for month

**Comment by Germar** [comment]
You're still using BackInTime 1.0.6!? This has been fixed four years ago. Please upgrade to a more recent version.
