### ISSUE TITLE
Can't open files with spaces in name (or space in folder name)

### ISSUE THREAD

**Issue by sbaragnaus2** [bit-team/backintime#552]
Hi,
I'm using backintime-qt 1.1.12 in Manjaro Linux (Kde 5.5.4, Qt 5.5.1, Kernel 4.4.3).

I can't open a file from snapshot if the file name (or folder name) contains spaces.

For example, if I try to open "spa ces.txt" from "Test folder" I have this error message:

_Error -- KIO Client
Unable to run the command specified. The file or folder /run/media/myusername/Dati_Linux/Test%20folder/spa%ces.txt does not exist_

The same happens if I try to open file "test name with spaces.txt" from "Test" folder.

I haven't any problems opening a file "testname.txt" from "Test" folder (no spaces in names).

Here are some screenshots:

http://postimg.org/image/9dv9dpne9/ (folder structure)

http://postimg.org/image/5xfpo18cx/ (error message)

Is this a bug?

**Comment by Germar** [comment]
Jepp, it is. Thanks for reporting

**Comment by sbaragnaus2** [comment]
Hi, 
this bug is still present in Back in time 1.1.20. Why don't you backport to 1.1.x series? I've read release date for 1.2.0 has not been set yet.

Thanks
