### ISSUE TITLE
List of Issues with Synology DSM 6

### ISSUE THREAD

**Issue by caco3** [bit-team/backintime#553]
This is not a real BackinTime related issue but more a list of issues concerned the usage with the Synology DSM 6.

There are some instructions in the wiki (https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-synology-dsm-5-with-bit-over-ssh), but they are mostly related to DSM 5 and do not work anymore on DSM 6.
To keep track of those issues and to have a platform to discuss them, I started this issue. If there is a better way for this please let me know.

**Comment by caco3** [comment]
Issue #1: When a new diskstation user (i.e. backup) gets created, one has to give it access to the shell by changing the shell in /etc/passwd. This works as expected, how ever after a few minutes, the shell gets reset to its default. This was working correctly in DSM 5!
Note: This is only related of using rsync over SSH!

**Comment by caco3** [comment]
Issue #2: SŜH login as non-root does not work anymore, see also https://forum.synology.com/enu/viewtopic.php?f=260&t=115444

A bug report was sent to Synology and I will post here when there is an update.

**Comment by Germar** [comment]
Thanks for sharing your experience here with others. I don't own a Synology device so I can't help. Only one thing: please don't use `#Number` because GitHub will link this to the bug with that number and at the moment there is no way to remove those false links again

**Comment by caco3** [comment]
No problem. I removed the #Number (I still can edit my comments).

**Comment by Germar** [comment]
Next release 1.2.0 (no release date yet) should make it lot easier with a NAS because almost everything will be done only with `rsync`. No need for full featured `find ... -exec` support anymore :raised_hands:

**Comment by mabl** [comment]
> Next release 1.2.0 (no release date yet) should make it lot easier with a NAS because almost everything will be done only with rsync. 

Hi @Germar, is there any news on this? I'd really like to try it out.

**Comment by Germar** [comment]
@mabl  if you're using Ubuntu you can try our testing PPA. It's already in there

    sudo add-apt-repository ppa:bit-team/testing
    sudo apt-get update
    sudo apt-get upgrade

Or you can [install from source](https://github.com/bit-team/backintime#from-sources).

**Comment by helge42** [comment]
Hi,
I have DSM6 and tried the instructions mentioned above. When I do " ssh backup@synology " the root file system is the home directory of the user backup. This differs from the instructions and it did not work.
Any ideas?
Sincerely, Helge

**Comment by szma** [comment]
I am using BIT with DSM 6 over SSH. I followed the DSM 5 instruction and had to add "--rsync-path=/bin/rsync" to the rsync flag in the settings.

**Comment by helge42** [comment]
Hi,
I got it!

On DSM 6 you can edit the user-root-dir for sFTP 
Control Panel -> File Services -> FTP -> General -> Advanced Settings -> Security Settings -> Change user root directories -> Select User
Now select the user "backup" and Change root directory to "User home"

That's it. The ssh user-root-directory is on DSM6 the "User home" by default. 

No extra Volumes or bind-mounts on Synology, this not necessary anymore ;). Everything is now in the home-dir of the user backup.
In BackinTime I started with a fresh profile.

Sincerely, Helge

**Comment by Germar** [comment]
It would be great if one of you guys could modify the FAQ for DSM6. It's world writeable. Just copy and modify the DSM5 section.
Thanks in advance!

**Comment by helge42** [comment]
Yes, I will update the FAQ. 

But I have a question for szma to get the things right:
Do you have activated the home service? (The second item of the FAQ)
If you didn't:  there are two ways to get the things working. Yours and mine.

**Comment by simgunz** [comment]
@helge42 Can you elaborate on that?

If my backup folder is stored in /volume1/backups/backintime, what path should I specify in the BIT ssh path settings after applying the suggested settings?

**Comment by helge42** [comment]
I have updated the FAQ: https://github.com/bit-team/backintime/wiki/FAQ#id23

@simgunz You can leave the path empty. BIT will create a folder "backintime" in the home directory. Please leave a note, if the FAQ for DSM6 is right.

**Comment by simgunz** [comment]
@helge42 In the FAQ I would still advise to create a new share to keep the backups instead of having them in the home of the user backup. Then in the SFTP home settings the user can select this share as root for the user. Isn't it more clean?

**Comment by simgunz** [comment]
My previous post was wrong, because setting the ``backups`` share as root for SFTP  doesn't solve the problem that the root for SSH is different.

I've tried a different approach:
1. Set the SFTP root to the backup user home
2. Create a symlink as follow (as user backup)

    mkdir /volume1/homes/backup/volume1
    ln -s /volume1/backups/ /volume1/homes/backup/volume1/backups

3. Set as target path in BIT ``/volume1/backups``

Still this approach doesn't work.

    sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/home/simone/.ssh/backup_id_rsa backup@192.168.0.250:/volume1/backups /home/simone/.local/share/backintime/mnt/D8BF5749/mountpoint

I get ``backup@192.168.0.250:/volume1/backups: Not a directory``

If I mount /volume1 only, I the mount is fine but then I cannot access or list the ``backups`` directory (which is the symlink)

   ls /home/simone/.local/share/backintime/mnt/D8BF5749/mountpoint/backups

produce ``ls: cannot read symbolic link '/home/simone/.local/share/backintime/mnt/D8BF5749/mountpoint/backups': Bad message``

This is probably why the mount bind was needed in the first place with DSM5, right?

**Comment by helge42** [comment]
Yes. I think with DSM6 you can only use the homedirs for backintime. Only you can alter the root directory for SSH there will be the way described for DSM5.
But there is an advantage: now every user can install and configure his own backintime backup! The user can take his homedir on the synology. No superuser access is needed. (if you have more users ;)

**Comment by helge42** [comment]
There are issues in this configuration: 

Backup of files greater then 500MiB yields to a brocken pipe. You must activate this option to prevent this.

The transfer rate which is shown is not correct: it increases all the time.

**Comment by Germar** [comment]
Thanks everyone for putting this together! I highly appreciate it!

@helge42 if you manually transfer a file >500MiB does `rsync` yield a broken pipe, too? Which rsync version is used on DSM6?

The transfer rate is incorrect. Has nothing to do with DSM6. rsync doesn't provide a better result.

**Comment by szma** [comment]
@helge42 sorry, for the late response, but yes I have enabled the home service as stated in the FAQ.

**Comment by derrafa** [comment]
Hi everybody. 
I just bought a Synology Diskstation and wanted to move my bit-backup there. I tried that now for a couple of days but didn't succeed.
My issue is that I wanted to have the backup in an encrypted folder. Since DSM6 only supports encrypted shared folders the home-folder solution mentioned above doesn't work and because of the encfs security issues I would rather not use bit-encryption.

Is there any other way?

Thanks!

**Comment by szma** [comment]
@derrafa Imho you can use the DSM5 way and backup to a shared folder. Don't forget to add "--rsync-path=/bin/rsync" as additional option in your bit profile.

**Comment by derrafa** [comment]
Thanks a lot, it worked!

**Comment by caco3** [comment]
Just a note:
2 days ago I got the following error:
![grafik](https://cloud.githubusercontent.com/assets/1783586/22269302/2061424a-e28b-11e6-9a14-848baea9d460.png)
Opening the BiT config and pressing apply showed this:
> Permission denied, please try again.
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]

It might have been due to an update or some unwanted changes on the synology system.
Anyway, it got solved by enabling the rsync service in the control panel:
![grafik](https://cloud.githubusercontent.com/assets/1783586/22269347/4cc84fc2-e28b-11e6-9e0d-ef4f539d1fb5.png)
Since this was not yet documented in the wiki, I guess it might be a new config. I now updated the wiki.

**Comment by caco3** [comment]
Update:
It was caused by the fact that I removed the shared folder NetBackup. How ever actually DSM shows a warning:
![grafik](https://cloud.githubusercontent.com/assets/1783586/22269503/e7c8fd28-e28b-11e6-954c-93cdc38e8dfb.png)

**Comment by Proton23** [comment]
Hi!

I would like to encrypt the folder like derrafa did, but I don't know what you mean with "the DSM5 way".
I guess you mean this https://github.com/bit-team/backintime/wiki/Hardware-Specific-Setups#how-to-use-synology-dsm-5-with-bit-over-ssh

What steps are necessary?

Best regards

**Comment by szma** [comment]
It's been a while, but basically you have the right link. I did steps 1-15, leaving out the rest, because I already can login to my NAS without password.
Then, when configuring your backintime profile, add "--rsync-path=/bin/rsync" as additional option.

**Comment by Proton23** [comment]
Thanks for the answer, but I decided that it's to much effort (didn't know the path to enter and so on) and putting everything into home is actually a very good solution.
