### ISSUE TITLE
Backup not incremental. Permission problems? How to debug?

### ISSUE THREAD

**Issue by simgunz** [bit-team/backintime#557]
HI,
I've setup an SSH profile to backup over a Synology NAS. The configuration worked fine three times, creating incremental backups (I've verified the inode information), while now the backup is not incremental any more for some reason (BUT tries to copy everything instead of creating hard links)

My questions are: 
1) how backintime determines if a file needs to be hardlinked or backed up? Based on date modified, permission changed, what else?
2) How can I debug this behavior? How can I compare the two files and see what has changed?  or by seeing what BIT thinks has changed?

Extra info:
- The file I use as test case has never been modified.
- I've try to run diff between this file in a previous backup and the same file in new_snapshot but diff doesn't return anything, so I guess they are equal.
- The permission between these two files differs tough. The file in the backup folder has attributes 777 (set by BIT?) the other file in new_snapshot 755.
- The fileinfo file in the previous backup folder contains only the two following lines

    16877 root root /media
    16877 root root /media/dataHD

where dataHD is the backup target directory.
Should it contain the file permissions for all the files in the backup directory tree?
- I'm NOT using full rsync mode

**Comment by simgunz** [comment]
I've found the problem. The last backup was empty for some reason (the "WITH ERROR" label was not present tough), so backintime was trying to backup everything again. By removing the empty backup, the new backup has been based on the previous non-empy one and everything went fine.

**Comment by Germar** [comment]
Did you already delete the problematic snapshot? Any chance you could post the `takesnapshot.log.bz2`?

**Comment by simgunz** [comment]
Attached you can find the log. I've purged all the parts where my files are listed, but should be useful.

[takesnapshot.log.txt](https://github.com/bit-team/backintime/files/189948/takesnapshot.log.txt)

**Comment by Germar** [comment]
Thanks. What was the Snapshot-ID of the empty snapshot? `20160313-205251-XXX` or `20160313-213002-XXX`?

**Comment by simgunz** [comment]
20160313-213002-639
