### ISSUE TITLE
 Can't remove folder

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#558]
This issue is similar to #524. I changed my backup source and now I have the same problem: 

`Can't remove folder: /home/USER/.local/share/backintime/mnt/2_2804/backintime/HOST/USER/2/new_snapshot`

My backup source is located in a LUKS encrypted volume. Destination is located at the external drive. Backup is local and encrypted.

```
$ ls  -la /home/USER/.local/share/backintime/mnt/2_2804/backintime/HOST/USER/2/
ls: cannot access /home/USER/.local/share/backintime/mnt/2_2804/backintime/HOST/USER/2/: No such file or directory
```

```
$ ls  -la /home/USER/.local/share/backintime/mnt/
total 24
drwx------ 6 USER USER 4096 Mar 25 19:15 .
drwxr-xr-x 7 USER USER 4096 Mar 25 19:15 ..
drwx------ 4 USER USER 4096 Mar 25 19:07 19D7DD7D
lrwxrwxrwx 1 USER USER   59 Mar 25 19:08 2_1918 -> /home/USER/.local/share/backintime/mnt/6B35EF76/mountpoint
drwx------ 4 USER USER 4096 Mar 25 19:00 6B35EF76
drwx------ 4 USER USER 4096 Mar 25 19:07 6D8F30D1
drwx------ 4 USER USER 4096 Mar 25 19:07 A644FAAE
```

To solve it I tried many things and lastly tried to delete everything under `/home/USER/.local/share/backintime/mnt` path but I could not succeed even with sudo. 

I don't understand how to formulate the suggested command `encfsctl encode /path/to/.encfs6.xml backintime/HOST/USER/1/new_snapshot`. Which path should I use as "/path/to/.encfs6.xml" exactly?

I want to delete all configurations/related files of backintime and make a fresh start with new profiles. What should I do for this?

**Comment by Germar** [comment]
If you want to delete just everything than you only need to remove the encrypted folder and the `.encfs6.xml` on your external drive (the path which you gave on `where to save snapshots`).

The mount in `/home/USER/.local/share/backintime/mnt/` is only temporary while the GUI is open or a snapshot is running. It will be unmounted on exit. You can use `backintime snapshots-path --keep-mount` to not unmount.

**Comment by dx486** [comment]
Thank you. I managed to delete all files and folders under snapshot directory (quickly with the help of [this information](http://unix.stackexchange.com/a/79656/156284)) and now I can take backup again without error.
