### ISSUE TITLE
rsync: opendir failed: Permission denied (13)

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#559]
I have no problem with local encrypted or SSH backups but I get following error during SSH encrypted backup and backup cannot be made.

`Error: rsync: opendir "/home/USER/.local/share/backintime/mnt/574826FE/mountpoint/1VFL,ncX9SIdZzFUHyH8Yf4z/HI11ukY1Oooa65bSlJXIKj2s" failed: Permission denied (13)`

I can use `$ sshfs USER@REMOTEHOST:/ /mnt/mountpoint/` command without any error and use remote directories via mount point.

Could you please help me?

(BIT 1.1.12 on debian 8.3 with Gnome)

**Comment by Germar** [comment]
You're trying to backup a folder for which your user doesn't have read-permissions. Take a look into the snapshot log and activate the `decrypt paths` option in there. This should show decrypt the part after `mountpoint` which is a not read-able path on your root filesystem.
