### ISSUE TITLE
Same source, same backup location, multiple computers

### ISSUE THREAD

**Issue by dx486** [bit-team/backintime#562]
I ask this just to be sure... 

I have a removable drive and I use BIT to make backups of this drive to my server. Is there any risk of doing this using multiple computers at different times? 

I have read #495 but I think that question is about using same directory at one server for different sources. My question is about making backups of the same source to the same directory at one server but using multiple client computers.

**Comment by Germar** [comment]
So your external drive will be connected to different clients which all have the server mounted on the same mountpoint with the same user/permissions? I never tried this before but I see no reason this shouldn't work.

But it would be a lot faster if you'd run Back In Time directly on the server and attach the external drive to the server, too. You can run it on head-less servers or even install just a minimal X and run backintime-qt4 through ssh x-tunneling (`ssh user@host -X`)

**Comment by dx486** [comment]
My files are on this external drive and I work on these files using different computers. I'd like to keep backups of these files to my server using BIT. So, my purpose is to keep up-to-date backups of these files to not lose recent changes for some reason. I cannot attach my drive to my server as it is often physically unreachable.

Using same mountpoint is a detail I might have missed, thank you for pointing that out. Also, SSH X-tunneling is something I should check out. It sounds interesting.

**Comment by Germar** [comment]
Ah, okay. Now I get it. The external is your source and the server is the destination. I thought it was the other way around. With this my last post is nonsense.

But still, your external must be on the same mountpoint on all machines and the config must be the same, too. You could copy/paste it from one to all other.
