### ISSUE TITLE
'Decode paths' in GUI stopped working with bit 1.1.13~trusty

### ISSUE THREAD

**Issue by bentolor** [bit-team/backintime#563]
It seems that with the latest update 1.1.13~trusty the decode path option snapshot log screen   stopped working for my for my encfs/SSH backups.

`backintime-qt4 --debug` does not reveal anything suspicious on the console.

`backintime-qt4 decode '<path>'` still works, though.

**Comment by Germar** [comment]
You're right. Thanks. I rewrote huge parts of `snapshots.py` and forgot to add that part. Will add it soon. In `View Last Log` the `decode paths` options still works.
