### ISSUE TITLE
Failed to restore from backup of unmounted crypted drive

### ISSUE THREAD

**Issue by harmancode** [bit-team/backintime#564]
I have a local encrypted backup of a drive which is encrypted by cryptsetup. BIT fails to restore from this local backup when enrcypted drive is not mounted. It does not give any restore output. When the drive is mounted restore works.

(BIT 1.1.12 on debian 8.3 with Gnome)

**Comment by Germar** [comment]
Just to get the facts correct this time ;)

1. you have a profile with mode `Local encrypted` with some snapshots from which you want to restore
2. a secondary drive encrypted with `cryptsetup` was the source to those snapshots
3. when the drive from 2. is not mounted you can't restore

Is this correct?

Did you try to restore to the original location or did you choose `Restore to...` which will let you choose a new destination.

**Comment by buhtzz** [comment]
@harmancode  There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

@emtiu Feedback

**Comment by emtiu** [comment]
Closing as outdated.
