### ISSUE TITLE
Translating to Dutch (nl)

### ISSUE THREAD

**Issue by linuxned** [bit-team/backintime#565]
Hi

I´am translating to Dutch (nl) but I am a little confused, maybe you can help me.

String (qt4/app.py:221 )
Restore selected files or folders to the original destination and delete files/folders in which are not in the snapshot. This will also delete files/folders which where excluded during taking the snapshot.! Be extremely careful!!!

What is the difference between ´delete files/folders in which are not in the snapshot´ and ´delete files/folders which where excluded during taking the snapshot´ ?

Thanks and greetings.
Rob

**Comment by Germar** [comment]
Oh, I've seen there is a typo 'and delete files/folders **in** which'. I updated the template. Should be on Launchpad, soon.

- `delete files/folders in which are not in the snapshot` should mean that files which did not exist during creating the snapshots will be deleted.
- `delete files/folders which where excluded during taking the snapshot` this is more like a warning that this will also delete those files which have been on in the original path but have been excluded.

The whole point of this option is to restore the folder exactly like it was before. But if there where excluded files in there before than this will differ.

**Comment by linuxned** [comment]
Thanks for your fast reply and explanation Germar.
But is it possible not to use the word ´also´ because I think if you leave
out the word ´also´ it becomes much clearer what it means.

Restore selected files or folders to the original destination and delete
files/folders which are not in the snapshot. This will also delete
files/folders which where excluded during taking the snapshot! Be extremely
careful!!!

Greetings,
Rob

2016-03-29 0:09 GMT+02:00 Germar Reitze <notifications@github.com>:

**Comment by linuxned** [comment]
Sorry I meant:

Restore selected files or folders to the original destination and delete
files/folders which are not in the snapshot. This will delete files/folders
which where excluded during taking the snapshot! Be extremely careful!!!

2016-03-29 16:58 GMT+02:00 Rob van den Berg <linuxned@gmail.com>:

**Comment by Germar** [comment]
You're right. Sounds better without.

Don't hesitate to suggest thinks like this in future. I'm no native english speaker and I'm always happy if someone help to make it more readable or fixes typos. Thanks

**Comment by linuxned** [comment]
Thanks Germar

Greetings,
Rob

2016-03-29 23:09 GMT+02:00 Germar Reitze <notifications@github.com>:
