### ISSUE TITLE
dbus exception on start of backintime 1.1.12 under opensuse leap

### ISSUE THREAD

**Issue by sacxue** [bit-team/backintime#566]
Hello,

I'm trying to install backintime 1.1.12 under opensuse leap 42.1. As suddenly the distribution version 1.0.6 stopped working with a problem that I thing might be solved after 1.0.8.

I started with installing the rpm from the tumbleweed release. As this didn't work I tried to also install from source. Both times the error is the same:

======================================================================
ERROR: test_None_as_config (test.test_snapshots.TestSnapShots)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

**Comment by Germar** [comment]
That test doesn't pass without installing BackInTime before. Please install it without running test before

    cd common
    ./configure
    make
    sudo make install

BTW 1.0.6 is still the latest version in current OpenSuse? :flushed:

**Comment by sacxue** [comment]
In OpenSuse Leap 1.0.6 is the latest version I was offered. I switched backintime to the tumbleweed version to get 1.1.12. I installed that rpm before trying from source and got the same error on start up as in the test. I nevertheless now finished the installation from source but nothing changed. After installation it is throwing the same error on start up.

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3.4/site-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3.4/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

**Comment by Germar** [comment]
I'm currently downloading the OpenSuse Leap image. I'll report back as soon as I've installed it inside a VM

**Comment by Germar** [comment]
I wasn't able to reproduce this on fresh installed OpenSuse Leap 42.1 with BIT 1.1.12 from source tarball. Both the test and the GUI it self run without problems here.

Please post the output of

    ls -la /usr/share/dbus-1/system-services/
    qdbus --system

**Comment by sacxue** [comment]
ls -la /usr/share/dbus-1/system-services/
insgesamt 136
drwxr-xr-x 1 root root 2266  3. Apr 18:15 .
drwxr-xr-x 1 root root  110 13. Jan 09:05 ..
-rw-r--r-- 1 root root  208  1. Okt 2015  fi.epitest.hostap.WPASupplicant.service
-rw-r--r-- 1 root root  198  1. Okt 2015  fi.w1.wpa_supplicant1.service
-rw-r--r-- 1 root root  135 13. Jan 09:05 net.launchpad.backintime.serviceHelper.service
-rw-r--r-- 1 root root  106 25. Okt 15:45 net.sourceforge.smb4k.mounthelper.service
-rw-r--r-- 1 root root   95 13. Okt 21:15 org.bluez.service
-rw-r--r-- 1 root root  125 11. Sep 2015  org.freedesktop.Accounts.service
-rw-r--r-- 1 root root  971  7. Nov 18:42 org.freedesktop.Avahi.service
-rw-r--r-- 1 root root  419 25. Feb 21:11 org.freedesktop.hostname1.service
-rw-r--r-- 1 root root  415 25. Feb 21:11 org.freedesktop.locale1.service
-rw-r--r-- 1 root root  413 25. Feb 21:11 org.freedesktop.login1.service
-rw-r--r-- 1 root root  417 25. Feb 21:11 org.freedesktop.machine1.service
-rw-r--r-- 1 root root  445 11. Sep 2015  org.freedesktop.ModemManager1.service
-rw-r--r-- 1 root root  148 29. Feb 11:04 org.freedesktop.nm_dispatcher.service
-rw-r--r-- 1 root root  119 14. Okt 01:12 org.freedesktop.PackageKit.service
-rw-r--r-- 1 root root  130 18. Nov 17:00 org.freedesktop.PolicyKit1.service
-rw-r--r-- 1 root root  835 30. Sep 2015  org.freedesktop.RealtimeKit1.service
-rw-r--r-- 1 root root  364 25. Feb 21:11 org.freedesktop.systemd1.service
-rw-r--r-- 1 root root  419 25. Feb 21:11 org.freedesktop.timedate1.service
-rw-r--r-- 1 root root  127 11. Sep 2015  org.freedesktop.UDisks2.service
-rw-r--r-- 1 root root  114 11. Sep 2015  org.freedesktop.UPower.service
-rw-r--r-- 1 root root  103 25. Okt 13:22 org.gnome.GConf.Defaults.service
-rw-r--r-- 1 root root   94 27. Mär 18:54 org.kde.fontinst.service
-rw-r--r-- 1 root root   82  2. Apr 22:14 org.kde.k3b.service
-rw-r--r-- 1 root root  105 27. Mär 18:54 org.kde.kcontrol.kcmclock.service
-rw-r--r-- 1 root root  110 26. Mär 12:33 org.kde.kcontrol.kcmkwallet5.service
-rw-r--r-- 1 root root  107 24. Mär 13:20 org.kde.kcontrol.kcmkwallet.service
-rw-r--r-- 1 root root  117  1. Apr 00:26 org.kde.kcontrol.kcmremotewidgets.service
-rw-r--r-- 1 root root  105  3. Mär 18:17 org.kde.kcontrol.kcmsddm.service
-rw-r--r-- 1 root root  125  3. Mär 19:53 org.kde.ksysguard.processlisthelper.service
-rw-r--r-- 1 root root  112  3. Mär 22:44 org.kde.powerdevil.backlighthelper.service
-rw-r--r-- 1 root root  106 30. Sep 2015  org.opensuse.CupsPkHelper.Mechanism.service
-rw-r--r-- 1 root root  109 15. Jan 18:12 org.opensuse.Snapper.service
-rw-r--r-- 1 root root  139 25. Okt 15:51 org.opensuse.YaST.modules.service
-rw-r--r-- 1 root root  126 25. Okt 15:51 org.opensuse.yast.SCR.service

 qdbus --system
:1.0
 org.freedesktop.systemd1
:1.1
 fi.epitest.hostap.WPASupplicant
 fi.w1.wpa_supplicant1
:1.10
 org.opensuse.Network.Nanny
:1.11
:1.16
:1.17
:1.18
:1.19
:1.2
 org.freedesktop.Avahi
:1.22
:1.24
 org.freedesktop.DisplayManager
:1.25
:1.28
 org.freedesktop.UDisks2
:1.29
 org.freedesktop.UPower
:1.3
 org.freedesktop.ModemManager1
:1.30
:1.32
 com.redhat.NewPrinterNotification
:1.33
:1.34
:1.35
:1.36
:1.37
:1.38
:1.4
 org.freedesktop.login1
:1.40
 org.freedesktop.RealtimeKit1
:1.42
:1.43
:1.46
:1.47
 org.bluez
:1.49
:1.5
 org.freedesktop.PolicyKit1
:1.50
:1.51
:1.53
:1.54
:1.55
:1.58
:1.59
:1.6
 org.opensuse.Network.DHCP6
:1.7
 org.opensuse.Network.AUTO4
:1.8
 org.opensuse.Network.DHCP4
:1.9
 org.opensuse.Network
org.freedesktop.DBus

**Comment by Germar** [comment]
Seems like there is a problem with your dbus daemon. It doesn't load these systembus services:

```
net.launchpad.backintime.serviceHelper.service
net.sourceforge.smb4k.mounthelper.service
org.gnome.GConf.Defaults.service
org.kde.fontinst.service
org.kde.k3b.service
org.kde.kcontrol.kcmclock.service
org.kde.kcontrol.kcmkwallet5.service
org.kde.kcontrol.kcmkwallet.service
org.kde.kcontrol.kcmremotewidgets.service
org.kde.kcontrol.kcmsddm.service
org.kde.ksysguard.processlisthelper.service
org.kde.powerdevil.backlighthelper.service
```

Please ask at OpenSuse for help on this. I never used OpenSuse before and can't help on this.
