### ISSUE TITLE
Documentation requests

### ISSUE THREAD

**Issue by zzottel** [bit-team/backintime#570]
Apart from the existing GUI documentation, I'd politely suggest a FAQ, which could, among other questions, answer the following I have myself:

- What happens if I hibernate/power down the computer while a backup is running, or if a power outage happens?
- What happens if there is not enough disk space for the current backup?
- Which additional features on top of a GUI does BIT provide over a self-configured rsync backup? I saw that it saves the names for uids and gids, so I assume it can restore correctly even if the ids change. Great! :-) Are there additional benefits?
- If I edit my crontab and add additional entries, will that be a problem for BIT as long as I don't touch its entries? What does it look for in the crontab to find its own entries?
- What is the effect of "Modify for Full System Backup"? From the dialog that follows when clicking this button, I had assumed that some kind of file system dump including boot records would happen, but the backup looks just like any normal rsync backup?

Thanks for this great software, BTW, it is VERY close to the backup tool of my dreams. :-)

**Comment by Germar** [comment]
We already have a [FAQ](https://github.com/bit-team/backintime/wiki/FAQ). I'll answer your questions later this evening.

**Comment by Germar** [comment]
Sorry, took me a bit longer to answer your questions. But it's done now. Please find them in the [FAQ](https://github.com/bit-team/backintime/wiki/FAQ)

**Comment by zzottel** [comment]
Perfect, thanks!
