### ISSUE TITLE
Erroneous exclude line causes "Done, no backup needed"

### ISSUE THREAD

**Issue by Coshibu** [bit-team/backintime#575]
Including an erroneous exclude line will cause a "Done, no backup needed" scenario. 
In my case I added the following line:
"/home/user/Data/.Trash-1000*

but it should be

/home/user/Data/.Trash-1000*

This prevented any snapshots, scheduled or using "Take snapshot"

Setup:
Ubuntu 14.04, backup to usb hard drive

**Comment by Germar** [comment]
I just double-checked. It's already fixed in master with the change from `os.system` to `subprocess.Popen`.
