### ISSUE TITLE
Mountprocess lock timeout

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#576]
Hi all, 

I have been running BIT for many years now on a day to day basis backing up via ssh to a remote server and it works really nice.

However, today when I try to start BIT, I see the "working" pointer spinning for a while, then I get the following message: "Mountprocess lock timeout". Then, BIT gui starts up with no backups listed.

What can I do to fix this? I can log in to the remote server via ssh no problem.

I am using BIT 1.1.12.

The only thing I can think of that may have caused this is that I had to force a shutdown of my computer some days ago when ubuntu froze. I did not pay attention, but perhaps BIT was in the middle of a backup then?

Thanks for any help or suggestion on this matter.

Best regards,

/Sven

**Comment by Germar** [comment]
If reboot doesn't fix this please make sure there is nothing mounted in `/home/USER/.local/share/backintime/mnt`. The command `mount | grep .local/share/backintime/mnt` must show nothing! Then remove the whole folder `/home/USER/.local/share/backintime/mnt`.

**Comment by ersv** [comment]
Thank you Germar! It worked like a charm! 
Due you think it was due to an interrupted backup that it happened? 
Btw, everything seems to work ok now. However, should I trust BIT to recover even when a backup was interrupted? Or should I take any precautionary measures in such a situation?

**Comment by Germar** [comment]
Not sure what caused this. But it was not during taking a snapshot. `mountprocess lock` is used to prevent two processes changing mounts at the same time. After mounting or unmounting is done it will be removed. You probably killed BIT during it was (un-)mounting the remote share. So everything should be fine :v:

But to be absolutely sure you can run one new snapshot with `backintime --checksum backup`. This will take ages but it will also make sure all files are healthy.
