### ISSUE TITLE
Incorrect work with IPv6 SSH target

### ISSUE THREAD

**Issue by zimy** [bit-team/backintime#577]
System: Fedora 24 with a package backintime-gnome 1.1.12
There is two hosts connected by IPv6 overlay network like CJDNS or Teredo.
Can directly connect with SSH like 
```
ssh -i ~/.ssh/id_rsa user@really_long_not_square_bracketed_address
```

The error message with the following text is displayed when specifying that long IPv6 address in host field of backup configuration form with backup type "SSH" and configuring all other aspects and clicking OK:
```
remote host <hostname> doesnt support `rsync .......  --rsh="ssh someparams" --dry-run ... "admin@not_bracketed_ipv6_address"`:3072
```
This text can't be copied from GUI, but I can provide error screenshots by request.

The message above is displayed in error dialog with only button "OK", that closes error dialog and returns back to configuration menu. That dialog can be bypassed by switching now to another and working profile, clicking OK again on equal error about profile with IPv6 and than clicking OK, again, that saves configuration.

Next, when scanning for existing backups on incorrectly saved IPv6 profile another message is displayed:
```
Not exact error message about next command (command is exact) not works: sshfs  -p 22  -o ServerAliveInterval=240 -o IdentityFile=/home/user/.ssh/id_rsa -o idmap=user admin@fc2a:e32:f584:0000:0000:9533:1ccd:9d52:/home/admin/backups /home/user/.local/share/backintime/mnt/25A948BE/mountpoint/
```

Executing following command in terminal leads to `connection closed by peer` message.

However, rightbracketing of IPv6 address in sshfs command makes it working as expected, following command works fine:
```
sshfs  -p 22  -o ServerAliveInterval=240 -o IdentityFile=/home/user/.ssh/id_rsa -o idmap=user admin@[fc2a:e32:f584:0000:0000:9533:1ccd:9d52]:/home/admin/backups /home/user/.local/share/backintime/mnt/25A948BE/mountpoint/
```

Unfortunately, setting rightbracketed IPv6 address in "Host" field of GUI produces the following: 
```
ping <here address> failed. Host is down or wrong address.
```

**Comment by Germar** [comment]
Looks like Pythons `socket` can not handle brackets correctly. I'll have a look. Thanks

**Comment by Germar** [comment]
Would you please test current master? It will add square brackets automatically to IPv6 addresses

**Comment by zimy** [comment]
Now plan to test it in next 20 hours.
