### ISSUE TITLE
support rssh installations

### ISSUE THREAD

**Issue by cyberic99** [bit-team/backintime#578]
I have a server which only supports some commads: rsync, sftp.(see http://pizzashack.org/rssh/)
With backintime version git-c46771a, I cannot set a new 'ssh encrypted' backup.

It tells me that password less authentication does not work.

That is true, in a sense, because when I ssh to the box, I get:

```
$ ssh xxx@yyy:
Linux zzz Debian 3.2.35-2 x86_64
The programs included with the Debian GNU/Linux system are free software;
....
permitted by applicable law.

Restricted

Connection to yyyy closed.
```

Is there a need to launch real command on the server side, apart from rsync?

**Comment by Germar** [comment]
Both, yes and no :wink:

Current master (c46771ad5849bab006d6e5afd236fc50c89f5d59) uses only rsync for taking a snapshot (except of experimental remote smart-remove feature). I made that changes just a few weeks ago. Before there where couple commands which needed to be run remote through ssh. But there are still some checks during testing new configs that relay on a login shell.

I'll have a look if I can get rid of them...

**Comment by cyberic99** [comment]
ok, let me know if you want me to test something
Thank you

**Comment by mossroy** [comment]
I'm also interested in a way to limit the rights the users have on the server through SSH (for security reasons), while still allowing BIT to work properly (even if some features might be disabled in that case).

If it's too complicated or impossible to use rssh, maybe another approach might be to use a slightly more permissive shell like https://github.com/ghantoos/lshell , that would allow to configure a list of white-listed commands?

**Comment by emtiu** [comment]
Closing this in favor of feature request #224.
