### ISSUE TITLE
Backing up to a server via ssh with different UIDs

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#579]
I've previously been backing up to a external hard drive that I plug directly into my laptop. I've been trying to move that hard drive to my server, and backup over wifi/ssh. However, on the first backup, it seems that almost all files are being recreated, and backintime is not using hard links. For example, this file has not changed.
```
$ ls 20160513-200501-652/backup/home/protist/Pictures/Family2015/Cake.jpg  -il
99222106 -rw-r--r-- 5 pi pi 6414684 Oct 31  2015 20160513-200501-652/backup/home/protist/Pictures/Family2015/Cake.jpg
$ sudo ls new_snapshot/backup/home/protist/Pictures/Family2015/Cake.jpg  -il
115344235 -rw-r--r-- 1 protist protist 6414684 Oct 31  2015 new_snapshot/backup/home/protist/Pictures/Family2015/Cake.jpg
```
The first, original backup has 5 hard-links, and the second, newest file is a new hard-link. Also note the change in owner and group. I suspect that the new hard-links are because of the differences in UID between laptop and server. The laptop has `protist`'s user:group, as `1000:1000`. However, the raspberry pi has `pi` as `1000:1000`, and has `protist` as `1003:1051`. It seems that backintime ignores the original backup's correct UID of `1000:1000`. Instead, backintime looks only at the *username* `protist`, and translates it to `1003:1051`, which differs from the previous  `1000:1000`. It hence writes a new file.

**Comment by protist** [comment]
To be clear, I consider the implementation with the original direct USB connection to be "correct". I think that UIDs should be consistent, and usernames ignored. This strategy works even if the server doesn't have those users defined. Also, it allows me to pull the hard drive from the server, and directly copy files back without needing backintime. I also did some testing and using `rsync -a` from the server maintains UIDs and ignores username, so it seems this also the correct way to do it for restoring from the server via ssh. However, I'm not sure why backintime would be backing up the other way…

Arch Linux
backintime 1.1.12

**Comment by Germar** [comment]
The unprivileged user `protist` on the server has no permissions to create files in behalf of other users. It can only create files owned by him self with groups in which he is member of.

So there is no translation at all, it just can't create the files for any other user on remote. That's why BackInTime stores permissions inside an extra file `fileinfo.bz2`.

Also the remote user can't create new hard-links for files he doesn't own. Just imagine creating a hard-link for `/etc/passwd` in your `/home/USER/` and you'd be able to get your self `root`. Would be a big security issue...

So you need to either change user/group for all files in all snapshots to `protist:protist` on the server or you could use `pi` as remote user

**Comment by protist** [comment]
I don't think that this is the problem. I looked back in my history, and the command that I ran was

    $ sudo nice -n 19 ionice -c2 -n7 backintime --backup

I confirmed that the local root account logs into the server with remote root permissions, by running the following locally.
```
$ sudo -i
# ssh pi 
##### ssh login banner #####
# whoami
root
```

I also double checked the the USB drive, and only root has write access to both the share and the directory `backintime/computer-name/root`.

FWIW I managed to backup another laptop using almost identical configuration options, and this works fine. However, in this case, the main local user is `1000:1000`, which translates to the remote user `1000:1000`, so perhaps this was less "confusing" to backintime/rsync.

**Comment by protist** [comment]
Further, the owner of some of the backup's files (such as `etc/passwd`) is root as expected, so the backup must have been made with root permissions.

**Comment by protist** [comment]
Aha! I got it. I tested a single `rsync` command with a test file. I looked in a backintime log and used the following command.

    sudo rsync -rtDHh --links -A -X -pEgo --info=progress2 --no-i-r --rsh="ssh -p <foo> -c arcfour -o IdentityFile=/root/.ssh/root@pi_rsa"  --delete --delete-excluded  -v  --chmod=Du+wx .lesshst 'root@192.168.1.91:"/media/bar/test/"' -i --out-format="BACKINTIME: %i %n%L"

Similarly to above, this incorrectly set the owner:group by user name rather than UID:GID. I looked in rsync's man page, and found this option.

    --numeric-ids           don't map uid/gid values by user/group name

I appended this option to the rsync command above, and it worked perfectly! I then modified the `backintime` config in the `Paste additional options to rsync` section, putting in `--numeric-ids`. Backintime now works perfectly.

In my opinion, I think this should be default, because ultimately it makes backups more portable. Users can disconnect storage from servers and plug them into their computers. Users can move storage the other way. If a user is deleted on the server, there are no associated problems. The only problem that I can imagine is that if local user `foo` tries to backup to a server, then it's *likely* they will have a remote user `foo` too. That's not guaranteed of course, but probably more likely than having the same UID, I suppose. If not default, then I think this is potentially important enough to warrant its own checkbox in the preferences at least, perhaps one that appears when `ssh` is selected. I'll leave this open for now, but if you disagree (or otherwise) feel free to close it. Thanks again for the great software!

**Comment by Germar** [comment]
But that only works if you use root as remote user which I'd highly recommend NOT to do! With non privileged remote users you end up like I posted above.

**Comment by protist** [comment]
I'm also uncomfortable logging in as remote's root, generally. However, if I want to do full-rsync backups of my full system, then is there another alternative? I feel that full-rsync is "safer" for restoring, since I can just copy directly, rather that relying on backintime being installed. e.g. in case of full system destruction, I could just pull the hard drive, and manually copy a snapshot back onto ths drive.

**Comment by Germar** [comment]
You could use `--fake-super` for this in `Paste additional options to rsync`

**Comment by protist** [comment]
Oh nice! I didn't know about that. I wish I'd used that from the beginning! I presume there's no way to transition from the old "full-rsync" to the `--fake-super` without losing all my hard-links and associated disk space?

Also, I was curious… do you recommend not connecting to the server as root because of general security issues (i.e. having a username that is called `root`), or because of something specific to backintime?

**Comment by Germar** [comment]
You could write your own script which will read permissions, reset them and write them as `xargs` like `rsync` would do. But that's quite tricky. You could loose your old snapshots if something goes wrong.

I wouldn't use root because of general security issues.

**Comment by protist** [comment]
Thanks for the advice. Yes, this sounds a little risky to me. Given that I've got ~2 years of backups and my hard drive is almost full, I'll keep the status quo for now. FWIW I'm not *massively* worried about the general security implications of logging in as root, because my server only allows logging in as root from the internal network, the client needs a key, not just a password, and my wifi network itself has a very strong password too. However, I accept that it's probably not best practice in theory, just practical right now! Thank you again for all your help.

**Comment by protist** [comment]
Hi, you mentioned this in passing earlier, but I just noticed `fileinfo.bz2` being created for each of my `ssh`-based backups. If I indeed do log in with root, then this file is moot right? i.e.

1.`rsync` *should* save with correct `owner`:`group`s, and hence I shouldn't have to worry about restoring manually?
2. Backintime creating `fileinfo.bz2` presumably takes an additional, unnecessary step?

Also (slightly-related), I'm testing `Smart remove` > `Run in background on remote Host. EXPERIMENTAL!` option. Since it's… experimental, I thought I should double-check that it's working. However, I can't seem to find log information on previous smart removes. That is, I can see information on the _last_ sync at the end of `~/.local/share/backintime/takesnapshot_.log` as follows
```
[I] Remove old snapshots
[I] Smart remove
[I] Try to keep min free space
[I] Try to keep min 2% free inodes
[I] Finalizing
```
However, this information is missing in the logs for each backup, i.e. at `/path/to/backup/backintime/hostname/root/1/last_snapshot/takesnapshot.log.bz2`.

**Comment by Germar** [comment]
1. BIT uses `--chmod=Du+wx` option for rsync. So the snapshot could still be slightly different
2. Might be unnecessary, but your case is kind of special. In most cases it is necessary to create `fileinfo.bz2`

BIT copies the log to `last_snapshot/takesnapshot.log.bz2` after it is done creating the snapshot. Removing old snapshots is done later. Take a look into your local `/var/log/syslog` for old smart-remove logs. You can also run `backintime --debug --backup` to double-check that function. This will even write into remote syslog.

**Comment by protist** [comment]
Thanks again @Germar. Out of interest, what's the rationale for `--chmod=Du+wx`? I guess this precludes me from doing "dumb" restores anyway, since the mode bits might differ.

**Comment by Germar** [comment]
This will make folders write and executable for the owner which is necessary to create files inside folders. Without this rsync wouldn't sync files inside folders which are not writeable on source.

**Comment by protist** [comment]
That makes sense. So by ssh, is there is no real way to get a full, "dumb" backup, where I could restore simply by copying from `last_snapshot` to the replacement hard drive of my computer? I guess if I have root access to the server, then might I be able override `--chmod=Du+wx` somehow, since it's not necessary?

I could live with taking "unnecessary" time to create `fileinfo.bz2`, but the "dumb" backup part is a bit more important to me.

**Comment by Germar** [comment]
Yea, you could remove `--chmod=Du+wx` with this patch

```
diff --git a/common/snapshots.py b/common/snapshots.py
index 81831b6..e44efde 100644
--- a/common/snapshots.py
+++ b/common/snapshots.py
@@ -1779,7 +1779,7 @@ class Snapshots:
         rsync_include, rsync_include2 = self.rsyncInclude(includeFolders)
 
         encode = self.config.ENCODE
-        ret = ['--chmod=Du+wx']
+        ret = []
         ret.extend(['--exclude=' + i for i in (encode.exclude(self.config.get_snapshots_path()),
                                                encode.exclude(self.config._LOCAL_DATA_FOLDER),
                                                encode.exclude(self.config._MOUNT_ROOT)
```

But you could also just keep it and run a second restore with BIT GUI after copying from `last_snapshot`. Due to rsync this should be quite fast and BIT will restore permissions from `fileinfo.bz2` when done.

**Comment by protist** [comment]
Hmmm… it looks like I'm wanting backintime to do something that's it's not really made to do. I don't really want to patch it directly, because I'll inevitably forget after an update one day.

Okay, I guess I just need to face the fact that I'll need backintime to restore my backups, and there doesn't seem to be a way to do "dumb" restores, at least not if I backup to ssh.

Thank you again for all your help.

**Comment by protist** [comment]
FWIW I just tried backing up over `ssh` with the `--debug` option, and I had quite a few warnings similar to the following. I presume that they are unimportant?
```
DEBUG: [common/snapshots.py:537 Snapshots.get_user_name] Failed to get user name for UID 150: 'getpwuid(): uid not found: 150'
DEBUG: [common/snapshots.py:537 Snapshots.get_user_name] Failed to get user name for UID 73: 'getpwuid(): uid not found: 73'
DEBUG: [common/snapshots.py:553 Snapshots.get_group_name] Failed to get group name for GID 75: 'getgrgid(): gid not found: 75'
DEBUG: [common/snapshots.py:537 Snapshots.get_user_name] Failed to get user name for UID 108: 'getpwuid(): uid not found: 108'
DEBUG: [common/snapshots.py:553 Snapshots.get_group_name] Failed to get group name for GID 117: 'getgrgid(): gid not found: 117'
```

**Comment by Germar** [comment]
Do you have users with UID 150, 73, 75, 108 or 117 in your `/etc/passwd`? Looks like this are left over files from users who are deleted already.

BIT will just restore them with the original UID in this case...

**Comment by protist** [comment]
Ah yes, perfect. Thanks once again!
