### ISSUE TITLE
Hard-Linking not working on locally mounted USB disk (Ext3)

### ISSUE THREAD

**Issue by caco3** [bit-team/backintime#580]
I have a locally mounted USB disk with an Ext3 partition.
I use it every now and then to create a backup of my NAS (mounted through CIFS) to the USB disk.

Now, for some reasons BiT stopped to do hard links and instead creates full backups.
I can't see any error in the log or terminal.

This are the commands I use:
```
mkdir /media/Ext_HD/
chmod 777 /media/Ext_HD/

mount /dev/sdd1 /media/Ext_HD/
backintime-qt4 --config /media/Ext_HD/backintime/BiT_DS_Backup.conf
```

I know this was working before as older backups have the same inode ID.
Also, I use the same BiT version to backup my PC to the NAS and there hard-linking works fine.

BiT Version: 1.1.13.3

**Comment by caco3** [comment]
Might it have something to do with the rsync parameters?
Last time I run it successfully (with working hard-links), it started like this:
`[I] rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded    -i --dry-run --out-format="BACKINTIME: %i %n%L"                                              --chmod=Du+wx`
Now it looks like this:
`[I] rsync -rtDHh --links -pEgo                --info=progress2 --no-i-r  --delete --delete-excluded -v -i           --out-format=BACKINTIME: %i %n%L   --link-dest=../../20150905-113230-894/backup --chmod=Du+wx`

One fact that stook out to me it the parameter `--link-dest=../../20150905-113230-894/backup` which was missing on the older call and the changed firs few parameters `-pEgo `.

**Comment by Germar** [comment]
Current testing version always uses `Full rsync mode`. The old default mode (check for changes with `rsync --dry-run`, create hard-links with `cp -aRl` and finaly sync with `rsync`) is gone. Instead everything is done with one single rsync command. But that should still create hard-links...

Might be a permission problem...
Could you please post the output of `ls -lai` from a folder that didn't change in both the last correctly hard-linked snapshot and the current snapshot?

**Comment by caco3** [comment]
Indeed, you are right, the user and also the access rights are not the same anymore?
In the last backups, the files belonged to root, but recently I changed the mount settings to make sure the NAS is mounted as my user. I actually don't care about the user/group and also the access rights.
What would be the easiest way to get in sync again? Should i simply use chown, chgrp and chmod to set all (NAS and backups) to same settings?

**Comment by Germar** [comment]
`chown USER:GROUP -R /path/to/lastsnapshot` should be enough to make it sync with hard-links again. Removing old snapshots will only work again if you do the same for all other old snapshots, too.

User, group and permissions are stored in `fileinfo.bz2`, too. So if you restore a file BIT will restore the permissions from `fileinfo.bz2`

**Comment by caco3** [comment]
Thank you very much!
Now it works again as expected.
