### ISSUE TITLE
SSH max arg length choke on SSH banner

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#581]
I'm backing up to my ssh server, and testing `Smart remove` > `Run in background on remote Host. EXPERIMENTAL!`. On my local computer, backintime is stuck on the `Smart remove` step, according to the system tray and backintime GUI. It's been stuck for several hours, which is much longer than it normally takes to smart remove when locally directed, over ssh.

However, as far as I can tell, the server isn't doing anything. I wasn't exactly sure what process to look for, so I tried searching `sudo ps aux` for `rsync`, `screen`, `backintime` and `nohup`. However, none of those were running.

On the local computer, I can see a few `backintime` and `screen` processes, as follows.

```
/usr/bin/python /usr/share/backintime/qt4/serviceHelper.py
python /usr/share/backintime/common/backintime.py pw-cache start
/bin/sh /usr/bin/backintime-qt4
python /usr/share/backintime/qt4/app.py
ssh-agent python /usr/share/backintime/qt4/app.py
ssh -p 123 -o ServerAliveInterval=240 -c arcfour -o IdentityFile=/root/.ssh/root@pi_rsa root@192.168.1.1 screen -d -m bash -c "(flock -x 9; ) 9>\"/media/Wells/backintime/hostname/root/1/smartremove.lck\""
/bin/sh /usr/sbin/backintime backup-job
python /usr/share/backintime/common/backintime.py backup-job
ssh-agent python /usr/share/backintime/common/backintime.py backup-job
sshfs -p 123 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/root@pi_rsa -o Ciphers=arcfour -o idmap=user root@192.168.1.1:/media/Wells /root/.local/share/backintime/mnt/6A5D466C/mountpoint
/usr/bin/python /usr/share/backintime/qt4/qt4systrayicon.py 1
```

**Comment by Germar** [comment]
ssh -p 123 -o ServerAliveInterval=240 -c arcfour -o IdentityFile=/root/.ssh/root@pi_rsa root@192.168.1.1 screen -d -m bash -c "(flock -x 9; ) 9>\"/media/Wells/backintime/hostname/root/1/smartremove.lck\""

That command should be much longer. Please run a new snapshot with `backintime backup --debug` and post the output starting at smart-remove here.

**Comment by protist** [comment]
Hm… I wonder if that process name got truncated somehow. After posting the initial comment, my scheduled backup ran the next two nights, completing successfully. I guess I'll just have to wait for it to fail again. Is there a way to use `--debug` with scheduled backups?

**Comment by Germar** [comment]
Nope, it's missing in the middle. Not at the end. `...(flock -x 9; COMMANDS MISSING) 9>\"/media/Wells/...`

If you open GUI with `backintime-qt4 --debug` and open/close Settingsdialog once BIT will change all scheduled backups to run with `--debug`, too.

**Comment by protist** [comment]
I think I have something informative. Before I got your reply about debugging, I ran my monthly checksum backup, this time over `ssh`. The snapshot part worked, but then I got this.
```
INFO: [smart remove] remove snapshots in background: ['20160523-183012-257', '20160518-210851-523', '20160311-174630-164']
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 626, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 1059, in take_snapshot
    self._free_space( now )
  File "/usr/share/backintime/common/snapshots.py", line 1679, in _free_space
    self.smart_remove( now, keep_all, keep_one_per_day, keep_one_per_week, keep_one_per_month )
  File "/usr/share/backintime/common/snapshots.py", line 1596, in smart_remove
    maxLength = self.config.ssh_max_arg_length()
  File "/usr/share/backintime/common/config.py", line 547, in ssh_max_arg_length
    raise ValueError('SSH max arg length %s is to low to run commands' % value)
ValueError: SSH max arg length 6 is to low to run commands
```
There were no snapshots removed. Having said this, the error was different from the one I first reported, as it crashed cleanly.

>If you open GUI with `backintime-qt4 --debug` and open/close Settingsdialog once BIT will change all scheduled backups to run with `--debug`, too.

I then tried to do this, but I couldn't click `OK` after changing the settings. I had a similar error on the command line.
```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1698, in accept
    if self.validate():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1452, in validate
    if not self.save_profile():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1327, in save_profile
    mnt.pre_mount_check(mode = mode, first_run = True, **mount_kwargs)
  File "/usr/share/backintime/common/mount.py", line 130, in pre_mount_check
    return tools.pre_mount_check(first_run)
  File "/usr/share/backintime/common/sshtools.py", line 152, in pre_mount_check
    self.check_remote_commands()
  File "/usr/share/backintime/common/sshtools.py", line 493, in check_remote_commands
    maxLength = self.config.ssh_max_arg_length(self.profile_id)
  File "/usr/share/backintime/common/config.py", line 547, in ssh_max_arg_length
    raise ValueError('SSH max arg length %s is to low to run commands' % value)
ValueError: SSH max arg length 6 is to low to run commands
```

**Comment by Germar** [comment]
Please run 

    sed '/snapshots.ssh.max_arg_length/d' -i ~/.config/backintime/config

and try again.

**Comment by protist** [comment]
Hm… I think it's happening fairly consistently now. I've never had anything removed yet. I tried to backup with `backintime backup --debug`.
```
...
INFO: [common/snapshots.py:1593 Snapshots.smart_remove] [smart remove] remove snapshots in background: ['20160526-093627-980', '20160523-183012-257', '20160518-210851-523', '20160311-174630-164']
Check length 1048320:	python exception: Argument list too long
Check length 524160:	python exception: Argument list too long
Check length 262080:	python exception: Argument list too long
Check length 131040:	is to long
Check length 65520:	is to long
Check length 32760:	is to long
Check length 16380:	is to long
Check length 8190:	is to long
Check length 4095:	is to long
Check length 2047:	is to long
Check length 1023:	is to long
Check length 511:	is to long
Check length 255:	is to long
Check length 127:	is to long
Check length 63:	is to long
Check length 31:	is to long
Check length 15:	is to long
Check length 7:	is to long
Check length 3:	is to long
Check length 1:	is to long
Maximum SSH argument length between <hostname> and root@192.168.1.1 is 6
```
I then get caught in the following loop.
```
DEBUG: [common/snapshots.py:1640 Snapshots.smart_remove] Call command "ssh -p 123 -o ServerAliveInterval=240 -c arcfour -o IdentityFile=/root/.ssh/root@pi_rsa root@192.168.1.1 'screen -d -m bash -c "(logger -t \"backintime smart-remove [$BASHPID]\" \"start\"; flock -x 9; logger -t \"backintime smart-remove [$BASHPID]\" \"got exclusive flock\"; ) 9>\"/media/Wells/backintime/hostname/root/1/smartremove.lck\""'"
<<<SSH login boilerplate>>>
DEBUG: [common/snapshots.py:1640 Snapshots.smart_remove] Command "ssh -p 709 -o Se..." returns 0
```
This just kept repeating. After a few hundred times I killed it. I checked the config file before and during the backup, and confirmed the removal of the line `snapshots.ssh.max_arg_length`. However, I also checked when backintime was stuck in the loop, and this line had reappeared!

**Comment by Germar** [comment]
Okay, for some reason the check for the argument length is going crazy on your system. Please add a line
```
profile1.snapshots.ssh.max_arg_length=1024
```
to your `config` and try again.

Also please post the output of
```
ssh USER@HOST printf foobar
```

**Comment by protist** [comment]
I'll test again later today. As for the output, it's as expected.
```
root@hostname:~# ssh pi printf foobar
<ssh boilerplate>
foobarroot@hostname:~#
```

**Comment by protist** [comment]
After modifying `profile1.snapshots.ssh.max_arg_length=1024`, I ran the backup again. It didn't throw any errors locally, and the config file stayed with the new setting. The local output said
```
INFO: [common/snapshots.py:1593 Snapshots.smart_remove] [smart remove] remove snapshots in background: ['20160526-093627-980', '20160523-200035-539', '20160523-183012-257', '20160518-210851-523', '20160318-174403-248', '20160311-174630-164']
```
The server seems to working remotely, but ridiculously slow. Two hours later, only two snapshots were removed remotely, `20160526-093627-980` and `20160523-183012-257` (not the first two, is that important?).

I looked at `htop` on the server, filtering for `backintime`. The `SCREEN` and/or `logger` processes were `S    interruptible sleep (waiting for an event to complete)`, but the only one that was `D    uninterruptible sleep (usually IO)` was
```
find /media/Wells/backintime/hostname/root/1/20160523-200035-539 -type d -exec chmod u+wx {} +
```
which was only using ~5% of one core. I guess it's the storage medium that is slow, but I'm a bit surprised that it is *that* slow. The backup itself took exactly 35 minutes, which is quite normal. However, (I think) the smart-removes are normally much quicker than that. Somewhere between 2:08 and 2:29, the third snapshot was removed, so it's taking 42–50 minutes to remove a single snapshot.

I just checked `htop` on the server at another point, and it progressed to `rm -rf…`. I wonder if the `find… chmod` step is the slowest? (As per the other thread) if I'm logging into the server as root I'd not need to `chmod` before `rm -rf`. I realise this is not "recommended", so I'm not suggesting you modify code (unless it's easy to do, or for me to pass a simple option to) but it's more from curiosity…

**Comment by Germar** [comment]
Current master (next version 1.2.0) will use `rsync` to remove the files remote. It won't need `find -type d -exec chmod ...` anymore and is much faster. You can give it a try from [backintime-git](https://aur.archlinux.org/packages/backintime-git/) package.

**Comment by protist** [comment]
Thanks for that. I've updated and I'll consider this fixed, then. If you'd like me to troubleshoot more, then I'm more than happy to help out. Just let me know what I can do (and reopen the issue).

Oh, `<ssh boilerplate>` is just the `ssh` greeting from my server, as defined in `/etc/ssh/sshd_config`'s `Banner`.

**Comment by Germar** [comment]
Okay, so the check for `max_arg_length` chokes on SSH banners...

**Comment by protist** [comment]
Oh, interesting. I didn't even think that this might cause problems! For the sake of being thorough, here is my setup.

Firstly, `/etc/ssh/sshd_config` contains `Banner /etc/issue.net`. The contents of `/etc/issue.net` are printed when connecting by ssh. Then, after automatically logging on with a key, I get more text, i.e.

    Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l

and the contents of `/etc/motd`. I'm not really sure where the line above comes from. However, these are possibly moot, since when I `rsync`, I only get `/etc/issue.net` printed. Thanks for looking into this.

**Comment by protist** [comment]
Regarding how long the smart remove was taking, I upgraded to the AUR's backintime-git. However it still took 1:27 to remove two snapshots, i.e. 44 minutes each, similar to backintime 1.1.12. I checked the server as it was happening, just to confirm that it was running the expected commands.

```
$ sudo ps aux | grep '[b]ackintim'
root       479  0.0  0.1   5164  1176 ?        Ss   19:20   0:00 SCREEN -d -m bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; logger -t "backintime smart-remove [474]" "start"; flock -x 9; logger -t "backintime smart-remove [474]" "got exclusive flock"; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 still exist"; sleep 1; rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 remove done"); rmdir $TMP) 9>"/media/Wells/backintime/hostname/root/1/smartremove.lck"
root       480  0.0  0.0   4580   908 pts/3    Ss+  19:20   0:00 bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; logger -t "backintime smart-remove [474]" "start"; flock -x 9; logger -t "backintime smart-remove [474]" "got exclusive flock"; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 still exist"; sleep 1; rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 remove done"); rmdir $TMP) 9>"/media/Wells/backintime/hostname/root/1/smartremove.lck"
root       483  0.0  0.0   4584   860 pts/3    S+   19:20   0:00 bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; logger -t "backintime smart-remove [474]" "start"; flock -x 9; logger -t "backintime smart-remove [474]" "got exclusive flock"; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 still exist"; sleep 1; rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 remove done"); rmdir $TMP) 9>"/media/Wells/backintime/hostname/root/1/smartremove.lck"
root      1247  0.0  0.0   4584   520 pts/3    S+   20:04   0:00 bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; logger -t "backintime smart-remove [474]" "start"; flock -x 9; logger -t "backintime smart-remove [474]" "got exclusive flock"; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 still exist"; sleep 1; rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 remove done"); rmdir $TMP) 9>"/media/Wells/backintime/hostname/root/1/smartremove.lck"
root      1250  0.0  0.1   4584  1688 pts/3    S+   20:04   0:01 rsync -a --delete /tmp/tmp.OtaxT4pKey/ /media/Wells/backintime/hostname/root/1/20160525-174042-462
root      1251  6.0  1.1  15480 11020 pts/3    D+   20:04   1:55 rsync -a --delete /tmp/tmp.OtaxT4pKey/ /media/Wells/backintime/hostname/root/1/20160525-174042-462
root      1252  0.0  0.0   4532   660 pts/3    S+   20:04   0:00 rsync -a --delete /tmp/tmp.OtaxT4pKey/ /media/Wells/backintime/hostname/root/1/20160525-174042-462
```

**Comment by Germar** [comment]
The RaspberryPi is quite slow on HDDs. It's just USB2 and the USB shares it's IRQ with the network.

I recently bought my self a Cubieboard 3 which is nice and fast. It comes with SATA...

**Comment by Germar** [comment]
Not only the `max_arg_length` choked here on SSH banners. All SSH commands had problems with it...

**Comment by protist** [comment]
Thanks for the fix!

> The RaspberryPi is quite slow on HDDs. It's just USB2 and the USB shares it's IRQ with the network.

At the "smart remove" stage, the network connection shouldn't matter though, right? Can I test this speed somehow? What kind of command should I use? I thinking that I could create multiple copies of files from `/dev/urandom` on my USB hard drive, then benchmark deleting them when connecting to my Pi vs. my normal computer. I could test three permutations:

1. The actual `screen` command that backintime passes from my local computer to the Pi.
2. An analogous local command that I could run directly from the Pi (i.e. without `screen`).
3. The same command as 2. on my local computer, with the hard drive directly connected.

> I recently bought my self a Cubieboard 3 which is nice and fast. It comes with SATA...

I can't afford that! :grin: But seriously, I have 5 Pis, so it does add up a little.

**Comment by protist** [comment]
Regarding the original bug report, I upgraded to the latest git version, and reverted my config. I tested again with `--debug`, and it's still failing. It's not entering the infinite loop any more, but it's still not doing the smart remove. I get the following error.

```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1052, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 485, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 705, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 83, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 695, in take_snapshot
    self._free_space( now )
  File "/usr/share/backintime/common/snapshots.py", line 1359, in _free_space
    self.smart_remove(del_snapshots)
  File "/usr/share/backintime/common/snapshots.py", line 1256, in smart_remove
    maxLength = self.config.ssh_max_arg_length()
  File "/usr/share/backintime/common/config.py", line 510, in ssh_max_arg_length
    raise ValueError('SSH max arg length %s is to low to run commands' % value)
ValueError: SSH max arg length 6 is to low to run commands
```

**Comment by Germar** [comment]
Which image did you use for your RPi so I can test this on my own RPi? The `sshd` settings are default from that image, right?

You could benchmark with these both commands:
```
SCREEN -d -m bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; logger -t "backintime smart-remove [474]" "start"; flock -x 9; logger -t "backintime smart-remove [474]" "got exclusive flock"; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 still exist"; sleep 1; rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; logger -t "backintime smart-remove [474]" "snapshot 20160525-174042-462 remove done"); rmdir $TMP) 9>"/media/Wells/backintime/hostname/root/1/smartremove.lck"

TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; test -e "/media/Wells/backintime/hostname/root/1/20160525-174042-462" && (rsync -a --delete "$TMP/" "/media/Wells/backintime/hostname/root/1/20160525-174042-462"; rmdir "/media/Wells/backintime/hostname/root/1/20160525-174042-462"); rmdir $TMP
```

**Comment by protist** [comment]
I can't actually remember what original image I used for my Pi. My backintime backups are from July 2014, so I guess the original image was around then. I've modified `/etc/ssh/sshd_config` a bit, changing the default port, disabling password access, and changing a few other things. I can't seem to find the original so that I can post the diff, but [here](https://gist.github.com/protist/d7297c058716ac0318d870ed3c888997) is my file.

As for the benchmarking, I don't really understand all of the command, but is there a more minimal version that would test on some unimportant data, rather than removing my real backups? Is this the real crux of it: create an empty directory, then `rsync -a --delete <empty_dir> <remote_dir_to_delete>`?

**Comment by Germar** [comment]
Sorry for the late answer. I'll try to reconstruct the problem based on your `sshd_config`, soon.

The command will create an empty temp dir, check that this folder really exist and is empty (I had a case where `mkdir` wasn't available and so `rsync` copied the whole filesystem into the snapshot :see_no_evil:). Next it will try to lock an exclusive file lock (only one process can lock that at a time, other processes will wait). Then we check if the snapshot is still available (other smart-remove instances could have removed it already). Now `rsync` will sync the empty temp dir to the snapshot folder (which will delete everything inside) and finally `rmdir` will remove the snapshot folder itself.

Here is a more readable version without `logger`:
```
SCREEN -d -m bash -c (TMP=$(mktemp -d); test -z "$TMP" && exit 1; test -n "$(ls $TMP)" && exit 1; flock -x 9; test -e "PATH_TO_REMOVE" && (rsync -a --delete "$TMP/" "PATH_TO_REMOVE"; rmdir "PATH_TO_REMOVE"); rmdir $TMP) 9>"PATH_FOR_LOCK_FILE"
```

**Comment by Germar** [comment]
:see_no_evil: found the problem. The test for max argument length doesn't have values for non-default ports...

**Comment by protist** [comment]
Thanks for the fix. I reverted my config to change `profile1.snapshots.ssh.max_arg_length=6` and it worked fine, including the smart removes.
