### ISSUE TITLE
Anacron is backing up constantly!

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#584]
The "anacron" function was working perfectly for a few days, but now seems broken on my system. It's backing up every 15 minutes if it can. From my research on backintime, it looks like it calls `backintime backup-job` every 15 minutes, and looks for a timestamp in `~/.local/share/backintime/anacron`.

```
$ sudo crontab -l
#Back In Time system entry, this will be edited by the gui:
*/15 * * * * /usr/sbin/nice -n 19 /usr/sbin/ionice -c2 -n7 /usr/sbin/backintime backup-job >/dev/null 2>&1
$ sudo ls -l /root/.local/share/backintime/anacron
total 4
-rw-r--r-- 1 root root 13 Jun  5 09:38 1_Main_profile
$ sudo cat /root/.local/share/backintime/anacron/1_Main_profile
20160605 0938
$ date
Tue Jun  7 21:44:16 AEST 2016
```

It looks like the timestamp isn't getting updated?

==EDIT==
This is actually my wife's laptop. I tried changing the config, but got the same error as on my laptop in #581 (`SSH max arg length`). I modified the config manually, which let me change the config via the GUI to stop the anacron jobs for now. I'm unsure if fixing the `max arg` issue will solve this anacron issue, but it still doesn't explain why this error suddenly appeared now. I hadn't modified her config for a week or so.

**Comment by Germar** [comment]
Not sure either. Could you please remove the spool file (`/root/.local/share/backintime/anacron/1_Main_profile`) and check if it is rewritten after the next run?

The problem with `SSH max arg length` will be the same on all machines which use the same destination because of the SSH banner. I'll set up a banner my self and fix this, soon.

**Comment by protist** [comment]
I removed this file and it was rewritten after the next "anacron" run. I have no idea why; as per my original post, the permissions were fine (although this is root, so I don't think that's important). Thanks again!

**Comment by mkkyah** [comment]
Hi Germar,
I'm having the same issue after changing my Qnap NAS with a new one. I have migrated my old disks to the new device and everything is working including BiT, but it's taking snapshots every 15 minutes instead of daily anacron snapshots.
I have deleted 1_Main_profile file, it didn't help and the file is not created again. My BiT version is 1.2.0 alpha12.

**Comment by Germar** [comment]
Does it mark new snapshots with `Error` in Timeline? Please post the output of
```
backintime --debug backup-job
```

**Comment by mkkyah** [comment]
No, I see no errors in snapshot logs or timeline.
I'm using BiT as root and have deleted /root/.local/share/backintime/anacron/1_Main_profile
here is debug info:

DEBUG: [common/backintime.py:584 argParse] Arguments: {'command': 'backup-job', 'debug': True, 'func': <function backupJob at 0x7fed373d8268>} | unknownArgs: []
DEBUG: [common/tools.py:2011 BackupJobDaemon.daemonize] first fork pid: 2295
DEBUG: [common/tools.py:2011 BackupJobDaemon.daemonize] first fork pid: 0
DEBUG: [common/tools.py:2020 BackupJobDaemon.daemonize] decouple from parent environment
DEBUG: [common/tools.py:2028 BackupJobDaemon.daemonize] second fork pid: 2296
DEBUG: [common/tools.py:2028 BackupJobDaemon.daemonize] second fork pid: 0
DEBUG: [common/tools.py:2037 BackupJobDaemon.daemonize] redirect standard file descriptors

Back In Time
Version: 1.2.0~alpha12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:669 getConfig] config file: /home/murat/.config/backintime/config
DEBUG: [common/backintime.py:670 getConfig] share path: /home/murat/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile

**Comment by Germar** [comment]
That's it? No new snapshot and no error at all?

When you said you use BiT as root, did you ran that command as root, too? Doesn't look like as it loads the config from `/home/murat/`. Please run it again as root:
```
sudo -i backintime --debug backup-job
```

**Comment by mkkyah** [comment]
I tried sudo, but I should sudo -i
http://pastebin.com/BTwEn6T4

**Comment by Germar** [comment]
Did it stop at the last line you posted?  I just changed the position a new timestamp will be written. So a bug during `Smart Remove` won't prevent a new timestamp anymore.

But now the question is why it broke at `Smart Remove`!? Please run `backintime --debug smart-remove` and post output again.

**Comment by mkkyah** [comment]
Yes, I think it was the last line.
here is sudo -i backintime --debug smart-remove output:
http://pastebin.com/gPi2vrkq

**Comment by mkkyah** [comment]
dpkg-buildpackage: source package backintime
dpkg-buildpackage: source version 1.2.0~alpha0
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Germar Reitze <germar.reitze@gmail.com>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build backintime
dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 7)
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)

**Comment by Germar** [comment]
> dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 7)
```
sudo apt install debhelper
```

**Comment by mkkyah** [comment]
I have now alpha0 installed and 1_Main_profile is created after first run. Now I believe we have to wait 15 minutes to see the result :)

**Comment by mkkyah** [comment]
I think it worked :+1:

**Comment by mkkyah** [comment]
yes, it's not trying to run every 15 minutes anymore.
There is a package manager "broken dependencies" warning for backintime-qt. Should I do something, or will it be fixed with an upcoming new version?

**Comment by Germar** [comment]
You could remove both `backintime-common` and `backintime-qt` once and install it again with `dpkg -i ...` manually. This should fix the brocken dependencies. But next time you update this version will be overwritten because of the lower version number. I'll release a new alpha, soon.
