### ISSUE TITLE
Build dependencies unmet on Kali latest build

### ISSUE THREAD

**Issue by worsedoughnut** [bit-team/backintime#585]
Tried to run `./makedeb.sh` but it keeps giving me this:

`root@kali:~/backintime-1.1.12# ./makedeb.sh `
`dpkg-buildpackage: info: source package backintime`
`dpkg-buildpackage: info: source version 1.1.12`
`dpkg-buildpackage: info: source distribution unstable`
`dpkg-buildpackage: info: source changed by Germar Reitze <germar.reitze@gmail.com>`
`dpkg-buildpackage: info: host architecture amd64`
`dpkg-source --before-build backintime-1.1.12`
**`dpkg-checkbuilddeps: error: Unmet build dependencies: debhelper (>= 7)`**
**`dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting`**
`dpkg-buildpackage: warning: (Use -d flag to override.)`
`root@kali:~/backintime-1.1.12#`

(emphasis mine).

This is on the latest build of Kali rolling so I could just be missing some dependency normally found in Debian.

**Comment by Germar** [comment]
You need to install `debhelper`
```
sudo apt-get install debhelper
```
