### ISSUE TITLE
backintime-qt4 ICE default IO error handler doing an exit()

### ISSUE THREAD

**Issue by jeffsilverm** [bit-team/backintime#588]
I'm pretty sure that backintime was working properly yesterday, not sure what changed between yesterday and today that causes this to fail.

I tried running this from the gnome menu, and it would silently fail (this is gnome 3.18.5 on Ubuntu Ubuntu 16.04 LTS).  So then I tried running it from the command line and I got:
```
jeffs@jeff-desktop:~$ /usr/bin/backintime-qt4

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

ICE default IO error handler doing an exit(), pid = 4562, errno = 0
jeffs@jeff-desktop:~$ echo $DISPLAY
:0
jeffs@jeff-desktop:~$ 
```

I get the same error using backintime:

```
/usr/bin/backintime backup --profile "With 4 TB Seagate USB"
Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Inhibit Suspend started. Reason: take snapshot
INFO: Take a new snapshot. Profile: 2 With 4 TB Seagate USB
INFO: Compare with old snapshot: 20160623-223001-936
ICE default IO error handler doing an exit(), pid = 3556, errno = 0
INFO: Create hard-links
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Remove backups older than: 20060601-000000
INFO: Keep min free disk space: 1024 MiB
INFO: Keep min 2% free inodes
INFO: Unlock
INFO: Release inhibit Suspend
jeffs@jeff-desktop:~$ 
```

However, I get the sense that the backups are working properly, because I have a directory on the backup media that has lots and lots of files in it:
```
jeffs@jeff-desktop:~/.config/backintime$ ls /media/jeffs/Jeff_Silverman_b/backintime/jeff-desktop/jeffs/2/20160623-233001-625/backup/home/jeffs/ | wc -l
1279
jeffs@jeff-desktop:~/.config/backintime$ ls -ld /media/jeffs/Jeff_Silverman_b/backintime/jeff-desktop/jeffs/2/20160623-233001-625
dr-xr-xr-x 3 jeffs jeffs 4096 Jun 23 23:38 /media/jeffs/Jeff_Silverman_b/backintime/jeff-desktop/jeffs/2/20160623-233001-625
jeffs@jeff-desktop:~/.config/backintime$ date
Thu Jun 23 23:54:22 PDT 2016
jeffs@jeff-desktop:~/.config/backintime$ 
```

So is this an error that can be ignored?  Why does the version that worked from the gnome menu fail silently?  How can I find more debugging information?

Many thanks,

Jeff

**Comment by Germar** [comment]
Please remove the file `~/.ICEauthority` and try again.

**Comment by jeffsilverm** [comment]
Germar,

I think that resolved the issue.

jeffs@jeff-desktop:~$ /usr/bin/backintime --profile-id 2 backup-job
jeffs@jeff-desktop:~$
Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Inhibit Suspend started. Reason: take snapshot
INFO: Take a new snapshot. Profile: 2 With 4 TB Seagate USB
Qt: Session management error: None of the authentication protocols
specified are supported
INFO: [qt4systrayicon] begin loop
INFO: Compare with old snapshot: 20160624-230001-660
INFO: Create hard-links
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Remove backups older than: 20060601-000000
INFO: Keep min free disk space: 1024 MiB
INFO: Keep min 2% free inodes
INFO: Unlock
INFO: Release inhibit Suspend
INFO: [qt4systrayicon] end loop

jeffs@jeff-desktop:~$

I wish the error message was clearer.


Thank you

Jeff


On Fri, Jun 24, 2016 at 5:09 AM, Germar Reitze <notifications@github.com>
wrote:

> Please remove the file ~/.ICEauthority and try again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bit-team/backintime/issues/588#issuecomment-228329535>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAhhhx-mavIq0QNUp3Cz0pKo9TePfkgaks5qO8jrgaJpZM4I9g1K>
> .
>



-- 
Jeff Silverman, linux sysadmin
nine two four   twentieth avenue east
Seattle, WA, nine eight one one two -3507
(253) 459-2318
jeffsilverm@gmail.c0m (note the zero!)
http://www.commercialventvac.com
See my portfolio of writings and talks
<http://www.commercialventvac.com/portfolio.html>

**Comment by Germar** [comment]
That message is not from BIT itself. I've no control over it.
