### ISSUE TITLE
File Picker doesn't show external drives

### ISSUE THREAD

**Issue by sudhirkhanger** [bit-team/backintime#589]
Hi,

I noticed that the file picker in Back In Time doesn't show external use drives. Is there a reason for it. I would be easy for me if it showed my KDE's file picker which has bookmarks and everything. Is that possible?

Regards,
Sudhir.

**Comment by Germar** [comment]
Native filesystem dialogs don't support multiselection and control over hidden files. That's why I chose Qt Filedialog. This might change with Qt5 but I'm not sure yet.
