### ISSUE TITLE
Cron backup results in empty snapshot, while manual backup works properly.

### ISSUE THREAD

**Issue by simgunz** [bit-team/backintime#590]
In one of my configuration the automatic backup executed by cron results in an empty snapshot, while if I take the backup manually with the save button, the backup is correct.

Info for debugging

- In the latest good backup folder there is a file named 'failed'. Is this a flag? What's the meaning of this file? (The log of the backup seems the backup completed successfully, since it reached the "Save permission" stage)
- The info file in this folder reports:
```
group.1.gid=0
group.1.name=root
group.2.gid=100
group.2.name=users
group.size=2
snapshot_date=20160623-093529
snapshot_machine=dragonfly
snapshot_profile_id=3
snapshot_tag=485
snapshot_user=simone
snapshot_version=3
user.1.name=root
user.1.uid=0
user.2.name=simone
user.2.uid=1000
user.3.name=test
user.3.uid=1001
user.size=3
```

Backup with cron based on the latest good backup:
- The info file in the empty backup folder is:
```
group.1.gid=0
group.1.name=root
group.size=1
snapshot_date=20160623-150002
snapshot_machine=dragonfly
snapshot_profile_id=3
snapshot_tag=381
snapshot_user=simone
snapshot_version=3
user.1.name=root
user.1.uid=0
user.size=1
```

Manual backup based on the previous backup:
- The info file is:
```
group.1.gid=0
group.1.name=root
group.2.gid=100
group.2.name=users
group.size=2
snapshot_date=20160624-101022
snapshot_machine=dragonfly
snapshot_profile_id=3
snapshot_tag=342
snapshot_user=simone
snapshot_version=3
user.1.name=root
user.1.uid=0
user.2.name=simone
user.2.uid=1000
user.3.name=test
user.3.uid=1001
user.size=3
```

Content of crontab:
```
#Back In Time system entry, this will be edited by the gui:
*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2>&1
#Back In Time system entry, this will be edited by the gui:
0 15 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 3 backup-job >/dev/null 2>&1
```
I think the first line is an anacron configuration for the profile number 1. The problematic profile is the number 3.

- The command executed by rsync is exactly the same for the two cases.

**Comment by Germar** [comment]
`failed` is a flag, correct. If that file is present BIT will show `With Errors` beside the Snapshot in GUI.

Could you please send me (germar DOT reitze HOSTED ON gmail DOT com) the `takesnapshot.log.bz2` from the failed snapshot?

Might be a permission problem as you backup files that belong to a different user (test) without being root.

**Comment by Germar** [comment]
rsync deletes everything inside the snapshot folder. So the source folder `/media/dataHD` must have been empty while taking the snapshot. I guess you're using Nautilus to automount the external drive and this was not done before taking that snapshot. 

I'd suggest to either add a line in `/etc/fstab` to mount your drive or mount it with [autofs](https://help.ubuntu.com/community/Autofs)

Regards,
Germar

**Comment by simgunz** [comment]
The drive `/media/dataHD` where the backup target folder resides is LUKS encrypted and it is mounted with pam_mount

- There is no entry for it in /etc/fstab
- Dolphin shows that device entry as unmounted after I turn on the PC

but still:

- Running `ls -l /media/dataHD` I can see the content of it.
- Running `ls -l /media/` I can see that it is not a symbolic link and has the following permissions and ownership `drwxrwsr-x+ 21 simone users`
- Running the same commands as root give me the same results

- Weirdly clicking on that entry in Dolphin, the drive is mounted on `/run/media/simone/Wonderland/`, so that I can access it from two mount points.

Beside the general weird behavior, I don't understand why the cron job of backintime cannot see the content of it. Is the cron job run as root or as the normal user? 
Do you have any other idea in helping me debugging this?

**Comment by Germar** [comment]
So, if you don't touch that drive in Dolphin after you turned on your PC you can still access all the data via Terminal? Or do you have to click it in Dolphin first?

Please run `/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 3 backup-job` manually as user `simone` after initial start of your PC (without touching Dolphin first). Does this create a correct snapshot? In this case it might be missing environ variables during cron job.

The cron job runs as user `simone`. Only profiles created with `Back In Time (root)` would run as root.

**Comment by simgunz** [comment]
I confirm I can access the data via terminal without touching dolphin.

I've tried this:
- Reboot computer without opening dolphin
- Run the suggested command: backup successful
- Setup a cron backup and let it run (just after the previous finished): empty backup

**Comment by simgunz** [comment]
More debugging info:

I've run an sh session containing the environment variables used by cron in this way:

Added the following to crontab: `30 08 * * * env > ~/cronenv`
and then: `env - `cat ~/cronenv` /bin/sh`

from there I've accessed the drive and I can list all the files.

Finally I've run the cron command (ionice ...) manually and the backup succeded.

Running again cron automatically the folder is empty.

**Comment by Germar** [comment]
Hmm, quite strange behaviour...

Okay, lets try something different. Please add a cronjob 
```
30 8 * * * ls -la /media/dataHD /media/dataHD/work /media/dataHD/work/_current > /tmp/filelist
```
and check if `/tmp/filelist` does list the content of all three dirs after cron run that command.

**Comment by hcw70** [comment]
Maybe it is related, i have setup / started a backup job via the gui with "BackinTime (as root)" menu which does something like "sudo backintime-gnome". 
That works but the cron job does not. The cron job complains about "backintime not configured".

Looking closer revealed that the backintime config is put under ~user/.config whereas the cron job expects the config under ~root/.config.

"sudo" is not the same as running it as root regarding the env variables.

**Comment by simgunz** [comment]
I've tried to list the folders from the  cron job, and actually nothing is listed inside the luks mounted device (/media/dataHD). So I guess this problem might be related to pam_mount and the fact that the device is encrypted. I'm trying to look around for a solution.

As an example, the following job:

    */1 * * * * ls -l /media /media/dataHD > /home/myuser/tempfile 2>&1

produce

```
/media:
total 6
drwxr-xr-x 2 root root  4096 10 ott  2015 dataHD

/media/dataHD:
total 0
```

**Comment by Germar** [comment]
@hcw70 `Back In Time (root)` uses `gksu backintime-gnome` to start the GUI. This will correctly set `HOME=/root` and the config will be stored in `/root/.config/backintime`. But if you run `sudo backintime-gnome` the users home environ will be kept.

@simgunz okay, now I get a picture of what happens here. `pam` uses your password during login to decrypt your drive. So when the cronjob starts as your user `pam` can not decrypt because there is no password at all.

I'm still wondering if the cronjob works while you're logged in with your user. If this is the case you could switch to `Repeatedly (anacron)` schedule and add a `/home/USER/.config/backintime/user-callback` scrip which will stop new snapshots while the drive is not mounted:
```
#!/bin/bash

profile_id="$1"
profile_name="$2"
reason="$3"

case $reason in
    1) #Backup process begins
        case $profile_id in
            3) /bin/mountpoint /media/dataHD >/dev/null; exit $?;;
        esac
        ;;
esac
```
The `Repeatedly (anacron)` schedule will try to create a new snapshot every 15 min. If it fails it will retry after 15min. The above script will make it fail while the drive is not mounted (make sure `/bin/mountpoint` is installed).

An other solution would be to decrypt and mount the drive during boot together with your filesystem root. But your root partition must be encrypted, too. Take a look [at this wiki](https://wiki.ubuntuusers.de/LUKS/Schl%C3%BCsselableitung/). I only found German wikis, sorry.

**Comment by simgunz** [comment]
The cron job fails when I'm logged in. I'm not interested in backing up when I'm not logged in, since I'm the only user of the PC, it is off when I'm not logged.

I would like to avoid mounting it on boot, because it requires to input the password during boot and then again during the login (beside the fact that I'll need to encrypt / as well).

I need to figure out why the password is not available to cron while I've logged in.

**Comment by simgunz** [comment]
So this error is caused by the fact that /etc/pam.d/crond is not configured properly to execute pam_mount. I still haven't found a solution but at least I've tracked down the source of the problem. I'll update the issue if I find a solution.

**Comment by simgunz** [comment]
Well apparently /etc/pam.d/cron was not the problem. And the problem now is gone by itself, after many months of struggling to solve it.
