### ISSUE TITLE
backintime with ssh and only password

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#592]
Hi,

I am having a hard time, getting ssh to work without a password on my NAS. Wouldn't it be possible to explicitly allow the connection over ssh eventhough you are only using a password and not a key?
This would be really great, at the moment I resorted to another backup solution, but that's not perfect.
Thanks a lot,
hannes

**Comment by Germar** [comment]
I don't have plans to add this.

Which NAS do you use? Did you took a look at our [FAQ Hardware section](https://github.com/bit-team/backintime/wiki/FAQ)?

**Comment by hannes101** [comment]
Fair enough, then it's fine for me.

**Comment by hannes101** [comment]
Just to follow up on this and to better understand the decision. Is it because of the effort to implement or are there security issues preventing this?

**Comment by Germar** [comment]
It's because of the effort to implement and performance issues. We would need to call a `ask-password` helper script each time `ssh` is called which will collect the password and paste it back to the `ssh` command.
