### ISSUE TITLE
Cannot change settings with ssh backups (custom port)

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#594]
I can't seem to change settings. I'm unsure if a recent commit (perhaps 4e8904f208192b8b6e3cbd072c896b5fc95368ab?) caused this, because it was working fine previously.

I start backintime with `/usr/bin/backintime-qt4_polkit --debug`. I then attempt to change some settings. However, it stalls for ages, at the end of the following output.
```
DEBUG: [common/sshtools.py:279 SSH.unlock_ssh_agent] Private key /root/.ssh/root@pi_rsa is already unlocked in ssh agent
DEBUG: [common/sshtools.py:451 SSH.check_ping_host] Check ping host
DEBUG: [common/sshtools.py:460 SSH.check_ping_host] Host 192.168.1.1 is available
DEBUG: [common/mount.py:582 SSH.check_fuse] Check fuse
DEBUG: [common/sshtools.py:214 SSH.unlock_ssh_agent] Remove private key /root/.ssh/root@pi_rsa from ssh agent
DEBUG: [common/sshtools.py:227 SSH.unlock_ssh_agent] Add private key /root/.ssh/root@pi_rsa to ssh agent
DEBUG: [common/sshtools.py:232 SSH.unlock_ssh_agent] Password available: True
DEBUG: [common/sshtools.py:377 SSH.check_known_hosts] Check known hosts file
DEBUG: [common/sshtools.py:384 SSH.check_known_hosts] Host [192.168.1.1]:123 was found in known hosts file
DEBUG: [common/sshtools.py:288 SSH.check_login] Check login
DEBUG: [common/sshtools.py:319 SSH.check_cipher] Check cipher
```
After a minute or so, the following window pops up.
```
Cipher ARCFOUR failed for 192.168.1.1:
ssh: connect to host 192.168.1.1 port 22: Connection timed out
```
And in the standard out:
```
DEBUG: [common/sshtools.py:335 SSH.check_cipher] Ciper ARCFOUR is not supported
```
Arcfour is definitely fine with my server. However, I noticed that the window above says port 22. However, I'm connecting via port 123, and the first block above agrees. So clearly backintime *is* okay with connecting in some situations. Similarly, I can see all the past snapshots in the left panel, so it's connecting fine there too.

**Comment by protist** [comment]
Also, backing up manually with `time sudo nice -n 19 ionice -c2 -n7 backintime backup --debug` works fine. I remembered I still had that workaround from issue #581 with the following.

    profile1.snapshots.ssh.max_arg_length=1024

So I changed it back to

    profile1.snapshots.ssh.max_arg_length=6

But I still have the same problems saving settings.

**Comment by Germar** [comment]
Oh, sorry. I messed up `check_cipher` with 2ffbac9b043454efc49b1df95a0a435e5271aa49

**Comment by protist** [comment]
Thank you for the quick fix. This works perfectly for me now.
