### ISSUE TITLE
Cannot restore files with spaces in their name from SSH

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#595]
Hi again! This is possibly related to my strange server settings that I've mentioned before (custom port, root, --numeric-ids, arcfour), but I can't restore files via either the GUI or command line.

I get similar errors in both, but here is the error from the GUI's fail. Presumably paths just need to be quoted.
```
rsync -rtDHh --links -A -X -pEgo --info=progress2 --no-i-r --numeric-ids --rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/root/.ssh/root@pi_rsa -p 123 -o Ciphers=arcfour -R -v --backup --suffix=.backup.20160628 root@192.168.1.91:/media/Morlock/backintime/foo-lenovo/root/1/20160627-073002-210/backup/./home/foo/Splitting and printing pdfs.txt /
receiving file list ... 
rsync: link_stat "/media/Morlock/backintime/foo-lenovo/root/1/20160627-073002-210/backup/home/foo/Splitting" failed: No such file or directory (2)
rsync: link_stat "/root/and" failed: No such file or directory (2)
rsync: link_stat "/root/printing" failed: No such file or directory (2)
rsync: link_stat "/root/pdfs.txt" failed: No such file or directory (2)
done
sent 8 bytes  received 388 bytes  792.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1650) [Receiver=3.1.2]
rsync: [Receiver] write error: Broken pipe (32)
 
 
Restore permissions:

Restore permissions: Done
```
Files without spaces in their path work fine.

**Comment by Germar** [comment]
Nope, has nothing to do with your setup. I thought, quotes are not necessary anymore with `subprocess.Popen` because there is no shell in between Python and the external command. And this works quite fine if you run `rsync` only local. But if you use `SSH` mode `rsync` will start a new instance on the remote host through ssh which will run a shell. So I need to add back all those quotes :confounded:

**Comment by protist** [comment]
Thank you again for the quick fix! Works perfectly here.
