### ISSUE TITLE
All my backups just... disappeared.

### ISSUE THREAD

**Issue by maniqui** [bit-team/backintime#598]
I know the summary might sound a bit alarm-triggering.
But I cannot explain yet why all my backups of over a year have just disappeared from my external drive.
I don't discard this is a case of PEBKAC ("problem exists between keyboard and chair")

I'm on Debian Unstable running backintime-qt4 1.1.12
Today, after seeing that the LED of my external HDD was still blinking since more than 24 hours, I checked what was going on. I saw that the BIT icon was there on the systray, and a quick glance showed me that a full backup was taking place.
I wondered why a full backup was being run. I still wonder.
When I went to the backup folder to check what could be going on, I found it almost empty. There was only a backup from 3 days ago. Any other backup from previous days and weeks and months were just lost.

These are some things that I recall doing that might be related to my backups disappearing:
- a few weeks ago, I changed the method of backup to "rsync". But, at that time, after letting BIT run a few times with the new configuration, I've checked and all my backups were still there.
- a few days ago I run GSmartControl (the GUI for smartmontools) to run some checks on the external HDD. There is a chance that I've run it while a backup was being run. Could this have caused problems and/or be related?

I'm not going mad because I don't think I've lost anything important so far (well, just my backups :smile:) and now BIT is backing up my folders again. But I can't figure out what could have happened.

Thanks.

**Comment by maniqui** [comment]
The log for the only snapshot that I found on the backup folder is this:

```
========== Take snapshot (profile 1): Thu Jul 14 00:04:41 2016 ==========

Last snapshot didn't finish but can be continued.

======== continue snapshot (profile 1): Thu Jul 14 09:30:03 2016 ========

Last snapshot didn't finish but can be continued.

======== continue snapshot (profile 1): Thu Jul 14 10:15:02 2016 ========

[E] Error: rsync: write failed on "/media/storejet/backintime/manmachine/root/1/new_snapshot/backup/home/julian/Music/xxxxx/xxxxxxxxxxxx.flac": No space left on device (28)
```

As you can see, the only backup I've found on the backup folder failed because `No space left on device`. I can't say if this backup was created before or after all my backups have disappeared. But, being that the error message reads `No space left on device`, logic says that this snapshot was probably taken _before_ my backups disappeared.

Here are some screenshots of my BIT profile settings:

![image](https://cloud.githubusercontent.com/assets/333695/16903064/9fe68102-4c49-11e6-89db-6e9db71bae53.png)

![image](https://cloud.githubusercontent.com/assets/333695/16903084/02179c12-4c4a-11e6-8c2a-3fbf7a851cf0.png)

**Comment by Germar** [comment]
Sounds like the `If free space is less than 1GiB` rule took place and deleted old snapshots until there was more than 1GiB free again.

Please take a look into your syslog from July 14. There should be some lines like

    INFO: Keep min free disk space: 1024 MiB
    INFO: Command "find ".../backintime/<host>/<user>/1/<snapshot_id1>" -type d -exec chmod u+wx {} +" returns 0
    INFO: Command "rm -rf ".../backintime/<host>/<user>/1/<snapshot_id1>"" returns 0
    INFO: free disk space: 10 MiB
    INFO: Command "find ".../backintime/<host>/<user>/1/<snapshot_id2>" -type d -exec chmod u+wx {} +" returns 0
    INFO: Command "rm -rf ".../backintime/<host>/<user>/1/<snapshot_id2>"" returns 0
    INFO: free disk space: 15 MiB

You might need to browse the already archived syslog with 

    zless /var/log/syslog.2.gz

**Comment by maniqui** [comment]
@Germar, thanks for the prompt reply and for your help.

I've checked the logs for July 14 and a few previous days, and although there are some BIT-related lines, none of them look similar to the ones you posted.
And I can't find anything substantial in relation to all backups being "smart removed" by BIT. 

I can't say exactly how many snapshots did I have (I'd say that 15, or maybe less, but can't be sure). The snapshots were pretty large, because on this profile I'm backing up documents, music, videos, etc. So, deleting any of the older backups should easily have released far more than 1GiB free again.

I think this will remain a mystery. But let me know if I can provide you with any info.

**Comment by Germar** [comment]
> So, deleting any of the older backups should easily have released far more than 1GiB free again.

If there where no (big) changes between those snapshots, deleting one or more snapshots does not necessarily release much space because the files are hard-linked.

But also my `less than free space` theory doesn't explain why ALL snapshots are gone. At least the very last one should be kept.

Was there any other data (beside BIT snapshots) on that drive which disappeared?

Just to make sure your drive is healthy without corruption please run `fsck` on the drive.

**Comment by maniqui** [comment]
Well, maybe the July 14 snapshot was the only one to be kept after the `less than free space` rule was applied. I can't say.
But what I found weird was that a new, full backup began to run (that was the reason I noticed many of my backup were just gone), instead of an incremental backup. 

I've run `fsck` and there seems to be no issues.

```bash
$ sudo fsck /dev/sdd1 -f
fsck from util-linux 2.28
e2fsck 1.43.1 (08-Jun-2016)
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information
Transcend-ext4: 658023/54501376 files (2.3% non-contiguous), 172079768/217976064 block
```

**Comment by buhtz** [comment]
Do we have new informations on that bug or possibilities to get new informations?

If not I would recommend to close the bug.

**Comment by emtiu** [comment]
Closing because there hasn't been feedback from the reporter.
