### ISSUE TITLE
Protect against rm -rf /

### ISSUE THREAD

**Issue by jeffsilverm** [bit-team/backintime#600]
There is an urban legend that some sysadmin somewhere gave the command `rm -rf / ` and killed his company.

I run a snapshot every half an hour.  What I would like to be able to do is umount the backup device until backintime is ready to run, then mount it, do the backintime run, and then umount the backup drive again.  I understand that this is a kludgy solution.  I could setup the backup device to be user mountable in /etc/fstab, so backintime need not run as root nor use sudo.  I thought of using a bash script that does the mount, the run, and then the umount, and put that in crontab.  I've thought about using chroot, and I couldn't quite figure out how to do that one.  I haven't started thinking about how to protect the backup device using SELinux, but even if I did, that seems like a complicated solution, and not scalable, and also a lot of installations do not install SELinux.

1. Is this a real problem?  How often do sysadmins do something that stupid?
2. Is there a simple solution that I'm not seeing?
3. Is this a feature request?  I'm not sure.  I think what I am asking for is for backintime to run as an ordinary user, which is does just fine, and yet be proof against a stupid sysadmin (It can't be proof against a malicious sysadmin).  I'm not sure that's possible, and I do not want to ask for something that can't be done.

Many thanks,

Jeff Silverman

**Comment by Germar** [comment]
Urban legends are... just legends.

    $ sudo rm -rf /
    rm: it is dangerous to operate recursively on '/'
    rm: use --no-preserve-root to override this failsafe

So this won't happen on modern Linux. But for sure there are lot of scenarios which could cause a lost  of your backup. Theft, fire or malware just to name some.

For most of them storing your backups offside is the best solution. This could be done either with one or two external drives which will be placed in an other building/fireproofed locker while not used. Or use a remote machine/NAS over SSH to put your backups on there.

But to come back to your original question, you can use the `~/.config/backintime/user-callback` script to mount/unmount your drive. Starting with BackInTime version 1.1.0 the `user-callback` will be called with third argument = 7 when a drive could get mounted and third argument = 8 when it need to unmount. Take a look at the [examples](https://github.com/bit-team/user-callback) and the [default script](https://github.com/bit-team/user-callback/blob/master/user-callback.default).
