### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by kayakr** [bit-team/backintime#602]
I'm stuck on the config dialog. On Ubuntu 14.04, installed stable version of BiT per Ubuntu PPA instructions. Via the GUI, whether I run Back In Time or Back In Time (root) I end up on Settings dialog. I specify Mode=Local with patch to USB disk under /media path, and include /home/{user} directory. There seems to be no way to save the config and access any other screens. Clicking ok on settings dialog does nothing.

**Comment by Germar** [comment]
Please open a Terminal and run `backintime-qt4 --debug` then try to configure again and post the output from the Terminal in here if it fails again.

**Comment by buhtz** [comment]
I would be interested in the debug output, too.

**Comment by buhtz** [comment]
@kayakr Are you still interested in finding a solution for your problem.

If not I would recommend to close this issue.

**Comment by kayakr** [comment]
Not using BiT right now, closing, thanks.
