### ISSUE TITLE
"Local Encrypted" backup does not work

### ISSUE THREAD

**Issue by themartin78** [bit-team/backintime#604]
Good morning everyone,

when I try to take an encrypted (initial) snapshot, backintime keeps giving me a "Done. No snapshot necessary." message. It does create one encrypted folder in the destination directory with some subdirectories and a few files, but that's about everything it does.

Unencrypted snapshots to the same destination, however, work as supposed.

I'd be extremely happy to use the encryption feature.

OS: Ubuntu 16.04
backintime version: 1.1.12.a

Take care
Martin

**Comment by Germar** [comment]
Please run `backintime-qt4 --debug` from Terminal, create a new encrypted snapshot and post the output from Terminal. Also add the content of `~/.local/share/backintime/takesnapshot_.log`
