### ISSUE TITLE
Make snapshot protocol window non-modal to ease adding of exclusions

### ISSUE THREAD

**Issue by bentolor** [bit-team/backintime#608]
Thank your very for making this great tool! During may day-to-day work I stumble upon a little annoyance which could be fixed very easily: 

I'm using BIT in an encrypted environment. Therefore wildcard ignores do not work. 

So I regularly I open & view the snapshot protocols and scan for unwanted files which are going into the backups (typical folders are cache dirs and build outputs like `target` order `node_modules`). 

Due to the UI I have to:

1. Click "view snapshot protocol" and wait for a few secs
2. Click "decrypt paths" and wait a few secs
3. Start a editor like `gedit`
4. Use `Ctrl-A`, `Ctrl-V` to paste the file liste
5. Close the snapshot protocol and open the settings / browse the tree to add the file/directory exclusions.

In the simplest form if the snapshot window would not be modal I'd be able to move it on the side and add my exclusions while scrolling the list.

**Comment by Germar** [comment]
Good idea and done :wink:

**Comment by bentolor** [comment]
Wow! Great. Looking forward to test it.
