### ISSUE TITLE
GUI status bar unreadable 

### ISSUE THREAD

**Issue by bnilsson11** [bit-team/backintime#612]
My backup operation hangs on a certain file, and will not continue.
The bottom status bar in the backintime-qt4 GUI shows black text on a very dark blue background. At least for me, this is completely unreadable, so I cannot say if it is trying to tell me what is wrong, if anything.
Is there any way of getting the status without using the GUI?
(Or fix the readability problem?)

I am using Ubuntu Studio 16.04, backintime 1.1.12.
I am backing up to a Synology DSS412+ using a SSH passwordless connection.

**Comment by bnilsson11** [comment]
I found out how to do it:
watch -n 1 "cat ~/.local/share/backintime/worker.message; cat ~/.local/share/backintime/worker.progress"

Example output:
Take a snapshot (rsync: home/bnilsson/Video/Musik/Nashville - Part 4 of 6.mp4)eta=1:04:50
percent=64
sent=43.05G
speed=6.01MB/s
status=50

But my complaint remains: 
Could the BIT team please make the status bar readable!
There is no need for a black text on a dark blue background!

**Comment by Germar** [comment]
The colors are set by your Theme. BIT doesn't define any color in GUI. But the problem with unreadable statusbar is based on a bug in Qt progressbar widget. I didn't found a workaround for this in Qt4. But recently I switched BIT to use Qt5 (not released yet) and I'll try again to fix it with Qt5, soon.

**Comment by bnilsson11** [comment]
Thanks, then it is worth waiting for the next qt5 version.
Since I can handle it with the worker.* files it is not urgent for me anymore.

**Comment by rklemme** [comment]
@bnilsson11 you can also do `tail -F ~/.local/share/backintime/worker.message`.
