### ISSUE TITLE
BIT backup stops without error message when disk quota is close but not exceeded

### ISSUE THREAD

**Issue by bnilsson11** [bit-team/backintime#613]
I am backning up to a Synology DS412+, using SSH, set up according to http://superuser.com/questions/996928/backup-of-a-linux-desktop-on-a-synology-nas-ds-5-2-using-backintime.
My OS is Ubuntu Studio 16.04, BIT 1.1.12.

When I am close to but not exceeding my disk quota of the DS412+, the backup hangs without any message. E.g. my quota was set to 2500GB and my usage was indicated 2.44TB.

(Edit 20160808: Quota and used space now exactly as displayed by the DS412+ Web interface)

I suspected corrupt files, so I did Exclude repeatedly (8 times) on the file(s) where the backup halted, and restarted the backup. I got a bit further, the backup hanged again and again. Then finally, I got a "disk quota exceeded".
I extended my quota to 4095GB, and now it runs smoothly.

It seems to be a greyzone where the DS412+ stops receiving data without telling why, or possibly BIT fails to receive it (not likely).

I suggest a selectable timeout in BIT would be appropriate, notifying a "timeout exceeded, please check your disk quota".

**Comment by bnilsson11** [comment]
I left a similar report to Synology.

**Comment by bnilsson11** [comment]
Interesting that 2500 (my quota) / 2440 (my consumption) ≈ 1.024.

**Comment by bnilsson11** [comment]
A simple calculation shows that I had reached the DS quota limit when it happened, i.e. no "greyzone" at all:

Quota = 2500GB
Used Space = 2.44TB = 2 498.56 GB.

So why did the rsync process not acknowledge this and aborted gracefully until after several pushy attempts?

**Comment by Germar** [comment]
Sorry, I don't have a Synology device so I can't tell. Please ask Synology Support why the quota doesn't break the writing progress.

**Comment by buhtzz** [comment]
@bnilsson11 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Maybe we can close this for the first time. But we should add this scenario (reaching quota limit) to our integration tests. I'll make a note on my private TODO.

**Comment by emtiu** [comment]
Closing as outdated.
