### ISSUE TITLE
Partial restore from a snapshot

### ISSUE THREAD

**Issue by afettouhi** [bit-team/backintime#614]
I've been using backintime for over 3 years now. I have build a new PC and now I want to restore my data on to the new machine. I already copied the config file from my oldmachine onto the new one. What I would like to know is, can I do a partial restore from a snapshot? I realised that I only need part of the data now (set it up so long ago). Is that possible?

**Comment by Germar** [comment]
Sure. Just select those files (multi-selection is available since 1.1.0) and hit restore.

**Comment by afettouhi** [comment]
Where in the UI do I select what files/directories I want to restore from a certain snapshot?

**Comment by Germar** [comment]
In the [Files View](http://backintime.readthedocs.io/en/latest/mainwindow.html#overview) of the main window

**Comment by afettouhi** [comment]
Ah many thanks. Just a suggestion, this would be much clearer if it were some boxes the user could tick off.
