### ISSUE TITLE
BiT 1.1.12 doesn't respect user icon selection

### ISSUE THREAD

**Issue by BelladonnavGF** [bit-team/backintime#615]
Hi there!

I already read that BiT no longer has a `backintime-gnome` and `backintime-kde` version, but only a "merged" version, i.e. `backintime-qt4`. I also saw that Germar mentioned that BiT should adapt to the users theme (which it does in my case). Furthermore, BiT should also use the users icon set(ting). According to Germar, if no icon preference is set, BiT defaults to gnome (GTK) or oxygen (KDE).

However, with me, whatever icon I select, BiT persists in only using (in my case Gnome) default setting/ icons. Am I missing something or is this a bug? Other qt (and kde for that matter) applications have no problems adapting to my personal preference.

**Comment by Germar** [comment]
Hi,

I did a little dirty hack for the icons. It tries to load the icon `document-save` (which is the BiT logo as we don't have an own yet) from the current theme. If it fail to load that icon it will set the theme to `ubuntu-mono-dark`, `gnome` and `oxygen` and try again with each to load the `document-save` icon. If it was successful it will keep that theme or proceed with the next theme.

So if this will always use the default Gnome icon theme I'd guess your theme does not have a `document-save` icon and neither has a parent theme which has `document-save` icon. In this case you should add a line to your `index.theme` like:

```
[Icon Theme]
Inherits=default
```

and rebuild the icon cache with `gtk-update-icon-cache -f /usr/share/icon/<YOUR_THEME>`

**Comment by BelladonnavGF** [comment]
Hi Germar,

Thanks for the super speedy reply! I understand what you write, and do remember the (elementary) `document-save` icon being the BiT logo on the window and panel notification area with the BiT-GTK version I used before.
I double checked the suggestions you gave, but those unfortunately don't solve the issue for me. As I wrote before, BiT shows the same (gnome/ default) icon set, _whatever_ icon set I choose/ activate. It is indeed true I have a custom icon set normally, but this one defaults (`Inherits=`) for missing icons to elementary (the Xfce default) as a parent, which does have the `document-save` icon. Furthermore, as I mentioned, I also switched to Humanity (the Ubuntu default I believe) to test, the Breeze and Oxygen (kde) sets, and even HighContrast, which all have the `document-save` icon. None made BiT loose its grip on the gnome icons. And yes, they are all cached properly, even the notorious elementary-xfce-darkest! Hence my original question: am I missing something, or is it just BiT being stubborn? =0

**Comment by Germar** [comment]
Which distribution and version do you use? I'll set up a VM to check this out.

Alternative you could manually disable (add `#` in front) these lines in `/usr/share/backintime/qt4/icon.py` and try again if this helps?

```
for theme in ('ubuntu-mono-dark', 'gnome', 'oxygen'):
    if not QIcon.fromTheme('document-save').isNull():
        break
    QIcon.setThemeName(theme)
```

**Comment by BelladonnavGF** [comment]
I'm on Xubuntu 16.04.1 LTS amd64

```
bella@tiki:~$ cat /proc/version
Linux version 4.4.0-34-generic (buildd@lgw01-20) (gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) ) #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016

bella@tiki:~$ dpkg -l | grep xfdesktop4
ii  xfdesktop4                                                  4.12.3-2ubuntu1                                             amd64        xfce desktop background, icons and root menu manager
```

Did what you suggested, and got very strange results indeed!
Commenting the section out gave me a BiT interface without any icons at all.
Feeling adventurous, I tried the Xfce default icon set only:

`for theme in ('elementary'):`

And this didn't give me any icons at all, similar to commenting the section out. When I add the elementary set to your original code

`for theme in ('elementary', 'ubuntu-mono-dark', 'gnome', 'oxygen'):`

it gives the GUI with gnome icons. Removing the gnome definition

`for theme in ('elementary', 'ubuntu-mono-dark', 'oxygen'):`

gives a GUI with oxygen icons. Curious concerning priority, I also tried

for theme in ('elementary', 'oxygen', 'gnome', 'ubuntu-mono-dark'):

and that indeed gives me a GUI with oxygen icons.

`for theme in ('ubuntu-mono-dark', 'gnome'):`

restores the GUI with oxygen icons.

On a hunch, I tried:

`for theme in ('gnome'):`

... and that give me a GUI with no icons at all, similar to commenting your original code out.
Same thing if I try oxygen only.

I also have to say that "GUI with no icons" needs an additional note. In all combinations I tried the "Show hidden files" icon was present, and remained the same. Furthermore, the root icon and shutdown icons were always present, even if the complete section was commented out. In the gnome and oxygen options I tried these last 2 icons do change according to the defined icon set.

**Comment by Germar** [comment]
Hi BelladonnavGF,

I made myself an XUbuntu VM and was able to reproduce this.

Problem here is Qt running in an GTK+ environ. I did not find any working solution for this either.

But for a workaround you have already been on the right track. Only the theme's name is `elementary-xfce-darker`. So you could change the line into
```
for theme in ('elementary-xfce-darker', 'ubuntu-mono-dark', 'gnome', 'oxygen'):
```

I'm not sure how Ubuntu (Unity) handle this. But icon themes work over there even in Qt apps.

BTW `for theme in ('gnome')` doesn't work because Python recognizes `('gnome')` as a string and not as a tuple and so it will iterate over each and every char of that string. You'd need to add a comma `('gnome', )` to have a one-item-tuple.

Kind regards,
Germar

**Comment by BelladonnavGF** [comment]
Germar, you are a star for forcing me to put on my glasses and look at my syntax properly! After your workaround and pointer concerning my syntax I even got my own bespoke icon set working! THX!

Just curious - now that more and more devs leave GTK and go over to Qt, won't this be a continuing issue in the future?

Bella

**Comment by Germar** [comment]
Hi Bella,

I'm glad I could help :relaxed: 

Yeah, that's indeed an issue which will grow further. Like I said, the Unity folks solved this. But I've no idea how they did. Maybe the XUbuntu folks could adopt this if they contact the Ubuntu Team.

Hey, it sounds like you're having fun creating your own icons. Would you mind creating one for BIT, too? I tried myself several times but I'm no good in icon design. I have a some graphical background as I have a diploma in architecture (the one for bricks and concrete, not for bits and bytes), but that didn't help me much in creating a good icon :see_no_evil:. So I'd be very pleased about some help...

Kind regards,
Germar
