### ISSUE TITLE
Folder exclusions in default profile

### ISSUE THREAD

**Issue by jasiomonitor** [bit-team/backintime#619]
Hi,

In the default profile "/proc/" (with a star, but the star fools github's editor) is listed on the exclusion list. I would suggest changing it to "proc" or something similar: this way it would apply not only to the root /proc, but also to /proc's of chrooted programs. 

And yes, it actually happened to me: recently backintime started to keep waiting forever just consuming cpu and writing nothing. I identified that I had ordered it to include /var in its backups, and quite recently I installed a new program which runs in chroot jail with its own copy of /proc. /var/lib/program/proc/kcore proved to be too much for a backup...

Best regards,

(js).

**Comment by Germar** [comment]
Actually the [default exclude](https://github.com/bit-team/backintime/blob/master/common/config.py#L110) **is** `/proc/*`.  I changed this some releases ago to have the mountpoints backed up, too.
But I don't see, how `/proc/*` should help against `/var/lib/program/proc/kcore`. That wouldn't match. For this you'd need to exclude `proc/*` but IMHO that's far to broad for a default exclude.

**Comment by jasiomonitor** [comment]
Yes, it's `/proc/*` - [shame on]I simply tried to avoid converting the text to italics[shame off]. 
I needed a quick hack, so I included just "proc" on my exclusions list - it's ok with me, but I understand that for you it would be a way to broad. But perhaps a mask like `*/proc/*` would do?

**Comment by jasiomonitor** [comment]
BTW - I also excluded akonadi. Again: simple "akonadi" template may be a way to broad for you, but for me it worked by removing a database which is re-built every day anyway.

**Comment by Germar** [comment]
Na, to be honest I'm not confident of excluding everything called `proc` by default. Just imagine someone with a brand new project for which he/she has no name yet calling it just `proc`. He/she will have a disaster and find all the precious project was excluded...

Your case is somewhat special for a "normal" user. You'll have to tweak the exclude list manually, sorry.
