### ISSUE TITLE
[XFCE] blanks instead of newlines in paths displayed in systray (backintime-notify)

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#621]
![bit_notify](https://cloud.githubusercontent.com/assets/11861496/17836291/5cab80c2-678d-11e6-870d-ef930d375d46.png)

See the example pictures. This is the backintime from repository one week ago on Siduction GNU/Linux (Debian unstable) with Xfce as desktop. See the blank space I marked with a pink circle.

Currently I have no time for deeper diagnosis. But I think there is something with a newline character. Maybe it depends only on Xfce. I'll take care of it later. This is just for reporting.

**Comment by Germar** [comment]
Looks like xfce's systray doesn't support newlines `\n`. BiT does automatically break lines after 80 chars for the systray menu.

**Comment by buhtz** [comment]
You mean this work well on other plattforms?

btw: What means the label `ux`?

**Comment by Germar** [comment]
Jepp, it does.

`ux` means `User eXperience`. `ui` label would indicate a fundamental problem/enhancement with GUI/CUI, `ux` is more like `this could be done better`

**Comment by buhtz** [comment]
Then it is a Qt-bug I think. Couldn't find something about in their bug-tracker.

But I am unable to create a minimal working example to report the problem. I don't understand the concept of that QtAction thing. :)

**Comment by Germar** [comment]
I found an old systray test snipped which could help you debugging. 

```
#!/usr/bin/env python3

import os
import sys
from PyQt4.QtCore import *
from PyQt4.QtGui import *

class My(object):
    def __init__(self):

        self.qapp = QApplication(sys.argv)
        self.status_icon = QSystemTrayIcon(QIcon.fromTheme('document-save'))
        self.contextMenu = QMenu()

        foo = self.contextMenu.addAction('foo\nbar')
        self.status_icon.setContextMenu(self.contextMenu)

    def run(self):
        self.status_icon.show()
        self.qapp.exec_()

if __name__ == '__main__':
    My().run()
```


![systray](https://cloud.githubusercontent.com/assets/2731999/17875128/1f6aab0e-68d0-11e6-9c59-c31763966ce5.png)

**Comment by buhtz** [comment]
I can't reproduce this anymore with Debian 11 and its XFCE.
Might have been a bug with an older XFCE or another component involved.
This report was coming from an "unstable" Debian.

So I'm closing my own bug after nearly 7 years. 🤣
