### ISSUE TITLE
IOWAIT Blockin

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#623]
I love the application and it's working great except for one annoying IOwait blocking issue.  
I setup hourly cron via the config and it renices to -19    yet periodically   and as murphy dictates at the worst times when the backup is kicked off I get a completely unresponsive system for about 1-3 min.    the Only indicator I have is the HDD light on my p50 being lit.

A few times I've notice the iowate at 30-50%  which should completely hose things but  the system is unresponsive.  If it is not IOwait please let me know what to check as this quite annoying when it hits.  

Back to the Praise.. this prog has saved my ass many times  almost as many as timemachine.  the skew being I had the last 9 years on mac and now am back on linux for the last 7 months.

Marty

**Comment by Germar** [comment]
Did you deactivate `ionice` for running as cron-job in `Expert-Options`? `nice -19` only manage to keep CPU usage on lowest level. `ionice` will keep IO usage on lowest level.

**Comment by MBuchaus** [comment]
the settings are set to nice and ionice on cronjob.  is this right?

--- snip ----
#Back In Time system entry, this will be edited by the gui:
0 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null

**Comment by Germar** [comment]
Hmm. Looking good so far. Also your machine should have more than enough power (it's better than my own).

Please save the patch below into a file, apply it with `sudo patch /usr/share/backintime/common/tools.py < patch` and try again if this helps. This should reduce rsync IO usage during start of rsync but also make the progress-bar even more nonsense...

```
--- /tmp/meld-tmpDj_pS5
+++ /home/germar/Dokumente/workspace/backintime/common/tools.py
@@ -453,7 +453,7 @@
         cmd = cmd + ' -pEgo'
 
     if 'progress2' in caps:
-        cmd += ' --info=progress2 --no-i-r'
+        cmd += ' --info=progress2'
 
     if config.rsync_options_enabled():
         cmd += ' ' + config.rsync_options()

```

**Comment by buhtzz** [comment]
The reporting account doesn't exist anymore ("ghost").

Close because extreme hard to reproduce and maybe not relevant in newer versions.
