### ISSUE TITLE
backup-job no longer working

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#624]
I recently updated from backintime `1.1.12.r254.gc3d46ea-1` to the latest `1.1.12.r266.gf574b7f-1` (via Arch Linux's [AUR package](https://aur.archlinux.org/packages/backintime-git/)). My backintime cronjobs have stopped working. I tried to run `backup-job` manually, but this fails silently. `backup` still works as expected.
```
$ sudo /usr/sbin/nice -n 19 /usr/sbin/ionice -c2 -n7 /usr/sbin/backintime backup-job

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Unlock
```
There are no `backintime` or `rsync` processes running.

**Comment by Germar** [comment]
I changed the way BiT forks into background with d484641930155a6e6326f85b66958f23f2e1c6be which could cause the troubles. Is there anything in `syslog` or `~/.local/share/backintime/takesnapshot_.log`?

**Comment by protist** [comment]
The following appends to `journalctl`.
```
Aug 29 09:46:42 protist-XPS-17 python3[29472]: backintime (root/1): INFO: Lock
Aug 29 09:46:42 protist-XPS-17 python3[29472]: backintime (root/1): ERROR: Failed to unlock SSH private key /root/.ssh/root@pi_rsa: Error connecting to agent: No such file or directory
Aug 29 09:46:42 protist-XPS-17 python3[29472]: backintime (root/1): ERROR: Could not unlock ssh private key. Wrong password or password not available for cron.
Aug 29 09:46:42 protist-XPS-17 python3[29472]: backintime (root/1): INFO: Unlock
```
However, as above, I *can* connect fine with `sudo backintime backup`.

There is nothing in `~/.local/share/backintime/takesnapshot_.log`.

**Comment by Germar** [comment]
Ah, okay. I see what happens here. After I made the above mentioned changes `ssh-agent` will terminate immediately after BiT forked into background...

**Comment by protist** [comment]
Thanks. Just to double-check, I tested the commit you mentioned (d484641930155a6e6326f85b66958f23f2e1c6be), and the one prior (c3d46eaa5077895dd6a4c3afeb0ea17a00c30747). You are correct. The bug *was* introduced in the d484641930155a6e6326f85b66958f23f2e1c6be commit.

**Comment by protist** [comment]
Thank you for the quick fix. I can confirm that `backup-job` works perfectly now. Cheers.
