### ISSUE TITLE
User interaction "Question" window has no scroll bar - confirmation buttons off screen

### ISSUE THREAD

**Issue by BelladonnavGF** [bit-team/backintime#625]
Upon selecting a large number of files to restore, a dialog window opens labelled "Question", offering the option to first back up files at the destination location that might be overwritten. After selecting the desired preference, the user can then proceed/ abort by clicking either the Yes or No the button.

In the window all files to be restored are listed.
However, if the list with files to restore is large enough, due to the fact that this user interaction window has no scroll bar, the tick box and buttons can be off screen and thus can not be used/ set/ clicked.

**Comment by buhtz** [comment]
As a workaround before the fix comes up. When you hold `ALT` button and drag the window by mouse.
