### ISSUE TITLE
is there a '--help' in the rsync command?

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#626]
Please see `common/tools.py:688`.

`cmd.append('-rtDHh')`

If I interprete this correct: the last character `h` is the short form of `--help`. Do we need it here?

**Comment by Germar** [comment]
From `man rsync`:

```
--help Print a short help page describing the  options  available  in  rsync  and
       exit.   For  backward-compatibility with older versions of rsync, the help
       will also be output if you use the -h option without any other args.
```

Combinated with other args `-h` is the short form of `--human-readable` which will change size and speed values into SI prefixes.
