### ISSUE TITLE
Reconsider compression of backups

### ISSUE THREAD

**Issue by rugk** [bit-team/backintime#629]
I saw the old issue https://github.com/bit-team/backintime/issues/262 about compressing backups, but I think this issue was about compression a whole backup.
I would however argue in favour of compressing each single file in a GZIP/ZIP/GZ/Brotli/whatever archive. This means you can still compare the single files to save space and AFAIK you should still be able to hardlink/compare the files (as the compressed files should be identical).

This is how Window's own backup utility does it. It just ZIPs each single file or so and it can still update them incrementally...

**Comment by Germar** [comment]
Sorry, but that won't work. Back in Time uses `rsync` to synchronize local data to a new snapshot and `rsync` does compare files size and mod-time to check if a file has changed. So it can't compare a plain file with a compressed file.

The only way to compress the backup data using `rsync` would be to write the files into a single, compressed store and save the metadata in a separate file so `rsync` can browse the metadata for files that have changed on the next run. But that would be a completely different backup program. AFAIK duplicity works like this.

IMHO the only way to use compression with BiT is to use a filesystem which support compression like BTRFS or something like [compFUSEd](https://www.linux.com/news/save-disk-space-use-compfused-transparently-compress-filesystems).
