### ISSUE TITLE
Question: Recommended schema for multiple remotes?

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#631]
Hi,
I have been using BIT for backup for quite a while now. I use a remote server to back-up off site via ssh.
Now, for increased security, I would like to add a second server that resides on a different remote site.

Anyone having experience with this set up? Any recommended practise?

For instance, one way to do this would be to cascade the remote servers and run BIT on one of them to do a back-up to the second. In this way, my computer would do a back-up to one server and then that server would back-up itself to the second server.   

Another variant would be to use different profiles in BIT on my computer, one for each server. However, I am not sure I can have both profiles running automatically? I remember vaguely that only the main profile was activated automatically and any other profile had to be activated manually. Not sure about this. Anyway, activating manually would not be ok for my set up. I would need automatic back-up to both servers.

Any other ideas or thoughts?

Thanks!

**Comment by colinl** [comment]
On 13 September 2016 at 11:02, ersv <notifications@github.com> wrote:

> Hi,
> I have been using BIT for backup for quite a while now. I use a remote
> server to back-up off site via ssh.
> Now, for increased security, I would like to add a second server that
> resides on a different remote site.
>
> Anyone having experience with this set up? Any recommended practise?
>
> For instance, one way to do this would be to cascade the remote servers
> and run BIT on one of them to do a back-up to the second. In this way, my
> computer would do a back-up to one server and then that server would
> back-up itself to the second server.
>

I do this using rsync on a cron job to backup to the second server over the
internet. I tell rsync never to delete anything from the second server just
in case the 1st gets accidentally deleted.  The script I use is

#!/usr/bin/env bash
# rsync backintime archive to vps

LOCK=/some_path/.rsync_lock.1
LOG=/some_path/rsync.log

SOURCE=/path/to/backintime/backup
EXCLUDE=last_snapshot
DESTINATION=user@url:path/to/backups
echo "$(date)  Starting" >> $LOG
(
  # Wait for exclusive lock for 10 seconds, exit if can't get it
  flock -x -w 10 200 || exit 1
  echo "$(date)  Starting rsync"  >> $LOG
  rsync --bwlimit=25 -H -azipc $SOURCE $DESTINATION --exclude=$EXCLUDE  >>
$LOG 2>&1
  echo "$(date)  Done"  >> $LOG
) 200>$LOCK

The bwlimit option is to stop it clobbering my broadband, which is rather
slow.
This technique assumes that ssh access is available from server 1 to server
2 using keys.

Colin

**Comment by Germar** [comment]
You can have multiple profiles running automatically without problems. You could activate `Run only one snapshot at a time` in `Options` to make sure they run serialized. But even two different profiles taking a snapshot at the same time is no problem. It would only slow down your system.

I wouldn't set up a cascade of BiT because that would end up in a huge number of hard-links on the second server. @colinl's script looks good to me. Thanks! If you don't want to use two profiles (maybe because that will double your upload) you should go with Colin's solution.

**Comment by ersv** [comment]
Thank you Colin and Germar, very helpful. 

The script looks like a good thing to keep the load on my computer down. One idea would be to combine the techniques: Use Colin's script to backup to a second server and then set up a second profile in BIT to that server, but keep the second profile inactive. In this way, the load for the second backup would be on the server but I can still easily get to the files on that second server via BIT, should I need to recover any of them. 

Any pros/cons with that set up? Colin, how do you do that part?

**Comment by Germar** [comment]
Sounds reasonable to me.

**Comment by ersv** [comment]
Thanks for the help with this matter, I'll mark it as closed now.

**Comment by colinl** [comment]
ersv, I don't worry about how to restore from the second server.  Remember the backup files on the server can be accessed by normal file access under the snapshot directories (that is one of the reasons I like BIT).  The second server is there just in case of a catastrophic failure of the first server.  The chance of ever having to use it is very small so the fact that recovering might be slightly less convenient than using BIT does not worry me.

**Comment by ersv** [comment]
Colin, I am trying out your script above. 

To check that all is good, I just used the row with the rsync command from your script with the -P option (--progress and --partial) added to make a first sync of the entire backup:  

rsync --bwlimit=2560 -H -azipcP /srv/backup/ server:/srv/backup --exclude=last_snapshot

In doing this, rsync starts up nicely and starts to copy files to the target. 

However, after awhile, it sort of hangs. rsync just stops copying after a certain file, seemingly idle. I guess it maybe is busy calculating/matching hardlinks? After awhile, it starts iterating through files again. 

However, it seems like rsync is going in circles, after some further time it stops again after the exact same file. That is, it is the exact same snapshot (date+time) and the exact same file in that snapshot that it stops after. Then, this circle is repeated again and again. Checking the disk (df -h) used on the target it does not grow from here and rsync does not seem to ever complete the copying.

Do you have any idea as to what can be happening?

**Comment by colinl** [comment]
If it really is copying the same files again, ie the same snapshot date and
time then no I cannot explain it.
Can you run it with, on the end of the command
> logfile.log 2>&1

Let it run till it shows the problem and then put the log somewhere we can
see it.

Colin
