### ISSUE TITLE
Cannot get BiT configured

### ISSUE THREAD

**Issue by robertdaleweir** [bit-team/backintime#632]
[root@ACER media]# backintime-qt4 --debug
DEBUG: [common/backintime.py:509 arg_parse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:576 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:577 getConfig] profiles: ['1']
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin qt4plugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
Qt: Session management error: None of the authentication protocols specified are supported
Bus::open: Can not get ibus-daemon's address. 
IBusInputContext::createInputContext: no connection to ibus-daemon 
q
^CTraceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 1425, in eventFilter
    def eventFilter(self, receiver, event):
KeyboardInterrupt

^C^C^C^C^Z
[1]+  Stopped                 backintime-qt4 --debug
[root@ACER media]# ps aux | grep backin

There is no config file anywhere in /root/.config/backintime/ and I cannot edit profile in the GUI interface

**Comment by Germar** [comment]
Please run `env -u SESSION_MANAGER` and try again.

Alternative you can launch `backintime-qt_polkit` as a normal user to run BiT as root.

**Comment by robertdaleweir** [comment]
I attempted your first run `env -u SESSION_MANAGER` and same result.
On the second item I had the following output `[me@ACER ~]$ backintime-qt_polkit
bash: backintime-qt_polkit: command not found
[me@ACER ~]$ 
Not sure why...
`

**Comment by robertdaleweir** [comment]
Sorry I did not intend to close this thread.

**Comment by robertdaleweir** [comment]
Sorry I did not intend to

**Comment by robertdaleweir** [comment]
Sorry I hit the wrong button by mistake.  I would like to continue with this thread.

**Comment by Germar** [comment]
No worries.
The `command not found` was my fault. Sorry. It is `backintime-qt4_polkit` (watch out for the `4`)

**Comment by robertdaleweir** [comment]
I do not have any executable called 'backintime-qt4_polkit' .  
The output from / follows  --->
[root@ACER /]# locate backintime-qt4
/etc/pam.d/backintime-qt4-root
/etc/security/console.apps/backintime-qt4-root
/usr/bin/backintime-qt4
/usr/bin/backintime-qt4-root
/usr/sbin/backintime-qt4-root
/usr/share/applications/backintime-qt4-root.desktop
/usr/share/applications/backintime-qt4.desktop
/usr/share/doc/backintime-qt4
/usr/share/doc/backintime-qt4/AUTHORS
/usr/share/doc/backintime-qt4/CHANGES
/usr/share/doc/backintime-qt4/LICENSE
/usr/share/doc/backintime-qt4/README.md
/usr/share/doc/backintime-qt4/TRANSLATIONS
/usr/share/doc/backintime-qt4/VERSION
/usr/share/doc/backintime-qt4/copyright
/usr/share/man/man1/backintime-qt4.1.gz
[root@ACER /]# 
<----
I must not have installed everything properly.  :(

**Comment by Germar** [comment]
Oh, looks like your distribution changed the name of that. So please run `backintime-qt4-root`

**Comment by robertdaleweir** [comment]
Thanks for your patience.  It still will not allow me to set the Config.  It ran and opens the GUI however.

**Comment by robertdaleweir** [comment]
Hi Germar.  I have started poking around and realized that I had to ADD a profile and choose a folder to be backed up.  Once I got going it works fine.  I did not understand the interface and was not curious (or brave) enough to experiment.  Thanks for your assistance.  Love this app.  I use 'rsync' from CLI but a friend needs this app. :)

**Comment by robertdaleweir** [comment]
This problem is solved.

**Comment by Germar** [comment]
Good to hear that it works now. But normally you don't need to add a new profile. Just configure `Where to save snapshots` and `Include` for the default `Main profile` and you're good to go.

**Comment by robertdaleweir** [comment]
Thanks I appreciate that.  Have a great day.  :)
