### ISSUE TITLE
[enhancement] add pre and post script capabilities

### ISSUE THREAD

**Issue by kdupke** [bit-team/backintime#633]
[Thank you for this great tool and the effort spent on this. I not only like it but it has helped me many times already. Backintime going back till 2011!]

Please add a option to run a (shell)script before and after the backup job.

Background: On my system I run a mariaDB data base. To get consistent backups I do exports of the data via cron and exclude the data base itself from backintime. It would really help to not have this tasks configured independent but merged in backintime. I could run the export just before the backup.

Other scenario: The backup is on a different system, which should be off while not in use. With scripts I could send a wake-on-lan to the backup system and power it off at the end.

[NB: originally I was up to ask for a WOL and power off feature but figured out that this would be just one specific use case]

**Comment by Germar** [comment]
That's already implemented. Please take a look at [user-callback](https://github.com/bit-team/user-callback) for a basic documentation and examples.

**Comment by kdupke** [comment]
Thank you.

Assumed it's not there as it isn't in the GUI.

regards,
kai
