### ISSUE TITLE
Snapshot?

### ISSUE THREAD

**Issue by robertdaleweir** [bit-team/backintime#636]
Hi
  I have a question, more of a learning curve issue than anything.  Does 'backintime' lock the OS, when it is being run, and do its 'rsync' runs while ALL files are locked, or only the one it is working on?  I use the tool as a user, not as 'root', so I am more concerned whether user files could be changed (or corrupted) while the the backup is being made, if they are being changed by some app while they are in process?  I know this is not as important as the entire system backup.
  Second could 'backintime' actually do a total backup of an OS, perhaps as an 'iso' or something booted while the system being backed up is down?
  Thanks...
Robert

**Comment by Germar** [comment]
Hi Robert,

no, BiT doesn't lock files or the OS (it only locks suspend/hibernate while running). If a file changes during BiT is running rsync will transfer the new version. It will add a warning at the end `rsync warning: some files vanished before they could be transferred (code 24)`. But if rsync already synced the file before the changes, the old version will be kept. 

BiT does not create ISOs or anything bootable. Just a snapshot of the selected files. You can of course create snapshots of your whole system and also restore them after a disaster. I'd recommend using e.g. Clonezilla to create an additional image of your system which can be restored first and finally use BiT to go back to the last working snapshot. This way you already have a working system where you can launch BiT and don't need to recreate and format partitions and run BiT in a Live System.

But IMHO it is an overkill to take snapshots of the whole system. On a "normal" system all the files come from repositories which can be installed again easily. So if you take a backup of the selection of installed packages you can restore them quite fast. Take a look at the FAQ about [backing up Package selections](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection) and how to [restore them](https://github.com/bit-team/backintime/wiki/FAQ#how-to-restore-debian-ubuntu-package-selection). So all you need to do is to add the `user-callback` script and include the folder `~/.apt-backup`. You should also take snapshots of `/etc` and `/usr/local/` as root. If you add any software without the package-management, you should install them in `/usr/local/bin/`.

In case of a disaster you only need to install a basic system, install BiT, restore your home, `/etc` and `/usr/local` and follow the FAQ to [restore the package selections](https://github.com/bit-team/backintime/wiki/FAQ#how-to-restore-debian-ubuntu-package-selection)

Regards,
Germar

**Comment by robertdaleweir** [comment]
Thank you.  I sort of thought that but you have clarified it for me.  Your explanation is much appreciated and very thorough.  Now that I have mastered 'backintime', it is very much my choice for backing up using a GUI.  Your efforts are extremely helpful.  :D

**Comment by Germar** [comment]
Glad I could help ;)
