### ISSUE TITLE
Numerous blank emails

### ISSUE THREAD

**Issue by tbclark3** [bit-team/backintime#638]
This morning I updated my server from Fedora 23 to Fedora 24, which upgraded Backintime to version 1.1.12.  Beginning with the upgrade, I get two blank emails every time I open the Backintime GUI, every time I switch profiles within the GUI, and every time Backintime runs from a cron job.  The cron jobs are apparently still working, and are still correctly sending email with a report, though accompanied by two blank emails each time.

**Comment by Germar** [comment]
BiT it self does not send any mails. Did you configure a `user-callback` script which sends mails? I added checkboxes in `Expert Options` to enable stdout/stderr redirection to `/dev/null` from cronjobs. This should both be enabled for existing profiles (new profiles have only stdout redirected by default). Please double check if they are both enabled.

**Comment by tbclark3** [comment]
Yes, the email is by means of a user-callback script.  Both checkboxes are checked. Could BiT be triggering the script at inappropriate times?

**Comment by tbclark3** [comment]
Whoops, I just found your updated user-callback scripts,and replaced my user-callback.sendmail script.  That appears to have fixed the issue.  Sorry to disturb you, but perhaps others will find this thread and benefit.

**Comment by Germar** [comment]
Oh sure, I added new triggers for the `user-callback` script. Take a look at [user-callback repository](https://github.com/bit-team/user-callback) for a basic documentation and examples
