### ISSUE TITLE
Unable to locate package backintime-qt 

### ISSUE THREAD

**Issue by harmlessdrudge** [bit-team/backintime#639]
Just tried to install per instructions here on a new Linux Mint 18 installation. Received the error message

Unable to locate package backintime-qt

After some searching I succeeded with 

sudo apt-get install backintime-qt4

Doc fix?

**Comment by Germar** [comment]
Oh, sorry for the confusion. `backintime-qt` is the name in the upcoming new version (not released yet). It will use Qt5.

**Comment by Aktab** [comment]
Having the same issue here on Debian 8, "sudo apt-get install backintime-qt4" throws the same error message:

Unable to locate package backintime-qt4

Any idea how I can fix it?

**Comment by Germar** [comment]
Debian has an old version which provided a Gnome and a KDE GUI. Install either `backintime-gnome` or `backintime-kde`

**Comment by iootaa** [comment]
You can get a fancy interface in Debian 10 if you install `backintime-qt` from `testing`: `apt install  backintime-qt/testing` did the trick for me
