### ISSUE TITLE
Gnome 3.22 Wayland default replaces X.org; BIT cannot connect to X server

### ISSUE THREAD

**Issue by dtschmitz** [bit-team/backintime#640]
BIT produces this error:

> [root@ThinkPad dts]# backintime-qt4

Back In Time
Version: 1.1.13

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

No protocol specified
app.py: cannot connect to X server :0
[root@ThinkPad dts]# 

I am running Gnome Shell 3.22 in Arch with its default display engine - Wayland.
Arch Linux is rolling release.

Please review and advise -- Thank you for a superb application!
Dietrich

**Comment by Germar** [comment]
I'm out on vacations atm. Will have a look at this, soon.

**Comment by Germar** [comment]
Sorry for the long delay.

This seems to be a general problem with wayland not allowing GUI applications run as root. Take a look at this [bug on Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1274451).

Curious thing is, it doesn't even work with `pkexec`. BiT already uses `pkexec` to run as root (`backintime-qt4_polkit`). I also installed a policy for `gedit` which failed, too.

**Comment by dtschmitz** [comment]
Bump.

**Comment by Germar** [comment]
Please install `qt5-wayland` and apply [this patch](https://gist.github.com/Germar/cf75ae4a008409a5c245c0b317ca0d24):

```
sudo patch /usr/bin/backintime-qt_polkit < wayland_pkexec.patch
```

**Comment by dtschmitz** [comment]
[dts@ThinkPad ~]$ sudo patch /usr/bin/backintime-qt_polkit < wayland_pkexec.patch
bash: wayland_pkexec.patch: No such file or directory
[dts@ThinkPad ~]$ ls -l /usr/bin/backin*
-rwxr-xr-x 1 root root 1533 May 11  2016 /usr/bin/backintime
-rwxr-xr-x 1 root root 1162 May 11  2016 /usr/bin/backintime-askpass
-rwxr-xr-x 1 root root 1235 May 11  2016 /usr/bin/backintime-qt4
-rwxr-xr-x 1 root root   73 May 11  2016 /usr/bin/backintime-qt4_polkit
[dts@ThinkPad ~]$ 


^^ a file: /usr/bin/backintime-qt_polkit  does not exist.

Thank you for your quick reply.
Please review and advise.

**Comment by Germar** [comment]
You should have [downloaded it from this link](https://gist.github.com/Germar/cf75ae4a008409a5c245c0b317ca0d24)

**Comment by Germar** [comment]
Oh, sorry. I've overseen you use the stable version. Please install `1.2.0~alpha` with backintime-git from AUR. It won't work with `1.1.12`

**Comment by dtschmitz** [comment]
http://i.imgur.com/9BHk3YE.png
see above image ^^
I'm on 1.1.12.  What next? ;)

**Comment by Germar** [comment]
Please download the package again and install it manually:

```
wget https://aur.archlinux.org/cgit/aur.git/snapshot/backintime-git.tar.gz
tar xvzf backintime-git.tar.gz
cd backintime-git
makepkg -srci
```

The command `backintime --version` should show should show `backintime 1.2.0~alpha0` when done

**Comment by dtschmitz** [comment]
makepkg aborts with error: http://i.imgur.com/2EXpRmh.png

#facepalm

**Comment by dtschmitz** [comment]
i think i can wait for a production version.  am using Xorg gnome-shell and the backup runs fine with backintime-cli.

**Comment by Germar** [comment]
Okay. Which `cron` daemon did use above? Wasn't able to reproduce the unittest fail...

**Comment by dtschmitz** [comment]
root
[root@ThinkPad backintime-git]# crontab -l
#Back In Time system entry, this will be edited by the gui:
0 0 * * * /usr/sbin/nice -n 19 /usr/sbin/ionice -c2 -n7 /usr/sbin/backintime backup-job >/dev/null 2>&1

I'm fine for now.  Will wait until your revision is prod

**Comment by Germar** [comment]
@dtschmitz it does work now with [backintime-git](https://aur.archlinux.org/pkgbase/backintime-git/)

**Comment by dtschmitz** [comment]
okay thanks for your follow-up.

**Comment by kthneighbor** [comment]
any way to solve this issue on fedora (25) yet?

**Comment by Germar** [comment]
@kthneighbor Is there a testing repository for BiT on Fedora which provides 1.2.0 alpha?

**Comment by kerner1000** [comment]
Hi there, anything new on that topic? Just upgraded to Ubuntu 17.10., BiT stable wont start..

**Comment by sebastien** [comment]
I'm on Fedora 29, applied the patch mentioned above and still can't start BiT root version:

```
Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

No protocol specified
app.py: cannot connect to X server :0.0
```

It's weird because the `/usr/bin/backintime-qt4_polkit` script does specify wayland as the QT backend.

```
#!/bin/sh
pkexec --disable-internal-agent env QT_QPA_PLATFORM=wayland-egl XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR "/usr/bin/backintime-qt4" "$@"
```

I tried also `wayland` instead of `wayland-egl` with no better success. Everything works on X11 though.

**Comment by simonsan** [comment]
Having the same issues with Debian 10 now. :-(

**Comment by simonsan** [comment]
Found the solution:
https://stackoverflow.com/a/646947

> Non-Authorised User trying to run the X Application
> Solution ( as X owning user, ie: yourself )

`xhost +local:root   # where root is the local user you want to grant access to.`
