### ISSUE TITLE
Problem with Schedule "when disk get connected"

### ISSUE THREAD

**Issue by urilabob** [bit-team/backintime#641]
This may be a misunderstanding or an rfe rather than a bug, I'm happy to help with any documentation required to clarify it.
I'm using a systemd option in /etc/fstab to automount a partition for use by backintime at /backup/backup2. The partition is an LVM logical volume containing an ext4 filesystem. This seems to work fine for the rest of backintime. However when I try to use "when disk get connected", which I assume works off something getting mounted at the location /backup/backup2, I get a message that backintime can't get the UUID. Unfortunately I can't find anything in the system or backintime logs that relates to this problem.
My best guess is that this option is trying to get the UUID of the disk that the filesystem resides in, but that this isn't possible because of the indirection via LVM. If this is so, I wonder if it would be possible for backintime to trigger off the UUID of the filesystem getting mounted, rather than off the connection of the UUID of the disk, for this purpose? This would be more flexible (specifically in supporting lvm, which has major advantages in flexibility for backup targets), but it might also remove potential timing issues (the time between connecting a disk and having it mounted cannot be guaranteed, so I presume that if the trigger is connecting the disk, there must be a risk that backintime starts trying to backup before the partition is mounted). But I know close to zero about udev, so please forgive any misunderstanding.
My second-best guess is that the problem arises from the partition mount being via systemd (in which case there might be some jiggery-pokery that I can do to help to make sure the mount is visible).
Happy to help in any way I can, including writing/testing code and learning udev if required, but some pointers as to what would need to be done would be appreciated.

**Comment by Germar** [comment]
I'm not sure, if LVM devices trigger an `udev` event. You can check this with `udevadm monitor`. The mount actually doesn't mater. `udev` normally get triggered when the block-device get connected. So this should happen when you run `vgchange -ay`.

I'm on vacation. Will have a look at this, soon.

**Comment by buhtzz** [comment]
@urilabob There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

I never used LVM so my opinion isn't quit strong. But this seems relevant and should be checked how BIT/udev react in such a situation.

Not sure about tags: "Further investigation"

**Comment by urilabob** [comment]
Hi and thanks. I ended up not using backintime, as I couldn't get it to
work in my context. Somewhere along the way, maybe due to the LVM issues,
the setup ended up corrupted, and I couldn't find a way to clean it up.
These days I just do a full backup every time I upgrade Fedora. Not ideal,
but I don't have that much critically important stuff these days. So no,
it's not really that relevant, and after this time I'm not too sure whether
I could replicate the problem. But thanks for contacting me
     All the Best
     Bob
