### ISSUE TITLE
encrypted backup to "cloud": integrate with rclone?

### ISSUE THREAD

**Issue by juliencarnot** [bit-team/backintime#642]
I'm looking for a solution to encrypt and backup my local data to a cloud service, minimizing intervention/supervision needs, and offering an easy way restore files from previous snapshots. I know that BIT supports saving to a distant server via SSH, but I'm not aware of cheap cloud offers that support SSH...

Not sure if http://rclone.org could be a drop-in/alternative mode for rsync but it does seem to offer access to several of the major "cloud" players and supports encryption, but apparently does not offer history/snapshots. Would it make sense for BIT to integrate with rclone to offer backing up to cloud services or is this out of the scope?

**Comment by Germar** [comment]
Sure, that would be nice to have. But it would be a complete new program which would need to be written from scratch. BiT does not have a "backend" design where we could simply switch between `rsync` and `rclone`.

I'm currently working on a new version which will work with pure `rsync` and `sshfs` support on the remote machine. This should make it easier to use cloud services as you don't need a remote shell anymore.
