### ISSUE TITLE
Moving backups to a new server howto make backintime aware of this

### ISSUE THREAD

**Issue by afettouhi** [bit-team/backintime#645]
Like the title says I have a drobofs file server, that I am planning to retire in the next couple of weeks with custom build PC running freenas with ZFS instead. All my backups from the last two years (since I started using backintime) are on the drobofs and they span my old pc and my new pc. I will be copying all my stuff over to the new server and disconnect the old one. How do I make backintime see the old backups on the new file server?

**Comment by Germar** [comment]
First of all please make sure, you preserve the hard-links while coping. Take a look at [the FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive)

For BiT you only need to copy your public key to the new server with `ssh-copy-id -i ~/.ssh/id_rsa.pub USER@NEW_SERVER` and change `Host` and maybe `Path` in Settings to the new server.

**Comment by afettouhi** [comment]
ssh-copy-id is only needed if I was using ssh?

**Comment by Germar** [comment]
Oh, sure. I assumed you did!? If not, you really should as it is lot faster than syncing to a local mounted share

**Comment by afettouhi** [comment]
I never set it up I think because I connect to my share via cifs. How much faster is it with ssh? Can I set it up after I copy everything over?

**Comment by Germar** [comment]
Depends on your setup. But should be two to three times faster than syncing to a local mounted share.

Sure, you can change it later, too. Take a look at `man backintime` section SSH on how to set it up.

**Comment by afettouhi** [comment]
Uh nice! Will look into that when I get the server up and running and everything copied over.
