### ISSUE TITLE
Enable bwlimit option for local mode

### ISSUE THREAD

**Issue by rugk** [bit-team/backintime#646]
BiT v1.0.36

In the advanced options of a backup these three options are disabled:
![optionsdis](https://cloud.githubusercontent.com/assets/11966684/19315797/68c18894-909f-11e6-8527-c0437615515f.png)

(sorry for not having an English screenshot, my system is set to non-English)

It is not clear why and how to enable them.
In my case I'd like to use the option to limit the bandwidth of rsync (third option). AFAIK this is just a parameter you can pass to --rsync, so why can't I use this?

**Comment by Germar** [comment]
You're using mode `Local` or `Local encrypted`. Those three options are only enabled with modes `SSH` or `SSH encrypted`. The first and second wouldn't make sense on local because `nice` and `ionice` level effect all child processes. Including the receiving rsync process on a local sync.
The third option will only limit bandwidth of the transfer between sending and receiving rsync processes. IMHO this only make sense while syncing over network, too.

**Comment by rugk** [comment]
Thx for your answer.

> Those three options are only enabled with modes SSH or SSH encrypted. 

Ah, all right. Maybe you should indicate this in the UI or at least mention it somewhere in the doc.

> The third option will only limit bandwidth of the transfer between sending and receiving rsync processes. IMHO this only make sense while syncing over network, too.

Yeah, maybe. Maybe not. I think this decision could be left to the user.

I mean basically this does the same as ionice ([as explained here](http://www.cyberciti.biz/faq/throttle-disk-io-rate-limit-disk-io/)) - and these can also be enabled when using the local backup option.

BTW: To what value is ionice actually set? (I hope "Idle")

**Comment by Germar** [comment]
BiT uses `nice -n 19 ionice -c2 -n7`

**Comment by rugk** [comment]
Okay, so some more questions:
1. I should be able to see the nice/ionice process running in task manager (in tree view), should not I?
2. My task manager (GNOM's one) should be able to see a lower priority when I right-click on a rsync process started by BiT and choose "Priority", should not it?

**Comment by Germar** [comment]
1. Nope. They won't show up in process tree
2. Yes, you should see that

![nice](https://cloud.githubusercontent.com/assets/2731999/19327620/2485fc1a-90d0-11e6-8a04-fae220558787.png)

**Comment by rugk** [comment]
Okay, I'll check that when the next backup is started.
