### ISSUE TITLE
backintime + ssh multihop

### ISSUE THREAD

**Issue by 2e0byo** [bit-team/backintime#647]
`HOSTB` (the backup fileserver) is only availble via `HOSTA`, so I use multihop setup in `~/.ssh/config` so that `ssh hostB` works fine; but I can't seem to get backintime to be aware of this.  Does backintime consider `~/ssh/config` or if not is there some way to set a manual ssh command?  I couldn't seem to find anything in the docs.

Thanks very much.

**Comment by Germar** [comment]
I checked with this [config example](http://sshmenu.sourceforge.net/articles/transparent-mulithop.html) (A Better Way). It works fine without any need for manual ssh commands.
But BiT is not able to ping the remote host (actually it's no ping at all but a port-check on the host/port). If I manually disable this check in source the multihop works fine.

So I could offer you to add an expert option to disable the ping-check.

BTW make sure your config is in `~/.ssh/config`!

**Comment by 2e0byo** [comment]
that makes sense; if you get round to it that would be excellent. (yes, that's exactly the config)

**Comment by 2e0byo** [comment]
After a cursory glance at the code I wonder if the port-check is part of the sshfs mount?  but that will take out the remote browsing as well, won't it---if it's the sshfs failing?  Or maybe I didn't look at the source carefully enough and there's a port check function I couldn't find, which is very likely.  But as a workaround I'm just using a local tunnel.  I'll have a dig around in the code and try to find it, but a pointer would be very welcome.

Many thanks

**Comment by Germar** [comment]
I already did all necessary changes but didn't commit them yet. Will make a new Alpha release this weekend

**Comment by 2e0byo** [comment]
brilliant, I'll give it a go when you do, thanks very much.

**Comment by Germar** [comment]
`1.2.0~alpha09` should be up and running in half an hour on `ppa:bit-team/testing`

**Comment by 2e0byo** [comment]
Many thanks: I�ll try it tomorrow.
