### ISSUE TITLE
Auto-remove paramters not applied

### ISSUE THREAD

**Issue by ChrisBail** [bit-team/backintime#649]
Hi,

I realized last night that back up failed because I've no more space left on my drive. So I changed the the parameters in auto-remove so that I remove the snapshot if there is less than 10gb on my disk. However nothing is done. Any idea why?

Regards

**Comment by Germar** [comment]
The `freeSpace` subroutines only run if there was no error. If your disk is full so no new snapshot could be created BiT will fail with an error and doesn't run `freeSpace` either. You need to manually remove snapshots first.
