### ISSUE TITLE
Plugin errors cause the program to hang

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#65]
If there is a programming error in one of the plugins it does not report this back to the program, resulting in an indefinite loop in the main program.

---

Imported from Launchpad using lp2gh.
- date created: 2009-10-08T09:40:30Z
- owner: bratdaking
- the launchpad url was https://bugs.launchpad.net/bugs/446168

**Comment by buhtz** [comment]
I asked report opener on launchpad

> Can you please give feedback if this problem is still relevant for you in the current stable or development version of backintime?
