### ISSUE TITLE
Changelog on web lacks dates

### ISSUE THREAD

**Issue by jnordeng** [bit-team/backintime#651]
This is pretty minor, but the changelog page
  http://backintime.le-web.org/change-log
would be a lot more useful if it included dates for the entries.

I'm finally updating from ubuntu 10.04 to 16.04 (yes, I like legacy software).  I wanted to see if backintime was still being actively developed.  I had to go all the way into github to find out that 1.1.12 was released Jan of this year (which is recent by my standards :-).

Thanks,
-Jeff

**Comment by Germar** [comment]
backintime.le-web.org is owned by Dan who left the project. The projects new home is GitHub.
