### ISSUE TITLE
Snapshots have stopped. Just says 'Working: Create hard-links'

### ISSUE THREAD

**Issue by EagleOwl900** [bit-team/backintime#653]
Hi,

I am new to using Back in time, I have the backups happen on an external 8TB disk in NTFS.
I am running ubuntu 16.04 LTS, 64-bit, on AMD Turion(tm) II Neo N54L Dual-core
With 1.8GB Memory.

Snapshots have been happening, it needed to transfer an initial 4.5TB, I believe this has now happened.
However for 2 days no new snapshots appear to have taken place and it says in the bottom of its window. 'Working: Create hard-links'

What do I need to do?

Thank you

**Comment by Germar** [comment]
Please manually remove `~/.local/share/backintime/worker.*` files and start BiT again.

**Comment by LeonArundell** [comment]
I have the same problem.
To see the ~/.local directory (which is within my home folder) I had to select "View > Show hidden files" from the Dolphin file viewer.
I have a ~/.local/share/backintime/ directory.
I have deleted the files worker2.lock, worker3.message and worker3.lock.
After re-starting, BackInTime still seems to be stuck at "create hard-links"

**Comment by LeonArundell** [comment]
I have also tried uninstalling and reinstalling BackInTime. It stil stops at "create hard-links"

**Comment by Germar** [comment]
@LeonArundell please open a Terminal, run `backintime --debug backup` and post the output here.

**Comment by LeonArundell** [comment]
After a completely new installation of Ubuntu 16.04 (without updates), my BackInTime is working again.

**Comment by mxa** [comment]
I have the same issue and there is no `worker` directory in `~/.local/share/backintime/`.
Additionally I had the issue that the external backup drive disconnected (bad cable) and then the  root directory filled up (backups in a folder /media/user/nameofbackupdrive ) instead of on the external media.
Back in time makes my desktop manager freeze (Cinnamon).

**Comment by Germar** [comment]
@mxa please check the external drive for consistency. Might have some corrupt sectors caused by the bad cable.

If that doesn't help please post the output of `backintime --debug backup`

**Comment by mxa** [comment]
@Germar good call. tried to check it ant even gparted freezes when trying to repair. Something with that drive is going on.

**Comment by mxa** [comment]
Forgot to mention it is a ntfs drive. Could that cause an issue? It worked okay until now though.

**Comment by Germar** [comment]
Please use a Windows machine for repairing NTFS. Or even better, backup your important data from that drive and reformat it. Filesystem is damaged, so this would be the best way.

**Comment by mxa** [comment]
> @mxa There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?
Thanks for reaching out -- I currently do not use backintime (at the moment running nextcloud sync for partial cloud backups). I may in the future go back to using a local disk for backups, but never again on an ntfs drive for sure.
