### ISSUE TITLE
Ubuntu 16.04 to Qnap ssh connection, "[qnap_ip] not found in ssh_known_hosts." error.

### ISSUE THREAD

**Issue by mkkyah** [bit-team/backintime#657]
Hi,
I'm trying to setup BIT to backup my Ubuntu 16.04 laptop to my Qnap TS-210 arm NAS.
I have found this https://github.com/bit-team/backintime/issues/481 with similar problems and tried a mixed solution with this tutorials:
https://wiki.qnap.com/wiki/SSH:_How_To_Set_Up_Authorized_Keys
http://backintime.readthedocs.io/en/latest/settings.html

At the end, I can passwordless ssh to Qnap from laptop's terminal even with your command:
ssh -o PreferredAuthentications=publickey -p 22 -o ServerAliveInterval=240 -o IdentityFile=/home/[user]/.ssh/id_rsa admin@[qnap-ip].

But from BIT setup, when I click ok, I get "[qnap_ip] not found in ssh_known_hosts." error.

I have not used Openssh on Qnap, but decided to stay with default sshd. I'm ok with admin login limit, I hope that's not creating other problems. (I have installed openssh on qnap, but shamefully couldn't make it start on Nas boots! I was so confused and decided to uninstall it)

I hope you can help me with this issue and I wish you can simplify "BIT backup to nas" process on future releases.

**Comment by Germar** [comment]
Are you running BiT as root? If so, you need to run `sudo -i ssh admin@[qnap-ip]` once to add `[qnap-ip]` to `/root/.ssh/known_hosts`. At the moment only your normal user knows the remote host.

Please also have a look at our FAQ [How to use QNAP QTS with BIT over SSH](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-qnap-qts-with-bit-over-ssh).

---------

I already improved that process a lot. But that's not yet released. You can check it out
```
sudo add-apt-repository ppa:bit-team/testing
sudo apt update
sudo apt upgrade
```

The current alpha version will set up known_hosts and SSH public/private key automatically if you want. And it should not need Entware anymore (did not test that yet because I don't own a QNAP device).

**Comment by mkkyah** [comment]
Thanks for the fast answer Germar,
I'm running Bit as root and sudo -i ssh ... helped me to pass that step and I did also install Entware-ng and run all opkg update/upgrade/install fixes from FAQ, but I still get fallowing error:
_Remote host 192.168.1.20 doesn't support 'find PATH -type f -exec chmod u-wx {} \;':
BusyBox v1.01 (2016.10.27-18:44+0000) multi-call binary_

**Comment by Germar** [comment]
It still uses the builtin `find` (BusyBox). Did you activate `SSH prefix` with `PATH=/opt/bin:/opt/sbin:\$PATH` in `Expert Options`?

On the other hand I really recommend using the new alpha version. It runs stable and doesn't need `find` anymore.

**Comment by mkkyah** [comment]
ok, I missed that, BiT started with my ssh config, but I get write errors. The share has admin permissions.

I will start with the alpha build from scratch and test it. What should I remove/clean before I start with it?

**Comment by Germar** [comment]
Nothing need to be cleaned up before. Whats this write errors?

**Comment by mkkyah** [comment]
Nas has at least 600GB free space. I'm trying to backup my downloads folder to test only. I have also added a new file to Downloads folder after the error, BiT says "done, no backup needed." when I try to take a snapshot.

========== Take snapshot (profile 1): Mon Nov  7 00:11:29 2016 ==========

[E] Error: rsync: [sender] write error: Broken pipe (32)
[E] Error: rsync: write failed on "/EnvyAutoBackup/backintime/Envy/root/1/new_snapshot/backup/home/[User]/Downloads/CrashPlan_4.8.0_Linux.tgz": No space left on device (28)

**Comment by Germar** [comment]
Hmm. Maybe quota? Or the default `rsync` on QNAP doesn't work with BiT. Try to add `--rsync-path="/opt/bin/rsync"` (or what ever the path is to Entwares rsync on the NAS)  to `Add prefix to SSH commands` in `Expert Options`

**Comment by mkkyah** [comment]
I have added that to add prefix to ssh commands in expert options. My full prefix line is like this:
_PATH=/opt/bin:/opt/sbin:\$PATH --rsync-path="/opt/bin/rsync"_
 Now BiT keeps asking "Would you like to copy your public SSH key to the
remote host to enable password-less login?" It keeps asking the same if I click yes.

**Comment by Germar** [comment]
Oh, sorry. My fault. `--rsync-path="/opt/bin/rsync"` need to go into `Paste additional options to rsync`.

**Comment by mkkyah** [comment]
ok, it accepted the option and stopped asking same question, but I get same error. I have checked /opt/bin/rscync in Qnap, it's correct path.

**Comment by Germar** [comment]
Okay. What about quota? Is there any quota set for admin? What happen if you manually transfer a file to your NAS? 
```
scp /path/to/big/file admin@[qnap-ip]
```

**Comment by mkkyah** [comment]
Germar,
If I open settings/expert options, I see that _--rsync-path="/opt/bin/rsync"_ is not there, not saved. I have tried again, it's not staying saved.

**Comment by mkkyah** [comment]
--I have no quota for any user
-- scp copy works from laptop to NAS backup share.

**Comment by Germar** [comment]
Fixed the bug with with rsync option. I'll push a new alpha to Launchpad. Should be up in half an hour. But I need to go sleep now. Sorry.

**Comment by mkkyah** [comment]
thanks,
good idea, I need that sleep, too.
I'll keep reporting tomorrow.

**Comment by mkkyah** [comment]
Hi Germar,
It's working now, but it had nothing to do with --rsync option. At least we have found not saving bug.

I had to change destination folder path as "/share/[BackupShare]/". Now it seems working well.
Thanks, for your help.

**Comment by mkkyah** [comment]
Hi Germar,
After a Qnap firmware update I'm having BiT errors. BiT can't login to ssh. I have checked with terminal and I can login with passphrase, passwordless after a _ssh-keygen -f "/root/.ssh/known_hosts" -R [qnap_ip]_
What  should I remove and which steps should I  repat to fix it again?
BiT asks "Would you like to copy your public SSH key to the
remote host to enable password-less login?" if I open settings, input "ssh private key password"(it's empty, is this normal) and click ok. Nothing happens, no connection, no error, no confirmation.

**Comment by mkkyah** [comment]
sudo -i ssh admin@[qnap-ip] worked once more.
