### ISSUE TITLE
1.2.0 alpha10 possibly not saving ssh private key password

### ISSUE THREAD

**Issue by mkkyah** [bit-team/backintime#658]
Thanks to Germar's help I could install and have a working BiT 1.2.0 alpha10.
I think Bit settings is not saving ssh private key password. After a reboot BiT asks for the password when scheduled snapshot starts in the background. If I enter the password it continues.
I don't know if it's the normal behavior, but corresponding password input area is empty when I open the settings.

**Comment by Germar** [comment]
Root does not have a keyring and so BiT can not save the password into a keyring. I'd recommend using a passphrase-less private SSH key for root. You can remove the passphrase from your existing key with `sudo ssh-keygen -f /root/.ssh/id_rsa -p` then enter your old passphrase and hit <kbd>Enter</kbd> twice for an empty new passphrase

**Comment by mkkyah** [comment]
I have no id-rsa in /root/.ssh but _sudo ssh-keygen -f /home/[user]/.ssh/id_rsa -p_ worked, thank you.
