### ISSUE TITLE
[Arch] test fail: Failed to read process stat from /proc/21073/stat: [2] No such file or directory

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#659]
I'm installing backintime-git from the Arch Linux AUR [PKGBUILD](https://aur.archlinux.org/packages/backintime-git/), and I get the following issue during the `check` phase. This is when I make the package, even before installing it (although I have the latest version already installed.) I'm fairly sure that it's not a packaging problem, because I can replicate the issue when running the command manually.
```
$ cd backintime/common
$ LANG=en_US.UTF-8 make test
python3 -m unittest  -b test/test_applicationinstance.py
...................
----------------------------------------------------------------------
Ran 19 tests in 0.043s

OK
python3 -m unittest  -b test/test_argparser.py
.....................
----------------------------------------------------------------------
Ran 21 tests in 5.884s

OK
python3 -m unittest  -b test/test_backintime.py
..
----------------------------------------------------------------------
Ran 2 tests in 4.873s

OK
python3 -m unittest  -b test/test_backup.py
............
----------------------------------------------------------------------
Ran 12 tests in 1.200s

OK
python3 -m unittest  -b test/test_configfile.py
WARNING: Failed to read process stat from /proc/21073/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/21073/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/21073/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/21073/stat: [2] No such file or directory
```

The check completes properly, but my terminal continues to be spammed with the final lines. These are interspersed with normal output, and even continue after the check has completed. I also get constant pop-up notifications informing me that the backup has not completed because my snapshots folder cannot be found. (It's on a network drive that is not present.)

**Comment by protist** [comment]
Thank you for the very quick fix! This prevents the `WARNING: Failed to read process stat` messages. However, I still get the "can't find snapshots folder" notifications. Is it possible to prevent this, or is it just a necessary part of the tests?

**Comment by Germar** [comment]
It "should" not appear. I"ll have a look,what went wrong. Though there are still some popup messages, that need to be muted. But `can't find snapshots folder` shouldn't be one of them...

**Comment by protist** [comment]
Thanks again. I'm happy to troubleshoot if helpful. Cheers.

**Comment by protist** [comment]
I'm not sure if I was mistaken before, but I tried to `makepkg` again, and this time the warnings reappeared. However, they were only restricted to a few lines, and they had non-unique numbers, unlike before. I'm still getting the popup messages. I backup to an ssh-connected network drive.
```
python3 -m unittest  -b test/test_configfile.py
WARNING: Failed to read process stat from /proc/23591/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/23601/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/23764/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/23771/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/23773/stat: [2] No such file or directory
WARNING: Failed to read process stat from /proc/23777/stat: [2] No such file or directory
```

**Comment by Germar** [comment]
Hmm. Must be a race condition... Sometimes I get those lines and sometimes all is fine

**Comment by aryoda** [comment]
@emtiu Could you please add the `distro-specific` tag? THX!

**Comment by buhtz** [comment]
Dear @protist ,

can you reproduce the problem with the current AUR backintime-git package?

Does anyone has an idea where in `test_configfile.py` this problem occures?

**Comment by protist** [comment]
Wow, this really is back in time! 🤣

Looks like the issue has changed in the last six years. It's not as annoying as before, but something weird is still happening.

```
python3 -m unittest  -b test/test_backup.py
............
----------------------------------------------------------------------
Ran 12 tests in 1.028s

OK
/usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 846269 is still running
/usr/lib/python3.10/subprocess.py:1072: ResourceWarning: subprocess 846423 is still running
python3 -m unittest  -b test/test_config.py
```

I don't get popups now either.

**Comment by buhtz** [comment]
It seems to me that the original issues is fixed.

Your last posted output about "subprocess is still running" is related to #1292 .

Please feel free to re-open the issues and ask questions.
