### ISSUE TITLE
Copying snapshots to new server

### ISSUE THREAD

**Issue by afettouhi** [bit-team/backintime#660]
I have a DroboFS mounted via cifs where all my backintime snapshots. It is time to retire that server and move to my new freenas server that I mounted via smb. According to the FAQ one can via rsync move the snapshot. I wanted to do it as below

rsync -avhH --info=progress2 /media/drobofs/Backup smb://freenas.local/media/

but I get an error saying

ssh: Could not resolve hostname smb: Name or service not known
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]

what am I doing wrong?

**Comment by colinl** [comment]
On 14 November 2016 at 20:13, André Fettouhi <notifications@github.com>
wrote:

> I have a DroboFS mounted via cifs where all my backintime snapshots. It is
> time to retire that server and move to my new freenas server that I mounted
> via smb. According to the FAQ one can via rsync move the snapshot. I wanted
> to do it as below
>
> rsync -avhH --info=progress2 /media/drobofs/Backup
> smb://freenas.local/media/
>
> but I get an error saying
>
> ssh: Could not resolve hostname smb: Name or service not known
>

I think you will need to mount the samba share on your machine, then you
will be able to use rsync to the share. However if you can ssh into it that
would be better, you can certainly rsync to ssh://user@server/path

Colin

**Comment by Germar** [comment]
I agree with Colin. Take a look at our FAQ [How to move snapshots to a new hard-drive?](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive)

Best would be to use rsync directly from one to the other NAS through SSH

**Comment by afettouhi** [comment]
I setup ssh on my freenas box and I am now rsyncing the backup over ssh to the freenas server. Many thanks for the help!
