### ISSUE TITLE
Create hardlinks status

### ISSUE THREAD

**Issue by crisgc** [bit-team/backintime#665]
It would be nice if in the 'create hardlinks' part, the backup status show not only 'create hardlinks', but more useful information like the estimated time of completion or other verbose status.

**Comment by Germar** [comment]
Previous BiT versions used `cp -aRl` to create hard-links which did not provide any progress. Next version 1.2.0 will use `rsync --link-dest` only for creating hard-links and syncing in one step. And so this is included in the rsync progress.
