### ISSUE TITLE
"WITH ERRORS!" what and where?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#666]
Ubuntu 14LTS, backing up /home/username to Folder on USB drive.

Every snapshot is showing the date and "(WITH ERRORS!)" tacked on the end.

I created a new target folder and still get the errors. What are they and how do I find what they are?

No point telling me there are errors with no way of determining what they might be.

Ooops, forgot to add, Logs were empty with "Log All" set.

**Comment by Germar** [comment]
Please select the snapshot with errors and open `Snapshot Log` (5. button). There you can change `Filter` to only show errors.

**Comment by FlailAway** [comment]
Thanks, but...
As mentioned in OP, "Ooops, forgot to add, Logs were empty with "Log All" set."

By, "empty," I mean the only thing in there is "Take snapshot (profile 1): Sunday... " None of the Filters showed anything.

Anyway, I uninstalled and reinstalled and the problem seems to have gone away. But I have other issues I will post a new report here.
