### ISSUE TITLE
[Question] TimeShift like full system backup profile?

### ISSUE THREAD

**Issue by mkkyah** [bit-team/backintime#667]
Hi,
I have configured 1.2.0 alpha12 with Germar's help to backup my Ubuntu 16.04 laptop to my Qnap Nas over ssh. After a few tests and trials to understand, I'm using BiT to backup my Data and Home with a few add/exclude rules. It's working like a charm. Thanks for the really fast and efficient support. 
My new question:
After getting used to BiT and it's configuration I have uninstalled Time Shift from my laptop. I was using it for system backup. It was nice and easy, but there are also downsides like backup path limitation, having a second backup software and backups taking too much space than I expected.
How should I configure BiT(or is it possible) to have a full system only snapshot profile? Will everything covered as in Time Shift? How will a restore process to same and different laptops be?
(I have read somewhere that this full system backup is planned, but couldn't find the thread.)

**Comment by Germar** [comment]
You'd need to use `Back in Time (root)` and include `/`. Default excludes should normally cover all parts that can't be backed up or don't need to be backed up. Downside of this (in case of a disaster) is, you still need to recreate partitions and filesystems and restore from a LiveCD. You could additional create an Image with Clonezilla and restore this first so you only need to restore all changes since the Image was created with BiT.

But IMHO this is a bit overkill. Most of the system are static files, that can be installed again quite fast. My personal system-backup strategy is to only backup `/etc` and `/usr/local` (that's where all my custom scripts live) as root and also backup a list of installed packages. Take a look at our FAQ [How to backup Debian/Ubuntu Package selection?](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection)

The `Full system backup` is a contribution which is not ready yet (#480)

**Comment by mkkyah** [comment]
Dear Germar,
    I have added that 2 system folders and trying to follow the
      tutorial for user-callback.apt-backup.
     I'm running BiT as root
    
     I have created /root/.config/backintime/user-callback
      folder, 
    
    copied user-callback.apt-backup to that folder,
     executed sudo 755 chmod /root/.config/backintime/user-callback
     and run snapshot, but there is no  ~/.apt-backup
          created. Am I copying the file in a wrong
          structure or with wrong name?
        
    
    On 23-11-2016 14:23, Germar Reitze
      wrote:
    
    
      You'd need to use Back in Time (root) and include
        /. Default excludes should normally cover all parts
        that can't be backed up or don't need to be backed up. Downside
        of this (in case of a disaster) is, you still need to recreate
        partitions and filesystems and restore from a LiveCD. You could
        additional create an Image with Clonezilla and restore this
        first so you only need to restore all changes since the Image
        was created with BiT.
      But IMHO this is a bit overkill. Most of the system are static
        files, that can be installed again quite fast. My personal
        system-backup strategy is to only backup /etc and
        /usr/local (that's where all my custom scripts
        live) as root and also backup a list of installed packages. Take
        a look at our FAQ How
          to backup Debian/Ubuntu Package selection?
      The Full system backup is a contribution which is
        not ready yet (#480)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bit-team/backintime","title":"bit-team/backintime","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bit-team/backintime"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Germar in #667: You'd need to use `Back in Time (root)` and include `/`. Default excludes should normally cover all parts that can't be backed up or don't need to be backed up. Downside of this (in case of a disaster) is, you still need to recreate partitions and filesystems and restore from a LiveCD. You could additional create an Image with Clonezilla and restore this first so you only need to restore all changes since the Image was created with BiT.\r\n\r\nBut IMHO this is a bit overkill. Most of the system are static files, that can be installed again quite fast. My personal system-backup strategy is to only backup `/etc` and `/usr/local` (that's where all my custom scripts live) as root and also backup a list of installed packages. Take a look at our FAQ [How to backup Debian/Ubuntu Package selection?](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection)\r\n\r\nThe `Full system backup` is a contribution which is not ready yet (#480)"}],"action":{"name":"View Issue","url":"https://github.com/bit-team/backintime/issues/667#issuecomment-262489056"}}}

**Comment by Germar** [comment]
The script itself must be `/root/.config/backintime/user-callback`. No subfolders!

**Comment by mkkyah** [comment]
Ok,
I have already tried that, too. I have downloaded user-callback-master.zip and extracted, copied user-backup.apt-backup file to /root/.config/backintime folder and renamed as user-callback. Than run `sudo chmod 755 /root/.config/backintime/user-callback`
Still not working.

**Comment by mkkyah** [comment]
solved.
I have cleaned everything and started from scratch for the process. This time I have created the script file with nano (probably not related) and it worked. I have a /root/.apt-backup folder now.

**Comment by Germar** [comment]
👍

Don't forget to include `/root/.apt-backup`, too.

**Comment by mkkyah** [comment]
I did that, thank you.
Regarding to system restore,
Will restoring these backups be enough to a new fresh Ubuntu installation, without permission setups etc?

**Comment by Germar** [comment]
To restore your whole system you need to follow the FAQ [How to restore Debian/Ubuntu Package selection?](https://github.com/bit-team/backintime/wiki/FAQ#how-to-restore-debian-ubuntu-package-selection

I don't understand what you mean with permission setups!?

**Comment by mkkyah** [comment]
I did mean to restore the backup (including the system files, not only data) to a new laptop. Will it be working straight after restore or do we need some tweaking with uid, guid settings.

**Comment by Germar** [comment]
It will work straight as you restore `/etc`, too.
