### ISSUE TITLE
Back In Time relaunches the snapshot at startup

### ISSUE THREAD

**Issue by yguel** [bit-team/backintime#668]
For some reason the last snapshot failed (it ran all night without finishing)
Now each time I start Back In Time, it tries to continue the snapshot.
I am unable to stop it. I killed all the processes, even restarted the computer, but with no luck so far.
I do not manage to find where the program get its orders to relaunch the snapshot.

I am working with Ubuntu 15.10 and Back In Time version 1.0.36

Any help would be welcome.

**Comment by Germar** [comment]
You can disable the schedule with `crontab -e` and delete the backintime command.

Then please run a new snapshot from Terminal with `backintime --backup-job` and post the output.

**Comment by yguel** [comment]
Ok, thanks for the prompt answer.

**Comment by yguel** [comment]
Thanks,
It took a very long time but It worked, here is the output:

Back In Time
Version: 1.0.36

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: on process begins
INFO: Profile_id: 1
INFO: Call rsync to take the snapshot
INFO: Command "rsync -rtDH --checksum --links -pEgo  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/media/manu/Backup_MANU_Ext4" --exclude="/home/manu/.local/share/backintime" --exclude="/tmp/backintime" --include="/media/manu/manuLinux/" --include="/media/manu/" --include="/media/" --exclude=".*" --exclude="*.backup*" --exclude="*~" --exclude="*.o" --exclude="/media/manu/manuLinux/data/3d/kinect" --exclude="/media/manu/manuLinux/lost+found" --exclude="/media/manu/manuLinux/tmp/Downloads" --include="/media/manu/manuLinux/**" --exclude="*" / "/media/manu/Backup_MANU_Ext4/backintime/rebus/manu/1/new_snapshot/backup/" --link-dest="../../20161125-083847-697/backup" -i --out-format="BACKINTIME: %i %n%L" 2>&1" returns 0
INFO: Save config file
INFO: Command "cp /home/manu/.config/backintime/config /media/manu/Backup_MANU_Ext4/backintime/rebus/manu/1/new_snapshot/backup/.." returns 0
INFO: Create info file
INFO: Keep min free disk space: 1024 Mb
INFO: Keep min 2% free inodes
INFO: Unlock

**Comment by Germar** [comment]
The snapshot looks good. Just open and close Settings once in `Back in Time` to re-enable the schedule.
