### ISSUE TITLE
Main Proifle throws error on start up

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#670]
I am not using the "Main Profile," and have created two of my own, (backup-odd and backup-even) for odd and even day numbers, but at start-up the Main Profile always comes up and declares 
_**"Can't find snapshots folder. If it is on a removable drive please plug it and then press OK"**_

Is there some way to have the last used profile come up at start-up and NOT the Main Profile?

Or, better yet, on start-up, automatically open the profiles drop down so I can select a Profile for this backup.

**Comment by Germar** [comment]
You can use `backintime-gnome --profile backup-odd` to open the GUI directly into one profile.

**Comment by buhtz** [comment]
#1371
