### ISSUE TITLE
HowTo do a selective backup (single folder)

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#671]
Hi,
is there a way to snapshot only a specific set of folders or files?

**Comment by Germar** [comment]
Sure, just select that file/folder in `Include`

**Comment by kerner1000** [comment]
But I dont want to change my settings for sheduled back ups. I just want to do a quick, extra backup of some files that have changed and I dont want to trigger a complete backup for that. Is that possible?

**Comment by Germar** [comment]
Nope. A snapshot must always contain the whole set of files. You could add a new profile for your files

**Comment by kerner1000** [comment]
OK, thanks, I will just do a complete snapshot then. Thanks a lot!
