### ISSUE TITLE
Delete some files/ folders from a Snapshot

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#672]
How to delete some files/ folders from a Snapshot?

**Comment by Germar** [comment]
Select that file/folder in main window and open Snapshotsdialog. There you can select all snapshots from which you want to delete that file and press delete. 

You need at least BiT version 1.0.26

**Comment by kerner1000** [comment]
Ah, OK, great, thanks! Maybe it would be good to have the delete option available in the main window as well.

**Comment by emtiu** [comment]
This is now possible by right-clicking on files or folders, or when clicking the "Snapshots" button when a file/folder is selected.
