### ISSUE TITLE
Latest version for 14.04 Trusty ?

### ISSUE THREAD

**Issue by kabalist** [bit-team/backintime#673]
1.  What is the latest stable version I can install on 14.04 Trusty?

2.  Also, which (Gnome or KDE) do I install if I use the Unity Desktop? I read in one place that it is the Gnome and in the other that was questionable...or has the 'backintime-qt' (or 'backintime-qt4') version become the one to install?

3.  Or do I just run:

"sudo apt-get install backintime-qt4"  
If so, will it install the necessary dependencies?

Thanks for your work and HELP!

**Comment by Germar** [comment]
1. latest official version in Ubuntu repositories is `1.0.34`. From our stable PPA you can install `1.1.12`:
    ```
    sudo add-apt-repository ppa:bit-team/stable
    sudo apt-get update
    sudo apt-get install backintime-qt4
    ```

2. The 1.0 release branch provided both Gnome and KDE GUI. So from official Ubuntu repository you'd need to install Gnome (backintime-gnome) for Unity desktop. The 1.1 release branch came with only one GUI written in Qt4 which run on all desktop environs. But `backintime-gnome` still works as it is a virtual package depending on `backintime-qt4`

3. for official Ubuntu version you need to run `sudo apt-get install backintime-gnome`. For PPA version see above

Dependencies will be installed automatically, sure.

**Comment by kabalist** [comment]
Thanks, darn-tootin' that was fast.  Doing it now...

Appreciate the help!  ...as does my media server...

**Comment by kabalist** [comment]
By the way,

Thanks for how fast you answered my question.  AND for the fact that you
followed my questions (which I numbered) and actually matched your answers
to my numbers.  I know that sounds simple but SO MANY PEOPLE CANNOT DO IT!

Thanks again,

Richard
