### ISSUE TITLE
How to restore?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#675]
Sir, this is a GUI application and if you think about it, the people most likely to be looking for a GUI- anything are going to be non-Linux-techy people just changing over to Linux. Me in particular. I have been programming for forty years but have done nothing in Linux.

Up until yesterday, I had a Ubuntu 14.4 installation and used BIT and it very nicely saved stuff. All good. 

Yesterday, I had to reinstall Ubuntu and tried to BIT-Restore but there was no "Snapshot" so the "Restore" button was grayed out. I did some searching and found a posting on "AskUbuntu," I think it was and it had about twenty CLI commands to wade through.  Way out of my league with Linux at this time.

Why can't you have a "Find Snapshot" button or option so I can locate the previous backup? I know where I saved it BUT, I finished up manually copying stuff back. That sucked.

A few days back I also asked here "main Profile throws error..." and you gave me some CLI stuff. I think that's how I screwed up the Ubuntu installation I had to reinstall and start again as I was not sure of exactly what I should be doing at the CLI. 

What's the point in providing a GUI if I have to also learn how to use the CLI to use the GUI? I have no problem making a donation to something that is this useful, but not if I have to sit down and learn CLI stuff to fully use the GUI.

Thanks

**Comment by Germar** [comment]
I already added that config restore feature in `1.1.0`. Current stable version is `1.1.12`. So please use a current version.

**Comment by scytho** [comment]
That may be what I’m looking for, except one thing: I just reinstalled my system and all my BIT profiles are gone. My mistake, as I always used BIT as superuser but didn’t backup any system directories. So I guess the settings where saved somewhere under /root and went to /dev/null when I reformatted the system partition. So: Where is said config that is to be restored, i.e. where does BIT store its settings?

**Comment by Germar** [comment]
Every snapshot contains a backup of the config. Version 1.1.0 and above have a feature `Restore Config` (lower left corner in Settings) which will try to find your old config automatically or you can choose the config manually in there.

**Comment by scytho** [comment]
Great, thanks!

**Comment by buhtz** [comment]
Can be closed? :)

**Comment by scytho** [comment]
For my part yes.
