### ISSUE TITLE
Let users define sets of files to always restore together

### ISSUE THREAD

**Issue by trueshanti** [bit-team/backintime#676]
Hi .. i would like to discuss a wishlist-issue:

i would like to se a function where specific Application-Profiles may be defined to keep restores consistent:

in the example-case KMAIL/akonadi
here several files take part , also a mysql-db in userspace .. so for such a profile a post- and pre-backup sequence should be able to define 

if this feature-set would be possible, community can start definining and contributing other custom-app-profiles, also adapt them over time 

please comment on my suggestion , .. would it make sense for you ?? also where a right place would be to deposit this wishlist (until i i learn coding myself x-b )

**Comment by Germar** [comment]
Not sure, I understood your suggestion. Do you want to backup the whole home but have presets for apps which will automatically restore all files belonging to that app?

This is the right place for it, sure.

**Comment by trueshanti** [comment]
@Germar  .. yes exactly .. this would only apply to the RESTOREs 

20ç on parameters for a EDIT-Mask:

%Profile-Name
%Included-Files
%Included-Folders
%Description
%Prerun-aktivate
%Prerun-Command/Script
%Postrun-aktivate
%Postrun-Command/Script

i would rate that feat AWESOME+2 

c-:

**Comment by buhtz** [comment]
Dear @trueshanti ,
I don't understand your use case. Can you try to explain it a bit in more details please?

**Comment by trueshanti** [comment]
my idea targets the restore-process .. out of all that has been backed up , some application span over multiple files that belong together .. 
e.g.:
an akonadi-backup set consists of ressourcefiles and a mysqlDB-instance

so within a "profile" thosr files could be stacked together as a restore-procedure "profile"  .. further with a prerun i could cleanly dump the db .. during that process

restoring such a set might help people that are not that aware of their software's way-of-doing 

RFC

**Comment by trueshanti** [comment]
# I try to define a usecase:
e.g.:

if implemented, a user would create an "App-profile" within the current BIT-profile by the name of "Akonadi" ..( further such App-profile may be templates committed laterby) . a user select files belonging to this App-profile add or ignore filesandfolders and optionally sets  paths to (bash) scripts  .. one to run before the backup itself starts (%PreBackuprun-Command)  and one for after a restore was triggered (%PostRestorerun-Command)).. a checkbox would care if the profile might be active.
 
UseCase backup: for every active "App-profile" its script "%PreBackuprun-Command" is triggered , then BIT does its job. (e.g. this script might dump a running mysqldb to sql-dumpfile for later restore)

UseCase restore: a user selects such an  "App-profile" via dropdown and selects "restore app/profile" .. then files or folder from the chosen App-profile are restored and a "%PostRestorun-Command" is triggered (eg pipes a sqldump into akonadidb)

i'd think that be nice
br
-c-

**Comment by aryoda** [comment]
THX for your detailed description! I really see the benefits for end users provided by this use case.

I even have similar use case when setting up a new machine with the same apps at home (where I want to re-use my app config files as much as possible).

I am just somehow wondering if this would open Pandora's box on the other hand because there are so many apps, app versions and config files that it seems nearly impossible to keep all this up-to-date, error-free and even give support in case of problems...

**Comment by trueshanti** [comment]
![grafik](https://github.com/bit-team/backintime/assets/567801/afafb80b-a505-4c86-9078-3d92b032bc5e)

another usecase .. stop-backup-start a redis-db

**Comment by buhtz** [comment]
> I am just somehow wondering if this would open Pandora's box on the other hand because there are so many apps, app versions and config files that it seems nearly impossible to keep all this up-to-date, error-free and even give support in case of problems...

This is also my mayor concern and don't see a solution for this.

> THX for your detailed description! I really see the benefits for end users provided by this use case.

I wouldn't trust such a feature and would always check myself if everything I need is in the backup.

I vote to close especially of value-cost-calculation. Maintain such a future is to much for us.

**Comment by trueshanti** [comment]
i'd agree with @buhtz @aryoda  that maintaining such profiles might be an overkill for the codeteam, but implementing the feature would be a massivly greaT feat.  (IMHO).. such profiles i'd rather seen as an external community repo (i would provide my doings as such)

br
