### ISSUE TITLE
"Restore" and "Restore to" opens the same dialogue

### ISSUE THREAD

**Issue by rain0r** [bit-team/backintime#678]
Just noticed that "Restore" and "Restore to" opens the same dialogue.
I was expecting that "Restore to" opens a file chooser where I can select the directory the file/folder should be restored.

Am I mistaken here?

Version: 1.1.12

**Comment by Germar** [comment]
The dialog for choosing a new destination does come AFTER the first dialog (for historical reasons). I know this is confusing and I'm going to change this.

**Comment by Germar** [comment]
Was fixed in 4acb811619cfa3efa17c819daaee0fe394ef9861
