### ISSUE TITLE
Profile prioritizing

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#680]
Hi Germar,

Is it possible to set a priority for each profile we create? I backup my laptops everyday on and off site. The problem is that when the off-site profile gets running, it's slow and it may not complete so the on-site profiles may not executed at all. If I can set a priority, say that always starts with these specific profiles and then run the others, that would be very helpful.

**Comment by Germar** [comment]
There is no prioritzing, sorry. But you can copy the schedule for the off-site profile from `crontab -l`, deactivate the schedule in BiT GUI and add the schedule again in `crontab -e` with a minute delay to the other one. E.g. if your current crontab looks like this:
```
$ crontab -l
#Back In Time system entry, this will be edited by the gui:
0 */2 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/share/backintime/common/backintime backup-job >/dev/null
#Back In Time system entry, this will be edited by the gui:
0 */6 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/share/backintime/common/backintime  --profile-id 2 backup-job >/dev/null
```
You'd copy the last line, deactivate the schedule for the second profile and add this line in `crontab -e`
```
1 */6 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/share/backintime/common/backintime  --profile-id 2 backup-job >/dev/null
```
Notice the `1` at start which will start the profile one minute after the full hour.

BTW I guess, you activated `Run only one snapshot at a time`! Because otherwise different profiles would run at the same time.

**Comment by codesmaker** [comment]
Thanks for the quick and informative reply as usual! Does it work with anacron? I use anacron to backup laptops because as you know, laptops aren't always connected. Here is what it looks like here:
`*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 5 backup-job >/dev/null`

**Comment by Germar** [comment]
Hmm, that's tricky. You could disable `Run only one snapshot at a time` and use a user-callback (event 7) to add a delay for the off-site profile so it will start running after the other profile is done.

**Comment by codesmaker** [comment]
I'm sorry but what's event 7? Could you please elaborate more?

**Comment by Germar** [comment]
user-callback will be started couple times during taking a snapshot. Which status the snapshot currently has will be given by the third argument. You can use this to specify the action you need. But I just realized event 7 would be wrong. Better use 1

```

#!/bin/bash
#    Copyright (c) 2012-2015 Germar Reitze
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#Script should return 0 if everything is alright. Returncode !0 will cancle
#the running snapshot (BIT version >1.1.0).

profile_id="$1"
profile_name="$2"
reason="$3"

case $reason in
    1) #Backup process begins
        #only run this for profile id 5
        if [ "$profile_id" -eq "5" ]; then
            sleep 600
        fi
        ;;
    2) #Backup process ends
        ;;
    3) #A new snapshot was taken
        snapshot_id="$4"
        snapshot_name="$5"
        ;;
    4) #There was an error
        errorcode="$4"
        case $errorcode in
            1) #ERROR The application is not configured
              ;;
            2) #ERROR A 'take snapshot' process is already running
              ;;
            3) #ERROR Can't find snapshots folder (is it on a removable drive ?)
              ;;
            4) #ERROR A snapshot for 'now' already exist
              ;;
        esac
        ;;
    5) #backintime-qt4 (GUI) started
        ;;
    6) #backintime-qt4 (GUI) closed
        ;;
    7) #Mount drives
        ;;
    8) #Unmount the drives
        ;;
esac
```

**Comment by buhtz** [comment]
Can be closed?

**Comment by buhtzz** [comment]
Close.
