### ISSUE TITLE
cannot see older versions of files and newly created files in backup browser

### ISSUE THREAD

**Issue by dnlathrop** [bit-team/backintime#682]
This problem is so basic I must be doing something wrong -- or I don't understand how rsync works. BTW, I am new to Linux.

I created an initial snapshot of my home directory and subdirectories to a USB drive.

I deleted some files, updated others and created new files in my ~/Documents folder.

I took an incremental snapshot to the same USB drive. I selected both the initial snapshot and the second snapshot in BiT and used its browser to look at the files in the snapshots. For both snapshots BiT's browser shows the deleted files and the updated files.

The original version of the updated files are not shown in the first snapshot. The newly created files are not shown in the second snapshot.

I examined the actual snapshots on the USB drive. The new flies are in the second snapshot. The first snapshot appears to have the updated versions of the files, not the original version.

So I cannot use BiT to recover either the original versions of files or the new files. And apparently I cannot manually recover the original version of any updated files. Obviously a huge problem. Am I doing something wrong? or is there a software problem?

The environment:
   backintime 1.1.12
   linux mint 18 (64-bit) cinnamon desktop
   backup drive is USB formatted NTFS

**Comment by Germar** [comment]
I'm not aware of such a problem. Would be huge indeed.

When you said:

> I selected both the initial snapshot and the second snapshot in BiT and used its browser to look at the files in the snapshots

did you mean you selected both at once (multi selection)? Please only select one snapshot. Multi selection is only for removing multiple snapshots at once.

Please select the `~/Documents` folder in your initial snapshot and open the [Snapshots Dialog](http://backintime.readthedocs.io/en/latest/snapshotsdialog.html). There please select the second snapshot and press `Diff`. This will open 'Meld' which will show a side-by-side view of both snapshots where all new/changed files are marked with colors.

**Comment by dnlathrop** [comment]
I selected each snapshot, one at a time, and looked at the files that were shown in each snapshot.

I erased everything and started over. Did some tests. I am relieved and happy to report I can see updated files in newer snapshots and can see older versions of files in older snapshots.

I would like to use the Snapshots Dialog but cannot find where to open it. I followed the link you gave in your post but still can't see where it is. Can you help?

**Comment by Germar** [comment]
It's in the [Files Toolbar](http://backintime.readthedocs.io/en/latest/mainwindow.html#files-toolbar) on [Main Window](http://backintime.readthedocs.io/en/latest/mainwindow.html).

**Comment by dnlathrop** [comment]
That is one of the many things I have tried. When I click on that icon nothing happens. It is the same with Snapshots on the View menu.

**Comment by geo909** [comment]
I have exactly the same problem in arch linux with backintime 1.1.12-4.
In the browser I select a file, right-click, choose 'snapshots'; from there I 
choose different versions (that I know that they have are different than the
selected one) and I press "Diff". Nothing at all happens. When I choose
"diff options", I see "false" in the command field. When I press ok, nothing
happens again.

**Comment by dnlathrop** [comment]
@geo909 I had a different issue. I did not have a file selected and so nothing happened when I clicked snapshot. A message explaining the problem would be nice for new users like me but otherwise my "problem" was not a problem.

**Comment by buhtzz** [comment]
@dnlathrop and @geo909 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing as outdated and impossible to reproduce.
