### ISSUE TITLE
Hangs on restore

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#684]
I do daily Back-in-Time (BiT) ups of some selected Home-Folders I created as well as /opt.

I do a full image backup with Clonezilla (CZ) every three days. The last image CZ failed to complete (no error message) but I didn't find out about it until today when I tried to use it for a Restore. I was having trouble with the Ubuntu 14.4 installation and decided to roll back to the previous CZ image. I ran BiT to be up to date then went to CZ.

Finding out that the last CZ image was faulty, I had to go back to an image of six days back which did restore fine. But, in the period between today and six days back I had installed VMWare and some other stuff (can't remember exactly) that **may** have used /opt and/or created folders in Home. 

After the six-day old Clonezilla restore today, I ran BiT Restore and after it showed "Done" in the main screen, the log file failed to close and the "Close" button remained grayed out and slowly the entire app turned gray, indicating a hang.

I finally had to kill BiT, but, the good news is it appears to have restored everything that I have needed. I am guessing the issue was trying to restore something (Folder etc) that no longer existed in the six-day old image.

**Comment by Germar** [comment]
Did it say `Restore permissions: Done`? (There is no other `Done` in restore...)

If that's the case all restore was already done and it only could have frozen on clean up it's own lock. Which version did you use?

**Comment by FlailAway** [comment]
Using version 1.1.12.a

The log screen stayed open and I do not remember what it had as the final line. The underlying main screen showed "Done" in the bottom left corner. But, by that time it had locked and gone all black and I could not do anything at all with it.

I'll try another backup to save current stuff then try yesterday's restore to see if I can duplicate the issue. But, I am messing with some important data so do not want BiT to lose that. I guess I can do a new CZ image first, but getting messy.

**Comment by FlailAway** [comment]
>> _Did it say Restore permissions: Done? (There is no other Done in restore...)_
Hate to contradict you but there is...
Parts of the main screen are still visible **under the Restore log dialog** and the bottom line has stuff like, "3% something - something..."
When completed the restore log normally shows "Permissions Done" and the "Close" button is no longer grayed and at the same time, the underlying main page then shows "Done" where the "3%..." stuff was.

**Comment by buhtzz** [comment]
@FlailAway There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing, because the reporter isn't responding.
