### ISSUE TITLE
Disable Snapshots Dialog button when no file/folder is selected

### ISSUE THREAD

**Issue by dnlathrop** [bit-team/backintime#685]
I mentioned this in another thread but it may have been overlooked.

Nothing visible happens when I click on the last icon in the toolbar and on Views -> Snapshots.

I am running backintime ver 1.1.12 on Linux Mint 18 (64-bit) cinnamon desktop.

**Comment by Germar** [comment]
Please run `backintime-qt4 --debug` in Terminal, try to open that dialog again and post the output from Terminal.

**Comment by dnlathrop** [comment]
Thanks for the reply.

The debug log is attached. I did not see any items written to the log when I clicked on the snapshots icon.

[backintime.txt](https://github.com/bit-team/backintime/files/670136/backintime.txt)

**Comment by W0nderer** [comment]
As a newbie to Back In Time this caught me out too, I wanted to compare two snapshots and couldn't understand why the Snapshots Dialog panel didn't appear.  I didn't realise it was necessary to first select a file or folder in the Files View as well as the top level folder under Shortcuts.

If I understand correctly the selected file or folder appears at the top of the Snapshots panel, and different versions of it can be compared according to the snapshots selected.  How do I compare different versions of the top level folder (in the Include list)?  I had hoped that selecting it would enable different versions to be compared.  Is it necessary to always take snapshots of the folder containing the one you want to keep track of (e.g. include /home to be able to compare different versions of /home/user-name)?

If clicking on the Snapshots button when no files or folder are selected in the files view always opened the Snapshots Dialog for the currently selected top level folder this would solve both problems.
