### ISSUE TITLE
AttributeError in inhibitSuspend

### ISSUE THREAD

**Issue by daedator** [bit-team/backintime#686]
Hi! 
When trying to create backup, GUI fails to do so with no error messages. CLI gives error in inhibitSuspend as below. I fixed it with commenting out line 990 in "/usr/share/backintime/common/snapshots.py" but now I have no inhibitSuspend function. Hope to see a proper solution.
My system is Centos 7. Installed from tar.

```
[r@m]$ backintime -b
INFO: Run command 'backup' instead of argument '-b' due to backwards compatibili                                                                                           ty.

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
Traceback (most recent call last):
  File "/usr/share/backintime/common/tools.py", line 799, in inhibitSuspend
    bus = dbus.SessionBus()
AttributeError: 'NoneType' object has no attribute 'SessionBus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 567, in aliasParser
    newArgs.func(newArgs)
  File "/usr/share/backintime/common/backintime.py", line 626, in backup
    ret = take_snapshot(cfg, force)
  File "/usr/share/backintime/common/backintime.py", line 70, in take_snapshot
    ret = snapshots.Snapshots( cfg ).take_snapshot( force )
  File "/usr/share/backintime/common/snapshots.py", line 990, in take_snapshot
    self.config.inhibitCookie = tools.inhibitSuspend(toplevel_xid = self.config.                                                                                           xWindowId)
  File "/usr/share/backintime/common/tools.py", line 805, in inhibitSuspend
    except dbus.exceptions.DBusException:
AttributeError: 'NoneType' object has no attribute 'exceptions'
```

**Comment by Germar** [comment]
Please install dependency `python3-dbus`.

Didn't this raise an `ImportError` before? `dbus` should only be `None` if running on travis-ci.

**Comment by daedator** [comment]
I just found  a similar problem description [here] (https://answers.launchpad.net/backintime/+question/269976).  Same as that guy Elio, I have hard time installing python3-dbus on Centos 7 system. I guess I will have to live with inhibitSuspend commented out (unless there is another solution).
Strangely enough, I had BackInTime running on Centos 6 machine couple of years ago with no problems.

**Comment by Germar** [comment]
Please try current master. I fixed the `AttributeError` in aeb432a8f9195b95a7869b8c97b9f8fba082fbe3

**Comment by daedator** [comment]
Hi, Germar,
I tried latest master but I still see same error. The reason may be that I do not have TRAVIS or READTHEDOCS. See output below. Perhaps some other fix may help?
```
[rs@mosk_ ~]$ python3
Python 3.5.1 (default, Dec 23 2015, 10:55:25) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
import os
os.environ.get('TRAVIS', 'None')
'None'
os.environ.get('READTHEDOCS', 'None')
'None'
```
**os.environ.get output:**
_<bound method Mapping.get of environ({'MAIL': '/var/spool/mail/rs', 'DISPLAY': ':1', 'HISTCONTROL': 'ignoredups', 'GPG_AGENT_INFO': '/run/user/1000/keyring/gpg:0:1', 'USER': 'rs', 'LOGNAME': 'rs', 'SHELL': '/bin/bash', 'LANG': 'en_US.UTF-8', 'QTLIB': '/usr/lib64/qt-3.3/lib', 'SSH_CONNECTION': '192.168.1.17 51808 192.168.1.7 22', 'HOME': '/home/rs', 'TERM': 'xterm-256color', 'VTE_VERSION': '3804', 'XDG_MENU_PREFIX': 'gnome-', 'IMSETTINGS_MODULE': 'none', 'IMSETTINGS_INTEGRATE_DESKTOP': 'yes', 'XMODIFIERS': '@im=ibus', 'QT_GRAPHICSSYSTEM_CHECKED': '1', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_TTY': '/dev/pts/3', 'OLDPWD': '/home/rs', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'XDG_SESSION_ID': '31374', '_': '/usr/local/bin/python3', 'LS_COLORS': 'rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:', 'XDG_RUNTIME_DIR': '/run/user/1000', 'M2_HOME': '/opt/maven', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'SSH_CLIENT': '192.168.1.17 51808 22', 'SESSION_MANAGER': 'local/unix:@/tmp/.ICE-unix/18023,unix/unix:/tmp/.ICE-unix/18023', 'XDG_CURRENT_DESKTOP': 'GNOME', 'GTK_IM_MODULE': 'gtk-im-context-simple', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'HISTSIZE': '1000', 'WINDOWID': '29360509', 'GNOME_SHELL_SESSION_MODE': 'classic', 'QTINC': '/usr/lib64/qt-3.3/include', 'VNCDESKTOP': 'mosk:1 (rs)', 'PWD': '/home/rs', 'SSH_AGENT_PID': '18171', 'QTDIR': '/usr/lib64/qt-3.3', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-bopXZBA5xW,guid=92325b14b800369b7d772479589e8703', 'QT_IM_MODULE': 'ibus', 'SHLVL': '3', 'PATH': '/opt/maven/bin:/usr/lib64/qt-3.3/bin:/opt/maven/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/rs/.local/bin:/home/rs/bin', 'HOSTNAME': 'mosk', 'GJS_DEBUG_OUTPUT': 'stderr'})>_

**Comment by Ndolam** [comment]
I don't know whether this will help you or not, but in case other people see this in the future...

I updated Python3 on my system, but sip, dbus-python3 and PyQt-4, which are biolt against python3, did not get rebuilt.  This caused the same message

Traceback (most recent call last):
  File "/usr/share/backintime/common/tools.py", line 799, in inhibitSuspend
    bus = dbus.SessionBus()
AttributeError: 'NoneType' object has no attribute 'SessionBus'

but rebuilding those packages made the error go away.

**Comment by Germar** [comment]
I'm currently downloading CentOS7 and will have a look...

**Comment by Germar** [comment]
Okay, I'm a novice on CentOS but this is how I got it working:
```
sudo yum -y install yum-utils
sudo yum -y groupinstall development
sudo yum -y install https://centos7.iuscommunity.org/ius-release.rpm
sudo yum -y install python34-dbus
```
make sure, `python3` command will start Python3.4

**Comment by daedator** [comment]
Germar,
thank for the advice, I also made it work in Centos7. Please add your comment to the install instructions.

**Comment by Germar** [comment]
Hmm, I would but now I wonder, how to install the other dependencies :see_no_evil: 

Did you install PyQt5 with `pip`? How did you satisfy the requirement for sip>=4.19? There is only 4.16 in CentOS7 repositories

**Comment by daedator** [comment]
I think I did it with pip. Don't remember for sure though.
