### ISSUE TITLE
How to restore just a single Folder?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#687]
I am testing Linux-Mint so named the PC and the account the same name as this Ubuntu 14.4 account that I have been using with BiT for a few weeks.

I started Mint 18.1 and installed BiT from the Software Manager, not sure of the exact version, 1.10, I think. I created an empty folder identical to the Ubuntu one. After the install of BiT it asked for a backup and I pointed at todays and it was all happy -- so far. 

I then exited back to the main BiT GI and selected the todays backup in the left pane, then clicked the Folder I needed in the middle pane and clicked "Restore this Folder/Files."

Then I sat there for 26-minutes while it restored **everything.** Naturally most stuff was useless as some of the programs had not yet been installed on Mint and it all crashed.

The single folder that I actually asked to be restored contained only text files and would have been fine --if-- it had only restored the one folder and it's sub-fodlers. So, I had to kill the Partition, install Mint again then manually copy the single folder from the backup.

Unless I am missing something the restore-folder is not working as I expected.

How do I just restore a single folder without having to do it manually from the BiT backup files?

**Comment by Germar** [comment]
Oh, sorry for that! That's definitely a bug. For now you need to select the folder in the RIGHT pane and click Restore. It does not recognize the selection in middle pane at the moment.

Thanks for reporting.

**Comment by Germar** [comment]
related to #685
