### ISSUE TITLE
Minor typo in Snapshot -> Settings when choosing anacron

### ISSUE THREAD

**Issue by geo909** [bit-team/backintime#689]
Hi, 

Thanks for backintime, great tool, has been very useful to me.

In Snapshot -> Settings, when you choose Repeatedly (anacron) in the Shedule section, I believe that the message should be: [..] is not running regular**ly** (not regular).

Not a native English speaker, so please double-check, but I'm pretty sure.

**Comment by Germar** [comment]
Thanks!

BTW there is a typo in s**c**hedule :joy:  :wink:

**Comment by geo909** [comment]
Haha, touche! :)
