### ISSUE TITLE
[Feature Request] On demand access

### ISSUE THREAD

**Issue by Crackd0wn** [bit-team/backintime#691]
Would it be possible to use BiT(maybe in addition with other linux commands) so that unused files are periodically "deleted" from the original/source location while continuing to exist in the backup folders? A symlink or something else can instead take the place of the deleted original file and can be used to retrieve the latest file again if ever required.

The point, in a situation where the backups are not stored on the same HDD/Device, would be to clear up storage space on the device while still being able to view the full list of files and being able to retreive them(via FTP, etc) at any time.

I think this could be a great use case for BiT. Regardless, thanks for the great work so far.

**Comment by Germar** [comment]
You could use a user-callback script which will do this after each new snapshot (just a quick hack, not tested)
```
profile_id="$1"
profile_name="$2"
reason="$3"
snapshot_id="$4"
snapshot_name="$5"

case $reason in
    3) #A new snapshot was taken
       find /path/to/source -atime +90 -exec rm "{}" \; -exec ln -s "/path/to/backintime/<HOST>/<USER>/<ID>/$snapshot_id/backup/{}" "{}" \;
       ;;
esac
```

**Comment by Germar** [comment]
Oh, you'd need to disable any remove strategy in BiT. Because if a snapshot would be removed the link would be broken.
