### ISSUE TITLE
AppImage for rapid availability

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [bit-team/backintime#692]
ref: [AppImages](https://appimage.org)

This would be useful for rapid restoration of userspace files after an event or to provision a personal $HOME on a new machine. The AppImage could easily be saved on the (local media) backup source. A quick `cp <sourcedir>BackInTime.appimage <destdir>/ && chmod +x <destdir>/BackInTime.appimage && .<destdir>BackInTime.appimage` (assuming backup system does not preserve permissions) puts a user in a position to restore.

I suppose a user could just cp everything over, but BIT makes recovery of encrypted backups easier.

Not so useful for bare metal restores. Frankly, that's what disc cloning or automated provisioning systems, like Ansible and Puppet, are for. Then again, these tools render the need for a bit.appimage moot because, presumably, it would be already installed in the cloned or newly provisioned system.

**Comment by probonopd** [comment]
@ParaplegicRacehorse also worth mentioning that AppImages run great from Live CDs and Live ISOs. For example, I am running an Ubuntu Live ISO right now, and a couple of AppImages.

**Comment by buhtz** [comment]
This is related to #1045 about a FlatPack.

I do [reference my own personal answer in that thread](https://github.com/bit-team/backintime/issues/1045#issuecomment-1330430125).

**Comment by aryoda** [comment]
This is packaging problem not directly related to the development of BiT but how to distribute a ready-to-use installation.

Any help/contribution here (or with flatpack) is greatly appreciated since we as developers and maintainers do always have more work than time ;-)

**Comment by buhtz** [comment]
I'm interested why do you think an AppImage is more rapidly then another release "channel". Can you explain how this improve your workflow and why is it faster in your situation?

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen if you want to add something. Let us know if we can be of assistance to you when creating an AppImage. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
