### ISSUE TITLE
Saving Workspaces?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#693]
I can't seem to get it to save workspaces. It saves then restores a single desktop OK, but not any of the  workspaces with loaded programs. Because of some Cinnamon weirdness, I have to run Lazarus in it's own workspace. It'd be nice to have it restored after a restore.

Is it possible?

Ubuntu 14.4, BiT 1.1.12.a

**Comment by Germar** [comment]
I don't know the concept of this workspaces. But BiT only works on files. So if these workspaces are stored in a file you just need to backup/restore that file and maybe restart the service which provide the workspaces

**Comment by buhtzz** [comment]
@FlailAway There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Close. Seems Distro specific (or Desktop Environment). I assume this is out of scope.

**Comment by emtiu** [comment]
Closing as outdated (and most likely answered).
