### ISSUE TITLE
Named Snapshots?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#695]
Just looking through the auto-remove options and saw, "Don't remove named snapshots."

How does one name a snapshot?

In the main page where the snapshot dates are listed, is it possible to name those?

I am a programmer and make many backups during the day. I'd like to be able to change that list to include a comment...

2017-01-20 09:30:10 _Removed USB_SerIn_

Or some way to identify why I made each backup. I could use something like SVN but it is too cumbersome for the stuff I need to do and BiT is fast to save and fast to restore if/when I screw up. :)

**Comment by DecoDogs** [comment]
BiT 1.0.34, Linux Mint 17.3

There is a pencil icon at the top of the BiT window - clicking opens a window in which you can name a snapshot.  The timestamp will always be prepended to what you type.

![screenshot from 2017-01-21 07 46 32](https://cloud.githubusercontent.com/assets/16939723/22174486/c03d472c-dfad-11e6-8598-3e6b8f1957ef.png)
