### ISSUE TITLE
Using Nextcloud box with BiT?

### ISSUE THREAD

**Issue by aridus** [bit-team/backintime#697]
I am thinking about purchasing a Nextcloud box (https://nextcloud.com/box/) once it becomes compatible with the Raspberry Pi 3. As it runs Ubuntu it should be possible to use BiT with it (although I have not given this any deep thought). Does anybody have any comments on this idea and/or what would be involved?
With thanks!

**Comment by Germar** [comment]
Should work just fine. Just install `rsync` and `opensshd` on it if not done already.

**Comment by aridus** [comment]
Many thanks Germar - this give me the encouragement to go ahead with a purchase - although I am waiting for them to upgrade the device so that it runs with the Pi 3 (it currently only accepts the Pi 2). Once I have the device I'm may have some more questions! 
Martin

**Comment by Germar** [comment]
No worries.

**Comment by colinl** [comment]
The fact that the front page of the website says that Pi3 support will be
available in November last year does not fill me with confidence.
https://nextcloud.com/box/

**Comment by aridus** [comment]
I know, I know, it is of concern and I cannot find any clear indication of when support will be available (hence I am holding off the purchase...).

**Comment by aridus** [comment]
Checking today, I see there is now an update at https://nextcloud.com/box/
'Right now, the OS only works with the Raspberry Pi 2. Software support for Raspberry Pi 3 is planned for April 2017.'  
Hope springs eternal, etc....

**Comment by aridus** [comment]
Following up on this: I heard from Nextcloud today: an image (which one has to write to a microSD card) that supports the Raspberry Pi 3 is now available (https://download.nextcloud.com/server/images/). This dates from March, and apparently a new image is due for release shortly. The box still ships with a microSD card that supports the Pi 2, so one has to download the image and write it to the card.

On the basis of this information I have ordered a Nextcloud box today (and a card reader). When it arrives I will try to figure out how to backup from backintime to it...

**Comment by Germar** [comment]
BTW I recently purchased a Cubietruck for BiT target (and some other task, NextCloud could run easily on it). The Cubietruck comes with a SATA port which make file transfers from/to HDD a lot quicker than on RPis with USB

**Comment by aridus** [comment]
For information, in case anybody else wishes to use BiT on a NextCloud Box (see my post above of 3 days ago): I have been able to write the new image to the microSD (see https://github.com/nextcloud/nextcloud-snap/wiki/Flashing-an-image) and NextCloud is up and running. I have tried to follow https://github.com/nextcloud/nextcloud-snap/wiki/How-to-connect-to-the-Nextcloud-Box-with-SSH to try and set up SSH on the Box, so that I can use it with BiT (I am using the The RPI3 compatible new image: First option: Ubuntu SSO account for out-of-box experience to do this). However, I have become stuck, and have posted a query about this at https://help.nextcloud.com/t/connect-to-the-nextcloud-box-with-ssh-ipv6-error/12457?u=aridus.

**Comment by aridus** [comment]
Follow-up to my post above: I am now able to access the Nextcloud Box via ssh. The next question is how to install rsync (which doesn't seem to be already installed). One cannot use apt, as Ubuntu core accepts only snaps:

**Comment by aridus** [comment]
I am now able to log in to my nextcloud box with ssh,  but I receive the following message when I try to set up a new backintime profile:

Remote host 192.168.1.170 doesn't support 'rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r --rsh="ssh -p 22  -o IdentityFile=/home/martin/.ssh/id_rsa"  --dry-run --chmod=Du+wx /tmp/tmpr492k8vn "user@XXX.XXX.X.XXX:/home/martin-pescador/backintime"

Looking at man backintime, and reading Germar's post above of 26 Jan, is this because rsync needs to be installed on the host (and if so, is this actually possible, as rsync does not seem to be available as a snap: Ubuntu core does not use apt)?

If I ever manage to resolve these problems I will write a How To!

**Comment by Germar** [comment]
Sorry, I can't help on this. I've never used Ubuntu Core/Snappy before. But you should use BiT current dev version 1.2.0 as this does only need rsync on the remote host. Older versions needed more commands (find, chmod ...)

**Comment by aridus** [comment]
Many thanks Germar! I have tried 1.2.0 but the problem persists. rsync does not appear to be installed on nextcloud and there is not yet a snap for it. I will probably need to wait, therefore.

**Comment by Germar** [comment]
Sure, rsync is still necessary. Maybe[ this could help](https://askubuntu.com/a/681990/37580)
