### ISSUE TITLE
Q: What's the recommended file system for a backup drive?

### ISSUE THREAD

**Issue by mxa** [bit-team/backintime#698]
I had a backup drive that I also used to exchange data between a windows and a linux computer. It was NTFS and I had issues with it. I am reformatting and thinking I could go with a UDF File system. Would that work ok with Back In Time?

**Comment by Germar** [comment]
It 'should' work as it supports hard-links. But I have no experience with it. I'd recommend using a ext3 (or ext4) partition for backups and a separate NTFS partition to exchange data

**Comment by mxa** [comment]
OK, Thank you for your advice. I've read many recommendations for UDF over NTFS for an exchange volume, so I'll try that. I have another backup, and will test if UDF will work as a backup as well.
BTW: One issue with NTFS was, that Back In Time had stored very deep directories and I was not any more able to access or even delete those files on the NTFS.
