### ISSUE TITLE
Config File Issue

### ISSUE THREAD

**Issue by victorstewart** [bit-team/backintime#700]
Hey,

I'm creating this config file at : /etc/backintime/config

> profile1.snapshots.automatic_backup_mode=19
> profile1.snapshots.custom_backup_time=3
> profile1.snapshots.path.auto=true
> profile1.snapshots.path.host=$HOSTNAME
> profile1.snapshots.path.profile=1
> profile1.snapshots.path.user=root
> profiles.version=1

then I do : `backintime --config /etc`

but when I try...
`backintime backup --config /etc`

I get...

> Back In Time
> Version: 1.1.12
> 
> Back In Time comes with ABSOLUTELY NO WARRANTY.
> This is free software, and you are welcome to redistribute it
> under certain conditions; type `backintime --license' for details.
> 
> ERROR: Back In Time is not configured!

What am I doing wrong?

thanks!

**Comment by Germar** [comment]
`--config` takes the full path to the config file. You need to use `backintime backup --config /etc/backintime/config`

**Comment by victorstewart** [comment]
I just tried that `backintime backup --config /etc/backintime/config`, and still got the same response.

any other ideas?

**Comment by Germar** [comment]
Oh, sorry I didn't notice. You need to add at least the path for the snapshots and one include:
```
profile1.snapshots.include.size=1
profile1.snapshots.include.1.type=0
profile1.snapshots.include.1.value=/home/victorstewart/Documents
profile1.snapshots.path=/tmp
```

BTW BiT does not parse env vars in config. But if you remove the whole line `profile1.snapshots.path.host=$HOSTNAME`, it will automatically use the current hostname

**Comment by victorstewart** [comment]
thanks!!

**Comment by victorstewart** [comment]
would "profile1.snapshots.include.1.value=/" just do the entire filesystem?

**Comment by victorstewart** [comment]
and sorry, how do I set up the crontab daemon so that it will back up every 3 hours?

**Comment by victorstewart** [comment]
figured it out, thanks!!

**Comment by Germar** [comment]
Yes, `profile1.snapshots.include.1.value=/` would backup the whole system.

Please use `backintime check-config`. This will create the cronjobs you defined in config, too.
