### ISSUE TITLE
Cannot install from Ubuntu PPA

### ISSUE THREAD

**Issue by lsitongia** [bit-team/backintime#701]
Is this not supported for 16.1? I'm getting messages:
$ sudo apt-get update
...
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/bit-team/stable/ubuntu yakkety Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/bit-team/stable/ubuntu/dists/yakkety/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by colinl** [comment]
On 2 February 2017 at 18:23, Leonard Sitongia <notifications@github.com>
wrote:

> Is this not supported for 16.1? I'm getting messages:
> $ sudo apt-get update
> ...
> Reading package lists... Done
> W: The repository 'http://ppa.launchpad.net/bit-team/stable/ubuntu
> yakkety Release' does not have a Release file.
> N: Data from such a repository can't be authenticated and is therefore
> potentially dangerous to use.
> N: See apt-secure(8) manpage for repository creation and user
> configuration details.
> E: Failed to fetch http://ppa.launchpad.net/bit-team/stable/ubuntu/dists/
> yakkety/main/binary-amd64/Packages 404 Not Found
> E: Some index files failed to download. They have been ignored, or old
> ones used instead.
>

If you go to https://launchpad.net/~bit-team/+archive/ubuntu/stable you can
see that the ppa does not support yakkety. However since yakkety has 1.1.12
in the standard repository this may not matter at the moment.

Colin

**Comment by Germar** [comment]
Oh, sorry. I forgot to push a package for Yakkety. Should be up and running in half an hour.

@colinl Ubuntu repository has 1.1.12 but PPA has a patched 1.1.12a...

**Comment by colinl** [comment]
Excellent, thanks Germar, I can re-enable the ppa again.

Cheers

Colin
