### ISSUE TITLE
intelligent-remove should try to keep backups without errors

### ISSUE THREAD

**Issue by MK-42** [bit-team/backintime#703]
I'm on 1.1.12, maybe that is already fixed in master?

I had several snapshots of last week, the last one of them was/is marked with "Has Errors". Then intelligent-remove deleted the other snapshots of that week, keeping the one with errors.

From my point of view it would make more sense to keep a backup that completed without errors, if there is one in the timespan that is looked at. So I would have prefered to keep the second-last from last week, as that completed without errors. One could argue if it should maybe always preserve the last one and if that had errors, keep an additional one without errors or something like this. But as the setting says 'keep one per week for x weeks", I think its absolutely ok to not keep the last, but the last without errors, if there is one without.

**Comment by Germar** [comment]
Good point :+1:

**Comment by Germar** [comment]
fixed by 33e913aa355de1b18e603ac6cb842936e85bc458
