### ISSUE TITLE
Incorrect instructions for Ubuntu PPA?

### ISSUE THREAD

**Issue by collectorgeneral** [bit-team/backintime#704]
On the front page, after adding the PPA && sudo apt update; the next step is to:
`sudo apt-get install backintime-qt`
This results in an error (E: Unable to locate package backintime-qt). Looking around the Internet, I found the actual command is:
`sudo apt-get install backintime-qt4`
Which works completely fine. So I think this can be edited on the front page? On a side note, this suggests to me that Qt4 is being used, which is a bit odd though. I thought Qt5 was used?

**Comment by Germar** [comment]
Sorry, that's already for the next version. Changed it back...

**Comment by Germar** [comment]
BTW next version 1.2.0 will use Qt5. The current stable is still on Qt4

**Comment by collectorgeneral** [comment]
Thanks!
