### ISSUE TITLE
How to Open an existing Backup?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#705]
Hi, I have two main BiT-profiles that I use several times daily. Yesterday I created another Profile named "Programming" and added all the source folders as I sometimes I need to roll back just the programming source a few hours. The Programming stuff is always included in the main BiT backups, but it often takes several minutes to restore so decide to make a smaller one. 

This morning I had to roll back to a Clonezilla image of a few days back and wanted BiT to restore just the Programming but the Snapshot was not available and I can't find a way to open the BiT backup.

How can I open that "Programming" backup that did not exist when I made the Clonezilla image?

**Comment by Germar** [comment]
You need to restore the new config first. In `Settings` press the `Restore Config` Button at the bottom left corner. Navigate to the last snapshot from the 'Programming' profile and restore it.

**Comment by FlailAway** [comment]
Ahhh, OK, I thought the "Restore Config" button just restored the other options in Settings all back to the "Factory" settings. Did not realize it meant **my** config. Thanks
