### ISSUE TITLE
Unpleasant surprise - bug maybe?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#706]
Yesterday I created a new BiT profile, "Programing" and then assigned the Target Location and added all the files I need to back up, plus setting the other things I needed in Settings.

I was about to go back to the BiT main screen and noticed I had misspelled "Programing" so clicked "Edit", added in the missing "p" and clicked OK. 
BOOM!
Everything I had previously entered for the backup was gone. It seemed to regard the "Edit" as a request for a New profile instead of correcting the name change. A touch brutal. :)

**Comment by Germar** [comment]
Ups. Sorry about that. Will fix it soon.
