### ISSUE TITLE
No status bar informations while manually deleting snapshots

### ISSUE THREAD

**Issue by Mintulix** [bit-team/backintime#707]
Hi Germar,

I don't know if it's intended or a little bug:
Choose one or more snapshots, start remove -> status bar shows "Fertig" (ready/done) the whole time. Deletion works as expected, so no big deal.
Versions tested: The official 1.1.12 and the latest 1.2.0-alpha14.
Experimental deletion is OFF.

I use backintime with Linux Mint and a Synology NAS. I had a hard time to get SSH to work (after using bit with local mounts for two years), but after choosing the right NAS-directories and the correct access rights it's a speed dream. You should really point it out how much faster SSH is, so more people would use it.

Thanks a lot for developing and maintaining it!

**Comment by Germar** [comment]
The status bar currently only shows status from running snapshots. It is a relict from old times which also doesn't work very well. I want to replace it, but first I need to implement a proper interprocess communication between snapshots, GUI, systray, ...

related to #84

**Comment by emtiu** [comment]
Closing in favor of #1264.
