### ISSUE TITLE
Where are the profiles set up with the GUI saved?

### ISSUE THREAD

**Issue by fromagek** [bit-team/backintime#712]
I would like to lunch the backup via a bash script but use the GUI to configure everything.
I found that I can lunch a snapshot backup via 
`backintime -profile PROFILE\ NAME –backup`
But where do I find the PROFILE that I have to hand over?
Best florian

EDIT:
By try and error I found that you only have to hand ofer the profile name. Everything works fine. Thanks for this nice peace of code!

**Comment by Germar** [comment]
This is the name you entered for the profile in Settings. The first profile is always `Main Profile`. But I'd strongly recommend to use `backintime --profile-id 2 --backup` for this as the profile-id won't change but the name could change...

**Comment by fromagek** [comment]
Ok changed that in my script. Thanks for the hint.
