### ISSUE TITLE
Upgrade stable to testing: Profile is gone and Expert option is not there

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#713]
Hello Germar,

I tried to upgrade BIT from stable to testing on my Ubuntu 14.04 system by adding the ppa.
BIT is upgraded (1.2.0~alpha15) but now my profile is gone. How should I do the upgrade to preserve the profile?
What can I do now? I would either like to go back to the stable branch or somehow revive the old profile in the 1.2 branch.

Also, I mainly did the upgrade because I wanted to get the option "Check if remote host is online in Expert Options" see #655. However, in 1.2 and looking in the advanced options tab, the rightmost tab, this option does not seem to be there. 

As an alternative, would you consider backporting the option to turn off "Check remote host online" to the stable branch?

Thanks for any help on this.

**Comment by ersv** [comment]
I realised that I used to run the stable branch with as a user while I started the testing branch as the root user. That is probably why the profile did not show up. However, when trying to start the testing branch as the user, nothing happens. When trying from the terminal, I get a message: "Segmentation fault (core dumped)"
Any ideas?

**Comment by Germar** [comment]
`Check if remote host is online` is only available if you choose `SSH` or `SSH encrypted` mode in General tab.

Please run `backintime-qt --debug` from Terminal and post the output.

**Comment by ersv** [comment]
Hello Germar,

I just cloned the master off github with the latest commit commit 87e7a6fb548aa91c3ac0be2fd59cd0e4bbd8a2b4

Then I did a 

./makedeb.sh
sudo dpkg -i ./backintime-common_1.2.0~alpha0_all.deb
sudo dpkg -i ./backintime-qt_1.2.0~alpha0_all.deb

Then I ran $ backintime-qt --debug

With the following output:

DEBUG: [common/backintime.py:669 getConfig] config file: /home/user/.config/backintime/config
DEBUG: [common/backintime.py:670 getConfig] share path: /home/user/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Huvudprofil
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
Segmentation fault (core dumped)

I am not sure how to interpret the output. Something wrong when adding qt4plugin?
However, I installed backintime-qt, should use qt5, yes?  
Any ideas?

**Comment by Germar** [comment]
Hmm. Just did the same on a 14.04 machine and wasn't able to reproduce it. Could you please open a Terminal and run

```
cd /usr/share/backintime/plugins/
python3 -c "import sys; sys.path.insert(0, '../common'); import qt4plugin; plugin = qt4plugin.QtPlugin(); print(plugin.init('foo')); print(plugin.isGui())"
```

This should print `True` two times.

qt**4**plugin is only an old filename I forgot to change

**Comment by ersv** [comment]
Ok, to be safe, I did a complete uninstall and then reinstalled BIT according to above. 
Then I did as you suggested, `cd /usr/share/backintime/plugins/`
and `python3 -c "import sys; sys.path.insert ...`
I get the message:
`True`
`True`
If I try to run BIT as user, I get the exact same debug message as above.
If I try to run BIT as root, it starts and I get the following truncated debug message:
DEBUG: [common/backintime.py:584 argParse] Arguments: {'debug': True} | unknownArgs: []
WARNING: [common/backintime.py:512 startApp] It looks like you're using 'sudo' to start Back In Time. This will cause some troubles. Please use either 'sudo -i backintime-qt' or 'pkexec backintime-qt'.

Back In Time
Version: 1.2.0~alpha0

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:669 getConfig] config file: /home/user/.config/backintime/config
DEBUG: [common/backintime.py:670 getConfig] share path: /home/user/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Huvudprofil
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/tools.py:795 keyringSupported] No keyring due to import errror.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:82 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/sshtools.py:224 SSH.startSshAgent] ssh-agent started successful: SSH_AUTH_SOCK=/tmp/ssh-BOWjSxToDiBp/agent.4018 | SSH_AGENT_PID=4019
DEBUG: [common/sshtools.py:267 SSH.unlockSshAgent] Add private key /home/user/.ssh/id_rsa to ssh agent
DEBUG: [common/sshtools.py:272 SSH.unlockSshAgent] Password available: True
DEBUG: [common/mount.py:678 SSH.mountProcessLockAcquire] Acquire mountprocess lock /home/user/.local/share/backintime/mnt/4007.lock
DEBUG: [common/sshtools.py:494 SSH.checkPingHost] Check ping host
DEBUG: [common/sshtools.py:503 SSH.checkPingHost] Host host is available
DEBUG: [common/mount.py:574 SSH.checkFuse] Check fuse
DEBUG: [common/sshtools.py:328 SSH.checkLogin] Check login
DEBUG: [common/sshtools.py:440 SSH.checkRemoteFolder] Check remote folder
DEBUG: [common/sshtools.py:457 SSH.checkRemoteFolder] Call command: ssh -o ServerAliveInterval=240 -o 
/removed some data/
DEBUG: [common/sshtools.py:463 SSH.checkRemoteFolder] Command returncode: 20
DEBUG: [common/sshtools.py:155 SSH._mount] Call mount command: sshfs -o ServerAliveInterval=240 -o 
/removed some data/
DEBUG: [common/mount.py:705 SSH.mountLockAquire] Set mount lock 
...

Any ideas? I really would like to use the 1.2 series in order to be able to use a bastion host.
Thanks for any help.

**Comment by Germar** [comment]
Please run `dpkg --get-selections` and send me the output. I guess there is a conflict in installed packages on your system. I'll try build a VM with exact the same packages as yours

**Comment by ersv** [comment]
Ok, thanks. I just sent you an email with the information. I run ubuntu 14.04 LTS, 64-bit.

**Comment by Germar** [comment]
I was able to reproduce it with your packages installed. Will troubleshoot it the next days.

**Comment by ersv** [comment]
Ok, thanks. If there is anything I can do, I would be glad to assist you in bug tracking.

**Comment by ersv** [comment]
Hello Germar, any progress on this matter?

**Comment by Germar** [comment]
Sorry, I didn't find time to go deeper into this. Quite busy the last weeks...

**Comment by Germar** [comment]
Okay, it took me couple hours to pin this down to both packages `python3-pykde4` and `python3-pyqt4`.
Please remove both...

**Comment by ersv** [comment]
YES, it is working! Thank you Germar!
Nice I will now cut my teeth into a bastion host configuration of BIT.

Btw,  where those packages remnant of my old BIT installation? Anything I could have done differently?

**Comment by Germar** [comment]
`python3-pyqt4` was a dependency of previous BiT version. But it should have been deinstalled as soon as you run `apt-get autoremove` after upgrade.

`python3-pykde4` has never been a dependency of BiT. No clue where it came from...
