### ISSUE TITLE
Invalid interface to SNW_SERVICE

### ISSUE THREAD

**Issue by garymeer** [bit-team/backintime#715]
I am getting e-mails from BackupInTime as follows:

"sni-qt/8443" WARN  06:40:03.769 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE
WARNING: Command "rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/backup" --exclude="/home/gary/.local/share/backintime" --exclude=".local/share/backintime/mnt" --include="/home/gary/" --include="/home/" --include="/usr/local/" --include="/usr/" --exclude=".gvfs" --exclude=".cache/*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/etc/mtab" --exclude="/var/cache/apt/archives/*.deb" --exclude="lost+found/*" --exclude="/tmp/*" --exclude="/var/tmp/*" --exclude="/var/backups/*" --exclude=".Private" --include="/home/gary/**" --include="/usr/local/**" --exclude="*" / "/backup/backintime/system1/gary/1/new_snapshot/backup/" 2>&1" returns 5888

Can these be fixed or eliminated? Do I need to change something on my system?

I am running Fedora 25, 64bit.

**Comment by Germar** [comment]
rsync returned 23 (5888/256) which means `Partial transfer due to error`. Most probably this was caused by changing a file after rsync scanned it and before rsync was able to transfer it. Take a look at the snapshot log. There should be an error message.
