### ISSUE TITLE
remove a single file or directory from all backup

### ISSUE THREAD

**Issue by jpaulbiss** [bit-team/backintime#716]
I have been using Backintime for a couple of years. Is it possible to remove a file or directory from the backups? I have a couple of Dir in my /home that really do not need to be backed up like VirtualBox and dvdrip-data.

Thanks

Paul

**Comment by DecoDogs** [comment]
Do you mean exclude them from the backups?  If so, then list the files/directories in the 'exclude' tab for the backup job in question.

If you mean delete them from existing backups, I have done that with 'find', though that may not be The Most Accepted Method in the BiT universe :)


Ed

**Comment by Germar** [comment]
@DecoDogs there is nothing wrong with `find` but there is a much easier way in BiT :wink: 

@jpaulbiss please select the file/folder you want to delete in Back in Time main window and press the [Snapshots button](http://backintime.readthedocs.io/en/latest/mainwindow.html#files-toolbar). Select all snapshots and press `Delete`. After confirming and deleting it will ask you if you wish to exclude it from future snapshots, too.

**Comment by jpaulbiss** [comment]
That works thanks
