### ISSUE TITLE
Lost backups

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#718]
I appear to be losing backups. I have two identical BiT profiles. I have two identical flash-drives, one in a USB-Dock and on in laptop and I always backup both profiles so they are only about a minute apart. 

This has been working fine for many weeks, but a few days back one of them suddenly lost a bunch of backups. 

Flash drive 1: Good = 238,456 items, totalling 1.7 GB
Flash drive 2: Bad = 76,604 items, totalling 1.2 GB

![bit-good](https://cloud.githubusercontent.com/assets/14017982/23873566/b8a2cb80-07ef-11e7-8955-b91bbd1649af.jpg)

![bit-bad](https://cloud.githubusercontent.com/assets/14017982/23873557/ad668518-07ef-11e7-8cee-5e92fd3305df.jpg)

**Comment by Germar** [comment]
How much free space did you had? By default BiT delete the oldest snapshots until there is at least 1GiB free space.

Please run `zgrep "backintime" /var/log/syslog*` in Terminal and post the output.

**Comment by FlailAway** [comment]
Thanks, they are 64GB flash drives with 23GB free.
Logs only go back to yesterday
euly@Acer14:~$ zgrep "backintime" /var/log/syslog*
/var/log/syslog:Mar 14 06:13:57 Acer14 dbus[487]: [system] Activating service name='net.launchpad.backintime.serviceHelper' (using servicehelper)
/var/log/syslog:Mar 14 06:13:57 Acer14 dbus[487]: [system] Successfully activated service 'net.launchpad.backintime.serviceHelper'
/var/log/syslog:Mar 14 06:14:00 Acer14 backintime (euly/1): INFO: Lock

**Comment by Germar** [comment]
By any chance, did you backup `/var/log`? Could you restore the old logs?

By default BiT only removes snapshots which are older than 10 years, if there is less than 1GiB free space or if there are less than 2% free inodes. You can check free inodes with `df -i`

**Comment by Germar** [comment]
[Could this](https://github.com/bit-team/backintime/issues/733#issuecomment-291279348) have been the same problem on your side?

**Comment by buhtz** [comment]
#733

**Comment by buhtzz** [comment]
@FlailAway There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing as outdated.
