### ISSUE TITLE
Attribute error in qttools.py (backintime-qt)

### ISSUE THREAD

**Issue by Russtopia** [bit-team/backintime#719]
Platform: Gentoo Linux (4.4.21 x64)
Python 3.4.5
backintime 1.1.12

After initial struggles emerging PyQt5 with Qt5.QtGui support, I now have this issue which I'm unsure how to resolve:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 35, in <module>
    import qttools
  File "/usr/share/backintime/qt/qttools.py", line 187, in <module>
    class TimeLine(QTreeWidget):
  File "/usr/share/backintime/qt/qttools.py", line 247, in TimeLine
    @pyqtSlot(snapshots.SID)
AttributeError: 'module' object has no attribute 'SID'

```

**Comment by Germar** [comment]
Hmm. Version 1.1.12 didn't use PyQt5. It was on Qt4. Also the traceback you provided is from 1.2.0. I guess, you mixed up backintime-common from 1.1.12 and backintime-qt from 1.2.0 which won't work. Please install both from the same source.

**Comment by Russtopia** [comment]
Oh, hah! My apologies for a false alarm then. I didn't realize.. I should have parsed the project repo history more before submitting. Also didn't see my -common and -qt installs were mismatched.

Thanks for responding and sorry to waste your time. Will close this.

**Comment by Germar** [comment]
No worries
