### ISSUE TITLE
Back In Time gui hangs when creating a snapshot or restoring or anything else..

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#72]
It seems the backup or restore wouldn't happen in seperate processes but everything in one process. This makes the gui of course hang and being unresponsive when doing a backup or restoring. Please read "man fork" and apply good coding practice to this nice software....

---

Imported from Launchpad using lp2gh.
- date created: 2010-02-24T13:02:31Z
- owner: r0rschach
- the launchpad url was https://bugs.launchpad.net/bugs/527038

**Comment by Germar** [comment]
(by danleweb)
1. Backup process is always running in another process. If it is started from cron if can run nice and/or ionice. If is stated from the GUI is running as a normal process. (there can't be 2 backup process at the same time; if one is already running

2. Restore process is always running in the GUI and this is the way I wanted to be (I don't want to restore at the same time, at least not for now). I agree that a message box showing "Please wait. Restoring in running ...".

**Comment by Germar** [comment]
(by kiddo)
In case it may be of use:

http://faq.pygtk.org/index.py?req=show&file=faq20.006.htp
http://faq.pygtk.org/index.py?req=show&file=faq10.017.htp 

There's quite a few other entries in the pygtk FAQ (http://faq.pygtk.org), I just happened to stumble upon these and thought I'd share them.

**Comment by Germar** [comment]
(by danleweb)
Thanks for your tips. I was looking to thinks like this.
As for this bug: backup process is not blocking the GUI (a separate process) and restore process it does but it has to (at least for now).

Regards,
Dan

**Comment by Germar** [comment]
(by jdnier)
I'd just like to add that I find the lack of any indicator or feedback when restoring to be confusing. The status bar on the bottom left seems to be a natural place to say "Restoring..." or something more specific. Right now, when restoring individual files or directories, the status bar continues to show "Done" even as the GUI locks up waiting for the restore to complete; depending on how much you're restoring, this can last for minutes. I've taken to having htop running in a background terminal so I can get some sense of when individual restore actions (rsync commands) have finally completed.

**Comment by Germar** [comment]
(by tpo-deb)
For backintime-kde4 this is resolved with the patch mentioned here:

https://answers.launchpad.net/backintime/+question/213871

Hasn't maybe the bug been fixed in the meantime in the gtk GUI as well?

What seems to have been fixed in the KDE GUI as well is the button saying "Done" while the restore is being done.

**Comment by Germar** [comment]
(by drdlund)
I'm also having problems with backintime hanging my entire system in the middle of a foreground backup. Running in an Ubuntu virtual machine. Only way I can regain access to the system is to do an ACPI shutdown.

I am going to try a background backup and see if it finishes. Will report back.

**Comment by buhtz** [comment]
Is this still relevant? Maybe this is related to the planed/wished RPC-redesign you mentioned in another Issue?

**Comment by nodiscc** [comment]
The backintime window (backintime-qt4 1.1.12-2 in Debian) hangs when the user clicks on the "View last snapshot log" button in the toolbar (maybe other buttons, untested) during a snapshot creation operation.

Is this normal/expected? If so maybe these buttons should be disabled/grayed out during snapshot.

The qt4 systray icon/progress indicator still works fine so at least I have an indication of the file currently being backed up (but no progress percentage).

Should I open another issue for this?

Thanks

**Comment by Germar** [comment]
@buhtz you're right, this is done. Restore does show a log while restoring and backup is in background without blocking

@nodiscc please open an other issue. Please run `backintime-qt4 --debug` start a new snapshot, click on `View last log` and post the output
