### ISSUE TITLE
No such device or address: '/dev/stdout'

### ISSUE THREAD

**Issue by aexoxea** [bit-team/backintime#720]
After updating to v1.1.14, running "**backintime --profile-id [id] backup-job**" through a systemd service unit (in either system or user session scopes) produces the following:
```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 865, in <module>
    start_app()
  File "/usr/share/backintime/common/backintime.py", line 450, in start_app
    args.func(args)
  File "/usr/share/backintime/common/backintime.py", line 634, in backupJob
    cli.BackupJobDaemon(backup, args).start()
  File "/usr/share/backintime/common/tools.py", line 1365, in start
    self.daemonize()
  File "/usr/share/backintime/common/tools.py", line 1333, in daemonize
    so = open(self.stdout, 'w')
OSError: [Errno 6] No such device or address: '/dev/stdout'
```

The same command can be run successfully from a terminal, and backups can also be done through the GUI without trouble; it's only when triggered as a service unit. The configuration of the units in question is the same as in #669.

Enabling or disabling the 'Redirect' options under 'Expert options' in the GUI has no effect.

For now, I've downgraded to v1.1.12, so this is mainly aimed at trying to fix this in a future release. Knowing that my setup is a little unusual, I'm happy to help in whatever ways I can to track this down.

**Platform:** Arch Linux (4.9.14.r201703121245-1-grsec) with python 3.6.0 and systemd 232.

**Comment by Germar** [comment]
The `Redirect` options only take place on automatic created crontab jobs (using predefined schedules in `Generals` tab). They will add `>/dev/null 2>&1` to the command and that's also what I'd recommend in your case.

It looks like systemd doesn't provide stdout and/or stderr. So as long as this bug isn't fixed you should provide it manually in the systemd command with `>/dev/null 2>&1`.

**Comment by aexoxea** [comment]
Thank you @Germar for both the fix and the workaround!

I have also re-upgraded to v1.1.14 and applied your workaround through adding the parameter `StandardOutput=null` to the systemd service files (this cascades, as `StandardError=inherit` is the default). Happily, the services now run properly again 😄.
