### ISSUE TITLE
"snapshots.rsync_options.value" is not set in "config"

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#721]
The profile-specific option `snapshots.rsync_options.value` is not set in `config`. Not only the value. The complete variable is missing there. `snapshots.rsync_options.enabled` is set and used (in the dialog) correct.

For me it looks like that the *settingsdialog* code use the correct read/write calls on the config file.

I can not see why this happens. But this depends on my low understanding of the config code. Sorry.
Using the current git-version of **bit**.

**Comment by Germar** [comment]
It does work here. Can you please send me your config?

**Comment by buhtz** [comment]
See #657.
It is still fixed. Missused my git.
