### ISSUE TITLE
BIT doesn't backup automatically anymore after the latest update

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#722]
Hi Germar,

I've updated BIT to v1.1.14. After the update, the "repeatedly anacron" schedule stopped working. The computers which are still using v1.1.12.a works fine. Any idea?

**Comment by Germar** [comment]
I was able to reproduce this but didn't found the reason yet. Looks like I made the last release a bit overhasty, sorry.

**Comment by codesmaker** [comment]
It's OK:). Only two PCs were affected and I've disabled the automatic updates of BIT on the other PCs. I would like you to know that BIT is a beautiful piece of software and we depend on it for our laptops' backup. I also would like to take the opportunity to thank you for your hard work, commitment, and great support! Any idea how long will it take to debug?

**Comment by Germar** [comment]
Fixed in new release 1.1.16
Sorry for the troubles

**Comment by codesmaker** [comment]
Thanks Germar. It works.
