### ISSUE TITLE
After upgrade from 1.1.14 to 1.1.16 manual snapshot button doesn't work

### ISSUE THREAD

**Issue by jbernal-ej2sistemas** [bit-team/backintime#728]
I upgraded BIT via apt upgrade today to 1.1.16 from version 1.1.14. I'm suffering the issue/bug #722. 
Now, the manual snapshot button doesn't work, seems to do nothing.

I tried uninstall BIT and make a fresh install, but same problem.

My system: Ubuntu Desktop 16.04.2 with 4.8.0 kernel.

Thanks.

**Comment by joaoherberto** [comment]
Same issue on Manjaro XFCE 64bit...

**Comment by pagnotta** [comment]
When starting backintime from the command line I get the following output on clicking the snapshot button:

```
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 873, in on_btn_take_snapshot_clicked
    backintime.take_snapshot_now_async( self.config )
  File "/usr/share/backintime/common/backintime.py", line 69, in take_snapshot_now_async
    subprocess.Popen(cmd, env = env)
  File "/usr/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: 'backintime backup &'
```

**Comment by corro** [comment]
The fix is rather easy, just add `shell=True` to the Popen() call. See pull request #729.

**Comment by Germar** [comment]
Ahhh :see_no_evil: Never touch a running system!

I'm so sorry for the troubles. I'm currently quite short on time and didn't it test like I should have. Sorry
