### ISSUE TITLE
Package does not open

### ISSUE THREAD

**Issue by superlativo77** [bit-team/backintime#731]
First of all thanks for the excellent work with Back In Time. I think it is the best backup program and I have used it for a long time. This is the first time I have a problem.

I have several copies created in Manjaro Gnome but a few days ago I can not open the package. I have tried uninstalling completely with the command: pacman -Rsc backintime

Then I reinstalled it but the problem continued. As root, the same thing happens. I also tried to run it in the Terminal to see if it gave error. The GUI also does not open but it does not report any errors.

I have recorded a video for you to see the problem (sorry for the glitches but it's a remote session):
https://youtu.be/dFwyngd5Tm4

It does not seem to be Back In Time problem but can anyone help me with this problem?

Thanks in advance.

**Comment by Germar** [comment]
To start GUI from Terminal please run `backintime-qt --debug` and post the output

**Comment by superlativo77** [comment]
Hi Germar,

Thanks for your support.

Terminal returned this:
[salva@salva-pc ~]$ backintime-qt --debug
bash: backintime-qt: no se encontró la orden
[salva@salva-pc ~]$ 

"no se encontró la orden" is the spanish of "The order was not found."

I understand that backintime-qt is not installed. True?

**Comment by Germar** [comment]
Oh, sorry. With 1.1.18 the command is `backintime-qt4 --debug`

**Comment by superlativo77** [comment]
Don't worry.

[salva@salva-pc ~]$ backintime-qt4 --debug
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 30, in <module>
    import qt4tools
  File "/usr/share/backintime/qt4/qt4tools.py", line 21, in <module>
    from PyQt4.QtGui import QFont, QFileDialog, QListView, QAbstractItemView,      \
ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
[salva@salva-pc ~]$

**Comment by Germar** [comment]
This is a bug in `freetype2-inf`. Please remove it.

[More infos](https://aur.archlinux.org/pkgbase/backintime/)

**Comment by superlativo77** [comment]
Hi Gemar. Thanks for the clue!

I solved it with this command:
`sudo pacman -S --asdeps freetype2 cairo fontconfig`

Accept when prompted to remove freetype2-infinality

VLC that did not open also works again.

Thank you very much Germar for your help!
