### ISSUE TITLE
Odd interface?

### ISSUE THREAD

**Issue by aridus** [bit-team/backintime#732]
I have installed backintime stable on for somebody else on their Ubuntu 16.10 installation and it works fine, but the interface is odd and clunky looking (presumably it is not using qt?). I installed using 'sudo apt-get install backintime-qt4', as on my 16.10 machine, which has the correct interface.

Presumably something is missing on this person's installation but I am unsure (a) why, or (b) how to resolve this.

With grateful thanks for any advice, Martin.

**Comment by Germar** [comment]
Did you run Back in Time as root on the other machine? Qt GUIs running as root always look awkward.

If you run it as normal user than you can fix it with `qtconfig-qt4`

**Comment by aridus** [comment]
Many thanks Germar: I was able to fix the interface using qtconfig-qt4.

One additional matter that I note - I mention it in case it is relevant for the design of BiT: the screen is a double resolution screen and the icons of BiT are therefore very small: I did not see anyway of changing this with qtconfig-qt4.

**Comment by Germar** [comment]
This won't work with BiT stable. The function for HighDPI screens where added in Qt5.6 but BiT stable uses Qt4

I'll add it in testing but I don't have a HighDPI screen to test.

**Comment by aridus** [comment]
Ahhh so it should work in BiT testing? If so I will give that a try.

Many thanks Germar

**Comment by Germar** [comment]
Not yet. But I'll add that feature...

**Comment by aridus** [comment]
OK, thanks: when it is added let me know and I will test.

**Comment by Germar** [comment]
According to [Qt Doc](http://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum) this has been added in 5.6.
So it shouldn't raise an `AttributeError`. But I'll try to update my OpenSuse Leap VirtualBox to 42.2 and reproduce this.

**Comment by Germar** [comment]
Looks like OpenSuse removed `Qt.AA_EnableHighDpiScaling` in Qt 5.6.1. It does work fine on Ubuntu 16.10 with Qt 5.6.1

**Comment by taupehat** [comment]
Confirmed fixed. Thank you for the very prompt work on this.
