### ISSUE TITLE
backup-job behavior

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#735]
Hi Germar,

When I put the following in the crontab:
`*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job >/dev/null`
`*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 3 backup-job >/dev/null`

"backup-job" runs normally and it doesn't backup every 15 minutes but when I put "backup-job" in a script or run it directly in a terminal, it backs up every time it runs.

I've checked "/root/.local/share/backintime/anacron" and the timestamp of the profiles gets updated every time I run "backup-job". Could you please help me understand what's going on?

**Comment by Germar** [comment]
BiT will write a new timestamp everytime it creates a new successful snapshot. No matter if started with `backup` or with `backup-job`.

But it will only use the timestamp to determine if a new snapshot is necessary if you choose schedule `Repeatedly (anacron)` or `When drive get connected (udev)`. 

So as long as you keep the schedule it should not create a new snapshot with `backup-job` if not necessary. No matter where you call it.

**Comment by codesmaker** [comment]
So if the schedule is off and I run `backup-job` in terminal, it will create a new snapshot even if there is one created 15 minutes ago for example. Interesting.

What if I activate the anacron schedule and instead of executing `backup-jobs` directly, I put it in a script? Would that solve the every 15 minutes backups? The issue I have here is that I have many laptops and I don't want them to hit hard the backup server at the same time. So, I want to check that there is no laptop being backed up before firing up `backup-jobs`.

**Comment by codesmaker** [comment]
So, I've tried it and it worked. Is it possible to prevent backintime from overwriting the crontab?

**Comment by Germar** [comment]
Sure, as long as the schedule is activated BiT will check the timestamp before taking a new snapshot and it won't connect to the server to check. So you don't need to worry about your backup server.

But you could also use a user-callback script to add a (random) delay before running the snapshot.

BiT will always recreate the job in crontab. There is no way to deactivate that.

**Comment by codesmaker** [comment]
Good idea. Hmm...instead of adding a delay, I would like to do the following:

`#!/bin/bash
#    Copyright (c) 2012-2015 Germar Reitze
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#Script should return 0 if everything is alright. Returncode !0 will cancle
#the running snapshot (BIT version >1.1.0).

profile_id="$1"
profile_name="$2"
reason="$3"

case $reason in
    1) #Backup process begins
         #Check the backup server for a specific value. If the received value is "0", then exit without backing up 
        RESULT=`su - john -c "ssh -q -p2222 john@192.168.1.9 check-rsync"`
        if [ $RESULT -eq 0 ]; then
        exit 1
        ;;
    2) #Backup process ends
        ;;
    3) #A new snapshot was taken
        snapshot_id="$4"
        snapshot_name="$5"
        ;;
    4) #There was an error
        errorcode="$4"
        case $errorcode in
            1) #ERROR The application is not configured
              ;;
            2) #ERROR A 'take snapshot' process is already running
              ;;
            3) #ERROR Can't find snapshots folder (is it on a removable drive ?)
              ;;
            4) #ERROR A snapshot for 'now' already exist
              ;;
        esac
        ;;
    5) #backintime-qt4 (GUI) started
        ;;
    6) #backintime-qt4 (GUI) closed
        ;;
    7) #Mount drives
        ;;
    8) #Unmount the drives
        ;;
esac   5) #backintime-qt4 (GUI) started
        ;;
    6) #backintime-qt4 (GUI) closed
        ;;
    7) #Mount drives
        ;;
    8) #Unmount the drives
        ;;
esac`

Should it be saved as user-callback in `~/.config/backintime`? Will this script be checked no matter what schedule I use or even disable all schedules?

**Comment by Germar** [comment]
The script must be named `~/.config/backintime/user-callback` and have execute permissions. It will be called on several events during taking the snapshot and also during starting and ending the GUI.

 Why do you call it with `su - john -c ...`?

**Comment by codesmaker** [comment]
I'll try it out and get back to you. Thanks!

Actually, it's just a test script. The idea is that I want these users to login to the backup server using their SSH keys. If not, they would need to ssh as root because the cron job is executed as root.

**Comment by Germar** [comment]
You could use `ssh -q -p2222 -i /home/john/.ssh/id_rsa john@192.168.1.9 check-rsync` instead

**Comment by codesmaker** [comment]
Your command is much cleaner. I forgot about "-i" switch :). Everything works as a charm. Thanks Germar for all your help and advices!

**Comment by buhtz** [comment]
Thank you to you two. I learned a lot, too. :) Nice use case.
Issue can be closed now?
