### ISSUE TITLE
Changing the scheduled daily hour of a second profile adds another cron job for the first profile, triggering 2 daily snapshots instead of one for the first profile

### ISSUE THREAD

**Issue by jean-christophe-manciot** [bit-team/backintime#737]
Ubuntu 16.10
bit 1.1.18

No such issue when any other every day hour is scheduled, except for 23:00 which is not even available (cf. issue "[23:00 is missing in the list of every day hours](https://github.com/bit-team/backintime/issues/736)").

**Comment by Germar** [comment]
When do they start? Both at 0:00?

**Comment by jean-christophe-manciot** [comment]
The second one starts when the first one is done.
This means in particular that ~/.config/user-callback is called and executed twice.

**Comment by jean-christophe-manciot** [comment]
I have just realized the real trigger of this issue by launching **gnome-schedule**: I saw in real time what was happening and the chosen bit job scheduled hour has no real impact.
I have 2 profiles. Let's say the first one is scheduled every day at 22:00 and the second at 1:00, although the chosen hours are not important.
If I launch gnome-schedule, I can see both cron jobs.
Now, if I change the hour of the second profile within bit to, let's say, 2:00, I can see on gnome-schedule that the original 1:00 job disappears, but 2 more jobs are added to the list: the first one at 22:00 - **again** - and the second one at 2:00!
That makes 2 jobs at 22:00 and 1 job at 2:00.

**Comment by Germar** [comment]
When you change schedules in BiT it will always clean up all backintime entries in crontab and then write them again. To prevent removing custom crontab lines BiT adds a comment line before every schedule and it will also only remove those lines with those trailing comment line
```
#Back In Time system entry, this will be edited by the gui:
*/15 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null
```

I guess, you have one line without this trailing comment which causes BiT to not remove it. Please run `crontab -e` in Terminal and remove ALL lines which contain `backintime`. Next open BiT GUI, go to Settings and press OK. This will rewrite the schedules and should fix your problem

**Comment by jean-christophe-manciot** [comment]
It works now, but I don't recall manually adding a bit entry in cron, which means you changed your policy. So other people should also be impacted by this new behavior.
