### ISSUE TITLE
Relationship between backintime-qt4_polkit and backintime-qt4-root

### ISSUE THREAD

**Issue by hannes101** [bit-team/backintime#738]
Hello,

I am the packager for fedora and I just wondered what exactly is the difference between these two binaries and how exactly they should be called.
Is the polkit version a substitute for the root version or why do we need the additional binary?

Thanks a lot 
Johannes

**Comment by Germar** [comment]
`/usr/bin/backintime-qt4_polkit` is a wrapper script for running BiT as root with polkit. See #550 

`/usr/share/applications/backintime-qt4-root.desktop` is a menu entry which will start the above script.
