### ISSUE TITLE
Any way to backup Files in Home Folder?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#739]
Hi, I have a small number of Files in the Home Folder that I use to launch Terminal stuff. They do not seem to be saved unless I specifically include them in the setup and I sometimes forget to add new ones or delete old ones.

I do not want to back the entire Home Folder just some specific Folders and all non-hidden Files in Home. How do I do that?

**Comment by DecoDogs** [comment]
Just another user's thoughts here, but is there some reason for not backing up your home directory?  If it contains a lot which doesn't change, then BiT only saves the changes (after the first backup).

You said "just some specific Folders and all non-hidden Files in Home".  You can include those folders explicitly (/home/whatever1, etc) without including /home itself.  On Linux, 'hidden' files can be excluded by including the patter ".*" (dot star) in the exclude list.  I do not have a windows machine (or BiT for that), so I don't know if there is an attribute selection (e.g., "hidden").

**Comment by Germar** [comment]
I'd second @DecoDogs. You can either cherry-pick include folders in home but than you'll always miss new important stuff. Or you include the whole home and exclude those you don't need to backup but won't miss new stuff anymore. You can use wildcards to exclude. `/home/USER/.*` would exclude all hidden folders in your home.
