### ISSUE TITLE
Recording Backup when no changes

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#740]
Hi, I like to check that my wife is running BiT daily on her laptop. But noticed that if there are no changes to the snapshot, then nothing is shown in the GUI-list on the left side of the window.

I have no way of knowing if she has backed up or not and I have ti run BiT for her, just in case. Is there some way you can still apply a date in the list even when the snapshots are the same? I notice it shows a message in the Terminal mode, but I don't get to see that unless I am there at the time. :)

**Comment by DecoDogs** [comment]
In my 1.0.24 version GUI, there's a 'view last log' item at the top of the BiT window.  The timestamp in it is updated even if no backup is done (needed).   This is also saved in the snapshot_X.log file, so you could look there without starting BiT GUI I suppose.  The timestamp in the 'view sanpshot log' is specific to the snapshot (of course).

I've been using BiT for years, and I keep finding nifty new things.....!  Great software.

**Comment by Germar** [comment]
When you hover over a snapshots there will be a Tooltip showing the date when that snapshot was checked last time without finding any changes.

![hover](https://cloud.githubusercontent.com/assets/2731999/24840780/658c5cbe-1d74-11e7-8767-c0c630b1a578.png)

You could also make BiT to create a new snapshot no matter if there was changes or not. If you use `Full rsync mode` you need to check `Take a new snapshot regardless of there was changes or not` in `Settings -> Options` or if you not use `Full rsync mode` you need to uncheck `Check for changes (don't take a new snapshot if nothing changed)`
