### ISSUE TITLE
Hard drive Raspberry pi: "Operation not permitted"

### ISSUE THREAD

**Issue by ilyasst** [bit-team/backintime#741]
Hi,
I am trying to setup backintime through ssh on my Raspberry Pi. A hard drive is mounted on the Raspberry Pi at `/mnt/usb`, and I can read and write on the drive. However, when I try to validate the configuration in backintime, I get the following error message:
```
Remote host 192.168.0.162 doesn't support 'cp -aRl SOURCE DEST':
cp: cannot create hard link ‘/mnt/usb/tmp_K07PWQ/b’ to ‘/mnt/usb/tmp_K07PWQ/a’: Operation not permitted
```
I have looked into the manual, found a section about this, but cannot really understand what I am supposed to do to fix it...
Could you please help me solve this ?

Thank you,
Ilyass

**Comment by Germar** [comment]
please make sure your drives filesystem supports hard links. Best would be a native Linux filesystem like EXT. But NTFS would do the job, too. FAT doesn't work because FAT doesn't support hard links.
