### ISSUE TITLE
Backup to my ancient NAS is slow, can I offload rsync processes to the clients?

### ISSUE THREAD

**Issue by mospaw** [bit-team/backintime#742]
Back in Time is working great for me, but I have a question about offloading the rsync process to the client machines. 

I have an old but reliable Netgear ReadyNAS NV+ that serves me well as a big dumb place to store my various machines. Unfortunately, top speed with rsync is around 1.3 MB/second. A full snapshot of my larger systems takes days. Each rsync instance hits its little CPU at 100%.

The same NAS can handle SAMBA/NFS transfers at around 10.5 MB/second.

Is there a way to offload the rsync process in Back In Time so that my much more powerful client machines can do the heavy CPU work and let the NAS just kind of store things?

**Comment by Germar** [comment]
First of all please activate `Full rsync mode` in Options. This is much faster than the old method because rsync will handle hard links.

Can you please send me the `~/.local/share/backintime/takesnapshot_.log` from one of the hosts which took that long? I guess there is something going wrong with matching unchanged files. Normally rsync only compares file size and date to determine if it has changed. If it takes that long for you I wonder if rsync does always calculate checksums for all files.

**Comment by mospaw** [comment]
Thank you for the reply. I checked both machines and `Full rsync mode` was already enabled. They're both fully-up-to-date Linux Mint 18.1 machines, if that makes any difference. The connection is made via ssh and private key. 

Here is the `takesnapshot._log` file from one of the machines. I redacted some information, including the hostname, local folders, etc. and about 30,000 lines of various files. 

```
========== Take snapshot (profile 1): Mon Apr 10 00:00:01 2017 ==========

[I] ...
[I] Take snapshot
[I] rsync -rtDHh --links -A -X -pEgo --info=progress2 --no-i-r --rsh="ssh -p 22  -o IdentityFile=/root/.ssh/id_rsa"  --delete --delete-excluded  -v  --chmod=Du+wx  --exclude="/root/.local/share/backintime/mnt/1_32448" --exclude="/root/.local/share/backintime" --exclude=".local/share/backintime/mnt"  --exclude=".gvfs" --exclude=".cache/*" --exclude=".thumbnails*" --exclude="[Tt]rash*" --exclude="*.backup*" --exclude="*~" --exclude=".dropbox*" --exclude="/proc/*" --exclude="/sys/*" --exclude="/dev/*" --exclude="/run/*" --exclude="/etc/mtab" --exclude="/var/cache/apt/archives/*.deb" --exclude="lost+found/*" --exclude="/tmp/*" --exclude="/var/tmp/*" --exclude="/var/backups/*" --exclude=".Private" --exclude="/media/*" --exclude="/mnt/*"  --include="/" --include="/**" --exclude="*" / '[redacted]/root/1/new_snapshot/backup/"' --link-dest="../../20170409-153002-233/backup" -i --out-format="BACKINTIME: %i %n%L"
[I] Take snapshot (rsync: building file list ... done)
[I] Take snapshot (rsync: BACKINTIME: .d..t...... ./)
[I] Take snapshot (rsync: BACKINTIME: cd..t...... dev/)
[I] Take snapshot (rsync: BACKINTIME: cd..t...... etc/)
[I] Take snapshot (rsync: BACKINTIME: <f.st...... etc/ld.so.cache)
[C] <f.st...... etc/ld.so.cache
[I] Take snapshot (rsync: BACKINTIME: <f..t...... etc/mailcap)
[C] <f..t...... etc/mailcap
[I] Take snapshot (rsync: BACKINTIME: cd..t...... etc/apt/)
[I] Take snapshot (rsync: BACKINTIME: <f.st...... etc/apt/trusted.gpg)
[C] <f.st...... etc/apt/trusted.gpg
[I] Take snapshot (rsync: BACKINTIME: <f..t...... etc/apt/apt.conf.d/99synaptic)
[C] <f..t...... etc/apt/apt.conf.d/99synaptic
[I] Take snapshot (rsync: BACKINTIME: cd..t...... etc/cups/)
[I] Take snapshot (rsync: BACKINTIME: <f.st...... etc/cups/subscriptions.conf)
[C] <f.st...... etc/cups/subscriptions.conf
[I] Take snapshot (rsync: BACKINTIME: <f.st...... etc/cups/subscriptions.conf.O)
[C] <f.st...... etc/cups/subscriptions.conf.O

[removed about 30,000 lines of various files]

[I] Take snapshot (rsync: BACKINTIME: cd..t...... var/lib/xkb/)
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/Xorg.0.log)
[C] <f.st...... var/log/Xorg.0.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/alternatives.log)
[C] <f.st...... var/log/alternatives.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/auth.log)
[C] <f.st...... var/log/auth.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/dpkg.log)
[C] <f.st...... var/log/dpkg.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/kern.log)
[C] <f.st...... var/log/kern.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/syslog)
[C] <f.st...... var/log/syslog
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/apt/history.log)
[C] <f.st...... var/log/apt/history.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/apt/term.log)
[C] <f.st...... var/log/apt/term.log
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/log/cups/access_log)
[C] <f.st...... var/log/cups/access_log
[I] Take snapshot (rsync: BACKINTIME: cd..t...... var/spool/cron/crontabs/)
[I] Take snapshot (rsync: BACKINTIME: <f.st...... var/spool/cron/crontabs/root)
[C] <f.st...... var/spool/cron/crontabs/root
[I] Take snapshot (rsync: BACKINTIME: cd..t...... var/spool/cups/tmp/)
[I] Take snapshot (rsync: BACKINTIME: cd..t...... var/tmp/)
[I] Take snapshot (rsync: BACKINTIME: hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0)
[C] hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_r600.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0
[I] Take snapshot (rsync: BACKINTIME: hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0)
[C] hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_r300.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0
[I] Take snapshot (rsync: BACKINTIME: hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0)
[C] hf+++++++++ usr/lib/i386-linux-gnu/vdpau/libvdpau_nouveau.so.1.0.0 => usr/lib/i386-linux-gnu/vdpau/libvdpau_radeonsi.so.1.0.0
[I] Take snapshot (rsync: sent 2.08G bytes  received 1.49M bytes  444.80K bytes/sec)
[I] Take snapshot (rsync: total size is 73.30G  speedup is 35.15)
[I] Take snapshot (rsync: rsync warning: some files vanished before they could be transferred (code 24) at main.c(1183) [sender=3.1.1])
[I] Save config file ...
[I] Save permission ...
[I] Remove old snapshots
[I] Try to keep min free space
[I] Try to keep min 2% free inodes
[I] Finalizing
```

I am happy to provide any other information, or privately share the non-redacted version of the file.

**Comment by Germar** [comment]
That looks good so far. All changes where detected because of size and time differences.

It looks like you're backing up the whole system. IMHO this is a waste of time and space because most files on the system come from packages and can be reinstalled easily if you only keep a list of all installed packages.

I personally prefer to take an image once a year of the system with Clonezilla which I can restore in half an hour to have the basic system up and running again. With Back in Time I only backup my home as user and `/etc`, `/usr/local` , `/root` and a [list of all installed packages](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection) as root. 

In case of a disaster I restore the image with Clonezilla and then use BiT to restore the data and settings. All installed programs can be [reinstalled from the list](https://github.com/bit-team/backintime/wiki/FAQ#how-to-restore-debian-ubuntu-package-selection) which was made on backup.

**Comment by mospaw** [comment]
I'm glad the basic setup looks good. And yes, I am backing up the entire system. The actual day-to-day changes (I do a snapshot every 12 hours) are small. The initial snapshots were pretty painful, but they finished. And I have Back In Time set to only allow one instance at a time (per machine).

My main issue was that rsync was running on the NAS, which gets CPU-bound doing so. I was wondering if there is any configuration beyond what we have already discussed that might offload any of the work to the client machines being backed up, given that the NAS itself can handle file operations roughly ten times as fast as the throughput on rsync.

**Comment by Germar** [comment]
You can also sync to a local mounted NFS/SMB share. This would not stress the NAS CPU. But it would take much longer as every filesystem interaction would cause a TCP request and answer.

**Comment by mospaw** [comment]
I haven't tried the NFS/SMB mount for a few reasons yet (mainly that permanent network mounts on Linux Mint are somewhat of a pain in the neck and two of my three machines are laptops that travel).

I  was experimenting with plain old rsync via port 873 from another matching to my NAS, and it moves along quite a bit faster than going via SSH. It appears that on my setup the SSH daemon is what's slwoing things down for whatever reason. 

Is there a way to configure Back In Time to use 873 and rsync directly instead of using SSH? I am aware that this has potentially very serious security implications.

**Comment by Germar** [comment]
No, at the moment there is no way to connect to a rsync daemon with BiT.

You can check, if other ciphers would be faster than the default. I used to use `arcfour` with my WD MyBook WorldEdition which has a weak CPU, too. `arcfour` was about two times faster than default `AES` ciphers. But of course it is a weak, insecure cipher. You shouldn't use it on untrusted networks. Also every serious SSHd should be configured to not accept `arcfour` anymore. Maybe you could activate it on your NAS. You can run `backintime benchmark-cipher 100` to benchmark all available ciphers (with a file size of 100MiB).

But again, please do this only on trusted networks. If you need to backup your Laptops while they're on the road, you could connect them through VPN first.

Alternative you could use a second Linux server (which has enough power to decode the cipher or even better has [AES-NI](https://en.wikipedia.org/wiki/AES_instruction_set) support) where you mount the NAS (NFS or iSCSI) and configure BiT to sync to that server. This could even be a low power ARM board like [Cubieboard](http://cubieboard.org/)

**Comment by mospaw** [comment]
Given that this is my spare NAS and it's roughly 10 years old, it supports `arcfour` out of the box. 

I'm only backing up on my home wired network, and never remotely, so if someone can see what I'm doing, I've got bigger issues.  But thank you for the warning just the same. Not everyone who reads this will necessarily understand the implications of a weak, insecure cipher. And if I do decide to backup from outside my network, VPN it is!

I did tests at 25MB, 50MB, and 100MB files on the various ciphers, making sure there was only one job running and monitoring CPU load via `top`. It looks like `arcfour128` is the fastest across the board, so I'll go with that. 

I do have a spare Core 2 Duo box lying around and might set it up as you suggest above. That's a great idea. 

I really appreciate your answers. Thank you for taking the time to explain things in detail and help me out. My throughput appears roughly double what it was. And if the server approach works, I'll let you know.

**Comment by Germar** [comment]
I'm happy to help.

A Core 2 Duo could hit hard on your power bill. That's why I suggested a Cubieboard. I recently replaced my old WD MyBook with a CubieTruck3 and it works great. I still use the same HDD, power supply and case. Only the logic board changed. But for sure, this is a different story with your ReadyNAS.

**Comment by mospaw** [comment]
My power bill is actually pretty low. I run an i7 desktop, 2 NASs, 3 laptops and 4 monitors all the time, not to mention the rest of my household stuff, and it's $50 or $60 a month usually. :) 

Plus, the Core 2 Duo is already bought, paid for, and set up with Linux.

**Comment by Germar** [comment]
So, you're happy to have low energy costs at your place :wink: 

I'm currently planing to replace a server because a new one is cheaper than running the old one for two more years...
