### ISSUE TITLE
Can't mount sshfs

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#743]
`Can't mount sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh[my-id]_rsa -o idmap=user backup@[my.ip]:[my-backup-dir] /root/.local/share/backintime/mnt/C322B638/mountpoint`

I see this directory already exists. Should I remove it?

**Comment by Germar** [comment]
There should have been an error message why it couldn't mount, wasn't it?

If you are sure there is nothing mounted you can remove the directory. BiT will recreate it.

**Comment by kerner1000** [comment]
This is the only message I get.. deleting the directory does not help, it gets re-created and again the same error..

**Comment by Germar** [comment]
Please try that command manually in Terminal

```
sudo -i
mkdir ~/mnt
sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[my-id]_rsa -o idmap=user backup@[my.ip]:[my-backup-dir] ~/mnt
```

**Comment by kerner1000** [comment]
I get "remote host has disconnected"

If I try ssh backup@[my.ip] I can connect without pw.

**Comment by Germar** [comment]
Please make sure, `sftp` is installed correctly on remote host. In `/etc/ssh/sshd_config` here must be a line like
```
Subsystem sftp /usr/lib/openssh/sftp-server
```
Make sure, that path is correct.

If that doesn't help please run 

```
sshfs -odebug,sshfs_debug,loglevel=debug -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[my-id]_rsa -o idmap=user backup@[my.ip]:[my-backup-dir] ~/mnt
```
and post the output again

**Comment by kerner1000** [comment]
That was it. sftp-server was not installed. Thanks a lot!
