### ISSUE TITLE
Question: How dangerous is the experimental removal of remote snapshots?

### ISSUE THREAD

**Issue by Mintulix** [bit-team/backintime#744]
Hi Germar, the option "Auf entferntem Rechner im Hintergrund ausführen" ("delete remote snapshots in background" or so) is marked as experimental.
What is the worst case: no removal of a snapshot or the total loss of all snapshots?

**Comment by Germar** [comment]
Worst case is no removal of snapshots. I just don't have a NAS like QNAP or Synologie where I could test it. That's why I added the Experimental warning. It does work fine on Debian remote hosts...

**Comment by Mintulix** [comment]
OK, I tried it with a Synology NAS and get the error while saving the configuration (background removal switched on):
Remote client doesn't support »screen -d -m bash -c ...«:
sh: screen: command not found

So it doesn't work. Thanks for the info.
