### ISSUE TITLE
Failed to take snapshot [..] !!!

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#745]
Maybe connected to #743.

The log file does not seem to have valuable information:

```
[C] <f+++++++++.fdt
[C] <f+++++++++ .fdx
[C] <f+++++++++ 39.fnm
[C] <f+++++++++ 39.frq
[C] <f+++++++++39.nrm
[C] <f+++++++++ 39.prx
[C] <f+++++++++ 39.tii
[C] <f+++++++++ .tis
[C] <f..t...... .gen
[C] <f+++++++++ _3a
[E] Failed to take snapshot 04/12/17 08:57:58 !!!
```

**Comment by Germar** [comment]
Please switch filter in Snapshots Log View to All. That should show more Infos about the problem

**Comment by kerner1000** [comment]
Yes, that helped.
```
[I] Take snapshot (rsync: rsync: [sender] write error: Broken pipe (32))
[E] Error: rsync: [sender] write error: Broken pipe (32)
```
Could that be some timeout issue?

**Comment by Germar** [comment]
Please try out current dev version. This will use `ServerAliveInterval=240` to prevent timeouts.
```
sudo add-apt-repository ppa:bit-team/testing
sudo apt-get update
sudo apt-get install backintime-qt
```

**Comment by kerner1000** [comment]
OK, I will give that a try. But I think the keep alive is already defined in the current version?

`sshfs -p 22 -o ServerAliveInterval=240 -o IdentityFile=/root/.ssh/[my-id]_rsa -o idmap=user backup@[my.ip]:[my-backup-dir] ~/mnt`

**Comment by Germar** [comment]
That's only for the `sshfs` mount. The ssh tunnel which rsync uses didn't have that option in older versions

**Comment by kerner1000** [comment]
I have installed the latest testing build.

Now I do not see any broken pipes anymore, but the backup still fails..

```
[C] <f.st...... [..].log
[I] Take snapshot (rsync: sent 54.25M bytes  received 301.47K bytes  84.78K bytes/sec)
[I] Take snapshot (rsync: total size is 73.98G  speedup is 1,356.12)
[E] Failed to take snapshot 2017-04-13 18:21:35 !!!
```

**Comment by Germar** [comment]
Please run `backintime backup --debug` in Terminal and post the output.

**Comment by kerner1000** [comment]
Hi, here is the complete log. I saw some strange 'permission denied's.

https://gist.github.com/kerner1000/55832be7942cbe5ce6b8c241dd2e6139

**Comment by Germar** [comment]
Please check the remote filesystem integrity with `fsck`. Could be corrupt.

On the other hand this could be caused by the broken pipe before. You just started to use BiT, didn't you? Can you start a new snapshot destination from scratch? Or delete the previous snapshots inside the current destination?

**Comment by kerner1000** [comment]
Im already using BiT since ages, thanks for your great work! I had to do some changes to my NAS, i.e. change from Optware to Entware, which messed up thinks quite a lot. I was using a "simple" backup using a locally mounted NFS share in the meantime, but the performance is horrible, especially during the smart remove. Therefore I am trying to come back to the ssh-based approach, which has a great performance.

I know BiT does a full (not increment) backup from time to time. Is there a way to trigger this manually? I would rather like to keep my snapshots..

**Comment by Germar** [comment]
Okay. You can try to remove/rename the last snapshot so BiT will sync to the overlast snapshot. Maybe that one is not corrupt.

BiT always make incremental backups. There is no function to make a new full snapshot. You would have to move the current snapshots, take a new one and move the old snapshots back in place to have a new 'full' snapshot.

But I think you meant the checksum method. This will force rsync to calculate checksums for all source and destination files to check if the files have changed. Normally rsync uses files size and modification time to check if they have changed. You can force to use this with `backintime backup --checksum`. I also wrote a [wiki on how to use that periodically](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-checksum-to-find-corrupt-files-periodically)

**Comment by kerner1000** [comment]
I resolved this by "fixing" permissions.
