### ISSUE TITLE
Display issues with the progress bar

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [bit-team/backintime#746]
Hi everyone !

Great software so far but I'm having this issue, the color of the progress bar makes it really hard for me to read it as you can see on the picture I'll try to add with this post. I actually didn't see it was a progress bar for a long time :/

![picture](https://cloud.githubusercontent.com/assets/26625900/24961109/1c0de1d6-1f98-11e7-9fa0-f0a97c8719d6.JPG)

I'm using back-in-time 1.1.20 on Ubuntu16.04. Also my computer is a MacBook.

I noticed I don't have this problem with the "back in time" shortcut but only with "back in time root" shortcut. But I need to use it as root to backup some folders. What can I do ?

Also, i guess this has to do with qt4 vs gnome or something like that but I never understood this properly.

**Comment by Germar** [comment]
You could try to change the Style with `sudo -i qtconfig-qt4`

**Comment by thiswillbeyourgithub** [comment]
It worked ! (after a reboot)

Thanks a lot
