### ISSUE TITLE
cache.py files are not backed up

### ISSUE THREAD

**Issue by sebastien** [bit-team/backintime#747]
Hi there,

I just realized why `cache.py` files were always missing from my restored backups: they somehow are excluded from backintime. 

However, I don't have a `cache.*` exclusion rule, here's a snapshot of my config (which is stock in Ubuntu 17.04)

![screenshot from 2017-04-19 11-45-49](https://cloud.githubusercontent.com/assets/14598/25188964/c17e3b22-24f5-11e7-95b1-96e901d52b2f.png)

**Comment by Germar** [comment]
I just double-checked but can't confirm this. A `cache.py` file is backed up and also restores without problems.

Please provide more infos on the file. Where is it located? Is that path in `Include`? Is it an ordinary file or a symlink? Is it read-able by the user, who runs the backup?

**Comment by buhtzz** [comment]
@sebastien There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, Not reproducible yet

**Comment by buhtz** [comment]
I wasn't able to reproduce the problem. I can backup `cache.py` files without problems.
