### ISSUE TITLE
where to save snapshots

### ISSUE THREAD

**Issue by nomad101** [bit-team/backintime#748]
I'm fairly new to linux. Sorry for the dumb question, but in settings, 'where to save snapshots' does not show other drives that are mounted. (I'm only able to see root and computer). Am I missing something? 

Thanks

**Comment by Germar** [comment]
You need to navigate to `/media/USER/`

Your drives are mounted in there.

**Comment by tigger10** [comment]
doh! Thanks for the quick response

**Comment by nomad101** [comment]
doh! Thanks for the quick reply
