### ISSUE TITLE
Snapshor Button is greyed-out

### ISSUE THREAD

**Issue by JayPiEs** [bit-team/backintime#750]
I've made some snapshots with backintime and today i want to make a new snapshot but it is not possible, because the button and menu-item is greyed-out.
Since the last succesful backup i didn't change anything and backintime recognizes the old snapshots...

I'm on Ubuntu 16.04 with backintime 1.1.12

**Comment by Germar** [comment]
Please remove the files `~/.local/share/backintime/worker.lock` and `~/.local/share/backintime/worker.message`.

**Comment by buhtz** [comment]
Dear @JayPiEs does this solution fix your problem? In that case we can close the Issue.

**Comment by jbescudie** [comment]
I had the same problem, it workded for me ! (ubuntu 16.04, backintime 1.1.20)

**Comment by buhtz** [comment]
#Close.
