### ISSUE TITLE
What does this message mean?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#751]
v 1.1.20 -- I think. 
I saw an update a few days back, but this is what's showing in the "About" box.

Using CLI with...
sudo -i backintime backup --profile-id 1 --config /media/Back-in-Time/backintime/Acer14/zingy/2/last_snapshot/config

Getting this warning/error most times I run it...
"sni-qt/7107" WARN  14:16:01.716 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 

Should I be worried?

**Comment by Germar** [comment]
Nothing to worry about. It's just a warning.

This is already fixed in current dev series 1.2.0
