### ISSUE TITLE
question about using BIT for simple backup

### ISSUE THREAD

**Issue by GreggWriter** [bit-team/backintime#755]
I've been using BackInTime to back up some folders to a pen drive. It's been working great until yesterday. I have changed absolutely nothing, so I don't know why I'd be getting this problem message. (screenshot) And that backintime folder it's asking to remove is where everything gets saved. Any idea what might be causing the problem? Thanks.
![selection_124](https://cloud.githubusercontent.com/assets/28337330/25650532/309c428a-2fa3-11e7-92c1-44f176ae8203.png)

**Comment by Germar** [comment]
Please check your drive with `fsck /dev/sdXX`. I guess there are corrupt sectors.

**Comment by GreggWriter** [comment]
Thanks Germar. Unfortunately, I didn't explain how newbie I was. I had a feeling the XXs in your command were for something else, but I don't know what to put in there. I actually ran the command as is and it said 'no such file or directory.' 

One thing I noticed was on the pen drive where my "where to save snapshots" is, there is this 'new snapshot' folder they're saying can't be removed. (screenshot 273)
![selection_273](https://cloud.githubusercontent.com/assets/28337330/25686825/d24efb5c-3036-11e7-91be-0caaa186dc31.png)

I tried to remove that folder and got screenshot 275
![selection_275](https://cloud.githubusercontent.com/assets/28337330/25686876/5b5c6d62-3037-11e7-8185-cc1ffb1e93d0.png)
And then when I clicked on 'delete' button in 275 I got this:
![selection_276](https://cloud.githubusercontent.com/assets/28337330/25686885/7055008a-3037-11e7-8b06-bf856bf26b3a.png)

I was afraid to try anything further. But I did a little searching and there is a "Gregg Bell" folder in my Calibre Library, which is one of my "included" folders in BIT. (screenshot 277)
![selection_277](https://cloud.githubusercontent.com/assets/28337330/25687070/d54c56cc-3038-11e7-9a5f-129d845a4e04.png)



I don't know though, why it would need to be removed and if so why it isn't being removed.

You don't have to explain any of this stuff. I just mention it in case it gives you a clue as to what the problem might be.

I should say too, I'm running Xubuntu 16.04LTS and it's a 64 bit computer. 

And if it's the fsck /dev/sdXX that still is the solution, I went to Gparted and took a screenshot (274)
![selection_274](https://cloud.githubusercontent.com/assets/28337330/25686920/ad3fdf4c-3037-11e7-9690-ed9fdca981ac.png)

I was hoping that might tell you what I could put in there instead of the XXs. I was thinking that if it's the main drive you wanted checked it would be:

fsck /dev/sda1

but I wasn't sure.


Thanks very much.

**Comment by colinl** [comment]
On 4 May 2017 at 01:50, GreggWriter <notifications@github.com> wrote:

> Thanks Germar. Unfortunately, I didn't explain how newbie I was. I had a
> feeling the XXs in your command were for something else, but I don't know
> what to put in there. I actually ran the command as is and it said 'no such
> file or directory.'
>

I believe Germar wanted you to run this on the pen drive to check it is
ok.  If you plug it in and, in a terminal, run
df
you should see the drive there. It will probably be something like
/dev/sdb1. If you are not sure which it is then run df before and after
plugging it in and you will see it appear.

Colin

**Comment by Germar** [comment]
Thanks Colin, that's exactly what I wanted. 

You also need to run fsck with sudo

**Comment by GreggWriter** [comment]
Thanks very much Colinl and Germar. I still don't think I have what you want. I did run the `fsck /dev/sdb1` and you can see I got the warning. So I unmounted the pendrive (BackInTimer) and ran the command again. But I forgot to use sudo so I tried again with sudo. You can see the results. I don't know if that's the result you're looking for. I was going to mount the pendrive and try again with sudo fsck /dev/sdb1 again but considering the warning earlier I decided to stop (before I wrecked anything). Thank you so much for the help and here are the terminal results:
```

gregory@gregory-GA-A55M-DS2:~/Desktop$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1743512        0   1743512   0% /dev
tmpfs             352752     5624    347128   2% /run
/dev/sda1       73154816 51599184  17816448  75% /
tmpfs            1763744      628   1763116   1% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
tmpfs            1763744        0   1763744   0% /sys/fs/cgroup
tmpfs             352752       48    352704   1% /run/user/1000
/dev/sdb1       31260652  2825168  28435484  10% /media/gregory/BackInTimer
gregory@gregory-GA-A55M-DS2:~/Desktop$ fsck /dev/sdb1
fsck from util-linux 2.27.1
e2fsck 1.42.13 (17-May-2015)
/dev/sdb1 is mounted.



WARNING!!!  The filesystem is mounted.   If you continue you ***WILL***
cause ***SEVERE*** filesystem damage.


Do you really want to continue<n>? no
check aborted.
gregory@gregory-GA-A55M-DS2:~/Desktop$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
udev             1743512        0   1743512   0% /dev
tmpfs             352752     5628    347124   2% /run
/dev/sda1       73154816 51599188  17816444  75% /
tmpfs            1763744      628   1763116   1% /dev/shm
tmpfs               5120        4      5116   1% /run/lock
tmpfs            1763744        0   1763744   0% /sys/fs/cgroup
tmpfs             352752       48    352704   1% /run/user/1000
gregory@gregory-GA-A55M-DS2:~/Desktop$ fsck /dev/sdb1
fsck from util-linux 2.27.1
e2fsck 1.42.13 (17-May-2015)
fsck.ext2: Permission denied while trying to open /dev/sdb1
You must have r/w access to the filesystem or be root
gregory@gregory-GA-A55M-DS2:~/Desktop$ sudo fsck /dev/sdb1
[sudo] password for gregory: 
fsck from util-linux 2.27.1
gregory@gregory-GA-A55M-DS2:~/Desktop$ ^C
gregory@gregory-GA-A55M-DS2:~/Desktop$ 
```

**Comment by GreggWriter** [comment]
Germar and Colin. I ran chkdsk on a Windows computer and chose the 'scan and repair' button. It fixed the pen drive. I came back onto my Xubuntu computer and tested BackInTime with the same pen drive and it worked fine. Thanks so much for your help and this great tool!
