### ISSUE TITLE
Mount unmounted Backup Destination, run, then automatically unmount

### ISSUE THREAD

**Issue by disk0x** [bit-team/backintime#761]
With ransomware attacks increasing, even people using GNU/Linux are in danger of losing access to the files their user can read/write. 

I imagine a lot of us back up our ~/ in another HDD that is constantly mounted and r/w from our user. In case of an attack, we will also lose our backups. 

A solution to that can be for BiT to learn to mount volumes just before the cronjob starts, and then unmount it when it's done. This will minimize the time the backups are accessible by malware. 

Maybe there's also merit in making the backup destination only readable from a BiT user, which afaik is not something in use right now.

**Comment by total1ty** [comment]
just write a script?
three lines: mount, backintime -b, umount

**Comment by Germar** [comment]
This can be done with a [user-callback](https://github.com/bit-team/user-callback/blob/master/user-callback.default) with `$reason` = 7 or 8

**Comment by mfeldt** [comment]
> This can be done with a [user-callback](https://github.com/bit-team/user-callback/blob/master/user-callback.default) with `$reason` = 7 or 8

Indeed. But then backintime complains that it does not find the backup folder while its unmounted

**Comment by aryoda** [comment]
> > This can be done with a [user-callback](https://github.com/bit-team/user-callback/blob/master/user-callback.default) with `$reason` = 7 or 8
> 
> Indeed. But then backintime complains that it does not find the backup folder while its unmounted

Thanks for your comment.

This issue is very old and already closed. If you think you have found a bug or want to request an improvement please open a new issue and include a minimal reproducible example. THX!
