### ISSUE TITLE
Permissions Not Saved on NTFS

### ISSUE THREAD

**Issue by EnochPrime** [bit-team/backintime#762]
When using version 1.2.0~alpha16 and backing up to an NTFS external drive, a full back is made every time as the permissions have "changed".

OS: Linux Mint 18.1

**Comment by Germar** [comment]
Did you read [this FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-can-i-check-if-my-snapshots-are-incremental-using-hard-links) to check if they are incremental?

**Comment by jdm12989** [comment]
They were from at 26 May 2016 till at the latest 6 Mar 2017. Here is a select folder from the oldest snapshot, a random one in the middle, last incremental, and then the latest. Backups had stopped running because it was no longer incremental and ran out of space.

```
...20160526-200704-832/backup/media/Raid/Installers/Microsoft/Office $ ls -laih
total 2.7G
142350 -rwxrwxrwx 11 x x  559M Mar 29  2013 Office 2007.iso
142351 -rwxrwxrwx 11 x x 1002M Mar 29  2013 Office 2010 (32 bit).exe
142353 -rwxrwxrwx 11 x x  1.2G Mar 29  2013 Office 2010 (64 bit).exe


...20160930-030007-561/backup/media/Raid/Installers/Microsoft/Office $ ls -laih
total 2.7G
142350 -rwxrwxrwx 11 x x  559M Mar 29  2013 Office 2007.iso
142351 -rwxrwxrwx 11 x x 1002M Mar 29  2013 Office 2010 (32 bit).exe
142353 -rwxrwxrwx 11 x x  1.2G Mar 29  2013 Office 2010 (64 bit).exe

...20170306-030001-336/backup/media/Raid/Installers/Microsoft/Office $ ls -laih
total 2.7G
142350 -rwxrwxrwx 11 x x  559M Mar 29  2013 Office 2007.iso
142351 -rwxrwxrwx 11 x x 1002M Mar 29  2013 Office 2010 (32 bit).exe
142353 -rwxrwxrwx 11 x x  1.2G Mar 29  2013 Office 2010 (64 bit).exe


...20170428-030002-454/backup/media/Raid/Installers/Microsoft/Office $ ls -laih
total 2.7G
1892040 -rwxrwxrwx 1 x x  559M Mar 29  2013 Office 2007.iso
1892043 -rwxrwxrwx 1 x x 1002M Mar 29  2013 Office 2010 (32 bit).exe
1892056 -rwxrwxrwx 1 x x  1.2G Mar 29  2013 Office 2010 (64 bit).exe
```

**Comment by buhtz** [comment]
Can you please specify _NTFS external drive_. Hardware, Connection (USB?), NAS, mount options, ...?

**Comment by jdm12989** [comment]
NTFS external drive. It says raid because that is what I was backing up.

**Comment by buhtz** [comment]
_NTFS external drive._ is a to broad description. :D Maybe it is a USB connected external hard disc (HDD) or solid state disc (SDD) or an USB-stick. Or you use firewire or anything else?

**Comment by jdm12989** [comment]
Ah yes sorry. It is a NTFS HDD in an external Firewire enclosure (can also use USB, but is not currently).
I should also mention that I started with a new blank drive in the same enclosure and everything is currently working, but I still have the drive that had stopped working.

**Comment by buhtz** [comment]
@Germar do you have experience with NTFS as destination drives? Would you say this shoudl work?

Depending on "[Using rsync with link-dest from HFS to NTFS](https://superuser.com/a/170204/486099)" I would take `--perm` and `--times` (`rsync` options) into account. Or it has something to do witht he timestamp-resolution of NTFS. I would make some testing with it calling `rsync` direct to find out what is going on here.

Currently I have no time here (Master-Thesis deadline). @jdm12989 can you do some testing here? You can see the original `rsync`-call when using the BIT with the `--debug` option. Run `rsync` direct and test arround with the two options.

**Comment by buhtzz** [comment]
@EnochPrime There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Close as duplicate.

**Comment by EnochPrime** [comment]
> @EnochPrime There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?
> 
> Close as duplicate.

I am using a different backup solution now so this is no longer relevant to me.

**Comment by emtiu** [comment]
I think it's a documentation issue. NTFS simply isn't fit for use with backintime (because of hardlink, permission and other problems). We should warn users about that.

**Comment by emtiu** [comment]
Closing in favor of #1339.
