### ISSUE TITLE
Separate log file

### ISSUE THREAD

**Issue by DecoDogs** [bit-team/backintime#766]
I've looked through the issues and comments here, as well as general online searches, and haven't been able to find this particular question addressed:

Is there a way to have BiT log to a separate logfile?  That is, separate from /var/log/syslog.

BiT 1.0.34
Linux Mint 17.3

Update: 
* I see the logfile is defined in logger.py
* Would need to create / chown a separate logfile when installing via sudo
* Would need to add a logrotate set of entries at install time

**Comment by Germar** [comment]
[This is what I did](https://gist.github.com/Germar/c3e8be518b94bf262cde52be6b45da5d) on my server
