### ISSUE TITLE
dh: Unknown sequence --with (options should not come before the sequence)

### ISSUE THREAD

**Issue by jean-christophe-manciot** [bit-team/backintime#768]
Ubuntu 17.04 zesty
debhelper debian/10.2.5_bpo8+1
bit tag: v1.1.20

Building with:
```
sudo -u actionmystique -H dpkg-buildpackage --build=binary -m"Jean-Christophe Manciot <manciot.jeanchristophe@gmail.com>"
```

leads to:
```
dpkg-buildpackage: info: source package backintime
dpkg-buildpackage: info: source version 1.1.20+17.04
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build git-backintime
 fakeroot debian/rules clean
dh --with python3 clean
dh: Unknown sequence --with (options should not come before the sequence)
debian/rules:32: recipe for target 'clean' failed
make: *** [clean] Error 2
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
```

**Comment by Germar** [comment]
It does work here. Did you install `debhelper` and `build-essential`?

**Comment by jean-christophe-manciot** [comment]
> It does work here. Did you install debhelper and build-essential?
Does it on Ubuntu zesty?
Also, first half of your question is already answered and the answer to the second half is:
```
# apt-cache policy build-essential
build-essential:
  Installed: 12.1ubuntu2
```

**Comment by Germar** [comment]
Yes, I downloaded and installed a new Zesty vbox, install `build-essential` and run your command above without problems. What does happen if you run `makedeb.sh` in BiT source?

BTW my debhelper version is 10.2.2ubuntu1

**Comment by jean-christophe-manciot** [comment]
I downgraded ```debhelper & dh-systemd ```to your version:
```
apt install debhelper=10.2.2ubuntu1 dh-systemd=10.2.2ubuntu1
```
But the issue remains when building ```v1.1.20``` from the series1.1 branch:
```
dh --with python3 clean
dh: Unknown sequence --with (options should not come before the sequence)
debian/rules:32: recipe for target 'clean' failed
```
What happens when you run ```dh --with python3 clean``` on your VM?
How can I bypass the ```fakeroot debian/rules clean```

**Comment by Germar** [comment]
```
$ dh --with python3 clean
dh: Compatibility levels before 9 are deprecated (level 5 in use)
   dh_testdir
   debian/rules override_dh_auto_clean
rm -rf locale common/po/*.mo
find /home/germar/Downloads/backintime-1.1.20 -name "*\.py[co]" -delete
# these get regenerated
rm -f */man/C/*.1.gz
rm -f common/Makefile qt4/Makefile
rm -f common/config-example-*.gz
   dh_clean
dh_clean: Compatibility levels before 9 are deprecated (level 5 in use)
```

I've no idea. There is a 17.04 BiT 1.1.20 package in ppa:bit-team/stable...

**Comment by jean-christophe-manciot** [comment]
I have just found out the reason why this is happening:
I change the compatibility level from 5 to 9, due to the warning message ```Compatibility levels before 9 are deprecated (level 5 in use)``` with:
```
sed -i 's|5|9|g' debian/compat
```
**If I remove this line in my script, the build is OK.**
What is really strange is that I perform the same correction for many other debian packages which have the same warning message during the build, without any issue.

**Comment by jean-christophe-manciot** [comment]
BTW, no issue with latest debhelper ```10.2.5+bpo8+1```.

**Comment by jean-christophe-manciot** [comment]
You missed the point: it's because I changed debian/compat value that I was not able to build it.
I confirm that with your new commit, I'm not able to build the package anymore and you shouldn't be able either.

**Comment by Germar** [comment]
Ah, okay. Thanks for clarifying
