### ISSUE TITLE
A Bug I suspect

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#769]
Hi, thank you for BiT!

I use this in the Terminal to make a backup
```
sudo -i backintime backup --profile-id 1 --config /media/SSD1/Back-in-Time/backintime/AcerP/justme/2/last_snapshot/config
```
If I launch the GUI and add a Folder and/or File and exit the GUI, the next time I make a backup in Terminal, the newly added Folder/File are not included.

If I go back into the GUI and use the "Backup" button, the new Folder/File are included and from then on, all Terminal operations work fine with the newly added Folders/File.

Am I using the terminal command incorrectly? If not, what should it be? 

OR? :)

Thanks

**Comment by Germar** [comment]
Please do not use the config in `last_snapshot` symlink. This is just a backup of your config. There will be some nasty side-effects if you use it like this.
Please use the default place `~/.config/backintime/config` or any other place in your users home that you prefer.

**Comment by FlailAway** [comment]
Thanks, but you should make that clear when creating the backup command for Terminal use. I used the "Help" and it never mentioned where the BiT config file is located so I searched around and that's where I found a copy. I am not a Clairvoyant, nor a Linux expert. :)

I will make the change and see if that fixes the issue.

**Comment by Germar** [comment]
You don't need to be neither a 'Clairvoyant'  nor a 'Linux expert'.
BiT will ask if you want to restore your config if you  don't have one and if you accept it will find the config automatically for you.
