### ISSUE TITLE
Restore does nothing

### ISSUE THREAD

**Issue by blakemcbride** [bit-team/backintime#772]
Hi, 

I am using backintime 1.2.0~alpha16 on a 64 bit LinuxMint system.

I started it up as root.

I am attempting a restore and nothing is happening.  I select the snapshot, I select the directories and/or files, and click restore/restore.  It lists the directories and files I selected.  It doesn't matter how I check the three checkboxes.  I click "Yes" and the restore box disappears and I go back to the main backintime screen.  Nothing happens.

The file /root/.local/share/backintime/restore_.log gets created but has zero bytes.

Appreciate the help!

Blake

**Comment by Germar** [comment]
Please start `backintime-qt --debug` from Terminal run your restore job again and post the output from Terminal

**Comment by blakemcbride** [comment]
# backintime-qt --debug
DEBUG: [common/backintime.py:584 argParse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.2.0~alpha16

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:669 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:670 getConfig] share path: /root/.local/share/backintime
DEBUG: [common/backintime.py:672 getConfig] profiles: 1=Main profile
DEBUG: [common/pluginmanager.py:90 PluginManager.load] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin qt4plugin.py
DEBUG: [common/pluginmanager.py:106 PluginManager.load] Add plugin notifyplugin.py
DEBUG: [common/tools.py:795 keyringSupported] No keyring due to import errror.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:82 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
DEBUG: [common/tools.py:1212 readCrontab] Read 2 lines from users crontab
DEBUG: [common/config.py:1495 Config.removeOldCrontab] Clearing system Back In Time entries
DEBUG: [common/config.py:1528 Config.cronLine] Profile: Main profile | Automatic backup: Disabled
DEBUG: [common/config.py:1479 setupCron] Crontab didn't change. Skip writing.
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 1105, in restoreThis
    rd.exec()
  File "/usr/share/backintime/qt/restoredialog.py", line 95, in exec
    self.config.inhibitCookie = tools.inhibitSuspend(toplevel_xid = self.config.xWindowId, reason = 'restoring')
  File "/usr/share/backintime/common/tools.py", line 1147, in inhibitSuspend
    if not toplevel_xid:
IndexError: sip.voidptr object has an unknown size
DEBUG: [common/tools.py:795 keyringSupported] No keyring due to import errror.
DEBUG: [common/mount.py:73 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:82 Mount.__init__] Call command: /usr/bin/backintime pw-cache start

**Comment by Germar** [comment]
Which window manager do you use? I just double-checked with current Mint Cinnamon 18 without having that troubles. 

You can temporary bypass this bug by adding one line with `return` in `/usr/share/backintime/common/tools.py` below line `1141` so it would look like:
```
def inhibitSuspend(app_id = sys.argv[0],
                    toplevel_xid = None,
                    reason = 'take snapshot',
                    flags = INHIBIT_SUSPENDING | INHIBIT_IDLE):
    """
    Prevent machine to go to suspend or hibernate.
    Returns the inhibit cookie which is used to end the inhibitor.
    """
    return
    if ON_TRAVIS or dbus is None:
    ....
```

**Comment by blakemcbride** [comment]
I am running MATE 1.8.1.  It came with Mint.

**Comment by blakemcbride** [comment]
Also, there is a grammar error on the restore "Questions" popup.

It says:  "Only restore files which does not exist..."

It should say:  "Only restore files which do not exist..."

**Comment by blakemcbride** [comment]
The change you suggested seems to be working.  Thanks!
