### ISSUE TITLE
Run anacron on a custom schedule

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#773]
I have a laptop. When I wake up in the morning, I turn it on for a while, then take it to work. I then get back in the evening. There is not enough time for a backup in the morning, so I can only back up when I get home. Hence, I'd like to schedule backintime to run daily, but only within a certain time period.

For a while now, I've been using the anacron option. i.e.
```
profile1.schedule.mode=25
profile1.schedule.repeatedly.period=1
profile1.schedule.repeatedly.unit=20
```
I then manually modify the crontab to something like
```
*/5 18-20 * * *
```
The problem is that if I use the backintime GUI, it automatically overwrites the crontab. Is there a way to prevent this? Presumably `profile1.schedule.mode=25` causes the rewrite, but is also necessary for `backup-job` to behave appropriately (i.e. only proceed once a day)?

backintime latest (g6c36080f)
Up-to-date Arch Linux

**Comment by Germar** [comment]
There is no way to prevent overwriting your cronjob. But you could instead use a `user-callback` script which will prevent a new snapshot during morning hours (exit code <> 0 will stop a new snapshot)

```
#!/bin/bash
profile_id="$1"
profile_name="$2"
reason="$3"

case $reason in
1) #Backup process begins
    if [ $(date +%H) -gt 6 ] && [ $(date +%H) -lt 18 ]; then
        exit 1
    fi
    ;;
esac
```

**Comment by protist** [comment]
Thanks @Germar, that looks perfect! Thank you again for the prompt and detailed answer!

One related question though… I normally further modify the crontab to check every 5 minutes instead of 15. My laptop is set to sleep after 10 minutes of inactivity, so it's plausible that it misses the cron window. Is there a way to check more frequently?

**Comment by protist** [comment]
Also, I just noticed some errors.
```
ERROR: Exception when trying to run user callback: Permission denied
```
I have `rw` permissions. Does it have to be executable too? (I didn't see anything in the `man` page.)

**Comment by protist** [comment]
Ah, I just tested, and it *does* need to be executable. Would the manual need to be updated?

FWIW, another theoretical problem (probably won't affect me much) is that this user callback will also prevent *manual* backups (i.e. `backintime backup`), not just anacron backups (i.e. `backintime backup-job`).
