### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by wodenhof** [bit-team/backintime#775]
Title says it all -- I have an overall font size of 14 pt adjusted for all programs on my machine. Backintime is displayed with about 8 pt. This is on openSUSE tumbleweed with KDE / Plasma. Any suggestions would be welcome.

**Comment by buhtz** [comment]
Do you want to change the font size or do you want BIT have the system font size?

**Comment by wodenhof** [comment]
Changing arbitrarily would be extra nice but system font size would be okay, too.

**Comment by buhtz** [comment]
I will try to reproduce this but currently I have problems with Suse....

Until it works can you tell me
 - Concrete **version** and **source** (Yast shows me two) of the `backintime-qt` packge.
 - You modified only the font size or other font settings, too?
 - Which one of the fonts-settings you used (default, menu, ...)?
 - Which settings dialog did you used in KDE? The *"system settings" -> "Fonts"* or *"qt settings"*

It would be the best if you provide a screenshot of your font-settings dialog.

**Comment by buhtz** [comment]
![font01](https://user-images.githubusercontent.com/11861496/30715093-7740acee-9f15-11e7-86e9-49d9ec4e7d3a.png)

Please see this screenshot. It is OpenSuse tumbleweed. Left you see a fonts-settings dialog from the system settings. Right you see the font tab of the "qt4 settings" dialog. This is default.
BIT looks ok.

Using the (left) system settings font dialog has absolute no effect on BIT. I think you did it that way?
But when using the (right) qt4-settings dialog to modify the font size it has an effect on BIT.
That is my situation. @wodenhof can you confirm this?

Like a understand it: BIT is Qt and react on qt-settings.
I don't understand to much of KDE. I don't know why they have two differnt font settings dialogs. KDE itself is Qt, isn't it?

Form the viewpoint of BIT everything is fine. Closing this bug.

For KDE: I would recommand you post your problem there and ask if this is a "normal" behaviour or a bug.

**Comment by wodenhof** [comment]
Hi buhtz,
no it wasn't that at all. I did choosing the font-size like you did (right side of your screen shot). It must have been an error in plasma / tumbleweed which is now gone, i.e. font size is 14 pt just like I set it. 
*sigh*
Sorry to bother you, thanks and bye.

**Comment by buhtz** [comment]
No problem you are welcome. Can you "close" the issue by yourself?

@Germar You can close this Issue.
