### ISSUE TITLE
How to transfer 2TB NTFS BackInTime drive image to 3TB Ext4 drive?

### ISSUE THREAD

**Issue by JillyM** [bit-team/backintime#776]
Hello, and thank you for Back In Time!

How should we transfer 2TB NTFS BackInTime drive image to 3TB Ext4 drive? (Using Ubuntu 17.10 64-it desktop version.)

So far, we've only found methods that take many days - and/or expand the image to 10TB.

**Comment by Germar** [comment]
Please take a look at [our FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive)
