### ISSUE TITLE
Data usage for remote backup using ssh 

### ISSUE THREAD

**Issue by justlostintime** [bit-team/backintime#778]
I am trying to do a remote backup of about 500gb, I am having an issue the its taking about 1.5 tb to do that on the first backup. Why is this happening, have i configured something incorrectly?

**Comment by colinl** [comment]
Have you used a backup technique that preserves hard links? If not then you will have a copy of every file for every backup, even if the file has not changed.

**Comment by buhtz** [comment]
Dear @justlostintime is this Issue still relevant for you?

Please provide a detailed description (hardware, filesystem, connection) of your source and destination drive. And try to replicate the problem while running backintime with the `--debug` option on console/bash. Please then poste the output here.

**Comment by justlostintime** [comment]
Yes this is still relevant,
I have a system remotely using backintime with ssh . It appears to use a mapped drive to access the remote backup.
For a 500gb backup it appears to have taken 1.4 terabytes of data to complete.
That's a bit much!
What details do you need?
It is setup per your documented instructions



⁣Brian G ​

**Comment by buhtz** [comment]
Filesystem, type and filesystem of destination-drive (extern USB-drive, NAS, ...). You _connect via SSH_ we know now.

Please start BIT with the `--debug` option and post the complete console output here.

**Comment by buhtzz** [comment]
@justlostintime There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment]
Closing as outdated.
