### ISSUE TITLE
I can't Restore

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#779]
I made some changes to a file today then decided I wanted to roll back to the 12th backup of that file, but BiT Restore will not overwrite the file.

I use this in Terminal to make the Backup
```
sudo -i backintime backup --profile-id 1 --config /home/vest/.config/backintime/config
```
1: 
I started BiT-GUI, selected the backup in the Left-Pane, clicked "Home" in the Middle-Pane then Navigated to the file I wanted in the Right-Pane. Clicked the Restore orange arrow and answered "yes" with the checkbox un-checked.

I get the following, but the file remains unchanged from this morning. Is it me?
```
rsync -rtDHh --links --no-p --no-g --no-o --info=progress2 --no-i-r -R -v --chmod=Du=rwx,Fu=rX,go= "/media/ssd1/Back-in-Time/backintime/Acer14/vest/1/20170612-160354-673/backup/./home/vest/vSens" "/"
building file list ... done
home/vest/
sent 293 bytes  received 53 bytes  692.00 bytes/sec
total size is 43.08K  speedup is 124.51
 
Restore permissions:

Restore permissions: Done
```
2:
I tried using Gedit to open the file in the snaphot but I get "Permission denied" I used to be able to selectively restore by both methods.

Am I doing something wrong?

**Comment by Germar** [comment]
You're running the snapshot with root but try to restore as normal user. Please run `backintime-qt4_polkit --config /home/vest/.config/backintime/config` and try again
