### ISSUE TITLE
require conditions be met before starting backup

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#78]
It would be very nice if it were possible to set some conditions that must be met prior to BiT kicking off a backup.  Maybe it already is possible, and I missed them?  These conditions could simply take the form of scripts that are executed and must return with a specific exit code for BiT to continue, for example an exit code of 0.  This would allow system owners to write scripts for any situations in which they wouldn't want the backup to kick off.  Perhaps they don't want to perform a backup if some process or an other is running.  Or, like in my case, I'd like for the system to be connected via a wired network connection rather than attempt a backup over wireless.

---

Imported from Launchpad using lp2gh.
- date created: 2010-03-15T20:41:38Z
- owner: jcollins
- the launchpad url was https://bugs.launchpad.net/bugs/539260

**Comment by emtiu** [comment]
I would have thought user-callback would make it possible to "abandon" a snapshot, but apparently, that's not the case.

In any case, user-callback is where that functionality belongs, IMHO.

**Comment by emtiu** [comment]
Ah, as I thought: This was implemented in version 1.1.0 (2015). The changelog says:
> Enable user-callback script to cancel a backup by returning a non-zero exit code.

So, whenever some condition is not met, `exit 1` will cause the `user-callback` script to abort the current snapshot.
