### ISSUE TITLE
Split plain-text part of encrypted paths before feeding into encfsctl with 'backintime decode'

### ISSUE THREAD

**Issue by bentolor** [bit-team/backintime#780]
I'm using a SSH/Encrypted Backup with a QNAP TS-412 as backup target. I have 5 backup plans for my regular user (which all work fine) and one for root to backup the system partition which fails.

I receive the following error on every backup:

````
========== Take snapshot (profile 1): Sat Mar 11 04:46:50 2017 ==========

[C] <f..t...... usr/lib/x86_64-linux-gnu/libarchive.so.13.1.2
[C] <f.st...... usr/share/doc/libarchive13/changelog.Debian.gz
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/f4htqBDBKHzvphl0DTN-R3Yb/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/7aOcpG3EC84lIu7yaVkzeFCf/Rse8Gf0sL1BPjgoR24edNOBRIATjOn84v8IULzPIosZ2k1/7CewRY-UYr1XAvH48MgxSgex/aE52uZdgkycMzbifU0EOGhHj" failed: No such file or directory (2)
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/f4htqBDBKHzvphl0DTN-R3Yb/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/7aOcpG3EC84lIu7yaVkzeFCf/Rse8Gf0sL1BPjgoR24edNOBRIATjOn84v8IULzPIosZ2k1/7CewRY-UYr1XAvH48MgxSgex/h66IrqDI0MnTfGu3fZIewbn,jGEJBLSqfwk,wqhRTqS-X0" failed: Address already in use (98)
[C] <f..t...... var/snap/canonical-livepatch/common/last-check

...

[C] <f.st...... var/log/apt/term.log
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/f4htqBDBKHzvphl0DTN-R3Yb/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/S7VC4dt0bqjKXLf5ZiILTG-T/4M-EnO-UlrV0uKxxq45eu7jW/pUBlz9SXeW6L8pGitl-Q,4a7/YyD6nITk1TAhCiWzzvzqYaC0/MC36E5zrhFdCyKAsV75lZa42" failed: No such file or directory (2)
[C] <f..t...... var/lib/update-notifier/dpkg-run-stamp
...
````

I was unable to resolve the mentioned path. 

I assume this is an issue with the QNap target. Obviously rsync fails to create the mentioned files due to .... ?? Path too long? Incompatible rsync?

Any hint how to debug? Thanks!

**Comment by Germar** [comment]
please run `fsck` on your QNAP. Sounds like there are corrupt files...

**Comment by bentolor** [comment]
Thank you Germar for yours support: Neither `fsck` nor _deleting the whole backup target folder_ and starting from scratch resolved my issues. 

The trigger seems to lie somewhere in the source file set, as all other backups (larger in volume) are from the same server and to the same target. The error boils down to:

```
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/h4LsmVoyy1PlwvMb7Idhu3V2/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/7aOcpG3EC84lIu7yaVkzeFCf/Rse8Gf0sL1BPjgoR24edNOBRIATjOn84v8IULzPIosZ2k1/EHr27Nv-536nLQPZ7kWnfGm0/aE52uZdgkycMzbifU0EOGhHj" failed: No such file or directory (2)
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/h4LsmVoyy1PlwvMb7Idhu3V2/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/7aOcpG3EC84lIu7yaVkzeFCf/Rse8Gf0sL1BPjgoR24edNOBRIATjOn84v8IULzPIosZ2k1/EHr27Nv-536nLQPZ7kWnfGm0/h66IrqDI0MnTfGu3fZIewbn,jGEJBLSqfwk,wqhRTqS-X0" failed: Address already in use (98)
[E] Error: rsync: mknod "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM/h4LsmVoyy1PlwvMb7Idhu3V2/FAVlIO4X2UWp2aNb4mXThCZo/fzJxLkk0pvN5a1TsV7XYLmiQ/RAGlyy2vhbEhjU5CZgoZbeMO/S7VC4dt0bqjKXLf5ZiILTG-T/4M-EnO-UlrV0uKxxq45eu7jW/pUBlz9SXeW6L8pGitl-Q,4a7/YyD6nITk1TAhCiWzzvzqYaC0/MC36E5zrhFdCyKAsV75lZa42" failed: No such file or directory (2)
```

This time I realized i need to strip the plain text part of the path before feeding the path into `backintime decode` which returned the path of a socket-file. Excluding all socket files after three rounds solved my issue.

So my basic issue was, that feeding the full path return from the error above into `decode` returns some very cryptic error message saying  `Filename too small to decode`. 

```
root ~# backintime decode "/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM"
INFO: Mountpoint /root/.local/share/backintime/mnt/D7544B31/mountpoint is already mounted
INFO: Mountpoint /root/.local/share/backintime/mnt/6BDCFD9D/mountpoint is already mounted
INFO: Mountpoint /root/.local/share/backintime/mnt/D07D6445/mountpoint is already mounted
18:42:08 (DirNode.cpp:320) decode err: Filename too small to decode
/share/MD0_DATA/Backups/root/hkSKsNqsjwyIGUev3foOKEWr/102kt,gx4fiHFkOQY8YRgVSV/q82nDjf6BgSJbO9Zq5yZ-6CM
INFO: Mountpoint /root/.local/share/backintime/mnt/D07D6445/mountpoint still in use. Keep mounted
INFO: Mountpoint /root/.local/share/backintime/mnt/6BDCFD9D/mountpoint still in use. Keep mounted
INFO: Mountpoint /root/.local/share/backintime/mnt/D7544B31/mountpoint still in use. Keep mounted
```

h3. Proposal 
Maybe

* make the decode logic more robust so it strips/ignores plaintext leading path elements 
* *or* much simpler: Give a hint in the Error message ` (DirNode.cpp:320) decode err: Filename too small to decode. Did you pass only the encrypted part?`

**Comment by Germar** [comment]
That error does come directly from `encfsctl`.  I've no control about it. But I did already some 'magic' to strip paths and other plain text parts from log lines. I'll port this to `backintime decode`, too.

**Comment by emtiu** [comment]
I've been wishing for this, too :) Could be tricky, but very convenient.

**Comment by buhtz** [comment]
Please note that the *Back In Time* project decided to gradually remove EncFS in
the **next five years** due to security reasons and maintenance burden.
It is not yet decided if it will be replaced by an alternative (e.g.
GoCrypt) or if BIT recommend using encrypted file systems (e.g. via LUKS). 

Please see Meta-Issue #1734 to monitor the transition process and join
the discussion.

Closing this ticket based on the comment above. Feel free to reopen
if there are new details or arguments to add. Thank you for your efforts.
If you have any further questions, ideas or encounter any other issues,
please don't hesitate to let us know.

Best regards,

**Comment by bentolor** [comment]
Hi @buhtz ! Thank you for the extensive feedback and explanation. I was _not_ aware about the plan to remove encfs, but i can understand the motivation. Will chip into myself in the Meta-Issue. Thanks for your feedback!
