### ISSUE TITLE
Full system backup fails due to permissions in /var/lib/lxcfs/cgroup/

### ISSUE THREAD

**Issue by demaddis** [bit-team/backintime#782]
I'm trying to backup my Ubuntu 16.04 system running backintime as root, using the exclude rules resulting from "Modify for full system backup". 
Taking a snapshot fails because of missing permissions for ~1000 files in /var/lib/lxcfs/cgroup/[blkio, device, memory]. Example from the snapshot log:
```
[I] Take snapshot (rsync: rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/blkio.reset_stats": Permission denied (13))
[E] Error: rsync: send_files failed to open "/var/lib/lxcfs/cgroup/blkio/blkio.reset_stats": Permission denied (13)
```
Output from `sudo ls -l /var/lib/lxcfs/cgroup/blkio/blkio.reset_stats`:
```
--w------- 1 root root 0 Jun 21 12:22 /var/lib/lxcfs/cgroup/blkio/blkio.reset_stats
```
I've found this bug https://bugs.launchpad.net/ubuntu/+source/lxcfs/+bug/1656309 , but it should already be fixed (my lxcfs version is 2.0.7).
I'm not entirely sure what the purpose of lxcfs is and if I can safely exclude the affected folders. Any help would be appreciated.

**Comment by demaddis** [comment]
For now, I purged lxcfs to work around the issue, since I'm not using LXC containers anyway. I'm still wondering how someone who actually needs lxcfs would go about backing up the system, although this is not specific to backintime.

**Comment by Germar** [comment]
I've no clue about LXC but in my mind it doesn't make sense to backup the fuse-mounted contend of containers. Rather backup the container it self. I bet you can't even restore the containers with only those files from lxcfs

**Comment by saudia-cmuetc** [comment]
For any type of full backup, on an active server, it's recommended that you snapshot the filesystem first, then run your backup script on the contents of the snapshot.  Your filesystem has to be on LVM to use snapshots, though, and have enough free physical extents (un-partitioned space) to shore up the amount of expected changed data during the snapshot window (more for very busy servers, less for not-so-busy servers).  Look here...

http://www.tldp.org/HOWTO/LVM-HOWTO/snapshots_backup.html
