### ISSUE TITLE
Two computers sharing one backup?

### ISSUE THREAD

**Issue by ersv** [bit-team/backintime#789]
Would it be possible to use BIT as a sort of a git version control? 
For instance: 
1. Computer A and B have the same directory tree and this tree is backup:ed to a BIT-server
2. On computer A: edit some files and the run backup to the BIT-server.
3. Turn on computer B. Realise (somehow?) that the local tree is behind the BIT-server tree.
4. On computer B: Update local tree from the BIT-server.

Is this scenario possible?

**Comment by klayman** [comment]
For me it sounds like it's a job for a syncing app, like [syncthing](https://syncthing.net/) - it has support for versioning.

**Comment by Germar** [comment]
I agree with @klayman. There is no collision control if you use BiT like this. You'd have lots of `*.backup.20170706` files from each and every restore which you always have to compare manually to consider which one is the last version
