### ISSUE TITLE
Text in status bar not readable

### ISSUE THREAD

**Issue by OBedford** [bit-team/backintime#791]
When doing a snapshot the status bar at the bottom of the window is not readable (black type on dark blue).

Can I change the background or text color to something different?

System: XUbuntu 16.04.

Regards,
Oliver

**Comment by Germar** [comment]
Nope, sorry. There is currently no way to change colors in BiT. They are defined by your Theme. You could of course change your Theme...

But I'm planing to redesign the progress bar to be a slim line above the status bar instead of laying behind the status bar

**Comment by b3nmore** [comment]
Try to add

export DESKTOP_SESSION="gnome"

after 'export QT_GRAPHICSSYSTEM="native"' in /usr/bin/backintime-qt4. This should pickup your icon-/theme in gtk non-gnome environments like xfce.

**Comment by OBedford** [comment]
The solution suggested by b3nmore does indeed solve the problem for me.

Thanks!
