### ISSUE TITLE
SSHFS mount options

### ISSUE THREAD

**Issue by harrim4n** [bit-team/backintime#792]
SSHFS does not support cache_*_timeout options when linked against libfuse >= 3.0.0.
(These options are used in common/sshtools.py)
This causes the mount to fail when opening backintime.

```
Can't mount sshfs -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=REDACTED -p 22 -o idmap=user -o cache_dir_timeout=2 -o cache_stat_timeout=2 REDACTED REDACTED

fuse: unknown option(s): `-o cache_dir_timeout=2,cache_stat_timeout=2'
```

I noticed this because sshfs on arch linux links against libfuse 3.1.0 since a few days.

**Comment by Germar** [comment]
So it's a libfuse bug, isn't it!?

**Comment by harrim4n** [comment]
Well, it's not really a _bug_, they just removed some mount options, although the documentation of this is lacking. (Only mention of the cache option I could find was in the [3.0.0 changelog of sshfs](https://github.com/libfuse/sshfs/blob/master/ChangeLog.rst), something about it being renamed).
You could of course simply require that backintime uses a sshfs version linked against libfuse2, but I'm not sure if that's enforcable.
Alternatively it might be possible to check which version of sshfs is used? Then the options could be dropped when an incompatible version is detected.

**Comment by Germar** [comment]
They changed from `cache_dir_timeout` to `dcache_dir_timeout`. I don't see any benefit with this but breaking other projects. I'd kindly ask the sshfs folks to add backwards compatibility in this...

**Comment by protist** [comment]
I've just hit this too. FWIW I did the following workaround in the meantime by editing these [two lines](https://github.com/bit-team/backintime/blob/697727b63c593fa1c1f1a94456911d2a408529c8/common/sshtools.py#L144-L145) as follows.
```
--- sshtools.py.orig	2017-07-21 17:46:28.726432917 +1000
+++ sshtools.py	2017-07-21 17:47:46.076184451 +1000
@@ -141,8 +141,8 @@
         if not self.cipher == 'default':
             sshfs.extend(['-o', 'Ciphers=%s' % self.cipher])
         sshfs.extend(['-o', 'idmap=user',
-                      '-o', 'cache_dir_timeout=2',
-                      '-o', 'cache_stat_timeout=2'])
+                      '-o', 'dcache_dir_timeout=2',
+                      '-o', 'dcache_stat_timeout=2'])
 
         sshfs.extend([self.user_host_path, self.currentMountpoint])
         #bugfix: sshfs doesn't mount if locale in LC_ALL is not available on remote host
```
(Presumably that's okay?)

**Comment by Nikratio** [comment]
There is a new *writeback_cache* option. Leaving the `*_timeout` options as-is would make it very confusing because it wouldn't be obvious to which cache they apply. However, I think it should be fine to still accept the old option names (maybe with a warning message).
