### ISSUE TITLE
Move large directory without duplicating backup

### ISSUE THREAD

**Issue by protist** [bit-team/backintime#794]
I'm backing up my entire hard drive with backintime. I have a reasonably large directory (64 GB) on my computer, which I want to move elsewhere. Presumably, when I move this directory, backintime/rsync will not know that the new directory is actually just the old directory moved, and will duplicate it instead of using hard links. Hence, it will use up twice the space.

What is the best way around this? Should I manually delete is and create hard links after the backup? Is there an easier way?

**Comment by Germar** [comment]
I added [a FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-large-directory-in-source-without-duplicating-backup) for this because there was exactly the same question yesterday via mail :laughing:

**Comment by protist** [comment]
Oh brilliant! I promise it's not a sock puppet! 😬

Just tested and that works well. Looks like a fairly simple way to do it too. Thanks for the ultra-quick response as always! Cheers.
