### ISSUE TITLE
Find Backup Subdir sizes?

### ISSUE THREAD

**Issue by benyanke** [bit-team/backintime#795]
I recently made a backup to a corporate network share, and it was far larger than I expected, so I had to delete it.

I was previously using deja dup, which was about 22G with my exclude rules. I _thought_ I configured the same exclude rules, and backintime gave me an archive of about 220 GB. I probably missed a local VM's drive image in my exclude rule, or some such thing.

However, when I started to look around to find what caused it to be so big (the way you would run `du * -sh` on an actual filesystem), I found I couldn't find the size of subdirectories.

Is there any tooling or features to allow you to find the size of various directory trees so I can track down large files in my backups?

**Comment by Germar** [comment]
You can use every ordinary tool like `du` for this. I recommend using `ncdu /path/to/backintime/HOST/USER/ID/last_snapshot/`. Snapshots with Back in Time are just plain files which are hard-linked.

**Comment by benyanke** [comment]
What about for encrypted volumes?

**Comment by Germar** [comment]
Open BiT GUI and browse to the plain files in `/home/USER/.local/share/backintime/mnt/HASH/mountpoint/backintime/HOST/USER/ID/last_snapshot`
