### ISSUE TITLE
Backup Error: ~/.local/share/backintime/mnt/*

### ISSUE THREAD

**Issue by automaticserver** [bit-team/backintime#796]
Hi Folks,

I'm working on BiT for our company. We want to use it as backup-Tool for PCs. We have different OSs: Ubuntu (and similar stuff), Debian, Windows. For now, I want to get it work on Ubuntu and Debian, so only this OSs do matter.

Problem:
We use the "SSH encrypted" mode. BiT is **not** started as root. We exclude ~/.local/share/backintime/mnt/ in the configuration, but we still get a "permission denied"-error when running the backup job.

`[E] Error: rsync: send_files failed to open "/home/user/.local/share/backintime/mnt/6D60B9A2/mountpoint/2XF3Qx1z6p-3S3ZsmXS7l2-M/gwsR6vudeak7R1AXPMGx4ZyE/Qnz8ydVYe9Uqwf4lv3P56h,P": Operation not permitted (1)`

My configuration:
global.use_flock=true
profile1.qt4.last_path=/home/user/Desktop
profile1.qt4.places.SortColumn=1
profile1.qt4.places.SortOrder=0
profile1.qt4.settingsdialog.exclude.SortColumn=1
profile1.qt4.settingsdialog.exclude.SortOrder=0
profile1.qt4.settingsdialog.include.SortColumn=1
profile1.qt4.settingsdialog.include.SortOrder=0
profile1.snapshots.automatic_backup_anacron_period=1
profile1.snapshots.automatic_backup_anacron_unit=10
profile1.snapshots.automatic_backup_day=1
profile1.snapshots.automatic_backup_mode=25
profile1.snapshots.automatic_backup_time=0
profile1.snapshots.automatic_backup_weekday=7
profile1.snapshots.backup_on_restore.enabled=true
profile1.snapshots.bwlimit.enabled=false
profile1.snapshots.bwlimit.value=3000
profile1.snapshots.check_for_changes=true
profile1.snapshots.continue_on_errors=false
profile1.snapshots.copy_links=false
profile1.snapshots.copy_unsafe_links=false
profile1.snapshots.cron.ionice=true
profile1.snapshots.cron.nice=true
profile1.snapshots.cron.redirect_stderr=false
profile1.snapshots.cron.redirect_stdout=true
profile1.snapshots.custom_backup_time=8,12,18,23
profile1.snapshots.dont_remove_named_snapshots=true
profile1.snapshots.exclude.1.value=.gvfs
profile1.snapshots.exclude.10.value=/dev/*
profile1.snapshots.exclude.11.value=/run/*
profile1.snapshots.exclude.12.value=/etc/mtab
profile1.snapshots.exclude.13.value=/var/cache/apt/archives/*.deb
profile1.snapshots.exclude.14.value=lost+found/*
profile1.snapshots.exclude.15.value=/tmp/*
profile1.snapshots.exclude.16.value=/var/tmp/*
profile1.snapshots.exclude.17.value=/var/backups/*
profile1.snapshots.exclude.18.value=.Private
profile1.snapshots.exclude.19.value=/home/user/.vbox_vms
profile1.snapshots.exclude.2.value=.cache/*
profile1.snapshots.exclude.20.value=/home/user/.local/share/akonadi/file_db_data
profile1.snapshots.exclude.21.value=/home/user/.local/share/backintime/*
profile1.snapshots.exclude.3.value=.thumbnails*
profile1.snapshots.exclude.4.value=[Tt]rash*
profile1.snapshots.exclude.5.value=*.backup*
profile1.snapshots.exclude.6.value=*~
profile1.snapshots.exclude.7.value=.dropbox*
profile1.snapshots.exclude.8.value=/proc/*
profile1.snapshots.exclude.9.value=/sys/*
profile1.snapshots.exclude.bysize.enabled=false
profile1.snapshots.exclude.bysize.value=500
profile1.snapshots.exclude.size=21
profile1.snapshots.full_rsync=true
profile1.snapshots.full_rsync.take_snapshot_regardless_of_changes=false
profile1.snapshots.gnu_find_suffix_support=true
profile1.snapshots.include.1.type=0
profile1.snapshots.include.1.value=/home/user
profile1.snapshots.include.size=1
profile1.snapshots.local.nocache=false
profile1.snapshots.local_encfs.path=
profile1.snapshots.log_level=3
profile1.snapshots.min_free_inodes.enabled=true
profile1.snapshots.min_free_inodes.value=2
profile1.snapshots.min_free_space.enabled=true
profile1.snapshots.min_free_space.unit=20
profile1.snapshots.min_free_space.value=10
profile1.snapshots.mode=ssh_encfs
profile1.snapshots.no_on_battery=true
profile1.snapshots.notify.enabled=true
profile1.snapshots.path.host=client
profile1.snapshots.path.profile=1
profile1.snapshots.path.user=user
profile1.snapshots.preserve_acl=false
profile1.snapshots.preserve_xattr=false
profile1.snapshots.remove_old_snapshots.enabled=true
profile1.snapshots.remove_old_snapshots.unit=80
profile1.snapshots.remove_old_snapshots.value=10
profile1.snapshots.rsync_options.enabled=false
profile1.snapshots.rsync_options.value=
profile1.snapshots.smart_remove=true
profile1.snapshots.smart_remove.keep_all=4
profile1.snapshots.smart_remove.keep_one_per_day=10
profile1.snapshots.smart_remove.keep_one_per_month=48
profile1.snapshots.smart_remove.keep_one_per_week=10
profile1.snapshots.smart_remove.run_remote_in_background=false
profile1.snapshots.ssh.cipher=default
profile1.snapshots.ssh.host=backupserver.mydomain.com
profile1.snapshots.ssh.ionice=false
profile1.snapshots.ssh.nice=false
profile1.snapshots.ssh.nocache=false
profile1.snapshots.ssh.path=
profile1.snapshots.ssh.port=22
profile1.snapshots.ssh.prefix.enabled=false
profile1.snapshots.ssh.prefix.value=PATH=/opt/bin:/opt/sbin:\$PATH
profile1.snapshots.ssh.private_key_file=/home/user/.ssh/id_rsa
profile1.snapshots.ssh.user=user
profile1.snapshots.ssh_encfs.password.save=true
profile1.snapshots.ssh_encfs.password.use_cache=true
profile1.snapshots.use_checksum=false
profile1.snapshots.user_backup.ionice=false
profiles.version=1
qt4.last_path=/home/user/Desktop
qt4.main_window.files_view.date_width=100
qt4.main_window.files_view.name_width=100
qt4.main_window.files_view.size_width=100
qt4.main_window.files_view.sort.ascending=true
qt4.main_window.files_view.sort.column=0
qt4.main_window.height=1025
qt4.main_window.main_splitter_left_w=479
qt4.main_window.main_splitter_right_w=1435
qt4.main_window.second_splitter_left_w=472
qt4.main_window.second_splitter_right_w=944
qt4.main_window.width=1920
qt4.main_window.x=0
qt4.main_window.y=0
qt4.show_hidden_files=false

What kind of Information do you need? This test was on Ubuntu 16.04 with backintime-qt4 1.1.12.

Salutations
Aaron

**Comment by automaticserver** [comment]
This same Problem does not happen with 1.1.20 on Ubuntu, but 1.1.20 is not available for Debian...

**Comment by Germar** [comment]
`~/.local/share/backintime/mnt/` is excluded by default. You don't need to exclude it again. But with `SSH encrypted` BiT actually sync the encrypted view of your system which is mounted with `encfs --reverse` in `/home/user/.local/share/backintime/mnt/6D60B9A2/mountpoint/`.

Please use `backintime decode 2XF3Qx1z6p-3S3ZsmXS7l2-M/gwsR6vudeak7R1AXPMGx4ZyE/Qnz8ydVYe9Uqwf4lv3P56h,P`. This will print the plain text of the encrypted path which failed to open. Exclude that path and you should be good to go

**Comment by automaticserver** [comment]
Hi Germar,

First of all, thx for your fast answer. I'll try it.

**Comment by automaticserver** [comment]
First Test worked, thx. I'll close the issue.
