### ISSUE TITLE
question - Error: You can't include a backup sub-folder !

### ISSUE THREAD

**Issue by wolfv6** [bit-team/backintime#797]
This is my first attempt at setting up backintime.
Full snapshot path is: /home/wolfv/backintime/localhost.localdomain/wolfv/1

Many software installs will place configuration files in /home/wolfv/, and I don't want them backed up.
How to back up only these four folders?:

    /home/wolfv/Documents/
    /home/wolfv/scripts/
    /home/wolfv/Pictures/
    /home/wolfv/app_configs/

I added the above folders to the Include tab, but got this error:

    Profile: "1"
    You can't include a backup sub-folder !

I am running backintime on Fedora 26.

**Comment by Germar** [comment]
You need to choose a different destination folder (`Where to save snapshots`). This should be on a separate (maybe external) harddrive. You can't use your home folder for this

**Comment by wolfv6** [comment]
Thanks Germar.  So I created a partition on the local SSD just to save backintime snapshots.
Will backintime mount the partition at startup, or should the operating system do that?

**Comment by Germar** [comment]
If you put the backup on the same drive with your original file you will loose both if the drive fails. Rather put the backup on a separate drive...

**Comment by wolfv6** [comment]
yeah, I know.  I am using hourly backintime for it's time machine feature.
My real backup is daily and saved to the cloud.
