### ISSUE TITLE
USB Drive is not selectable in Backup Location

### ISSUE THREAD

**Issue by acestu** [bit-team/backintime#798]
Hi,

I have a Linux Mint 18.2 setup, I have installed Backintime, I have a 1Terrabyte usb drive mounted but when I open Backintime the backup to location does not show the usb drive, does it have to be formatted in a particular format ?

Thanks
Stuart

**Comment by Germar** [comment]
You'll find your external drive in `/media/USER`. I recommend using `EXT`. But `NTFS` does work, too.

**Comment by acestu** [comment]
Thanks Germar, with it being a gui I was expecting a drive to click on , however as you say you have to type in the path...

**Comment by Germar** [comment]
That's because the native file dialogs doesn't work with BiT. The filedialogs from Qt won't show those links...

**Comment by acestu** [comment]
Thanks for the info Germar , new to Linux

Stuart

**Comment by buhtz** [comment]
#Close
