### ISSUE TITLE
Store files in tar archives instead of files

### ISSUE THREAD

**Issue by codesmaker** [bit-team/backintime#800]
Hi,

I rely on Backintime to backup more than 15 laptops everyday. I'm a happy user in terms of the software itself and the quick support I get here. So, I would like to thank you for all the efforts!

Because Backintime stores the files as they are in the backup location using hard links to have incremental backups, it's really hard to move the the snapshots to an external location, taking into consideration that I'm dealing with millions of files and more than 4TB so far. I was wondering if there is a way to store the backups as tar archives? As you know, it's relatively easier to transfer tars over the Internet than handling all the files themselves.

**Comment by Germar** [comment]
tar does support hard links. So you can manually create a tar archive of your snapshots and move it. But there is no way to make BiT write directly into tar archives, sorry. Take a look at [this FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive)

**Comment by codesmaker** [comment]
Hi Germar,

Thanks a lot for your reply. I'll write a script and test. Is it in your plans to implement such feature to store backups as tar archives?

**Comment by Germar** [comment]
No plans, sorry. BiT is just an intelligent frontend for rsync. And there is no way to use rsync with tar. Also one of BiTs main features is that you can browse snapshots without any tool. Contain them in tars would break this

**Comment by codesmaker** [comment]
Yes, I agree. It's convenient to have the ability to browse through snapshots and restore without needing any extra software. The problem is that when the backups grow in size, one would face a problem to move the snapshots, for example, to an external backup server. It's not an easy decision to choose between BiT and another backup software like Bareos for example. BiT is simple, easy to configure, great support but Bareos, for example on the other hand, stores files differently and because of that, it's much easier to transfer them to other places but not easy to manage and configure. Besides, you can't restore files without the Bareos console.

Again, thanks a lot for your time and support. Keep up the good work.

**Comment by buhtz** [comment]
I would recommand to use the [callback-scripts](https://github.com/bit-team/backintime/wiki/FAQ#user-callback-and-other-plugins) to create your own tar-archives after a snapshot-job is done. Would this help?

@Germar can close this Issue I think.
