### ISSUE TITLE
Issues Restoring from an Encrypted Backup After Reinstalling OS?

### ISSUE THREAD

**Issue by xSarahx** [bit-team/backintime#803]
Basically, I had to reinstall my OS after it became unstable, unfortunately, I think the config file was on the disk when this happened. But I made all of the backups to my external hard drive. Is there any chance to still restore the files to my original computer? I'm using Kubuntu 17.04 for both versions, computer name is the same, as is the username. I made a summation and took a few pictures on my askubuntu question page here: https://askubuntu.com/questions/948071/back-in-time-configuration-missing/948141#948141

**Comment by Germar** [comment]
Hi Sarah,

your backup is encrypted with encfs. You need to mount the encrypted files manually to be able to copy your config.
 
Open a Terminal and type

```
mkdir ~/mnt
encfs "/media/<YOUR_USER>/SENTINEL/Ubuntu Backup" ~/mnt
```
It will ask for your password. Now start BiT. It will ask to restore your config and should find it in `~/mnt` automatically. Restore the config, close BiT and unmount encfs with `fusermount -u ~/mnt`. Finally you can start BiT again and restore all your files.

**Comment by xSarahx** [comment]
It worked perfectly, thank you so much. I was really worried that for a bit :D

**Comment by Germar** [comment]
Glad I could help. This is related to #556
