### ISSUE TITLE
Could backintime show x11 window to use on remote ubuntu server?

### ISSUE THREAD

**Issue by CSGrandeur** [bit-team/backintime#806]
or how to use backintime in ubuntu server system without gui？

no wiki and no document show this.

(I'm using ubuntu server 16.04 x64)

**Comment by Germar** [comment]
Sure, that works perfectly fine here. I use it all the time on my headless server. Just start `ssh -X REMOTE_HOST backintime-qt4`

Also there is a documentation in `man backintime-config`

**Comment by CSGrandeur** [comment]
Thank you. Maybe I just want to know the name of the executable command "backintime-qt4", now I got it~~~^_^
