### ISSUE TITLE
[Feature] Trigger backup when connected to specified wifi network(s)

### ISSUE THREAD

**Issue by madchap** [bit-team/backintime#809]
Hi,

In this case probably better useful for a laptop.

The idea would be that backintime would trigger whenever the laptop is connected to a home network -- or whatever local wifi network -- where the rsync target is located. We should be able to specify several wished networks (i.e. I have 4 distinct sids at home).

I am guessing that should be doable with `nmcli` (provided you use NetworkManager), which most of the desktop distros possibly have now by default?

Thanks for considering,
Cheers.
fred

**Comment by Germar** [comment]
Not exactly the same but [here is user-callback](https://github.com/bit-team/user-callback/blob/master/user-callback.ssid) which will stop new snapshots before they even start if not connected to the correct WLAN

**Comment by madchap** [comment]
@Germar thanks for the pointer. That's useful.

I meant rather as a trigger. For a disconnected laptop, anacron is probably the best existing option. However (and I haven't looked at any code), the connection to a given wifi network could trigger the actual start of the backup (and disconnecting from it possibly pausing/killing the job). Yet, maybe that would require a daemon for BIT or potentially a networkmanager plugin/extension to take the problem the other way.

Such as nmcli command
`nmcli -f ACTIVE,SSID dev wifi list | awk '$1=="yes" {print $2}'` returns your home network, and trigger BIT to start the backup immediately.

I'll look into the user-callback thing, as it's doing half of the things I want ;-)

Cheers,
fred

**Comment by madchap** [comment]
I am closing this for now, as I understand BIT way of working does not allow to do it this way. Thanks for your feedback! and thanks again for the tool :)
