### ISSUE TITLE
New release, when to expect?

### ISSUE THREAD

**Issue by rapgro** [bit-team/backintime#814]
Is this project still alive?
We would like to test a new release with Qt5 in Fedora. Can you provide some offical tarball?

**Comment by Germar** [comment]
It is still alive. But I'm quite busy in the last months so I didn't found that much time for BiT anymore. There are still some bugs and new features that I wish to fix/implement before I release the new 1.2 series which includes the port to Qt5. I can't tell how long it will take, sorry.

**Comment by rapgro** [comment]
#787

**Comment by rnc** [comment]
@Germar  Is there any news on a new release please?

**Comment by moozaad** [comment]
QT4 is now officially being removed from opensuse factory - that means backintime will stop working for Tumbleweed and any future versions of Leap and Suse.

I would love to see a version of this but I can't submit a master, only a release. 
What state is qt5 support in? I looked back through the logs and saw it added back in 2017.

**Comment by Germar** [comment]
I finally released 1.2.0 today :wink:
