### ISSUE TITLE
[Feature Request] Add restore sync

### ISSUE THREAD

**Issue by jean-christophe-manciot** [bit-team/backintime#816]
Ubuntu 17.04
bit 1.1.20

With latest bit release, restoring a folder does 2 things:
- updates modified files/folders
- copies new files/folders

However, nothing is done regarding not-yet existing files/folders in the snapshot.

This means that if we restore a snapshot folder in which some files don't exist yet, over a folder in which those files have been created in the meantime, the latter won't be deleted.
In short, **we can't go back in time before creations** in existing folders.

Hence a **sync restore feature is needed** (right-click -> sync), so that we can fully go back in time where the folder is restored to its fully original state, instead of its original state + everything created in the meantime.

This sync feature should be very easy to implement with rsync.

Example:
snapshot folder performed on 1/1/2016:
foo
  - bar1
  - bar2
  - bar3

same folder 1 year later on 1/1/2017
foo
  - bar1 modified
  - bar2
  - bar3
  - bar4

Consequences when using existing restore feature:
foo:
 - bar1
 - bar2
 - bar3
 - **bar4**

Consequences of using a sync feature (true bit):
foo:
  - bar1
  - bar2
  - bar3

As you can see, the foo **folder returns to its original state, without any additions**.

**Comment by Germar** [comment]
Since `1.1.0` there is an option in Restore menu called `Restore and delete new files`.  With `1.2.0` this will be a checkbox in Restore dialog `Remove newer files in original folder`. Both do exactly what you ask

**Comment by jean-christophe-manciot** [comment]
My feature request was about the "right-click" menu.
I'm glad to hear that it is expected to be implemented in 1.2.0.
