### ISSUE TITLE
Meaning of INFO: Lock in BiT log

### ISSUE THREAD

**Issue by Graveen** [bit-team/backintime#821]
I'm wondering if INFO:Lock - when BiT starts - could involve a perf issue on a SAMBA share. 

If i'm connected and using remotely this SAMBA share, would the periodic BiT run (30mns for me) would be problematic if i write during the 2mns when BiT is running ?

**Comment by Graveen** [comment]
Oh, and i tested this behaviour :) But i just want to be sure what side effect i could have :D

**Comment by buhtz** [comment]
Sorry I dont understand your question. What is INFO:Lock and why do you expect sideeffects?

**Comment by Graveen** [comment]
The BiT log in syslog starts with INFO: Lock, and end with INFO: Unlock.

I would like to know if the "Lock" is a filelock that could forbid me to write to files during the process.

**Comment by buhtz** [comment]
I understand - a bit.

Can you please specifiy "syslog" more detailed. I am using a quite young Debian GNU/Linux unstable. Syslog doesn't esxist here anymore. Now there is systemd with `journalctl`. I can not find "INFO:Lock" in the output of `journalctl` nor in `--debug` output of `backintime-qt`.

Please specificy your operating system, bit-version and give an example output of the log message.

**Comment by buhtz** [comment]
I checked the code. The "Lock" take care about that bit only run one snapshot at the same time. It serialize the snapshots if there are more then one waiting to start.

The files and directories in your snapshot are not handled by bit itself. `rsync` does the snapshot and touch that files. In a very short and not absolute correct description: BIT is more a front-end for `rsync`.

But just to be absolutly sure I would wait for a comment from @Germar about it. I think he can close this Issue.

**Comment by Graveen** [comment]
Thank you ! It should not interfere with my use.

**Comment by Germar** [comment]
Thanks  @buhtz! That's absolute correct. It will only prevent multiple instances taking a snapshot at the same time. BiT doesn't block writing in source while backing up. `rsync` will only report if a file was deleted after scan and before syncing with `file has vanished`. If a file was did not change from last snapshot until rsync scans the source but changed before syncing it will remain as the old file inside the snapshot. If a file has changed from snapshot and changes again after scanning it will sync the current state of the file while syncing.
