### ISSUE TITLE
Could not unlock SSH private key

### ISSUE THREAD

**Issue by cement-head** [bit-team/backintime#825]
Wrong pasword or password not available for cron"

What should I do now?

**Comment by cement-head** [comment]
Any help?  Or am I just not using this correctly?

**Comment by Germar** [comment]
Please open Settings and retype your password. If this still happens please run `backintime --debug backup` from Terminal and post the output

**Comment by cement-head** [comment]
$ backintime --debug
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 24, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 31, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 45, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

**Comment by cement-head** [comment]
Any suggestions?

**Comment by Germar** [comment]
Please make sure you `python3-dbus` package (and all [other dependencies](https://github.com/bit-team/backintime#from-sources)) is installed on your system

**Comment by cement-head** [comment]
No, doesn't work.  This is simply way too complicated and cumbersome.

**Comment by dizid** [comment]
I could also use some advice on the above issue.
It is not clear if i have to fill in a Password and/or a private SSH key.
I pointed the 'private key' already to my .ssh/id_rsa.pub file. (which i just generated and tested).
What password is needed here? root? user?
Thanks, any help appreciated
