### ISSUE TITLE
A DBUS error

### ISSUE THREAD

**Issue by jim-moe** [bit-team/backintime#826]
opensuse 42.2
backintime v1.1.20

BiT seems to work fine regardless of the log entry.

The error message below is in the system log every time BiT runs. The text "/usr/share/backintime/common/backintim" is clipped: the last part should be "/backintime.py". I cannot tell if the error message truncated the text, or if there is a line length limit for some DBUS operations, or something else.

The same thing happened with "/usr/share/backintime/qt4/ser" which should be "/usr/share/backintime/qt4/serviceHelper.py".

2017-10-16T07:00:16-0700 sma-server3 dbus[1383]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.202" (uid=1000 pid=31461 comm="python3 -Es /usr/share/backintime/common/backintim") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.174" (uid=0 pid=28246 comm="/usr/bin/python3 -Es /usr/share/backintime/qt4/ser")

**Comment by cmdtstof** [comment]
hi
i do my backup stuff since long, long with backintime. great!
i use backintime only from the konsole.

since a while i get an not as error marked comment: „dbus.proxies:Introspect error on :1.70:/modules/kwalletd“. i guess it started when i turned off (once more) kwallet.
the backup works fine, also with this „error“. but it would be nice if the note would disappear (be solved!).

thanks a lot


opensuse tumbleweed (latest)

```
Back In Time
Version: 1.1.20

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Inhibit Suspend started. Reason: take snapshot
INFO: Take a new snapshot. Profile: 1 Main profile
INFO: [qt4systrayicon] begin loop
ERROR:dbus.proxies:Introspect error on :1.70:/modules/kwalletd: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
ERROR:dbus.proxies:Introspect error on :1.44:/UdevRules: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.85" (uid=1001 pid=4006 comm="/usr/bin/python3 /usr/share/backintime/qt4/qt4syst") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.44" (uid=0 pid=2785 comm="/usr/bin/python3 -Es /usr/share/backintime/qt4/ser")
ERROR:dbus.proxies:Introspect error on :1.71:/modules/kwalletd: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
...
```

**Comment by jim-moe** [comment]
I have gotten 2 of 3 backups working again. I de-installed xdpyinfo; it is apparently not very important.

The 2 working backups are in user space. The non-working backup is in root space; it just hangs waiting for something, I know not what.

----[ Here is the output from a hung session ]----
Back In Time
Version: 1.1.20
DEBUG: [common/backintime.py:585 getConfig] config file: /root/.config/backintime/config
DEBUG: [common/backintime.py:586 getConfig] profiles: ['1']
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
root:/etc/postfix> DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/snapshots.py:953 Snapshots.has_old_snapshots] Found old snapshots: False
DEBUG: [common/applicationinstance.py:88 ApplicationInstance.check] No process with PID 27254
DEBUG: [common/applicationinstance.py:73 ApplicationInstance.check] No PID file
INFO: [common/snapshots.py:991 Snapshots.take_snapshot] Lock
----[ end ]----

Is there any way to get more info on what BIT is (not) doing?

**Comment by glyndon** [comment]
Looks like I ran into it, too.
Ubuntu Bionic 18.04, BiT 1.2.24
Every time I try to 'OK' the configuration dialog, this happens:

```
ERROR:dbus.proxies:Introspect error on :1.89:/UdevRules: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.119" (uid=0 pid=8058 comm="python3 /usr/share/backintime/qt4/app.py " label="unconfined") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.89" (uid=0 pid=3072 comm="/usr/bin/python3 /usr/share/backintime/qt4/service" label="unconfined")
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1698, in accept
    if self.validate():
  File "/usr/share/backintime/qt4/settingsdialog.py", line 1458, in validate
    if not self.config.setup_cron():
  File "/usr/share/backintime/common/config.py", line 1386, in setup_cron
    self.setupUdev.clean()
  File "/usr/share/backintime/common/tools.py", line 1256, in clean
    self.iface.clean()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.119" (uid=0 pid=8058 comm="python3 /usr/share/backintime/qt4/app.py " label="unconfined") interface="net.launchpad.backintime.serviceHelper.UdevRules" member="clean" error name="(unset)" requested_reply="0" destination=":1.89" (uid=0 pid=3072 comm="/usr/bin/python3 /usr/share/backintime/qt4/service" label="unconfined")
```

**Comment by CatsDans** [comment]
Hello! I have exactly the same error as @glyndon unfortunately. I use Ubuntu Bionic 18, BiT 1.2.1

DEBUG: [common/config.py:291 Config.checkConfig] Check profile Основной профиль
Traceback (most recent call last):
  File "/usr/share/backintime/qt/settingsdialog.py", line 1754, in accept
    if self.validate():
  File "/usr/share/backintime/qt/settingsdialog.py", line 1504, in validate
    if not self.config.setupCron():
  File "/usr/share/backintime/common/config.py", line 1418, in setupCron
    self.setupUdev.clean()
  File "/usr/share/backintime/common/tools.py", line 1765, in clean
    self.iface.clean()
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 1 matched rules; type="method_call", sender=":1.226" (uid=1000 pid=24262 comm="python3 -Es /usr/share/backintime/qt/app.py --debu" label="unconfined") interface="net.launchpad.backintime.serviceHelper.UdevRules" member="clean" error name="(unset)" requested_reply="0" destination=":1.109" (uid=0 pid=8288 comm="/usr/bin/python3 -Es /usr/share/backintime/qt/serv" label="unconfined")

**Comment by CatsDans** [comment]
Reinstall those packages:
qdbus-qt5 (5.9.5-0ubuntu1)
dbus (1.12.2-1ubuntu1.2)
python-dbus (1.2.6-1)
python3-dbus (1.2.6-1)
python3-dbus.mainloop.pyqt5 (5.10.1+dfsg-1ubuntu2)
python3-dbus.mainloop.qt (4.12.1+dfsg-2)
python3-pyqt4 (4.12.1+dfsg-2)
python3-pyqt5 (5.10.1+dfsg-1ubuntu2)
qdbus (4:4.8.7+dfsg-7ubuntu1)

+ BiT . Restart system and now it seems that it works normal...

**Comment by buhtzz** [comment]
Tags: Qt
Close because problem solved.

**Comment by aryoda** [comment]
@emtiu I also vote for closing this issue after a grace period of two more weeks
