### ISSUE TITLE
no qt4systrayicon when using in CLI mode 

### ISSUE THREAD

**Issue by cmdtstof** [bit-team/backintime#831]
improvment!
hi
using backintime in konsole (opensuse tumbleweed, plasma, with some lxde stuff) is starting a
INFO: [qt4systrayicon] begin loop
and ending with 
INFO: [qt4systrayicon] end loop 
where then the prompt only will be showed when pressing <enter>. not nice!

when using backintime via CLI there is no need for an systrayicon.

thanks

**Comment by Germar** [comment]
Sorry but I disagree. Systrayicon is necessary even if started from Terminal.

But with next version `1.2.0` the process which is running the systrayicon in background, will be silent. `begin loop` and `end loop` will only be debug messages.

**Comment by TentativeConvert** [comment]
I have an issue which I think is related to this thread.  

I have a script that depends on BIT closing with `exit code 0`.  This worked fine with BIT 1.0.34.  With BIT 1.1.24, it seems that BIT either doesn’t close at all, or closes with `exit code 1`, even when no error occurs.  I’m guessing that this is related to the `[qt4systrayicon] begin/end loop`.  

I understand that with version `1.2.0` these loop messages will dissappear from the command line.  In the meantime, is there a work-around?  Would it be safe to check for `exit code 0 OR exit code 1` in my script?  I certainly don’t want the script to proceed unless I’m sure that the backup was succesful.

Many thanks!

**Comment by Germar** [comment]
Not related to this thread. 
If it doesn't close at all is there a zombie process?

There is a bug #906 with the exit code. But you can use `user-callback` to run your script. Here is a [sample](https://github.com/bit-team/user-callback/blob/master/user-callback.default). Just put it in `/home/USER/.config/backintime/user-callback` and make it executable.

**Comment by TentativeConvert** [comment]
Thanks a lot!  Yes, you’re right, this bug seems unrelated.  I can confirm that `exit code 1` occurs when no changes are detected in the file system.  Thanks for opening a separate issue!
