### ISSUE TITLE
Create hard links step uses 100%cpu

### ISSUE THREAD

**Issue by rra100** [bit-team/backintime#832]
The last successfull backup was October 28. Yesterday I started a backup but it did stop without backing up .The only warning is "Creating hard links". I use ubuntu 16.04, linux 4.10.0-38-generic and the computer is up  to date. The task mount,ntfs is running 100% of cpu 01. I also attempted to delete an old backup and it stops showing "Creating hard links".

Computer is a Toshiba portégé R835 P81
Processor: Intel® Core™ i5-2435M CPU @ 2.40GHz × 4 
Memory: 7.7 GiB
Graphics: Intel® Sandybridge Mobile 
OS type: 64-bit

external disk
size: 320 GB — 99 GB free (69,0% full)
Partition type: HPFS/NTFS
Partitioning: Master boot record

**Comment by Germar** [comment]
Sounds like there is a filesystem error on your drive. Please check your drive with
```
ntfsfix /dev/sdXX
```
Or even better use a Windows machine with `chkdsk` to fix it.

When done please run `rm ~/.local/share/backintime/worker.*` to remove leftovers from last run and try again.

**Comment by rra100** [comment]
It was indeed a filesystem error (many errors). Thank you, very much. I decide to reformat the external hard disk to udf and the back in time is working fine.
