### ISSUE TITLE
About restauration

### ISSUE THREAD

**Issue by zerealdiouf** [bit-team/backintime#837]
Hi all,
Documentation is light (there's none actualy) about restoration. How doing to restore after install a new OS (after hard crash for exemple)?

thanx for replies

**Comment by Germar** [comment]
Just install BiT and launch it. If you have version `1.1.0` and above it will ask at first start if you want to restore your config and should find your config automatically. You can also reconfigure it exactly like it was before (path and host, user, id settings) or you can copy the old config to `~/.config/backintime/config`. There is a backup of the config in every snapshot.

**Comment by zerealdiouf** [comment]
Oh, it works. Thank you !
