### ISSUE TITLE
Cleaning up snapshots is very slow

### ISSUE THREAD

**Issue by thardeck** [bit-team/backintime#838]
I am using Backintime 1.1.24.

I have setup a cronjob to backup my home directory with some git trees during working time every ten minutes. The backup is done from an SSD to an HDD. It usually takes a few seconds (not even close to a minute) to backup the next snapshot if not much was changed in the home directory.
The first snapshot is around 17 GB, but of course the follow ups are not big.

The problem is that while creating a snapshot takes seconds, cleaning it up takes ages. Cleaning up 84 snapshots after the weekend is already running for nearly three hours and only 57/84 snapshots are cleaned up.

I am using ext4 for the source and target partition.

Manually deleting with `rm` is also very slow. So it might not be a backintime issue but is there a workaround for it? Why is creating so fast and deleting hard links not? Maybe rsync is faster if used properly? Is there a file system which does not have this issue?

My Kernel has the version 4.13.12.

**Comment by Germar** [comment]
Next version `1.2.0` will speed up removing snapshots because it will use rsync to delete old snapshots. 

The old `1.1.XX` versions uses `find /BACKUP/FOLDER -type d -exec chmod u+wx {} +` to make all folders writable again and then `rm -rf /BACKUP/FOLDER`.

**Comment by thardeck** [comment]
That sounds great, many thanks.

**Comment by thardeck** [comment]
@Germar Is there a scheduled date for the 1.2.0 release? It is not that trivil to backport this fix.
