### ISSUE TITLE
Question: Recommended way to run Full-System Backup?

### ISSUE THREAD

**Issue by nottoseethesun** [bit-team/backintime#839]
Should the gui be launched from command line with `su` privileges?  There's no dialog to ask for root privileges, so of course the system files are missed due to lack of permissions.  What's the recommended way?

**Comment by Germar** [comment]
There is an extra application in your starter `Back in Time (root)` which will start BiT as root.

Alternative you can start `backintime-qt4_polkit` from Terminal

**Comment by pydo** [comment]
I'm also trying to perform a full (scheduled) system backup.
I started BiT using `backintime-qt4_polkit` but the application is unable to create a crontab entry after I save my settings.
I get this error in my logs after hitting the `OK` button on the settings dialog.
`ERROR: Failed to get crontab lines: 1, no crontab for root`.

Should I manually add an entry to my `root` user's crontab, something along the lines of:
`0 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null`
or is there a way to fix this issue using the GUI?

Thanks

**Comment by Germar** [comment]
The correct command is `backintime-qt4_polkit` without sudo. The error message does only say it was unable to GET crontab lines. That's only because there was no crontab for root before. It will create a new one...

**Comment by pydo** [comment]
@Germar Thanks for the clarification, so far BiT has been working perfectly. But I have one last question, how can `backintime-qt4_polkit` perform a full system backup with elevated privileges (i.e without sudo or without running it as root) ?

**Comment by Germar** [comment]
It does run as root if you use `backintime-qt4_polkit`. Authentication is done through `pkexec`.
