### ISSUE TITLE
ssh encrypted fails to backup

### ISSUE THREAD

**Issue by kpeeters** [bit-team/backintime#840]
I have successfully created a profile with encryption over ssh, in the sense that an encfs volume gets created on the remote machine. However, trying to make a snapshot then spits out

    INFO: Lock
    ERROR: No matching output from ssh-agent: setenv SSH_AUTH_SOCK /tmp/ssh-zWg8uTdgh1QJ/agent.9070;
    setenv SSH_AGENT_PID 9071;
    echo Agent pid 9071;
     | 
    INFO: Unlock

and the GUI reports 'Working' and then 'Done, no backup needed'. Any suggestions as to what might be going wrong?

**Comment by kpeeters** [comment]
Just to clarify: I have tried this with both the versions of the stable and testing PPAs, and with a clean configuration (started by wiping ~/.config/backintime and ~/.local/share/backintime). I can ssh as the indicated user to the remote host using the ssh key set in the backup profile.

**Comment by Germar** [comment]
Your `ssh-agent` version changed the output so BiT won't recognize it anymore. Which version of `openssh-client` do you use? And which distribution/version?

**Comment by kpeeters** [comment]
$ ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.2, OpenSSL 1.0.2g  1 Mar 2016

on a Mint 18.1 distribution.

**Comment by Germar** [comment]
could you please check with current master?
