### ISSUE TITLE
Search for a file in all backups

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#842]
What is the recommended way to search all backups for the latest/ newest version of a specific file (by filename)?

**Comment by Germar** [comment]
There is no search function. But you can show all versions of a file by highlighting it and press the ['Snapshots' button](https://backintime.readthedocs.io/en/latest/mainwindow.html#files-toolbar). If you don't have the original file anymore you can create a dummy file with the same name (e.g. `touch /path/to/my_important_file.pdf`) and highlight this in BiT

**Comment by kerner1000** [comment]
Works only if I know the absolute path for that file, but anyways, nice tip, thanks!

**Comment by Germar** [comment]
You can use any tool you like to search the snapshots directly e.g. `find` from Terminal or the search bar in your files browser

**Comment by emtiu** [comment]
I'd say that a search feature is out of scope, because all snapshots with all files are openly accessible in the file system, and can be searched with `find` or `grep`.

But we should document this fact somewhere (in the FAQ maybe)?

**Comment by ReinPeacock** [comment]
Search does not appear to function with "Back In Time 1.3.3-3, with both "Catfish File Search 4.16.3" and "PCManFM-Qt 1.2.1" on an external USB drive formatted in NTFS. While *.odt files are present in the backups, a full search of the external drive found no hits for *.odt.

**Comment by aryoda** [comment]
@ReinPeacock 

> Search does not appear to function with "Back In Time 1.3.3-3, with both "Catfish File Search 4.16.3" and "PCManFM-Qt 1.2.1" on an external USB drive formatted in NTFS.

Did you start the search somehow from the BiT GUI or completely independent in the aforementioned tools?

> While *.odt files are present in the backups, a full search of the external drive found no hits for *.odt.

Could you please check this in a console by `cd`ing to the root folder of the `backintime` snapshots and applying this command:

`find . -iname "*.odt"`

If this doesn't work and you are absolutely sure that `.odt` files were included and existed then we have to find the reason for that... (e.g. autoremove feature)

**Comment by ReinPeacock** [comment]
find . -iname "*.odt" worked. Don't know why Catfish and PCManFM failed.
This still is a usability problem, I think.

**Comment by buhtz** [comment]
> Don't know why Catfish and PCManFM failed. This still is a usability problem, I think.

Such tools don't search in the real filesystem. They do search their own index. From time to time they build and refresh their index based on the real filesystem. It might be that the new backuped files are not indexed by that tools at the time you searched them.
