### ISSUE TITLE
Ubuntu 16.04: Screen lock and then frozen on screen unlock ( backintime-qt4_polkit )

### ISSUE THREAD

**Issue by nottoseethesun** [bit-team/backintime#846]
Using `backintime-qt4_polkit` from terminal (not as su or sudo or root), I locked the screen while a snapshot was in progress (to a local disk, not to a usb, etc. disk).  Then when I unlocked the screen, Back in Time was frozen. 

However, after killing Back in Time and restarting, Back in Time did report that it found a usable snapshot to continue with.  I hope that snapshot is truly not corrupted. 

Here's what I am running - it is from the `stable` ppa on the github `README` instructions:

```
$ apt-cache show backintime-qt4
Package: backintime-qt4
Source: backintime
Priority: extra
Section: utils
Installed-Size: 395
Maintainer: BIT Team <bit-team@lists.launchpad.net>
Architecture: all
Version: 1.1.24~xenial

$ apt-cache show backintime-common
Package: backintime-common
Source: backintime
Priority: extra
Section: utils
Installed-Size: 1278
Maintainer: BIT Team <bit-team@lists.launchpad.net>
Architecture: all
Version: 1.1.24~xenial
Recommends: powermgmt-base, sshfs, encfs
Replaces: backintime

$ apt-cache show backintime-notify
Package: backintime-notify
Source: backintime
Priority: extra
Section: oldlibs
Installed-Size: 8
Maintainer: BIT Team <bit-team@lists.launchpad.net>
Architecture: all
Version: 1.1.24~xenial
Depends: backintime-qt4

```

**Comment by Germar** [comment]
`rsync` will resync the snapshot if it says it can continue a previous snapshot. So even if it was corrupt it will get fixed during continuing.

If it freeze again please run `backintime-qt4_polkit --debug` from Terminal and post the output after the freeze.

**Comment by buhtzz** [comment]
@nottoseethesun There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment]
Closing as outdated.
