### ISSUE TITLE
Is it possible to merge different backups into one?

### ISSUE THREAD

**Issue by GvThun** [bit-team/backintime#847]
I set up some time ago a new disk and began filling it with BIT backups. 
On a different disk there are BIT backups of the same directories that are older and some of them time overlap with the ones on the new disk.
So I wonder if I could copy the older directories into appropriate directory of the new disk by taking care of the directory structure as there is  machine name, username, backup number. etc. 
Thanks to all.

**Comment by Germar** [comment]
You can move the old snapshots into the new destination. But to make them incremental you'd need to use a tool like [fslint](http://www.pixelbeat.org/fslint/)

**Comment by GvThun** [comment]
Thanks to Germar
Guido
