### ISSUE TITLE
Backintime starts two instances: Gnome and QT4

### ISSUE THREAD

**Issue by Coshibu** [bit-team/backintime#848]
I setup backintime on my machine to backup as a normal user to a USB hardrive. All worked fine for a few days. Then I unplugged the USB hardrive and replugged it on a different USB port (on the same machine). Backintime then would start to run to instances. One gnome instance and one qt4 instance. Both are running in parallel and snapshots keep failing.

**Comment by buhtzz** [comment]
@Coshibu There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Crazy story. But I assume this isn't reproducible anymore.

Tag: Feedback

**Comment by emtiu** [comment]
There are no longer separate Gnome/Qt GUIs, so this couldn't happen anymore.
