### ISSUE TITLE
Tray icon missing under Elementary OS Loki

### ISSUE THREAD

**Issue by Aurelien-** [bit-team/backintime#849]
Hello,

When doing the backup, at some point a systray icon is missing, instead the image-missing icon is shown (see picture attached).
The BackInTime default icon (grey background with down arrow) is displayed at the beginning. Then during the backup the icon change to the missing one (not sure if it is related when the files copy begins).

I'am using Elementary OS Loki and BackInTime 1.1.24.

[image-missing.pdf](https://github.com/bit-team/backintime/files/1576040/image-missing.pdf)

**Comment by buhtz** [comment]
You should report that to the package maintainer from Elementary OS.

**Comment by Germar** [comment]
That's a problem on how I solved the progress bar in the tray icon. It will load a different icon as soon as it prints the progress bar. Should be fixed as soon as we have a proper BiT icon which will have a progress indicator by it self. I already have an idea for that...

**Comment by Germar** [comment]
related to #215

**Comment by emtiu** [comment]
Closing since the affected code has changed with 1.2.0:
https://github.com/bit-team/backintime/blob/ab24e105e618b8b1f5d779e0d4713a6296ca46d3/CHANGES#L41
… and Elementary OS Loki is long obsolete.
