### ISSUE TITLE
single click opens files in backups

### ISSUE THREAD

**Issue by scytho** [bit-team/backintime#852]
I found BIT opening files when clicking on them. I can’t remember it did when I started using BIT. The problem with this is that I have raw files of photographs and opening those triggers RawTherapee to start. RawTherapee has the very annoying habit to save a profile file for the raw file when being closed. It does write that profile file into the backup, even when I start BIT as root. I can’t find any settings in RawTherapee, so I can’t stop this, but even if, I think BIT shouldn’t open files on a single click in the first place, or should it? That’s the file browsers’ job.

**Comment by Germar** [comment]
BiT does open a file with its default application only on a double-click action. If they open on single-click this must be a configuration in your system. Some desktop environments threat single-clicks as double-clicks...

**Comment by scytho** [comment]
I’m using Mate and haven’t configured anything to open things on a single-click. BIT is the only app that does. There’s nothing about it in the BIT preferences. There are some KDE components/packages installed because of other apps needing them. Maybe those packages make BIT use the default behaviour of KDE?

**Comment by Germar** [comment]
Which version and package of BiT did you install? Please run `dpkg -l | grep backintime` in Terminal and post the output.

There was a Gnome and a KDE user-interface in old versions of BiT. If you have `backintime-kde` please remove it and install `backintime-gnome` instead.

New BiT versions only come with one Qt user-interface `backintime-qt4`

**Comment by scytho** [comment]
```
dpkg -l | grep backintime
ii  backintime-common  1.1.12-1  all  simple backup/snapshot system (common files)
ii  backintime-qt4     1.1.12-1  all  simple backup/snapshot system (graphical interface)
```
And I was hoping we had it&#160;…

**Comment by scytho** [comment]
I’ve added your ppa and updated to 1.1.24, BIT still opens files on a single-click. Any other ideas?

**Comment by scytho** [comment]
BIT didn’t open files upon single click on a newly installed system running only Mate. Recently I installed KDE alongside, now BIT opens files and folders on single click under Mate. My distro is still shipping BIT 1.1.12. Is that fixed in newer releases, or do I have to change any settings outside BIT?
