### ISSUE TITLE
Will You Create a Guix Package for Back In Time?

### ISSUE THREAD

**Issue by davidpgil** [bit-team/backintime#853]
I noticed you don't have a Guix package ... I think you should definitely be on there! Here is a list of their current available packages:

https://www.gnu.org/software/guix/packages/

The rest of the links have more info about Guix.

**Comment by buhtz** [comment]
Please give us short informations about __what__ guix is and what would be the benefit of having such pacakges for backinintime.

**Comment by davidpgil** [comment]
Here is a a link that describes the main features on one screenful: [Guix Features](https://www.gnu.org/software/guix/manual/html_node/Features.html#Features)

I personally like it because it is package manager that can be easily added to any distro. However, I know there are benefits regardign being able to easily roll back packagaes because the package manager keeps track of the state. Also makes it easy to handle installing multiple versions of the same software. The link has more info.

**Comment by buhtz** [comment]
I am not the maintainer here or in any distro. ;) But...

You should do invest more energy in convincing me and the maintainer.

Why should I use different package manager beside the one I use with my distro (e.g. apt)?

How does guix handle dependencies on different distros?

For a guix package we need a package maintainer.

**Comment by davidpgil** [comment]
My main reason, for using Guix is the following. I use Trisquel GNU/Linux as my main distro. In that distro, packages are often outdated. However, the repository tries its best to only include Libre/Free software. It is my understanding, although I am not 100% sure, that Guix also only has Libre/Free software. So, in my use case, I can lead my package installations with Guix, which often has the latest software. Where there are missing packages on Guix, I go back to the Trisquel repository.

Regarding Backintime, I try to avoid using PPAs and DEB installs because I cannot ensure (to my satisfaction) they are free software based off their source. Guix also allows building a software from source from within the package manager which is very nice although probably impractical to install every software that way.

Unfortunately, I don't know whats involved with package maintanance and other technicalities because of my lack of experience in that area. I suppose I could figure it out, but I may need help with things.

You asked me to give you a brief description of what Guix is, but now you have tricked me into explaining with "more energy" ;)

**Comment by Germar** [comment]
Guix sounds good. But to be honest, I don't have time to become a package maintainer for any distro/package management. I barely find time to provide support nor add new features for BiT anymore.

So if you want to see BiT on Guix you need to either find a Guix Package Maintainer who is willing to do this job (have a look into their forum) or become a Package Maintainer by your self. Sorry
