### ISSUE TITLE
"Run 'rsync' with 'nocache'" is confusing

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [bit-team/backintime#857]
Hi, it took me a while (and a look at the source code) to figure out why the option `Run 'rsync' with 'nocache'` was disabled (as in greyed out, unavailable). I thought it was a `rsync` option. Specially given that the previous similar options to run `rsync` though an external command to change its behaviour is phrased differently (`Run 'nice'` and `Run 'ionice'`), I found it confusing (or at least inconsistent).

Also having a tooltip on how one can enable those options (like "Make sure you have tool XXX installed to enable this command) would be helpful.

**Comment by jdrch** [comment]
For those who are wondering, you have to install `nocache` from your distro's repos for that option to work.
