### ISSUE TITLE
[feature] Pause all scheduled backups

### ISSUE THREAD

**Issue by CristianCantoro** [bit-team/backintime#861]
Hi,

I would like to know it there is a way to prevent BiT to start scheduled backups. Sometimes one may want to avoid starting any backup and so It would be nice to be able to have a switch that pauses all scheduled  backups.

**Comment by Germar** [comment]
There is no builtin feature like this. Version 1.2.0 will be able to pause and stop a already running snapshot. But nothing like your request.
But you can add this with the `user-callback` script. For example you could return `exit 1` if the file `/home/USER/Desktop/no_backup` exist. Then you just need to create the `no_backup` file on your desktop if you don't want backups and delete it to enable backups again

```
#!/bin/bash
#    Copyright (c) 2012-2015 Germar Reitze
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#Script should return 0 if everything is alright. Returncode !0 will cancle
#the running snapshot (BIT version >1.1.0).

profile_id="$1"
profile_name="$2"
reason="$3"

case $reason in
    1) #Backup process begins
        if [ -a "/home/USER/Desktop/no_backup" ]; then
            exit 1
        fi
;;
esac
```

**Comment by CristianCantoro** [comment]
Hi,

thanks for the prompt answer. I think this is a nice solution.
In which point of the configuration of BiT should I specify where the `user-callback` script resides? Should I add this manually to all the configuration that I wish to stop?

Thank you.

C

**Comment by Germar** [comment]
You just need to place the `user-callback` inside `/home/USER/.config/backintime/` and make it executable.

**Comment by CristianCantoro** [comment]
Thank you, that worked perfectly.
