### ISSUE TITLE
How to configure retentation or max amount of file versions

### ISSUE THREAD

**Issue by tjakie** [bit-team/backintime#862]
I like the simple approach of the software of just using rsync.<3

But I have a dataset that's approx 8tb large. that needs to go to a offsite NAS. I think that works good.

But what about the retention or max amount of file versions or something like that? I couldn't find it in the configuration. Or is that under the section Smart Remove. If so where can I find the explanation about that part and what do all the parameters mean?:)

Thanks for writing this application...:) _crashplan was being mean to me the last months... especially with the offsite backup.. (SO SLOW)_

**Comment by Germar** [comment]
Correct. For this BiT uses `Smart Remove`. Like the parameters say it will keep one snapshot per day/week/month for the configured time. All other snapshots will be deleted. Take a look at the FAQ [How does snapshots with hard-links work?](https://github.com/bit-team/backintime/wiki/FAQ#id23)

To get the full speed you should activate `Full rsync mode` in Options if you're on version 1.1.X
Starting with 1.2.0 this will be the default...

**Comment by tjakie** [comment]
Thanks, I get it now;) the inode part was a little bit tldr when your just new to this application..

Btw. Is there a way how I can help to improve the application I am working as a webdeveloper and would love to help you guys with a project like this;) please let me know!

**Comment by tjakie** [comment]
Btw. I also saw that if the log file is big the interface crashes.. :|

**Comment by Germar** [comment]
The crashes with big log files should be fixed by now!? Can you please create a new Issue and add the Tracelog?
The log is just a bziped text file. You can show it with every other tool, too.

Help is very welcome! I don't have much time anymore which I could spend on BiT. But there is still so much to do for the next 1.2 release. Would you like to code? Or do you prefer working on the documentation?

**Comment by buhtzz** [comment]
@tjakie There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

Seems to be fixed but without user feedback. Could be closed.

**Comment by emtiu** [comment]
Closing as outdated.
