### ISSUE TITLE
User callback not executed

### ISSUE THREAD

**Issue by uhausbrand** [bit-team/backintime#866]
Hi,
i have the following problem with the user callbacks using the user-callback.multiple-scripts [https://github.com/bit-team/user-callback/blob/master/user-callback.multiple-scripts](url):

Somehow the ls command can't read the sub directory user-callback.d but if i execute the command it works.

The syslog from the backup run:
>Jan 31 08:55:15 HOST backintime (USERNAME/3): INFO: Lock
Jan 31 08:55:15 HOST backintime (USERNAME/3): INFO: Inhibit Suspend started. Reason: take snapshot
Jan 31 08:55:15 HOST backintime (USERNAME/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory'
Jan 31 08:55:15 HOST backintime (USERNAME/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory'
Jan 31 08:55:15 HOST backintime (USERNAME/3): INFO: Take a new snapshot. Profile: 3 full_backup
Jan 31 08:55:15 HOST backintime (USERNAME/3): INFO: Call rsync to take the snapshot
Jan 31 08:55:15 HOST backintime (USERNAME/3): INFO: [qt4systrayicon] begin loop
Jan 31 08:55:16 HOST backintime (USERNAME/3): INFO: Save config file
Jan 31 08:55:16 HOST backintime (USERNAME/3): INFO: Create info file
Jan 31 08:55:16 HOST backintime (USERNAME/3): INFO: Remove backups older than: 20170101-000000
Jan 31 08:55:16 HOST backintime (USERNAME/3): INFO: Keep min free disk space: 1024 MiB
Jan 31 08:55:16 HOST backintime (USERNAME/3): INFO: Keep min 2% free inodes
Jan 31 08:55:18 HOST backintime (USERNAME/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory'
Jan 31 08:55:18 HOST backintime message repeated 2 times: [ (USERNAME/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory']
Jan 31 08:55:18 HOST backintime (USERNAME/3): INFO: Unlock
Jan 31 08:55:18 HOST backintime (USERNAME/3): INFO: Release inhibit Suspend
Jan 31 08:55:18 HOST backintime (USERNAME/3): INFO: [qt4systrayicon] end loop

The output of ls -la for the config directory:
>USERNAME@HOST ~/.config/backintime $ ll
total 32
drwxr-xr-x  3 USERNAME USERNAME  4096 Jan 31 11:44 ./
drwxr-xr-x 31 USERNAME USERNAME  4096 Jan 31 08:14 ../
-rw-r--r--  1 USERNAME USERNAME 12691 Jan 31 12:02 config
-rwxr-xr-x  1 USERNAME USERNAME  1051 Jan 31 11:44 user-callback*
drwxrwxr-x  2 USERNAME USERNAME  4096 Jan 25 10:47 user-callback.d/

The scripts in the directory are working. (using one of the scripts as user-callback works)

UPDATE:
I've found the problem. The user callback is executed in the context of the users home directory, not in the context of the config directory. This results in the error that the directory user-callback.d not exists (which resides in the .config/backintime/ directory).

>Feb  1 08:21:22 HOST backintime (USER/3): INFO: Lock
Feb  1 08:21:22 HOST backintime (USER/3): INFO: Inhibit Suspend started. Reason: take snapshot
Feb  1 08:21:22 HOST USER: execute user-callback 3 full_backup 7 USER /home/USER
Feb  1 08:21:22 HOST backintime (USER/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory'
Feb  1 08:21:22 HOST USER: execute user-callback 3 full_backup 1 USER /home/USER
Feb  1 08:21:22 HOST backintime (USER/3): ERROR: user-callback returned 'ls: cannot access 'user-callback.d': No such file or directory'
Feb  1 08:21:22 HOST backintime (USER/3): INFO: Take a new snapshot. Profile: 3 full_backup
Feb  1 08:21:22 HOST backintime (USER/3): INFO: Call rsync to take the snapshot
Feb  1 08:21:23 HOST backintime (USER/3): INFO: [qt4systrayicon] begin loop
Feb  1 08:21:24 HOST backintime (USER/3): INFO: Save config file
Feb  1 08:21:24 HOST backintime (USER/3): INFO: Create info file

I'm not sure what the correct solution is in that case? Somehow it could be that the user-callback.d should reside in the home directory too or anyone using this script should change this. (it is just an example script provided)
Is it the expected behavior that the user callback will be executed in the context of the home dir?

**Comment by uhausbrand** [comment]
Additional info:
If the backup process gets started on boot/reboot, the working directory is / . So it would be nice to get the location of the user callback script as a config variable or parameter.

**Comment by buhtzz** [comment]
@uhausbrand There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by uhausbrand** [comment]
@buhtzz Hi, as I am not using back in time anymore, the issue is not relevant for me anymore.
