### ISSUE TITLE
Restore never shows as done

### ISSUE THREAD

**Issue by blakemcbride** [bit-team/backintime#869]
Greetings,

I am using backintime 1.2.0~alpha17 on a 64 bit Linux box.  I restored a directory seemingly correctly but the bottom message says:

99% | Sent: 7.90G | Speed 18.10MB/s | Working:

It is stuck there.  My impression is that it finished completely but the message hasn't been updated.

The popup box that showed the details said something like "Permissions restore complete".  I am not sure because I thought if I closed the box the other message would go to 100% or Done.

Thanks!

**Comment by buhtzz** [comment]
@blakemcbride There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Seems to be a "duplicate" of  #1275 .

Tag: Feedback, GUI
Maybe close as duplicate.

**Comment by emtiu** [comment]
Closing in favor of #1275.
