### ISSUE TITLE
Backup management

### ISSUE THREAD

**Issue by paul1149** [bit-team/backintime#870]
Hi,

Started using BackInTime recently, and really like it. Thanks for a great prog.

In addition to my main /home backup, I'm considering using BIT to back up some relatively static storage folders. These contain things like movies, etc. I would need only two backups - the base one, and one that is up to date. This is important because of the size of the folders.

I don't see any way to achieve this under AutoRemove, which is the only place I see to configure backup management.

Is there a way to achieve this? 

Thanks.

**Comment by Germar** [comment]
New snapshots only use space for the changed files. Static files that didn't change don't use any additional space. So you can keep as much snapshots as you like even with huge folders.

**Comment by paul1149** [comment]
Ok, thanks much. I had overlooked that. As I thought about this, I determined that a sync prog would be best for my task, so I can delete files from the original backup by mirroring. But for the /home directory, this prog rules.

Thanks,
Paul

**Comment by Germar** [comment]
Just remember that sync is no backup. If you delete a file by accident it will be gone for good in the synced folder, too. With BiT you will still have a snapshot from which you can restore...

Take a look [at this FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-does-snapshots-with-hard-links-work) about how backups with snapshots work in BiT

**Comment by paul1149** [comment]
Yes, that is a bit confusing at first glance, but very interesting. Bottom line is I like the way BIT intelligently saves space. At some point I would like to read up and understand it better. Meanwhile, great prog! And yes, I am aware of the risks of mirroring.
