### ISSUE TITLE
Retroactively add snapshot from a different backup medium

### ISSUE THREAD

**Issue by akki42** [bit-team/backintime#872]
Hi there!

By now, I've been using backintime for a number of years - great tool!

For instance, I have regularly taken snapshots of my documents directory (let's say: /home/akki42/documents ) to a remote server (remote path: /backintime ) since 2012.

Recently, I've "rediscovered" old backups (simple file copies, not created by backintime) on an external hard drive (mounted on my local pc for example to /mnt/hdd ). These include older copies of my documents directory (e.g. at /mnt/hdd/backup/2009/home/akki42/documents and /mnt/hdd/backup/2011/home/akki42/documents ).

I would like to somehow "add" these older states of my documents directory to my backintime snapshots, thus extending the backintime "timeline" back to 2009. (I suppose there is a 90%+ match between the 2009 and 2011 files and my oldest existing snapshot from 2012.)

Any ideas on how to best proceed? Many thanks!

**Comment by buhtzz** [comment]
@akki42 I'm sorry this isn't possible without hacking something.

Close as out of scope.

**Comment by emtiu** [comment]
I have to agree. There's no feature or documented way to do this. You might try, and it should be possible theoretically, but there's a good chance you'll break something. Still, I understand it would be very satisfying ;)
