### ISSUE TITLE
Improve platform independence (was: Backintime on OSX)

### ISSUE THREAD

**Issue by myzinsky** [bit-team/backintime#873]
Is there a realistic chance that Backintime can run on OSX? Time Machine does not work properly for me so I consider backintime as a good alternative.

**Comment by Germar** [comment]
As BiT is written in Python which is platform independent it would be possible to port BiT to OSX or Windows. But BiT uses lots of Linux specific code so it won't run out of the box. It would be quite some work...

**Comment by myzinsky** [comment]
Yeah, I realised that there are many calls to /proc which does not exists in macOS. I just wrote a simple rsync script by myself. However, platform independence could be a feature request :)

**Comment by buhtz** [comment]
I assume OS X does have an rsync implementation. All other things can be done.

But we need an OS X person in the team to realize this. None of use OS X. But if anyone is out there we will support.

But I also wonder if there is a need for BIT on OS X. Don't they have something like a "timemachine" as a backup solution?

**Comment by EureDudeheit** [comment]
Yes, on Mac OS they have time machine. As was mentioned before there is lots of Linux specific code.
How are the chances to get BiT running native under Windows?
My current workaround is to install BiT in a Live-USB-system, boot the machine from the USB-drive and perform the backups. However, this is very inconvenient.

**Comment by aryoda** [comment]
> How are the chances to get BiT running native under Windows?

I'd say chances for getting BiT running on Windows with **all** features working is far beyond the capacity we have to port the code (even when using `[cygwin](https://www.cygwin.com/)`:

- Scheduling in BiT is done with `cron`
- BiT uses DBus IPC communication
- BiT uses POSIX signal handling to communicate with processes
- Keyrings are used to store credentials (Windows uses a similar concept called "Credential store" though)
- ...

Perhaps Microsoft's "Linux subsystem for Windows" may be mature enough for this in the future.

For OS X is see similar challenges (efforts) though it is at least a Unix system more similar to Linux than Windows.

**Comment by EureDudeheit** [comment]
Thanks for the explanation! I think that would be too much effort after all...
For those who are also interested in Windows-use, a short summary of the workarounds i tried so far*:

- I already tried Linux subsystem for Windows -> there were some issues with the read permissions. I think it cannot "pass-through" the permissions.
- Also read permission issues when i use cygwin with handwritten rsync-scripts.
- Sharing the C:\ in the Network and mounting it in the Linux machine to perform the backup with BiT has a massive lack in transmission speed and also issues with read permissions.**

- **The easiest** workaround is: Install Linux (dualboot) or use a pendrive with BiT on it.



*This is a little off-topic, i wanted to share my experience to prevent others from wasting their time. Maybe this could be added in the FAQ?
**My private network at home, i don't do that at work...

**Comment by aryoda** [comment]
> * **The easiest** workaround is: Install Linux (dualboot) or use a pendrive with BiT on it.

And it looks like NTFS does support hardlinks to BiT (better: `rsync`) can save disk space on the backup target:

https://github.com/bit-team/backintime/issues/1212#issuecomment-1742837937

> Maybe this could be added in the FAQ?

Good idea (task assigned to myself :-)

**Comment by buhtz** [comment]
The topic is relevant but to broad. Using all platform independence features of Python (e.g. `pathlib`) will be realized step by step but not finished early. I would like to close this issue because of this.

But I also encourage Mac (and other platform) users to report specific problems and suggest specific solutions in separate Issues tickets.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen. Thank you for your efforts. If you have
any further questions, ideas or encounter any other issues, please
don't hesitate to let us know.

Best regards,
