### ISSUE TITLE
Enable encryption, confirm password dialog box not generated

### ISSUE THREAD

**Issue by tneo** [bit-team/backintime#876]
I have a profile and I wanted to enable **local encryption** of the back-ups. When you go through the GUI you have to set the password and upon submitting a pop-up is shown to create the directory for you. Then the GUI stalls and renders BiT useless.

When I open the application through the terminal and go through the same process upon submitting the password and creation of the directory in the terminal is asked to confirm the password. Pasting my password there again continues the process of creating the local encrypted volume.

Expected behavior: User gets either 1) a dialog box to insert password for confirmation or 2) see 2 input fields for the password to be used.

In case it matters: running openSUSE Tumbleweed KDE.

**Comment by buhtzz** [comment]
@tneo There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, GUI, SSH/Password/Encryption

**Comment by tneo** [comment]
This issue is no longer relevant.
