### ISSUE TITLE
Back In Time, sending an email on Failure 

### ISSUE THREAD

**Issue by DanielMarchand** [bit-team/backintime#878]
Hi,

I was interested in having BIT send me an email in case there were any failures. I think this was mentioned before:

https://github.com/bit-team/backintime/issues/193

I'm OK with handling this with a wrapper script but I'm only used to using the GUI at this point. Any guidance on how I could script an email aspect in?

**Comment by colinl** [comment]
I think the status indicates if there is a failure, so you can use a Status node to pick that up. The reason for #193 is that there is no indication of _successful_ completion.

**Comment by DanielMarchand** [comment]
Hi Back in Time People,

I have the current crontab setup shown below. I'm confused because the system is running back in time successfully every day, but no email shows up in my inbox. I know I have the email system set up correctly because the second message '"This message appears in my inbox"' does show up in my inbox every day. 

Can anyone advise me as to what I can do to get back in time to email me its success/failure directly? 

```
#Back In Time system entry, this will be edited by the gui:
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO="XXXXX@gmail.com"
# old versions to test the email
#*/1 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job >/dev/null 2> mail -s 'cron error' -r XXXX XXXXXX@gmail.com
#0 1 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job > mail -s 'cron success' -r XXXXX XXXXXXX@gmail.com 2> mail -s 'cron fail' -r daniel daniel.marchand@gmail.com
#*/1 * * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job > mail -s 'cron success' -r daniel daniel.marchand@gmail.com 2> mail -s 'cron fail' -r daniel daniel.marchand@gmail.com

# my own testing
#*/1 * * * * echo "test v7"
#Back In Time system entry, this will be edited by the gui:
0 1 * * * /usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime backup-job
0 1 * * * echo "This message appears in my inbox"
```

**Comment by Germar** [comment]
`backup-job` forks into background and exit the main process. You'd need to use `/usr/bin/backintime backup` instead. Also you don't need to pipe the output into mail. Just remove `>/dev/null 2>&1` and cron will automatically send all output to your default mail address.

**Comment by DanielMarchand** [comment]
Great that answers my question thanks!
