### ISSUE TITLE
Recommended folders to backup

### ISSUE THREAD

**Issue by Shuunen** [bit-team/backintime#882]
Hi there,

First thanks for your tool, I just tried it and working well on my freshly installed Linux Mint :+1: 

But I have to admit that on the include tab, I was wondering "what should I include ?"

For sure I put my `/home/johndoe` folder, but after that, no clue... I'm using Linux for years but i'm no expert enough to know which folder is useful to backup or not.

I think this tab could have a "Add recommended" button that will pre-fill common folders to backup, what do you think ?

Cheers !

**Comment by Germar** [comment]
If you just use Linux as a regular desktop user you should be fine with only `/home/johndoe`. You could create a second snapshot running as root which backup `/etc` and you can use a `user-callback` to [backup your installed package selection](https://github.com/bit-team/backintime/wiki/FAQ#how-to-backup-debian-ubuntu-package-selection).

**Comment by Shuunen** [comment]
thanks @Germar , what about the "Add recommended" button that will pre-fill common folders to backup ?

**Comment by buhtz** [comment]
I don't get the use case. If someone don't know what to backup then why does someone use BIT?
It is a rare case. No need for such a button. There is a lot of material in the web and literature about backup strategies.

**Comment by Shuunen** [comment]
> I don't get the use case. If someone don't know what to backup then why does someone use BIT?

Because there is people that are beginners and want to backup.

Also the concept of suggestions is not only for beginners but also to facilitate any user experience, for example I use FreeFileSync to synchronize files & folders and the software come with some patterns ignored by default, for sure it's not mandatory to use the software, but it's more handful to have this kind of things out of the box

**Comment by buhtz** [comment]
Dear @Shuunen ,
my apologize I still don't see a use case but I have an proposal.

We could add a help text (Wiki, FAQ, user manual, manpage, ???, etc) and link that in the Include-dialog.

The question is what should be the content of such a help text. Because I can't imagine a use case here I need to ask you. Can provide a draft for such a text?

It would also help if you could give a good example of what should be recommended. Maybe you know about a software that does it the same way where we can look at?

I also didn't get your example with *FreeFileSync*. It has ignore patterns? How is this relevant to this Issue?

I really try to get into your use case that is why I ask such detailed questions.

**Comment by Shuunen** [comment]
So the thing I'm suggesting here is suggestions for begginers,

For example I'm used to Windows operating system, if I were developping a backup software, I would suggests to the user to backup his home folder `C:\Users\{USER}` 

Also I would check some common places, for example if I detect a `C:\Games` folder I will show a suggestion to the user to backup this folder which is a common path used to install games on windows

If I had more years of experience with Linux I could also be aware of the important folders to backup but I'm not, that's where suggestions like above are interesting for begginers

So for sure the begginer user could [google "recommended linux directories to backup"](https://www.google.com/search?q=recommended+linux+directories+to+backup) but isn't the aim of software is to facilitate user experience ?

Is it more clear to you ?

**Comment by buhtz** [comment]
> So the thing I'm suggesting here is suggestions for begginers,

Not in my eyes. Of course "beginners" are the target users of BIT. But we differ on how we define that term. You don't have to be a nerd, an expert or something like this. A [Luser](https://en.wikipedia.org/wiki/Luser)/[DAU](https://de.wikipedia.org/wiki/D%C3%BCmmster_anzunehmender_User) and my grandmother should be able to do backups without known something else about rsync and all this. BIT currently is not in that state but it is a goal.

But even a Luser/DAU or my grandmother would know what to backup before starting any backup application.

How people (and the software they use) do use and structure the folders and files is to individual.

> If I had more years of experience with Linux I could also be aware of the important folders to backup but I'm not, that's where suggestions like above are interesting for begginers

Do you feel that you do not backup everything on your system that should be backed up?

> So for sure the begginer user could [google "recommended linux directories to backup"](https://www.google.com/search?q=recommended+linux+directories+to+backup) but isn't the aim of software is to facilitate user experience ?

"User experience" is term used by marketing people not by professional software developers. But I won't dive to much into that topic. It is not the same as making life easier for the users.

Try this terms (from the good old [TAM](https://en.wikipedia.org/wiki/Technology_acceptance_model)): "Perceived usefulness" and "perceived ease of use" often summarized in terms like "usability". I don't see how this proposed feature can increase on that two points. The important word here is "perceived"! It focus on the view, feeling and needs of the users.

> Is it more clear to you ?

Yes, it is. Thanks.

If no one comes up with better ideas or the will to implement this I will close this Issue in the near future.
