### ISSUE TITLE
Remove stuff from backup?

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#883]
Hi,

I have a Ubuntu 16.04 backup that is a bit bloated with old stuff. Is it OK to go into the "last_snapshot" backup and remove folders and files I no longer want to keep for a Restore?

If not, how can I lean down the backup so I don't get everything with a Restore.

I need to do an install of Ubuntu 18.04 in the near future and will be restoring some stuff to the same username. I'd like to be able to do the full "Home" Restore.

**Comment by glyndon** [comment]
You could do a partial restore, by de-selecting the unwanted folders at restore time.
If recovering backup space is instead your goal, you'd probably have to remove the files from each snapshot in order to truly delete them.

**Comment by Germar** [comment]
You can remove files and folders in `last_snapshot` but if you don't exclude them the next snapshot will create new copies of those files. Without hardlinks.
Also like @glyndon already said if you want reserve space you need to remove them from all snapshots. You can do this from [Snpahots Dialog](https://backintime.readthedocs.io/en/latest/snapshotsdialog.html)

**Comment by FlailAway** [comment]
Thanks, but I should have explained that better. I mainly mean this for using Arduino and dated Sketches. I have the backup Folder in BiT as "arduinoIDE" and in that I will have multiple iterations of the "xxxxx.ino" files.
GPS Folder:
  basic-2018-02-21a.ino <-- these "a", "b" etc, are often about hourly
  basic-2018-02-21b.ino
 ...
  basic-2018-04-10a.ino

On my working laptop I delete the "xxxxx.ino" files older than about three days. I am not so much concerned about freeing space, but if I have to restore, I get all the old stuff and I do not want to have to go through hundreds of selections to weed out the old stuff before the restore.

But, I think I have the answer that it is OK to manually delete the files from the Backup drives. I wasn't sure if that would mess up Incremental-backup management or something.

p.s.
I use the GUI version as the Command Line is a little out of my league.
