### ISSUE TITLE
Segfault on Kubuntu 16.04

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [bit-team/backintime#884]
Hello. Im not very proficient, but im looking to provide more information to help either get my problem fixed or help locate the underlying issue.

I tried installing `backintime-qt4` or `backintime-kde` from the Github latest release tar, 16.04 Ubuntu repos, stable PPA and testing PPA (not 100% sure i tried each and every `backintime-kde`, but definitely the `backintime-qt4`). I got a segfault with each of them. In some cases i also tried the --debug flag, but that didnt change anything, still the same `Segmentation fault (core dumped)`. Can i locate this dumped core somewhere to share? I also tried running `apport-bug backintime-qt4 --save bug-report_output.txt`. I attached the result. 
[bug-report_output.txt](https://github.com/bit-team/backintime/files/1934353/bug-report_output.txt)

Let me know how what else i should test or paste.

**Comment by 0xpr03** [comment]
Just a heads up that KUbuntu 16.04 only receives security updates [till 2019-04](https://en.wikipedia.org/wiki/Kubuntu#Releases) while KUbuntu [18.04 LTS is already released](https://kubuntu.org/event/bionic-release-kubuntu-18-04-lts/). I don't know how the dependency situation is there.

**Comment by gislikarl** [comment]
Anyone have han answer to this problem?

**Comment by emtiu** [comment]
Closing as outdated.
