### ISSUE TITLE
Getting message at startup: "can not find snapshots folder"

### ISSUE THREAD

**Issue by rdfuhr** [bit-team/backintime#885]
I am running Pop!_OS and when I start up (or restart) the computer I always get the alert entitled "can not find snapshots folder" related to Back In Time, though the snapshots folder is right there on my external hard drive.

**Comment by rdfuhr** [comment]
My snapshots folder is on /media/richardfuhr/My Passport/BackInTime which is the location of the folder in an external hard drive that is plugged in to my computer at startup time.  So I don't understand why I would be getting a message saying that the Back In Time app can not find this folder.  It does seem to be saving snapshots to that location regularly.

**Comment by glyndon** [comment]
That looks like the path where Nautilus mounts removable media, so the drive may not be mounted immediately at startup.
In fact, it may not be mounted until you open a Nautilus window or take some other action.
(Your OS may use another file browser, so just substitute its name for 'Nautilus' above)
For a volume that has to be present, especially for background processes and regardless what the user is doing, I usually create an entry in /etc/fstab to mount it automatically. Just don't mount it in the /media/richardfuhr directory, else it may collide with something Nautilus tries to put there.
That approach may solve this for you as well.

**Comment by buhtzz** [comment]
@rdfuhr There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

Close. Problem solved because a temporary mount point created by Nautilus was used.
