### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by pehlm** [bit-team/backintime#887]
I have used back in time on Ubuntu 16.04 for some time, it's very good. Do you have plans to add a Bionic build in your ppa? I know there is a build in the Ubuntu repositories but it is only 1.1.12, and I doesn't know if it's working either. Just a wish.

**Comment by rferro** [comment]
+1

**Comment by amithiel** [comment]
looking forward to it

**Comment by Germar** [comment]
Done
