### ISSUE TITLE
"can't remove folder", with empty folder and "can't unmount encfs"

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [bit-team/backintime#888]
Hi !

(Setup : Ubuntu 16.04 & BIT version : 1.1.24)

I started using this software to do backups a while ago and never had any issue until this error.

In the logs I get `Can't remove folder /root/.local/share/backintime/mnt/1_11204/backintime/USER/root/1/new_snapshot`.

First, I started another backup profile to keep backing up just in case, it works fine.

Then I took a look at the folder. When going into the folder mentionned I found a `new_snapshot` folder and tried to delete it using `rm -r`. It returned `new_snapshot/backup/home/USER/.steam/ubuntu12_32/steam-runtime/i386/usr/share/doc/libnm-util2': Directory not empty` however, there are no files inside, and using `rm -rf` didn't help.

I had never heard of such a problem and didn't find anything related on the internet.

Suspecting a hard drive inconsistency I "checked" the file using gparted and it didn't find any issue. Do you think it comes from BIT or my hard drive is having failures ?

edit : just ran ntfsfix and ran a SMART test, hdd seems fine :/

**Comment by buhtzz** [comment]
@thiswillbeyourgithub There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback

**Comment by thiswillbeyourgithub** [comment]
Hi! I'm sorry for not closing this but I have not been using backintime for a while, I switched to restic and duplicity.

I wish you great success :)!

**Comment by emtiu** [comment]
For the record: This error indicated filesystem corruption, so it's highly recommended to work the affected partition thoroughly with `fsck`.
