### ISSUE TITLE
Multihop connection fails on "ssh_known_hosts"

### ISSUE THREAD

**Issue by thomaspaulb** [bit-team/backintime#892]
Having an issue related to [this one](https://github.com/bit-team/backintime/issues/647). My configuration in `.ssh/config` is:

    Host my-backup-server
         ForwardAgent yes
         Hostname 10.2.3.4
         Port 9022
         User root
         ProxyCommand ssh my-gateway-server nc %h 22

I disabled the ping check to bypass any errors about the servers not existing, but now am still getting errors because of [this](https://github.com/bit-team/backintime/blob/master/common/sshtools.py#L422) check. Apparently, [ssh-keyscan does not support the .ssh/config file](https://serverfault.com/questions/823687/ssh-keyscan-through-a-bastion).

Could we include another bypass checkbox for the Known hosts - check until a better solution is found?

**Comment by buhtzz** [comment]
@thomaspaulb There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

Tag: Feedback, Bug, External

**Comment by thomaspaulb** [comment]
I havent used backintime in a while so I couldnt say if this is still relevant or not. I didnt find a solution.

**Comment by emtiu** [comment]
Thanks for reporting back, @thomaspaulb. Closing as outdated.
