### ISSUE TITLE
WARNING: Failed to change Profile_ID 2 and other WARN

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#893]
Ubuntu 16.04 and CLI lines below backup of three profiles. Should I be worried about either or both warnings?

sudo -i backintime backup --profile-id 2 --config /media/vc2/bit-2/backintime/PC4/Bob/2/last_snapshot/config

Back In Time
Version: 1.1.24

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: [qt4systrayicon] end loop
INFO: Take a new snapshot. Profile: 2 usb-2
INFO: Compare with old snapshot: 20180521-160117-385
WARNING: Failed to change Profile_ID 2
"sni-qt/2564" WARN  19:22:59.385 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE

**Comment by buhtzz** [comment]
@FlailAway There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing as outdated.
