### ISSUE TITLE
PPA signing key is only 1024 bytes small

### ISSUE THREAD

**Issue by jean-christophe-manciot** [bit-team/backintime#894]
@Germar 
The current PPA ```59DA D276 B942 642B 1BBD  0EAC A8AA 1FAA 3F05 5C03``` [signing key](https://launchpad.net/~bit-team/+archive/ubuntu/stable) has a 1024 bits size.

![image](https://user-images.githubusercontent.com/13176858/40598520-6c215038-6248-11e8-9f97-2ba6a692ff1e.png)

Current best practice is to use a 4096 bits RSA key.
I strongly suggest to follow that practice, especially for a software which deals with potentially sensitive data..

**Comment by buhtz** [comment]
@Germar can you do something about it as the admin of that PPA?

**Comment by Germar** [comment]
It looks like this is still not possible with Launchpad. See [bugreport 1700167](https://bugs.launchpad.net/launchpad/+bug/1700167)

**Comment by buhtz** [comment]
Closing this ticket based on the comment above. Feel free to reopen if you see an opportunity to solve it on our side. Thank you for your efforts. If you have any further questions, ideas or encounter any other issues, please don't hesitate to let us know.

Best regards,
