### ISSUE TITLE
If nothing changed BIT exits with exit code 1 instead of 0

### ISSUE THREAD

**Issue by qqqqqqqqq9** [bit-team/backintime#895]
**Step to reproduce:** 
1. /usr/bin/backintime  backup ; echo "Exit Code $?" 

2. /usr/bin/backintime  backup ; echo "Exit Code $?" 

**Expected behaviour:** 
$ Exit code 0

**Actual behaviour:** 
...
WARNING: No new snapshot
...
$ Exit code 1

**Comment by buhtzz** [comment]
@qqqqqqqqq9 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Cannot confirm for version 1.3.2. Closing this Issue – feel free to re-open if the problem still exists for you.
