### ISSUE TITLE
backintime don't work

### ISSUE THREAD

**Issue by jbyvosges** [bit-team/backintime#896]
Back In Time  Version: 1.1.12 on Ubuntu 18.04

1) Backup size is always the same
2) exlude files don't work (all files are backed up) 
[config.txt](https://github.com/bit-team/backintime/files/2069552/config.txt)

**Comment by buhtzz** [comment]
@jbyvosges There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you or did you find a solution?

**Comment by emtiu** [comment]
Closing as outdated.
