### ISSUE TITLE
Calculated speed unreasonable

### ISSUE THREAD

**Issue by TinkyWonky** [bit-team/backintime#897]
My worker.progress (and the status in backintime-qt4) file claims that the backup speed is approx. 170 GB/s. I doubt it. Real harddisk transfer is approx. 40 MByte/s.
(Headless) Ubuntu Linux (backup started from remote), backintime-qt4 package version 1.1.24~trusty. Any suggestions?

**Comment by mauromol** [comment]
I think this is due to the "speedup" factor computed by rsync, thanks to the delta-transfer algorithm.

**Comment by buhtzz** [comment]
@TinkyWonky There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

I assume @mauromol is right.

Tag: Feedback, Support, External

**Comment by buhtz** [comment]
The problem described depends on rsync itself. I see no possibility to work around that or fix it in BIT.

If no one else has a fresh idea here or additional information the issue will be closed in the near future.

**Comment by buhtz** [comment]
Please feel free to re-open this issue, add new information or ask further questions.
