### ISSUE TITLE
BIT doesn't do incremental updates

### ISSUE THREAD

**Issue by CasualPyDev** [bit-team/backintime#900]
Hi,
whenever I start an update (which is usually once per week) BIT always performs a full backup, which is quite cumbersome as well as very time consuming. I don't use encryption, so actually this shouldn't happen. I'm using BIT 1.1.24 as provided by SUSE Tumbleweed 15.

**Comment by mzhKU** [comment]
Same here. Then hangs at "Working: Save permission...", and informs that not enough space for backup on drive available.
Ubuntu 16.04

**Comment by buhtzz** [comment]
@mzhKU and @CasualPyDev There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug

**Comment by emtiu** [comment]
Closing as outdated.
