### ISSUE TITLE
When resuming an unfinished snapshot, add a detection of whether the hard-linking phase had ended or not

### ISSUE THREAD

**Issue by mauromol** [bit-team/backintime#901]
I'm often experiencing the following behaviour.
A new snapshot starts and, for any reason, it's interrupted before completion (a typical example: I shut down my notebook or reboot).
When the next snapshot starts, BIT detects there's an existing unfinished snapshot it can pick up and resume.
However, if the first snapshot taking process ended before the hard linking phase had finished, the new snapshot process will cause a lot of files to be transferred again (without hard linking) from the source, even if they are logically unchanged from the previous snapshot. In fact, if I understand it correctly, when resuming an existing snapshot, BIT just calls rsync to update the partial snapshot.

This is quite annoying, because it breaks the "hard linking chain" between subsequent snapshots. Even if some snapshots are removed over time thanks to the auto-removing feature (and hence some space is reclaimed), there will always be "breaks" in hard linking between snapshots and, as time goes by, in the worst case you will end up with having few snapshots but every one being a new whole copy of the source.

**Comment by buhtzz** [comment]
@mauromol There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug, Medium/High, External

**Comment by mauromol** [comment]
Hi @buhtzz , this was relevant when using the original BIT way of backing up (that was: create hardlinks with cp, then rsync over them). AFAIK, the new default mode for BIT (perhaps the only one now available? I can't remember honestly) is "rsync only" and in this case the above problem should not occur any more.
So, if you don't plan to support the old backup mode, this should not be relevant any more.

**Comment by emtiu** [comment]
You're right, thanks for pointing how backintime has changed – I wasn't fully aware of that history :)

"Full rsync mode" mode was introduced in version 1.0.22 in 2013:
https://github.com/bit-team/backintime/blob/06b62ffb31d8debfb1ad8f41159e12b533eff952/CHANGES#L433

… and made the one and only default mode of operation in 1.2.0 in 2019:
https://github.com/bit-team/backintime/blob/06b62ffb31d8debfb1ad8f41159e12b533eff952/CHANGES#L107

Therefore, we won't be dealing with the old mode of operation anymore, and this Issue can be closed. Thanks!
