### ISSUE TITLE
Question: backup of BIT config file

### ISSUE THREAD

**Issue by DonEdwards** [bit-team/backintime#903]
Question: I notice that each backup in any profile contains a fresh copy of BIT's own config file. Is there a reason for storing duplicate copies when this file hasn't changed, rather than using hard links in the same manner as for all the other files being backed up?

**Comment by Germar** [comment]
The only reason is it's a lot more complicated to hard-link it instead of just copy it...

**Comment by buhtzz** [comment]
@DonEdwards There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Support

Close because question is answered.
