### ISSUE TITLE
BIT exits when selecting another profile

### ISSUE THREAD

**Issue by malypetu** [bit-team/backintime#905]
I'm experiencing a new problem. After opening BIT (not root mode) the application exits when selecting a different profile other than Main.
There is no message or anything. 
On the other hand, Main profile works just fine.
All functions in Main profile works ok.
Backups are all present in the external HDD. Including the one for alternate profile
However, the last backup for the alternate profile is dated a couple of days back.

I'm thinking it may have lost the profile setting but the name is still present in the dropdown list.
Questions:
1. Can I recover the profile?  
2. Do I have to recreate the profile from scratch?  
3. If I create a new profile with the same name as before,  Will it be linked the old backups?
Are the profiles settings stored somewhere were I can rescue the settings?

Any help will be appreciated.

**Comment by Germar** [comment]
Please run `backintime-qt4` from Terminal, change the profile and post the output from Terminal if it crashes again.

1. there is a config backup in each and every snapshot. You can manually copy it to `/home/USER/.config/backintime/config` or delete the config in that path and restart Bit. It will automatically scan for snapshots and ask if you want to restore the config from there...
2. Nope
3. If you point the new profile to the same backup destination (Where to save snapshots) and use the same User/Host/Profile ID below it will use the old backup again.

**Comment by malypetu** [comment]
Hi Germar, Thank you for the response.  I have tried the following:
1. I have deleted /home/MYUSER/.config/backintime/config then try to run BIT and use the profile
RESULT:  BIT shuts down.
2. I have deleted /home/MYUSER/.config/backintime/config and copied the one from latest snapshot and use the profile 
RESULT: BIT shuts down.
3. I have run usr/bin/backintime-qt4 from Terminal and that seems to do the trick as backup is taken and old ones are displayed, see below:
Back In Time
Version: 1.2.0~alpha17

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

INFO: Lock
INFO: Take a new snapshot. Profile: 2 ssd-win Amaro
INFO: Call rsync to take the snapshot
INFO: Save config file
INFO: Save permissions
INFO: Create info file
INFO: Unlock
.....
However, when I come back to BIT-GUI it continues to exits when selecting the profile.  Main Profile continues to work just fine.

Any hints?
Amaro

**Comment by malypetu** [comment]
Hi Germar,
Happy to report that after a dismount and mount the backup media again, all seems to work ok.  
After re-connecting the device the scheduled job fire up and give us an error on privileges on a specific file in the last snapshot.  We decided to delete the snapshot and take a new backup, that proved to be the solution. BIT is back to normal.
Thanks for the support keep up the good work.
Amaro
