### ISSUE TITLE
problem with local encrypted backup: encfs password incorrect

### ISSUE THREAD

**Issue by afrap** [bit-team/backintime#908]
Backintime performs the backup,
but when I restart it then says:

"Can't mount 'encfs --extpass=backintime-askpass /media/franco/MyPassport4T/backup-backintime /home/franco/.local/share/backintime/mnt/D9E7F1ED/mountpoint':

Error decoding volume key, password incorrect"

Nevertheless, if then I insert the password in Settings everything keeps working fine.
I have checked 'Cache password for Cron',
and I have tried checking and unchecking 'Save password to keyring'
always the same problem
I have Ubuntu 16.04LTS

**Comment by buhtzz** [comment]
@afrap There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug, External

**Comment by aryoda** [comment]
I could imagine that the used `keyring` package picks the wrong backend to get the password and it is stored in two "password safes" (one with the wrong password). `keyring` uses a new `ChainingBackend` (introduced 2018) which iterates over all installed pw safe backends and may cause this problem IMHO.

If the problem still exists could you please retest with a newer version of BiT (from the package maintainer or via Github).

You can find some instructions to add diagnostic output around `keyring` ins this issue:

https://github.com/bit-team/backintime/issues/1321#issuecomment-1271689827

**Comment by buhtz** [comment]
Dear @afrap ,
do you have new information about that issue for us? Are you able to reproduce the problem with the latest 1.3.3 version of BIT?

The issue will be closed in the new future if no new information are added.
