### ISSUE TITLE
What about to support BorgBackup ?

### ISSUE THREAD

**Issue by L0cutus** [bit-team/backintime#910]
I think BIT is perfect GUI to use borgbackup tool.
Thanks !

**Comment by plgruener** [comment]
I think this is way out of scope for this project, since BIT is solely built as an rsync wrapper (to my knowledge, not a developer) – which is a completely different concept than borg (file- vs chunk-based).

**Comment by Germar** [comment]
@plgruener is right. Borg-GUI would be a complete different program from scratches
