### ISSUE TITLE
backup cannot be paused or stopped

### ISSUE THREAD

**Issue by peidaqi** [bit-team/backintime#918]
I cannot believe this is not put in the Readme - the backup process cannot be paused or stopped.

I was using it to backup my 300GB drive. The process was 30% when I needed to unplug my laptop and leave. That was when I discovered this cannot be stopped. The process cannot be killed, and even a shutdown -r was not possible. I had to turn off the power, risking losing both my backup drive and my hard drive.

This is a very serious issue. I understand there's no guarantee using open source software, but at least noting this in the readme file as a warning will be helpful - or consider make a startup popup.

**Comment by Germar** [comment]
Version `1.2` will come with pause, resume and stop feature
