### ISSUE TITLE
Backintime won't start after Ubuntu upgrade to 18.04

### ISSUE THREAD

**Issue by malypetu** [bit-team/backintime#919]
After upgrading ubuntu 16.04 to 18.04.1, backintime won't start with the following error:
```
linux:~$ backintime 
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 51, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus
```
Actions:
Remove BIT
`sudo apt purge backintime-common`
`sudo apt purge backintime-qt4`
`sudo apt autoremove`

Install BIT again
```
sudo add-apt-repository ppa:bit-team/testing
sudo apt update   # done automatically now
sudo apt install backintime-qt
```
Result:  Fail!.   Same Error as above.
Any hints??

**Comment by malypetu** [comment]
Just to add information.  I have run BIT in debug mode:
```
-linux:~$ backintime-qt --debug
Traceback (most recent call last):
  File "/usr/share/backintime/qt/app.py", line 35, in <module>
    import qttools
  File "/usr/share/backintime/qt/qttools.py", line 47, in <module>
    import snapshots
  File "/usr/share/backintime/common/snapshots.py", line 34, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 51, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
Hope it helps

**Comment by colinl** [comment]
Is this the same problem as #871?  If so then perhaps python3-dbus is not installed.

**Comment by Germar** [comment]
python3-dbus  is a hard dependency. So it must have been installed. Question is why isn't it present. I'd reckon you have an alternate python environ installed beside apt packagemanagement on your system which is the default for python3

**Comment by malypetu** [comment]
Germar
Thank you for replying. I have checked and I do have python installed using Anaconda, see below:
```
linux:~$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
```
Could you please send any hint as to how to check 
Just to add a bit of info, I have on bashrc  
`export` PATH="/home/amaro/anaconda3/bin:$PATH"
brings the error I show at the top

However, when I change the line to, (Anaconda after path) :  
`PATH="$PATH:/home/amaro/anaconda3/bin"`

Then the error change to 

```
Back In Time
Version: 1.2.0~alpha17

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 1165, in <module>
    startApp()
  File "/usr/share/backintime/common/backintime.py", line 521, in startApp
    return getConfig(args, False)
  File "/usr/share/backintime/common/backintime.py", line 669, in getConfig
    cfg = config.Config(config_path = args.config, data_path = args.share_path)
  File "/usr/share/backintime/common/config.py", line 279, in __init__
    self.setupUdev = tools.SetupUdev()
  File "/usr/share/backintime/common/tools.py", line 1699, in __init__
    conn = bus.get_object(SetupUdev.CONNECTION, SetupUdev.OBJECT)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 248, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Launch helper exited with unknown return code 1

```
I have checked python3-dbus the result is as follow:
```
linux:~$ sudo apt-get install python3-dbus
[sudo] password for amaro: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dbus is already the newest version (1.2.6-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.

```

It will be nice to have a couple of commands to check dependencies and how to fix them.
Also if the problem is python3-dbus how to make sure is installed

As usual, any hints will be welcome.
Cheers

**Comment by Germar** [comment]
Please change PATH like mentioned above to have anacconda behind $PATH and then restart. The dbus service failed with the same problem and need to be restarted.

**Comment by malypetu** [comment]
Hi Germar,
Thanks for the help.  I have done as you suggested:
modified bashrc file, so anaconda goes after PATH
reboot the machine so to start dbus.service 
```
 linux:~$ backintime
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 27, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 32, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 51, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'
```
I have attempted to follow #871 but creating the soft link didn't help the problem.
However, I have checked the disk and I do have the following in it:
python2.7
python3
python3.6
pyton3.7
Now I'm happy to try and delete the wrong ones, but not sure which ones and what impact may have.

Cheers

**Comment by Germar** [comment]
Wow, please don't delete anything in `/usr/lib`! That would break you whole system. Just remove this anaconda thing. Should be in `/home/amaro/anaconda3/`

**Comment by malypetu** [comment]
Hi Guys,
Thank you for replying, this thing is getting on my nerves.  I have managed
to get one step closer to the isolate issue... I think. These were my steps:

*$> systemctl --no-pager --full  status dbus*
$> systemctl --no-pager --full  status dbus
Aug 31 10:20:55 amaro-linux dbus-daemon[984]: [system] Activating service
name='net.launchpad.backintime.serviceHelper' requested by ':1.147'
(uid=1000 pid=11087 comm="python3 -Es
/usr/share/backintime/common/backintim" label="unconfined") (using
servicehelper)
Aug 31 10:20:55 amaro-linux net.launchpad.backintime.serviceHelper[984]:
Traceback (most recent call last):
Aug 31 10:20:55 amaro-linux net.launchpad.backintime.serviceHelper[984]:
 File "/usr/share/backintime/qt/serviceHelper.py", line 75, in <module>
Aug 31 10:20:55 amaro-linux net.launchpad.backintime.serviceHelper[984]:
 from PyQt5.QtCore import QCoreApplication
Aug 31 10:20:55 amaro-linux net.launchpad.backintime.serviceHelper[984]:*
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.11'
not found* (required by
/usr/local/lib/python3.6/dist-packages/PyQt5/QtCore.so)
Aug 31 10:20:55 amaro-linux dbus-daemon[984]: [system] Activated service
'net.launchpad.backintime.serviceHelper' failed: Launch helper exited with
unknown return code 1

When checking the system, the (library) file is there, (at least the soft
link) but apparently it is pointing to the wrong version (
libQt5Core.so.5.9.5), se below:
$> ls -la /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
lrwxrwxrwx 1 root root 19 Apr 13 09:24
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5 -> libQt5Core.so.5.9.5

As per the error, I need to have library *libQt5Core.so.5: version `Qt_5.11
*in /usr/lib/x86_64-linux-gnu/ and I don't have the correct version.
*So here are the questions:*

   1. How do I check what library version (*libQt5Core.so.5*) I do have
   installed?
   2. How do I installed a specific version of *libQt5Core**.so.5 *?
   3. If I do have that version installed somewhere else, would it be
   enough just to point the soft link to that version?

Of course, I'll search for answers to these questions on my own.
Nevertheless, if someone 'out there' knows the answer(s) please share it.

Finally, if this is the case (wrong library version *libQt5Core.so.5*) I
think it is fundamental to BIT.  We should have a list of user checkings to
be made to find/isolate errors.

Cheers


*Amaro Roach, MIT*Senior IT Specialist



*¯¯¯¯¯**¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯**¯*

*Mobile:* 0422 354 435
<http://s.wisestamp.com/links?url=http%3A%2F%2Fs.wisestamp.com%2Flinks%3Furl%3Dtel%253A0434%252520286%252520020>

*Email:* aroach@rsystems.com.au
<http://s.wisestamp.com/links?url=http%3A%2F%2Fs.wisestamp.com%2Flinks%3Furl%3Dmailto%253Aaroach%2540rsystems.com.au>
[image: Skype] Maly.petu

Please consider the environment before printing this e-mail!
Get your own email signature
<https://www.wisestamp.com/signature-in-email?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>

**Comment by malypetu** [comment]
Hi Guys,
Another change,  I've managed to locate Qt5Core.so.5 version 5.11 in my home directory under
/Qt/Tools/QtCreator/lib/Qt/lib
I have created the soft link:
```
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s  /home/amaro/Qt/Tools/QtCreator/lib/Qt/lib/libQt5Core.so.5.11.1 libQt5Core.so.5
# reboot the machine to restart systemctl
```
Now the error is different, meaning it found dbus (I guess), this is the error.
```
linux:~$ systemctl --no-pager --full  status dbus
● dbus.service - D-Bus System Message Bus
   Loaded: loaded (/lib/systemd/system/dbus.service; static; vendor preset: enabled)
....
Aug 31 16:32:20 amaro-linux net.launchpad.backintime.serviceHelper[880]:   File "/usr/share/backintime/qt/serviceHelper.py", line 74, in <module>
Aug 31 16:32:20 amaro-linux net.launchpad.backintime.serviceHelper[880]:     import dbus.mainloop.pyqt5
Aug 31 16:32:20 amaro-linux net.launchpad.backintime.serviceHelper[880]: ImportError: **libicui18n.so.56**: cannot open shared object file: No such file or directory
Aug 31 16:32:20 amaro-linux dbus-daemon[880]: [system] Activated service 'net.launchpad.backintime.serviceHelper' failed: Launch helper exited with unknown return code 1
Aug 31 16:32:49 amaro-linux blueman-mechanism[2163]: Exiting
```
So I've search for the missing library libicui18n.so.56 and I found it in the same location
`/home/amaro/Qt/Tools/QtCreator/lib/Qt/lib`

But I'm guessing now that I need to define LD_LIBRARY_PATH to point to that location rather than softlink each library.  

Is that a fair assumption?

Cheers

**Comment by malypetu** [comment]
I guess there is no help available for this issue. I will keep trying to solve it and report back when I have a solution.  
Thanks

**Comment by glyndon** [comment]
I may be the least qualified person to offer help on this, because I'm just shooting in the dark without knowing what I'm doing, but I ran into very similar problems occasionally over the last year. 
My guess is that it's the version of QT (4/5) that's tripping it up, and here is a note I made for myself:

Workaround is to launch it directly as root, viz:
sudo backintime-qt_polkit 
(note the 'qt' and not 'qt4'. Check if yours will launch this way, and then check what your .desktop files are calling. Mine were still launching the qt4 version, even though my system was not at qt5.)

Later, I also found the following package installs allowed it to run normally:
aptitude install qtwayland5 qml-module-qtwayland-compositor python3-pyqt5 python3-dbus.mainloop.pyqt5

I also had some strange dbus rejections, and while I haven't seen that one lately. When I did, there were some edits I had to make to a dbus config to grant permissions to the process. 
Again, here, I'm shooting blind, but with some finds on StackExchange I was able to get it running happily again on one or two systems.
Edit /etc/dbus-1/system.conf and add the following 'allow' line: (I put it within a block that included user="root")

<policy>
    ...
    <allow own="net.launchpad.backintime.serviceHelper"/>
</policy>

**Comment by malypetu** [comment]
Hi glyndon, Thank you for your help, I have tried a few things you mentioned, still no joy here. 
Attempting to install
`sudo apt-get install python3-dbus python3-dbus.mainloop.qt
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-dbus is already the newest version (1.2.6-1).
python3-dbus.mainloop.qt is already the newest version (4.12.1+dfsg-2).
0 to upgrade, 0 to newly install, 0 to remove and 23 not to upgrade.
`
So all installed and up to date.

However, after removing QT, my error has changed now to  
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 175, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    's', (bus_name,), **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'net.launchpad.backintime.serviceHelper': no such name
```
With this change VirtualBox has come back to work ok. No luck with BIT though

I'm guessing it is now related to python3

Thanks for your help, it is really appreciate it.

**Comment by glyndon** [comment]
I wish I had more to offer in this case, but am way out of my league in that stuff.  What had helped me were the things I found by trial-and-error with all the smarts provided by the great people on StackExchange and other sites. I barely even know what QT is, let alone how to properly use it. Same with dbus. I'm an old assembler/C programmer, so frameworks and such are something yet-to-be-learned about for me. 
Best of luck. I really love BackInTime, for reasons too numerous to list here, so I hope that stuff like this doesn't become too insurmountable a challenge.

**Comment by colinl** [comment]
@malypetu I notice that you have 23 out of date packages. Have you considered upgrading them just in case the problem is related to one of them, or do you have a reason for not doing so?
`sudo apt upgrade`
should do that for you.

**Comment by malypetu** [comment]
Hi Colin, Thanks for the tip I have done the upgrade just now and no difference, but worth a shot.

I am considering next to uninstall all python 3.6, leave 2.7 as required and try to install 3.6 from scratch and see if it makes a difference.

Cheers

**Comment by malypetu** [comment]
Hi Guys,
I manage to get BIT working again, it was a series of mismatch between different Python/QT/PIP3 versions that makes BIT unable to work with the path to libraries. 
My steps were:
I purge BIT,  then 
```
sudo apt update
reboot
check all apps works fine (they did)
then install BIT stable
No Luck,  then I checked dbus
linux:~$ systemctl --no-pager --full  status dbus
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `**Qt_5.11' not found** (required by /usr/local/lib/python3.6/dist-packages/PyQt5/QtCore.so
```

So I decided to uninstall pyqt using pip3 (I have to reinstall it), it gave me a strange warning (see below) but all works fine. 
```
linux:~$ sudo pip3 uninstall pyqt5
The directory '/home/amaro/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling PyQt5-5.11.2:
..... many python 3.6 files to be uninstalled.....................

```
After this BIT works ok!!.

I have done aa few extra 
sudo apt update 
sudo reboot

to check all other apps and all working fine.

Thanks to all who provide tips and suggestions, there were all directly or indirectly contributions to find the cause either by showing commands to investigate systems status or libraries dependencies etc.

I guess the best lesson is, if you are going to have several python environments in a single machine,  it is better to establish a common working platform for your apps.  Then use/create/define a point in time recovery system in case something breaks, so you can come back to your working version.  I learn in a hard way that BIT won't help in that situation (not a critic just a warning). Also after Ptyhon and/or QT modifications updates etc. TEST the hell out of everything!!, looks for failures on all your installed systems with python libraries dependencies, then proceed, I learned after a while that a few apps were broken, though the one we were working on, was working as expected.

Timeshift is a good tool for a point in time recovery (not necessarily the best)
My lesson is, use VM for a testing, do a system image, create a VM with it, then test, test, test.
I start with VirtualBox on the same machine, however, is got Python dependencies that were also broken.  There it was my testing platform gone.
I end up using Proxmox in another machine (really nice) and basically allow me to break the system apart with many different tests and always get back to initial testing point.

Hope this helps

**Comment by esentino** [comment]
After install python3-dbus.mainloop.pyqt5 backintime start working (Ubuntu 19.04)

**Comment by Flurrywinde** [comment]
I'm on Ubuntu 18.04. I finally got it to work. I made a new Anaconda environment: `conda create --name bitenv python=3.7`. (I called mine `bitenv`. You can use any name you want.)

Then, I installed pyqt5 there: `pip install pyqt5` . (Backintime seems to be qt5 now, despite what the readme says about stable being qt4.)

Then, activate this environment: `conda activate bitenv`

Running `backintime-qt` now gives the dbus module missing error, so then install it. I think this means both the following are required: First, `conda install dbus` and then `pip install dbus-python`.

After that, it finally worked. My problem was that I had to do a `which pip` to make sure I ran the `pip` in the bitenv environment, not some other pip like the general anaconda environment or /usr/bin/pip.

**Comment by julienpmorand** [comment]
After trying everything mentioned here with no success, I reinstalled every package that starts with `python`, reinstalled BackInTime and it worked flawlessly, which means some python program was broken and prevented backintime to open.
Here's a command I used to do so
```bash
apt list --installed | egrep "^python" | sed -r 's/^(python[-a-zA-Z0-9]+?).+/\1/' | sort | uniq -u | xargs -L 1 sudo apt-get install -y --reinstall 
```
