### ISSUE TITLE
Allow user to defined a shell script to execute post-run of every scheduled snapshot

### ISSUE THREAD

**Issue by digi9ten** [bit-team/backintime#920]
I want to create a compressed tar of every new snapshot, and then ship it to a remote drive.
I'm sure I could do this via cron.

Is there a way we could add a feature to the existing backintime to actively run a defined script post every new, successful snapshot?

**Comment by Germar** [comment]
Take a look at `user-callback`. This is already implemented for years.

[Here](https://github.com/bit-team/user-callback) you'll find some examples
