### ISSUE TITLE
when the source is very big. More than 5TB, BIT can not generate the snapshots after rsync finished. 

### ISSUE THREAD

**Issue by michael-qi** [bit-team/backintime#923]
While, when less the size of source, such as less then 99GB, BIT could generated the snapshots successfully.  I don't try other size, but for source is as bigger as 5TB, it could not generate the snapshots in the snapshots list. But the rsync process is finished normally.  The first rsync process is more than 24 hours. 
--------------------------
backintime -v
backintime 1.2.0~alpha0

OS: Centos 6.5

Python: 3.6.5

**Comment by buhtzz** [comment]
@michael-qi There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback

**Comment by emtiu** [comment]
Closing as outdated.
