### ISSUE TITLE
Question: Hard links in SSH mode, NTFS, USB HDDs

### ISSUE THREAD

**Issue by cbhushan** [bit-team/backintime#924]
I read through the docs of Back in time (BIT) and did not find clear explicit answers. So, posting here:

1. Does BIT support backing data _from_ NTFS drive?
2. Does BIT support NTFS drives as backup destination? with hard-links? with encfs? Any limitations with NTFS?
3. Does BIT perform hard-linking in SSH mode (assuming remote is linux with ext3/4 filesystem)?
4. Would BIT work in SSH mode when backup target is a folder on USB-connected NTFS drive on remote host? Would hard-links work? (My remote host is a raspberry pi running rasbian & several NTFS HDDs are connected to it via USB).
5. Does hard-links work when using encryption?

**Comment by Germar** [comment]
1. sure. No probs at all
2. as NTFS supports hard-links it will work just fine. But I still prefere a native Linux filesystem for my backups as NTFS is a properitary, undocumented format which you can never tell how good it will work with Linux
3. of course
4. yes
5. yes

**Comment by emtiu** [comment]
I think we can close this issue. NTFS seems to be used by many users, and we can tackle specific problems if/when they are reported. I don't see any need to make a recommendation for/against NTFS anymore.
