### ISSUE TITLE
Question: How is back in time different from rsnapshot?

### ISSUE THREAD

**Issue by cbhushan** [bit-team/backintime#925]
How is back in time (BIT) different from [rsnapshot](https://github.com/rsnapshot/rsnapshot)?

I have been long-time user of rsnapshot and am looking around as [rsnapshot is not actively maintained  anymore](https://github.com/rsnapshot/rsnapshot/issues/191). I have tried using BIT yet, but from the description it seems to achieving very similar outcomes. It may be good to outline similarities / differences w.r.t. rsnapshot. Here are some specific questions in this context:
* How are hard-links created/managed in BIT? rsnapshot uses `--link-dest` option of rsync.
* Is there a CLI for BIT? Can it be used in a head-less server?

**Comment by Germar** [comment]
I've never uses rsnapshot. So I can't tell the differences / similarities

1. older versions uses `cp -aRl` before syncing with `rsync`. Current version has an option to use `--link-dest`. Next version 1.2. will use this by default
2. you need to create a config manually. Take a look at `man backintime-config` everything else can be done from CLI. Take a look at `man backintime`
