### ISSUE TITLE
requirement ssh w/password-less account hinders some environments

### ISSUE THREAD

**Issue by Yanestra** [bit-team/backintime#926]
Synology NAS devices recently changed behavour so that password-less accounts cannot be configured (the users' home directories are no longer writable).
It would be a help if backintime could only rely on ONE kind of service (in this case, sshfs) and skip the use of rsync on the storage host.

**Comment by Germar** [comment]
Sorry but that won't work. BiT is basically a fancy frontend for rsync. Without rsync there is no BiT

**Comment by Yanestra** [comment]
Rsync can simply synchronize client based on a sshfs mounted remote filesystem. sshfs supports hardlinks, so no need for a server running an rsync instance.

**Comment by Germar** [comment]
Last time I checked sshfs didn't support hardlinks. But even if it would, it would be very inefficient to sync to a local mounted remote share no matter which format that would be. Snapshots would take 4-5 times longer.
