### ISSUE TITLE
Question: How to completely delete newfiles  while restoring？

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#928]
I am a kind of newbee about rsync,here are some quetions about BIT

1. I try BIT in virtualbox and do a whole back up "/". After that ,I install some new softwares   and uninstall some softwares to change the system state,then restore the whole "/" with "restore and delete new files“，but I noticed the newlly intalled softwares sttill in the folder '/usr/lib" ,i can simply  lauch them . and somebody advise me add --delete-after while restoring，but，i cant  do that with gui of BIT, how can i completely delete the files  newlly installed while restoring
2. Does BIT support compression snapshot to *. tar so that we can store the archieve in mobile HDD(ntfs format, you kwon,mobile HDD not only for linux  but also for windows)

**Comment by buhtzz** [comment]
Unresponsive "ghost" account.

Tag: Support

Close
