### ISSUE TITLE
only back up one file type / extension?

### ISSUE THREAD

**Issue by mankoff** [bit-team/backintime#929]
I have BIT and two profiles for an external backup disk at home and at work. I back up to these every few days.

I'd like to run a 3rd profile every 10 minutes that backs up all of my Org and Python files to a local folder. Is this feature possible in BIT? I know in rsync I could exclude everything, include ".org" and ".py". But I'd like that feature *plus* all the great BIT features (time-stamping, removing old backups, etc.)

**Comment by Germar** [comment]
There is no way to use include pattern in BiT because of the way BiT handles include. But you can use regular expressions to exclude everything but .py/.org

**Comment by mankoff** [comment]
That sounds promising. My regex-foo is not strong, and I just spent an hour trying to do this. Do you have a hint?

**Comment by mankoff** [comment]
From https://unix.stackexchange.com/questions/469333/rsync-specify-negative-exclusion-not-inclusion It seems I can almost achieve what I want by passing 

    --filter="+ *.org" --filter="+ *.py" --filter="- *.*" --prune-empty-dirs 

To the 'Paste additional options to rsync` under the `Expert Options` tab.

It isn't perfect (files without extensions are still backed up), but it is good enough, I think.

**Comment by mankoff** [comment]
This works: `--filter="+ *.py" --filter="+ *.org" --filter="-! */" --prune-empty-dirs`. Then select home or some subset of folders to backup, presumably add Anaconda or other py-file heavy folders to the exclusion, and it works.
