### ISSUE TITLE
How to backup to multiple external drives?

### ISSUE THREAD

**Issue by HolgerJeromin** [bit-team/backintime#930]
I have setup BIT to my external usb drive. Very nice, thanks for this nice peace of software!

But better would be to backup alternating to two usb drives. This way a problem (power surge?) while backup would not destroy data and backup at the same time.

I want to setup the secondary external drive the same as the first. 
Is there a good way to configure BIT and / or my file system to not duplicate all BIT profiles?

**Comment by Germar** [comment]
Just make sure, the second drive is mounted at the same place as the first. For automount give both the same drive name. Than open BiT. It will complain that it didn't find the snapshot folder. Ignore that, open and close settings once so it will create the folderstructure on the second drive and you're done

**Comment by HolgerJeromin** [comment]
Thanks for your quick help. Naming both drives with the same name was the key :-)
