### ISSUE TITLE
[Question] Backintime Deleted Files Xubuntu 16.04 to 18.04

### ISSUE THREAD

**Issue by roadroots** [bit-team/backintime#932]
I saw with BIT is- and I don't know if it's a bug or working as intended- that it stores deleted files?

MWE: Backup /home/user/Videos/movie1.mkv and /home/user/Videos/movie2.mkv.

Then delete /home/user/Videos/movie1.mkv and backup again.

Now, when I restore my backup I have /home/user/Videos/movie1.mkv still in the backupped files and it also gets restored. Is this a bug or working as intended? And if the latter: Can this behaviour been avoided?

Also, if this is working as intended: How do you normally restore backups? My intention was to restore just the most recent snapshot, which contains the state of my current system- without the deleted files but with all modifications to files made, incrementally saved.

**Comment by buhtzz** [comment]
@roadroots There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?
