### ISSUE TITLE
Schedule "When drive get connected (udev)" leads to emergency mode after reboot

### ISSUE THREAD

**Issue by alevdonsky** [bit-team/backintime#935]
Schedule "When drive get connected (udev)" for USB flash leads to emergency mode after reboot
Ubuntu 18.04, Backintime 1.1.12
Switching off the schedule restores normal reboot completion.

**Comment by alevdonsky** [comment]
Oh, it just doesn't work the way I expected. I need to backup USB stick on permanently mounted media as the USB stick get mounted  but BIT offers to backup a partition as backup disk get mounted.  
By the way it seems the schedule is not really "When drive get CONNECTED (udev)" really it is "When drive get MOUNTED (udev)", isn't it?

**Comment by buhtzz** [comment]
@alevdonsky There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Support

**Comment by emtiu** [comment]
Closing as outdated.
