### ISSUE TITLE
Launching/Running BIT Through Script

### ISSUE THREAD

**Issue by quarkrad** [bit-team/backintime#944]
I have a simple folder to be backed up - ideally I would like this to be run automatically at Shutdown but that seems a little too far (ubuntu 18.04/systemd).  Is it possible to have an icon/script on my Desktop that I can double click that will automatically run BIT? I.e. not launch the program and than I have to click on the icon but actually run the snapshot.

**Comment by Germar** [comment]
Open an Editor (`gedit` for example) and copy / paste this
```
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Back In Time Take Snapshot Profile 1
GenericName=Backup
Exec=backintime backup-job --profile-id 1
Icon=document-save
Terminal=false
X-MultipleArgs=false
Type=Application
```
than save it as `take_snapshot.desktop` on your desktop

**Comment by quarkrad** [comment]
Sorry - I had been away.  Many thanks for your Reply - it works very well.
