### ISSUE TITLE
Does ppa reflect latest commits

### ISSUE THREAD

**Issue by dkebler** [bit-team/backintime#946]
Bit confused.   

ppa shows 
backintime | 1.1.24a~bionic | Germar (2018-04-29)

which I installed (in bionic) but repo says there has been 443 commits! since that release.  

It kinda seems that the binaries at the ppa are updated with the latest commits as the date there matches the last commit.   Is that true?   If so all is well if not then ppa is 443 commits behind the repo master

Kinda a housekeeping thing but having the releases at github somewhat match the ppa would be nice.  I'd say it's ok bump a version number after 443 commits.  Side benefit is then we all know you are hard at work when the about dialog shows a new number :-).

**Comment by willemw12** [comment]
Is it because the latest version is not on the master branch? In the ArchLinux AUR we noticed a similar issue: https://aur.archlinux.org/packages/backintime-git/

**Comment by Germar** [comment]
Current stable is [series1.1](https://github.com/bit-team/backintime/tree/series1.1) but Master is already series 1.2 which is in testing ppa but not yet ready for stable release.
