### ISSUE TITLE
Backup job changes backup path permission to 700

### ISSUE THREAD

**Issue by harrim4n** [bit-team/backintime#954]
Whenever I run a backup, the permissions of the remote target directory changes to 700.
Mode is SSH with the target directory being a ZFS fs.
If I manually change the permission of the "Path:" to anything other than 700, e.g., 770, they immediately get changed to 700 when a snapshot is taken.
As I want to backup to this directory with other users, this is undesirable. Also, as far I can see, this is not mentioned in the documentation.

**Comment by bentolor** [comment]
https://github.com/bit-team/backintime/issues/579#issuecomment-222816362 ff. seems to mention what & why

**Comment by harrim4n** [comment]
Hm, I'm not sure if that's correct. After all it's u+wx, which shouldn't change group ownership at all. Also, I tried adding g+wx as an rsync option with no success.

**Comment by bentolor** [comment]
After re-reading the code & your issue realized that, too.

Currently I'm also heavily struggling with local uid/gids and permissions vs. remote. That's why I was skimming the issues here.

**Comment by bentolor** [comment]
So sorry for the false alarm :-(

**Comment by harrim4n** [comment]
No worries :)
