### ISSUE TITLE
Backup only needed folder, no root or home

### ISSUE THREAD

**Issue by p-frolov** [bit-team/backintime#955]
I need backup only projects folder
I added the folder to include, after a run I got home and root additionally.
How I can backup only necessary 'projects' folder? No any home, root, etc...

**Comment by buhtzz** [comment]
@p-frolov There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Support

**Comment by emtiu** [comment]
Closing as outdated.
