### ISSUE TITLE
"Error: Failed to take snapshot [date/time] !!!"

### ISSUE THREAD

**Issue by arzachel23** [bit-team/backintime#957]
That's the only error message I'm seeing & I can't find the logs.  It goes through the whole process & fails at the end w/that not-so-helpful message.

Running on Ubuntu 18.0.4 LTS.  I'm attempting to run with "+Modify for Full System Backup" prefs, nothing else changed (that I remember), to an external linux-formatted drive.  Running the "(root)" version of the app.

Sadly, I installed with the Ubuntu App Store initially, where users are reporting all sorts of mayhem & recommending installing w/apt.  I removed via App Store, reinstalled via apt, but it remembered my preferences so perhaps cruft from the first install is causing my problems.

I'm a rank amateur at Linux, so checking how to do a full wipe & reinstall (& trying to find those consarned logs) is my next step.

No help line per se other than here, correct?  #irc channel or whatnot?

**Comment by emtiu** [comment]
Closing as outdated.
