### ISSUE TITLE
Updating to python-pyqt4 4.12.3 from 4.12.1 breaks BIT

### ISSUE THREAD

**Issue by graysky2** [bit-team/backintime#964]
Upon updating I get the following
```
% backintime-qt4                                                                               :(
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 30, in <module>
    import qt4tools
  File "/usr/share/backintime/qt4/qt4tools.py", line 21, in <module>
    from PyQt4.QtGui import QFont, QFileDialog, QListView, QAbstractItemView,      \
ModuleNotFoundError: No module named 'PyQt4.sip'
```

Am I missing a dependency?

**Comment by LeoniePhiline** [comment]
I can confirm the same issue on an all-updated OpenSUSE Tumbleweed.
```
$ backintime-qt4_polkit                                                                                                                   
Traceback (most recent call last):
  File "/usr/share/backintime/qt4/app.py", line 30, in <module>
    import qt4tools
  File "/usr/share/backintime/qt4/qt4tools.py", line 21, in <module>
    from PyQt4.QtGui import QFont, QFileDialog, QListView, QAbstractItemView,      \
ModuleNotFoundError: No module named 'PyQt4.sip'
```

**Comment by finswimmer** [comment]
With PyQt4 v4.12.2 it is neccessary to create a private copy of the sip module. See the note int the [install instructions](http://pyqt.sourceforge.net/Docs/PyQt4/installation.html)

> Note When building PyQt4 v4.12.2 or later you must configure SIP to create a private copy of the sip module using a command line similar to the following:
> `python configure.py --sip-module PyQt4.sip --no-dist-info --no-tools`

**Comment by graysky2** [comment]
@finswimmer - Thanks.  https://aur.archlinux.org/packages/python-sip-pyqt4/ and all is well.

**Comment by nullx5** [comment]
I am on Ubuntu 22.04 and I get the same error, 

`$ python3 pyqt4.py  `

```                                                   
Traceback (most recent call last):
  File '/home/blessed/pyqt4.py', line 2, in <module>
    from PyQt4 import QtGui
ModuleNotFoundError: No module named 'PyQt4.sip'
```
I manually compile from pyqt4 source code, Unfortunately `python3 configure.py --sip-module PyQt4.sip --no-dist-info --no-tools`  It did NOT work for me. :(

**Comment by buhtz** [comment]
Version 4 of Qt is not supported anymore for a long time. Please use BIT from the official Ubuntu repos. Don't use PPA or the git repo if you don't have a good reason for it.
Please read https://github.com/bit-team/backintime?tab=readme-ov-file#installation

**Comment by nullx5** [comment]
After several trial and error attempts, I was able to install PyQt4 and Qt Designer on manjaro base arch linux. 😁 on Ubuntu I could NOT get it to work.

![PyQt4](https://github.com/user-attachments/assets/fef2f2d8-654c-46bc-adff-165bc8cc12bb)

**Comment by buhtz** [comment]
I don't get why you need version 4 of Qt?
Which version of Back In Time are you using? It must be quit out dated because the latest release 1.5.2 supported Qt version 6.

The last Back In Time version supporting Qt version 4 was 1.1.24 seven(!) years ago.
