### ISSUE TITLE
Scheduled backup not running

### ISSUE THREAD

**Issue by tobiz** [bit-team/backintime#966]

**Comment by tobiz** [comment]
Back in Time set to auto run on Kubuntu 18.04.  Using GUI, Settings/General/Schedule set to: Every Week/Weekday: Saturday/Hour: 12:00 result:- it doesn't run, why not?  If I select Snapshot/Take Snapshot it works ok.

**Comment by tobiz** [comment]
Closing this was a mistake

**Comment by emtiu** [comment]
Hi, thanks for your error report. We're sorting out old reports at the moment. Kindly tell us: Is this issue still relevant, or did you ever find a cause/solution?

**Comment by emtiu** [comment]
Closing, since the reporter is not responding and we can't reproduce.
