### ISSUE TITLE
Not Saving "Last backup" or whatever

### ISSUE THREAD

**Issue by FlailAway** [bit-team/backintime#967]
Mint 19.1, BIT 1.1.24
I had to use the recover and the only definition it fund had no "Last backup profile," or whatever was it that used to be below the last backup date on the destination.
Now when I try to run from the CLI I get , "Back in time is no configured." and it stops. 

I tried manually making a back up from the GUI and it ran but reported errors. But it did **not** create that "Last backup ..." so the CLI still insists it is not configured.

Here's the errors. The last two I have no idea where that is coming from as I have searched ALL of the backups in the "bit" chain of backups and they do not exist **and** they do not exist on the Acer-laptop. It seems like it is using an old or corrupted list of folders.

[E] Error: rsync: mknod "/media/drive-1/bit/backintime/acer/auser/1/new_snapshot/backup/home/auser/.config/VeraCrypt/.show-request-queue" failed: Input/output error (5)
[E] Error: rsync: symlink "/media/drive-1/bit/backintime/acer/auser/1/new_snapshot/backup/home/auser/.config/menus/cinnamon-applications-merged" -> "/home/auser/.config/menus/applications-merged" failed: Function not implemented (38)
[E] Error: rsync: mkstemp "/media/drive-1/bit/backintime/acer/auser/1/new_snapshot/backup/home/auser/.local/share/gvfs-metadata/.network:.123456" failed: No such file or directory (2)
[E] Error: rsync: mkstemp "/media/drive-1/bit/backintime/acer/auser/1/new_snapshot/backup/home/auser/.local/share/gvfs-metadata/.network:-123456678.log.123456" failed: No such file or directory (2)

**Comment by emtiu** [comment]
Closing as outdated. Feel free to reopen if you still need help.
