### ISSUE TITLE
Nocache option breaks backups

### ISSUE THREAD

**Issue by FuturePilot** [bit-team/backintime#968]
It appears using the "nocache" option breaks backups. With the "nocache" option enabled backups started automatically or manually hang indefinitely on "comparing with snapshot" with no disk activity at all. After I disabled the option, a manually started backup completed normally.

```
nocache:
  Installed: 1.0-1
  Candidate: 1.0-1
  Version table:
 *** 1.0-1 500
        500 http://mirror.us.leaseweb.net/ubuntu cosmic/universe amd64 Packages
        100 /var/lib/dpkg/status

backintime-qt4:
  Installed: 1.1.24a~cosmic
  Candidate: 1.1.24a~cosmic
  Version table:
 *** 1.1.24a~cosmic 500
        500 http://ppa.launchpad.net/bit-team/stable/ubuntu cosmic/main amd64 Packages
        500 http://ppa.launchpad.net/bit-team/stable/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
     1.1.24-0.1 500
        500 http://mirror.us.leaseweb.net/ubuntu cosmic/universe amd64 Packages
        500 http://mirror.us.leaseweb.net/ubuntu cosmic/universe i386 Packages
```

Kubuntu 18.10

**Comment by jdrch** [comment]
[Might not be broken](https://github.com/Feh/nocache/issues/22#issue-32529090). From that link it seems `rsync` is just running very slowly.

**Comment by buhtzz** [comment]
@FuturePilot There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, External, maybe a Bug

**Comment by FuturePilot** [comment]
> @FuturePilot There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?
> 
> Tag: Feedback, External, maybe a Bug

This seems to have been magically fixed at some point in the past.
