### ISSUE TITLE
Where is the config-file for the root-version?

### ISSUE THREAD

**Issue by xenongit** [bit-team/backintime#969]
I am running backintime (root) as well as the regular backintime (no root). I found the configuration files for the regular backintime profiles in ~/.config/backintime/config. Good. But I cannot find the configuration files for backintime (root); it is definitely NOT the same file as for the regular backintime. There is no folder /etc/backintime on my computer.  And I could not find any documentation on it either.

Please tell me where the settings for the backintime (root) are stored.

Thanks!
Xenon

**Comment by glyndon** [comment]
on mine, they are in /root/.config/backintime
(/root is user 'root's home directory)

**Comment by xenongit** [comment]
Indeed! I had not known that there *was* a home directory of "root". Thank you! That helped a lot.
