### ISSUE TITLE
Backintime used all my memory and locked up my system...

### ISSUE THREAD

**Issue by AKADAP** [bit-team/backintime#970]
I recently upgraded my system to mint 19.1 via a clean install. My home directory is on a separate drive that I soft link to, so its contents did not change.
I installed backintime, but it had forgotten the previous configuration. I restored the configuration from my backup disk, and tried to run a snapshot.
The compare took an extremely long time, and eventually used all of my memory (6 GB), and all of my swap space (2GB) at which point my computer locked up.
While this was happening I noticed that there were two r-sync tasks that showed up in the system monitor. both using what appears to be the same very long command line, both using exactly the same amount of memory (about half my RAM).
I got out a second drive that had a swap partition, connected it to my computer, and started it with the disks tool. This gave me 4 GB of swap space.
I ran the backup again, and it immediately started copying files after spending only seconds comparing files.
At this point I don't trust that it has done the comparison properly, and may not have properly backed up my system.
Is there a way to get backintime to re-do the comparison?
Is rsync safely saving its comparison results so that it can pickup where it left off?
Why does rsync need so much memory?

**Comment by ced75** [comment]
Hi,
I have exactly the same issue since few days.
I'm also using backintime on Mint 19.1. A top command shows that it is the rsync comparison that is consuming all the RAM.
I deleted the last completed backup, but it did not solve the problem.

**Comment by AKADAP** [comment]
I think I have a bit more info on this.
I bought more memory for my computer in an attempt to work around this issue. I quadrupled the amount of memory to 24 GB.
The effect of this is that it now ran four times longer, still used all the memory and locked up the computer. This time though, rebooting and trying again did not work.
The entire time, the only message in the application was that it was comparing the current state to the last snapshot.
It did not help that there were no messages in the log file.
On my third attempt, I deleted all the old snapshots and started seeing messages.
One looked like the same path was repeating. a link loop.
On my disk is a backup of the final state of my deceased fathers computer. In that backup was ".googleearth/instance_running-lock" which was a link to /proc/2314 (I don't remember the actual number, but I don't think it matters). I think what was happening was that sometimes, on some boots this link would point to an actual file that was a link back to the root file system. This created an infinite loop that would eventually use all of the memory and lock up the computer.
While running the backup I deleted this link, and backup continued without more errors (there is no way to stop the backup in progress without using the task manager). The backup ran for more than 12 hours before reporting done with errors. I tried to look at the log file, but the software could not find it. I found the log myself, and it was filled with errors about soft links more than 40 deep.
The reason this took so long to find is that there were no error messages.

**Comment by glyndon** [comment]
Infinite-depth link loops can be tricky for filesystem-traversing code to detect/handle without recursing itself into thrash-land. 
In this case, it sounds like it's rsync - not BiT - that's going nuts with it.
My way of avoiding this is to always exclude directories like /var/run, /var/lock, /dev, /proc, etc.
Basically anything that's composed of transient run-time-only stuff like those is not good to try to backup, as they are about the state of the machine and not the disk's content.

**Comment by buhtzz** [comment]
@AKADAP There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback, Bug, External, Discussion

Not sure if BIT should be able to detect link loops like this or to high memory usage.
