### ISSUE TITLE
Failed to take incremental snapshot on QNAP NAS - due to xattrs?

### ISSUE THREAD

**Issue by demaddis** [bit-team/backintime#973]
I recently transitioned to a QNAP NAS as a backup destination. The first snapshot ran fine, the following ones failed, with xattr-related errors in the log, e.g. for /etc:
```
[I] Take snapshot (rsync: rsync: get_xattr_names: llistxattr("etc",1024) failed: No such file or directory (2))
[E] Error: rsync: get_xattr_names: llistxattr("etc",1024) failed: No such file or directory (2)
```

I tried to run getfattr on /etc in the sshfs-mounted backup folder , which resulted in:
`Operation not supported`
So I'm assuming something is going wrong on that level. The backup folder on the NAS is located on a "Thick Volume", in case this is relevant.

I'd be thankful for any help or pointers.

System info: Back In Time 1.1.24 on Ubuntu 16.04

**Comment by buhtzz** [comment]
@demaddis There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback

**Comment by demaddis** [comment]
I don't have access to the hardware in question anymore, so unfortunately I can't give you an update.
