### ISSUE TITLE
How to cancel an ongoing process of taking a snapshot?

### ISSUE THREAD

**Issue by aritorhamo** [bit-team/backintime#976]
When configuring Back In Time, I accidentally included some files and folders that I don't want back up right now, because they include some very large files that I don't have enough space for on the target device. I already started the snapshot process, and would like to cancel it, but there seems to be no way to do that in the user interface. None of the buttons on the user interface do that, neither do any of the available menu items. I also tried to remove the specified folder from "Include", add another folder, and restart Back In Time. I also removed the related content in the config files, and finally removed the target folder on the back up device, but the process just keeps going on. Strangely the files and folders being copied don't seem to end up anywhere anymore after I removed the target folder, but the progress bar shows that the copying process is going forward, gigabyte after gigabyte and hour after hour (the process is slowish over USB 2). The "Browse log" button is greyed out, but the file takesnapshot_.log shows a growing list of supposedly backed up files. 

Is there any other way to handle the situation except complitely uninstalling and reinstalling Back In Time? I was going to do that right away, but thought that this situation perhaps deserves some attention, because other people might face it too. I wonder what might be the best way to proceed. Thanks!

**Comment by trendzetter** [comment]
a better workaround is killing the process. Use some process monitor like ksysguard

**Comment by Germar** [comment]
With Version 1.2.0 released today there are buttons to pause or stop a running snapshot. In previous versions you needed to kill the rsync and snapshot processes manually
