### ISSUE TITLE
Merging two config files

### ISSUE THREAD

**Issue by udopt** [bit-team/backintime#978]
I have two computers, each with a backintime profile. Both profiles are the main profile / profile1. Both computers have their settings stored at `~/.config/backintime/config`.

Now, I would like the have both profiles available at one of the computers. What would be the best way to merge to configs?

I assume that one could more or less concatenate the files with the settings, renaming one of the profiles from "profile1" to "profile2". Then, a line "profiles=1:2" should be added. Settings which are not profile specific should be included only once. Furthermore, it would probably be useful to add a name for the new profile2.

Is there anything else that should be cared for?

**Comment by Germar** [comment]
Sounds good for me. Didn't try it my self but it should work this way. Just make sure, the snapshot path with host / user / profile-id will work for both profiles into different destinations...
