### ISSUE TITLE
rsync parallel execution

### ISSUE THREAD

**Issue by andreaskemvise** [bit-team/backintime#979]
Is it possible to execute rsync in parallel during the backup? This speeds up the backup.

One option could be the parallel project or an option to set a "precommand" for rsync

example:
parallel -j 8 rsync .........

**Comment by Germar** [comment]
Nope, that won't work, sorry. Also the bottleneck is most likely harddrive IO and not single- vs. multithreading. If you throw more threads on a already busy harddrive you probably slow it down even more...
