### ISSUE TITLE
continue using existing snapshots

### ISSUE THREAD

**Issue by billyg599** [bit-team/backintime#983]
Hi,
So I moved by BIT backup folder to an external drive with rsync -avhH --info=progress2 /SOURCE /DESTINATION

I managed to import the backup folder to new Linux PC so that then new PC can see the old backups. Everything ok till now. Now I want to continue the backups so that I won't lose the old ones (it is the same folder that is being backed up), but I create new ones on top of them. The problem is that when I start to get a new snapshot the whole process is very slow and generates so much data that is way bigger than the folder that is being backed up. Do you have a by ideas what is happening or how can I find the problem?

**Comment by buhtzz** [comment]
@billyg599 There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Support, Documentation

And often upcoming question. There is something (but IMHO not enough) about it in the [FAQ](https://github.com/bit-team/backintime/wiki/FAQ)

**Comment by emtiu** [comment]
Yes, the likely solution is [here in the FAQ](https://github.com/bit-team/backintime/wiki/FAQ#back-in-time-doesn-t-find-my-old-snapshots-on-my-new-computer). Feel free to re-open this Issue is questions remain.
