### ISSUE TITLE
BackInTime changes screen lock password on restore.

### ISSUE THREAD

**Issue by Lukon100** [bit-team/backintime#984]
I’m doing a restore of my Ubuntu 16.xx partition.

Meanwhile, the screen has locked up, wanting me to authenticate. So I enter my password and it says my password is invalid.

Is this a temporary situation that will fix itself when the restore is complete?

But here’s the glitch: how do I know when the restore is complete if I can’t authenticate?

How can I know whether the restore has crashed?

I’m not even positive that BackInTime is doing anything right, as when I gave the command to restore, no status widgets appeared, but rather the interface window just grayed out. I guessed it was actually doing something when, a few minutes later, a few of my desktop icons appeared from the prior installation. That’s a good sign that at least my desktop icons are getting restored. But other than that, no clue.

So. I let it go on.

In the meantime, I switch my KVM switch to another computer to do other things. When I switch back to check on the restore process, I’m greeted by the screen-lock thing. So I authenticate to it and it lets me in. Great. There I see the same old grayed out BackInTime window. No clue about the progress. So I switch back to the other computer. Then switch back to the restoring computer some time later. This time the screen-lock thing rejects my password. And hence the question at the top of this post.

I’m not even sure I’m using BackInTime correctly. Was I really supposed to restore my old installation to replace my fresh new installation while booted into that fresh new installation? I mean, it didn’t protest my doing this so long as I used the version of it called “As root”. So here it is overwriting the very system it is running from. I hope it can do this and get things right.

**Comment by emtiu** [comment]
Closing as outdated. Feel free to re-open if questions remain.
