### ISSUE TITLE
Enhancement request: Email notification in GUI

### ISSUE THREAD

**Issue by omgdz** [bit-team/backintime#985]
Would it be possible to add a tab to the GUI to configure email notification?
I'd be interested in "not backed up after xx days", "backup completed successfully", and "backup terminated with errors, log attached"
Thanks

**Comment by Germar** [comment]
This can be done with `user-callback`. Take a look at these examples: [user-callback.sendmail](https://github.com/bit-team/user-callback/blob/master/user-callback.sendmail) or [user-callback.notify](https://github.com/bit-team/user-callback/blob/master/user-callback.notify)
