### ISSUE TITLE
Log to separate file - update

### ISSUE THREAD

**Issue by DecoDogs** [bit-team/backintime#986]
re: #766, May, 2017: https://github.com/bit-team/backintime/issues/766
(and, I see, an even earlier conversation, #174, Oct, 2015: https://github.com/bit-team/backintime/issues/174)

Current: BiT 1.1.12; Linux Mint 19.1 (Ubuntu 18.04)

The advice given on sending BiT logs to a separate file seems to need an update.  (I'm sure there must be many different ways of accomplishing this.)

/etc/rsyslog.conf ends with
$IncludeConfig /etc/rsyslog.d/*.conf

If the BiT config file is named "**80**-backintime.conf", then it will be processed AFTER the "**50**-default.conf", thus sending the logs to BOTH /var/log/syslog and the specified BiT log file.  Naming it, say, "**30**-backintime.conf" (and making sure that the "& stop" at the end is NOT commented") produces the desired behavior - BiT logs to and only to the specified file.

Ed

**Comment by emtiu** [comment]
Thanks for the tip, I'm closing this in Issue favor of keeping the discussion in #174.
