### ISSUE TITLE
How to move previously excluded folder into last snapshot?

### ISSUE THREAD

**Issue by Elbchillharmonie** [bit-team/backintime#987]
Hi there,

I have a question: I previously excluded a huge folder from my backintime profile which backups my laptop to a server. I have separate backups of this folder on my server. Now, I would like to add it back to my profile, but I'd like to avoid that all files are synced again between laptop and server. Can I somehow copy the previously excluded folder into the last snapshot, so only the differences are synced without corrupting my profile?

**Comment by Germar** [comment]
You can create a new snapshot and then manually copy the folder from last snapshot before you excluded it into the new snapshot with `cp -aRl SOURCE DESTINATION`. This will create hard-links for the files inside your new snapshot. Then remove the exclude and run a new snapshot again to sync the changes to the folder. Finally you should remove the overlast snapshot in which you manually linked the excluded folder

**Comment by emtiu** [comment]
Closing as done (question was answered).
