### ISSUE TITLE
backup consistency for a running server ?

### ISSUE THREAD

**Issue by GeraldSoellinger** [bit-team/backintime#992]
Dear BackInTime -team!

Your tool looks very good, thanks for sharing! I could not find in the documentation some information to judge if it suits to my needs. 

Can Back In Time handle situations as described here ->
http://www.system-rescue-cd.org/lvm-guide-en/Making-consistent-backups-with-LVM/

In particular I am running a nextcloud server and want to do a backup without (huge) downtime of the server.
I may add other services in the future like an email-server etc.

**Comment by buhtzz** [comment]
@GeraldSoellinger There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

I have not read the link you provided. But BIT does use rsync in the back. It should be possible I assume.

Tag: Feedback, Support

**Comment by emtiu** [comment]
Hi, thanks for your question. backintime does not support LVM operations, or LVM-style atomic backups. By design, it works by running rsync, which is _not_ atomic in the way described above.
