### ISSUE TITLE
Files not being deleted from backup when deleted from source

### ISSUE THREAD

**Issue by colinl** [bit-team/backintime#993]
Running version 1.2 from bit stable ppa on Ubuntu 19.04
If I delete files from the source and run a snapshot it does not delete the files from the backup.  The files do not show as deleted in the log.  If all I have done is delete some files then it says that no snapshot is necessary.

**Comment by monsta** [comment]
Have you checked the actual files? I see the same after upgrading from 1.1.24 to 1.2.0, but when I've checked the snapshots, the files I've deleted really aren't there.

**Comment by monsta** [comment]
Looks like it's the same commit with radical changes that we already know: https://github.com/bit-team/backintime/commit/a6a4d523ea45ecec9f36f85ed50209322dbc93ce. It's the first rsync pass with `--dry-run` option that made "deleting..." entries appear in the log. That pass was removed in that commit.

**Comment by buhtzz** [comment]
@colinl There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Bug

Duplicate of #988

**Comment by emtiu** [comment]
Closing as duplicate of https://github.com/bit-team/backintime/issues/136.
