### ISSUE TITLE
Linux: How to start application?

### ISSUE THREAD

**Issue by gitman23** [bit-team/backintime#995]
Using Fedora 30 I just installed backintime. Wonder how to start the application. In the applications menue it's not listed, as well not under software. If I go in the shell into the backintime folder I don't see a file to start the application (or better said I don't know what file).

Help appreciated. Thanks!

**Comment by hannes101** [comment]
How did you install the application? It should be available via the repositories and it also should be available in the menus.
If installed via dnf or the package management the command to execute backintime is:
`backintime-qt`

**Comment by gitman23** [comment]
Installed via dnf and using gnome, but now working. 
After entering "backintime-qt" it asked me if I want to install and I said yes.
So had this as well with another application that it suddenly disappeared and I needed to install again. Either this is a F30 bug or I did something too late in the night.
Nevertheless, your comment helped, thanks a lot!

**Comment by hannes101** [comment]
I don't really know how the installation is done in the GUI under Gnome. I usually just do everything on the commandline and in Xfce it just works. 
But good, that it's fixed and I didn't make a mistake in packaging ;-)
