### ISSUE TITLE
rsync command with no reaction

### ISSUE THREAD

**Issue by erich-s** [bit-team/backintime#997]
My Systems/Versions:
Synology Diskstation 218+ with DSM 6.2.1-23824 Update 6
sshfs 2.9
FUSE library version: 2.9.7
Backintime 1.1.24
OpenSuse Leap 15 64-bit

I try to make a backup of my home directory on Linux to the Synology NAS. Login in using RSA keys and mouting the filesystem works. But the backup does not start. In the Log I can see the rsync command (see attachment) but nothing happens.
Need advice please, I'm a Linux beginner.
[takesnapshot_3.log](https://github.com/bit-team/backintime/files/3170014/takesnapshot_3.log)

**Comment by Germar** [comment]
It may take some time until rsync start to sync depending on the size of your source. Maybe try with a little subfolder of your home to try out first

**Comment by erich-s** [comment]
I created a new profile (4) and included a different directory (home/erich/Arbeit) which is 12 MB (the one in profile 3 "Anleitungen" was 485 MB). But still even after 20 minutes no backup started but the directories have been created locally and on the NAS. The private keyfile I use (bit28) has a passphrase which I entered in the BIT Gui.  Please find the log for profile 4 attached.
[takesnapshot_4.log](https://github.com/bit-team/backintime/files/3194016/takesnapshot_4.log)

**Comment by erich-s** [comment]
Since I've installed BIT the option "Passwort in Schlüsselbund speichern" is greyed out. Now I use a different rsa key with no passphrase and now the backup works.

**Comment by buhtzz** [comment]
@erich-s There is a new forming maintaining team and we do review all issues. Is this problem still relevant for you, can you reproduce it with a newer or the latest release? Did you find a solution?

Tag: Feedback

**Comment by erich-s** [comment]
Hi, thanks for asking. This issue is resolved, I'll close the ticket.
Best regards, Erich
